website/tsconfig.json

Enable MDX type hints:
https://github.com/mdx-js/mdx-analyzer?tab=readme-ov-file#typescript

chore(workflow): enable MDX type hints

---

packages/core/modern.config.ts

The modern.js module-tools `afterBuild` hook is not being called when we run rsbuild/core dev (`modern build --watch`).
we can use `transform` hook during build process instead of `afterBuild` 
https://modernjs.dev/module-tools/en/guide/advance/in-depth-about-build.html#transform

chore: fix can't find compiled module when run dev in core

---

packages/plugin-pug/package.json
pnpm-lock.yaml

Bump pug and fix security alert: https://github.com/web-infra-dev/rsbuild/security/dependabot/12

fix(plugin-pug): bump pug and fix security alert

---

website/docs/en/config/dev/start-url.mdx
website/docs/zh/config/dev/start-url.mdx

Improve the `startUrl` config guide.

docs: improve startUrl config guide

---

packages/create-rsbuild/src/index.ts
website/docs/en/guide/start/quick-start.mdx
website/docs/zh/guide/start/quick-start.mdx

Allow to create new Rsbuild project in the current folder and override files.

feat(create-rsbuild): allow to create in the current folder

---

packages/core/package.json
packages/plugin-react/package.json
packages/shared/package.json
pnpm-lock.yaml

Bump Rspack v0.7.0.
https://github.com/web-infra-dev/rspack/releases/tag/v0.7.0

feat: bump Rspack v0.7.0

---

website/rspress.config.ts

docs: OG image is broken

---

website/docs/en/community/releases/v0-7.mdx
website/docs/zh/community/releases/v0-7.mdx

Improve the v0.7 announcement, align with Rspack.

docs: improve v0.7 announcement

---

packages/core/src/cli/commands.ts
packages/core/src/helpers.ts

Check if dist folder is empty before previewing:

feat: check if dist folder is empty before previewing

---

website/docs/en/guide/faq/exceptions.mdx
website/docs/en/plugins/list/plugin-less.mdx
website/docs/zh/guide/faq/exceptions.mdx
website/docs/zh/plugins/list/plugin-less.mdx

Move Less FAQ to plugin-less document.

docs: move Less FAQ to plugin-less document

---

website/docs/en/plugins/list/plugin-less.mdx
website/docs/zh/plugins/list/plugin-less.mdx

Fix lessOptions example in plugin-less document.

docs(plugin-less): fix lessOptions example

---

e2e/cases/output/manifest/index.test.ts
website/docs/en/config/output/manifest.mdx
website/docs/zh/config/output/manifest.mdx

Add custom manifest path example and E2E case.

docs: add custom manifest path example

---

packages/plugin-typed-css-modules/src/loader.ts

Change webpack to Rsbuild, make the error message correct.

fix(typed-css-modules): change webpack to Rsbuild

---

website/docs/en/guide/migration/webpack.mdx
website/docs/zh/guide/migration/webpack.mdx

Reorganize the webpack migration guide, improve the "Configuration Migration" part.

docs: reorganize the webpack migration guide

---

packages/core/package.json
packages/core/prebundle.config.mjs
packages/plugin-source-build/package.json
packages/plugin-source-build/src/common/pnpm.ts
packages/shared/package.json
packages/shared/prebundle.config.mjs
pnpm-lock.yaml

Update dependency postcss-load-config to v6 and update some yaml configs.
close https://github.com/web-infra-dev/rsbuild/pull/2491

chore(deps): update dependency postcss-load-config to v6

---

e2e/cases/plugin-api/plugin-hooks/index.test.ts
e2e/cases/plugin-api/plugin-modify-tags/index.test.ts
e2e/cases/plugin-api/plugin-modify-tags/myPlugin.ts
e2e/cases/plugin-api/plugin-modify-tags/rsbuild.config.ts
packages/core/src/rspack/HtmlBasicPlugin.ts
packages/shared/src/types/hooks.ts
website/docs/en/plugins/dev/hooks.mdx
website/docs/zh/plugins/dev/hooks.mdx

Expose `assetPrefix` and `filename` for modifyHTMLTags hook.

feat: expose assetPrefix for modifyHTMLTags hook

---

e2e/cases/react/react-compiler-babel/package.json
pnpm-lock.yaml

bump react 19.0.0-rc.0
https://x.com/acdlite/status/1797668537349328923

chore(deps): bump react 19.0.0-rc.0

---

e2e/cases/sri/algotithm/index.test.ts
e2e/cases/sri/algotithm/rsbuild.config.ts
e2e/cases/sri/algotithm/src/index.css
e2e/cases/sri/algotithm/src/index.js
e2e/cases/sri/basic/index.test.ts
e2e/cases/sri/basic/rsbuild.config.ts
e2e/cases/sri/basic/src/index.css
e2e/cases/sri/basic/src/index.js
e2e/cases/sri/enable-dev/index.test.ts
e2e/cases/sri/enable-dev/rsbuild.config.ts
e2e/cases/sri/enable-dev/src/index.css
e2e/cases/sri/enable-dev/src/index.js

Add E2E cases for security.sri.
https://github.com/web-infra-dev/rsbuild/pull/2499

test(e2e): add cases for security.sri

---

packages/core/package.json
packages/plugin-react/package.json
packages/shared/package.json
pnpm-lock.yaml
website/package.json

feat(deps): bump Rspack v0.7.1

---

website/docs/en/config/output/filename.mdx
website/docs/zh/config/output/filename.mdx

Add filename query hash example.
https://github.com/web-infra-dev/rsbuild/issues/2044

docs: add filename query hash example

---

biome.json
website/docs/en/guide/basic/server.mdx
website/docs/en/guide/migration/webpack.mdx
website/docs/zh/guide/basic/server.mdx
website/docs/zh/guide/migration/webpack.mdx

Add dev server comparison to help users migrating dev server configs.

docs: add dev server comparison

---

scripts/dictionary.txt
website/docs/en/guide/advanced/module-federation.mdx
website/docs/zh/guide/advanced/module-federation.mdx

Update the module federation guide.
same as https://github.com/web-infra-dev/rspack/pull/6746

docs: update module federation guide

---

.github/workflows/release-nightly.yml
.github/workflows/release.yml

Remove duplicated pnpm install in the release CI.

chore(CI): remove duplicated pnpm install

---

website/docs/en/api/javascript-api/core.mdx
website/docs/zh/api/javascript-api/core.mdx

docs: add tip for load env mode

---

website/docs/en/config/source/define.mdx
website/docs/en/guide/advanced/env-vars.mdx
website/docs/zh/config/source/define.mdx
website/docs/zh/guide/advanced/env-vars.mdx

Add some bad cases of define replacement, because it is often used incorrectly.

docs: add some bad cases of define replacement

---

e2e/cases/glob-import/index.test.ts
e2e/cases/glob-import/rsbuild.config.ts
e2e/cases/glob-import/src/App.jsx
e2e/cases/glob-import/src/components/Footer.jsx
e2e/cases/glob-import/src/components/Header.jsx
e2e/cases/glob-import/src/index.js

Add E2E case for glob import
https://github.com/web-infra-dev/rspack/pull/6751

feat(e2e): add case for glob import

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/plugin-assets-retry/package.json
packages/plugin-css-minimizer/package.json
packages/plugin-image-compress/package.json
packages/plugin-lightningcss/src/minimizer.ts
packages/plugin-mdx/package.json
packages/plugin-source-build/package.json
packages/plugin-umd/package.json
packages/plugin-vue2-jsx/package.json
packages/plugin-vue2-jsx/tsconfig.json
pnpm-lock.yaml

Remove unused dependencies and devDependencies, found by knip.
https://github.com/webpro-nl/knip

chore: remove unused dependencies

---

packages/create-rsbuild/package.json
packages/create-rsbuild/src/index.ts
packages/create-rsbuild/template-prettier/.prettierrc
packages/create-rsbuild/template-prettier/extra-package.json
pnpm-lock.yaml

Allow to add prettier as formatter:

feat(create-rsbuild): allow to add prettier as formatter

---

packages/create-rsbuild/src/index.ts
packages/create-rsbuild/template-biome/biome.json
packages/create-rsbuild/template-biome/extra-package.json
packages/create-rsbuild/template-preact-ts/src/index.tsx
packages/create-rsbuild/template-react-ts/src/index.tsx
packages/create-rsbuild/template-solid-ts/src/index.tsx

Allow to add Biome as formatter and linter.
https://github.com/biomejs/biome

feat(create-rsbuild): allow to add Biome

---

packages/create-rsbuild/template-svelte-js/src/index.js
packages/create-rsbuild/template-svelte-ts/package.json
packages/create-rsbuild/template-svelte-ts/src/index.ts

Add svelte-check for svelte TS project.
https://www.npmjs.com/package/svelte-check

feat(create-rsbuild): add svelte-check for svelte TS project

---

website/docs/zh/plugins/list/plugin-svgr.mdx

docs: remove duplicated comma in plugin-svgr.mdx

---

website/docs/en/guide/start/quick-start.mdx
website/docs/zh/guide/start/quick-start.mdx

Add optional tools to quick start guide.

docs: add optional tools to quick start

---

website/docs/en/config/tools/bundler-chain.mdx
website/docs/en/config/tools/rspack.mdx
website/docs/en/guide/basic/configure-rspack.mdx
website/docs/zh/config/tools/bundler-chain.mdx
website/docs/zh/config/tools/rspack.mdx
website/docs/zh/guide/basic/configure-rspack.mdx

docs: add configuring Rspack tips

---

website/docs/en/guide/migration/_meta.json
website/docs/en/guide/migration/vite.mdx
website/docs/en/guide/start/quick-start.mdx
website/docs/zh/guide/migration/_meta.json
website/docs/zh/guide/migration/vite.mdx
website/docs/zh/guide/start/quick-start.mdx

Provide a basic Vite migration guide.

docs: vite migration guide

---

packages/core/package.json
packages/plugin-react/package.json
packages/shared/package.json
pnpm-lock.yaml
website/package.json

feat(deps): bump Rspack v0.7.2

---

e2e/cases/output/copy/index.test.ts
website/docs/en/config/output/copy.mdx
website/docs/zh/config/output/copy.mdx

- improve output.copy examples
- link to [rspack.CopyRspackPlugin](https://rspack.dev/plugins/rspack/copy-rspack-plugin)

docs: improve output.copy examples

---

.changeset/beige-bags-refuse.md
packages/core/package.json
packages/core/tests/__snapshots__/default.test.ts.snap
packages/plugin-react/package.json
packages/shared/package.json
pnpm-lock.yaml

https://github.com/web-infra-dev/rspack/releases/tag/v0.7.3

feat(deps): bump rspack to 0.7.3

---

scripts/dictionary.txt
website/docs/en/plugins/list/plugin-vue-jsx.mdx
website/docs/en/plugins/list/plugin-vue2-jsx.mdx
website/docs/zh/plugins/list/plugin-vue-jsx.mdx
website/docs/zh/plugins/list/plugin-vue2-jsx.mdx

Add Vue SFC JSX guide.
close https://github.com/web-infra-dev/rsbuild/issues/2599

docs: add Vue SFC JSX guide

---

website/docs/en/guide/migration/vite.mdx
website/docs/zh/guide/migration/vite.mdx

Add migration guide for glob imports.
https://www.rspack.dev/api/modules/module-variables#importmetawebpackcontext

docs: glob imports migration

---

website/docs/en/plugins/list/plugin-css-minimizer.mdx
website/docs/zh/plugins/list/plugin-css-minimizer.mdx

docs: fix broken cssnano link

---

packages/compat/webpack/src/shared.ts
packages/compat/webpack/src/webpackConfig.ts
packages/core/src/configChain.ts
packages/core/src/internal.ts
packages/core/src/provider/rspackConfig.ts
packages/core/tests/external.test.ts
packages/shared/src/chain.ts

Move the rspack chain helpers to core.

chore: move rspack chain helpers to core

---

.changeset/lazy-toys-shop.md
packages/core/package.json
packages/plugin-react/package.json
packages/shared/package.json
pnpm-lock.yaml

feat(deps): bump Rspack 0.7.4

---

packages/core/src/config.ts

Make load config function more general in upper-class framework usage.

chore: modify error message in loadconfig

---

packages/compat/webpack/src/webpackConfig.ts
packages/core/src/index.ts
packages/core/src/plugins/css.ts
packages/core/src/plugins/entry.ts
packages/core/src/plugins/html.ts
packages/core/src/plugins/resolve.ts
packages/core/src/plugins/swc.ts
packages/core/src/provider/rspackConfig.ts
packages/core/src/reduceConfigs.ts
packages/core/tests/reduceConfigs.test.ts
packages/plugin-babel/src/helper.ts
packages/plugin-css-minimizer/src/index.ts
packages/plugin-less/src/index.ts
packages/plugin-lightningcss/src/plugin.ts
packages/plugin-pug/src/index.ts
packages/plugin-sass/src/index.ts
packages/plugin-sass/src/types.ts
packages/plugin-styled-components/src/index.ts
packages/plugin-stylus/src/index.ts
packages/plugin-type-check/src/index.ts
packages/shared/src/index.ts
packages/shared/src/types/config/html.ts
packages/shared/src/types/config/source.ts
packages/shared/src/types/config/tools.ts
packages/shared/src/types/utils.ts
website/docs/en/api/javascript-api/core.mdx
website/docs/zh/api/javascript-api/core.mdx

Expose `reduceConfigs` and `reduceConfigsWithContext` helpers as public API.

feat: expose `reduceConfigs` helper

---

website/docs/en/config/output/override-browserslist.mdx
website/docs/en/guide/advanced/browserslist.mdx
website/docs/zh/config/output/override-browserslist.mdx
website/docs/zh/guide/advanced/browserslist.mdx

Add document for overriding browserslist by environment.
https://github.com/web-infra-dev/rsbuild/pull/2646

docs: override browserslist by environment

---

packages/compat/webpack/src/plugin.ts
packages/core/src/plugins/basic.ts
packages/core/src/plugins/css.ts
packages/core/src/plugins/resolve.ts
packages/core/src/plugins/splitChunks.ts
packages/core/src/types.ts
packages/plugin-css-minimizer/src/index.ts
packages/plugin-less/src/index.ts
packages/plugin-lightningcss/src/plugin.ts
packages/plugin-react/src/react.ts
packages/plugin-react/src/splitChunks.ts
packages/plugin-rem/src/index.ts
packages/plugin-solid/src/index.ts
packages/plugin-stylus/src/index.ts
packages/plugin-svelte/src/index.ts
packages/plugin-svgr/src/index.ts
packages/plugin-vue-jsx/src/index.ts
packages/plugin-vue/src/splitChunks.ts
packages/plugin-vue2/src/splitChunks.ts

More environment configurations can be used in rsbuild builtin plugins.

feat: support apply more environment configs

---

CONTRIBUTING.md
README.md
README.zh-CN.md
website/docs/en/community/releases/index.mdx
website/docs/zh/community/releases/index.mdx

Update the releases page for 1.0 release:
- `main` branch -> Rsbuild v1.x
- `v0.x` branch -> Rsbuild v0.x

docs: update releases page for 1.0 release

---

website/docs/en/guide/framework/_meta.json
website/docs/en/guide/framework/preact.mdx
website/docs/zh/guide/framework/_meta.json
website/docs/zh/guide/framework/preact.mdx

docs: add guide for Preact

---

packages/core/src/plugins/lazyCompilation.ts
packages/shared/src/types/config/index.ts
website/docs/en/config/environments.mdx
website/docs/zh/config/environments.mdx

Should allow to configure some dev options in environments config.

types: allow to configure dev in environments

---

packages/core/src/mergeConfig.ts
website/docs/en/api/javascript-api/instance.mdx
website/docs/en/config/output/target.mdx
website/docs/en/guide/advanced/browserslist.mdx
website/docs/en/guide/basic/output-files.mdx
website/docs/en/plugins/dev/core.mdx
website/docs/en/shared/onBeforeBuild.mdx
website/docs/en/shared/onBeforeCreateCompiler.mdx
website/docs/zh/api/javascript-api/instance.mdx
website/docs/zh/config/output/target.mdx
website/docs/zh/config/source/entry.mdx
website/docs/zh/config/tools/bundler-chain.mdx
website/docs/zh/config/tools/rspack.mdx
website/docs/zh/guide/advanced/browserslist.mdx
website/docs/zh/guide/basic/output-files.mdx
website/docs/zh/plugins/dev/core.mdx
website/docs/zh/shared/onBeforeBuild.mdx
website/docs/zh/shared/onBeforeCreateCompiler.mdx

Update document for `output.target`.

docs: update document for `output.target`

---

README.md
README.zh-CN.md

Update badge links in README, should link to `@rsbuild/core`.

docs: update badge links in README

---

website/docs/en/guide/migration/webpack.mdx

Updated instructions to be consistent with script section
Minor text update
- [ x] Tests updated (or not required).
- [ x] Documentation updated (or not required).

docs: update dev command in webpack.mdx

---

README.md
README.zh-CN.md
packages/plugin-sass/src/types.ts

Fix sass-loader's additionalData function type.
close https://github.com/web-infra-dev/rsbuild/issues/2582

fix(plugin-sass): additionalData function type

---

README.md
README.zh-CN.md
website/docs/en/community/releases/v0-1.mdx
website/docs/en/config/performance/bundle-analyze.mdx
website/docs/en/guide/advanced/browserslist.mdx
website/docs/en/guide/faq/hmr.mdx
website/docs/en/guide/optimization/optimize-bundle.mdx
website/docs/en/guide/start/index.mdx
website/docs/zh/community/releases/v0-1.mdx
website/docs/zh/config/performance/bundle-analyze.mdx
website/docs/zh/guide/advanced/browserslist.mdx
website/docs/zh/guide/faq/hmr.mdx
website/docs/zh/guide/optimization/optimize-bundle.mdx
website/docs/zh/guide/start/index.mdx

Update assets URLs, prefer using <https://assets.rspack.dev>

docs: update assets URLs

---

package.json
packages/core/package.json
packages/core/src/plugins/sri.ts
packages/core/tests/__snapshots__/builder.test.ts.snap
packages/core/tests/__snapshots__/css.test.ts.snap
packages/core/tests/__snapshots__/default.test.ts.snap
packages/core/tests/minimize.test.ts
packages/plugin-less/tests/__snapshots__/index.test.ts.snap
packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
packages/plugin-react/package.json
packages/plugin-react/tests/__snapshots__/index.test.ts.snap
packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
packages/plugin-typed-css-modules/tests/__snapshots__/index.test.ts.snap
packages/shared/package.json
pnpm-lock.yaml

bump Rspack 1.0 alpha version, see: https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-alpha.0

feat(deps)!: bump Rspack 1.0 alpha

---

packages/core/src/plugins/progress.ts
packages/shared/src/types/config/index.ts
website/docs/en/config/environments.mdx
website/docs/zh/config/environments.mdx

Allow to configure progress bar by environment.

feat: allow to configure progress bar by environment

---

packages/compat/plugin-swc/src/plugin.ts
packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
packages/core/src/constants.ts
packages/core/src/plugins/fileSize.ts
packages/core/src/plugins/inlineChunk.ts
packages/core/src/plugins/splitChunks.ts
packages/core/src/plugins/swc.ts
packages/plugin-check-syntax/src/CheckSyntaxPlugin.ts
packages/plugin-type-check/src/index.ts
packages/plugin-typed-css-modules/src/loader.ts
packages/shared/src/index.ts
scripts/test-helper/src/rsbuild.ts

The `applyScriptCondition` helper is moved to core as an internal helper.

chore: remove script condition helper from shared

---

packages/plugin-image-compress/package.json
packages/plugin-image-compress/src/minimizer.ts
pnpm-lock.yaml

Prefer using Rspack types instead of webpack.

fix(image-compress): prefer using Rspack types

---

packages/core/src/plugins/swc.ts

fix: error message in decorator

---

e2e/cases/vue/sfc-basic/index.test.ts
e2e/cases/vue/sfc-basic/src/A.vue
e2e/cases/vue2/sfc-basic/index.test.ts
e2e/cases/vue2/sfc-basic/src/A.vue
packages/plugin-vue2/src/index.ts
packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap
packages/plugin-vue2/tests/index.test.ts

fix(plugin-vue2): apply js resolve config to vue2 sfc template

---

e2e/cases/performance/print-file-size/index.test.ts
packages/core/src/plugins/fileSize.ts

feat: prettier print file size log

---

README.md
README.zh-CN.md
website/docs/en/plugins/list/_meta.json
website/docs/zh/plugins/list/_meta.json

Remove underlines between badges.

docs: remove underlines between badges

---

website/docs/en/guide/advanced/_meta.json
website/docs/en/guide/advanced/environments.mdx
website/docs/zh/guide/advanced/_meta.json
website/docs/zh/guide/advanced/environments.mdx

docs: add basic environments guide

---

packages/core/package.json

fix(core): incorrect Rspack version

---

packages/compat/webpack/src/webpackConfig.ts
packages/compat/webpack/tests/__snapshots__/environment.test.ts.snap
packages/compat/webpack/tests/environment.test.ts
packages/core/src/configChain.ts
packages/core/src/provider/rspackConfig.ts
packages/core/tests/__snapshots__/environments.test.ts.snap
packages/core/tests/environments.test.ts

fix: tools.rspack / bundlerChain can be used in environment config

---

packages/compat/plugin-swc/modern.config.ts
packages/compat/plugin-swc/package.json

Fix the type issue with moduleResolution node16+.

fix(plugin-swc): type issue with moduleResolution node16+

---

packages/core/src/config.ts
packages/core/src/helpers.ts
packages/core/src/plugins/output.ts
packages/core/src/provider/initConfigs.ts
packages/core/tests/__snapshots__/environments.test.ts.snap
packages/core/tests/__snapshots__/output.test.ts.snap
packages/core/tests/output.test.ts
packages/shared/src/types/config/index.ts
packages/shared/src/types/config/output.ts
website/docs/en/config/output/dist-path.mdx
website/docs/en/config/output/filename.mdx
website/docs/zh/config/output/dist-path.mdx
website/docs/zh/config/output/filename.mdx

Rsbuild output config should works when target is node.
fix: https://github.com/web-infra-dev/rsbuild/issues/2787

fix: output config should works when target is node

---

package.json
packages/core/package.json
packages/core/src/plugins/rspackProfile.ts
packages/core/tests/__snapshots__/default.test.ts.snap
packages/core/tests/minimize.test.ts
packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
packages/plugin-react/package.json
packages/plugin-react/tests/__snapshots__/index.test.ts.snap
pnpm-lock.yaml

bump Rspack 1.0.0-alpha.1
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-alpha.1

feat(deps): bump Rspack 1.0.0-alpha.1

---

packages/core/src/config.ts

Prefer to use dynamic import to load config, this can make loading `.js` `.mjs` `.cjs` config 100ms faster.

perf: prefer using dynamic import to load config

---

packages/compat/babel-preset/package.json
packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-check-syntax/package.json
packages/plugin-image-compress/package.json
packages/plugin-less/package.json
packages/plugin-lightningcss/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-rem/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-source-build/package.json
packages/plugin-styled-components/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-typed-css-modules/package.json
packages/plugin-umd/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
packages/plugin-vue2-jsx/package.json
packages/plugin-vue2/package.json
scripts/config/package.json
scripts/test-helper/package.json

* feat(deps): bump Rspack 1.0.0-alpha.1 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2803
* perf: prefer using dynamic import to load config by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2809
* perf!: disable polyfill injection by default by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2804
* docs: add get environment context info guide by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/2796
* chore: move css minimizer plugin to separate repo by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2801
* chore: move eslint plugin to separate repo by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2805
* chore(deps): update dependency ws to ^8.18.0 by @renovate in …

release: 1.0.0-alpha.4

---

e2e/cases/lazy-compilation/add-initial-chunk/index.test.ts
e2e/cases/lazy-compilation/add-initial-chunk/rsbuild.config.ts
e2e/cases/lazy-compilation/add-initial-chunk/src/index.js
e2e/cases/lazy-compilation/add-initial-chunk/src/initial.js
packages/core/src/server/socketServer.ts

beyond webpack
https://github.com/web-infra-dev/rspack/issues/6633

fix: hmr failed when adding initial chunk

---

e2e/cases/server/ssr/rsbuild.config.ts
packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
packages/core/src/plugins/splitChunks.ts
packages/core/tests/__snapshots__/builder.test.ts.snap
packages/core/tests/__snapshots__/default.test.ts.snap
packages/core/tests/__snapshots__/environments.test.ts.snap
packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
packages/core/tests/__snapshots__/splitChunks.test.ts.snap
packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
packages/plugin-babel/tests/index.test.ts
packages/plugin-react/src/splitChunks.ts
packages/plugin-react/tests/__snapshots__/features.test.ts.snap
packages/plugin-react/tests/__snapshots__/index.test.ts.snap
packages/plugin-vue/src/splitChunks.ts
packages/plugin-vue2/src/splitChunks.ts
website/docs/en/config/performance/chunk-split.mdx
website/docs/en/config/source/include.mdx
website/docs/en/config/source/transform-import.mdx
website/docs/en/guide/advanced/browser-compatibility.mdx
website/docs/zh/config/performance/chunk-split.mdx
website/docs/zh/config/source/include.mdx
website/docs/zh/config/source/transform-import.mdx
website/docs/zh/guide/advanced/browser-compatibility.mdx

Simplify node_modules related RegExps, remove the leading slash.

perf: simplify node_modules RegExps

---

package.json
packages/core/package.json
packages/plugin-react/package.json
pnpm-lock.yaml

bump Rspack 1.0.0-alpha.2
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-alpha.2
https://github.com/web-infra-dev/rsbuild/issues/2819

feat(deps): bump Rspack 1.0.0-alpha.2

---

packages/core/src/server/devServer.ts
packages/core/src/types/config/dev.ts
website/docs/en/api/javascript-api/instance.mdx
website/docs/en/config/dev/setup-middlewares.mdx
website/docs/en/guide/advanced/environments.mdx
website/docs/zh/api/javascript-api/instance.mdx
website/docs/zh/config/dev/setup-middlewares.mdx
website/docs/zh/guide/advanced/environments.mdx

add environment api basic guide.
#2620

docs: add environment api basic guide

---

website/rspress.config.ts

The same as https://github.com/web-infra-dev/rspack/pull/7074

docs: baidu SEO verification

---

scripts/dictionary.txt
website/docs/en/guide/basic/html-template.mdx
website/docs/en/guide/basic/json-files.mdx
website/docs/zh/guide/basic/html-template.mdx
website/docs/zh/guide/basic/json-files.mdx
website/rspress.config.ts

Add HTML minify guide.
https://github.com/web-infra-dev/rsbuild/pull/2833

docs: HTML minify guide

---

packages/core/src/index.ts
packages/core/src/internal.ts

Export some types for use by high-level frameworks (such as Modern.js).

chore: export some types for use 

---

e2e/cases/module-federation/index.test.ts
e2e/cases/module-federation/remote/moduleFederation.config.ts
e2e/cases/module-federation/remote/src/App.js
e2e/cases/module-federation/remote/src/Button.js
packages/core/src/plugins/moduleFederation.ts
packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
website/docs/en/config/module-federation/options.mdx
website/docs/zh/config/module-federation/options.mdx

Set uniqueName for module federation HMR.
- https://github.com/module-federation/core/issues/2316
- resolve https://github.com/web-infra-dev/rsbuild/discussions/2802

feat: set uniqueName for module federation HMR

---

packages/core/src/types/utils.ts
packages/plugin-babel/src/helper.ts
packages/plugin-babel/src/index.ts

chore: clear some useless utils

---

website/docs/en/plugins/list/plugin-check-syntax.mdx
website/docs/zh/plugins/list/plugin-check-syntax.mdx

Add limitations of check syntax plugin.

docs: add check syntax limitations

---

packages/compat/babel-preset/package.json
packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-check-syntax/package.json
packages/plugin-image-compress/package.json
packages/plugin-less/package.json
packages/plugin-lightningcss/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-rem/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-source-build/package.json
packages/plugin-styled-components/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-typed-css-modules/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
packages/plugin-vue2-jsx/package.json
packages/plugin-vue2/package.json
scripts/config/package.json
scripts/test-helper/package.json

* feat: set uniqueName for module federation HMR by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2853
* perf: bump html plugin to remove lodash by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2857
* fix(plugin-solid): remove `@babel/preset-typescript` for resolve the babel warning by @zhylmzr in https://github.com/web-infra-dev/rsbuild/pull/2842
* fix: transform Module Federation runtime by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2850
* fix: incorrect WS port when using MF by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2852
* docs: baidu SEO verification by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2845
* docs: enable sitemap for SEO by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2846 …

release: 1.0.0-alpha.7

---

website/docs/en/guide/basic/configure-rspack.mdx
website/docs/zh/guide/basic/configure-rspack.mdx

Update custom loader examples, show how to insert loaders before a built-in loader.

docs: update custom loader examples

---

package.json
packages/core/package.json
packages/core/prebundle.config.mjs
packages/core/tsconfig.json
pnpm-lock.yaml

Prebundle html-rspack-plugin to reduce dependencies and required modules.

perf: prebundle html-rspack-plugin

---

packages/compat/babel-preset/package.json
packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-check-syntax/package.json
packages/plugin-image-compress/package.json
packages/plugin-less/package.json
packages/plugin-lightningcss/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-rem/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-source-build/package.json
packages/plugin-styled-components/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-typed-css-modules/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
packages/plugin-vue2-jsx/package.json
packages/plugin-vue2/package.json
scripts/config/package.json
scripts/test-helper/package.json

* feat(deps): bump Rspack 1.0.0-alpha.3 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2883
* feat: OPTIONS request return success code by @vtv6 https://github.com/web-infra-dev/rsbuild/pull/2867
* perf: prettier the compiled packages by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2879
* perf: skip calculation if browserslist is default value by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2882
* fix: html-rspack-plugin typo by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2880
* fix(plugin-assets-retry): url calculation when using asset prefix by @SoonIter in https://github.com/web-infra-dev/rsbuild/pull/2835
* fix(server): register OPTIONS fallback middleware at last by @chenjiahan in …

release: 1.0.0-alpha.9

---

website/docs/en/guide/basic/unocss.mdx

docs: Replace 'tailwindcss' with 'UnoCSS' in unocss.mdx

---

e2e/cases/create-rsbuild/helper.ts
e2e/cases/create-rsbuild/index.test.ts
e2e/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Add some E2E test cases for create-rsbuild.

test(e2e): add cases for create-rsbuild

---

website/docs/en/guide/start/quick-start.mdx
website/docs/zh/guide/start/quick-start.mdx

Add create-rsbuild quick creation guide.
https://github.com/web-infra-dev/rsbuild/pull/2903

docs: add create-rsbuild quick creation guide

---

packages/core/src/configChain.ts
website/docs/en/config/tools/bundler-chain.mdx
website/docs/zh/config/tools/bundler-chain.mdx

Update the builtin CHAIN_ID list to match the current implementation.
https://github.com/rspack-contrib/rsbuild-plugin-yaml/pull/2
https://github.com/rspack-contrib/rsbuild-plugin-eslint/pull/1

docs: update the builtin CHAIN_ID list

---

packages/create-rsbuild/src/index.ts

- Add framework alias for vue and solid-js
- Validate the user input

feat(create-rsbuild): add framework alias and validate input

---

packages/core/package.json
packages/plugin-react/package.json
pnpm-lock.yaml

feat(deps): bump rspack 1.0.0-alpha.4

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-check-syntax/package.json
packages/plugin-less/package.json
packages/plugin-lightningcss/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-rem/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-source-build/package.json
packages/plugin-styled-components/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
packages/plugin-vue2-jsx/package.json
packages/plugin-vue2/package.json
scripts/config/package.json
scripts/test-helper/package.json

* feat(create-rsbuild): add framework alias and validate input by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2922
* feat(deps): bump rspack 1.0.0-alpha.4 by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/2936
* fix: specify SWC cache directory by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/2926
* fix(webpack): should generate config files correctly when output is specified by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/2929
* docs: add modify config tips by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2930
* docs: correct server.htmlFallback tip by @Thulof in https://github.com/web-infra-dev/rsbuild/pull/2933
* chore(deps): update eslint to ^9.7.0 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/2924
* chore: …

Release: v1.0.1-beta.2

---

packages/core/package.json
packages/plugin-react/package.json
pnpm-lock.yaml

bump Rspack 1.0.0-alpha.5
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-alpha.5
https://github.com/web-infra-dev/rspack/issues/7193
https://github.com/web-infra-dev/rspack/issues/7194

feat(deps): bump Rspack 1.0.0-alpha.5

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-check-syntax/package.json
packages/plugin-less/package.json
packages/plugin-lightningcss/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-rem/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-source-build/package.json
packages/plugin-styled-components/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
packages/plugin-vue2-jsx/package.json
packages/plugin-vue2/package.json
scripts/config/package.json
scripts/test-helper/package.json

* feat: add `htmlPlugin` and `rspackConfig` template parameters by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2938
* feat: add environments as a filter of `api.transform` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2947
* feat(deps): bump Rspack 1.0.0-alpha.5 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2949
* fix: minify.jsOptions is not pass to SwcMinimizerPlugin by @luhc228 in https://github.com/web-infra-dev/rsbuild/pull/2931
* fix: only print verbose error logs in debug mode by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2941
* fix: should print stats.file as file name when have build errors by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2942
* docs: add benchmark to homepage by @chenjiahan in …

release: 1.0.1-beta.3

---

website/docs/en/config/output/externals.mdx
website/docs/zh/config/output/externals.mdx

align with rspack https://www.rspack.dev/config/externals#externals-1

docs: fix output.externals type

---

pnpm-lock.yaml
website/package.json
website/theme/components/ToolStack.module.scss
website/theme/components/ToolStack.tsx
website/theme/i18n.ts
website/theme/pages/index.tsx

Add tool stack to homepage:
https://github.com/rspack-contrib/rsfamily-doc-ui

docs: add tool stack to homepage

---

website/docs/en/plugins/list/plugin-vue-jsx.mdx
website/docs/en/plugins/list/plugin-vue2-jsx.mdx
website/docs/zh/plugins/list/plugin-vue-jsx.mdx
website/docs/zh/plugins/list/plugin-vue2-jsx.mdx

fix Vue JSX example
resolve https://github.com/web-infra-dev/rsbuild/issues/2964

docs: fix Vue JSX example

---

e2e/cases/plugin-api/plugin-process-assets-by-targets/index.test.ts
e2e/cases/plugin-api/plugin-process-assets-by-targets/myPlugin.ts
e2e/cases/plugin-api/plugin-process-assets-by-targets/rsbuild.config.ts
e2e/cases/plugin-api/plugin-process-assets-by-targets/src/index.css
e2e/cases/plugin-api/plugin-process-assets-by-targets/src/index.js
packages/core/src/initPlugins.ts
packages/core/src/types/plugin.ts

Allow to process assets for specific target.
https://github.com/web-infra-dev/rsbuild/pull/2966

feat: allow to process assets for specific target

---

e2e/cases/plugin-api/plugin-transform-by-environments/index.test.ts
e2e/cases/plugin-api/plugin-transform-by-environments/myPlugin.ts
packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
packages/core/src/initPlugins.ts
packages/core/src/loader/transformLoader.ts
packages/core/src/types/plugin.ts
packages/core/tests/__snapshots__/default.test.ts.snap
packages/core/tests/__snapshots__/environments.test.ts.snap
packages/core/tests/__snapshots__/nodeAddons.test.ts.snap
website/docs/en/plugins/dev/core.mdx
website/docs/en/plugins/dev/hooks.mdx
website/docs/zh/plugins/dev/core.mdx
website/docs/zh/plugins/dev/hooks.mdx

Allow to access environment context in transform API.

feat: allow to access environment context in transform API

---

packages/core/src/rspack/HtmlBasicPlugin.ts
packages/core/src/types/hooks.ts
website/docs/en/plugins/dev/hooks.mdx
website/docs/zh/plugins/dev/hooks.mdx

Allow to access compiler in modifyHTMLTags hook

feat: allow to access compiler in modifyHTMLTags hook

---

packages/core/src/plugins/rsdoctor.ts

fix: modify the criteria for verifying the Rsdoctor plugin.

fix: modify the criteria for verifying the Rsdoctor plugin

---

website/docs/en/guide/advanced/environments.mdx
website/docs/en/plugins/dev/hooks.mdx
website/docs/zh/guide/advanced/environments.mdx
website/docs/zh/plugins/dev/hooks.mdx

environmentConfig is normalized, and environmentConfig.html will not be undefined.

docs: update modifyEnvironmentConfig example code

---

website/docs/zh/api/javascript-api/instance.mdx

按照示例没有给出api声明,理解应该是上文中的rsbuild

docs(instance.mdx): adjust the references

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-check-syntax/package.json
packages/plugin-less/package.json
packages/plugin-lightningcss/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-rem/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-source-build/package.json
packages/plugin-styled-components/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
packages/plugin-vue2-jsx/package.json
packages/plugin-vue2/package.json
scripts/config/package.json
scripts/test-helper/package.json

* feat: add sources param to api.processAssets by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2987
* feat: support add plugins for specified environment by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/2986
* feat: more plugins support used as environment plugin by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/2994
* feat: add environments as a filter of `api.processAssets` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3009
* feat: enable inline chunks based on conditions through output options by @Thulof in https://github.com/web-infra-dev/rsbuild/pull/3000
* fix: webSocket stats message conflict when multiple web environment by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/2989
* fix: modify the criteria for verifying the …

release: 1.0.1-beta.5

---

packages/compat/webpack/modern.config.ts
packages/plugin-sass/modern.config.ts
packages/plugin-sass/package.json
scripts/config/modern.config.ts

Fix the type issue with moduleResolution node16+.
See https://github.com/web-infra-dev/rsbuild/pull/2353 for more
https://github.com/web-infra-dev/rsbuild/pull/2791

fix(plugin-sass): type issue with moduleResolution node16+

---

package.json

bump pnpm@9.6.0
https://github.com/pnpm/pnpm/releases/tag/v9.6.0

chore(deps): bump pnpm@9.6.0

---

e2e/playwright.config.ts

Retry e2e tests on CI.  Fix https://github.com/web-infra-dev/rsbuild/pull/2997
https://playwright.dev/docs/test-configuration

test(e2e): retry on CI

---

website/docs/en/guide/basic/css-usage.mdx
website/docs/zh/guide/basic/css-usage.mdx

Add guide for builtin lightningcss loader.

docs: add guide for builtin lightningcss loader

---

e2e/cases/module-federation-v2/host/rsbuild.config.ts
e2e/cases/module-federation-v2/host/src/App.js
e2e/cases/module-federation-v2/host/src/bootstrap.js
e2e/cases/module-federation-v2/host/src/index.js
e2e/cases/module-federation-v2/index.test.ts
e2e/cases/module-federation-v2/remote/rsbuild.config.ts
e2e/cases/module-federation-v2/remote/src/App.js
e2e/cases/module-federation-v2/remote/src/bootstrap.js
e2e/cases/module-federation-v2/remote/src/index.js
e2e/package.json
e2e/scripts/shared.ts
examples/module-federation-v2/host/package.json
examples/module-federation-v2/host/rsbuild.config.ts
examples/module-federation-v2/remote/package.json
examples/module-federation-v2/remote/rsbuild.config.ts
package.json
pnpm-lock.yaml

Add basic e2e cases for MF v2.
TODO: fix the failed cases.

test(e2e): add basic e2e cases for MF v2

---

website/docs/en/config/module-federation/options.mdx
website/docs/zh/config/module-federation/options.mdx

Make `moduleFederation.options` more clear

docs: make moduleFederation.options more clear

---

website/docs/en/config/tools/rspack.mdx
website/docs/zh/config/tools/rspack.mdx

update docs for `addRules`
closes #3070

docs: tells that `addRules` is adding rules to the leading

---

packages/core/package.json
packages/plugin-react/package.json
pnpm-lock.yaml

bump Rspack 1.0.0-beta.1
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-beta.1

feat: bump Rspack 1.0.0-beta.1

---

e2e/cases/css/lightningcss-prefixes/index.test.ts

Add test case for lightingcss-loader, ensure it can work as expected in dev mode.

test(e2e): add test case for lightingcss-loader

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-check-syntax/package.json
packages/plugin-less/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-rem/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-source-build/package.json
packages/plugin-styled-components/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
packages/plugin-vue2-jsx/package.json
packages/plugin-vue2/package.json
scripts/config/package.json
scripts/test-helper/package.json

* fix: pnpm generates invalid peerDependencies version by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3078
**Full Changelog**: https://github.com/web-infra-dev/rsbuild/compare/v1.0.1-beta.7...v1.0.1-beta.8

release: 1.0.1-beta.8

---

website/docs/en/guide/advanced/environments.mdx
website/docs/zh/guide/advanced/environments.mdx

docs: what is environment

---

website/docs/en/guide/migration/_meta.json
website/docs/en/guide/migration/rsbuild-0-x.mdx
website/docs/zh/guide/migration/_meta.json
website/docs/zh/guide/migration/rsbuild-0-x.mdx

Add migration guide for Rsbuild 0.x projects.

docs: add migration guide for Rsbuild 0.x

---

website/docs/en/plugins/dev/hooks.mdx
website/docs/zh/plugins/dev/hooks.mdx

list which hooks will be triggered again when rebuild.

docs: list which hooks will be triggered again when rebuild

---

e2e/cases/plugin-api/plugin-hooks/index.test.ts
website/docs/en/plugins/dev/hooks.mdx
website/docs/zh/plugins/dev/hooks.mdx

add distinguish between Global Hooks and Environment Hooks.

docs: distinguish between Global Hooks and Environment Hooks

---

e2e/cases/cli/reload-extra-config/.gitignore
e2e/cases/cli/reload-extra-config/index.test.ts
e2e/cases/cli/reload-extra-config/rsbuild.config.ts

test(e2e): fix a slow case case

---

website/docs/en/guide/advanced/browser-compatibility.mdx
website/docs/zh/guide/advanced/browser-compatibility.mdx

Add UA polyfill guide for using Cloudflare's polyfill service.
https://cdnjs.cloudflare.com/polyfill/

docs: add UA polyfill guide

---

website/docs/en/config/tools/swc.mdx
website/docs/en/guide/basic/_meta.json
website/docs/en/guide/basic/configure-swc.mdx
website/docs/zh/config/tools/swc.mdx
website/docs/zh/guide/basic/_meta.json
website/docs/zh/guide/basic/configure-swc.mdx

Add a new page for configuring SWC.

docs: add configure SWC guide

---

website/docs/en/config/output/minify.mdx
website/docs/en/guide/basic/configure-swc.mdx
website/docs/en/guide/start/npm-packages.mdx
website/docs/zh/config/output/minify.mdx
website/docs/zh/guide/basic/configure-swc.mdx

Add guide for custom JS minimizer, such as switching to Terser.

docs: add guide for custom JS minimizer

---

website/docs/en/guide/basic/configure-swc.mdx
website/docs/zh/guide/basic/configure-swc.mdx

Add tips for SWC plugin version.
resolve https://github.com/web-infra-dev/rsbuild/issues/2953

docs: add tips for SWC plugin version

---

website/docs/en/config/dev/watch-files.mdx
website/docs/zh/config/dev/watch-files.mdx

Add guide for watching files and reload dev server.

docs: add guide for watching files and reload dev server

---

README.md
README.zh-CN.md
scripts/dictionary.txt
website/docs/en/guide/faq/general.mdx
website/docs/en/guide/start/index.mdx
website/docs/zh/guide/faq/general.mdx
website/docs/zh/guide/start/index.mdx

docs: add Rslib links

---

pnpm-lock.yaml
website/package.json

bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack

docs: bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack

---

.github/pr-labeler.yml
.github/release.yml

Align PR labels with Rspack
https://github.com/web-infra-dev/rspack/labels?page=2&sort=name-asc

chore(workflow): align PR labels with Rspack

---

packages/core/src/helpers/fs.ts
packages/core/src/helpers/index.ts
packages/core/src/helpers/stats.ts

Move some helpers to sub folder. Just to better organize the code.

chore: move helpers to sub folder

---

README.md
README.pt-BR.md
README.zh-CN.md

Portuguese is one of the most spoken languages in the world, adding this language can help native speakers reading the docs.

docs: Add pt-BR Readme

---

website/docs/en/guide/advanced/environments.mdx
website/docs/en/guide/start/glossary.mdx
website/docs/en/shared/environment.mdx
website/docs/zh/guide/advanced/environments.mdx
website/docs/zh/guide/start/glossary.mdx
website/docs/zh/shared/environment.mdx

docs: add `environment` to glossary

---

packages/create-rsbuild/src/index.ts

Fix failed to override existed package.json when target folder is not empty. We should only merge package.json for the tools templates.

fix(create-rsbuild): failed to override package.json

---

packages/compat/webpack/src/createCompiler.ts
packages/core/src/cli/init.ts
packages/core/src/config.ts
packages/core/src/helpers/index.ts
packages/core/src/index.ts
packages/core/src/plugins/basic.ts
packages/core/src/plugins/bundleAnalyzer.ts
packages/core/src/plugins/define.ts
packages/core/src/plugins/inlineChunk.ts
packages/core/src/plugins/minimize.ts
packages/core/src/plugins/progress.ts
packages/core/src/plugins/sri.ts
packages/core/src/provider/createCompiler.ts
packages/core/src/types/hooks.ts
packages/plugin-assets-retry/src/index.ts
packages/plugin-assets-retry/src/types.ts
packages/plugin-babel/src/plugin.ts
packages/plugin-preact/src/index.ts
packages/plugin-react/src/index.ts
packages/plugin-react/src/react.ts
packages/plugin-rem/src/index.ts
packages/plugin-styled-components/src/index.ts

Prefer reading the `mode` config instead of using `process.env.NODE_ENV`.
https://github.com/web-infra-dev/rsbuild/pull/3155

feat: prefer reading the mode config

---

website/docs/en/config/_meta.json
website/docs/en/config/mode.mdx
website/docs/zh/config/_meta.json
website/docs/zh/config/mode.mdx

Add `mode` config documentation.
https://github.com/web-infra-dev/rsbuild/pull/3155

docs: add `mode` config documentation

---

e2e/cases/mode/index.test.ts
e2e/cases/mode/src/index.ts
e2e/scripts/shared.ts

Add more cases for `mode` config.
https://github.com/web-infra-dev/rsbuild/pull/3155

test(e2e): add more cases for `mode` config

---

e2e/cases/cli/mode/index.test.ts
e2e/cases/cli/mode/src/index.ts
e2e/cases/cli/mode/tsconfig.json
packages/core/src/cli/commands.ts
packages/core/src/cli/init.ts
website/docs/en/guide/basic/cli.mdx
website/docs/zh/guide/basic/cli.mdx

Add new `--mode` CLI option to set the `mode` config.
https://rsbuild.dev/config/mode

feat(CLI): add new `--mode` option

---

website/docs/en/guide/start/quick-start.mdx
website/docs/zh/guide/start/quick-start.mdx

Add a simple guide for MarsCode to the online examples section.

docs: add MarsCode to online examples

---

package.json
packages/core/package.json
pnpm-lock.yaml

bump Rspack 1.0.0-beta.4
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-beta.4

feat(deps): bump Rspack 1.0.0-beta.4

---

CONTRIBUTING.md

Small grammatical tweaks to the contribution guide to make it easier for new contributors to understand the docs 😀.

docs: Fix minor grammar errors in the contribution docs 📙

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-less/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
packages/plugin-vue2-jsx/package.json
packages/plugin-vue2/package.json
scripts/config/package.json
scripts/test-helper/package.json

* fix: ensure postcss-loader uses the built-in postcss by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3204
**Full Changelog**: https://github.com/web-infra-dev/rsbuild/compare/v1.0.1-beta.12...v1.0.1-beta.13

release: 1.0.1-beta.13

---

e2e/cases/type-check/basic/index.test.ts
website/docs/en/plugins/list/plugin-type-check.mdx
website/docs/zh/plugins/list/plugin-type-check.mdx

Add exclude examples for the type-check plugin.

docs(type-check): add exclude examples

---

website/docs/en/config/security/sri.mdx
website/docs/zh/config/security/sri.mdx

doc: fix typo in security

---

packages/core/package.json
pnpm-lock.yaml

bump Rspack 1.0.0-beta.5
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-beta.5

feat(deps): bump Rspack 1.0.0-beta.5

---

packages/core/src/types/config/html.ts
website/docs/en/config/html/app-icon.mdx
website/docs/zh/config/html/app-icon.mdx

update documentation for `html.appIcon`
https://github.com/web-infra-dev/rsbuild/pull/3219

docs: update documentation for `html.appIcon`

---

packages/compat/plugin-swc/src/minimizer.ts
packages/compat/plugin-swc/src/plugin.ts

`environmentConfig` is repeat with `rsbuild.config.[environment-name].mjs`

chore: simplify plugin-swc inspected config

---

website/docs/en/config/html/inject.mdx
website/docs/en/config/output/inline-scripts.mdx
website/docs/zh/config/html/inject.mdx
website/docs/zh/config/output/inline-scripts.mdx

Add example for inlining async chunks.
https://github.com/web-infra-dev/rsbuild/issues/3240

docs: add example for inlining async chunks

---

README.md
README.pt-BR.md
README.zh-CN.md
website/docs/en/guide/start/index.mdx
website/docs/zh/guide/start/index.mdx

update Rspack stack layers, add Rslib

docs: update Rspack stack layers

---

website/docs/en/guide/migration/rsbuild-0-x.mdx
website/docs/zh/guide/migration/rsbuild-0-x.mdx

https://github.com/web-infra-dev/rsbuild/discussions/2508

docs: add more breaking changes about rsbuild 1.0

---

packages/core/tests/server.test.ts

Update ip in test files, use a common ip address.

test: update ip in test files

---

website/docs/en/guide/migration/rsbuild-0-x.mdx
website/docs/zh/guide/migration/rsbuild-0-x.mdx

Improve 0.x migration guide, add more breaking changes.

docs: improve 0.x migration guide

---

website/docs/en/guide/advanced/environments.mdx
website/docs/en/plugins/dev/index.mdx
website/docs/zh/guide/advanced/environments.mdx
website/docs/zh/plugins/dev/index.mdx

add developing environment plugins guide.

docs: add developing environment plugins guide

---

e2e/cases/module-federation/index.test.ts
packages/core/package.json
packages/core/src/helpers/fs.ts
packages/core/src/plugins/appIcon.ts
packages/core/src/rspack/RsbuildHtmlPlugin.ts
pnpm-lock.yaml

bump Rspack 1.0.0-rc.0.
TODO: fix MF runtime syntax.
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-rc.0

feat(deps): bump Rspack 1.0.0-rc.0

---

packages/compat/plugin-swc/package.json
packages/core/package.json
pnpm-lock.yaml

fix(deps): use caret version for swc helpers

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-less/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
packages/plugin-vue2/package.json
scripts/config/package.json
scripts/test-helper/package.json

* feat(deps): bump Rspack 1.0.0-rc.0 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3268
* feat: expose `server.printUrls` method by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3260
* feat: add `environments` to `onAfterStartProdServer` by @colinaaa in https://github.com/web-infra-dev/rsbuild/pull/3264
* feat: transformImport support function type by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3266
* perf: replace dev middleware with a lightweight version by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3257
* fix(webpack): no longer need to set NODE_ENV by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3255
* fix: not inline scripts / styles when enable not set by @9aoy in …

release: 1.0.1-beta.16

---

packages/compat/plugin-swc/package.json
packages/core/package.json
pnpm-lock.yaml

Bump Rspack 1.0.0-rc.1.
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-rc.1

feat(deps): bump Rspack 1.0.0-rc.1

---

packages/core/package.json
pnpm-lock.yaml

bump Rspack 1.0.0-rc.2
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-rc.2

feat(deps): bump Rspack 1.0.0-rc.2

---

packages/core/package.json
packages/core/src/helpers/index.ts
pnpm-lock.yaml

bump Rspack 1.0.0
https://github.com/web-infra-dev/rspack/pull/7691

feat(deps): bump Rspack 1.0.0

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-less/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
scripts/config/package.json
scripts/test-helper/package.json

* feat!: enable Rspack config schema validation by default by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3295
* fix!: remove transformImport false option by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3289
* feat(deps): bump Rspack 1.0.0 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3297
* feat: minify CSS for injected styles by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3272
* feat: allow to override Rspack config validate env by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3292
* fix: avoid passing unsupported Rspack config by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3293
* docs: update EJS usage by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3275
* test(e2e): improve …

release: 1.0.1-rc.0

---

website/docs/en/config/output/target.mdx
website/docs/zh/config/output/target.mdx

Add guide for other Rspack targets.
https://github.com/web-infra-dev/rsbuild/issues/3298

docs: add guide for other Rspack targets

---

website/docs/en/config/dev/client.mdx
website/docs/zh/config/dev/client.mdx

Add some content for error overlay.

docs: add guide for error overlay

---

website/docs/en/guide/basic/html-template.mdx

docs: Update html-template.mdx

---

website/docs/en/config/performance/bundle-analyze.mdx
website/docs/en/guide/debug/rsdoctor.mdx
website/docs/en/plugins/list/plugin-react.mdx
website/docs/zh/config/performance/bundle-analyze.mdx
website/docs/zh/guide/debug/rsdoctor.mdx
website/docs/zh/plugins/list/plugin-react.mdx

Using cross-env to set env var, guide for Windows users.
https://www.npmjs.com/package/cross-env

docs: use cross-env to set env var

---

website/docs/en/guide/migration/rsbuild-0-x.mdx

Adjust code change preview, supposedly server.open

docs: update server.open guide rsbuild-0-x.mdx

---

website/docs/en/guide/migration/rsbuild-0-x.mdx
website/docs/zh/guide/migration/rsbuild-0-x.mdx

Add Rspack config validation to migration guide.
https://github.com/web-infra-dev/rsbuild/pull/3295

docs: add Rspack config validation to migration guide

---

README.md
README.zh-CN.md
packages/core/src/types/rsbuild.ts
website/docs/en/api/javascript-api/core.mdx
website/docs/en/config/dev/hmr.mdx
website/docs/en/guide/migration/vite.mdx
website/docs/en/guide/start/index.mdx
website/docs/zh/api/javascript-api/core.mdx
website/docs/zh/config/dev/hmr.mdx
website/docs/zh/guide/migration/vite.mdx
website/docs/zh/guide/start/index.mdx

- Add Vite config migration table.
- Polish Rsbuild introduction.

docs: config migration table

---

website/docs/en/config/server/proxy.mdx
website/docs/zh/config/server/proxy.mdx

docs: add /api in the example of server.proxy

---

packages/create-rsbuild/README.md
packages/create-rsbuild/package.json
pnpm-lock.yaml
website/docs/en/guide/advanced/env-vars.mdx
website/docs/en/guide/start/quick-start.mdx
website/docs/zh/guide/start/quick-start.mdx

Update README for `create-rsbuild` and add link.

docs(create-rsbuild): update README

---

e2e/cases/node-addons/index.test.ts
packages/compat/webpack/src/build.ts
packages/compat/webpack/src/createCompiler.ts
packages/core/src/client/types.d.ts
packages/core/src/config.ts
packages/core/src/env.d.ts
packages/core/src/provider/build.ts
packages/core/tests/pluginStore.test.ts

Reduce any type from the codebase.

chore: reduce any type

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-less/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
scripts/config/package.json
scripts/test-helper/package.json

* fix(create-rsbuild): broken shebang line in bin file by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3344
**Full Changelog**: https://github.com/web-infra-dev/rsbuild/compare/v1.0.1-rc.1...v1.0.1-rc.2

release: 1.0.1-rc.2

---

website/docs/en/guide/basic/configure-swc.mdx
website/docs/en/guide/debug/debug-mode.mdx
website/docs/en/guide/faq/features.mdx
website/docs/zh/guide/basic/configure-swc.mdx
website/docs/zh/guide/debug/debug-mode.mdx
website/docs/zh/guide/faq/features.mdx

Improve selecting SWC plugin version guide, add [plugins.swc.rs](https://plugins.swc.rs/).

docs: improve selecting SWC plugin version

---

website/docs/zh/guide/migration/rsbuild-0-x.mdx

docs: remove repeat info in rsbuild-0-x.mdx

---

website/docs/en/guide/migration/rsbuild-0-x.mdx

docs: remove repeat info in en rsbuild-0-x.mdx

---

packages/core/package.json
pnpm-lock.yaml

feat(deps): bump Rspack v1.0.1

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-less/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
scripts/config/package.json
scripts/test-helper/package.json

* feat(deps): bump Rspack v1.0.1 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3360
* feat: support nested plugins by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3348
* feat: export more sub-types of Rsbuild config by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3351
* fix: correct proxy options type by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3352
* fix: resolve mjs extension before js by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3359
* fix(plugin-swc): should verify the version correctly by @yimingjfe in https://github.com/web-infra-dev/rsbuild/pull/3364
* docs: improve selecting SWC plugin version by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3346
* docs: correct addPlugins type by …

release: 1.0.1-rc.3

---

packages/core/package.json
pnpm-lock.yaml

bump Rspack 1.0.3
https://github.com/rspack-contrib/storybook-rsbuild/issues/83

feat(deps): bump Rspack 1.0.3

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-less/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
scripts/config/package.json
scripts/test-helper/package.json

* feat(deps): bump Rspack 1.0.2 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3375
* feat(deps): bump Rspack 1.0.3 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3378
* fix: skip resolution if Rsdoctor plugin is registered by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3370
* docs(website): typo for easy to configure text on homepage by @aryan1306 in https://github.com/web-infra-dev/rsbuild/pull/3371
* chore(deps): update dependency picocolors to ^1.1.0 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/3366
* chore(deps): update dependency vue to ^3.5.0 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/3367
* chore(deps): update dependency svelte-check to v4 by @renovate in …

release: 1.0.1-rc.4

---

website/docs/en/config/output/charset.mdx
website/docs/zh/config/output/charset.mdx

Improve `output.charset`, add some notes.

docs: improve `output.charset`

---

website/docs/zh/plugins/list/plugin-stylus.mdx

the same as https://github.com/web-infra-dev/rsbuild/pull/3392

docs(zh): updated StylusOptions type

---

website/docs/en/guide/advanced/env-vars.mdx
website/docs/zh/guide/advanced/env-vars.mdx

https://github.com/web-infra-dev/rsbuild/issues/3394

docs: should manually call loadEnv method when using Rsbuild Environment API

---

packages/compat/plugin-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-less/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-type-check/package.json
packages/plugin-vue-jsx/package.json
packages/plugin-vue/package.json
scripts/config/package.json
scripts/test-helper/package.json

* fix: failed to use html-loader by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3384
* fix(plugin-stylus): updated StylusOptions type by @sudhakar-selva in https://github.com/web-infra-dev/rsbuild/pull/3392
* fix: lightningcss-loader not work when using PostCSS by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3396
* docs: fix rsdoctor link by @iamdin in https://github.com/web-infra-dev/rsbuild/pull/3379
* docs: add eslint plugin guide in CRA migration by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3383
* docs: improve `output.charset` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3389
* docs: add tip for deprecated tilde by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3391
* docs(zh): updated StylusOptions type …

release: 1.0.1-rc.5

---

website/docs/en/guide/basic/css-usage.mdx
website/docs/zh/guide/basic/css-usage.mdx

Add guide for disabling Lightning CSS.
resolve https://github.com/web-infra-dev/rsbuild/issues/3328

docs: add guide for disabling Lightning CSS

---

website/docs/en/guide/start/index.mdx
website/docs/zh/guide/start/index.mdx

Add build tools image to introduction
https://x.com/alirz_sedghi/status/1833108697117061395

docs: add build tools image to introduction

---

packages/compat/plugin-webpack-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-less/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-vue/package.json
scripts/config/package.json
scripts/test-helper/package.json

release: 1.0.1

---

website/docs/zh/community/releases/v1-0.mdx

docs: fix typo in 1.0 announcement

---

website/docs/en/config/tools/rspack.mdx
website/docs/zh/config/tools/rspack.mdx

Add example for merging Rspack config.
resolve https://github.com/web-infra-dev/rsbuild/issues/3410

docs: add example for merging Rspack config

---

packages/plugin-stylus/src/index.ts

feat(plugin-stylus): support `define` option

---

website/docs/en/plugins/list/plugin-stylus.mdx
website/docs/zh/plugins/list/plugin-stylus.mdx

docs(plugin-stylus): update `StylusOptions`

---

packages/core/package.json
pnpm-lock.yaml

Bump Rspack v1.0.4.
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.4

feat(deps): bump Rspack v1.0.4

---

website/docs/en/guide/basic/configure-rspack.mdx
website/docs/zh/guide/basic/configure-rspack.mdx

remove non-existent utils variable in rspack config

docs: remove non-existent utils variable in rspack config

---

website/docs/en/config/dev/lazy-compilation.mdx
website/docs/en/config/security/sri.mdx
website/docs/en/config/server/open.mdx
website/docs/en/guide/basic/cli.mdx
website/docs/zh/config/security/sri.mdx
website/docs/zh/config/server/open.mdx
website/docs/zh/guide/basic/cli.mdx

Add server open priority to documentation.
resolve https://github.com/web-infra-dev/rsbuild/issues/3458

docs: server open priority

---

packages/compat/webpack/src/build.ts

the same as https://github.com/web-infra-dev/rsbuild/pull/3470

chore: fix type for eco CI

---

packages/core/package.json
pnpm-lock.yaml

bump Rspack v1.0.5
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.5
https://github.com/web-infra-dev/rspack/issues/7869

feat(deps): bump Rspack v1.0.5

---

package.json
packages/create-rsbuild/package.json
packages/plugin-less/package.json
packages/plugin-less/rslib.config.ts
pnpm-lock.yaml
scripts/config/modern.config.ts
scripts/config/package.json
scripts/config/rslib.config.ts

Extract shared Rslib config for internal packages.

chore: extract shared Rslib config

---

.changeset/config.json
packages/compat/webpack/package.json
packages/core/package.json
scripts/test-helper/package.json

* feat: expose `devServer.open` API by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3498
* feat: disable preserveAllComments by default by @Timeless0911 in https://github.com/web-infra-dev/rsbuild/pull/3510
* docs: htmlPaths typo by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3508
* chore(deps): update dependency @modern-js/module-tools to ^2.60.0 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/3488
* chore(deps): update dependency nx to ^19.7.3 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/3490
* chore(lint): enable Biome support for CSS Modules by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3494
* chore(deps): update dependency terser to v5.32.0 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/3492
* …

release: @rsbuild/core v1.0.5

---

website/docs/en/config/tools/style-loader.mdx
website/docs/zh/config/tools/style-loader.mdx

Correct style-loader example.
https://github.com/web-infra-dev/rsbuild/pull/3515

docs: correct style-loader example

---

website/docs/en/guide/basic/css-modules.mdx
website/docs/en/guide/basic/json-files.mdx
website/docs/en/guide/basic/static-assets.mdx
website/docs/en/guide/basic/typescript.mdx
website/docs/en/guide/migration/vite.mdx
website/docs/en/guide/optimization/inline-assets.mdx
website/docs/zh/guide/basic/css-modules.mdx
website/docs/zh/guide/basic/json-files.mdx
website/docs/zh/guide/basic/static-assets.mdx
website/docs/zh/guide/basic/typescript.mdx
website/docs/zh/guide/migration/vite.mdx
website/docs/zh/guide/optimization/inline-assets.mdx

Add guide for preset types.
resolve https://github.com/web-infra-dev/rsbuild/issues/3520

docs: add preset types

---

packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
packages/core/prebundle.config.mjs
packages/core/src/plugins/css.ts
packages/core/src/types/thirdParty.ts
packages/core/tests/__snapshots__/builder.test.ts.snap
packages/core/tests/__snapshots__/css.test.ts.snap
packages/core/tests/__snapshots__/default.test.ts.snap
packages/core/tests/__snapshots__/environments.test.ts.snap
packages/plugin-less/tests/__snapshots__/index.test.ts.snap
packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap

Fixed by Rspack, see https://github.com/web-infra-dev/rspack/pull/7846
https://github.com/web-infra-dev/rsbuild/pull/3396

fix: remove temp code for PostCSS AST

---

packages/core/package.json
pnpm-lock.yaml

feat(deps): bump Rspack v1.0.6

---

packages/compat/webpack/package.json
packages/core/package.json

* feat(create-rsbuild): adds decorator configs to lit-html templates an… by @alexUXUI in https://github.com/web-infra-dev/rsbuild/pull/3527
* feat: allow to import TS files with js extension by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3536
* feat(deps): bump Rspack v1.0.6 by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3544
* perf: avoid requiring empty module by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3538
* fix(types): missing toml module type by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3526
* fix(create-rsbuild): useDefineForClassFields in lit template by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3530
* fix: remove temp code for PostCSS AST by @chenjiahan in …

Release: v1.0.6

---

packages/core/package.json
pnpm-lock.yaml

bump Rspack v1.0.7
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.7

feat(deps): bump Rspack v1.0.7

---

packages/compat/plugin-webpack-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json

* feat(deps): bump Rspack v1.0.7 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3549
* fix(plugin-webpack-swc): swcMinimizerPlugin sourceMap config by @easy1090 in https://github.com/web-infra-dev/rsbuild/pull/3550
* Revert "feat: allow to import TS files with js extension (#3536)" by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3559
* chore(deps): update dependency browserslist to v4.24.0 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/3553
* chore(deps): update dependency babel-preset-solid to ^1.9.0 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/3552
* chore(deps): update all patch dependencies by @renovate in https://github.com/web-infra-dev/rsbuild/pull/3551
* chore: remove lightningcss minimizer exclude by @chenjiahan in …

release: 1.0.7

---

website/docs/en/plugins/list/plugin-assets-retry.mdx
website/docs/zh/plugins/list/plugin-assets-retry.mdx

Add module federation assets retry guide.
https://www.npmjs.com/package/@module-federation/retry-plugin

docs: add module federation assets retry

---

packages/compat/webpack/src/build.ts

fix: correct webpack error message

---

website/docs/en/guide/optimization/split-chunk.mdx
website/docs/zh/guide/optimization/split-chunk.mdx

Add an example for splitting single CSS chunk.

docs: add example for splitting single CSS chunk

---

e2e/cases/browserslist/package-config-array/index.test.ts
e2e/cases/browserslist/package-config-array/package.json
e2e/cases/browserslist/package-config-array/rsbuild.config.ts
e2e/cases/browserslist/package-config-array/src/index.js
e2e/cases/browserslist/package-config-object/index.test.ts
e2e/cases/browserslist/package-config-object/package.json
e2e/cases/browserslist/package-config-object/rsbuild.config.ts
e2e/cases/browserslist/package-config-object/src/index.js
e2e/cases/browserslist/package-config-string/index.test.ts
e2e/cases/browserslist/package-config-string/package.json
e2e/cases/browserslist/package-config-string/rsbuild.config.ts
e2e/cases/browserslist/package-config-string/src/index.js
examples/vue/src/App.vue
packages/core/package.json
pnpm-lock.yaml

Fix failed load browserslist string value:
https://github.com/rspack-contrib/browserslist-load-config/releases/tag/v0.1.1

fix: failed load browserslist string value

---

package.json

chore: bump pnpm v9.11.0

---

.github/renovate.json5

Update renovate ignore deps list.

chore: update renovate ignore deps

---

packages/core/package.json

* feat(deps): bump rspack 1.0.8 by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3596
* feat: improve logs order when port is in use by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3606
* fix: moduleFederation option only supports Rspack by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3597
* fix: failed load browserslist string value by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3598
* fix: compat invalid route by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3611
* fix: only print children compiler time when multi compiler by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3613
* chore(deps): update all patch dependencies by @renovate in https://github.com/web-infra-dev/rsbuild/pull/3599
* chore: update pnpm lock …

release: 1.0.9

---

website/rspress.config.ts
website/theme/components/Copyright.module.scss
website/theme/components/Copyright.tsx

docs: add Rspress link to footer

---

website/docs/en/config/output/asset-prefix.mdx
website/docs/zh/config/output/asset-prefix.mdx

Improve `output.assetPrefix` documentation, add relative path example.
https://github.com/web-infra-dev/rsbuild/issues/3616

docs: improve `output.assetPrefix`

---

website/docs/en/config/dev/asset-prefix.mdx
website/docs/en/config/output/asset-prefix.mdx
website/docs/en/config/server/base.mdx
website/docs/zh/config/dev/asset-prefix.mdx
website/docs/zh/config/output/asset-prefix.mdx
website/docs/zh/config/server/base.mdx
website/docs/zh/guide/advanced/env-vars.mdx
website/docs/zh/guide/basic/server.mdx

- Add `base` version range.
- Polish document.

docs: add `base` version range

---

website/docs/en/guide/migration/vite.mdx
website/docs/zh/guide/migration/vite.mdx

Add the new `base` config to migration guide.

docs: add `base` to migration guide

---

website/docs/en/guide/advanced/env-vars.mdx
website/docs/zh/guide/advanced/env-vars.mdx

List all default env vars and polish the env vars documentation.

docs: list all default env vars

---

e2e/cases/plugin-api/plugin-hooks/index.test.ts
packages/core/src/createRsbuild.ts
packages/core/src/types/rsbuild.ts
website/docs/en/api/javascript-api/instance.mdx
website/docs/zh/api/javascript-api/instance.mdx

Add a `checkDistDir` option for `rsbuild.preview` to allow to disable preview checks.

feat: allow to disable preview checks

---

packages/core/src/server/cliShortcuts.ts
packages/core/src/server/devServer.ts

Support for CLI shortcuts (part 2), see https://github.com/web-infra-dev/rsbuild/pull/3614 for more.
https://github.com/web-infra-dev/rsbuild/issues/2991

feat: support for CLI shortcuts (part 2)

---

packages/core/src/server/cliShortcuts.ts
packages/core/src/server/devServer.ts
packages/core/src/server/restart.ts

Support for restarting dev server via CLI shortcut.
https://github.com/web-infra-dev/rsbuild/issues/2991

feat: restart dev server via CLI shortcut

---

e2e/cases/cli/shortcuts/dev.mjs
e2e/cases/cli/shortcuts/index.test.ts
e2e/cases/cli/shortcuts/preview.mjs
e2e/scripts/helper.ts

Add e2e test cases for CLI shortcuts.
https://github.com/web-infra-dev/rsbuild/issues/2991

test(e2e): add test cases for CLI shortcuts

---

website/docs/en/config/dev/cli-shortcuts.mdx
website/docs/zh/config/dev/cli-shortcuts.mdx

Add documentation for the new `dev.cliShortcuts` configuration.

docs: add `dev.cliShortcuts` configuration

---

packages/core/src/client/hmr.ts

update rspack `webpackHot` docs link 😄

fix(comment): hmr broken docs link

---

website/docs/zh/config/dev/cli-shortcuts.mdx

Remove duplicate lines for zh-docs (en-docs is correct).

docs(cli-shortcuts): remove duplicate lines

---

packages/core/package.json
pnpm-lock.yaml

https://github.com/web-infra-dev/rspack/releases/tag/v1.0.9

feat(deps): bump rspack 1.0.9

---

packages/core/src/plugins/css.ts

Initialize PostCSS plugin after loading the PostCSS configuration to avoid multiple initialization.
resolve https://github.com/web-infra-dev/rsbuild/issues/3618

perf: initialize PostCSS plugin to avoid multiple initialization

---

packages/core/package.json
pnpm-lock.yaml

Bump Rspack v1.0.10
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.10
https://github.com/web-infra-dev/rsbuild/issues/3447

feat(deps): bump Rspack v1.0.10

---

package.json
packages/plugin-stylus/modern.config.ts
packages/plugin-stylus/package.json
packages/plugin-stylus/rslib.config.ts
packages/plugin-stylus/src/index.ts
pnpm-lock.yaml

Use Rslib to bundle `@rsbuild/plugin-stylus`.

feat(plugin-stylus): use Rslib to bundle

---

packages/plugin-sass/modern.config.ts
packages/plugin-sass/package.json
packages/plugin-sass/prebundle.config.mjs
packages/plugin-sass/rslib.config.ts
packages/plugin-sass/src/helpers.ts
packages/plugin-sass/src/index.ts
packages/plugin-sass/src/types.ts
packages/plugin-sass/tsconfig.json
packages/plugin-stylus/package.json
pnpm-lock.yaml

Use Rslib to bundle `@rsbuild/plugin-sass`.

feat(plugin-sass): use Rslib to bundle

---

packages/plugin-react/modern.config.ts
packages/plugin-react/package.json
packages/plugin-react/rslib.config.ts
packages/plugin-react/src/index.ts
packages/plugin-react/src/react.ts
packages/plugin-react/src/splitChunks.ts
packages/plugin-react/tsconfig.json

Use Rslib to bundle `@rsbuild/plugin-react`.

feat(plugin-react): use Rslib to bundle

---

.github/workflows/test.yml

support trigger rsbuild-ecosystem-ci test when main push.
https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions

test: add rsbuild-ecosystem-ci test

---

packages/compat/plugin-webpack-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-less/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-vue/package.json

* feat(core): add `distPath.assets`  and `filename.assets` by @SoonIter in https://github.com/web-infra-dev/rsbuild/pull/3688
* feat(core): allow to unset the title tag by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3714
* feat(core): make it easier to remove the built-in alias by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3715
* feat(plugin-stylus): use Rslib to bundle by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3679
* feat(plugin-solid): use Rslib to bundle by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3693
* feat(plugin-vue): use Rslib to bundle by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3697
* feat(plugin-babel): use Rslib to bundle by @chenjiahan in …

release: 1.0.14

---

pnpm-lock.yaml
website/package.json

support https://github.com/web-infra-dev/rspress/pull/1472

chore(deps): update rspress 1.33.1

---

.github/workflows/ecosystem-ci-trigger.yml
.github/workflows/ecosystem-ci.yml
.github/workflows/release.yml
.github/workflows/test.yml
scripts/alert/lark.js

Support run Rsbuild Ecosystem CI via:
- `!eco-ci` comment
- Merge PR into main & will send failure notification to lark
- before release (Can be disabled by selecting `run_eco_ci` false)

test: enhance Rsbuild  ecosystem CI

---

.github/workflows/ecosystem-ci.yml

Eco-ci results should be updated in the comments.

chore: should update eco-ci result in comment

---

.github/workflows/ecosystem-ci-trigger.yml
.github/workflows/ecosystem-ci.yml
.github/workflows/release.yml

fix ci `Unexpected inputs provided: [\"commitSHA\"]` 
https://github.com/web-infra-dev/rsbuild/actions/runs/11340468375/job/31536944531

fix: eco-ci unexpected inputs & token

---

.github/workflows/release.yml

fix: run_eco_ci option in release workflow

---

packages/core/package.json
packages/core/tests/__snapshots__/builder.test.ts.snap
packages/core/tests/__snapshots__/css.test.ts.snap
packages/core/tests/__snapshots__/default.test.ts.snap
packages/core/tests/__snapshots__/environments.test.ts.snap
packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
packages/plugin-less/tests/__snapshots__/index.test.ts.snap
packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
pnpm-lock.yaml

Bump @rspack/core to 1.0.11.
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.11

feat(deps): bump @rspack/core 1.0.11

---

.github/workflows/ecosystem-ci.yml
.github/workflows/release.yml

fix: add ref when call eco-ci-selected workflow

---

.github/workflows/ecosystem-ci.yml

ci: not run eco-ci when only docs changed

---

website/docs/zh/config/dev/lazy-compilation.mdx

docs: fix lazy compilation typo

---

packages/core/package.json
pnpm-lock.yaml

bump Rspack 1.0.12
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.12

feat(deps): bump rspack 1.0.12

---

packages/core/package.json
pnpm-lock.yaml

https://github.com/web-infra-dev/rspack/releases/tag/v1.0.13

feat(deps): bump rspack 1.0.13

---

packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-sass/package.json

* feat: add appendRules util to `tools.rspack` config by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3755
* feat: `output.filename.css` allow function by @gaoachao in https://github.com/web-infra-dev/rsbuild/pull/3752
* feat(create-rsbuild): support for both svelte4 and svelte5 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3771
* fix: use `getCompilationHooks` of HTML plugin by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3750
* fix: revert to the `getHooks` of HTML plugin by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3753
* fix: configure the default assetPrefix for MF apps correctly by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3757
* docs: improve `output.filename` function type by @chenjiahan in …

release: 1.0.16

---

website/docs/en/api/javascript-api/instance.mdx
website/docs/en/guide/framework/vue.mdx
website/docs/zh/api/javascript-api/instance.mdx

Add an example for get assets info after building.

docs: add example for get assets info after building

---

e2e/cases/react/react-compiler-babel/package.json
examples/react/rsbuild.config.ts
pnpm-lock.yaml

Bump React Compiler Beta to test the latest features.
https://react.dev/blog/2024/10/21/react-compiler-beta-release

 chore(deps): bump React Compiler Beta

---

website/docs/zh/guide/basic/configure-rsbuild.mdx

docs: update zh/configure-rsbuild.mdx

---

website/docs/en/guide/basic/configure-rsbuild.mdx

docs: update en/configure-rsbuild.mdx

---

packages/core/package.json
packages/core/src/types/plugin.ts
pnpm-lock.yaml
website/docs/en/plugins/dev/core.mdx
website/docs/zh/plugins/dev/core.mdx

https://github.com/web-infra-dev/rspack/releases/tag/v1.0.14

feat(deps): bump rspack 1.0.14

---

.github/ISSUE_TEMPLATE/bug-report.en-US.yml

Update the issue template for upstream bugs.

docs: update issue template for upstream bugs

---

packages/create-rsbuild/template-lit-ts/tsconfig.json
packages/create-rsbuild/template-preact-ts/tsconfig.json
packages/create-rsbuild/template-react-ts/tsconfig.json
packages/create-rsbuild/template-solid-ts/tsconfig.json
packages/create-rsbuild/template-svelte-ts/tsconfig.json
packages/create-rsbuild/template-svelte4-ts/tsconfig.json
packages/create-rsbuild/template-vanilla-ts/tsconfig.json
packages/create-rsbuild/template-vue2-ts/tsconfig.json
packages/create-rsbuild/template-vue3-ts/tsconfig.json
scripts/config/tsconfig.json

Sort tsconfig.json fields, following the official categories of TypeScript:
https://www.typescriptlang.org/tsconfig/

chore(create-rsbuild): sort tsconfig.json fields

---

packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-stylus/package.json

* feat(plugin-stylus): update dependency stylus to v0.64.0 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/3776
* feat: support `api.resolve` hook by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3785
* feat(deps): bump rspack 1.0.14 by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3793
* feat(create-rsbuild): check unused locals via tsconfig.json by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3799
* fix: `dev.assetPrefix: true` not work with `server.base` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3789
* fix: failed to load MF remote modules when using `server.base` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3790
* docs: add example for get assets info after building by @chenjiahan in …

release: 1.0.17

---

.github/renovate.json5

Bump Rslib separately so that we can better observe the effect of bumping Rslib versions.

chore(renovate): bump Rslib separately

---

packages/plugin-less/tests/__snapshots__/index.test.ts.snap
packages/plugin-less/tests/index.test.ts

Fix the Less plugin snapshot.
https://github.com/web-infra-dev/rsbuild/pull/3815

test(plugin-less): fix plugin snapshot

---

website/docs/zh/config/source/transform-import.mdx

docs: update example in transform-import.mdx

---

e2e/cases/preact/prefresh-disabled/index.test.ts
e2e/cases/preact/prefresh-disabled/src/A.jsx
e2e/cases/preact/prefresh-disabled/src/B.jsx
e2e/cases/preact/prefresh/index.test.ts
e2e/cases/preact/prefresh/src/A.jsx
e2e/cases/preact/prefresh/src/B.jsx
e2e/cases/solid/hmr/index.test.ts
e2e/cases/solid/hmr/src/A.jsx
e2e/cases/solid/hmr/src/B.jsx

Avoid writing temp files to git, rename these files to `test-temp-*`.

test(e2e): avoid writing temp files to git

---

e2e/cases/preact/basic/rsbuild.config.ts
e2e/cases/preact/prefresh/rsbuild.config.ts
packages/plugin-preact/src/index.ts
website/docs/en/plugins/list/plugin-preact.mdx
website/docs/zh/config/source/exclude.mdx
website/docs/zh/config/source/include.mdx
website/docs/zh/plugins/list/plugin-preact.mdx

Add `include` and `exclude` options for `@rsbuild/plugin-preact`.

feat(plugin-preact): add `include` and `exclude` options

---

packages/plugin-sass/src/index.ts

The same as https://github.com/web-infra-dev/rsbuild/pull/3842.

feat(plugin-sass): allow to register multiple times

---

.changeset/thick-pens-sip.md
packages/plugin-sass/src/index.ts
packages/plugin-sass/src/types.ts
packages/plugin-sass/tests/index.test.ts
website/docs/en/plugins/list/plugin-sass.mdx
website/docs/zh/plugins/list/plugin-sass.mdx

The same as https://github.com/web-infra-dev/rsbuild/pull/3843.

feat(plugin-sass): add `include` option

---

website/docs/en/config/tools/postcss.mdx
website/docs/zh/config/tools/postcss.mdx

Update `tools.postcss` config loading notes.

docs: update `tools.postcss` config loading notes

---

packages/core/package.json
pnpm-lock.yaml

feat(deps): bump rspack 1.1.0-beta.0

---

e2e/cases/server/ssr/src/assert.server.ts
e2e/cases/server/ssr/src/index.server.tsx
packages/core/src/server/runner/cjs.ts

Support `queueMicroTask` on the server side of SSR 
Fix https://github.com/web-infra-dev/rspack/issues/7826

feat: support `queueMicroTask` on the server side of SSR

---

website/docs/en/guide/basic/tailwindcss.mdx
website/docs/zh/guide/basic/tailwindcss.mdx

Improve Tailwind CSS configuration guide and add performance tip.
https://github.com/tailwindlabs/tailwindcss/issues/14229

docs(tailwindcss): improve configuration guide

---

pnpm-lock.yaml

Regenerate the pnpm lock file to reduce duplication and unused optional peer dependencies.

chore: regenerate pnpm lock file

---

packages/compat/webpack/package.json
packages/core/package.json

* feat: automatically read tsconfig paths by `references` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3882
* feat: add `layer` option to `api.transform()` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3883
* feat: add `issuerLayer` option to `api.transform()` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3884
* feat: export `ModifyWebpackConfigFn` hook type by @caohuilin in https://github.com/web-infra-dev/rsbuild/pull/3876
* docs(tailwindcss): improve configuration guide by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3877
* test: remove case for plugin-styled-components by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3878
* chore: regenerate pnpm lock file by @chenjiahan in …

release: 1.1.0-beta.1

---

website/docs/en/guide/basic/server.mdx
website/docs/zh/guide/basic/server.mdx

Add guide for assets report page.
https://github.com/web-infra-dev/rsbuild/pull/3896

docs: add guide for assets report page

---

packages/core/package.json
pnpm-lock.yaml

https://github.com/web-infra-dev/rspack/pull/8352

feat(deps): bump rspack 1.1.0

---

packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-vue/package.json

* feat(webpack): use Rslib to bundle by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3713
* feat: support `queueMicroTask` on the server side of SSR by @LingyuCoder in https://github.com/web-infra-dev/rsbuild/pull/3873
* feat: export ModifyWebpackConfigFn hook type by @caohuilin in https://github.com/web-infra-dev/rsbuild/pull/3876
* feat: automatically read tsconfig paths by `references` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3882
* feat: add `layer` option to `api.transform()` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3883
* feat: add `issuerLayer` option to `api.transform()` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3884
* feat: add `cliShortcuts.help` option by @chenjiahan in …

release: 1.1.0

---

.changeset/old-dodos-smoke.md
.changeset/pretty-flowers-jog.md
packages/plugin-svelte/package.json

* fix(plugin-svelte): failed to compile *.svslte.ts by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3918
* fix(plugin-svelte): `*.svslte.ts` files are transformed twice by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3920

release: @rsbuild/plugin-svelte@1.0.4

---

package.json
packages/compat/plugin-webpack-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-babel/package.json
packages/plugin-less/package.json
packages/plugin-preact/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-solid/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json
packages/plugin-svgr/package.json
packages/plugin-vue/package.json
pnpm-lock.yaml
scripts/test-helper/package.json

Reduce monorepo root dependencies to avoid phantom dependency issue.

chore: reduce monorepo root dependencies

---

website/docs/en/plugins/dev/index.mdx
website/docs/zh/plugins/dev/index.mdx

Add guide for referencing other Rsbuild plugins.

docs: reference other plugins

---

packages/core/package.json
pnpm-lock.yaml

feat(deps): bump rspack 1.1.1

---

website/docs/en/guide/basic/typescript.mdx
website/docs/zh/guide/basic/typescript.mdx

Explain the default behavior of the TypeScript extension alias.

docs: explain TypeScript extension alias

---

packages/core/src/server/helper.ts
packages/core/src/server/open.ts
website/docs/en/config/server/open.mdx
website/docs/zh/config/server/open.mdx

This PR follows https://github.com/web-infra-dev/rsbuild/pull/3943 to correct the opened URL.

fix: open page with the correct host

---

packages/compat/webpack/package.json
packages/core/package.json
packages/plugin-svelte/package.json

* feat: allow to configure dev.writeToDisk in environments by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3946
* feat(deps): bump rspack 1.1.1 by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3949
* feat: update the assignment method of host in baseUrl by @junxiongchu in https://github.com/web-infra-dev/rsbuild/pull/3943
* fix(plugin-svelte): failed to compile *.svslte.ts by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3918
* fix(plugin-svelte): `*.svslte.ts` files are transformed twice by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3920
* fix: proxy type error by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3936
* fix: line breaks ` \n` in error overlay messages by @ymq001 in https://github.com/web-infra-dev/rsbuild/pull/3944 …

release: 1.1.1

---

packages/core/src/helpers/stats.ts
packages/core/src/provider/createCompiler.ts
packages/core/src/server/socketServer.ts

Normalize stats with `getStatsOptions`, reduce duplicated code.

chore: normalize stats with `getStatsOptions`

---

website/docs/en/guide/basic/tailwindcss.mdx
website/docs/zh/guide/basic/tailwindcss.mdx

Add rsbuild-plugin-tailwindcss to optimize bundle size.

docs: add rsbuild-plugin-tailwindcss to optimize bundle size

---

packages/compat/plugin-webpack-swc/package.json

Related: https://github.com/web-infra-dev/rsbuild/pull/3990

release: @rsbuild/plugin-webpack-swc 1.0.8

---

packages/core/package.json
packages/plugin-sass/package.json

* feat: support print error module traces by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3986
* feat(plugin-sass): mute deprecation warnings of dependencies by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3998
* fix(webpack): move Rslib to devDependencies by @colinaaa in https://github.com/web-infra-dev/rsbuild/pull/3990
* fix: pin Rspack 1.1.0 to fix "Tsconfig not found" by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4001
* docs: add rsbuild-plugin-tailwindcss to optimize bundle size by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3991
* docs: add explanation to .env by @hangCode2001 in https://github.com/web-infra-dev/rsbuild/pull/3993
* chore: move `runCLI` from internal helpers to index export by @chenjiahan in …

release: 1.1.3

---

website/docs/en/plugins/dev/core.mdx

docs: unify handler param

---

packages/core/src/config.ts
packages/core/src/index.ts
website/docs/en/api/javascript-api/core.mdx
website/docs/zh/api/javascript-api/core.mdx

Complete the documentation for `loadConfig` options and export more types.
https://github.com/web-infra-dev/rsbuild/pull/4013

docs: complete loadConfig options

---

website/docs/en/api/start/index.mdx
website/docs/zh/api/start/index.mdx

docs: fix broken api links

---

website/docs/en/guide/framework/react.mdx
website/docs/zh/guide/framework/react.mdx

Add intro for TanStack Router and file-based routing.
https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing

docs: add intro for TanStack Router

---

README.md
README.zh-CN.md
website/docs/en/community/releases/v1-0.mdx
website/docs/en/guide/faq/general.mdx
website/docs/en/guide/start/index.mdx
website/docs/zh/community/releases/v1-0.mdx
website/docs/zh/guide/faq/general.mdx
website/docs/zh/guide/start/index.mdx

Update description for Rslib: "library build tool" -> "library development tool".

docs: update description for Rslib

---

website/docs/en/guide/migration/vite.mdx
website/docs/zh/guide/migration/vite.mdx

This pull request includes updates to the Vite configuration documentation. The changes primarily involve adding a new configuration option and correcting an existing one.

docs: update configuration migration

---

.changeset/cyan-flies-destroy.md
packages/core/package.json
packages/plugin-assets-retry/package.json

* feat: allow `output.sourceMap` to be boolean value by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4037
* feat: add `printFileSize.include` option by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4044
* feat: add `printFileSize.exclude` option by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4045
* fix: should close compiler when dev closed by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4027
* fix(plugin-assets-retry): avoid __webpack_require__.e pollution and add some try catch to be safer by @SoonIter in https://github.com/web-infra-dev/rsbuild/pull/4025
* docs(deps): bump rspress 1.37.2 by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4023
* docs: fix broken api links by @9aoy in …

release: 1.1.5

---

website/docs/en/guide/basic/typescript.mdx
website/docs/zh/guide/basic/typescript.mdx

This pull request includes updates to the TypeScript documentation to reflect a change in the integrated type checking plugin.
Related: https://github.com/rspack-contrib/rsbuild-plugin-type-check/releases/tag/v1.1.0

docs: update ts checker plugin links

---

packages/core/package.json
pnpm-lock.yaml

Bump Rspack v1.1.4
https://github.com/web-infra-dev/rspack/releases/tag/v1.1.4

feat(deps): bump Rspack v1.1.4

---

e2e/cases/server/ssr/rsbuild.config.ts
website/docs/en/guide/advanced/environments.mdx
website/docs/zh/guide/advanced/environments.mdx
website/docs/zh/guide/advanced/ssr.mdx

Update ssr environment to node environment, used same environment in doc which used in `Create SSR configuration`.
https://github.com/web-infra-dev/rsbuild/pull/4076

docs: update ssr environment to node environment

---

e2e/cases/javascript-api/build/index.test.ts
e2e/cases/javascript-api/build/src/index.js

This pull request includes changes to add a new E2E test for the JavaScript API build process.

test: add e2e case for build API

---

website/docs/en/config/performance/print-file-size.mdx
website/docs/zh/config/performance/print-file-size.mdx

This pull request adds tips to the documentation for enabling gzip compression on the server side.
- https://github.com/web-infra-dev/rsbuild/issues/3756
- https://github.com/web-infra-dev/rsbuild/discussions/2172

docs: tip for gzip compression

---

website/docs/en/guide/advanced/module-federation.mdx
website/docs/zh/guide/advanced/module-federation.mdx

This pull request includes updates to the documentation for Module Federation 2.0, specifically changing the required plugin for usage and updating the example configuration code accordingly.
https://www.npmjs.com/package/@module-federation/rsbuild-plugin

docs: update MF guides to @module-federation/rsbuild-plugin

---

website/docs/en/config/performance/chunk-split.mdx
website/docs/zh/config/performance/chunk-split.mdx

Clarify chunk-split behavior for different targets.
https://github.com/web-infra-dev/rslib/issues/354

docs: clarify chunk-split behavior for different targets

---

website/docs/en/config/resolve/dedupe.mdx
website/docs/en/guide/migration/vite.mdx
website/docs/en/guide/optimization/optimize-bundle.mdx
website/docs/zh/config/resolve/dedupe.mdx
website/docs/zh/guide/migration/vite.mdx
website/docs/zh/guide/optimization/optimize-bundle.mdx

This pull request includes updates to the documentation files to provide more information on the `resolve.dedupe` configuration. The changes add explanations and examples to help users understand the potential implications of using `resolve.dedupe`.

docs: improve dedupe guides

---

website/docs/en/config/environments.mdx
website/docs/en/config/html/template-parameters.mdx
website/docs/zh/config/environments.mdx
website/docs/zh/config/html/template-parameters.mdx

Updating the `EnvironmentConfig` interface and modifying the HTML template parameters documentation for clarity and consistency.

docs: update environment and template parameters

---

packages/compat/plugin-webpack-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json

* feat: add `resolve.dedupe` config by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4092
* feat: add `resolve.alias` and deprecate `source.alias` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4098
* feat: add `resolve.aliasStrategy` and deprecate `source.aliasStrategy` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4101
* feat: only print total size if there are more than one asset by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4072
* feat: always write manifest to disk by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4074
* feat(CLI): set default `process.title` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4083
* feat(CLI): close instance after building by @chenjiahan in …

release: 1.1.7

---

packages/core/package.json

* fix: `resolve.dedupe` may set incorrect path by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4106
* fix: improve compatibility of `source.alias` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4108
* docs: move alias config to resolve by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4109
* docs: add environment API type by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4113
* chore(deps): update all patch dependencies by @renovate in https://github.com/web-infra-dev/rsbuild/pull/4104
* chore(deps): update dependency svelte to ^5.3.1 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/4105
* chore(plugin-preact): use `resolve.alias` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4107
* chore: pin Rslib …

release: 1.1.8

---

.changeset/angry-berries-grab.md
.changeset/perfect-suns-attend.md
packages/compat/webpack/package.json
packages/core/package.json
packages/create-rsbuild/package.json
packages/plugin-assets-retry/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-svgr/package.json

* feat: make environment API result cacheable by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4126
* feat(create-rsbuild): create React 19 project by default by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4142
* feat: add `resolve.extensions` config by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4146
* fix(plugin-sass): mute import deprecation warning by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4122
* fix: correct `cliShortcuts.custom` typing by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4125
* fix(plugin-assets-retry): support `output.assetPrefix` with absolute url by @SoonIter in https://github.com/web-infra-dev/rsbuild/pull/4129
* docs: update some links by @chenjiahan in …

release: 1.1.9

---

e2e/cases/performance/preconnect/rsbuild.config.ts
packages/core/src/plugins/resourceHints.ts
packages/core/src/types/config.ts
scripts/dictionary.txt
website/docs/en/config/performance/dns-prefetch.mdx
website/docs/en/config/performance/preconnect.mdx
website/docs/zh/config/performance/dns-prefetch.mdx
website/docs/zh/config/performance/preconnect.mdx

This pull request includes several changes to improve the configuration and documentation for `preconnect` and `dns-prefetch` performance features.

docs: update preconnect and dns-prefetch configurations

---

packages/core/src/types/rsbuild.ts
website/docs/en/api/javascript-api/core.mdx
website/docs/zh/api/javascript-api/core.mdx

This pull request includes updates to the `CreateRsbuildOptions` type and corresponding documentation to improve clarity and provide additional configuration options.

docs: update `createRsbuild` options

---

packages/core/src/cli/init.ts
packages/core/src/server/cliShortcuts.ts
packages/core/src/server/devServer.ts

Should perform cleanup when closing the server / build.

fix: perform cleanup at the right time

---

website/docs/en/config/dev/lazy-compilation.mdx
website/docs/en/config/output/polyfill.mdx
website/docs/en/config/tools/css-extract.mdx
website/docs/en/config/tools/rspack.mdx
website/docs/en/plugins/list/plugin-preact.mdx
website/docs/zh/api/javascript-api/core.mdx
website/docs/zh/config/output/polyfill.mdx
website/docs/zh/config/tools/rspack.mdx

This pull request includes various updates to documentation files to correct and update links and descriptions.

docs: correct Rspack links

---

website/docs/en/guide/basic/html-template.mdx
website/docs/zh/guide/basic/html-template.mdx

Add tips for handling page titles in single-page applications (SPAs).
resolve https://github.com/web-infra-dev/rsbuild/issues/4103

docs: set title for SPA

---

.github/ISSUE_TEMPLATE/bug-report.en-US.yml
.github/ISSUE_TEMPLATE/feature-request.en-US.yml

> Issues types allow you to classify and manage your issues with a shared and consistent language across all repositories in the organization, such as bugs or tasks.
https://github.com/orgs/community/discussions/139933

chore(workflow): set Issue types

---

.changeset/chilled-falcons-fetch.md
packages/compat/webpack/package.json
packages/core/package.json

* feat(deps): bump Rspack 1.1.6 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4163
* fix: print file size should ends with a new line by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4153
* fix: perform cleanup at the right time by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4155
* fix: correct the restart build message by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4156
* fix: should not trigger dev hooks when building by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4165
* fix(webpack): use html-webpack-plugin by default by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4175
* docs: update preconnect and dns-prefetch configurations by @chenjiahan in …

release: 1.1.10

---

website/docs/en/config/server/cors.mdx
website/docs/en/guide/migration/vite.mdx
website/docs/zh/config/server/cors.mdx
website/docs/zh/guide/migration/vite.mdx

Add documentation for https://github.com/web-infra-dev/rsbuild/pull/4183.

docs: add `server.cors` config

---

packages/plugin-svelte/package.json

Changes:
- https://github.com/web-infra-dev/rsbuild/pull/4184

release: @rsbuild/plugin-svelte 1.0.6

---

website/docs/en/api/javascript-api/environment-api.mdx
website/docs/zh/api/javascript-api/environment-api.mdx

Add some basic examples for Environment Context.

docs: examples for Environment Context

---

website/rspress.config.ts

This pull request includes several changes to the `website/rspress.config.ts` file to remove unnecessary fields and updating descriptions for better clarity.

docs: clean up unnecessary Rspress config

---

e2e/cases/server/reload-html/index.test.ts
e2e/cases/server/reload-html/rsbuild.config.ts
e2e/cases/server/reload-html/src/index.html
e2e/cases/server/reload-html/src/index.js
packages/core/src/server/compilerDevMiddleware.ts
packages/core/src/server/devMiddleware.ts
packages/core/src/server/socketServer.ts

This pull request includes changes to add functionality for reloading the page when the template changes. The most important changes include updates to the E2E tests and server middleware to support this feature.
https://github.com/web-infra-dev/rsbuild/issues/4209

fix(HMR): should reload page when HTML template changed

---

website/docs/en/guide/advanced/environments.mdx
website/docs/zh/guide/advanced/environments.mdx

This pull request includes updates to the documentation for controlling the build order of environments in Rsbuild.

docs: multi environments build order

---

.github/workflows/bench-pr.yml
.github/workflows/ecosystem-ci-trigger.yml
.github/workflows/release.yml

Remove all issue_comment trigger for security.

chore(CI): remove issue_comment trigger

---

.github/workflows/release.yml
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json

- For testing the new release workflow: https://github.com/web-infra-dev/rsbuild/pull/4233
- Set npm token correctly.

release: stylus and svelte plugins v1.0.7-alpha.0

---

packages/core/package.json
packages/plugin-stylus/package.json
packages/plugin-svelte/package.json

* feat: add `server.cors` config by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4183
* feat: support for `importModule` in `api.transform` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4217
* fix(create-rsbuild): remove Svelte 4 template by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4182
* fix(plugin-svelte): require is not defined in computing sveltePath variable by @lguzzon in https://github.com/web-infra-dev/rsbuild/pull/4184
* fix(HMR): should reload page when HTML template changed by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4212
* fix: should copy publicDir to the environment distDir when multiple environments by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4220
* fix: pin rspack version by @9aoy in …

release: 1.1.11

---

packages/core/package.json

* Revert "fix: should copy publicDir to the environment distDir when multiple environments (#4220)" by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4240
* docs: update release workflow in CONTRIBUTING.md by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4238
**Full Changelog**: https://github.com/web-infra-dev/rsbuild/compare/v1.1.11...v1.1.12

release: v1.1.12

---

.github/workflows/ecosystem-ci.yml
.github/workflows/issue-close-require.yml
.github/workflows/issue-labeled.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml

Pin all actions to exact version to improve CI stability.
Renovate will help us to bump versions.

chore(CI): pin all actions to exact version

---

.github/workflows/ecosystem-ci.yml

example:
https://github.com/web-infra-dev/rsbuild/actions/runs/12480023432/job/34830143329
https://github.com/web-infra-dev/rsbuild/pull/4191#issuecomment-2560915390

chore(ci): support update eco-ci result in pr comment

---

packages/core/src/server/devServer.ts

This pull request includes several changes to the `packages/core/src/server/devServer.ts` file to improve type definitions and clean up the code. The most important changes involve updating type imports, removing unnecessary type assertions, and refining type usage in function definitions.

chore: resolve OutputFileSystem type TODO

---

website/docs/en/config/output/filename.mdx
website/docs/zh/config/output/filename.mdx

This pull request includes updates to the documentation files The changes clarify the types of files that support using functions.

docs: correct tips in filename.mdx

---

README.md
README.pt-BR.md
README.zh-CN.md
packages/compat/plugin-webpack-swc/README.md
packages/compat/webpack/README.md
packages/core/README.md
packages/create-rsbuild/README.md
packages/plugin-assets-retry/README.md
packages/plugin-babel/README.md
packages/plugin-less/README.md
packages/plugin-preact/README.md
packages/plugin-react/README.md
packages/plugin-sass/README.md
packages/plugin-solid/README.md
packages/plugin-stylus/README.md
packages/plugin-svelte/README.md
packages/plugin-svgr/README.md
packages/plugin-vue/README.md
scripts/test-helper/README.md

docs: update banner image

---

website/docs/en/community/index.mdx
website/docs/zh/community/index.mdx

This pull request includes updates to the community documentation. The changes add a new communication channel and a resource link.

docs: update community page

---

website/docs/en/guide/basic/tailwindcss.mdx
website/docs/en/guide/optimization/build-performance.mdx
website/docs/zh/guide/basic/tailwindcss.mdx
website/docs/zh/guide/optimization/build-performance.mdx

This pull request includes updates to the documentation for optimizing build performance when using Tailwind CSS. The changes include renaming sections for clarity and adding examples to avoid common pitfalls.

docs: optimize Tailwind CSS build performance

---

website/docs/en/config/source/exclude.mdx
website/docs/en/config/source/include.mdx
website/docs/en/guide/basic/configure-swc.mdx
website/docs/zh/config/source/exclude.mdx
website/docs/zh/config/source/include.mdx
website/docs/zh/guide/basic/configure-swc.mdx

This pull request includes updates to the documentation for the `source.include` and `source.exclude` configurations. The changes aim to improve clarity and provide additional usage examples.

docs: clarity`include` and `exclude` usages

---

website/docs/en/guide/basic/_meta.json
website/docs/en/guide/basic/css-usage.mdx
website/docs/zh/guide/basic/_meta.json
website/docs/zh/guide/basic/css-usage.mdx

This pull request includes updates to the Rsbuild documentation, specifically in the CSS usage guide . The changes aim to improve clarity and organization of the content.

docs: update PostCSS guide

---

packages/core/src/index.ts

export `RsbuildDevServer` type for user use.

feat: export `RsbuildDevServer` type

---

website/docs/en/plugins/dev/core.mdx
website/docs/zh/plugins/dev/core.mdx

Correct hooks, the previous way of writing would directly result in an error.

docs: call api.getNormalizedConfig in correct hook

---

packages/core/rslib.config.ts

As https://github.com/web-infra-dev/rslib/issues/452 has been resolved, we can merge similar loader build config and remove a TODO.

chore(build): merge similar loader config

---

packages/plugin-sass/package.json

Related:
- https://github.com/web-infra-dev/rsbuild/pull/4389
- https://github.com/web-infra-dev/rsbuild/pull/4398
- https://github.com/web-infra-dev/rsbuild/pull/4401

release: @rsbuild/plugin-sass v1.2.0

---

e2e/cases/cli/basic/index.test.ts
e2e/cases/cli/build-watch/index.test.ts
e2e/cases/cli/custom-config/index.test.ts
e2e/cases/cli/custom-env-dir/index.test.ts
e2e/cases/cli/custom-env-prefix/index.test.ts
e2e/cases/cli/falsy-plugins/index.test.ts
e2e/cases/cli/function-config/index.test.ts
e2e/cases/cli/inspect/index.test.ts
e2e/cases/cli/load-import-meta-env/index.test.ts
e2e/cases/cli/load-node-env/index.test.ts
e2e/cases/cli/load-process-env/index.test.ts
e2e/cases/cli/mode/index.test.ts
e2e/cases/cli/node-env/index.test.ts
e2e/cases/cli/public-env-vars/index.test.ts
e2e/cases/cli/reload-config/index.test.ts
e2e/cases/cli/root/index.test.ts
e2e/cases/cli/shortcuts/index.test.ts
e2e/cases/cli/specified-environment/index.test.ts
e2e/cases/cli/watch-files-array/index.test.ts
e2e/cases/cli/watch-files/index.test.ts
e2e/scripts/helper.ts

Increase E2E timeout limit to fix Window CI: https://github.com/web-infra-dev/rsbuild/actions/runs/12902143798/job/35975292246.

test(e2e): increase timeout limit

---

packages/core/package.json
pnpm-lock.yaml

bump Rspack v1.2.1
https://github.com/web-infra-dev/rspack/releases/tag/v1.2.1

feat(deps): bump Rspack v1.2.1

---

packages/core/package.json

release: v1.2.3

---

website/theme/index.tsx

Rsbuild v1 has been released for several months, it is time to remove the v1 announcement.

docs: remove v1 announcement

---

packages/plugin-sass/src/index.ts

Plugin sass should allow to disable source map when `rewriteUrls` is false and `output.sourceMap.css` is false.

fix(plugin-sass): allow to disable source map

---

README.md
README.pt-BR.md
README.zh-CN.md
e2e/README.md
e2e/cases/config/configure-webpack/index.test.ts
packages/compat/webpack/README.md
packages/compat/webpack/src/plugin.ts
packages/core/src/pluginManager.ts
packages/core/src/types/plugin.ts
packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
website/docs/en/community/releases/v0-1.mdx
website/docs/en/config/plugins.mdx
website/docs/en/config/tools/bundler-chain.mdx
website/docs/en/guide/basic/server.mdx
website/docs/en/guide/migration/modern-builder.mdx
website/docs/en/guide/migration/vue-cli.mdx
website/docs/en/guide/start/index.mdx
website/docs/en/plugins/dev/index.mdx
website/docs/zh/community/releases/v0-1.mdx
website/docs/zh/config/plugins.mdx
website/docs/zh/config/tools/bundler-chain.mdx
website/docs/zh/guide/basic/server.mdx
website/docs/zh/guide/migration/modern-builder.mdx
website/docs/zh/guide/migration/vue-cli.mdx
website/docs/zh/guide/start/index.mdx
website/docs/zh/plugins/dev/index.mdx
website/theme/components/Benchmark.tsx

Polish README files:
- "Webpack" should be "webpack"
- Simplify contributors graph.
- Update benchmark repo link.

docs: polish README files

---

website/docs/en/config/server/history-api-fallback.mdx
website/docs/en/config/server/html-fallback.mdx
website/docs/zh/config/server/history-api-fallback.mdx
website/docs/zh/config/server/html-fallback.mdx

This pull request includes updates to the documentation for the `server.historyApiFallback` and `server.htmlFallback` configurations. The changes aim to provide clearer instructions and additional configuration options.

docs: improve historyApiFallback and htmlFallback documentation

---

website/docs/en/api/javascript-api/core.mdx
website/docs/en/plugins/dev/hooks.mdx
website/docs/zh/api/javascript-api/core.mdx
website/docs/zh/plugins/dev/hooks.mdx

Correct onCloseDevServer example, should use plugin hooks.

docs: correct onCloseDevServer example

---

website/docs/en/config/output/legal-comments.mdx
website/docs/zh/config/output/legal-comments.mdx

This pull request includes updates to the documentation for handling legal comments. The changes primarily focus on providing more detailed explanations and examples for configuring legal comments in output files.

docs: enhance legal comments configuration documentation

---

packages/core/src/client/hmr.ts

Avoid duplicated Web Socket connections. If the fallback Web Socket URL is the same as the original URL, skip the fallback.
- https://github.com/web-infra-dev/rsbuild/pull/4474

fix(hmr): avoid duplicated connection

---

website/rspress.config.ts

Adds a new Bluesky social link to the Rspress configuration file.

docs: add Bluesky social link

---

packages/compat/webpack/package.json

Release @rsbuild/webpack v1.2.1 for https://github.com/web-infra-dev/rsbuild/pull/4460.

release: @rsbuild/webpack v1.2.1

---

e2e/cases/cli/base/index.test.ts
e2e/cases/cli/base/src/index.ts
e2e/cases/cli/base/tsconfig.json
packages/core/src/cli/commands.ts
packages/core/src/cli/init.ts
website/docs/en/guide/basic/cli.mdx
website/docs/zh/guide/basic/cli.mdx

This pull request adds support for specifying the base path with the `--base` CLI flag.
The changes include updates to the CLI commands, configuration files, and documentation.

feat(CLI): add `--base` flag

---

.github/workflows/lint.yml
.github/workflows/test.yml

Add minimal permissions to resolve some code scanning alerts.
Ref: https://github.com/web-infra-dev/rsbuild/security/code-scanning

chore(workflow): add minimal permissions

---

packages/core/src/cli/init.ts

Fix the issue that modifying the `dev.watchFiles` config in plugins is not effective.
In [source code](https://github.com/web-infra-dev/rsbuild/blob/main/packages/core/src/cli/init.ts#L47), the `loadConfig` method can't resolve the config in plugins, which can be resolved by `rsbuild.getNormalizedConfig()`. So changing the occasion for loading `dev.watchFiles` will fix the problem.
related issue #4503

fix(core): modifying the dev.watchFiles config in plugins is not effective

---

website/docs/en/config/tools/bundler-chain.mdx
website/docs/en/config/tools/rspack.mdx
website/docs/en/plugins/dev/hooks.mdx
website/docs/zh/config/tools/bundler-chain.mdx
website/docs/zh/config/tools/rspack.mdx
website/docs/zh/plugins/dev/hooks.mdx
website/theme/index.scss

Updating references to the `html-rspack-plugin` and adding details about the `utils` parameter in `modifyRspackConfig` callback functions. Additionally, there are updates to the theme settings for code blocks.
https://github.com/web-infra-dev/rsbuild/issues/4513

docs: access HTML plugin in `modifyRspackConfig`

---

pnpm-lock.yaml
website/package.json
website/theme/components/Hero.tsx

Display GitHub button on homepage:
https://github.com/rspack-contrib/rstack-doc-ui/pull/24

docs: display GitHub button on homepage

---

pnpm-lock.yaml
website/i18n.json
website/package.json
website/theme/components/Features.module.scss
website/theme/components/Features.tsx
website/theme/components/Hero.tsx
website/theme/pages/index.tsx

Update homepage i18n text to make it clearer.

docs: update homepage i18n text

---

packages/core/src/createRsbuild.ts
packages/core/src/types/plugin.ts
packages/core/src/types/rsbuild.ts
website/docs/en/plugins/dev/hooks.mdx
website/docs/en/shared/onAfterEnvironmentCompile.mdx
website/docs/en/shared/onBeforeEnvironmentCompile.mdx
website/docs/zh/plugins/dev/hooks.mdx

This pull request includes significant updates to the Rsbuild plugin API and Rsbuild instance types, along with some documentation improvements.

docs: JSDoc for Rsbuild plugin API

---

e2e/cases/server/preview/index.test.ts
packages/compat/webpack/tests/default.test.ts
packages/core/tests/default.test.ts
packages/core/tests/environments.test.ts
website/docs/en/community/releases/v0-4.mdx
website/docs/en/config/plugins.mdx
website/docs/en/guide/advanced/environments.mdx
website/docs/en/plugins/dev/core.mdx
website/docs/en/plugins/dev/hooks.mdx
website/docs/en/plugins/dev/index.mdx
website/docs/zh/community/releases/v0-4.mdx
website/docs/zh/config/plugins.mdx
website/docs/zh/guide/advanced/environments.mdx
website/docs/zh/plugins/dev/core.mdx
website/docs/zh/plugins/dev/hooks.mdx
website/docs/zh/plugins/dev/index.mdx

Simplify plugin setup method: `setup: (api) => {` -> `setup(api) {`

docs: simplify plugin setup method

---

packages/core/package.json

* feat: exclude `.d.ts` files from file size reporting by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4542
* feat: support `buildCache.buildDependencies` configuration by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4540
* feat: support generate preload link with duplicate by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4555
* feat: expose dev server instance for `onBeforeStartDevServer` hook by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4559
* fix: gzipped total file size calculation by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4539
* fix(server): remove `.mjs` suffix check when loading ESM module in runner by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4536
* docs: display GitHub button on homepage by …

release: 1.2.8

---

website/docs/en/api/javascript-api/dev-server-api.mdx
website/docs/en/config/dev/setup-middlewares.mdx
website/docs/en/guide/basic/server.mdx
website/docs/zh/api/javascript-api/dev-server-api.mdx
website/docs/zh/config/dev/setup-middlewares.mdx
website/docs/zh/guide/basic/server.mdx

This pull request includes updates to the documentation for integrating and configuring middlewares in Rsbuild. The changes improve clarity and provide more detailed instructions.

docs: improve server middlewares documentation

---

website/docs/en/guide/migration/cra.mdx
website/docs/zh/guide/migration/cra.mdx

Update CRA migration guide to add some examples and tips.

docs: update CRA migration guide

---

e2e/cases/module-federation/host/moduleFederation.config.ts
e2e/cases/module-federation/remote/moduleFederation.config.ts
packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
packages/core/tests/moduleFederation.test.ts

Correct react version for MF cases, should use ^19.0.0.

test: correct react version for MF cases

---

packages/compat/plugin-webpack-swc/README.md
packages/compat/webpack/README.md
packages/core/README.md
packages/create-rsbuild/README.md
packages/plugin-assets-retry/README.md
packages/plugin-babel/README.md
packages/plugin-less/README.md
packages/plugin-preact/README.md
packages/plugin-react/README.md
packages/plugin-sass/README.md
packages/plugin-solid/README.md
packages/plugin-stylus/README.md
packages/plugin-svelte/README.md
packages/plugin-svgr/README.md
packages/plugin-vue/README.md

Update README files for plugin packages:
- Link to the plugin documentation
- Update package name and description.
- Add badges and remove banner.

docs: update README files for plugin packages

---

e2e/cases/server/multi-server/index.test.ts
e2e/cases/server/multi-server/package.json
e2e/cases/server/multi-server/src/index.js
e2e/cases/server/multi-server/src/index1.js
pnpm-lock.yaml

Add test case about multiple rsbuild dev servers.

test: multiple rsbuild dev servers should work correctly

---

website/docs/en/guide/migration/vite.mdx
website/docs/zh/guide/migration/vite.mdx

Add a plugin migration guide for Vite plugin authors.

docs: plugin migration guide

---

packages/core/src/plugins/nonce.ts
packages/core/src/plugins/server.ts
packages/core/src/types/config.ts
website/docs/en/config/performance/profile.mdx
website/docs/en/config/server/host.mdx
website/docs/en/config/server/https.mdx
website/docs/en/config/server/port.mdx
website/docs/en/config/server/print-urls.mdx
website/docs/en/guide/basic/cli.mdx
website/docs/en/guide/basic/configure-rsbuild.mdx
website/docs/en/guide/basic/server.mdx
website/docs/zh/api/javascript-api/dev-server-api.mdx
website/docs/zh/config/performance/profile.mdx
website/docs/zh/config/server/host.mdx
website/docs/zh/config/server/https.mdx
website/docs/zh/config/server/port.mdx
website/docs/zh/config/server/print-urls.mdx
website/docs/zh/guide/advanced/environments.mdx
website/docs/zh/guide/basic/cli.mdx
website/docs/zh/guide/basic/server.mdx

Update some outdated JSDoc for Rsbuild configurations.

docs: update outdated JSDoc for Rsbuild configurations

---

.github/workflows/test.yml

shards e2e cases to reduce memory cost.
https://playwright.dev/docs/test-sharding

chore(test): shards e2e cases

---

packages/core/src/config.ts
packages/core/src/helpers/fs.ts
packages/core/src/loadEnv.ts
packages/core/src/plugins/cache.ts
packages/core/src/provider/createCompiler.ts
packages/core/src/server/open.ts
website/docs/en/guide/debug/debug-mode.mdx
website/docs/en/guide/faq/features.mdx
website/docs/zh/guide/debug/debug-mode.mdx
website/docs/zh/guide/faq/features.mdx

Add some debug logs of config file and env files loading:

feat: add debug logs of config file and env files loading

---

packages/create-rsbuild/package.json

- https://github.com/web-infra-dev/rsbuild/pull/4608
- https://github.com/web-infra-dev/rsbuild/pull/4634

release: create-rsbuild@1.2.3

---

e2e/cases/javascript-api/custom-logger/index.test.ts
e2e/cases/progress/index.test.ts
e2e/cases/rspack-profile/index.test.ts
packages/compat/webpack/src/progress/ProgressPlugin.ts
packages/compat/webpack/src/progress/helpers/nonTty.ts
packages/core/src/provider/createCompiler.ts

Print changed files when rebuild restarts for better debugging experience.
Preview:
- https://github.com/web-infra-dev/rspack/issues/9184

feat: print changed files when rebuild restarts

---

website/docs/en/plugins/list/plugin-assets-retry.mdx
website/docs/zh/plugins/list/plugin-assets-retry.mdx

supplement the definition at the beginning
https://github.com/web-infra-dev/rsbuild/pull/4643

docs(plugin-assets-retry): update type and default options

---

website/docs/en/guide/migration/cra.mdx
website/docs/zh/guide/migration/cra.mdx

This pull request includes updates to the ESLint setup instructions of the migration guide from Create React App to Rsbuild. The changes clarify the process of configuring ESLint and provide detailed steps for adding and running ESLint in Rsbuild projects.

docs: update CRA migration guide for ESLint

---

packages/core/src/index.ts

https://github.com/web-infra-dev/rspress/blob/7cbcbf44e6b77a85fb5451989c136232dbaa20e0/packages/shared/src/types/index.ts#L2

chore(types): export ConfigParams for reusing

---

website/docs/en/config/output/filename.mdx
website/docs/zh/config/output/filename.mdx

This pull request includes updates to simplify the `output.filename` configuration examples and improve the documentation clarity.

docs: improve filename configuration

---

e2e/cases/assets/filename-function/index.test.ts
e2e/cases/assets/filename-function/rsbuild.config.ts
e2e/cases/assets/filename-function/src/index.js
packages/core/src/helpers/index.ts
packages/core/src/plugins/asset.ts
packages/core/src/types/config.ts
website/docs/en/config/output/filename.mdx
website/docs/zh/config/output/filename.mdx

This pull request introduces support for dynamic asset filenames (includes font, image, media, SVG and other assets).

feat: support for dynamic asset filenames

---

packages/core/package.json

release: 1.2.12

---

website/docs/en/guide/basic/tailwindcss-v3.mdx

Sync https://github.com/web-infra-dev/rsbuild/pull/4668 to English documentation.

docs(en): install latest tailwindcss

---

packages/core/src/server/devServer.ts

fix reconnect port error when port automatically increment

fix: reconnect port error when automatically increment

---

packages/core/package.json

* perf(server): sendStats should not be called when no socket connection by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4667
* perf: remove unless `path.resolve` call by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4669
* fix: processAssets hook filter error by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4671
* fix: absolute path for favicon configuration by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4672
* fix: reconnect port error when automatically increment by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4673
* fix: improve favicon handling with better error logging by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4674
* fix: improve app icon handling with better error logging by @chenjiahan in …

release: 1.2.13

---

packages/core/package.json
packages/create-rsbuild/package.json

* fix(deps): revert @rspack/core to v1.2.5 to fix HMR by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4683
* fix(create-rsbuild): update tsconfig `moduleResolution` to lowercase by @hai-x in https://github.com/web-infra-dev/rsbuild/pull/4681
* docs: add guide for customizing JSX in React by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4680
* @hai-x made their first contribution in https://github.com/web-infra-dev/rsbuild/pull/4681
**Full Changelog**: https://github.com/web-infra-dev/rsbuild/compare/v1.2.13...v1.2.14

release: 1.2.14

---

website/docs/en/guide/framework/react.mdx

This pull request includes a minor change to the `website/docs/en/guide/framework/react.mdx` file. The change translates a comment from Chinese to English for better readability.

docs: fix react.mdx translation

---

e2e/cases/html/minify/index.test.ts
packages/core/package.json
pnpm-lock.yaml

Update @rspack/core to v1.2.7.
- https://github.com/web-infra-dev/rspack/releases/tag/v1.2.7

 feat(deps): update @rspack/core to v1.2.7

---

packages/compat/plugin-webpack-swc/package.json
packages/core/package.json
packages/create-rsbuild/package.json

release: v1.2.15

---

CONTRIBUTING.md
website/docs/en/guide/basic/static-deploy.mdx
website/docs/zh/guide/basic/static-deploy.mdx

Update contributing guide, use the latest Node.js LTS version, removes the outdated benchmarking section.

docs: update contributing guide

---

website/i18n.json
website/theme/components/Copyright.module.scss
website/theme/components/HomeFooter.module.scss
website/theme/components/HomeFooter.tsx
website/theme/pages/index.tsx

Add a footer component to home page.
Code copied from https://github.com/web-infra-dev/rspack/tree/main/website/theme/components/HomeFooter

docs(website): add footer to home page

---

website/docs/en/plugins/list/index.mdx
website/docs/zh/plugins/list/index.mdx

Update Angular Rspack link, see https://x.com/Michael_Hladky/status/1897430323295588364

docs: update Angular Rspack link

---

website/docs/zh/guide/start/quick-start.mdx

Remove MarsCode, see https://x.com/MarsCode_Team/status/1894930404312015066

docs: update quick start guide

---

.changeset/bumpy-llamas-guess.md
packages/compat/plugin-webpack-swc/src/utils.ts

use require.resolve to check react version to support pnpm catalog

feat(plugin-webpack-swc): use require.resolve to check react version to support pnpm catalog

---

packages/compat/plugin-webpack-swc/src/utils.ts
packages/compat/plugin-webpack-swc/tests/plugin.test.ts
packages/core/src/configChain.ts
packages/core/src/plugins/sri.ts
packages/core/src/provider/initConfigs.ts
packages/core/tests/external.test.ts
packages/core/tests/helpers.test.ts
packages/plugin-babel/src/helper.ts
packages/plugin-sass/src/helpers.ts

Removing redundant type assertions to simplify the code.

chore: remove unnecessary type assertions

---

website/docs/en/guide/advanced/browser-compatibility.mdx
website/docs/en/guide/advanced/browserslist.mdx
website/docs/zh/guide/advanced/browser-compatibility.mdx
website/docs/zh/guide/advanced/browserslist.mdx

Update the browser compatibility documentation, clarify default settings and compatibility information for different output targets.

docs: improve browser compatibility clarity

---

.changeset/bumpy-llamas-guess.md
packages/compat/plugin-webpack-swc/package.json
packages/core/package.json
packages/create-rsbuild/package.json

release: 1.2.17

---

packages/core/src/types/rsbuild.ts
website/docs/en/api/javascript-api/instance.mdx
website/docs/zh/api/javascript-api/instance.mdx

This pull request includes updates to the `InspectConfigOptions` type definition and its corresponding documentation. The changes enhance the clarity and completeness of the documentation by replacing comments with JSDoc annotations.

docs: improve InspectConfigOptions type

---

packages/core/src/index.ts

https://github.com/web-infra-dev/rspress/pull/1944

chore: export StartServerResult for resuing

---

packages/core/src/server/runner/cjs.ts

Add dynamic import callback to cjs vm

fix(rsbuild): add dynamic import callback to cjs vm

---

e2e/scripts/shared.ts
packages/core/src/createRsbuild.ts
packages/core/src/types/rsbuild.ts

Fix some type issues of `createRsbuild` that are introduced in https://github.com/web-infra-dev/rsbuild/pull/4778.

chore: fix some type issues of createRsbuild

---

packages/core/src/types/rsbuild.ts
website/docs/en/api/javascript-api/instance.mdx
website/docs/en/plugins/dev/hooks.mdx
website/docs/en/shared/onCloseBuild.mdx
website/docs/zh/api/javascript-api/instance.mdx
website/docs/zh/plugins/dev/hooks.mdx
website/docs/zh/shared/onCloseBuild.mdx

Clarify the behavior of the `close()` method of `rsbuild.build()` and ensure consistent across different documentation files.

docs: update description for build close method

---

packages/core/package.json

release: 1.2.19

---

website/docs/en/config/output/data-uri-limit.mdx
website/docs/en/guide/optimization/inline-assets.mdx
website/docs/zh/config/output/data-uri-limit.mdx
website/docs/zh/guide/optimization/inline-assets.mdx

Enhance the clarity and provide examples for static assets inlining.

docs: improve inline static assets

---

website/docs/en/community/releases/v0-1.mdx
website/docs/en/community/releases/v0-2.mdx
website/docs/en/community/releases/v0-3.mdx
website/docs/en/community/releases/v0-4.mdx
website/docs/en/community/releases/v0-5.mdx
website/docs/en/community/releases/v0-6.mdx
website/docs/en/community/releases/v0-7.mdx
website/docs/en/community/releases/v1-0.mdx
website/docs/zh/community/releases/v0-1.mdx
website/docs/zh/community/releases/v0-2.mdx
website/docs/zh/community/releases/v0-3.mdx
website/docs/zh/community/releases/v0-4.mdx
website/docs/zh/community/releases/v0-5.mdx
website/docs/zh/community/releases/v0-6.mdx
website/docs/zh/community/releases/v0-7.mdx
website/docs/zh/community/releases/v1-0.mdx

Update release dates for blogs to make it look better.

docs: update release dates for blogs

---

packages/core/package.json
packages/plugin-preact/package.json

release: 1.3.0-beta.0

---

packages/core/src/helpers/index.ts
packages/core/src/restart.ts
packages/core/src/server/cliShortcuts.ts

Improve restarting experience by:
- Remove the debounce to let restart trigger immediately
- Provide better logs

feat: improve restarting experience

---

packages/compat/webpack/src/createCompiler.ts

chore(webpack): improve logging condition for warning level

---

website/docs/en/guide/basic/css-usage.mdx
website/docs/zh/guide/basic/css-usage.mdx

- Add inline query parameter to CSS guide
- Add version tip

docs: add inline query parameter to CSS guide

---

packages/core/package.json
pnpm-lock.yaml

Update Rspack to v1.3.0-beta.1.
https://github.com/web-infra-dev/rspack/releases/tag/v1.3.0-beta.1

feat(deps): update Rspack to v1.3.0-beta.1

---

packages/compat/plugin-webpack-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/plugin-less/package.json
packages/plugin-sass/package.json
packages/plugin-stylus/package.json

release: 1.3.0-beta.2

---

website/docs/en/config/server/cors.mdx
website/docs/zh/config/server/cors.mdx

Update the CORS configuration documentation to provide more detailed examples and explanations for configuring the `cors.origin` option.

docs: enhance CORS configuration examples

---

packages/compat/plugin-webpack-swc/package.json
packages/compat/webpack/package.json
packages/core/package.json
packages/plugin-less/package.json
packages/plugin-sass/package.json
packages/plugin-stylus/package.json

release: 1.3.0-beta.3

---

.github/workflows/ecosystem-ci.yml

`paths-filter` requires node environment.
successful task: https://github.com/web-infra-dev/rsbuild/actions/runs/14098616314/job/39490581949

chore(workflow): fix paths-filter job in eco-ci

---

packages/core/package.json
pnpm-lock.yaml

feat(deps): update Rspack to v1.3.0

---

packages/plugin-less/src/index.ts
packages/plugin-less/tests/__snapshots__/index.test.ts.snap
packages/plugin-sass/src/index.ts
packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
packages/plugin-stylus/src/index.ts
packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap

See the comments in https://github.com/web-infra-dev/rsbuild/pull/4909 for background.

fix: improve inline rules in CSS preprocessor plugins

---

packages/plugin-less/package.json
packages/plugin-sass/package.json
packages/plugin-stylus/package.json

- https://github.com/web-infra-dev/rsbuild/pull/4909
- https://github.com/web-infra-dev/rsbuild/pull/4914

release: CSS preprocessor plugins

---

website/docs/en/config/server/compress.mdx
website/docs/zh/config/server/compress.mdx

Improved the description of gzip compression settings, updated instructions for disabling compression, and provided details on compression levels used by the dev server and preview server.

docs: improve `server.compress`

---

website/docs/zh/config/server/open.mdx

Updates the env file link to ensure it points to the correct section.

docs: fix env file anchor

---

packages/core/package.json
packages/create-rsbuild/package.json

* feat(deps): update Rspack to v1.3.1 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4941
* fix(create-rsbuild): missing eslint-plugin-vue by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4934
* fix: inject tags to HTML template without `<head>` tag by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4935
* docs: add guide for access Rspack API by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4930
* chore: simplify `isMultiCompiler` types by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4929
* chore(workflow): let prettier ignore pnpm lock file by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4931
* chore(deps): update dependency nx to ^20.7.0 by @renovate in …

release: 1.3.2

---

packages/core/package.json
packages/plugin-svgr/package.json

release: 1.3.3

---

packages/core/src/server/open.ts

If both `process.env.BROWSER` and `process.env.BROWSER_ARGS` variables are set by user, we should use `open` instead of AppleScript to open the page, as AppleScript does not support passing browser args.

fix: ensure BROWSER_ARGS works

---

website/docs/en/config/server/open.mdx
website/docs/zh/config/server/open.mdx

Add guide for passing browser arguments using the `BROWSER_ARGS` environment variable.
https://github.com/web-infra-dev/rsbuild/pull/4886

docs: add BROWSER_ARGS guide

---

website/docs/zh/plugins/dev/index.mdx

docs: fix error conditions

---

packages/create-rsbuild/package.json

- https://github.com/web-infra-dev/rsbuild/pull/4963
- https://github.com/rspack-contrib/create-rstack/releases/tag/v1.4.0
- https://github.com/web-infra-dev/rsbuild/issues/4962

release(create-rsbuild): v1.3.0

---

packages/core/package.json
packages/plugin-less/package.json

release: 1.3.4

---

packages/core/package.json
pnpm-lock.yaml

Update Rspack to v1.3.3
- https://github.com/web-infra-dev/rspack/releases/tag/v1.3.3

feat(deps): update Rspack to v1.3.3

---

packages/core/package.json
packages/plugin-babel/package.json
packages/plugin-react/package.json
packages/plugin-svgr/package.json

release: 1.3.5

---

packages/core/package.json
pnpm-lock.yaml

Update Rspack to v1.3.4
- https://github.com/web-infra-dev/rspack/releases

feat(deps): update Rspack to v1.3.4

---

website/docs/en/plugins/list/plugin-babel.mdx
website/docs/zh/plugins/list/plugin-babel.mdx

Provide additional information on the execution order of Babel and SWC, and include an example of adding a Babel plugin to handle new ECMAScript features.

docs(plugin-babel): add execution order section

---

e2e/cases/rspack-profile/index.test.ts
packages/core/src/plugins/rspackProfile.ts

Improve rspack profile plugin:
- Enhanced logging message to include color for better visibility.
- Changed comments for clarity.
- Refactored directory creation to use async fs.

feat: improve rspack profile plugin

---

packages/core/src/helpers/exitHook.ts
packages/core/src/server/gracefulShutdown.ts

Improve the handling of process termination and correct exit code in graceful shutdown.

fix: correct exit code in graceful shutdown

---

packages/plugin-svgr/package.json

Include: https://github.com/web-infra-dev/rsbuild/pull/5016

release(plugin-svgr): 1.2.0

---

website/docs/en/config/performance/profile.mdx
website/docs/zh/config/performance/profile.mdx

This pull request includes updates to the documentation for build profiling references.

docs: correct build profiling link

---

package.json
pnpm-lock.yaml
website/docs/en/guide/framework/react.mdx
website/docs/zh/guide/framework/react.mdx

- Add new sections on performance profiling using React Scan to the React framework guide.
- Update heading-case to the latest version, see https://github.com/rspack-contrib/heading-case/releases

docs: add React Scan guide

---

packages/core/src/plugins/output.ts
packages/core/src/server/devMiddlewares.ts
packages/core/src/server/helper.ts
packages/core/tests/output.test.ts
scripts/dictionary.txt

Refactor how the server port is handled, improving clarity and reducing redundancy.

refactor: streamline port handling in output and middleware logic

---

packages/core/src/config.ts
packages/core/src/provider/initConfigs.ts

Improve comments and variable naming, correct the outdated comments.

chore: improve comments and variable naming

---

packages/core/package.json

release: 1.3.8

---

packages/create-rsbuild/package.json
pnpm-lock.yaml

chore: add create-rsbuild devDependencies for a better type

---

package.json
packages/create-rsbuild/package.json
pnpm-lock.yaml

Update plugin dependencies in create-rsbuild package, fix CI issue and dependency issue in  https://github.com/web-infra-dev/rsbuild/pull/5041.

chore(deps): update plugin dependencies in create-rsbuild package

---

website/docs/en/config/performance/prefetch.mdx
website/docs/en/config/performance/preload.mdx
website/docs/zh/config/performance/prefetch.mdx
website/docs/zh/config/performance/preload.mdx

Provide more detailed usage examples for the `include` and `exclude` options in the `prefetch` and `preload` configurations.

docs: add examples for prefetch and preload filters

---

e2e/cases/node-polyfill-tip/with-protocol/index.test.ts
e2e/cases/node-polyfill-tip/without-protocol/index.test.ts
packages/core/src/helpers/format.ts

Update error message for Node.js built-in module:
- Add link for the plugin.
- Make the solutions clearer.

fix: update error message for Node.js built-in module

---

e2e/cases/server/ssr-type-module/rsbuild.config.ts
e2e/cases/server/ssr/rsbuild.config.ts
website/docs/en/api/javascript-api/dev-server-api.mdx
website/docs/en/guide/advanced/environments.mdx
website/docs/en/guide/advanced/ssr.mdx
website/docs/zh/api/javascript-api/dev-server-api.mdx
website/docs/zh/guide/advanced/environments.mdx
website/docs/zh/guide/advanced/ssr.mdx

Improve SSR example:
- Correct some invalid code.
- Keep the example easy to understand.

 docs: improve SSR example

---

packages/core/package.json

release: 1.3.10

---

packages/plugin-react/package.json

Related:
- https://github.com/web-infra-dev/rsbuild/pull/5076

release: @rsbuild/plugin-react v1.3.0

---

pnpm-lock.yaml
scripts/dictionary.txt
website/package.json
website/rspress.config.ts

docs(llms): add llms.txt with @rspress/plugin-llms
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-beta.1

docs(llms): bump to rspress@2.0.0-beta.1 and add llms.txt

---

packages/core/src/types/config.ts
website/docs/en/config/resolve/alias-strategy.mdx
website/docs/zh/config/resolve/alias-strategy.mdx
website/docs/zh/guide/advanced/alias.mdx

This pull request updates the documentation for the `resolve.aliasStrategy` configuration option, improving clarity and structure.

docs: update alias strategy documentation

---

scripts/dictionary.txt
website/docs/en/config/mode.mdx
website/docs/en/config/output/minify.mdx
website/docs/en/guide/configuration/swc.mdx
website/docs/zh/config/output/minify.mdx
website/docs/zh/guide/configuration/swc.mdx

This PR updates the documentation to provide clarification on default minifiers and instructions for switching minifiers.

docs: update guide for switching minifiers

---

website/rspress.config.ts

docs(llms.txt): add more description

docs(llms.txt): add more description

---

packages/core/package.json
pnpm-lock.yaml

Update Rspack to 1.3.7.
https://github.com/web-infra-dev/rspack/releases/tag/v1.3.7

feat(deps): update Rspack to 1.3.7

---

website/docs/en/config/plugins.mdx
website/docs/en/config/server/https.mdx
website/docs/en/config/server/middleware-mode.mdx
website/docs/zh/config/plugins.mdx
website/docs/zh/config/server/https.mdx
website/docs/zh/config/server/middleware-mode.mdx

Introducing sections on conditional and async plugin registration, updating plugin examples to use the Sass plugin, and adding external links for better context.

docs: update plugin examples with conditional and async

---

packages/core/src/server/devMiddlewares.ts
packages/core/src/server/prodServer.ts

This PR updates middleware orders to fix the proxied SSE connection.
The gzip middleware should be placed after proxy middleware to avoid breaking SSE (Server-Sent Events), but before other middlewares to ensure responses are properly compressed.
- https://github.com/web-infra-dev/rsbuild/issues/5100

fix: gzip middleware breaks SSE connection

---

e2e/cases/plugin-api/plugin-transform-error-handle/index.test.ts
packages/core/src/helpers/stats.ts

This PR focuses on improving error and warning messages in the build process by refining their formatting and handling.

fix: improve error message formatting in build stats

---

packages/core/src/server/overlay.ts

This pull request enhances the error overlay by adding a clickable link for the configuration reference.

feat: add config link to overlay footer for better accessibility

---

packages/core/package.json

release: 1.3.13

---

e2e/cases/print-file-size/basic/index.test.ts

This pull request refactors the file size logging tests to make it easier to understand and maintain while ensuring consistent validation of file size logging behavior.
- https://github.com/web-infra-dev/rsbuild/issues/5124

test(e2e): enhance file size logging assertions

---

packages/core/src/types/hooks.ts
website/docs/en/api/javascript-api/environment-api.mdx
website/docs/en/config/output/manifest.mdx
website/docs/zh/api/javascript-api/environment-api.mdx
website/docs/zh/config/output/manifest.mdx

Add guide for accessing manifest data via hooks.
https://github.com/web-infra-dev/rsbuild/pull/5140

docs: accessing manifest data via hooks

---

packages/core/src/types/plugin.ts
website/docs/en/plugins/dev/core.mdx
website/docs/zh/plugins/dev/core.mdx

This pull request updates the documentation for the `api.transform` function to provide a clearer explanation of its purpose and usage.

docs: enhance api.transform description

---

packages/core/package.json

release: 1.3.15

---

website/docs/en/plugins/dev/hooks.mdx
website/docs/zh/plugins/dev/hooks.mdx

Added an example demonstrating how to use the `cheerio` library to manipulate HTML content with a jQuery-like API in the `modifyHTML` hook.

docs: add cheerio example for HTML manipulation

---

website/docs/en/plugins/dev/core.mdx
website/docs/zh/plugins/dev/core.mdx

Added new `TransformDescriptor` fields: `issuer`, `issuerLayer`, and `with`, along with their descriptions and examples.

docs: update TransformDescriptor to include more conditions

---

packages/core/src/plugins/manifest.ts

Validate duplicated manifest filenames and throw a warning.
For example:
```js
output: {
manifest: true,
},
web: {},
node: {
output: {
target: 'node',
},
},
},
});
```
Should be:
```js
web: {
output: {
manifest: true,
},
},
node: {
output: {
target: 'node',
manifest: {
filename: 'manifest-node.json',
},
},
},
},
});
```

feat: validate duplicated manifest filenames and throw a warning

---

packages/plugin-less/package.json

Related:
- https://github.com/web-infra-dev/rsbuild/pull/5149
- https://github.com/web-infra-dev/rsbuild/actions/runs/14852139951

release: @rsbuild/plugin-less v1.2.3

---

packages/core/package.json

release: 1.3.16

---

packages/plugin-less/package.json

Related:
- https://github.com/web-infra-dev/rsbuild/pull/5181
- https://github.com/web-infra-dev/rsbuild/pull/5182

release: @rsbuild/plugin-less v1.2.4

---

packages/plugin-react/package.json

Related:
- https://github.com/web-infra-dev/rsbuild/pull/5185
- https://github.com/web-infra-dev/rsbuild/discussions/2665#discussioncomment-13058264

release: @rsbuild/plugin-react v1.3.1

---

packages/core/package.json
packages/create-rsbuild/package.json

release: 1.3.17

---

packages/core/package.json

release: 1.3.18

---

e2e/cases/server/setup-middlewares/index.test.ts

Refactors the `setupMiddlewares` test cases to improve clarity and functionality. Added a new test case to specifically validate the page reload behavior using the `static-changed` type.

test(e2e): split setupMiddleware tests to improve clarity

---

e2e/cases/rspack-profile/index.test.ts
packages/core/src/plugins/rspackProfile.ts
website/docs/en/guide/debug/build-profiling.mdx
website/docs/zh/guide/debug/build-profiling.mdx

Update Rspack profile recommended value, use `OVERVIEW` to generate smaller `trace.json` file.
- https://github.com/web-infra-dev/rspack/pull/10328
- https://github.com/web-infra-dev/rsbuild/discussions/5217#discussioncomment-13112124

docs: update Rspack profile recommended value

---

packages/core/package.json
pnpm-lock.yaml

Update @rspack/core to 1.3.10.
- https://github.com/web-infra-dev/rspack/releases/tag/v1.3.10
- https://github.com/web-infra-dev/rsbuild/issues/5193

feat(deps): update @rspack/core to 1.3.10

---

website/docs/en/guide/optimization/build-performance.mdx
website/docs/zh/guide/optimization/build-performance.mdx

Updates the build performance documentation to clarify that the optimization guidelines for Tailwind CSS specifically apply to v3. The updates also adjust related links to point to version-specific sections.

docs: fix Tailwind CSS optimization guidance link

---

packages/core/src/client/hmr.ts

Remove early exit to be bundler friendly:
- Simplified the logic by reordering conditions to check for `import.meta.webpackHot` earlier, reducing unnecessary nesting and improving readability.
- Moved the definition of the `tryApplyUpdates` function to a different location in the file for better organization and clarity.
See https://github.com/webpack/webpack/issues/19514 for more details.

refactor(hmr): remove early exit to be bundler friendly

---

website/docs/zh/plugins/list/plugin-sass.mdx

docs: improve description

---

website/docs/en/api/javascript-api/dev-server-api.mdx
website/docs/en/api/javascript-api/instance.mdx
website/docs/zh/api/javascript-api/dev-server-api.mdx
website/docs/zh/api/javascript-api/instance.mdx

Added a new section for the `close()` method in `dev-server-api.mdx`, including its type, purpose, and a usage example.

docs: add close method for dev server API

---

scripts/dictionary.txt
website/docs/en/api/javascript-api/core.mdx
website/docs/en/api/javascript-api/instance.mdx
website/docs/zh/api/javascript-api/core.mdx
website/docs/zh/api/javascript-api/instance.mdx

Update the `callerName` documentation to List Rsbuild-based tools with their `callerName` values.

docs: add available callerName values

---

website/i18n.json

Remove unused i18n config from `i18n.json`, related to https://github.com/web-infra-dev/rsbuild/pull/5251

docs: remove unused i18n config

---

packages/plugin-svelte/package.json

Related:
- https://github.com/web-infra-dev/rsbuild/pull/5270

release: @rsbuild/plugin-svelte v1.0.9

---

website/docs/en/guide/advanced/browserslist.mdx

fix typo in `en/browserslist.mdx`

docs: fix typo in `en/browserslist.mdx`

---

README.md
README.pt-BR.md
README.zh-CN.md
website/docs/en/community/index.mdx
website/docs/en/guide/start/index.mdx
website/docs/zh/community/index.mdx
website/docs/zh/guide/basic/web-workers.mdx
website/docs/zh/guide/start/index.mdx

Added a new "Rstack" section in `README.md` , detailing the components of the Rstack toolchain.
Same as https://github.com/web-infra-dev/rspack/pull/10424

docs: update Rstack introduction

---

e2e/cases/html/template-conditional-statement/index.test.ts
e2e/cases/html/template-conditional-statement/rsbuild.config.ts
e2e/cases/html/template-conditional-statement/src/index.html

This pull request adds new E2E test cases for validating the rendering of conditional statements in HTML templates.

test(e2e): add cases for template conditional statements

---

pnpm-lock.yaml
website/docs/en/guide/basic/html-template.mdx
website/docs/zh/guide/basic/html-template.mdx
website/rspress.config.ts

This pull request adds documentation to demonstrate conditional statements in HTML templates.
https://github.com/web-infra-dev/rsbuild/pull/5290

docs: template conditional statements usage

---

website/docs/en/config/output/copy.mdx
website/docs/zh/config/output/copy.mdx

This pull request  adds an example for `output.copy`.

docs: update `output.copy` examples

---

packages/core/src/server/devServer.ts
packages/core/src/server/helper.ts
packages/core/src/server/open.ts
packages/core/src/server/prodServer.ts

Replacing synchronous `node:net` imports with dynamic imports for better performance, and updating all calls to handle these changes.

perf: use dynamic imports for node:net

---

packages/core/package.json
pnpm-lock.yaml

Update @rspack/core to v1.3.12
- https://github.com/web-infra-dev/rspack/releases/tag/v1.3.12

feat(deps): update @rspack/core to v1.3.12

---

packages/core/package.json

release: 1.3.22

---

pnpm-lock.yaml
website/package.json

Update the dependencies and reduce duplications by regenerating the pnpm lock file.

chore: lock file maintenance

---

packages/plugin-react/package.json

Related:
- https://github.com/web-infra-dev/rsbuild/pull/5354

release: @rsbuild/plugin-react v1.3.2

---

packages/core/package.json
packages/plugin-preact/package.json

Release 1.4.0 beta.2

---

website/docs/en/config/server/cors.mdx

Add missing default value section to server.cors.

docs: add missing default value section to server.cors

---

packages/plugin-preact/package.json

Stablize @rsbuild/plugin-preact 1.4.0-beta.0.
- Ref: https://github.com/web-infra-dev/rsbuild/commit/289b049e807b0573a22e0b6c568b48c85e66cced

release: @rsbuild/plugin-preact v1.4.0

---

.github/pr-labeler.yml
.github/release.yml

Introduces a new release label for refactoring changes and updates the configuration files to support it.

chore:(workflow) update changelog generator to include refactor label

---

packages/core/package.json

release: 1.4.0-beta.3

---

website/docs/en/config/_meta.json
website/docs/zh/config/_meta.json

Add `logLevel` page to sidebar.

docs: add `logLevel` page to sidebar

---

packages/core/src/plugins/lazyCompilation.ts

Fix a regression introduced by https://github.com/web-infra-dev/rsbuild/pull/5431

fix: failed to enable lazy compilation in some cases

---

packages/core/package.json

release: 1.4.0-beta.5

---

website/docs/zh/config/output/externals.mdx

docs: update externals.mdx

---

packages/create-rsbuild/package.json

Related:
- https://github.com/web-infra-dev/rsbuild/pull/5458

release: create-rsbuild v1.3.4

---

e2e/cases/config/rspack-config-validate/index.test.ts
packages/core/package.json
pnpm-lock.yaml

Update @rspack/core to 1.4.0-rc.0 and fix test cases.
https://github.com/web-infra-dev/rspack/releases/tag/v1.4.0-rc.0

feat(deps): update @rspack/core to 1.4.0-rc.0

---

packages/core/package.json
packages/plugin-preact/package.json

release: 1.4.0-rc.0

---

website/docs/en/plugins/list/plugin-svelte.mdx
website/docs/zh/plugins/list/plugin-svelte.mdx

add replace solution for less alias import

docs(svelte): prefer replace for less alias import

---

package.json
pnpm-lock.yaml

Update @rstest/core to v0.0.3, see https://github.com/web-infra-dev/rstest/releases/tag/v0.0.3 for more details.

chore(deps): update @rstest/core to v0.0.3

---

packages/core/package.json
pnpm-lock.yaml

feat(deps): update @rspack/core to 1.4.0

---

packages/create-rsbuild/template-common/README.md

Update `create-rsbuild`, add a new "Learn more" section with links to the Rsbuild documentation and GitHub repository to help users explore features, APIs, and contribute to the project.

feat(create-rsbuild): update README additional resources

---

packages/core/package.json
packages/create-rsbuild/package.json

* feat(create-rsbuild): update README additional resources by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/5490
* feat: support output extra configs when `inspectConfig` by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/5483
* feat(deps): update @rspack/core to v1.4.1 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/5496
* docs: add redirect from rsbuild.dev to rsbuild.rs by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/5489
* chore(deps): update dependency @rsbuild/plugin-preact to ^1.5.0 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/5493
* chore(deps): update dependency @rsbuild/core to ^1.4.0 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/5492
* chore(deps): update all patch dependencies by @renovate …

release: 1.4.1

---

packages/core/package.json
packages/create-rsbuild/package.json

release: 1.4.2

---

packages/core/package.json
pnpm-lock.yaml

Update @rspack/core to v1.4.2
https://github.com/web-infra-dev/rspack/releases/tag/v1.4.2

feat(deps): update @rspack/core to v1.4.2

---

packages/core/package.json
packages/plugin-vue/package.json

release: 1.4.3

---

packages/plugin-react/package.json

Changes:
- https://github.com/web-infra-dev/rsbuild/pull/5524

release: @rsbuild/plugin-react v1.3.3

---

website/docs/zh/guide/basic/typescript.mdx

Apply the same change as https://github.com/web-infra-dev/rsbuild/pull/5539 to the Chinese documentation.

docs: fix typo in isolatedModules example

---

packages/core/package.json
packages/plugin-less/package.json
packages/plugin-react/package.json
packages/plugin-sass/package.json
packages/plugin-stylus/package.json
packages/plugin-svgr/package.json

release: 1.4.4

---

packages/core/package.json

release: 1.4.5

---

e2e/cases/server/ssr-type-module/index.test.ts
e2e/cases/server/ssr/index.test.ts
packages/core/package.json
pnpm-lock.yaml

update @rspack/core to v1.4.6
- https://github.com/web-infra-dev/rspack/releases/tag/v1.4.6

feat(deps): update @rspack/core to v1.4.6

---

website/docs/en/plugins/dev/core.mdx
website/docs/zh/api/javascript-api/core.mdx
website/docs/zh/api/javascript-api/instance.mdx
website/docs/zh/api/javascript-api/types.mdx
website/docs/zh/plugins/dev/core.mdx
website/docs/zh/plugins/dev/hooks.mdx

Improving clarity and consistency in wording, particularly in the descriptions of plugin API.

docs: update plugin API title

---

packages/create-rsbuild/package.json

- https://github.com/web-infra-dev/rsbuild/pull/5583
- https://github.com/web-infra-dev/rsbuild/pull/5587
- https://github.com/web-infra-dev/rsbuild/pull/5588

release: create-rsbuild v1.4.4

---

website/docs/en/guide/migration/_meta.json
website/docs/en/guide/migration/vite-plugin.mdx
website/docs/en/guide/migration/vite.mdx
website/docs/en/plugins/dev/index.mdx
website/docs/zh/guide/migration/_meta.json
website/docs/zh/guide/migration/vite-plugin.mdx
website/docs/zh/guide/migration/vite.mdx
website/docs/zh/plugins/dev/index.mdx

This pull request introduces a new section on migrating Vite plugins to Rsbuild plugins.

docs: update migration guides for plugins

---

packages/core/package.json
pnpm-lock.yaml

Update @rspack/core from v1.4.6 to v1.4.8
- https://github.com/web-infra-dev/rspack/releases/tag/v1.4.8
- https://github.com/web-infra-dev/rspack/releases/tag/v1.4.7

feat(deps): update @rspack/core to 1.4.8

---

packages/core/package.json

release: 1.4.7

---

package.json

It looks like the configuration can be further simplified.
https://github.com/bmish/check-dependency-version-consistency/blob/549968e1acdcbb7d3ef6ebdaa8f4050243faea0a/lib/package.ts#L57-L60

chore: simplify workspace config

---

website/docs/en/config/dev/setup-middlewares.mdx
website/docs/zh/config/dev/setup-middlewares.mdx

This pull request updates the documentation for the `setupMiddlewares` configuration to demonstrate how to use async functions as middleware.

docs: middleware can be an async function

---

website/docs/en/api/javascript-api/instance.mdx
website/docs/en/plugins/dev/core.mdx
website/docs/en/shared/isPluginExists.mdx
website/docs/zh/api/javascript-api/instance.mdx
website/docs/zh/plugins/dev/core.mdx
website/docs/zh/shared/isPluginExists.mdx

This pull request updates the documentation for the `isPluginExists` function, including examples of checking plugins in global and environment-specific contexts and modifications to the function signature to support an `options.environment` parameter.

docs: update plugin existence checks guide

---

packages/core/package.json

release: 1.4.8

---

packages/plugin-less/package.json

- https://github.com/web-infra-dev/rsbuild/pull/5630

release: @rsbuild/plugin-less 1.3.0

---

packages/core/src/types/plugin.ts
website/docs/en/plugins/dev/core.mdx
website/docs/zh/plugins/dev/core.mdx

Update the documentation of `apply` property for its function signature.
- https://github.com/web-infra-dev/rsbuild/pull/5653

docs(plugin): update `apply` property for its function signature

---

packages/core/package.json

release: 1.4.10

---

packages/plugin-less/package.json

Release @rsbuild/plugin-less v1.3.1:
- https://github.com/web-infra-dev/rsbuild/pull/5690
- resolve https://github.com/web-infra-dev/rsbuild/issues/5688

release: @rsbuild/plugin-less v1.3.1

---

biome.json
package.json
packages/core/src/plugins/rspackProfile.ts

This pull request includes updates to Biome config files and code to adjust file inclusion patterns and remove unnecessary rules.

chore(workflow): simplify biome rules

---

packages/core/package.json
packages/core/src/provider/build.ts
pnpm-lock.yaml

update @rspack/core to v1.4.11
- https://github.com/web-infra-dev/rspack/releases/tag/v1.4.11

feat(deps): update @rspack/core to v1.4.11

---

packages/create-rsbuild/template-lit-ts/tsconfig.json
packages/create-rsbuild/template-preact-ts/tsconfig.json
packages/create-rsbuild/template-react-ts/tsconfig.json
packages/create-rsbuild/template-react18-ts/tsconfig.json
packages/create-rsbuild/template-solid-ts/tsconfig.json
packages/create-rsbuild/template-svelte-ts/tsconfig.json
packages/create-rsbuild/template-vanilla-ts/tsconfig.json
packages/create-rsbuild/template-vue2-ts/tsconfig.json
packages/create-rsbuild/template-vue3-ts/tsconfig.json
scripts/config/tsconfig.json

Update tsconfig modules settings:
- Added `"moduleDetection": "force"`: https://www.typescriptlang.org/tsconfig/#moduleDetection
- Added `"noUncheckedSideEffectImports": true`: https://www.typescriptlang.org/tsconfig/#noUncheckedSideEffectImports
This aligns with the recommended TypeScript 5.9 options:: https://devblogs.microsoft.com/typescript/announcing-typescript-5-9/#minimal-and-updated-tsc---init

feat(create-rsbuild): update tsconfig modules settings

---

packages/core/src/cli/commands.ts
website/docs/en/api/javascript-api/core.mdx
website/docs/en/guide/basic/cli.mdx
website/docs/zh/guide/basic/cli.mdx

This pull request focuses on improving the clarity and consistency of CLI command descriptions and documentation. The main changes include rewording option descriptions for better readability, updating command help messages, and synchronizing documentation.

feat: improve command descriptions and documentations

---

packages/core/package.json
pnpm-lock.yaml

Update @rspack/core to v1.5.0-beta.0
- https://github.com/web-infra-dev/rspack/releases

feat(deps): update @rspack/core to v1.5.0-beta.0

---

packages/core/package.json

release: 1.5.0-beta.0

---

packages/core/package.json

release: 1.5.0-beta.1

---

website/docs/en/config/output/filename.mdx

Fix some formatting in filename.mdx

docs: Add missing backtick to filename.mdx

---

e2e/scripts/shared.ts

- Improve log pattern matching in test utils
- Use Set to track pending log patterns for better performance
- Add timeout handling for log pattern matching

test(e2e): improve log pattern matching in test utils

---

packages/core/package.json

release: 1.5.0-beta.4

---

website/docs/en/plugins/dev/hooks.mdx
website/docs/zh/plugins/dev/hooks.mdx

Add version information to indicate when the `modifyHTML` hook was introduced.
- https://github.com/web-infra-dev/rsbuild/pull/5145

docs: add version info for modifyHTML hook

---

examples/webpack/package.json
packages/compat/plugin-webpack-swc/src/utils.ts
packages/core/src/constants.ts
packages/core/src/helpers/index.ts
packages/core/src/hooks.ts
packages/core/src/plugins/swc.ts
packages/core/src/rspack-plugins/RsbuildHtmlPlugin.ts
packages/core/src/server/hmrFallback.ts
packages/core/src/server/runner/index.ts
packages/plugin-babel/src/plugin.ts
pnpm-lock.yaml

Improve code clarity and consistency by removing unnecessary exports and dependencies.

 chore: remove unnecessary exports and helpers

---

packages/core/package.json
packages/core/src/helpers/index.ts
pnpm-lock.yaml

- update @rspack/core to v1.5.0
- update `rspackMinVersion` to v1.5.0
- https://github.com/web-infra-dev/rspack

feat(deps): update @rspack/core to v1.5.0

---

packages/core/src/types/plugin.ts
website/docs/en/api/javascript-api/types.mdx
website/docs/zh/api/javascript-api/types.mdx

Add detailed descriptions for `RsbuildPlugin` and `RsbuildPluginAPI` types.

docs: improve plugin type documentation

---

packages/core/package.json

release: 1.5.1

---

packages/core/package.json
pnpm-lock.yaml

Update dependency `@rspack/core` to v1.5.1
- https://github.com/web-infra-dev/rspack/releases/tag/v1.5.1

feat(deps): update dependency @rspack/core to v1.5.1

---

packages/core/package.json
packages/create-rsbuild/package.json

release: v1.5.2

---

website/docs/en/guide/optimization/code-splitting.mdx
website/docs/zh/guide/optimization/code-splitting.mdx

docs: adjust the links of rspack-splitChunks

---

packages/core/package.json

release: v1.5.3

---

.github/copilot-instructions.md
AGENTS.md

- Setup the AGENTS.md file for coding agents.
- Refine instructions in `.github/copilot-instructions.md`
- https://agents.md/

docs: setup the AGENTS.md file

---

packages/create-rsbuild/package.json

- https://github.com/web-infra-dev/rsbuild/pull/6091
- https://github.com/rspack-contrib/create-rstack/pull/56

release: create-rsbuild v1.5.2

---

packages/core/package.json
packages/create-rsbuild/package.json
pnpm-lock.yaml

release: v1.5.5

---

packages/core/package.json

release: v1.5.6

---

website/docs/en/config/tools/bundler-chain.mdx
website/docs/en/config/tools/rspack.mdx
website/docs/zh/config/tools/bundler-chain.mdx
website/docs/zh/config/tools/rspack.mdx

- Added documentation for environment context parameter
- Added `rsbuild.config.ts` as the code title

docs: add documentation for environment context parameter

---

e2e/cases/server/proxy-error/index.test.ts
e2e/cases/server/proxy-mixed-rules/index.test.ts
e2e/cases/server/proxy-mixed-rules/project1/src/index.js
e2e/cases/server/proxy-mixed-rules/project2/src/index.js
e2e/cases/server/proxy-sse/index.test.ts

- Add test case for proxy mixed rules
- Update existing proxy test to simplify configuration
- Split proxy error test into separate file for better organization

test(e2e): add test case for proxy mixed rules

---

packages/core/package.json
pnpm-lock.yaml

Update dependency @rspack/core to v1.5.5: https://github.com/web-infra-dev/rspack/releases/tag/v1.5.5

feat(deps): update dependency @rspack/core to v1.5.5

---

packages/core/package.json

release: v1.5.10

---

packages/core/package.json

release: v1.5.11

---

packages/core/src/configChain.ts

Remove pug-related chain IDs as they are unused.
- https://github.com/rspack-contrib/rsbuild-plugin-pug/blob/main/src/index.ts

chore: remove pug-related chain IDs as they are unused

---

packages/compat/webpack/package.json
packages/core/package.json

release: v1.5.14
