.changeset/red-numbers-sell.md, packages/core/src/cli/init.ts, packages/core/src/config.ts, packages/core/src/createRsbuild.ts, packages/core/src/mergeConfig.ts, packages/core/src/plugins/open.ts, packages/core/tests/__snapshots__/inspect.test.ts.snap, packages/core/tests/mergeConfig.test.ts, packages/core/tests/open.test.ts, packages/shared/src/types/config/dev.ts, packages/shared/src/types/config/server.ts, website/docs/en/config/dev/before-start-url.mdx, website/docs/en/config/server/open.mdx, website/docs/en/guide/basic/cli.mdx, website/docs/en/guide/basic/server.mdx, website/docs/en/guide/start/features.mdx, website/docs/zh/config/dev/before-start-url.mdx, website/docs/zh/config/server/open.mdx, website/docs/zh/guide/basic/cli.mdx, website/docs/zh/guide/basic/server.mdx, website/docs/zh/guide/start/features.mdx, website/rspress.config.ts
Add `server.open` config and deprecate `dev.startUrl`:
- Align with Rspack dev server's [open](https://www.rspack.dev/config/dev-server#devserveropen) config.
- Allow to use in the preview server
`dev.startUrl` will be removed in 1.0.0-alpha.0.
https://github.com/web-infra-dev/rsbuild/discussions/2508#discussioncomment-9684336
=> feat: add server.open config, deprecate dev.startUrl

packages/create-rsbuild/template-prettier/.prettierignore, packages/create-rsbuild/template-prettier/.prettierrc
Let prettier ignore lock files.
=> fix(create-rsbuild): let prettier ignore lock files

packages/create-rsbuild/src/index.ts, packages/create-rsbuild/template-eslint/common-js/eslint.config.mjs, packages/create-rsbuild/template-eslint/common-js/extra-package.json, packages/create-rsbuild/template-eslint/common-ts/eslint.config.mjs, packages/create-rsbuild/template-eslint/common-ts/extra-package.json, packages/create-rsbuild/template-eslint/react-js/eslint.config.mjs, packages/create-rsbuild/template-eslint/react-js/extra-package.json, packages/create-rsbuild/template-eslint/react-ts/eslint.config.mjs, packages/create-rsbuild/template-eslint/react-ts/extra-package.json, packages/create-rsbuild/template-eslint/svelte-js/eslint.config.mjs, packages/create-rsbuild/template-eslint/svelte-js/extra-package.json, packages/create-rsbuild/template-eslint/svelte-ts/eslint.config.mjs, packages/create-rsbuild/template-eslint/svelte-ts/extra-package.json, packages/create-rsbuild/template-eslint/vue-js/eslint.config.mjs, packages/create-rsbuild/template-eslint/vue-js/extra-package.json, packages/create-rsbuild/template-eslint/vue-ts/eslint.config.mjs, packages/create-rsbuild/template-eslint/vue-ts/extra-package.json
Allow to add ESLint as linter.
Provide default lint configs for React / Vue / Svelte / common.
https://eslint.org/
=> feat(create-rsbuild): allow to add ESLint as linter

packages/shared/prebundle.config.mjs
Should external `@rspack/core` when prebundle rspack-chain.
Fix ecosystem CI: https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/9459134648/job/26059002470
=> chore: external rspack when prebundle rspack-chain

e2e/cases/styled-component/index.test.ts
Improve styled-components case and fix Rspack ecosystem CI.
- input:
```js
import styled from 'styled-components';
const div = styled.div`
color: red;
`;
```
- Rspack 0.7.1 output:
```js
const div = styled_components__WEBPACK_IMPORTED_MODULE_0___default().div`
color: red;
`;
```
- Rspack 0.7.2 output:
```js
const div = (styled_components__WEBPACK_IMPORTED_MODULE_0___default().div)`
color: red;
`;
```
see https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/9461493494/job/26062533760#step:6:2905
=> test(e2e): improve styled-components case

packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
Allow to import multiple core-js versions, as some legacy packages are still using `core-js@2` or `babel-runtime/core-js`.
resolve https://github.com/web-infra-dev/rsbuild/issues/2566
=> fix: allow to import multiple core-js versions

.changeset/short-tigers-lie.md, packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml, website/package.json
Revert Rspack to v0.7.1 to fix the `bus error` issue.
https://github.com/web-infra-dev/rspack/issues/6775
=> Revert "feat(deps): bump Rspack v0.7.2

e2e/cases/server/public-dir/publicDir.test.ts, packages/core/src/config.ts, packages/core/src/index.ts, packages/core/src/plugins/server.ts, packages/core/src/server/getDevMiddlewares.ts, packages/core/src/server/watchFiles.ts, packages/shared/src/types/config/server.ts, website/docs/en/config/server/public-dir.mdx, website/docs/zh/config/server/public-dir.mdx
Add support for multiple public dirs.
resolve https://github.com/web-infra-dev/rsbuild/issues/2410
=> feat: support for multiple public dirs

packages/plugin-assets-retry/src/index.ts, packages/plugin-babel/src/index.ts, packages/plugin-check-syntax/src/index.ts, packages/plugin-css-minimizer/src/index.ts, packages/plugin-eslint/src/index.ts, packages/plugin-image-compress/src/index.ts, packages/plugin-mdx/src/index.ts, packages/plugin-node-polyfill/src/index.ts, packages/plugin-preact/src/index.ts, packages/plugin-pug/src/index.ts, packages/plugin-rem/src/index.ts, packages/plugin-styled-components/src/index.ts, packages/plugin-svelte/src/index.ts, packages/plugin-svgr/src/index.ts, packages/plugin-toml/src/index.ts, packages/plugin-type-check/src/index.ts, packages/plugin-typed-css-modules/src/index.ts, packages/plugin-umd/src/index.ts, packages/plugin-vue-jsx/src/index.ts, packages/plugin-vue/src/index.ts, packages/plugin-vue2-jsx/src/index.ts, packages/plugin-vue2/src/index.ts, packages/plugin-yaml/src/index.ts
export all plugins name const, so user can import plugin name via `PLUGIN_XXX_NAME`.
=> feat: export plugin name const

packages/core/src/client/overlay.ts
increase overlay width from 800px to 960px to display more informations
- before:
- after:
=> feat: increase overlay width to display more informations

packages/core/src/client/format.ts, packages/core/src/helpers.ts
Only display verbose messages in prod build or debug mode.
- input:
```css
body {
color: #ff
}
```
- non-verbose:
- verbose:
=> feat: only display verbose msgs in prod build or debug mode

packages/core/tsconfig.json, packages/core/types.d.ts
Reference Rspack client module types:
https://github.com/web-infra-dev/rspack/pull/6787
=> feat: reference Rspack client module types

packages/create-rsbuild/src/index.ts, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
Should add `required: false` to allow skipping tools selection.
=> fix(create-rsbuild): should allow skipping tools selection

e2e/cases/check-syntax/basic/index.test.ts, packages/plugin-check-syntax/src/CheckSyntaxPlugin.ts, packages/plugin-check-syntax/src/helpers/printErrors.ts, website/docs/en/plugins/list/plugin-check-syntax.mdx, website/docs/zh/plugins/list/plugin-check-syntax.mdx
Print the expected ECMA version to make it more clear.
=> feat(check-syntax): print the expected ECMA version

packages/core/src/createContext.ts, packages/core/src/initPlugins.ts, packages/core/src/plugins/asset.ts, packages/core/src/plugins/html.ts, packages/core/src/plugins/output.ts, packages/core/src/plugins/wasm.ts, packages/plugin-assets-retry/src/index.ts, packages/plugin-rem/src/index.ts, packages/plugin-svgr/src/index.ts, packages/shared/src/fs.ts, packages/shared/src/types/config/output.ts
Make it easier to access `output.distPath.[name]` config, the `getDistPath()` helper is no longer required.
=> feat: make it easier to access distPath config

website/docs/404.mdx
Use the default 404 page and fix the build warning:
https://github.com/web-infra-dev/rspress/pull/1179
=> docs: use the default 404 page

packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts, packages/core/src/rspack/preload/helpers/extractChunks.ts
fix preload util type error in rspack-ecosystem-ci
https://github.com/web-infra-dev/rspack/pull/6859#issuecomment-2178531017
=> fix: preload util type assertion

packages/core/src/server/devServer.ts, packages/core/src/server/helper.ts, packages/core/tests/server.test.ts, website/docs/en/config/dev/client.mdx, website/docs/zh/config/dev/client.mdx
Fix HMR not work on online IDEs (such as [MarsCode](https://marscode.com/)).
The default  value of`client.port` should be `window.location.port` instead of `server.port`, this allows online IDEs to proxy the ws requests to dev server correctly.
- MarsCode React template https://www.marscode.com/dashboard/templates
=> fix: HMR not work on online IDEs

packages/core/src/client/hmr.ts, packages/core/src/config.ts, packages/core/src/constants.ts, packages/core/src/server/devServer.ts, packages/core/src/server/helper.ts, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/server.test.ts, packages/shared/src/types/config/dev.ts, website/docs/en/guide/advanced/hmr.mdx, website/docs/zh/guide/advanced/hmr.mdx
Apply the default dev config in the `getDefaultDevConfig` method, this can ensure that plugins can get the correct default config via `api.getNormalizedConfig()`.
=> fix: apply default dev config

packages/core/src/config.ts, packages/core/src/mergeConfig.ts, packages/core/src/plugins/open.ts, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/shared/src/types/config/dev.ts
Remove the deprecated `dev.startUrl` config, use `server.open` instead.
https://github.com/web-infra-dev/rsbuild/discussions/2508
Changes:
- Rename `dev.startUrl` to `server.open`.
- Rename `dev.beforeStartUrl` to `server.open.before`.
Motivation:
- Align with Rspack dev server's [open](https://www.rspack.dev/config/dev-server#devserveropen) config.
- Allow to use in the preview server.
=> feat!: remove deprecated `dev.startUrl`

e2e/cases/server/hmr/index.test.ts, packages/core/src/server/devServer.ts, website/docs/en/config/dev/client.mdx, website/docs/en/config/server/open.mdx, website/docs/zh/config/dev/client.mdx, website/docs/zh/config/server/open.mdx
Allow to use `'<port>'` placeholder in `client.port`.
=> feat: allow to use port placeholder in `client.port`

packages/core/src/createContext.ts, packages/core/src/plugins/entry.ts, packages/core/tests/__snapshots__/entry.test.ts.snap, packages/core/tests/entry.test.ts
support read environments source.entry config
```js
web: {
source: {
entry: {
index: './src/index.client',
},
},
},
ssr: {
source: {
entry: {
index: './src/index.ssr',
},
},
},
},
},
});
```
=> feat: support read environments source.entry config

e2e/cases/source/alias-by-target/rsbuild.config.ts, packages/core/src/plugins/resolve.ts, packages/shared/src/types/config/source.ts, website/docs/en/config/source/alias.mdx, website/docs/zh/config/source/alias.mdx
BREAKING CHANGE: remove `target` param for `source.alias`, use environment configuration instead.
- before:
```js
source: {
alias: (alias, { target }) => {
if (target === 'node') {
alias['@common'] = './src/node/common';
} else if (target === 'web') {
alias['@common'] = './src/web/common';
}
},
},
output: {
targets: ['web', 'node'],
}
};
```
- after:
```js
web: {
source: {
alias: {
'@common': './src/web/common',
},
},
output: {
target: 'web',
},
},
node: {
source: {
alias: {
'@common': './src/node/common',
},
},
output: {
target: 'node',
},
},
},
};
```
=> feat!: remove `target` param for `source.alias`

website/docs/en/config/tools/rspack.mdx, website/docs/zh/config/tools/rspack.mdx
Improve doc, support htmlPlugin param in tools.rspack utils.
=> docs: support htmlPlugin param in tools.rspack utils

website/docs/en/api/javascript-api/types.mdx, website/docs/en/config/_meta.json, website/docs/en/config/environments.mdx, website/docs/en/shared/getNormalizedConfig.mdx, website/docs/zh/api/javascript-api/types.mdx, website/docs/zh/config/_meta.json, website/docs/zh/config/environments.mdx, website/docs/zh/shared/getNormalizedConfig.mdx
User can define multiple environments configuration through `environments`.
```ts title="rsbuild.config.ts"
client: {
source: {
alias: {
'@common1': './src/web/common1',
},
entry: {
index: './src/index.client.js',
},
},
output: {
target: 'web',
},
},
ssr: {
source: {
alias: {
'@common1': './src/ssr/common1',
},
entry: {
index: './src/index.server.js',
},
},
output: {
target: 'node',
},
},
},
};
```
https://github.com/web-infra-dev/rsbuild/issues/2623
=> docs: add basic environment config

packages/core/src/createContext.ts, packages/core/src/plugins/html.ts, packages/core/src/plugins/inlineChunk.ts, packages/core/src/plugins/resourceHints.ts, packages/core/src/plugins/sri.ts, packages/plugin-assets-retry/src/index.ts, packages/shared/src/utils.ts
Enable html plugins if has html paths, so we do not need to call the `isHtmlDisabled` helper anymore.
=> chore: enable html plugins if has html paths

packages/core/src/helpers.ts
Fix failed to empty dir in some cases.
https://github.com/web-infra-dev/rsbuild/actions/runs/9610642439/job/26507536558
=> fix: failed to empty dir in some cases

packages/core/src/server/helper.ts, packages/core/tests/server.test.ts
If `target` is `node`, no HTML files will be generated, and Rsbuild should not print empty urls.
=> fix: should not print empty urls if target is node

packages/plugin-assets-retry/modern.config.ts, packages/plugin-basic-ssl/modern.config.ts, packages/plugin-eslint/modern.config.ts, packages/plugin-mdx/modern.config.ts, packages/plugin-pug/modern.config.ts, packages/plugin-rem/modern.config.ts, packages/plugin-toml/modern.config.ts, packages/plugin-umd/modern.config.ts, packages/plugin-yaml/modern.config.ts, scripts/config/tsconfig.json
Remove `"allowJs": true` from tsconfig.json, as allowJs can not be used with `"isolatedDeclarations": true`.
https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/
=> chore(config): remove allowJs true

.vscode/extensions.json, .vscode/settings.json
Add formatter config to VS Code setting.
Biome currently does not supports markdown and MDX, so we still need to use prettier as the formatter.
=> chore: add formatter config to VS Code setting

packages/core/src/helpers.ts, packages/core/src/rspack/HtmlAppIconPlugin.ts, packages/core/src/rspack/InlineChunkHtmlPlugin.ts, packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts, packages/core/src/server/devServer.ts, packages/plugin-assets-retry/src/AssetsRetryPlugin.ts, packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts, packages/shared/src/utils.ts
Handle more cases in ensureAssetPrefix helper, this allows plugins to use publicPath easily.
=> feat: handle more cases in ensureAssetPrefix helper

packages/compat/babel-preset/package.json, packages/compat/babel-preset/tests/__snapshots__/web.test.ts.snap, packages/compat/plugin-swc/package.json, packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap, packages/core/package.json, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap, pnpm-lock.yaml
- bump core-js v3.37
- bump @swc/helpers v0.5.11
https://github.com/zloirock/core-js/releases/tag/v3.37.0
=> feat(deps): bump core-js v3.37 and @swc/helpers

website/docs/en/config/tools/swc.mdx, website/docs/zh/config/tools/swc.mdx
Update relay example to use SWC plugin, the `rspackExperiments.relay` option will be removed in Rspack v1.0.0.
https://github.com/web-infra-dev/rspack/pull/6862
=> docs: update relay example to use SWC plugin

packages/core/tests/mergeConfig.test.ts, packages/plugin-styled-components/package.json, packages/plugin-styled-components/src/index.ts, packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap, pnpm-lock.yaml
Use SWC Wasm plugin instead of `rspackExperiments.styledComponents`, Rspack will remove `rspackExperiments.styledComponents` in v1.0.0.
https://github.com/web-infra-dev/rspack/pull/6862
=> feat(styled-components): use SWC Wasm plugin

packages/core/src/plugins/bundleAnalyzer.ts, website/docs/en/config/performance/bundle-analyze.mdx, website/docs/zh/config/performance/bundle-analyze.mdx
Generate bundle analyze HTML files with environment name.
=> fix: bundle analyze with environment name

.github/workflows/release-nightly.yml, e2e/cases/type-check/multiple-tsconfig/index.test.ts, e2e/cases/type-check/multiple-tsconfig/rsbuild.config.ts, e2e/cases/type-check/multiple-tsconfig/server/index.ts, e2e/cases/type-check/multiple-tsconfig/src/index.ts, e2e/cases/type-check/multiple-tsconfig/tsconfig.json, e2e/cases/type-check/multiple-tsconfig/tsconfig.server.json, packages/plugin-type-check/src/index.ts
Allow to check multiple tsconfig files, because each tsconfig.json may include different folders.
```js
web: {
source: {
tsconfigPath: './tsconfig.json',
},
},
node: {
source: {
tsconfigPath: './tsconfig.node.json',
},
},
},
});
```
=> feat(type-check): allow to check multiple tsconfig files

e2e/cases/performance/print-file-size/index.test.ts, packages/core/src/plugins/fileSize.ts
print file size grouped by environment.
before:
after:
=> feat: print file size grouped by environment

e2e/cases/nonce/basic/index.test.ts, packages/core/src/helpers.ts, packages/core/src/plugins/nonce.ts
```ts
web: {
security: {
nonce: 'CSP_NONCE_PLACEHOLDER',
},
},
web1: {
security: {
nonce: 'CSP_NONCE_PLACEHOLDER_1',
},
},
},
};
```
=> feat: support apply environment nonce config

packages/core/src/createContext.ts, packages/core/src/helpers.ts, packages/core/src/helpers/path.ts, packages/core/src/plugins/css.ts, packages/core/src/plugins/resolve.ts, packages/core/tests/helpers.test.ts
Extract the getCommonParentPath helper.
https://github.com/web-infra-dev/rsbuild/pull/2680
=> chore: extract getCommonParentPath helper

e2e/cases/source-build/components/package.json, e2e/cases/source-build/components/src/card/index.tsx, e2e/cases/source-build/index.test.ts, e2e/cases/source-build/utils2/package.json, e2e/cases/source-build/utils2/src/common/index.ts, e2e/cases/source-build/utils2/src/common/toLowerCase.ts, e2e/cases/source-build/utils2/src/common/toUpperCase.ts, e2e/cases/source-build/utils2/src/index.ts, e2e/cases/source-build/utils2/tsconfig.json, packages/plugin-source-build/src/project-utils/filter.ts, packages/plugin-source-build/src/project-utils/getDependentProjects.ts, packages/plugin-source-build/src/project/project.ts, pnpm-lock.yaml
Support for conditional exports without subpaths.
```json
// package.json
{
"exports": {
"source": "./index-module.ts",
"import": "./index-module.js",
"require": "./index-require.cjs"
},
"type": "module"
}
```
https://github.com/web-infra-dev/rsbuild/issues/2687
=> feat(source-build): support for flat conditional exports

packages/core/src/createContext.ts, packages/core/src/provider/initConfigs.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/en/api/javascript-api/types.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/types.mdx, website/env.d.ts, website/tsconfig.json
Remove `context.tsconfigPath`, use `environments[name].tsconfigPath` instead.
=> fix!: remove context.tsconfigPath

packages/core/src/plugins/lazyCompilation.ts
Remove unused lazy compilation wrapper, Rspack now supports lazy compilation + CSS.
=> fix: remove unused lazy compilation wrapper

packages/core/src/plugins/rspackProfile.ts
should not get `api.context.distPath` before config init
=> fix: rspack profile outputPath unexpected

e2e/cases/source/multiple-entry/rsbuild.config.ts, packages/core/src/createContext.ts, packages/core/src/plugins/entry.ts, packages/shared/src/types/config/source.ts, website/docs/en/config/output/override-browserslist.mdx, website/docs/en/config/source/alias.mdx, website/docs/en/config/source/entry.mdx, website/docs/zh/config/output/override-browserslist.mdx, website/docs/zh/config/source/alias.mdx, website/docs/zh/config/source/entry.mdx
BREAKING CHANGE: emove function usage of `source.entry`
Use `environments` config instead.
- before:
```js
source: {
entry({ target }) {
if (target === 'web') {
return {
index: './src/index.client.js',
};
}
if (target === 'node') {
return {
index: './src/index.server.js',
};
}
},
},
output: {
targets: ['web', 'node'],
},
};
```
- after:
```js
web: {
source: {
entry: {
index: './src/index.client.js',
},
},
output: {
target: 'web',
},
},
node: {
source: {
entry: {
index: './src/index.server.js',
},
},
output: {
target: 'node',
},
},
},
};
```
=> fix!: remove function usage of `source.entry`

packages/core/src/mergeConfig.ts, packages/core/tests/mergeConfig.test.ts
Add support for merging environments config. The `isOverridePath` helper should omit the environments name prefix.
=> feat: support for merging environments config

.github/renovate.json5, packages/compat/webpack/package.json, packages/compat/webpack/src/plugin.ts, pnpm-lock.yaml
Update copy-webpack-plugin to v11.
copy-webpack-plugin v12 requires Node 18, so we will stay on v11 until Rsbuild drops support for Node 16.
close https://github.com/web-infra-dev/rsbuild/pull/2390
=> chore(deps): update copy-webpack-plugin to v11

packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml
https://github.com/web-infra-dev/rspack/releases/tag/v0.7.5
=> chore(deps): bump rspack to 0.7.5

packages/create-rsbuild/template-lit-ts/tsconfig.json, packages/create-rsbuild/template-preact-ts/tsconfig.json, packages/create-rsbuild/template-react-ts/tsconfig.json, packages/create-rsbuild/template-solid-ts/tsconfig.json, packages/create-rsbuild/template-svelte-ts/tsconfig.json, packages/create-rsbuild/template-vanilla-ts/tsconfig.json, packages/create-rsbuild/template-vue2-ts/tsconfig.json, packages/create-rsbuild/template-vue3-ts/tsconfig.json
Enable `allowImportingTsExtensions` to allow TypeScript files to import each other with a TypeScript-specific extension like .ts, .mts, or .tsx.
https://www.typescriptlang.org/tsconfig/#allowImportingTsExtensions
=> feat(create-rsbuild): enable allowImportingTsExtensions

package.json, packages/core/src/plugins/resolve.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-rem/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-source-build/src/plugin.ts, packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap, packages/plugin-typed-css-modules/tests/__snapshots__/index.test.ts.snap, pnpm-lock.yaml
bump Rspack 1.0 canary, fix `resolve.tsConfig` types.
https://github.com/web-infra-dev/rspack/pull/6872
=> fix: bump Rspack 1.0 canary, fix types

e2e/cases/environments/outputs/index.test.ts, e2e/cases/server/environments/index.test.ts, e2e/cases/server/environments/src/index.js, e2e/cases/server/environments/src/web1.js, e2e/cases/server/print-urls/index.test.ts, packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap, packages/compat/plugin-swc/tests/plugin.test.ts, packages/core/src/cli/commands.ts, packages/core/src/mergeConfig.ts, packages/core/src/server/devServer.ts, packages/core/src/server/helper.ts, packages/core/src/server/prodServer.ts, packages/core/tests/__snapshots__/entry.test.ts.snap, packages/core/tests/__snapshots__/output.test.ts.snap, packages/core/tests/entry.test.ts, packages/core/tests/mergeConfig.test.ts, packages/core/tests/output.test.ts
print and serve multiple environments html route correctly in basic case.
When we need to serve multiple environment products, rsbuild server can run correctly in the following case: 
```ts
plugins: [pluginReact()],
web: {},
web1: {
dev: {
// assetPrefix is necessary when generating multiple environment web products, file search conflicts will occur if assetPrefix is ​​not added.
assetPrefix: 'auto',
},
source: {
entry: {
main: './src/web1.tsx',
},
},
output: {
distPath: {
root: 'dist/web1',
},
},
},
},
});
```
At this point, the print url is as follows:
```bash
- index    http://localhost:3000/
- main     http://localhost:3000/web1/main
```
Warning: not support serve multiply environments when distPath is different (non-inclusive …
=> fix: print and serve multiple environments html route correctly

e2e/cases/server/environments/index.test.ts, packages/core/src/server/devServer.ts, packages/core/src/server/getDevMiddlewares.ts, packages/shared/src/types/config/dev.ts, website/docs/en/config/dev/setup-middlewares.mdx, website/docs/zh/config/dev/setup-middlewares.mdx
add server environment api.
```ts
type RsbuildDevServer = {
...
[name: string]: {
getStats: () => Promise<Stats>;
loadBundle: <T>(entryName: string) => Promise<T>; // TODO
getTransformedHtml: (entryName: string) => Promise<string | undefined>; // TODO
}
};
};
```
#2713
=> feat: add basic server environment api

packages/plugin-typed-css-modules/src/loader.ts, packages/plugin-typed-css-modules/tests/helper.test.ts, website/docs/en/guide/faq/features.mdx, website/docs/zh/guide/faq/features.mdx
- Fix the missing auto function params for plugin-typed-css-modules.
- Prefer using `tools.rspack` instead of `tools.bundlerChain` in examples.
=> fix(typed-css-modules): missing auto function params

package.json, pnpm-lock.yaml
https://github.com/web-infra-dev/web-infra-QoS/blob/c9e4cb93b3c89fb63484f6c0646c612af9071d30/scripts/src/shared/git.ts#L78-L79
We don't use `--frozen-lockfile` here because of the cases workspace.
then get the installment result below 😅
```shell
old-canary-version(in lockfile): 0.7.5-canary-6253334-20240626035254
new-canary-version: 0.7.5-canary-cff3bb0-20240627062412
@rspack/core-canary@old-canary-version
└── @rspack/binding-canary@new-canary-version
└──  @rspack/binding-linux-x64-gnu-canary@new-canary-version
```
and we get the error
https://github.com/web-infra-dev/rspack/blob/b157267cfe989e0b45d88220945741f5382b96e1/packages/rspack/src/util/bindingVersionCheck.ts#L136
This error does not seem to terminate the entire dev process, causing our ci to be stuck. …
=> fix(ci): use canary specific version instead of npm tag

packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap
No need to disable `experiments.css` after bump Rspack 1.0 alpha, it is disabled by default.
https://github.com/web-infra-dev/rspack/pull/6910
=> fix(config): no need to disable experiments.css

e2e/cases/solid/hmr/rsbuild.config.ts, e2e/cases/solid/index.test.ts, e2e/cases/solid/ref/rsbuild.config.ts, e2e/cases/vue/jsx-basic/rsbuild.config.ts, e2e/cases/vue/jsx-hmr/rsbuild.config.ts, e2e/cases/vue/sfc-lang-jsx/rsbuild.config.ts, e2e/cases/vue/sfc-lang-tsx/rsbuild.config.ts, e2e/cases/vue2/jsx-basic/rsbuild.config.ts, e2e/cases/vue2/sfc-lang-jsx/rsbuild.config.ts, e2e/cases/vue2/sfc-lang-tsx/rsbuild.config.ts, examples/solid/rsbuild.config.ts, packages/create-rsbuild/template-solid-js/rsbuild.config.mjs, packages/create-rsbuild/template-solid-ts/rsbuild.config.ts, website/docs/en/guide/framework/solid.mdx, website/docs/en/plugins/list/plugin-solid.mdx, website/docs/en/plugins/list/plugin-vue-jsx.mdx, website/docs/en/plugins/list/plugin-vue2-jsx.mdx, website/docs/zh/guide/framework/solid.mdx, website/docs/zh/plugins/list/plugin-solid.mdx, website/docs/zh/plugins/list/plugin-vue-jsx.mdx, website/docs/zh/plugins/list/plugin-vue2-jsx.mdx
Update the pluginBabel examples to allow compiling .jsx files in the node_modules.
close https://github.com/web-infra-dev/rsbuild/issues/2727
=> docs(plugin-babel): compile jsx in node_modules

packages/plugin-babel/tests/index.test.ts, packages/plugin-styled-components/tests/index.test.ts, packages/plugin-svgr/src/index.ts, packages/plugin-svgr/tests/index.test.ts, scripts/test-helper/src/rsbuild.ts
- Prefer using matchRules helper instead of get the script test RegExp.
- Remove unused `matchLoader` helper.
=> test(ut): prefer using matchRules helper

e2e/cases/svelte/hmr/src/B.svelte, packages/plugin-svelte/src/index.ts, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap, website/docs/en/plugins/list/plugin-svelte.mdx, website/docs/zh/plugins/list/plugin-svelte.mdx
Fix plugin-svelte failed to HMR with style tag.
resolve https://github.com/web-infra-dev/rsbuild/issues/2744
=> fix(plugin-svelte): failed to HMR with style tag

e2e/cases/svelte/ts/tsconfig.json, packages/create-rsbuild/template-svelte-ts/tsconfig.json
Enable verbatimModuleSyntax for svelte to fix the compiler warning:
https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax
=> fix(create-rsbuild): enable verbatimModuleSyntax for svelte

website/docs/en/guide/faq/exceptions.mdx, website/docs/zh/guide/faq/exceptions.mdx
Fix typo in the exportsPresence example.
=> docs: fix typo in exportsPresence example

website/docs/en/plugins/dev/hooks.mdx, website/docs/zh/plugins/dev/hooks.mdx
=> docs: add modifyEnvironmentConfig hook

e2e/cases/prod-server/index.test.ts, e2e/cases/server/assetPrefix/index.test.ts, e2e/cases/server/assetPrefix/src/index.js, packages/core/src/helpers/path.ts, packages/core/src/server/compilerDevMiddleware.ts, packages/core/src/server/helper.ts, packages/core/src/server/prodServer.ts
should match resource correctly with full url assetPrefix, like below:
```ts
dev: {
assetPrefix: 'http://localhost:3000/subpath/,
},
});
```
fix: #2747
=> fix(server): should match resource correctly with full url assetPrefix

e2e/cases/assets-retry/index.test.ts, packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts, packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts, packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts, packages/plugin-assets-retry/src/types.ts, website/docs/en/plugins/list/plugin-assets-retry.mdx, website/docs/zh/plugins/list/plugin-assets-retry.mdx
1. async css chunk file will be repeatedly retried by both initialChunkRetry and asyncChunkRetry
2. fix it doesn't append script when using `publicPath: "auto"`
3. add `isAsyncChunk: boolean` to context
none
=> fix(plugin/assets-retry): repeated retrying of async css chunk

packages/compat/webpack/src/createCompiler.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/server/devServer.ts, packages/shared/src/types/hooks.ts, website/docs/en/shared/onAfterBuild.mdx, website/docs/en/shared/onAfterCreateCompiler.mdx, website/docs/en/shared/onAfterStartDevServer.mdx, website/docs/en/shared/onBeforeBuild.mdx, website/docs/en/shared/onBeforeCreateCompiler.mdx, website/docs/en/shared/onBeforeStartDevServer.mdx, website/docs/en/shared/onDevCompileDone.mdx, website/docs/zh/shared/onAfterBuild.mdx, website/docs/zh/shared/onAfterCreateCompiler.mdx, website/docs/zh/shared/onAfterStartDevServer.mdx, website/docs/zh/shared/onBeforeBuild.mdx, website/docs/zh/shared/onBeforeCreateCompiler.mdx, website/docs/zh/shared/onBeforeStartDevServer.mdx, website/docs/zh/shared/onDevCompileDone.mdx
Users can use `environment` info like follows:
```ts
api.onDevCompileDone(async ({ isFirstCompile, stats, environments }) => {
const entries = Object.keys(environments).map(e => e.entry)
})
```
https://github.com/web-infra-dev/rsbuild/pull/2680
=> feat: add environments param into rsbuild api

website/docs/en/guide/start/quick-start.mdx
just a little spelling mistake
uou -> you
=> docs: fix typo in quick-start.mdx

packages/core/src/createRsbuild.ts, packages/core/src/initPlugins.ts, packages/core/src/plugins/html.ts, packages/core/src/plugins/inlineChunk.ts, packages/core/src/plugins/manifest.ts, packages/core/src/plugins/resourceHints.ts, packages/core/src/plugins/sri.ts, packages/core/src/types.ts, packages/plugin-assets-retry/src/index.ts, packages/shared/src/types/plugin.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/en/plugins/dev/core.mdx, website/docs/en/shared/getHtmlPaths.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/plugins/dev/core.mdx, website/docs/zh/shared/getHtmlPaths.mdx
BREAKING CHANGE: Remove `api.getHtmlPath`, use environment htmlPaths  instead.
=> refactor!: use environment.htmlPaths instead of api.getHtmlPath

packages/plugin-source-build/src/plugin.ts
Avoid generating self reference as it will break the resolver.
https://github.com/oxc-project/oxc-resolver/pull/211
=> fix(plugin-source-build): avoid self reference

packages/plugin-source-build/src/plugin.ts, packages/plugin-source-build/src/types/index.ts
Dedupe the generated references and always use absolute path:
=> fix(plugin-source-build): dedupe references

packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-check-syntax/package.json, packages/plugin-css-minimizer/package.json, packages/plugin-eslint/package.json, packages/plugin-image-compress/package.json, packages/plugin-less/package.json, packages/plugin-lightningcss/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-typed-css-modules/package.json, packages/plugin-umd/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, packages/shared/package.json, scripts/config/package.json, scripts/test-helper/package.json
* feat: prettier print file size log by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/2761
* feat: add environments param into rsbuild api by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/2768
* fix(create-rsbuild): should lock alpha version by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2760
* fix(server): should match resource correctly with full url assetPrefix by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/2754
* fix(plugin/assets-retry): repeated retrying of async css chunk by @SoonIter in https://github.com/web-infra-dev/rsbuild/pull/2645
* fix(plugin-source-build): avoid self reference by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2774
* fix(plugin-source-build): dedupe references by @chenjiahan in …
=> release: 1.0.0-alpha.1

packages/core/src/server/getDevMiddlewares.ts, packages/core/src/server/prodServer.ts, packages/core/src/server/proxy.ts
Should lazy load `http-proxy-middleware`:
=> perf(core): lazy load http-proxy-middleware

packages/plugin-vue2/src/index.ts, packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap, website/docs/en/plugins/list/plugin-vue2.mdx, website/docs/zh/plugins/list/plugin-vue2.mdx
set whitespace: 'condense' for template compiler 
Consistent with vue cli compilation behavior
https://github.com/vuejs/vue-cli/pull/3853
=> feat!(plugin-vue2): update Vue 2 compiler options to condense whitespace

website/docs/en/guide/advanced/environments.mdx, website/docs/en/plugins/dev/core.mdx, website/docs/en/plugins/dev/hooks.mdx, website/docs/zh/guide/advanced/environments.mdx, website/docs/zh/plugins/dev/core.mdx, website/docs/zh/plugins/dev/hooks.mdx
add guide about how to get environment context info.
https://github.com/web-infra-dev/rsbuild/pull/2721
=> docs: add get environment context info guide

packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/config.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/moduleFederation.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/features.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap, website/docs/en/config/output/polyfill.mdx, website/docs/en/guide/advanced/browser-compatibility.mdx, website/docs/en/guide/optimization/optimize-bundle.mdx, website/docs/zh/config/output/polyfill.mdx, website/docs/zh/guide/advanced/browser-compatibility.mdx, website/docs/zh/guide/optimization/optimize-bundle.mdx
Set `output.polyfill` to `'off'` by default, this can reduce the polyfill code and generate smaller bundles by default.
If your application need polyfill, please set `output.polyfill` to `'usage'` or `'entry'`:
```ts
output: {
polyfill: 'usage'
}
};
```
See the vote on Twitter: https://x.com/rspack_dev/status/1808439138439274780
https://github.com/web-infra-dev/rsbuild/discussions/2776
=> perf!: disable polyfill injection by default

packages/core/package.json, packages/core/src/pluginHelper.ts, packages/core/src/rspack/HtmlBasicPlugin.ts, packages/core/src/rspack/InlineChunkHtmlPlugin.ts, packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts, packages/core/src/rspack/preload/helpers/doesChunkBelongToHtml.ts, packages/core/src/rspack/preload/helpers/type.ts, packages/core/src/types/config/html.ts, packages/core/src/types/config/tools.ts, packages/core/src/types/hooks.ts, packages/core/src/types/plugin.ts, packages/plugin-assets-retry/package.json, packages/plugin-assets-retry/src/AssetsRetryPlugin.ts, packages/plugin-rem/package.json, packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts, pnpm-lock.yaml, website/docs/en/config/html/template-parameters.mdx, website/docs/en/config/source/entry.mdx, website/docs/en/config/tools/bundler-chain.mdx, website/docs/en/config/tools/rspack.mdx, website/docs/en/guide/basic/html-template.mdx, website/docs/en/plugins/dev/hooks.mdx, website/docs/en/plugins/list/plugin-assets-retry.mdx, website/docs/zh/config/html/template-parameters.mdx, website/docs/zh/config/source/entry.mdx, website/docs/zh/config/tools/bundler-chain.mdx, website/docs/zh/config/tools/rspack.mdx, website/docs/zh/guide/basic/html-template.mdx, website/docs/zh/plugins/dev/hooks.mdx, website/docs/zh/plugins/list/plugin-assets-retry.mdx
Rename `html-webpack-plugin` to `html-rspack-plugin` can be confusing, so we will remove the renaming and import from `html-rspack-plugin`.
https://github.com/rspack-contrib/html-rspack-plugin
=> chore: import from html-rspack-plugin

.github/renovate.json5, packages/core/package.json, packages/core/prebundle.config.mjs, packages/core/src/plugins/fileSize.ts, packages/core/tsconfig.json, pnpm-lock.yaml
Compute gzip size in parallel. From `133ms` to `1.2ms` in a [medium sized project](https://github.com/rspack-contrib/rsbuild-arco-pro).
- before:
- after:
=> perf: compute gzip size in parallel

packages/core/src/plugins/fileSize.ts
Should read file async when printing file size.
Tested in https://github.com/liangyuetian/rsbuild-hmr-slow-demo:
- before (54ms):
- after (15ms):
=> perf: read file async when printing file size

packages/core/package.json, packages/plugin-assets-retry/package.json, packages/plugin-rem/package.json, pnpm-lock.yaml
Detailed change: https://github.com/rspack-contrib/html-rspack-plugin/commit/b8e977e14efd2c86b2a3191822ffd8359f9861fd
Tested in https://github.com/liangyuetian/rsbuild-hmr-slow-demo
- before (501ms total):
- after (249ms total):
=> perf: bump html plugin to redue entrypoints overhead

packages/core/package.json, packages/plugin-assets-retry/package.json, packages/plugin-rem/package.json, pnpm-lock.yaml
`html-rspack-plugin@5.8.0` has removed support for HTML5 Application caches, it is a deprecated feature.
Tested in https://github.com/liangyuetian/rsbuild-hmr-slow-demo
- before (74ms):
- after (10ms):
https://github.com/rspack-contrib/html-rspack-plugin/pull/9
=> perf: bump html plugin to redue appcache overhead

packages/core/src/createRsbuild.ts
Use `Promise.all()` with dynamic imports instead of awaiting one by one.
=> refactor(core): use `Promise.all` instead of one by one

packages/compat/babel-preset/package.json, packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-check-syntax/package.json, packages/plugin-image-compress/package.json, packages/plugin-less/package.json, packages/plugin-lightningcss/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-typed-css-modules/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
* perf: compute gzip size in parallel by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2813
* perf: simplify node_modules RegExps by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2816
* perf: read file async when printing file size by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2820
* perf: bump html plugin to redue entrypoints overhead by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2821
* perf: bump html plugin to redue appcache overhead by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2822
* fix: hmr failed when adding initial chunk by @SoonIter in https://github.com/web-infra-dev/rsbuild/pull/2743
* fix: failed to render page if html in public dir by @chenjiahan in …
=> release: 1.0.0-alpha.5

packages/core/package.json, packages/core/prebundle.config.mjs, pnpm-lock.yaml
postcss-loader and css-loader use `semver` to compare PostCSS ast version.
Rsbuild always uses the same PostCSS version and do not need the comparison, so we can skip this step for performance.
https://github.com/webpack-contrib/postcss-loader/blob/a442c5cc0df02a20cdf940a7e774d875cf35745d/src/index.js#L109
=> perf: skip PostCSS AST version compasion

packages/core/src/config.ts
`.mjs` and `.ts` are the most used configuration types, so we resolve them first for performance.
=> perf: resolve mjs config first

packages/core/prebundle.config.mjs, packages/core/tsconfig.json
Fix missing picocolors dependency.
resolve https://github.com/web-infra-dev/rsbuild/issues/2829
=> fix: missing picocolors dependency

e2e/cases/lazy-compilation/add-initial-chunk/index.test.ts
https://github.com/web-infra-dev/rsbuild/pull/2743#issuecomment-2213054306
=> test(e2e): skip test of hmr in windows

packages/core/package.json, packages/plugin-assets-retry/package.json, packages/plugin-rem/package.json, pnpm-lock.yaml
Use `@rspack/lite-tapable` for all packages.
https://github.com/rspack-contrib/html-rspack-plugin/pull/7
=> perf: bump html plugin to unify tapable

e2e/cases/css/css-minify-options/index.test.ts, e2e/cases/css/css-minify-options/rsbuild.config.ts, e2e/cases/css/css-minify-options/src/index.css, e2e/cases/css/css-minify-options/src/index.js, packages/core/src/plugins/minimize.ts, packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts, packages/core/src/rspack/preload/helpers/determineAsValue.ts, packages/core/src/rspack/preload/helpers/doesChunkBelongToHtml.ts, packages/core/src/rspack/preload/helpers/extractChunks.ts, packages/core/src/types/config/output.ts, website/docs/en/config/output/minify.mdx, website/docs/zh/config/output/minify.mdx
Added a new `output.minify.cssOptions` config to custom CSS minify options.
https://www.rspack.dev/plugins/rspack/lightning-css-minimizer-rspack-plugin
=> feat: allow to custom CSS minify options

packages/compat/babel-preset/package.json, packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-check-syntax/package.json, packages/plugin-image-compress/package.json, packages/plugin-less/package.json, packages/plugin-lightningcss/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-typed-css-modules/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
* feat(deps): bump Rspack 1.0.0-alpha.2 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2836
* feat: allow to custom CSS minify options by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2840
* perf: skip PostCSS AST version compasion by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2826
* perf: resolve mjs config first by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2828
* perf!: remove builtin terser HTML minimizer by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2833
* perf: bump html plugin to unify tapable by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2839
* fix: missing picocolors dependency by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2831
* docs: add environment api …
=> release: 1.0.0-alpha.6

packages/plugin-solid/src/index.ts, packages/plugin-solid/tests/__snapshots__/index.test.ts.snap
https://github.com/solidjs/vite-plugin-solid/issues/137
https://github.com/solidjs/vite-plugin-solid/pull/103
=> fix(plugin-solid): remove `@babel/preset-typescript` for resolve the babel warning

pnpm-lock.yaml, scripts/dictionary.txt, website/package.json, website/rspress.config.ts
Enable sitemap for SEO.
https://github.com/jl917/rspress-plugin-sitemap
=> docs: enable sitemap for SEO

e2e/cases/module-federation/index.test.ts, packages/core/src/plugins/moduleFederation.ts
Module Federation runtime uses ES6+ syntax, adding to include and let SWC transform it.
https://github.com/web-infra-dev/rspack/pull/7085
=> fix: transform Module Federation runtime

packages/core/src/plugins/moduleFederation.ts
Fix the incorrect WS port when using MF.
This is one of the changes that resolves https://github.com/web-infra-dev/rsbuild/discussions/2802
=> fix: incorrect WS port when using MF

packages/core/package.json, packages/plugin-assets-retry/package.json, packages/plugin-rem/package.json, pnpm-lock.yaml
bump "html-rspack-plugin": "6.0.0-beta.5" to remove lodash.
see: https://github.com/rspack-contrib/html-rspack-plugin/pull/9
=> perf: bump html plugin to remove lodash

packages/compat/webpack/tests/webpackConfig.test.ts, packages/core/src/configChain.ts, packages/core/src/index.ts, packages/core/src/pluginHelper.ts, packages/core/src/rspack/HtmlBasicPlugin.ts, packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts, packages/core/src/rspack/preload/helpers/type.ts, packages/core/src/types/hooks.ts, packages/core/src/types/plugin.ts, packages/core/src/types/thirdParty.ts, packages/plugin-assets-retry/package.json, packages/plugin-assets-retry/src/AssetsRetryPlugin.ts, packages/plugin-rem/package.json, packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts, pnpm-lock.yaml
Export `HtmlRspackPlugin` type for plugins to use.
This helps `plugin-rem` or `plugin-assets-retry` to remove the `html-rspack-plugin` dependency. We should provide more HTML-related plugin hooks for Rsbuild plugins in the future to reduce the dependency on html-rspack-plugin hooks.
=> types: export HtmlRspackPlugin type

packages/core/src/types/hooks.ts, website/docs/en/plugins/dev/hooks.mdx, website/docs/zh/plugins/dev/hooks.mdx
update mergeEnvironmentConfig type, support use userConfig override extraConfig fields.
```ts
const myPlugin = () => ({
setup: (api) => {
api.modifyEnvironmentConfig((userConfig, { mergeEnvironmentConfig }) => {
const extraConfig: EnvironmentConfig = {
source: {
// ...
},
output: {
// ...
},
};
return mergeEnvironmentConfig(extraConfig, userConfig);
});
},
});
```
=> types: allow passing user config to mergeEnvironmentConfig

packages/create-rsbuild/src/index.ts, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
Support for project name with npm scope:
```js
/**
* 1. Input: 'foo'
*    Output: folder `<cwd>/foo`, `package.json#name` -> `foo`
*
* 2. Input: 'foo/bar'
*    Output: folder -> `<cwd>/foo/bar` folder, `package.json#name` -> `bar`
*
* 3. Input: '@scope/foo'
*    Output: folder -> `<cwd>/@scope/bar` folder, `package.json#name` -> `@scope/foo`
*
* 4. Input: './foo/bar'
*    Output: folder -> `<cwd>/foo/bar` folder, `package.json#name` -> `bar`
*
* 5. Input: '/root/path/to/foo'
*    Output: folder -> `'/root/path/to/foo'` folder, `package.json#name` -> `foo`
*/
```
TODO: add e2e case for `create-rsbuild`.
https://github.com/web-infra-dev/rspack/pull/7092
=> feat(create-rsbuild): support for project name with npm scope

e2e/scripts/shared.ts, package.json, packages/compat/webpack/tests/helper.ts, packages/core/src/types/plugin.ts, pnpm-lock.yaml, scripts/test-helper/src/rsbuild.ts
Support for registering lower version Rsbuild plugins in the new version of Rsbuild core without throwing type mismatches. 
In most cases, Rsbuild core only adds new methods or properties to the API object, which means that lower version plugins will usually work fine.
Fix the following error:
=> types: fix plugins type mismatch

packages/core/src/helpers.ts, packages/core/tests/mergeConfig.test.ts, scripts/dictionary.txt
fix rspack plugin apply error, only deep merge plain object when mergeConfig.
https://www.npmjs.com/package/deepmerge#ismergeableobject
=> fix: rspack plugin apply error after merging config

packages/compat/babel-preset/package.json, packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-check-syntax/package.json, packages/plugin-image-compress/package.json, packages/plugin-less/package.json, packages/plugin-lightningcss/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-typed-css-modules/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
* types: export HtmlRspackPlugin type by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2861
* types: allow passing user config to mergeEnvironmentConfig by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/2863
* feat(create-rsbuild): support for project name with npm scope by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2874
* types: fix plugins type mismatch by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2875
* perf: prebundle html-rspack-plugin by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2870
* fix: js/css are minified when both minify.js and minify.css are false by @xc2 in https://github.com/web-infra-dev/rsbuild/pull/2865
* fix: rspack plugin apply error after merging config by @9aoy in …
=> Release: v1.0.0-alpha.8

packages/core/package.json, packages/core/prebundle.config.mjs, packages/plugin-babel/package.json, packages/plugin-babel/prebundle.config.mjs, packages/plugin-less/package.json, packages/plugin-less/prebundle.config.mjs, packages/plugin-rem/package.json, packages/plugin-rem/prebundle.config.mjs, packages/plugin-sass/package.json, packages/plugin-sass/prebundle.config.mjs, packages/plugin-svgr/package.json, packages/plugin-svgr/prebundle.config.mjs, packages/plugin-typed-css-modules/package.json, packages/plugin-typed-css-modules/prebundle.config.mjs, pnpm-lock.yaml
Prettier the compiled packages and strip comments, this change makes the compiled code more readable and also 77KB smaller.
https://github.com/rspack-contrib/prebundle/releases/tag/v1.2.0
=> perf: prettier the compiled packages

e2e/cases/css/resolve-ts-paths/index.test.ts, packages/core/package.json, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/config.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/define.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/output.test.ts.snap, packages/core/tests/minimize.test.ts, packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/package.json, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-vue/tests/__snapshots__/index.test.ts.snap, pnpm-lock.yaml
Bump Rspack 1.0.0-alpha.3.
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-alpha.3
=> feat(deps): bump Rspack 1.0.0-alpha.3

packages/core/src/plugins/target.ts
Skip calculation if the browserslist is the default value, 3.8ms saved.
=> perf: skip calculation if browserslist is default value

e2e/cases/assets-retry/index.test.ts, packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts, packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
1. url calculation when using asset_prefix
😄 should add asset_prefix/public_path
```
domain: ['https://cdn.com', 'https://cdn2.com', 'https://cdn3.com']
1: https://cdn.com/base/app1/static/js/index.js"
2: https://cdn2.com/static/js/index.js
3: https://cdn3.com/static/js/index.js
```
2. domain difference between initial chunk and async chunk
```js
pluginAssetsRetry({
domain: ['http://localhost:3030', 'http://a.com', 'http://b.com'],
onRetry(context) {
console.info('onRetry', context);
},
onSuccess(context) {
console.info('onSuccess', context);
},
onFail(context) {
console.info('onFail', context);
},
})
```
before
```js
onRetryContextList: [
{
times: 0,
domain: '<ORIGIN>/static/js/index.js',
// domain: '/'  // async
url: '<ORIGIN>/static/js/index.js',
tagName: 'script', …
```
=> fix(plugin-assets-retry): url calculation when using asset prefix

packages/core/src/server/getDevMiddlewares.ts
Support returning success code in OPTIONS requests.
=> feat: OPTIONS request return success code

packages/core/src/server/getDevMiddlewares.ts
- Change the status code from `200` to `204`, because server does not response any data.
- Move the middleware to the last as a fallback.
https://github.com/web-infra-dev/rsbuild/pull/2867
https://github.com/webpack/webpack-dev-server/pull/4559
=> fix(server): register OPTIONS fallback middleware at last

e2e/cases/cli/custom-env-dir/env/.env, e2e/cases/cli/custom-env-dir/index.test.ts, e2e/cases/cli/custom-env-dir/rsbuild.config.ts, e2e/cases/cli/custom-env-dir/src/index.js, packages/core/src/cli/commands.ts, packages/core/src/cli/init.ts, website/docs/en/guide/advanced/env-vars.mdx, website/docs/en/guide/basic/cli.mdx, website/docs/zh/guide/advanced/env-vars.mdx, website/docs/zh/guide/basic/cli.mdx
Add a new `--env-dir` option to set the env directory.
```bash
npx rsbuild dev --env-dir config
```
https://github.com/web-infra-dev/rsbuild/issues/2888
=> feat(CLI): add new --env-dir option

e2e/cases/performance/print-file-size/index.test.ts, packages/core/src/plugins/fileSize.ts, packages/core/src/types/config/performance.ts, website/docs/en/config/performance/print-file-size.mdx, website/docs/zh/config/performance/print-file-size.mdx
Add new `performance.printFileSize.compresed` option to disable gzip compression size. This can save some gzip computation time for large projects.
```ts
performance: {
printFileSize: {
compressed: false,
},
},
};
```
=> feat: allow to disable gzip compression size

README.md, README.zh-CN.md, website/docs/en/community/releases/v0-1.mdx, website/docs/en/guide/start/index.mdx, website/docs/zh/community/releases/v0-1.mdx, website/docs/zh/guide/start/index.mdx
Update benchmark graph, display the latest bench data.
https://github.com/rspack-contrib/performance-compare
=> docs: update benchmark graph

packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/core/package.json, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/html.test.ts.snap, packages/core/tests/__snapshots__/inlineChunk.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, pnpm-lock.yaml
html-rspack-plugin 6.0.0-beta.8 includes some small performance improvements.
See: https://github.com/rspack-contrib/html-rspack-plugin/commits/main/
=> perf: bump html-rspack-plugin 6.0.0-beta.8

packages/compat/webpack/modern.config.ts, packages/compat/webpack/package.json, packages/compat/webpack/tsconfig.json
`@rsbuild/webpack` type should works with moduleResolution node16+.
=> fix(type): webpack type should works with moduleResolution node16+

packages/plugin-sass/src/types.ts
Fix sass-loader additionalData missing string type.
```ts
type additionalData =
| string
| ((content: string | Buffer, loaderContext: LoaderContext) => string);
```
https://github.com/web-infra-dev/rsbuild/pull/2708
https://github.com/webpack-contrib/sass-loader?tab=readme-ov-file#additionaldata
=> fix(plugin-sass): additionalData missing string type

packages/compat/babel-preset/package.json, packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-check-syntax/package.json, packages/plugin-less/package.json, packages/plugin-lightningcss/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-typed-css-modules/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
We are releasing `1.0.1-beta.0` instead of `1.0.0-beta.0`.
This is because Rsbuild `1.0.0` is a deprecated version. Package managers will resolve `^1.0.0-beta.0` to `1.0.0`, which is unexpected.
resolve: https://github.com/web-infra-dev/rsbuild/issues/2897, https://github.com/web-infra-dev/rsbuild/issues/2864, https://github.com/web-infra-dev/rsbuild/issues/2767, https://github.com/rspack-contrib/rsbuild-plugin-umd/issues/1
* feat(CLI): add new --env-dir option by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2891
* feat: allow to disable gzip compression size by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2892
* perf: skip template evaluation when using default template by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2896
* perf: bump …
=> release: 1.0.1-beta.0

website/docs/en/config/dev/client.mdx
[doc] port value should be string instead of int
From the same doc
```
port?: string;
```
=> docs: port value should be string instead of int

packages/create-rsbuild/package.json, packages/create-rsbuild/src/index.ts, pnpm-lock.yaml
Allow to create via CLI options:
```bash
◆  Create Rsbuild Project
Usage: create-rsbuild [options]
Options:
-h, --help       display help for command
-d, --dir        create project in specified directory
-t, --template   specify the template to use
--tools          select additional tools (biome, eslint, prettier)
--override       override files in target directory
Templates:
react            react-ts
vue3             vue3-ts
vue2             vue2-ts
lit              lit-ts
preact           preact-ts
svelte           svelte-ts
solid            solid-ts
vanilla          vanilla-ts
```
I will add the document and e2e test later.
=> feat(create-rsbuild): allow to create via CLI options

examples/react/rsbuild.config.ts, packages/core/src/client/hmr.ts, packages/core/src/plugins/moduleFederation.ts, packages/core/src/types/config/dev.ts, website/docs/en/config/dev/client.mdx, website/docs/zh/config/dev/client.mdx
Allow `dev.client.port` to be a number, be consistent with `server.port`.
https://github.com/web-infra-dev/rsbuild/pull/2905
=> feat: allow dev.client.port to be a number

packages/create-rsbuild/template-lit-js/package.json, packages/create-rsbuild/template-lit-ts/package.json
lit should be a dependency instead of dev dependency.
=> fix(create-rsbuild): lit should be dependency

packages/create-rsbuild/src/index.ts
Skip tools selection when using CLI options and both `dir` and `template` are provided. tools are not required in this case.
=> fix(create-rsbuild): skip tools selection when using CLI options

e2e/cases/cli/load-node-env/.env, e2e/cases/cli/load-node-env/index.test.ts, e2e/cases/cli/load-node-env/rsbuild.config.ts, e2e/cases/cli/load-node-env/src/index.js, packages/core/src/loadEnv.ts
dotenv-expand does not override existing env vars by default, but we should allow overriding NODE_ENV, which is very common.
resolve https://github.com/web-infra-dev/rsbuild/issues/2904
https://github.com/motdotla/dotenv/issues/199
=> fix: allow setting NODE_ENV from env files

packages/compat/babel-preset/package.json, packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-check-syntax/package.json, packages/plugin-less/package.json, packages/plugin-lightningcss/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-typed-css-modules/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
* feat(create-rsbuild): allow to create via CLI options by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2903
* feat: allow dev.client.port to be a number by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2907
* fix(create-rsbuild): lit should be dependency by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2910
* fix(create-rsbuild): skip tools selection when using CLI options by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2911
* fix: es template string breaks template compiling by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2914
* fix: allow setting NODE_ENV from env files by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2915
* docs: port value should be string instead of int by @vikas5914 in …
=> release: 1.0.1-beta.1

packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
The swc plugin uses `.swc` as the cache directory by default, but `.swc` is not in the default `.gitignore`. So, in rsbuild, `.swc` should be placed in the cache root directory.
https://github.com/swc-project/swc/discussions/4023#discussioncomment-6095185
=> fix: specify SWC cache directory

e2e/cases/inspect-config/index.test.ts, packages/compat/webpack/src/inspectConfig.ts
fix webpack config inspect error when output is specified, outputPath should join with distPath.
=> fix(webpack): should generate config files correctly when output is specified

website/docs/en/plugins/dev/hooks.mdx, website/docs/en/shared/getNormalizedConfig.mdx, website/docs/zh/plugins/dev/hooks.mdx, website/docs/zh/shared/getNormalizedConfig.mdx
Add modify config tips, we can not use `modifyRsbuildConfig` to register additional Rsbuild plugins.
=> docs: add modify config tips

packages/compat/plugin-swc/src/plugin.ts, packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap, packages/compat/plugin-swc/tests/plugin.test.ts
The [output.minify.jsOptions](https://rsbuild.dev/config/output/minify#javascript-minify-options) should be passed to the `SwcMinimizerPlugin`.
=> fix: minify.jsOptions is not pass to SwcMinimizerPlugin

packages/core/src/helpers.ts
The verbose error logs are often repeated and useless, we should only print verbose error logs in debug mode.
This change makes the error log clearer and more accurate.
- before:
- after:
=> fix: only print verbose error logs in debug mode

e2e/cases/type-check/basic/index.test.ts, packages/core/src/client/format.ts
Should print `stats.file` as the file name when have build errors:
https://github.com/web-infra-dev/rspack/issues/6654
=> fix: should print stats.file as file name when have build errors

e2e/cases/plugin-api/plugin-transform-by-environments/index.test.ts, e2e/cases/plugin-api/plugin-transform-by-environments/myPlugin.ts, e2e/cases/plugin-api/plugin-transform-by-environments/rsbuild.config.ts, e2e/cases/plugin-api/plugin-transform-by-environments/src/index.js, packages/core/src/initPlugins.ts, packages/core/src/types/plugin.ts, website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Add environments as a filter of `api.transform`, example:
```js
import type { RsbuildPlugin } from '@rsbuild/core';
export const myPlugin: RsbuildPlugin = {
setup(api) {
api.transform({ test: /\.js$/, environments: ['web'] }, ({ code }) => {
return {
code: code.replace('hello', 'target is web'),
};
});
api.transform({ test: /\.js$/, environments: ['node'] }, ({ code }) => {
return {
code: code.replace('hello', 'target is node'),
};
});
},
};
```
=> feat: add environments as a filter of `api.transform`

packages/core/src/types/plugin.ts, website/docs/en/config/html/tags.mdx, website/docs/en/config/source/exclude.mdx, website/docs/en/config/tools/html-plugin.mdx, website/docs/en/guide/basic/html-template.mdx, website/docs/zh/config/html/tags.mdx, website/docs/zh/config/source/exclude.mdx, website/docs/zh/config/tools/html-plugin.mdx, website/docs/zh/guide/basic/html-template.mdx
Fix `tools.htmlPlugin` default options, the `minify` feature has been moved to `rsbuild-plugin-html-minifier-terser`.
=> docs: fix `tools.htmlPlugin` default options

website/docs/en/api/javascript-api/_meta.json, website/docs/en/api/javascript-api/environment-context.mdx, website/docs/en/api/javascript-api/instance.mdx, website/docs/en/api/javascript-api/types.mdx, website/docs/en/config/output/clean-dist-path.mdx, website/docs/en/guide/advanced/environments.mdx, website/docs/en/plugins/dev/core.mdx, website/docs/zh/api/javascript-api/_meta.json, website/docs/zh/api/javascript-api/environment-context.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/types.mdx, website/docs/zh/config/output/clean-dist-path.mdx, website/docs/zh/guide/advanced/environments.mdx, website/docs/zh/plugins/dev/core.mdx
Move environment context to separate page, and we can add more examples / properties to this page in the future.
=> docs: move environment context to separate page

packages/core/src/initPlugins.ts, packages/core/src/types/plugin.ts
Allow to access environment context in the process assets plugin API.
=> feat: allow to access environment context in process assets

examples/react/rsbuild.config.ts, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/core/src/plugins/sri.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Use new processAssets api to handle SRI.
https://github.com/web-infra-dev/rsbuild/pull/2966
=> refactor: use new processAssets api to handle SRI

packages/plugin-rem/src/helpers.ts, packages/plugin-rem/src/index.ts
Use new processAssets api to emit REM script.
https://github.com/web-infra-dev/rsbuild/pull/2966
=> refactor(plugin-rem): use new processAssets api

packages/core/src/server/getDevMiddlewares.ts
Addressed an issue causing HTTP 404 errors for `[hash].hot-update.json` files when using the `OPTIONS` method, leading to CORS problems.
=> fix: exclude method options when checking `[hash].hot-update.json`

e2e/cases/svg/svgr-exclude-importer/index.test.ts, e2e/cases/svg/svgr-exclude/index.test.ts, e2e/cases/svg/svgr-external-react/index.test.ts, e2e/cases/svg/svgr-named-export-component/index.test.ts, e2e/cases/svg/svgr-override-svgo-options/index.test.ts, e2e/cases/svg/svgr-override-svgo-options/rsbuild.config.ts, e2e/cases/svg/svgr-override-svgo-options/src/App.jsx, e2e/cases/svg/svgr-override-svgo-options/src/index.js, e2e/cases/svg/svgr-override-svgo-options/src/with-id.svg, packages/plugin-svgr/package.json, packages/plugin-svgr/src/index.ts, pnpm-lock.yaml, website/docs/en/plugins/list/plugin-svgr.mdx, website/docs/zh/plugins/list/plugin-svgr.mdx
Should dedupe SVGO plugins config after merging user config with the default config.
resolve https://github.com/web-infra-dev/rsbuild/issues/2978
=> fix(plugin-svgr): dedupe SVGO plugins config

packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-check-syntax/package.json, packages/plugin-less/package.json, packages/plugin-lightningcss/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
* feat: add new plugin API to process assets by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2966
* feat: allow to process assets for specific target by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2967
* feat: allow to access environment context in transform API by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2968
* feat: allow to access environment context in process assets by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2970
* feat: allow to access compiler in modifyHTMLTags hook by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2975
* fix: exclude method options when checking `[hash].hot-update.json` by @huuduy005 in https://github.com/web-infra-dev/rsbuild/pull/2977
* fix(plugin-svgr): dedupe SVGO plugins …
=> release: 1.0.1-beta.4

packages/core/src/initPlugins.ts, packages/core/src/plugins/appIcon.ts, packages/core/src/plugins/sri.ts, packages/core/src/types/plugin.ts, packages/plugin-assets-retry/src/AssetsRetryPlugin.ts, packages/plugin-rem/src/index.ts
Ad sources param to `api.processAssets`, this is a shorthand for `compiler.webpack.sources.RawSource`.
https://github.com/webpack/webpack-sources
=> feat: add sources param to api.processAssets

website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Add `api.processAssets` API to our document.
https://github.com/web-infra-dev/rsbuild/pull/2966
https://github.com/web-infra-dev/rspack/pull/7274
=> docs: add `api.processAssets` API

website/docs/en/plugins/dev/index.mdx, website/docs/zh/plugins/dev/index.mdx
correct `onAfterCreateCompiler` example in 'Modifying Rspack Configuration' chapter.
=> docs: correct onAfterCreateCompiler example

e2e/cases/environments/vue-react-plugins/index.test.ts, e2e/cases/environments/vue-react-plugins/rsbuild.config.ts, e2e/cases/environments/vue-react-plugins/src/react/App.tsx, e2e/cases/environments/vue-react-plugins/src/react/index.ts, e2e/cases/environments/vue-react-plugins/src/vue/A.jsx, e2e/cases/environments/vue-react-plugins/src/vue/index.js, packages/core/src/index.ts, packages/plugin-preact/src/index.ts, packages/plugin-rem/src/index.ts, packages/plugin-source-build/src/plugin.ts, packages/plugin-styled-components/src/index.ts, packages/plugin-vue/src/index.ts, packages/plugin-vue2/src/index.ts, website/docs/en/plugins/dev/hooks.mdx, website/docs/zh/plugins/dev/hooks.mdx
use `modifyEnvironmentConfig` instead of `modifyRsbuildConfig`, make more plugins support used as environment plugin.
https://github.com/web-infra-dev/rsbuild/pull/2986
=> feat: more plugins support used as environment plugin

e2e/cases/server/ssr/index.test.ts, e2e/package.json
After adding the Node.js `NODE_OPTIONS=--experimental-vm-modules` flag, our CI becomes unstable and often hangs. This PR removes it to try to fix CI.
https://github.com/web-infra-dev/rsbuild/actions/runs/10059324704
https://github.com/web-infra-dev/rsbuild/actions/runs/10058072059
https://github.com/web-infra-dev/rsbuild/actions/runs/10056127743
https://github.com/web-infra-dev/rsbuild/actions/runs/10055617969
https://github.com/web-infra-dev/rsbuild/actions/runs/10037914046/job/27738733628
https://github.com/web-infra-dev/rsbuild/actions/runs/10055129307/job/27791129689
=> test(e2e): try to fix CI failures

e2e/cases/cli/vue/rsbuild.config.mjs, packages/core/src/initPlugins.ts
Only listen to process exit event when the `onExit` hook is used, fix the following warning when creating many Rsbuild instances:
=> fix: only listen to process exit when onExit hook is used

e2e/cases/plugin-api/plugin-on-exit-hook/index.test.ts, e2e/cases/plugin-api/plugin-on-exit-hook/run.mjs, e2e/cases/plugin-api/plugin-on-exit-hook/src/index.js
Add e2e case for the `onExit` hook.
https://github.com/web-infra-dev/rsbuild/pull/2998
=> test: add e2e case for onExit hook

packages/core/src/types/thirdParty.ts
Fix css-loader type declaration is outdated.
- https://github.com/webpack-contrib/css-loader/releases/tag/v6.0.0
- https://github.com/webpack-contrib/css-loader?tab=readme-ov-file
=> fix: css-loader type declaration is outdated

website/theme/components/Benchmark.tsx
- fix build typo in the benchmark, `bold` -> `build`.
=> docs: fix build typo in the benchmark

e2e/cases/plugin-api/plugin-process-assets-by-environments/index.test.ts, e2e/cases/plugin-api/plugin-process-assets-by-environments/myPlugin.ts, e2e/cases/plugin-api/plugin-process-assets-by-environments/rsbuild.config.ts, e2e/cases/plugin-api/plugin-process-assets-by-environments/src/index.css, e2e/cases/plugin-api/plugin-process-assets-by-environments/src/index.js, packages/core/src/initPlugins.ts, packages/core/src/pluginManager.ts, packages/core/src/types/plugin.ts, website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Add environments as a filter of `api.processAssets`, example:
```js
export const myPlugin: RsbuildPlugin = {
setup(api) {
api.processAssets(
{ stage: 'summarize', environments: ['web'] },
({ assets, compilation }) => {
for (const key of Object.keys(assets)) {
if (key.endsWith('.js')) {
compilation.deleteAsset(key);
}
}
},
);
},
};
```
=> feat: add environments as a filter of `api.processAssets`

e2e/cases/browserslist/extends-browserslist/index.test.ts
Enable the e2e test case for browserslist extends.
https://github.com/web-infra-dev/rsbuild/issues/2443
=> test(e2e): enable test case for browserslist extends

e2e/cases/inline-chunk/index.test.ts, packages/core/src/plugins/inlineChunk.ts, packages/core/src/types/config/output.ts, website/docs/en/config/output/inline-scripts.mdx, website/docs/en/config/output/inline-styles.mdx, website/docs/zh/config/output/inline-scripts.mdx, website/docs/zh/config/output/inline-styles.mdx
Support inline chunks in development mode
https://github.com/web-infra-dev/rsbuild/issues/2957
=> feat: enable inline chunks based on conditions through output options

packages/core/src/helpers.ts, packages/core/src/plugins/inlineChunk.ts
Use Node.js built-in isRegExp util.
https://nodejs.org/api/util.html#utiltypesisregexpvalue
=> chore: use Node.js built-in isRegExp util

README.md, README.zh-CN.md, pnpm-lock.yaml, scripts/dictionary.txt, website/README.md, website/docs/en/guide/start/index.mdx, website/docs/zh/guide/start/index.mdx, website/package.json, website/theme/components/Benchmark.tsx, website/theme/components/ToolStack.tsx, website/theme/index.tsx
Update Rstack repo links, `Rsfamily` -> `Rstack`.
https://github.com/rspack-contrib/rstack-design-resources
=> docs: update Rstack repo links

e2e/cases/swc-plugin/package.json, packages/core/package.json, packages/core/src/helpers.ts, packages/plugin-react/package.json, packages/plugin-styled-components/package.json, pnpm-lock.yaml
bump Rspack 1.0.0-beta.0 and SWC Wasm plugins.
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-beta.0
=> feat(deps): bump Rspack 1.0.0-beta.0

e2e/cases/inspect-config/index.test.ts, packages/compat/webpack/src/inspectConfig.ts, packages/core/src/cli/commands.ts, packages/core/src/provider/inspectConfig.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Allow absolute output path for inspectConfig:
```ts
import path from 'node:path';
await rsbuild.inspectConfig({
writeToDisk: true,
outputPath: path.join(__dirname, 'custom-dir'),
});
```
https://github.com/web-infra-dev/rsbuild/issues/3023
=> feat: allow absolute output path for inspectConfig

packages/core/package.json
Fix incorrect exports fields of `@rsbuild/core`:
https://arethetypeswrong.github.io/?p=%40rsbuild%2Fcore%401.0.1-beta.5
=> fix(core): incorrect exports fields

packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-check-syntax/package.json, packages/plugin-less/package.json, packages/plugin-lightningcss/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
* feat(deps): bump Rspack 1.0.0-beta.0 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3022
* feat: allow absolute output path for inspectConfig by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3024
* fix(core): incorrect exports fields by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3025
* fix(plugin-sass): type issue with moduleResolution node16+ by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3026
* docs: update Rstack repo links by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3018
* chore(deps): update dependency preact to ^10.23.1 by @renovate in https://github.com/web-infra-dev/rsbuild/pull/3013
**Full Changelog**: https://github.com/web-infra-dev/rsbuild/compare/v1.0.1-beta.5...v1.0.1-beta.6
=> release: 1.0.1-beta.6

packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/plugin-less/src/index.ts, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-rem/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/src/index.ts, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-stylus/src/index.ts, packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap, website/docs/en/config/tools/css-loader.mdx, website/docs/zh/config/tools/css-loader.mdx
Enable lightningcss-loader by default.
Lightning CSS is much more faster than PostCSS / autoprefixer. And it can downgrade modern CSS features like CSS nesting.
TODO:
- remove the built-in autoprefixer
- remove the @rsbuild/plugin-lightningcss
- update documentation
- https://lightningcss.dev/
- https://www.rspack.dev/guide/features/builtin-lightningcss-loader
=> feat: enable lightningcss-loader by default

packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/css.test.ts, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-rem/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
Fix targets options of lightningcss-loader, `target` -> `targets`.
https://www.rspack.dev/guide/features/builtin-lightningcss-loader#options
https://github.com/web-infra-dev/rsbuild/pull/3034
=> fix: targets options of lightningcss-loader

e2e/cases/css/lightningcss-prefixes/.browserslistrc, e2e/cases/css/lightningcss-prefixes/index.test.ts, e2e/cases/css/lightningcss-prefixes/src/index.css, e2e/cases/css/lightningcss-prefixes/src/index.js, packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-rem/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap, scripts/dictionary.txt
Fix the targets of lightningcss-loader not work.
Rspack should convert browserslist query to browser array, but it does not. I will send a PR to Rspack later.
https://lightningcss.dev/transpilation.html
=> fix: targets of lightningcss-loader not work

packages/core/src/plugins/css.ts, packages/core/src/types/config/tools.ts, website/docs/en/config/tools/lightningcss-loader.mdx, website/docs/zh/config/tools/lightningcss-loader.mdx
Add new `tools.lightningcssLoader` config to modify the options of `builtin:lightningcss-loader`.
=> feat: add new `tools.lightningcssLoader` config

e2e/cases/server/ssr/index.test.ts, e2e/package.json
This reverts commit 0f22361f8c945c428b063f79125cd1d295c63f30.
Revert https://github.com/web-infra-dev/rsbuild/pull/2997. The CI failture is un-related to `experimental-vm-modules`.
https://github.com/web-infra-dev/rsbuild/pull/3044
=> Revert "test(e2e): try to fix CI failures (#2997)"

e2e/cases/svelte/hmr/index.test.ts, e2e/cases/svelte/hmr/src/A.svelte, e2e/cases/svelte/index.test.ts
Avoid write to committed file when running e2e test, use temp files instead.
=> test(e2e): avoid write to committed file

e2e/cases/css/lightningcss-prefixes/index.test.ts, packages/core/src/plugins/minimize.ts, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/minimize.test.ts
Set the browserset option for lightningcss minimizer. This can ensure the `builtin:lightningcss-loader` and `LightningCssMinimizerRspackPlugin` use the same browserslist value and avoid potential conflicts.
=> fix: set browserset for lightningcss minimizer

packages/core/src/server/devMiddleware.ts, packages/core/src/server/helper.ts, packages/core/src/server/socketServer.ts
Add uniqueName to the WebSocket compilation name, this can avoid the infinite loop when loading multiple entry chunks in a page (such as module federation).
see https://github.com/web-infra-dev/rsbuild/issues/3031
=> fix: add uniqueName to WebSocket compilation name

packages/core/tests/pluginStore.test.ts, website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
global plugin can remove environment plugin, but environment plugin can't remove global plugin
=> docs: add remove plugin tip when use environment plugin

e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/index.test.ts, e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/myPlugin.ts, e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/rsbuild.config.ts, e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/src/index.css, e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/src/index.js, e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/static/index.html, packages/core/src/initPlugins.ts
use `thisCompilation` hook instead of `compilation` hook to ensure `processAssets` callback only called once, because compilation hook will also called when has `childCompiler`.
=> fix: processAssets callback should only called once

website/docs/en/config/dev/watch-files.mdx, website/docs/en/guide/advanced/module-federation.mdx, website/docs/zh/config/dev/watch-files.mdx, website/docs/zh/guide/advanced/module-federation.mdx
Simplify `tools.rspack` examples, the object type is easier to use and Intuitive.
=> docs: simplify `tools.rspack` examples

packages/core/package.json, packages/core/prebundle.config.mjs, pnpm-lock.yaml
`postcss` is only used by `css-loader` and it can be prebundled to reduce dependencies and module count.
=> perf: prebundle postcss

packages/core/prebundle.config.mjs
Remove `cosmiconfig` from `postcss-loader`. Rsbuild uses `postcss-load-config` and no need to use `cosmiconfig`. The ralevent code will never be executed, so we can replace it with an empty object.
Removed 7680 lines of code.
=> perf: remove cosmiconfig from postcss-loader

packages/core/package.json, packages/core/prebundle.config.mjs, pnpm-lock.yaml
Bump rspack-manifest-plugin v5.0.1, remove `webpack-sources` and `tapable` from its dependencies.
https://github.com/rspack-contrib/rspack-manifest-plugin/releases/tag/5.0.1
=> perf: bump rspack-manifest-plugin v5.0.1

packages/compat/webpack/src/build.ts, packages/core/src/provider/build.ts, packages/core/src/types/hooks.ts, website/docs/en/shared/onAfterBuild.mdx, website/docs/en/shared/onBeforeBuild.mdx, website/docs/zh/shared/onAfterBuild.mdx, website/docs/zh/shared/onBeforeBuild.mdx
add `isWatch` param to determine whether it is watch mode when build.
=> feat: add `isWatch` param to determine whether it is watch mode when build

e2e/cases/css/enable-experiments-css/index.test.ts, e2e/cases/css/enable-experiments-css/rsbuild.config.ts, e2e/cases/css/enable-experiments-css/src/index.css, e2e/cases/css/enable-experiments-css/src/index.js, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
Set `javascript/auto` rule type to allow to enable Rspack `experiments.css`.
https://rspack.dev/plugins/rspack/css-extract-rspack-plugin#note
=> fix: allow to enable Rspack `experiments.css`

e2e/cases/cli/reload-extra-config/.gitignore, e2e/cases/cli/reload-extra-config/index.test.ts, e2e/cases/cli/reload-extra-config/src/index.js, e2e/cases/cli/reload-extra-config/tsconfig.json, packages/core/src/cli/init.ts, packages/core/src/server/watchFiles.ts, packages/core/src/types/config/dev.ts
Add `type` option to `dev.watchFiles` to choose 'reload-page'(default) or 'reload-server'
```typescript
type WatchFiles = {
paths: string | string[];
options?: WatchOptions;
type?: 'reload-page' | 'reload-server';
};
```
- type: 'reload-page' is the default value, align with the current usage.
```javascript
dev: {
watchFiles: {
type: 'reload-page',
paths: ['public/foo.txt'],
},
},
};
```
- type: 'reload-server' is the new value, can be used to watch some config files and reload the server.
```javascript
import proxy from './configs/proxy.ts';
dev: {
watchFiles: {
type: 'reload-server',
paths: ['configs/proxy.ts'],
},
},
server: {
proxy,
},
};
```
https://github.com/web-infra-dev/rsbuild/pull/3057
=> feat(core): add `type` option to `dev.watchFiles` to support reload server

packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-rem/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
Remove temp code for lightningcss-loader since the bug of Rspack has been fixed.
https://github.com/web-infra-dev/rspack/pull/7331
=> chore: remove temp code for lightningcss-loader

e2e/cases/plugin-api/plugin-on-exit-hook/index.test.ts
Should kill child process, otherwise the e2e process may not exit.
https://github.com/web-infra-dev/rsbuild/pull/2997
=> test(e2e): should kill child process

packages/core/src/cli/init.ts, packages/core/src/config.ts, packages/core/src/server/watchFiles.ts
Fix `watchFiles.options` not work for reloading server.
=> fix: watchFiles options not work for reloading server

packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-check-syntax/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json, website/docs/en/guide/basic/css-usage.mdx, website/docs/zh/guide/basic/css-usage.mdx
Rsbuild now enables [lightningcss-loader](https://rspack.dev/guide/features/builtin-lightningcss-loader) by default to transform CSS files, it replaces `autoprefixer` to add vendor prefixes and provides better performance.
- `@rsbuild/plugin-lightningcss` has been deprecated and no longer needed.
- `tools.autoprefixer` config has been removed.
Considering that Lightning CSS has some uncovered edge cases, you can still enable autoprefixer via the postcss configuration file:
```js
// postcss.config.cjs
module.exports = {
plugins: {
autoprefixer: {},
}
}
```
> https://github.com/web-infra-dev/rsbuild/pull/3047, https://github.com/web-infra-dev/rsbuild/pull/3034
* feat: bump Rspack 1.0.0-beta.1 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3072
* feat: add new …
=> release: 1.0.1-beta.7

package.json, packages/compat/plugin-swc/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-check-syntax/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json
Fix pnpm v9.6.0 generates invalid peerDependencies version.
revert https://github.com/web-infra-dev/rsbuild/pull/3033
https://github.com/pnpm/pnpm/issues/8355
=> fix: pnpm generates invalid peerDependencies version

packages/core/src/createContext.ts, packages/core/src/mergeConfig.ts, packages/core/tests/html.test.ts, packages/core/tests/mergeConfig.test.ts
Avoid merging boolean config with object config, because the `reduceConfigs()` helper can not handle it.
=> fix: avoid merging boolean config with object config

e2e/cases/css/lightningcss-disabled/.browserslistrc, e2e/cases/css/lightningcss-disabled/index.test.ts, e2e/cases/css/lightningcss-disabled/src/index.css, e2e/cases/css/lightningcss-disabled/src/index.js, packages/core/src/plugins/css.ts, packages/core/src/types/config/tools.ts, website/docs/en/config/tools/lightningcss-loader.mdx, website/docs/zh/config/tools/lightningcss-loader.mdx
Allow to disable the buit-in `lightningcss-loader`.
```js
tools: {
lightningcssLoader: false,
},
};
```
=> feat: allow to disable buit-in lightningcss-loader

e2e/cases/plugin-api/plugin-hooks-watch/.gitignore, e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts, packages/compat/webpack/src/build.ts, packages/compat/webpack/src/initConfigs.ts, packages/compat/webpack/src/shared.ts, packages/core/src/helpers.ts, packages/core/src/internal.ts, packages/core/src/plugins/cleanOutput.ts, packages/core/src/plugins/rspackProfile.ts, packages/core/src/plugins/server.ts, packages/core/src/provider/build.ts, packages/core/src/provider/initConfigs.ts, packages/core/src/types/hooks.ts, packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/en/shared/onBeforeBuild.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/shared/onBeforeBuild.mdx
`onBeforeBuild` hook should calling multiple times **in watch mode**. 
This modification may cause breaking for plugins that originally use `onBeforeBuild` hook.
If you want `onBeforeBuild` to be executed **only once** even in watch mode, you can use `isFirstCompile` to determine whether it is the first build on watch mode.
```diff
const myPlugin = () => ({
setup: (api) => {
api.onBeforeBuild(({ bundlerConfigs, isFirstCompile }) => {
+    if (!isFirstCompile) {
+        return;
+     }
console.log('the bundler config is ', bundlerConfigs);
});
},
});
```
=> feat!: `onBeforeBuild` hook supports calling multiple times in watch mode

website/docs/en/plugins/list/plugin-vue.mdx, website/docs/en/plugins/list/plugin-vue2.mdx, website/docs/zh/plugins/list/plugin-vue.mdx, website/docs/zh/plugins/list/plugin-vue2.mdx
Add FAQ for Vue deprecated deep selector.
https://github.com/web-infra-dev/rsbuild/issues/3058
https://github.com/web-infra-dev/rsbuild/issues/3087
=> docs: add FAQ for Vue deprecated deep selector

e2e/cases/asset-prefix/index.test.ts, e2e/cases/asset-prefix/src/index.js, packages/core/src/plugins/open.ts, packages/core/src/plugins/output.ts, packages/core/tests/open.test.ts, packages/core/tests/output.test.ts, website/docs/en/config/dev/asset-prefix.mdx, website/docs/zh/config/dev/asset-prefix.mdx
fix: #3094 
Note that `<port>` is also available in `output.assetPrefix`. But I can't think of any situation in which it should be used.
=> feat: support using `<port>` in `dev.assetPrefix`

packages/core/src/server/getDevMiddlewares.ts, packages/core/src/server/gzipMiddleware.ts, packages/core/src/server/prodServer.ts
In the previous PR (https://github.com/web-infra-dev/rsbuild/pull/3090), I changed the default gzip level to 1 for better performance. But for the preview server, it is better to use `level: 6` because it can simulate the common gzip compression rates and reflects a more realistic file size.
https://github.com/madler/zlib/blob/ac8f12c97d1afd9bafa9c710f827d40a407d3266/zlib.h#L239
=> fix: set gzip level to 6 for preview server

packages/core/src/plugins/moduleFederation.ts
The `PatchSplitChunksPlugin` will slow down the build process because it uses function `chunks` option, and the function will slow down Rspack when there are thousands of modules.
We can only apply `PatchSplitChunksPlugin` for the provider app (which uses `exposes` option) because `PatchSplitChunksPlugin` is designed to handle remote entries.
https://github.com/web-infra-dev/rsbuild/issues/3067
=> perf(mf): only patch split chunks for provider app

packages/core/src/plugins/moduleFederation.ts, packages/core/src/plugins/splitChunks.ts, packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
Set `splitChunks.chunks` to `async` by default if using `moduleFederation.options`.
If using `chunks: 'all'`, the `PatchSplitChunksPlugin` will turn `chunks` to a function and it is quite slow when there are thousands of modules.
https://github.com/web-infra-dev/rsbuild/issues/3067
https://github.com/web-infra-dev/rsbuild/pull/3102
=> perf(mf): set splitChunks.chunks to `async` by default if using module federation

packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-check-syntax/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
* feat: allow to disable buit-in lightningcss-loader by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3082
* feat!: `onBeforeBuild` hook supports calling multiple times in watch mode by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3066
* feat: support using `<port>` in `dev.assetPrefix` by @colinaaa in https://github.com/web-infra-dev/rsbuild/pull/3098
* perf(server): adjust gzip level for faster compression by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3090
* perf(mf): only patch split chunks for provider app by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3102
* perf(mf): set splitChunks.chunks to `async` by default if using module federation by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3104
* fix: avoid …
=> release: 1.0.1-beta.9

biome.json, e2e/cases/source-build/app/tsconfig.json, e2e/cases/source-build/components/tsconfig.json, e2e/cases/source-build/utils/tsconfig.json, e2e/cases/source-build/utils2/tsconfig.json, e2e/cases/type-check/basic/tsconfig.json, e2e/cases/type-check/exclude-node-modules/tsconfig.json, e2e/cases/type-check/multiple-tsconfig/tsconfig.json, e2e/cases/type-check/multiple-tsconfig/tsconfig.server.json
Make type checker faster by not including types.
- before:
- after:
https://github.com/microsoft/TypeScript/wiki/Performance#controlling-types-inclusion
=> test(e2e): make type checker faster by not including types

packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/css.test.ts, packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
Create a new config object when getting PostCSS config object from the cache, this can ensure isolation of config objects between different builds.
https://github.com/web-infra-dev/rsbuild/pull/3035/files#diff-d13036c459b24b45d227646a9c9721a79332a21dabe50f80850b3d094dfb2a07L175-L178
=> fix: ensure isolation of config objects between different builds

packages/core/package.json, packages/core/src/rspack/preload/helpers/extractChunks.ts, packages/plugin-react/package.json, pnpm-lock.yaml
bump Rspack 1.0.0-beta.2, and fix the type issue of initial chunks.
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-beta.2
=> feat(deps): bump Rspack 1.0.0-beta.2

packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/core/src/configChain.ts, packages/core/src/plugins/html.ts, packages/core/src/plugins/nonce.ts, packages/core/src/rspack/RsbuildHtmlPlugin.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/html.test.ts.snap, packages/core/tests/htmlHelper.test.ts, packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Rename the internal HTML plugin to `RsbuildHtmlPlugin`. `HtmlBasicPlugin` is inappropriate.
=> chore: rename internal HTML plugin to RsbuildHtmlPlugin

e2e/cases/html/custom-filename/index.test.ts, e2e/cases/html/custom-filename/rsbuild.config.ts, e2e/cases/html/custom-filename/src/bar.js, e2e/cases/html/custom-filename/src/foo.js, packages/core/src/initPlugins.ts, packages/core/src/types/config/output.ts, packages/core/tests/htmlHelper.test.ts, website/docs/en/config/output/filename.mdx, website/docs/zh/config/output/filename.mdx
Allow to configure `output.filename.html`.
=> feat: allow to configure `output.filename.html`

e2e/cases/html/filename-hash/index.test.ts, website/docs/en/config/output/filename.mdx, website/docs/zh/config/output/filename.mdx
- Add guide for filename template string.
- Add an e2e case for HTML filename.
=> docs: add guide for filename template string

packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-rem/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-source-build/package.json, packages/plugin-styled-components/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
* feat(deps): bump Rspack 1.0.0-beta.2 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3113
* feat: add environment hooks about compiler by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3108
* feat: allow to configure `output.filename.html` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3137
* fix: ensure isolation of config objects between different builds by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3111
* docs: add UA polyfill guide by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3115
* docs: add configure SWC guide by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3119
* docs: add guide for custom JS minimizer by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3120
* docs: add tips …
=> release: 1.0.1-beta.10

e2e/cases/cli/inspect/index.test.ts, packages/compat/webpack/src/inspectConfig.ts, packages/core/src/cli/commands.ts, packages/core/src/provider/inspectConfig.ts, packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Rename the `env` option of `rsbuild inspect` command to `mode`. This is to align with other APIs, such as the `mode` option of `rsbuild.build()`.
```bash
npx rsbuild inspect --env production
npx rsbuild inspect --mode production
```
https://rsbuild.dev/api/javascript-api/instance#rsbuildbuild
=> fix!(cli): rename env option of inspect command to mode

packages/plugin-sass/src/types.ts
`sassOptions` type should defaults to modern API, because sass-loader >= 16.0.0 uses modern API by default.
https://github.com/webpack-contrib/sass-loader/releases/tag/v16.0.0
https://github.com/web-infra-dev/rsbuild/pull/2708
=> fix(plugin-sass): sassOptions type should defaults to modern API

packages/core/src/configChain.ts, packages/core/src/hooks.ts, packages/core/src/provider/build.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/provider/initConfigs.ts, packages/core/src/provider/inspectConfig.ts, packages/core/src/provider/rspackConfig.ts, packages/core/src/types/config/output.ts, packages/core/src/types/config/tools.ts, packages/core/src/types/plugin.ts, packages/core/src/types/rsbuild.ts, packages/core/src/types/rspack.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/en/config/output/source-map.mdx, website/docs/en/config/tools/rspack.mdx, website/docs/en/plugins/dev/hooks.mdx, website/docs/en/shared/onBeforeBuild.mdx, website/docs/en/shared/onBeforeCreateCompiler.mdx, website/docs/en/shared/onBeforeEnvironmentCompile.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/config/output/source-map.mdx, website/docs/zh/config/tools/rspack.mdx, website/docs/zh/plugins/dev/hooks.mdx, website/docs/zh/shared/onBeforeBuild.mdx, website/docs/zh/shared/onBeforeCreateCompiler.mdx, website/docs/zh/shared/onBeforeEnvironmentCompile.mdx
No need to override Rspack configuration type, Rspack now supports webpack plugin type by default, see https://github.com/web-infra-dev/rspack/pull/7455.
=> fix: no need to override Rspack configuration type

cspell.config.cjs
Let cspell ignore Portuguese README, fix the CI.
=> chore: let cspell ignore Portuguese README

website/docs/en/_meta.json, website/docs/zh/_meta.json
Add link for Rsbuild 0.x website.
- https://v0.rsbuild.dev/ is hosted on Netlify.
- The website is deployed from the Rsbuild repo [v0.x branch](https://github.com/web-infra-dev/rsbuild/tree/v0.x).
=> docs: add link for Rsbuild 0.x website

e2e/cases/mode/index.test.ts, e2e/cases/mode/rsbuild.config.ts, e2e/cases/mode/src/index.ts, e2e/cases/mode/tsconfig.json, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/core/src/plugins/define.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/define.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-vue/tests/__snapshots__/index.test.ts.snap, website/docs/en/config/mode.mdx, website/docs/zh/config/mode.mdx
Fix define `NODE_ENV` conflicts when setting `mode`, Rspack already defines `process.env.NODE_ENV` by Rspack's mode, so Rsbuild do not need to define it again.
https://rspack.dev/config/mode
=> fix: define NODE_ENV conflicts when setting mode

website/docs/en/config/_meta.json, website/docs/zh/config/_meta.json, website/theme/rsbuildPluginOverview.ts
Display top level fields in the overview page.
=> docs: display top level fields in the overview page

e2e/cases/root/index.test.ts, e2e/cases/root/test/src/index.js, packages/core/src/config.ts, packages/core/src/createContext.ts, packages/core/src/types/config/index.ts, packages/core/tests/__snapshots__/environments.test.ts.snap, website/docs/en/config/_meta.json, website/docs/en/config/root.mdx, website/docs/zh/config/_meta.json, website/docs/zh/config/root.mdx, website/theme/rsbuildPluginOverview.ts
Add new `root` config to specify the project root directory.
```ts
root: './foo',
};
```
=> feat: add new `root` config

website/docs/en/config/mode.mdx, website/docs/en/config/root.mdx, website/docs/zh/config/mode.mdx, website/docs/zh/config/root.mdx
The value of `root` does not affect the path of the `.env` file, as the `.env` file is resolved before the Rsbuild configuration file.
=> docs: add tip for using root with env files

package.json, packages/core/src/plugins/fileSize.ts, pnpm-lock.yaml
Remove unused ts comments to fix the Rspack ecosystem CI.
- https://github.com/web-infra-dev/rspack/pull/7521
- https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/10316888656/job/28560210659
=> chore: remove unused ts comments

e2e/playwright.config.ts
Print line for each test being run in CI, playwright uses `process.env.CI ? 'dot' : 'list'` by default.
https://playwright.dev/docs/test-reporters
=> test(e2e): print line for each test being run in CI

e2e/cases/cli/inspect/index.test.ts, e2e/cases/inspect-config/debug.test.ts, e2e/cases/inspect-config/index.test.ts, packages/compat/webpack/src/inspectConfig.ts, packages/core/src/constants.ts, packages/core/src/plugins/cleanOutput.ts, packages/core/src/provider/inspectConfig.ts, packages/core/tests/cleanOutput.test.ts, website/docs/en/guide/advanced/environments.mdx, website/docs/en/guide/basic/cli.mdx, website/docs/en/guide/basic/configure-rsbuild.mdx, website/docs/en/guide/debug/debug-mode.mdx, website/docs/en/guide/faq/features.mdx, website/docs/zh/guide/advanced/environments.mdx, website/docs/zh/guide/basic/cli.mdx, website/docs/zh/guide/basic/configure-rsbuild.mdx, website/docs/zh/guide/debug/debug-mode.mdx, website/docs/zh/guide/faq/features.mdx
output inspect config to `.rsbuild` directory by default, and we will output more rsbuild related files to the `.rsbuild` directory.
=> feat!: output inspect config to .rsbuild dir

packages/core/src/plugins/fileSize.ts
No need to print file size after rebuilding, take Rslib as an example:
=> fix: no need to print file size after rebuilding

e2e/cases/html/favicon/index.test.ts, packages/core/src/rspack/RsbuildHtmlPlugin.ts
Should add`type="image/svg+xml"` attribute for SVG favicon.
https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs
=> feat: add type attribute for SVG favicon

packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
* feat: add new `root` config by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3170
* feat(CLI): add new `root` option by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3173
* feat(deps): bump Rspack 1.0.0-beta.4 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3178
* feat!: output inspect config to .rsbuild dir by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3189
* feat: add type attribute for SVG favicon by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3200
* fix: no need to print file size if there is any build error by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3190
* fix: no need to print file size after rebuilding by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3197
* fix: …
=> release: 1.0.1-beta.12

packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/prebundle.config.mjs, packages/core/src/helpers/path.ts, packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
`postcss-loader` will try to require the `postcss` package, and we should make sure that postcss-loader uses the built-in postcss package by default. If not, it may resolve to postcss v7 or lower versions in a monorepo and break the build.
- https://github.com/web-infra-dev/rsbuild/pull/3062
- https://github.com/webpack-contrib/postcss-loader/blob/master/src/utils.js#L548-L551
=> fix: ensure postcss-loader uses the built-in postcss

packages/create-rsbuild/src/index.ts, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
Improve CLI prompt usability for additional tool selection. Users may be unsure on how to select additional tools, leading to confusion.
It happened to me, when I was trying to select additional tools for linting and formatting, I wasn't quite sure why hitting enter was not selecting the tools 😅
=> feat(create-rsbuild): improve tool selection instruction in prompt

packages/core/src/plugins/cleanOutput.ts
By default, if the rsbuild outputs directory (`.rsbuild/`) is a subdir of the project root path, Rsbuild will automatically clean all files under the build directory.
https://github.com/web-infra-dev/rsbuild/pull/3189
=> fix: clean rsbuild outputs by default

packages/core/src/config.ts, packages/core/src/plugins/cleanOutput.ts, packages/core/src/types/config/output.ts, packages/core/tests/__snapshots__/environments.test.ts.snap, website/docs/en/config/output/clean-dist-path.mdx, website/docs/zh/config/output/clean-dist-path.mdx
`output.cleanDistPath` defaults to `auto`, this makes the default behavior of cleanDistPath more explicit.
=> feat: `output.cleanDistPath` defaults to `auto`

e2e/cases/mode/define/index.test.ts, e2e/cases/mode/define/src/index.js, packages/core/src/createRsbuild.ts, packages/core/src/provider/build.ts, packages/core/src/server/devServer.ts, packages/core/src/server/prodServer.ts, packages/core/src/types/rsbuild.ts, website/docs/en/config/mode.mdx, website/docs/zh/config/mode.mdx
Fix missing default mode when using `rsbuild.startDevServer()` and `rsbuild.createDevServer()`.
We should set the default `process.env.NODE_ENV` before calling `initRsbuildConfig()`, otherwise the default value of `mode` will be `none` instead of `development`.
https://github.com/web-infra-dev/rsbuild/issues/3206
=> fix: missing default mode when using `rsbuild.startDevServer`

website/rspress.config.ts
- use x logo to replace twitter logo.
- enable `ssg.strict` to ensure SSG can pass.
the same as https://github.com/web-infra-dev/rspack/pull/7581
=> docs: enable strict SSG and update X logo

e2e/cases/html/app-icon/index.test.ts, e2e/cases/html/combined/html.test.ts, packages/core/src/helpers/index.ts, packages/core/src/plugins/appIcon.ts, packages/core/src/types/config/html.ts
Previously, `html.appIcon` lacked support for web app manifests, meaning it was only available on iOS.
For Android devices, we should generate a `manifest.webmanifest` file to provide information about the web application.
Note that this PR contains a breaking change:
- before:
```js
html: {
appIcon: './src/icon.png',
},
};
```
- after:
```js
html: {
appIcon: {
icons: [{ src: './src/icon.png', size: 180 }],
},
},
};
```
- generating `manifest.webmanifest`:
```js
html: {
appIcon: {
name: 'My Website',
icons: [
{ src: './src/icon-192.png', size: 192 },
{ src: './src/icon-512.png', size: 512 },
],
},
},
};
```
- https://web.dev/articles/add-manifest
- https://developer.mozilla.org/en-US/docs/Web/Manifest
- …
=> feat!: support generating web app manifest when using `html.appIcon`

e2e/cases/server/custom-server/scripts/pureServer.mjs, e2e/cases/server/custom-server/scripts/server.mjs, packages/core/src/server/devServer.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/en/guide/advanced/ssr.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/guide/advanced/ssr.mdx
This PR will cause **breaking change** for users who use Rsbuild's `createDevServer` JavaScript API directly.
The `﻿onHTTPUpgrade` method does not fully convey its actual purpose, which is to activate the webSocket connection for Rsbuild.
Users who use rsbuild createDevServer directly need to make the following modifications:
```diff
const rsbuildServer = await rsbuild.createDevServer();
const httpServer = app.listen(rsbuildServer.port);
-  httpServer.on('upgrade', rsbuildServer.onHTTPUpgrade);
+  rsbuildServer.connectWebSocket({ server: httpServer });
```
=> feat!: use `connectWebSocket` instead of `onHTTPUpdate` method

e2e/cases/html/app-icon/index.test.ts
Add cases for new implementation of `html.appIcon`.
https://github.com/web-infra-dev/rsbuild/pull/3219
=> test(e2e): add cases for `html.appIcon`

packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2-jsx/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
* feat!: support generating web app manifest when using `html.appIcon` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3219
* feat!: use `connectWebSocket` instead of `onHTTPUpdate` method by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3216
* feat(deps): bump Rspack 1.0.0-beta.5 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3221
* feat(create-rsbuild): improve tool selection instruction in prompt by @BrinsilElias in https://github.com/web-infra-dev/rsbuild/pull/3208
* feat: `output.cleanDistPath` defaults to `auto` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3213
* fix: clean rsbuild outputs by default by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3210
* fix: missing default mode when using …
=> release: 1.0.1-beta.14

e2e/cases/source/entry-empty-object/index.test.ts, e2e/cases/source/entry-empty-object/rsbuild.config.ts, e2e/cases/source/entry-empty-object/src/index.js, packages/core/src/provider/initConfigs.ts
In some scenarios using JS API, such as Rslib, entry may be processed as an empty object, and we need to keep the default value available.
=> feat: set default entry when entry is set to an empty object

packages/core/src/helpers/fs.ts, packages/core/src/plugins/appIcon.ts
Use `compilation.inputFileSystem` to read app icons, reuse the cache of Rspack.
https://github.com/web-infra-dev/rspack/pull/7597
=> perf: use compilation.inputFileSystem to read app icons

e2e/cases/html/app-icon/index.test.ts, packages/core/package.json, packages/core/src/plugins/appIcon.ts, pnpm-lock.yaml, scripts/dictionary.txt, website/docs/en/config/html/app-icon.mdx, website/docs/en/guide/basic/html-template.mdx, website/docs/zh/config/html/app-icon.mdx, website/docs/zh/guide/basic/html-template.mdx
Add mime type for web app manifest, using `mrmime` (A tiny (2.8kB) and fast utility for getting a MIME type)
> `type`: The [MIME type](https://developer.mozilla.org/en-US/docs/Glossary/MIME_type) of the image file which the operating system can use to quickly ignore images it does not support.
- https://github.com/lukeed/mrmime
- https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Define_app_icons
=> feat: add mime type for web app manifest

e2e/cases/html/app-icon/index.test.ts, packages/core/src/plugins/appIcon.ts, packages/core/src/types/config/html.ts, website/docs/en/config/html/app-icon.mdx, website/docs/zh/config/html/app-icon.mdx
Allow to specify target for app icons:
```js
html: {
appIcon: {
name: 'My Website',
icons: [
{
src: './src/assets/logo-180.png',
size: 180,
target: 'apple-touch-icon',
},
{
src: './src/assets/logo-192.png',
size: 192,
target: 'web-app-manifest',
},
{
src: './src/assets/logo-512.png',
size: 512,
target: 'web-app-manifest',
},
],
},
},
};
```
=> feat: allow to specify target for app icons

website/rspress.config.ts
Add app icon to the website.
https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs
=> docs: add app icon to website

e2e/cases/source/entry-disable-html/index.test.ts, e2e/cases/source/entry-disable-html/rsbuild.config.ts, e2e/cases/source/entry-disable-html/src/bar.js, e2e/cases/source/entry-disable-html/src/foo.js, packages/core/src/createContext.ts, packages/core/src/index.ts, packages/core/src/plugins/entry.ts, packages/core/src/plugins/html.ts, packages/core/src/types/rsbuild.ts, website/docs/en/config/source/entry.mdx, website/docs/zh/config/source/entry.mdx
Allow to disable HTML for specific entry:
```js
source: {
entry: {
foo: {
import: './src/foo.js',
},
bar: {
import: './src/bar.js',
html: false,
},
},
},
};
```
=> feat: allow to disable HTML for specific entry

packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, packages/plugin-vue2/package.json, scripts/config/package.json, scripts/test-helper/package.json
* feat!: change default charset to utf8 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3250
* feat: set default entry when entry is set to an empty object by @Timeless0911 in https://github.com/web-infra-dev/rsbuild/pull/3225
* feat: allow to custom web app manifest filename by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3228
* feat: add mime type for web app manifest by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3234
* feat: allow to specify target for app icons by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3235
* feat: allow to set URL as app icon by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3237
* feat: allow to disable HTML for specific entry by @chenjiahan in …
=> release: 1.0.1-beta.15

packages/core/package.json, packages/core/prebundle.config.mjs, packages/core/src/server/compilerDevMiddleware.ts, packages/core/src/server/devMiddleware.ts, packages/core/src/server/getDevMiddlewares.ts, packages/core/tsconfig.json, pnpm-lock.yaml, website/docs/en/guide/basic/server.mdx, website/docs/zh/guide/basic/server.mdx
Replace `webpack-dev-middleware` with `rsbuild-dev-middleware`.
`rsbuild-dev-middleware` is forked from `webpack-dev-middleware`, and it is designed for Rsbuild. We will remove all unused options / features from this package to make it smaller and more performant. Eventually rsbuild-dev-middleware will be merged into `@rsbuild/core`
This PR introduces `rsbuild-dev-middleware` v0.1.0, the bundle size has been reduced from `348 KB` to `181 KB`.
https://github.com/chenjiahan/rsbuild-dev-middleware
=> perf: replace dev middleware with a lightweight version

e2e/cases/inline-chunk/index.test.ts, packages/core/src/plugins/inlineChunk.ts
Be consistent with documentation.  Setting `inlineStyles` / `inlineScripts` as  true / regexp / function is equivalent to setting `enable` to 'auto'. This indicates that inline will only be enabled in production mode.
=> fix: not inline scripts / styles when enable not set

packages/core/src/server/devServer.ts
Remove the unused `outputFileSystem` property from the server instance, it does not exist in the `RsbuildDevServer` type.
=> chore: remove unused outputFileSystem from server instance

packages/core/src/server/devServer.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Expose the `server.printUrls` method for printing server URLs.
Required by https://github.com/web-infra-dev/rsbuild/issues/2991
=> feat: expose `server.printUrls` method

packages/core/src/server/devServer.ts, packages/core/src/server/helper.ts, packages/core/src/server/prodServer.ts
Terminate http server and await for the callback.
- https://dev.to/gajus/how-to-terminate-a-http-server-in-node-js-ofk
- https://github.com/hunterloftis/stoppable
- https://github.com/web-infra-dev/rsbuild/issues/2288
=> fix: should terminate http server correctly

packages/core/src/server/devServer.ts, packages/core/src/server/prodServer.ts
`server.close` should close http server.
```js
// unify these two APIs:
await (await (server.listen()).close());
await server.close();
```
=> fix: server.close should close http server

packages/core/src/server/prodServer.ts, packages/core/src/types/hooks.ts, website/docs/en/shared/onAfterStartProdServer.mdx, website/docs/zh/shared/onAfterStartProdServer.mdx
I have a Rsbuild plugin to print QRCode for all entries. It works well with `rsbuild dev`:
```js
api.onAfterStartDevServer(async ({ environments }) => {
const fooEnvironment = environments['foo']
const entries = Object.keys(fooEnvironment.entry)
await printQRCode(entries)
})
```
I would also like to print the similar QRCode for `rsbuild preview`. But I cannot get the entries from `onAfterStartProdServer`.
This patch simply add `environments` to `onAfterStartProdServer`, which will work the same as `onAfterStartDevServer`.
N/A
=> feat: add `environments` to `onAfterStartProdServer`

website/docs/en/guide/basic/html-template.mdx, website/docs/zh/guide/basic/html-template.mdx
The escape syntax of `lodash.template` is different from EJS, and we should add some notes for it.
https://github.com/jantimon/html-webpack-plugin/issues/751
https://github.com/jantimon/html-webpack-plugin/issues/1794
=> docs: correct the default HTML template

packages/compat/plugin-swc/src/utils.ts, packages/core/src/plugins/swc.ts, packages/core/src/types/config/source.ts, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/core/tests/swc.test.ts, website/docs/en/config/source/transform-import.mdx, website/docs/zh/config/source/transform-import.mdx
support modify previous `transformImport` value via  `transformImport`  function.
eg:
```ts
source: {
transformImport: (imports) => {
return imports.filter(import => import.libraryName !== 'antd');
},
},
};
```
=> feat: transformImport support function type

e2e/cases/module-federation/index.test.ts, packages/core/src/plugins/moduleFederation.ts
`@module-federation/sdk` now contains ESNext syntax and Rsbuild should compile it by default:
=> fix(mf): should compile `@module-federation/sdk`

e2e/cases/css/enable-experiments-css/index.test.ts, e2e/cases/css/style-loader/index.test.ts, packages/core/src/plugins/css.ts, website/docs/en/config/output/inject-styles.mdx, website/docs/en/config/tools/lightningcss-loader.mdx, website/docs/zh/config/output/inject-styles.mdx, website/docs/zh/config/tools/lightningcss-loader.mdx
Use the `lightningcss-loader` to minify CSS for injected styles. No longer need to install `cssnano`.
- https://github.com/web-infra-dev/rsbuild/issues/3247
- https://github.com/web-infra-dev/rsbuild/pull/3254
=> feat: minify CSS for injected styles

website/docs/en/guide/basic/html-template.mdx, website/docs/zh/guide/basic/html-template.mdx
Update the EJS usage guide, recommend using `rsbuild-plugin-ejs` because it provides full support for EJS syntax.
https://github.com/rspack-contrib/rsbuild-plugin-ejs
=> docs: update EJS usage

e2e/cases/rspack-config-validate/index.test.ts, e2e/cases/rspack-config-validate/rsbuild.config.ts, e2e/cases/rspack-config-validate/src/index.js, packages/core/src/plugins/basic.ts
allow to override Rspack config validate env: `process.env.RSPACK_CONFIG_VALIDATE`.
https://rspack.dev/guide/migration/webpack#updating-configuration
=> feat: allow to override Rspack config validate env

packages/core/src/plugins/splitChunks.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/moduleFederation.test.ts.snap, packages/core/tests/__snapshots__/splitChunks.test.ts.snap, packages/plugin-react/tests/__snapshots__/features.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Avoid passing unsupported Rspack config, fix:
=> fix: avoid passing unsupported Rspack config

e2e/cases/rspack-config-validate/index.test.ts, e2e/cases/rspack-config-validate/rsbuild.config.ts, packages/core/src/plugins/basic.ts, scripts/dictionary.txt
Enable Rspack config schema validation by default, this can help users find invalid Rspack config in advance and avoid unexpected errors during the build process.
https://github.com/web-infra-dev/rspack/pull/7705
=> feat!: enable Rspack config schema validation by default

package.json, packages/create-rsbuild/modern.config.ts, packages/create-rsbuild/package.json, packages/create-rsbuild/rslib.config.ts, pnpm-lock.yaml, website/package.json
Use Rslib to bundle package, replace the legacy Modern.js Module.
=> refacor(create-rsbuild): use Rslib to bundle package

website/docs/en/guide/start/index.mdx, website/docs/zh/guide/start/index.mdx, website/theme/components/Benchmark.module.scss, website/theme/components/Benchmark.tsx
Temp fix for Benchmark graph width.
=> docs: fix Benchmark graph width

website/docs/en/guide/migration/vite.mdx, website/docs/zh/guide/migration/vite.mdx
Add vite environment variables migrate guide.
https://rsbuild.dev/guide/migration/vite#vite
=> docs: add vite environment variables migrate guide

e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts, packages/compat/webpack/src/build.ts, packages/core/src/index.ts, packages/core/src/provider/build.ts, packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Add stats to the return value of `rsbuild.build`, it can be used to get assets info after building.
=> feat: add stats to the return value of `rsbuild.build`

.github/workflows/test-ubuntu.yml, .github/workflows/test-windows.yml
I noticed that some e2e workflows were stuck for hours : 
https://github.com/web-infra-dev/rsbuild/actions/runs/10630679833?pr=3325
This PR adds a timeout for unit and e2e tests.
Feel free to adjust the timeout if it's too high or too low.
gha doc: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
=> chore(ci): add timeout for e2e and unit tests

e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts, packages/compat/webpack/src/build.ts, packages/core/src/provider/build.ts, packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
To make it easier to use, have `rsbuild.build` always return the `close` method.
=> fix: `rsbuild.build` always return close method

packages/core/src/loader/transformLoader.ts, packages/core/src/types/plugin.ts, packages/core/src/types/rspack.ts, website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Reuse source map type from Rspack.
=> chore: reuse source map type from Rspack

packages/core/src/server/helper.ts
Escape characters in compilationId.
- before: `ws://localhost:3000/rsbuild-hmr?compilationId=web_%40examples%2Freact`
- after: `ws://localhost:3000/rsbuild-hmr?compilationId=web__examples_react`
=> fix: escape characters in compilationId

e2e/cases/node-addons/index.test.ts, e2e/package.json, packages/core/src/plugins/rsdoctor.ts, packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts, pnpm-lock.yaml, website/docs/en/guide/basic/unocss.mdx
This reverts commit 5ae0c5939004942e43c293baf61c0224c8ac5e47.
Our e2e cases become unstable after bumping playwright.
=> Revert "chore(deps): update playwright monorepo to v1.46.1 (#2725)"

packages/compat/plugin-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-type-check/package.json, packages/plugin-vue-jsx/package.json, packages/plugin-vue/package.json, scripts/config/package.json, scripts/test-helper/package.json
* feat: add stats to the return value of `rsbuild.build` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3325
* feat: add `dev.client.reconnect` option by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3333
* fix: align stats types with Rspack by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3324
* fix: `rsbuild.build` always return close method by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3327
* fix: escape characters in compilationId by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3334
* fix: remove lib-lodash from experience chunks by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3337
* fix: increase WebSocket reconnect interval by @chenjiahan in …
=> release: 1.0.1-rc.1

packages/create-rsbuild/bin.js, packages/create-rsbuild/package.json, packages/create-rsbuild/src/index.ts
Fix Rslib breaks bin shebang line.
https://github.com/web-infra-dev/rslib/issues/166
=> fix(create-rsbuild): broken shebang line in bin file

website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
`addPlugins` is a sync method and does not support add async plugins.
=> docs: correct addPlugins type

packages/core/src/createRsbuild.ts, packages/core/src/types/plugin.ts, packages/core/tests/builder.test.ts, scripts/test-helper/src/rsbuild.ts, website/docs/en/config/plugins.mdx, website/docs/zh/config/plugins.mdx
Support adding nested plugins in Rsbuild. 
```ts title="rsbuild.config.ts"
function myPlugin() {
return [
fooPlugin(),
barPlugin()
];
}
plugins: [myPlugin()]
}
```
fix: https://github.com/web-infra-dev/rsbuild/issues/3253
=> feat: support nested plugins

website/i18n.json
Fixed a typo on the homepage of rsbuild.
https://github.com/web-infra-dev/rsbuild/issues/3363
https://rsbuild.dev
=> docs(website): typo for easy to configure text on homepage

e2e/cases/rsdoctor/index.test.ts, e2e/cases/rsdoctor/mock/index.cjs, packages/core/src/plugins/rsdoctor.ts
If Rsdoctor plugin has been registered, Rsbuild does not need to resolve the Rsdoctor plugin package.
https://github.com/web-infra-dev/rsbuild/issues/3358
=> fix: skip resolution if Rsdoctor plugin is registered

packages/core/package.json, pnpm-lock.yaml
Bump Rspack 1.0.2 and unpin the version.
We use `~1.0.2` instead of `^1.0.2`, as Rspack may introduce SWC breaking changes in minor releases.
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.2
=> feat(deps): bump Rspack 1.0.2

e2e/cases/source-map/index.test.ts, scripts/dictionary.txt
Add test case to validate all production source map types.
=> test(e2e): validate all production source map types

website/docs/en/guide/debug/rsdoctor.mdx, website/docs/zh/guide/debug/rsdoctor.mdx
fix 404 error of rsdoctor link
=> docs: fix rsdoctor link

e2e/cases/html-loader/index.test.ts, e2e/cases/html-loader/package.json, e2e/cases/html-loader/rsbuild.config.ts, e2e/cases/html-loader/src/index.js, e2e/cases/html-loader/src/template.html, packages/core/package.json, pnpm-lock.yaml
Bump `html-rspack-plugin` 6.0.1 to support the use of `html-loader`.
- resolve https://github.com/web-infra-dev/rsbuild/issues/3353
- https://github.com/rspack-contrib/html-rspack-plugin/pull/20
- https://www.npmjs.com/package/html-loader
=> fix: failed to use html-loader

.github/workflows/test-ubuntu.yml, .github/workflows/test-windows.yml, e2e/cases/module-federation-v2/index.test.ts
Skip unstable MF case in Windows
https://github.com/web-infra-dev/rsbuild/actions/runs/10716069606/job/29712777478
=> test(e2e): skip unstable MF case in Windows

examples/svelte5/package.json, examples/svelte5/rsbuild.config.ts, examples/svelte5/src/App.svelte, examples/svelte5/src/index.css, examples/svelte5/src/index.js, packages/plugin-svelte/src/index.ts, packages/plugin-svelte/tests/index.test.ts, pnpm-lock.yaml
Basic support for Svelte 5.
TODO:
- Hot Module Reloading is currently not supported for Svelte 5+, see https://github.com/sveltejs/svelte-loader/commit/d42a6053207ffbe3f8889775d50fd4796378013f
- When using both Svelte 4 and 5 in a monorepo, the `svelte-loader` may get wrong version, see https://github.com/sveltejs/svelte-loader/blob/master/index.js#L62-L64. This breaks our Svelte 5 example and Svelte 5 e2e cases.
- I haven’t verified the new features of Svelte 5 in this PR.
https://github.com/web-infra-dev/rsbuild/issues/3399
=> feat: basic support for Svelte 5

.changeset/config.json
Starting from Rsbuild 1.0, we no longer require all Rsbuild packages to use the same version.
=> chore(workflow): no longer fix package version

.changeset/config.json, packages/compat/plugin-swc/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-vue/package.json
Starting with Rsbuild 1.0, we no longer require all Rsbuild packages to use the same version, so plugins should change the version range of their peer dependencies.
https://github.com/web-infra-dev/rsbuild/pull/3420
=> chore: update peer dependencies range

packages/create-rsbuild/template-lit-js/package.json, packages/create-rsbuild/template-lit-ts/package.json, packages/create-rsbuild/template-preact-js/package.json, packages/create-rsbuild/template-preact-ts/package.json, packages/create-rsbuild/template-react-js/package.json, packages/create-rsbuild/template-react-ts/package.json, packages/create-rsbuild/template-solid-js/package.json, packages/create-rsbuild/template-solid-ts/package.json, packages/create-rsbuild/template-svelte-js/package.json, packages/create-rsbuild/template-svelte-ts/package.json, packages/create-rsbuild/template-vanilla-js/package.json, packages/create-rsbuild/template-vanilla-ts/package.json, packages/create-rsbuild/template-vue2-js/package.json, packages/create-rsbuild/template-vue2-ts/package.json, packages/create-rsbuild/template-vue3-js/package.json, packages/create-rsbuild/template-vue3-ts/package.json
Starting with Rsbuild 1.0, we no longer require all Rsbuild packages to use the same version, and `create-rsbuild` should unpin the `@rsbuild/*` dependencies version.
https://github.com/web-infra-dev/rsbuild/pull/3420
=> chore(create-rsbuild): prepare for 1.0 release

packages/create-rsbuild/package.json, pnpm-lock.yaml
Fix eslint-plugin-react-hooks version conflict.
- resolve https://github.com/web-infra-dev/rsbuild/issues/3427
- https://github.com/rspack-contrib/create-rstack/pull/3
=> fix(create-rsbuild): eslint-plugin-react-hooks version conflict

website/docs/en/guide/basic/css-usage.mdx, website/docs/zh/guide/basic/css-usage.mdx
Add recommended PostCSS plugins when not using Lightning CSS.
=> docs: add recommended PostCSS plugins when not using Lightning CSS

packages/compat/plugin-webpack-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/plugin-stylus/package.json, pnpm-lock.yaml, scripts/test-helper/package.json
* feat(deps): bump Rspack v1.0.4 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3443
* feat(plugin-stylus): support `define` option by @shulaoda in https://github.com/web-infra-dev/rsbuild/pull/3434
* fix(plugin-webpack-swc): @swc/helpers version requires at least 0.5.13 by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3436
* fix(create-rsbuild): eslint-plugin-react-hooks version conflict by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3441
* docs: fix typo in 1.0 announcement by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3432
* docs: add example for merging Rspack config by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3437
* docs(plugin-stylus): update `StylusOptions` by @shulaoda in …
=> release: @rsbuild/core v1.0.2

website/docs/zh/guide/start/index.mdx
This pull request fixes some incorrect punctuation usage in the Chinese guide documentation. The commas have been changed to enumeration commas.
https://rsbuild.dev/zh/guide/start/index
=> docs(guide): fix improper punctuation in Chinese guide

packages/core/package.json, packages/core/src/plugins/resolve.ts, pnpm-lock.yaml
Set r`esolve.tsConfig` by rspack-chain instead of `api.modifyRspackConfig`.
https://github.com/rspack-contrib/rspack-chain/releases/tag/v1.0.1
=> fix: set resolve.tsConfig by rspack-chain

website/docs/en/plugins/list/plugin-svgr.mdx, website/docs/zh/plugins/list/plugin-svgr.mdx
Correct named export guide for plugin-svgr.
resolve https://github.com/web-infra-dev/rsbuild/issues/3468
=> docs(plugin-svgr): correct named export guide

packages/core/src/provider/build.ts
close callback is "any" before,  and type is narrow now
https://github.com/web-infra-dev/rspack/pull/7824
=> fix(type): eco-ci fail of watching close callback type

e2e/cases/server/print-urls/index.test.ts, packages/core/src/server/helper.ts
should format printed url when htmlPath startsWith `./`
=> fix: should format printed url when htmlPath startsWith `./`

biome.json, e2e/cases/css/css-modules-dom/src/App.css, package.json, pnpm-lock.yaml
Enable Biome support for CSS Modules.
https://biomejs.dev/reference/configuration/#cssparsercssmodules
=> chore(lint): enable Biome support for CSS Modules

e2e/cases/source-map/index.test.ts, e2e/cases/source-map/rsbuild.config.ts
Validate source map for dev build.
=> test(e2e): validate dev source map

packages/plugin-less/modern.config.ts, packages/plugin-less/package.json, packages/plugin-less/rslib.config.ts, pnpm-lock.yaml
Use Rslib to bundle `@rsbuild/plugin-less`.
TODO:
- `getLessLoaderOptions` should not be marked as deprecated after bundling.
- The target should not become `es5` when using `syntax`: https://github.com/web-infra-dev/rslib/blob/ed9fe5b0760822e703d9703d5ec31dc86ead2e5f/packages/core/src/config.ts#L569
=> chore(plugin-less): use Rslib to bundle

website/docs/en/guide/migration/rsbuild-0-x.mdx, website/docs/zh/guide/migration/rsbuild-0-x.mdx
Fix `htmlPaths` typo, in rsbuild 0.x it is `api.getHtmlPaths`, not `api.getHtmlPath`.
=> docs: htmlPaths typo

packages/compat/plugin-webpack-swc/src/plugin.ts, packages/compat/plugin-webpack-swc/tests/__snapshots__/plugin.test.ts.snap, packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap, website/docs/en/config/tools/swc.mdx, website/docs/zh/config/tools/swc.mdx
Since https://github.com/swc-project/swc/issues/6403 is fixed, we do not need to enable `preserveAllComments` by default. This will cause comments in type cannot be deleted.
#3502 
https://github.com/web-infra-dev/rslib/issues/210
=> feat: disable preserveAllComments by default

website/docs/en/config/source/exclude.mdx, website/docs/zh/config/source/exclude.mdx
update `source.exclude` usage. `source.exclude` is only used to specify JavaScript/TypeScript files that do not need to be compiled. This does not mean that these files will not be bundled into the output.
=> docs: update `source.exclude` usage

website/docs/en/guide/migration/vite.mdx, website/docs/zh/guide/migration/vite.mdx
fix `webpackContext` link
- https://github.com/web-infra-dev/rsbuild/issues/3520
- https://rspack.dev/api/runtime-api/module-variables#importmetawebpackcontext
=> docs: fix `webpackContext` link

packages/core/types.d.ts
Fix missing `*.toml` module type in `core/types.d.ts`.
=> fix(types): missing toml module type

packages/create-rsbuild/template-lit-ts/tsconfig.json
From https://lit.dev/docs/components/decorators/#earlier-decorator-proposals:
> You should also ensure that the `useDefineForClassFields` setting is false. 
https://github.com/web-infra-dev/rsbuild/issues/3521
=> fix(create-rsbuild): useDefineForClassFields in lit template

packages/core/prebundle.config.mjs
Avoid requiring the empty `semver` module, use inlined code instead.
=> perf: avoid requiring empty module

packages/compat/plugin-webpack-swc/src/minimizer.ts, packages/compat/plugin-webpack-swc/tests/__snapshots__/plugin.test.ts.snap, packages/compat/plugin-webpack-swc/tests/plugin.test.ts
fix(plugin-webpack-swc): the rsbuildConfig's sourcemap should transmit to the swcMinimizerPlugin
=> fix(plugin-webpack-swc): swcMinimizerPlugin sourceMap config

packages/core/src/configChain.ts
Remove unused CHAIN_ID, some Rsbuild plugins no longer depend on the CHAIN_ID.
- https://github.com/rspack-contrib/rsbuild-plugin-node-polyfill/pull/5
- https://github.com/rspack-contrib/rsbuild-plugin-eslint/pull/1
=> chore: remove unused CHAIN_ID

website/docs/en/config/tools/html-plugin.mdx, website/docs/zh/config/tools/html-plugin.mdx
update `tools.htmlPlugin` options tip.  it is recommended to use the Rsbuild HTML configurations instead of the corresponding `tools.htmlPlugin` configurations.
close: https://github.com/web-infra-dev/rsbuild/issues/3546
=> docs: update tools.htmlPlugin options tip

packages/compat/webpack/package.json, pnpm-lock.yaml
Move `@rsbuild/core` to peer dependency.
resolve https://github.com/web-infra-dev/rsbuild/issues/3548
=> fix(webpack): move @rsbuild/core to peer dependency

website/docs/en/guide/basic/configure-rspack.mdx, website/docs/en/plugins/dev/hooks.mdx, website/docs/zh/guide/basic/configure-rspack.mdx, website/docs/zh/plugins/dev/hooks.mdx
Rsbuild supports modifying the Rspack configuration object through `tools.rspack`, `tools.bundlerChain`, `modifyBundlerChain`, etc. We should list the order of execution between them.
=> docs: add rspack config modification order

packages/plugin-react/src/react.ts, website/docs/en/plugins/list/plugin-react.mdx, website/docs/zh/plugins/list/plugin-react.mdx
Exclude node_modules from react-refresh plugin. Usually, modules in node_modules do not need to use react-refresh, which also avoids some potential conflicts.
resolve https://github.com/web-infra-dev/rsbuild/issues/3562
=> fix(plugin-react): exclude node_modules from react-refresh plugin

website/docs/en/config/tools/lightningcss-loader.mdx, website/docs/zh/config/tools/lightningcss-loader.mdx
Lightningcss is used in Rsbuild not only to transform CSS code, but also to minify CSS.  `tools.lightningcssLoader` false only disables the `lightningcss-loader`.
=> docs: add tools.lightningcssLoader false tip

e2e/cases/browserslist/browserslist-config-mock/index.json, packages/core/package.json, packages/core/src/plugins/target.ts, packages/core/tests/target.test.ts, packages/core/tsconfig.json, pnpm-lock.yaml
The PR removes `browserslist-to-es-version` dependency and uses Rspack's `browserslist:*` target value instead. This will improve performance in two ways:
- `@rsbuild/core` depends on fewer packages.
- Rspack can use the Rust version of browserslist to parse browserslist query in the future, which is faster than the JS version.
TODO: Rspack should support `browserslist:` for `webworker` target.
=> perf: remove browserslist-to-es-version dependency

packages/core/package.json, packages/core/prebundle.config.mjs, packages/core/src/createContext.ts, packages/core/tsconfig.json, pnpm-lock.yaml
Using [browserslist-load-config](https://github.com/rspack-contrib/browserslist-load-config) to load browserslist config:
- Removed 1600 LOC.
- Removed `caniuse-lite` dependency.
- Faster startup time.
https://github.com/rspack-contrib/browserslist-load-config
=> perf: using browserslist-load-config to load browserslist

packages/core/package.json, packages/plugin-react/package.json, pnpm-lock.yaml
In Rspack v1.0.8, the Rust crate `swc_core` has been upgraded to 0.106.0 and swc minifier source map error has been fixed.
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.8
- resolve https://github.com/web-infra-dev/rsbuild/issues/3447
- resolve https://github.com/web-infra-dev/rsbuild/issues/3433
=> feat(deps): bump rspack 1.0.8

packages/core/src/plugins/moduleFederation.ts
The `moduleFederation` option only supports Rspack, we can skip the plugin when using webpack.
Fix:
=> fix: moduleFederation option only supports Rspack

package.json, pnpm-lock.yaml
Remove esbuild version overrides as it is unnecessary and unstable.
=> chore: remove esbuild version overrides

packages/core/src/server/devServer.ts, packages/core/src/server/helper.ts, packages/core/src/server/prodServer.ts, packages/core/tests/server.test.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/en/api/start/index.mdx, website/docs/en/config/server/https.mdx, website/docs/en/config/server/print-urls.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/api/start/index.mdx, website/docs/zh/config/server/https.mdx, website/docs/zh/config/server/print-urls.mdx
Improve logs order when port is in use:
- before:
- after:
=> feat: improve logs order when port is in use

packages/core/src/provider/createCompiler.ts
`statsJson.children` get different children stats when call `stats.toJson({ children: true })` . In single compiler, statsJson.children will return childCompiler stats, and in multiCompiler, it will return compiler 1 / 2 / ... stats.
Rsbuild only need print children compiler time when multi compiler.
fix: https://github.com/web-infra-dev/rsbuild/issues/3610
=> fix: only print children compiler time when multi compiler

website/docs/en/guide/migration/vite.mdx, website/docs/zh/guide/migration/vite.mdx
Add guide for migrating env vars from Vite.
https://github.com/web-infra-dev/rsbuild/discussions/3623
=> docs: add guide for migrating env vars

packages/core/src/cli/prepare.ts
Enable Node.js 22 new compile cache in Rsbuild CLI.
- before:
- after:
- https://nodejs.org/id/blog/release/v22.8.0
- https://github.com/nodejs/node/pull/54501
=> perf(CLI): enable Node.js compile cache

packages/plugin-sass/src/index.ts, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/tests/index.test.ts
Mute the noisy Sass legacy API deprecation warnings when using the `legacy` API.
https://sass-lang.com/documentation/breaking-changes/legacy-js-api/
=> fix(plugin-sass): mute the legacy API deprecation warnings

website/docs/en/plugins/list/plugin-sass.mdx, website/docs/zh/plugins/list/plugin-sass.mdx
Add Sass legacy API deprecation tip.
https://sass-lang.com/documentation/breaking-changes/legacy-js-api/
=> docs(plugin-sass): add legacy API deprecation tip

e2e/cases/asset-prefix/index.test.ts, e2e/cases/asset-prefix/src/index.js, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/core/src/plugins/define.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/define.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/plugin-vue/tests/__snapshots__/index.test.ts.snap, website/docs/en/guide/advanced/env-vars.mdx, website/docs/zh/guide/advanced/env-vars.mdx
Rsbuild should define `import.meta.env.ASSET_PREFIX` by default to be consistent with `import.meta.env.BASE_URL`.
=> feat: define `import.meta.env.ASSET_PREFIX`

e2e/cases/plugin-api/plugin-hooks/index.test.ts, packages/core/src/cli/commands.ts, packages/core/src/createRsbuild.ts, packages/core/src/types/rsbuild.ts
Check output folder when using the `rsbuild.preview()` JS API.
=> feat: check output folder when using preview JS API

packages/core/src/cli/commands.ts, packages/core/src/createRsbuild.ts
No need to init the Rspack config before `rsbuild preview`.
=> perf: no need to init Rspack config before preview

packages/core/src/createRsbuild.ts, packages/core/src/index.ts, packages/core/src/server/prodServer.ts, packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Export the `PreviewOptions` type and correct `rsbuild.preview` documentation.
=> feat: export `PreviewOptions` type and correct doc

packages/core/src/index.ts, packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/core.mdx, website/docs/en/api/javascript-api/instance.mdx, website/docs/en/api/start/index.mdx, website/docs/zh/api/javascript-api/core.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/api/start/index.mdx
Correct type and documentation for `rsbuild.createCompiler`, remove the unused `CreateCompilerOptions` type.
=> fix: correct `rsbuild.createCompiler` type

examples/react/rsbuild.config.ts, packages/core/src/cli/init.ts
Enable CLI shortcuts by default when using Rsbuild CLI.
When using Rsbuild's JS API, the CLI shortcuts can be manually enabled via `dev.cliShortcuts`.
https://github.com/web-infra-dev/rsbuild/issues/2991
=> feat: enable CLI shortcuts by default when using Rsbuild CLI

website/docs/en/config/dev/watch-files.mdx, website/docs/zh/config/dev/watch-files.mdx
`reload-server` functionality is provided by Rsbuild CLI. This configuration may not be supported when using a custom server or an upper-layer framework based on the Rsbuild.
https://github.com/web-infra-dev/modern.js/pull/6336
=> docs: add reload-server tip

e2e/cases/rspack-config-validate/index.test.ts, packages/core/src/provider/rspackConfig.ts
Validate Rspack plugins and recognize Rsbuild plugins:
https://github.com/web-infra-dev/rsbuild/issues/3621
=> feat: validate Rspack plugins configuration

e2e/cases/print-file-size/basic/index.test.ts, e2e/cases/print-file-size/with-error/index.test.ts, packages/core/src/plugins/fileSize.ts, website/docs/en/config/performance/print-file-size.mdx, website/docs/zh/config/performance/print-file-size.mdx
Beautify file size logs for multiple environments. The log content has been simplified to avoid being too complicated
- before:
- after:
=> feat: beautify file size logs for multiple environments

e2e/cases/javascript-api/custom-logger/index.test.ts, e2e/cases/progress/index.test.ts, packages/compat/webpack/src/progress/ProgressPlugin.ts, packages/compat/webpack/src/progress/helpers/nonTty.ts, packages/core/src/provider/createCompiler.ts
Update build logs to use `build` instead of `compile`, as this more accurately reflects that Rsbuild is a build tool rather than a compiler.
=> feat: update building logs

packages/core/src/plugins/fileSize.ts
Merge file size logs to reduce `console.log` calls.
=> perf: merge file size logs

packages/plugin-solid/modern.config.ts, packages/plugin-solid/package.json, packages/plugin-solid/rslib.config.ts, packages/plugin-solid/src/index.ts, packages/plugin-solid/tsconfig.json, scripts/config/tsconfig-node16.json
- Use Rslib to bundle `@rsbuild/plugin-solid`.
- Add a tsconfig file for Node 16 resolution.
=> feat(plugin-solid): use Rslib to bundle

packages/create-rsbuild/tsconfig.json, packages/plugin-less/tsconfig.json, packages/plugin-preact/tsconfig.json, packages/plugin-stylus/tsconfig.json, scripts/test-helper/tsconfig.json
Prefer using the node16 tsconfig for packages built with Rslib. This will ensure that the generated DTS is correct for node16 TS projects.
=> chore: prefer using the node16 tsconfig

packages/plugin-babel/modern.config.ts, packages/plugin-babel/package.json, packages/plugin-babel/rslib.config.ts, packages/plugin-babel/src/helper.ts, packages/plugin-babel/src/index.ts, packages/plugin-babel/src/plugin.ts, packages/plugin-babel/tsconfig.json
Use Rslib to bundle `@rsbuild/plugin-babel`.
https://github.com/web-infra-dev/rslib/issues/283
=> feat(plugin-babel): use Rslib to bundle

packages/core/prebundle.config.mjs
Fix prebundle breaks RspackChain type when setting `"moduleResolution": "Node16"` in tsconfig.json.
=> fix: prebundle breaks RspackChain type

packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/config.ts, packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/core/tests/resolve.test.ts, website/docs/en/config/source/alias.mdx, website/docs/zh/config/source/alias.mdx
Make it easier to remove the built-in alias:
```js
source: {
alias: (alias) => {
delete alias['@swc/helpers'];
},
},
};
```
https://github.com/web-infra-dev/rsbuild/discussions/3711
=> feat: make it easier to remove the built-in alias

packages/create-rsbuild/package.json, pnpm-lock.yaml
Fix `require is not defined` error:
https://github.com/rspack-contrib/create-rstack/releases/tag/v1.0.6
=> fix(create-rsbuild): require is not defined

packages/plugin-assets-retry/modern.config.ts, packages/plugin-assets-retry/package.json, packages/plugin-assets-retry/rslib.config.ts, packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts, packages/plugin-assets-retry/src/index.ts, packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts, packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts, packages/plugin-assets-retry/tsconfig.json, pnpm-lock.yaml
Use Rslib to bundle `@rsbuild/plugin-assets-retry`.
=> feat(assets-retry): use Rslib to bundle

e2e/cases/javascript-api/load-env/index.test.ts, packages/core/src/loadEnv.ts, website/docs/en/api/javascript-api/core.mdx, website/docs/zh/api/javascript-api/core.mdx
Add a new `rawPublicVars` return value for the `loadEnv` JS API:
- Can be used to define the `process.env` object, see https://github.com/web-infra-dev/rsbuild/issues/3718
- Align the return value of Vite's `loadEnv` method, see https://vite.dev/guide/api-javascript.html#loadenv
=> feat: add rawPublicVars for `loadEnv`

e2e/cases/server/print-urls/index.test.ts, e2e/scripts/helper.ts, packages/core/src/server/helper.ts, website/docs/en/config/server/print-urls.mdx, website/docs/zh/config/server/print-urls.mdx
Allow to print URLs via the `printUrls` function when HTML is disabled.
resolve https://github.com/web-infra-dev/rsbuild/issues/3731
=> fix: allow to print URLs when HTML is disabled

website/docs/en/guide/advanced/env-vars.mdx, website/docs/zh/guide/advanced/env-vars.mdx
`process.env.NODE_ENV` injection capability is supported by Rspack, not injected via rsbuild `source.define`.
=> docs: add `process.env.NODE_ENV` inject tip

packages/compat/plugin-webpack-swc/package.json, packages/core/package.json, packages/plugin-assets-retry/package.json, packages/plugin-react/package.json
* feat(webpack-swc): use Rslib to bundle by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3726
* feat(assets-retry): use Rslib to bundle by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3727
* feat: add rawPublicVars for `loadEnv` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3732
* feat(plugin-react): allow to disable fast refresh by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3738
* feat(deps): bump rspack 1.0.13 by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3743
* fix: allow to print URLs when HTML is disabled by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3737
* docs: add note for destructuring of `process.env` to CRA guide by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3734 …
=> release: 1.0.15

.github/workflows/ecosystem-ci.yml, .github/workflows/release.yml
- fix eco-ci ref: should use eco-ci  main brach instead of rsbuild target branch.
- fix release checkout branch: should use selected branch
=> chore(CI): fix eco-ci ref & release checkout branch

packages/core/package.json, packages/core/src/rspack/RsbuildHtmlPlugin.ts, packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts, pnpm-lock.yaml
Use `getCompilationHooks` of HTML plugin as `getHooks` has been deprecated.
https://github.com/web-infra-dev/rspack/pull/8157#discussion_r1804551397
https://github.com/rspack-contrib/html-rspack-plugin/releases/tag/v6.0.2
=> fix: use `getCompilationHooks` of HTML plugin

packages/core/src/rspack/RsbuildHtmlPlugin.ts, packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
This PR revert some changes of https://github.com/web-infra-dev/rsbuild/pull/3750, because it is a potentially breaking change for `html-webpack-plugin <= 5.6.0` projects, such as Modern.js (https://github.com/web-infra-dev/modern.js/pull/6402).
We can use the `getCompilationHooks` API in Rsbuild minor releases.
=> fix: revert to the `getHooks` of HTML plugin

packages/core/src/provider/rspackConfig.ts, packages/core/src/types/config.ts, packages/core/src/types/plugin.ts, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/default.test.ts, website/docs/en/config/tools/rspack.mdx, website/docs/zh/config/tools/rspack.mdx
The `addRules(...)` method will prepend rules to Rspack rule list. To append rules,  user can use `appendRules`.
https://github.com/web-infra-dev/rsbuild/discussions/3754
=> feat: add appendRules util to `tools.rspack` config

packages/core/src/plugins/moduleFederation.ts, website/docs/en/config/module-federation/options.mdx, website/docs/zh/config/module-federation/options.mdx
The default asset prefix has been changed when using `moduleFederation.options`. These changes ensure that the assets of remote modules can be requested by consumer apps with the correct URL, and that the SPA URL fallback works as expected.
- Only change the default asset prefix for MF provider apps.
- Only change the default asset prefix in development mode (via `dev.assetPrefix`).
- The default asset prefix has been changed from `auto` to `true` (equivalent to `localhost:<port>`)
- Always prefer to use the `dev.assetPrefix` value set by user.
@nyqykk please take a look, I suppose these changes should be ported to [@module-federation/rsbuild-plugin](https://github.com/module-federation/core/blob/main/packages/rsbuild-plugin/package.json)
resolve: …
=> fix: configure the default assetPrefix for MF apps correctly

e2e/cases/filename-function/rsbuild.config.ts, packages/core/src/helpers/index.ts, packages/core/src/plugins/output.ts, packages/core/src/types/config.ts, website/docs/en/config/output/filename.mdx, website/docs/zh/config/output/filename.mdx
=> feat: output.filename.css allow function

e2e/cases/filename-function/index.test.ts, website/docs/en/config/output/filename.mdx, website/docs/zh/config/output/filename.mdx
Improve `output.filename.js` and `output.filename.css` function type, align with the Rspack configuration types.
=> docs: improve `output.filename` function type

website/docs/en/guide/start/features.mdx, website/docs/zh/guide/start/features.mdx
update the [documentation](https://rsbuild.dev/guide/start/features#development-and-preview) from `dev.proxy` to `server.proxy`
https://rsbuild.dev/config/dev/proxy
https://rsbuild.dev/config/server/proxy
https://rsbuild.dev/zh/config/dev/proxy
https://rsbuild.dev/zh/config/server/proxy
=> docs: fix proxy links in features.mdx

examples/svelte5/package.json, pnpm-lock.yaml
Bump Svelte from 5.0 pre-release to v5 stable.
close https://github.com/web-infra-dev/rsbuild/pull/3769
=> chore(deps): bump svelte to v5

e2e/cases/server/base-url/index.test.ts, packages/core/src/helpers/index.ts, packages/core/src/plugins/output.ts
Fix `dev.assetPrefix: true` not work with `server.base` config.
```js
{
server: {
base: '/base',
},
dev: {
assetPrefix: true,
},
}
```
=> fix: `dev.assetPrefix: true` not work with `server.base`

e2e/cases/module-federation/index.test.ts, packages/core/src/plugins/moduleFederation.ts
Fix failed to load MF remote modules when using `server.base`.
The default `dev.assetPrefix` is set to the value of `server.base`, and Rsbuild should replace it with `dev.assetPrefix: true` to ensure that the remote module's assets can be requested by consumer apps with the correct URL.
resolve https://github.com/web-infra-dev/rsbuild/issues/3780
=> fix: failed to load MF remote modules when using `server.base`

website/docs/en/guide/migration/vite.mdx
=> docs: update vite.mdx to fix npm command reference

packages/core/src/types/config.ts, website/docs/en/config/html/template.mdx, website/docs/zh/config/html/template.mdx
Improve JSDoc for `output` and `html` configurations, add default values.
=> feat: improve JSDoc for `output` and `html` configurations

website/docs/en/guide/basic/web-workers.mdx, website/docs/zh/guide/basic/web-workers.mdx
=> docs: add guide for worker-loader

website/docs/en/config/source/assets-include.mdx, website/docs/en/guide/basic/static-assets.mdx, website/docs/en/guide/migration/vite.mdx, website/docs/zh/config/source/assets-include.mdx, website/docs/zh/guide/basic/static-assets.mdx, website/docs/zh/guide/migration/vite.mdx
Update guide for additional asset types.
https://github.com/web-infra-dev/rsbuild/pull/3808
=> docs: update guide for additional asset types

website/docs/en/guide/basic/static-assets.mdx, website/docs/zh/guide/basic/static-assets.mdx
=> docs: add how to import absolute path in CSS files

packages/core/src/types/plugin.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Correct `rsbuild.addPlugins` typing, align with the implementation.
=> docs: correct `rsbuild.addPlugins` typing

packages/core/src/pluginManager.ts
Allow Rsbuild plugin to be registered times. This gives plugins more flexibility in designing their APIs, and allows multiple registrations with different options.
https://github.com/web-infra-dev/rsbuild/issues/3814
=> fix: allow Rsbuild plugin to be registered times

packages/core/src/helpers/index.ts, packages/core/src/server/cliShortcuts.ts, packages/core/src/server/restart.ts
Extract `isTTY` helper to check if running in a TTY context.
=> chore: extract `isTTY` helper

packages/core/src/internal.ts, packages/plugin-less/src/index.ts, packages/plugin-less/tests/index.test.ts
fix the `deepmerge` to judge whether is an plain object.
#3810
=> fix(plugin-less): lessLoaderOptions.lessOptions.plugins has lose it's prototype.

packages/core/src/helpers/index.ts, packages/plugin-less/src/index.ts
- Use modern JavaScript features to write `isPlainObject` more concisely
- Let pluginLess no longer depend on the internal helper of `@rsbuild/core`.
=> chore: simplify `isPlainObject` helper

packages/core/src/config.ts, packages/core/src/plugins/asset.ts, packages/core/src/types/config.ts, packages/core/tests/__snapshots__/environments.test.ts.snap, website/docs/en/config/output/data-uri-limit.mdx, website/docs/en/config/output/dist-path.mdx, website/docs/en/config/output/filename.mdx, website/docs/en/guide/basic/static-assets.mdx, website/docs/zh/config/output/data-uri-limit.mdx, website/docs/zh/config/output/dist-path.mdx, website/docs/zh/config/output/filename.mdx, website/docs/zh/guide/basic/static-assets.mdx
Allow to configure `dataUriLimit` for extended assets:
```js
output: {
dataUriLimit: { assets: 1000 }, 
}
};
```
=> feat: allow to configure `dataUriLimit` for extended assets

.changeset/afraid-beers-train.md, website/docs/en/plugins/list/plugin-preact.mdx, website/docs/zh/plugins/list/plugin-preact.mdx
- Add `prefreshEnabled` option to documentation for `@rsbuild/plugin-preact`.
- Add changeset for bumping version.
https://github.com/web-infra-dev/rsbuild/pull/2469
=> docs(plugin-prefresh): add `prefreshEnabled` option

packages/plugin-preact/src/index.ts
From prefresh README:
> If you want to use @prefresh/webpack with IE11, you'll need to transpile the @prefresh/core and @prefresh/utils packages.
https://github.com/preactjs/prefresh?tab=readme-ov-file#usage-in-ie11
=> fix(plugin-preact): allow to use Prefresh in IE11

.changeset/afraid-beers-train.md, packages/core/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json
* feat: improve JSDoc for `output` and `html` configurations by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3804
* feat: add new `source.assetsInclude` config by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3808
* feat: allow to configure `dataUriLimit` for extended assets by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3826
* feat(plugin-preact): support for prefresh by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/2469
* feat(plugin-preact): add `include` and `exclude` options by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3835
* fix: allow Rsbuild plugin to be registered times by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3818
* fix(plugin-less): lessLoaderOptions.lessOptions.plugins has …
=> release: 1.0.18

.changeset/fast-crabs-sin.md, packages/compat/plugin-webpack-swc/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-vue/package.json, website/docs/en/guide/basic/css-usage.mdx, website/docs/zh/guide/basic/css-usage.mdx
Remove the RC version from the peer dependencies, as we recommend using the stable version.
=> fix: remove RC version from peer dependencies

website/docs/en/guide/framework/preact.mdx, website/docs/zh/guide/framework/preact.mdx
Add the Prefesh recognition tip, referenced from the official Prefresh doc.
https://github.com/preactjs/prefresh?tab=readme-ov-file#best-practices
=> docs: add Prefesh recognition tip

website/docs/en/plugins/list/plugin-sass.mdx, website/docs/zh/plugins/list/plugin-sass.mdx
Add note for Sass deprecation warnings.
https://sass-lang.com/documentation/js-api/interfaces/deprecations/
=> docs(plugin-sass): add note for deprecation warnings

packages/plugin-less/src/index.ts, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-less/tests/index.test.ts
Allow to register `@rsbuild/plugin-less` multiple times.
https://github.com/web-infra-dev/rsbuild/issues/3814
=> feat(plugin-less): allow to register multiple times

website/docs/en/plugins/list/plugin-less.mdx, website/docs/en/plugins/list/plugin-sass.mdx, website/docs/zh/plugins/list/plugin-less.mdx, website/docs/zh/plugins/list/plugin-sass.mdx
Add practices for multiple Less plugins.
https://github.com/web-infra-dev/rsbuild/issues/3814
=> docs: add practices for multiple Less plugins

e2e/cases/assets/assets-retry/index.test.ts, e2e/cases/assets/assets-retry/src/testParallelRetryEntry.js, packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
each retry should be independent.
when two `"max": 3` retries are parallel, the result may be that one is `1, 3`, the other is `2`, so number of times of each retry is not fixed.
`first: 1 2 3` 
`second: 1 2 3`
every request retried three times
=> fix(plugin/assets-retry): calculate the times independently in each retry

packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
😂 loadScript in webpack runtime is for all the script, I'd better to scope it for safer
=> fix(plugin/assets-retry): make loadScript safer

e2e/cases/preact/prefresh-context/index.test.ts, e2e/cases/preact/prefresh-context/rsbuild.config.ts, e2e/cases/preact/prefresh-context/src/A.jsx, e2e/cases/preact/prefresh-context/src/index.js, packages/plugin-preact/package.json, packages/plugin-preact/src/index.ts, pnpm-lock.yaml
Integrate `@swc/plugin-prefresh` to enhance prefresh.
> Prefresh babel plugin is a forked equivalent of the react-refresh babel plugin difference being that we need a way to memoize createContext between HMR.
https://www.npmjs.com/package/@swc/plugin-prefresh
=> feat(plugin-preact): integrate `@swc/plugin-prefresh` to enhance prefresh

website/docs/en/config/output/css-modules.mdx, website/docs/en/guide/basic/css-modules.mdx, website/docs/zh/config/output/css-modules.mdx, website/docs/zh/guide/basic/css-modules.mdx
Correct CSS Modules named import example, `output.cssModules.namedExport` should be enabled.
=> docs: correct CSS Modules named import example

website/theme/components/Copyright.tsx
Add Rsbuild license to the footer of Rsbuild website.
https://github.com/web-infra-dev/rspack/pull/8261
=> docs: add license to website footer

nx.json, packages/compat/webpack/rslib.config.ts, scripts/config/rslib.config.ts
In https://github.com/web-infra-dev/rsbuild/pull/3713, `@rsbuild/webpack` has been changed to a pure ESM package (with a CJS shim wrapper).
But this change introduces the dual package hazard: `@rsbuild/core` will be loaded twice times when `@rsbuild/webpack` is used by a CommonJS package (like Modern.js).
This PR reverts `@rsbuild/webpack` to a dual package to avoid this problem.
- https://github.com/nodejs/package-examples?tab=readme-ov-file#dual-package-hazard
- https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions/runs/11608094993/job/32322683762
=> fix(webpack): avoid duplicate import core package

.changeset/old-dodos-smoke.md, packages/core/src/index.ts
Export ModifyWebpackConfigFn hook type for frameworks to use.
=> feat: export ModifyWebpackConfigFn hook type

package.json, pnpm-lock.yaml
Only check dependency version in CI, we do not need to install the `check-dependency-version-consistency` package locally.
=> chore(workflow): only check dependency version in CI

packages/core/src/initPlugins.ts, packages/core/src/types/plugin.ts, website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Allow to specify `layer` when using `api.transform()`.
https://rspack.dev/config/module#rulelayer
=> feat: add `layer` option to `api.transform()`

packages/core/src/initPlugins.ts, packages/core/src/types/plugin.ts, website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Allow to specify `issuerLayer` when using `api.transform()`.
https://rspack.dev/config/module#ruleissuerlayer
=> feat: add `issuerLayer` option to `api.transform()`

e2e/cases/react/split-chunk/index.test.ts, packages/plugin-react/src/splitChunks.ts
Allow to override builtin split chunks for `@rsbuild/plugin-react`.
resolve https://github.com/web-infra-dev/rsbuild/issues/3786
=> fix(plugin-react): allow to override builtin split chunks

packages/core/src/server/cliShortcuts.ts, packages/core/src/server/devServer.ts, packages/core/src/server/prodServer.ts, packages/core/src/types/config.ts, website/docs/en/config/dev/cli-shortcuts.mdx, website/docs/zh/config/dev/cli-shortcuts.mdx
Add `cliShortcuts.help` option to allow disable the help hint.
```js
dev: {
cliShortcuts: {
help: false,
},
},
};
```
=> feat: add `cliShortcuts.help` option

packages/core/bin/rsbuild.js, packages/core/src/cli/prepare.ts
Should enable Node cache before loading any modules.
- before:
- after:
https://github.com/web-infra-dev/rsbuild/pull/3627
=> perf: enable Node cache before loading modules

packages/core/bin/rsbuild.js
No need for checking NODE_DISABLE_COMPILE_CACHE, Node.js will check it. See https://nodejs.org/api/cli.html#node_disable_compile_cache1
=> fix: no need for checking NODE_DISABLE_COMPILE_CACHE

e2e/cases/server/viewing-served-files/index.test.ts, packages/core/src/server/middlewares.ts
Optimize UI for assets report page.
- before:
- after:
=> feat: optimize UI for assets report page

e2e/cases/svelte/index.test.ts, e2e/cases/svelte/ts/index.test.ts, e2e/cases/svelte/ts/rsbuild.config.ts, e2e/cases/svelte/ts/src/App.svelte, e2e/cases/svelte/ts/src/count.svelte.ts, e2e/cases/svelte/ts/src/index.ts, packages/plugin-svelte/src/index.ts, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Fix `@rsbuilld/plugin-svelte` failed to compile `*.svslte.ts`.
resolve https://github.com/web-infra-dev/rsbuild/issues/3903
=> fix(plugin-svelte): failed to compile *.svslte.ts

.changeset/pretty-flowers-jog.md, packages/core/src/server/middlewares.ts, packages/plugin-svelte/src/index.ts, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap, packages/plugin-svelte/tests/index.test.ts
Fix `*.svslte.ts` and `*.svslte.js` files are transformed twice, we should exclude them from the builtin JS/TS rules.
=> fix(plugin-svelte): `*.svslte.ts` files are transformed twice

e2e/cases/server/ssr/src/index.tsx
https://react.dev/reference/react-dom/client/hydrateRoot
=> test: use hydrateRoot API in SSR case

packages/core/prebundle.config.mjs
The proxy type of `http-proxy-middleware` refers to express, but express is not actually used in rsbuild.
This problem will be temporarily fixed in the prebundle. To completely fix this problem I think we need to upgrade to `http-proxy-middleware` v3 (maybe rsbuild v2)
fix: https://github.com/web-infra-dev/rsbuild/issues/3924
=> fix: proxy type error

packages/core/modern.config.ts, packages/core/package.json, packages/core/rslib.config.ts, packages/core/src/client/hmr.ts, packages/core/src/env.d.ts, pnpm-lock.yaml
I'm gradually switching @rsbuild/core's build tool from Modern.js Module to Rslib, and this is the first PR for it.
=> chore(core): use Rslib to bundle client code

packages/core/src/client/overlay.ts
换行符设置错误，导致 overlay 显示的信息，折行不正确
=> fix: line breaks ` \n` in error overlay messages

packages/core/package.json, packages/core/rslib.config.ts, pnpm-lock.yaml, scripts/config/package.json, scripts/config/rslib.config.ts
Enable Rslib's `dts.build` for incremental building project references.
https://github.com/web-infra-dev/rslib/pull/337
=> chore(build): enable Rslib's `dts.build`

packages/compat/plugin-webpack-swc/package.json, packages/compat/webpack/package.json, packages/compat/webpack/rslib.config.ts, packages/core/package.json, packages/core/rslib.config.ts, packages/create-rsbuild/package.json, packages/create-rsbuild/rslib.config.ts, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-vue/package.json, pnpm-lock.yaml, scripts/config/package.json, scripts/config/rslib.config.ts, scripts/test-helper/package.json
Bump Rslib to v0.0.18.
We no longer need to set `output.target: 'node'` as this becomes the default value, see https://github.com/web-infra-dev/rslib/releases/tag/v0.0.17
=> chore(deps): bump Rslib 0.0.18

packages/core/src/server/open.ts
When local development is allowed and the browser is automatically opened, the host of baseUrl uses the server host configuration by default, instead of directly defaulting to hard-coding localhost
(although it can be specified through open, it is more troublesome for those who use the default open configuration)
=> feat: update the assignment method of host in baseUrl

e2e/cases/cli/watch-files/index.test.ts, e2e/cases/cli/watch-files/rsbuild.config.ts, packages/core/src/cli/init.ts, packages/core/src/server/watchFiles.ts
If `watchFiles.type` is `undefined`, the default type should be `reload-page` as documented.
=> fix: `watchFiles.type` not work as expected

.github/renovate.json5, packages/core/package.json, packages/core/prebundle.config.mjs, packages/core/src/cli/init.ts, packages/core/src/config.ts, packages/core/src/server/devServer.ts, packages/core/src/server/watchFiles.ts, packages/core/src/types/config.ts, pnpm-lock.yaml, scripts/dictionary.txt, website/docs/en/config/dev/watch-files.mdx, website/docs/zh/config/dev/watch-files.mdx
- Bump chokidar to [v4](https://github.com/paulmillr/chokidar/releases) and remove fsevents dependency.
- Use [tinyglobby](https://github.com/SuperchupuDev/tinyglobby) to support glob paths and avoid introducing break change.
The dev startup is now 4ms faster.
- before:
- after:
=> perf: bump chokidar to v4 and remove fsevents dependency

packages/compat/webpack/rslib.config.ts, packages/core/rslib.config.ts, scripts/config/rslib.config.ts
Custom Rslib minify options for Node output, Rsbuild packages can enable the `compress` options of SWC minimizer to reduce the size of Node bundles. This can reduce memory usage and make the startup a little faster.
- before:
- after:
=> perf(build): custom Rslib minify options for Node output

packages/core/src/provider/build.ts
The build is not actually closed when `close()` is called, only watcher was closed before.
https://github.com/web-infra-dev/rspack/blob/8f75992e608d0e317ce94078f1b830d2d44121e6/packages/rspack/src/Compiler.ts#L646
=> fix: close API does not actually close the build

.changeset/popular-roses-learn.md, packages/plugin-stylus/src/index.ts, website/docs/en/plugins/list/plugin-stylus.mdx, website/docs/zh/plugins/list/plugin-stylus.mdx
`stylusOptions.import` should be `string[]` instead of `string`, see https://github.com/webpack-contrib/stylus-loader?tab=readme-ov-file#object
resolve https://github.com/web-infra-dev/rsbuild/issues/3971
=> fix(plugin-stylus): `stylusOptions.import` should be an array

.github/renovate.json5, e2e/cases/assets/assets-retry/index.test.ts, e2e/cases/cli/shortcuts/index.test.ts, e2e/cases/config/rspack-config-validate/index.test.ts, e2e/package.json, e2e/scripts/helper.ts, pnpm-lock.yaml
Use the Node.js builtin util `stripVTControlCharacters` to replace `strip-ansi`
https://nodejs.org/api/util.html#utilstripvtcontrolcharactersstr
=> test: replace strip-ansi with Node.js builtin util

.changeset/brown-books-sort.md, .changeset/popular-roses-learn.md, .changeset/proud-trains-dance.md, .changeset/sixty-pets-hide.md, packages/compat/plugin-webpack-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/plugin-stylus/package.json, packages/plugin-vue/package.json
* feat: add new `output.emitCss` config by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3967
* feat: support restart build in build watch mode by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/3974
* perf: bump chokidar to v4 and remove fsevents dependency by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3960
* perf(build): custom Rslib minify options for Node output by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3966
* fix: `watchFiles.type` not work as expected by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3963
* fix(plugin-vue): should transpile all Vue SFC by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/3964
* fix: close API does not actually close the build by @9aoy in …
=> release: v1.1.2

packages/core/bin/rsbuild.js, packages/core/rslib.config.ts, packages/core/src/cli/commands.ts, packages/core/src/cli/index.ts, packages/core/src/index.ts, packages/core/src/internal.ts
Move `runCLI` from internal helpers to index export.
Motivations:
- To remove all internal helpers.
- `runCLI` now can be used as a public API, it is still undocumented, but users can use it. So we will keep it stable and simple.
=> chore: move `runCLI` from internal helpers to index export

e2e/cases/config/stats-module-trace/index.test.ts, e2e/cases/config/stats-module-trace/rsbuild.config.ts, e2e/cases/config/stats-module-trace/src/index.tsx, e2e/cases/config/stats-module-trace/src/test.tsx, e2e/cases/config/stats-options/index.test.ts, packages/core/src/client/format.ts, packages/core/src/server/socketServer.ts
support print error module traces when `stats.moduleTrace` is enabled.
Maybe we can enable moduleTrace by default, because it is enabled by default in [preset: 'errors-only'](https://github.com/web-infra-dev/rspack/blob/f420048ee32b47007b5482b9a6a43721302dcb83/packages/rspack/src/Stats.ts#L186)
```file=rsbuild.config.ts
tools: {
rspack: {
stats: {
moduleTrace: true,
},
},
};
```
resolve: https://github.com/web-infra-dev/rsbuild/issues/3983
=> feat: support print error module traces

packages/compat/plugin-webpack-swc/package.json, pnpm-lock.yaml
Avoid installing Rslib as dependencies of `@rsbuild/plugin-webpack-swc`.
=> fix(webpack): move Rslib to devDependencies

website/docs/en/guide/advanced/env-vars.mdx, website/docs/zh/guide/advanced/env-vars.mdx
I think the variables that the client can access should be stated at the beginning of .env.
Where the .env file is loaded manually, our example will pass publicVars to source.define. The default value of publicVars should also be briefly commented to avoid misleading people.
https://github.com/web-infra-dev/rsbuild/issues/3975
=> docs: add explanation to .env

.github/workflows/test.yml
Reduce playwright install time, only `chromium` is required.
https://playwright.dev/docs/browsers#install-system-dependencies
=> chore(CI): reduce playwright install time

packages/core/tests/__snapshots__/bundleAnalyzer.test.ts.snap, packages/plugin-sass/src/index.ts, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, website/docs/en/plugins/list/plugin-sass.mdx, website/docs/zh/plugins/list/plugin-sass.mdx
Mute Sass deprecation warnings of dependencies to reduce the noise of Sass logs for daily development:
> If this option is set to true, Sass won’t print warnings that are caused by dependencies. A “dependency” is defined as any file that’s loaded through [loadPaths](https://sass-lang.com/documentation/js-api/interfaces/Options#loadPaths) or [importers](https://sass-lang.com/documentation/js-api/interfaces/Options#importers). Stylesheets that are imported relative to the entrypoint are not considered dependencies. This is useful for silencing deprecation warnings that you can’t fix on your own.
- https://sass-lang.com/documentation/js-api/interfaces/options/#quietDeps
- https://github.com/webpack-contrib/sass-loader/issues/954
=> feat(plugin-sass): mute deprecation warnings of dependencies

e2e/cases/server/print-urls/index.test.ts, packages/core/src/server/helper.ts
fix: print wrong URLs with custom dist path in windows
fix https://github.com/web-infra-dev/rsbuild/issues/3996
=> fix: print wrong URLs with custom dist path in windows

e2e/cases/assets/script-as-assets/index.test.ts, e2e/cases/assets/script-as-assets/rsbuild.config.ts, e2e/cases/assets/script-as-assets/src/index.js, e2e/cases/assets/script-as-assets/src/test1.js, e2e/cases/assets/script-as-assets/src/test2.ts, e2e/cases/assets/script-as-assets/src/test3.mjs, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap, website/docs/en/guide/basic/static-assets.mdx, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/basic/static-assets.mdx, website/docs/zh/guide/start/quick-start.mdx
If we use `new URL()` to reference `.js` or `.ts` files, they will be treated as URL assets and will not be processed by Rsbuild's built-in `swc-loader`.
```tsx
// foo.ts will remain the original content and be output to the dist directory
const fooTs = new URL('./foo.ts', import.meta.url).href;
console.log(fooTs); // "/static/foo.[hash].ts"
```
see https://github.com/web-infra-dev/rsbuild/issues/3953
=> feat: reference script modules as URL assets

e2e/cases/assets/styles-as-assets/index.test.ts, e2e/cases/assets/styles-as-assets/rsbuild.config.ts, e2e/cases/assets/styles-as-assets/src/index.js, e2e/cases/assets/styles-as-assets/src/test1.css, e2e/cases/assets/styles-as-assets/src/test2.less, e2e/cases/assets/styles-as-assets/src/test3.scss, e2e/cases/assets/styles-as-assets/src/test4.styl, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/plugin-less/src/index.ts, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/src/index.ts, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-stylus/src/index.ts, packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap, website/docs/en/guide/basic/static-assets.mdx, website/docs/zh/guide/basic/static-assets.mdx
When using `new URL()` to reference `.css` or `.scss` files, they will be treated as URL assets and will not be processed by Rsbuild's built-in CSS loaders.
```tsx
// foo.css will remain the original content and be output to the dist directory
const fooCss = new URL('./foo.css', import.meta.url).href;
console.log(fooCss); // "/static/foo.[hash].css"
```
The same as https://github.com/web-infra-dev/rsbuild/pull/4011
=> feat: reference style modules as URL assets

packages/core/src/config.ts
Allow to pass a meta data to `defineConfig` function:
```js
await loadConfig({
meta: {},
});
```
=> feat(loadConfig): allow to pass a meta data

packages/core/package.json, pnpm-lock.yaml
bump Rspack v1.1.2 and unpin the version.
https://github.com/web-infra-dev/rspack/pull/8471
=> feat(deps): bump Rspack v1.1.2

examples/module-federation-v2/host/package.json, examples/module-federation-v2/host/rsbuild.config.ts, examples/module-federation-v2/remote/package.json, examples/module-federation-v2/remote/rsbuild.config.ts, pnpm-lock.yaml
Use the MF Rsbuild plugin to simplify the MF v2 examples.
https://module-federation.io/guide/basic/rsbuild.html
=> chore(examples): use MF Rsbuild plugin

pnpm-lock.yaml, website/package.json
bump rspress 1.37.2 to fix website deploy failed.
https://github.com/web-infra-dev/rspress/pull/1609
=> docs(deps): bump rspress 1.37.2

e2e/cases/module-federation-v2/host/rsbuild.config.ts, e2e/cases/module-federation-v2/index.test.ts, e2e/cases/module-federation-v2/remote/rsbuild.config.ts, e2e/package.json, pnpm-lock.yaml
Switch to `@module-federation/rsbuild-plugin` and it supports MF v2 HMR out-of-the-box, so we can enable the MF v2 HMR test case.
https://module-federation.io/guide/basic/rsbuild.html
=> test(e2e): enable MF v2 HMR case

packages/core/src/server/compilerDevMiddleware.ts, packages/core/src/server/getDevMiddlewares.ts
Should close compiler when dev closed. According to `webpack-dev-middleware` doc, middleware close only stop watching for file changes.
https://github.com/webpack/webpack-dev-middleware?tab=readme-ov-file#closecallback
It is expected that the relevant memory can be GC when the compiler closed, however currently this part of the memory cannot be fully GC due to unknown reasons.
=> fix: should close compiler when dev closed

.changeset/cyan-flies-destroy.md, packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
if apps use preload, `__webpack_require__.e` would have other arguments `fetchPriority`, that would cause the error
1. add args placeholder to avoid other runtime code overrides the `__webpack_require__.e`  with some args
2. add some `try catch` logic to make safer
=> fix(plugin-assets-retry): avoid __webpack_require__.e pollution and add some try catch to be safer

packages/plugin-assets-retry/package.json
release: @rsbuild/plugin-assets-retry 1.0.5 
https://github.com/web-infra-dev/rsbuild/pull/4025
=> release: @rsbuild/plugin-assets-retry 1.0.5

packages/compat/plugin-webpack-swc/package.json, packages/compat/webpack/package.json, packages/compat/webpack/rslib.config.ts, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-vue/package.json, pnpm-lock.yaml, scripts/config/package.json, scripts/test-helper/package.json
Bump Rslib v0.1.0, remove unused config.
https://github.com/web-infra-dev/rslib/releases/tag/v0.1.0
close https://github.com/web-infra-dev/rsbuild/pull/4029
=> chore(deps): bump Rslib v0.1.0

e2e/cases/source-map/index.test.ts, packages/compat/plugin-webpack-swc/src/minimizer.ts, packages/compat/plugin-webpack-swc/tests/__snapshots__/plugin.test.ts.snap, packages/core/src/plugins/basic.ts, packages/core/src/plugins/css.ts, packages/core/src/types/config.ts, packages/plugin-less/src/index.ts, packages/plugin-stylus/src/index.ts, website/docs/en/config/output/source-map.mdx, website/docs/zh/config/output/source-map.mdx
Allow `output.sourceMap` to be boolean value to simplify source map configuration.
https://github.com/web-infra-dev/rslib/discussions/467
=> feat: allow `output.sourceMap` to be boolean value

packages/core/src/types/config.ts, website/docs/en/config/performance/print-file-size.mdx, website/docs/zh/config/performance/print-file-size.mdx
Add JSDoc for `PrintFileSizeOptions`.
=> docs: add JSDoc for `PrintFileSizeOptions`

e2e/cases/print-file-size/basic/index.test.ts, packages/core/src/plugins/fileSize.ts, packages/core/src/types/config.ts, website/docs/en/config/performance/print-file-size.mdx, website/docs/zh/config/performance/print-file-size.mdx
Add new `printFileSize.include` option to determine which static assets to print.
https://github.com/web-infra-dev/rsbuild/issues/4041
=> feat: add `printFileSize.include` option

e2e/cases/print-file-size/basic/index.test.ts, e2e/cases/print-file-size/basic/src/App.css, e2e/cases/print-file-size/basic/src/App.jsx, packages/core/src/plugins/fileSize.ts, packages/core/src/types/config.ts, packages/core/tests/fileSize.test.ts, website/docs/en/config/performance/print-file-size.mdx, website/docs/zh/config/performance/print-file-size.mdx
Add new `printFileSize.exclude` option to determine which static assets to exclude.
https://github.com/web-infra-dev/rsbuild/issues/4041Ï
=> feat: add `printFileSize.exclude` option

packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/basic.ts, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap
Update the default `watchOptions` configuration to improve performance by ignoring node_modules.
This will not affect symlinked resources in monorepo, as symlinked resources are resolved to their real path by default.
Using the benchmark repo for testing: https://github.com/rspack-contrib/build-tools-performance
- Memory usage reduced by 120MB
- dev startup speed increased by 40%
- HMR speed increased by 20~30%
- Next.js does not watch node_modules by default: https://github.com/vercel/next.js/blob/56b28ce8f814273b3a991e878731384fb0ebe025/packages/next/src/build/webpack-config.ts#L141
- Vite does not watch node_modules by default: https://vite.dev/config/server-options.html#server-watch
- Twitter votes: https://x.com/rspack_dev/status/1861223088001819115
- …
=> perf: ignore watching files in node_modules

website/docs/en/config/dev/watch-files.mdx, website/docs/en/guide/advanced/hmr.mdx, website/docs/zh/config/dev/watch-files.mdx, website/docs/zh/guide/advanced/hmr.mdx
This pull request updates the documentation to improve clarity and provide more detailed information regarding file watching and HMR in Rspack.
https://github.com/web-infra-dev/rsbuild/pull/4058
=> docs: update file watching

packages/core/src/plugins/fileSize.ts, website/docs/en/config/performance/print-file-size.mdx, website/docs/zh/config/performance/print-file-size.mdx
Print compressed size only for the browser targets by default, which can make Node bundles building faster.
=> perf: no need to calc gzipped size for Node bundles

packages/core/src/cli/commands.ts, website/docs/en/plugins/dev/hooks.mdx, website/docs/en/shared/onCloseBuild.mdx, website/docs/zh/plugins/dev/hooks.mdx, website/docs/zh/shared/onCloseBuild.mdx
Close Rsbuild instance after running `rsbuild build` to trigger the `onCloseBuild` hook.
=> feat(CLI): close instance after building

website/docs/en/config/output/source-map.mdx, website/docs/zh/config/output/source-map.mdx
Adds a recommendation against enabling both `output.injectStyles` and `output.sourceMap.css` in production builds, explaining the potential performance impact.
=> docs: tip for style-loader source map

e2e/cases/output/manifest/index.test.ts, packages/core/src/plugins/manifest.ts, website/docs/en/guide/advanced/ssr.mdx, website/docs/zh/guide/advanced/ssr.mdx
Always write the manifest to disk so that users can get the manifest from disk, regardless of `dev.writeToDisk` configuration.
https://github.com/rspack-contrib/rspack-examples/pull/178
=> feat: always write manifest to disk

website/docs/en/guide/advanced/ssr.mdx
Fixes incorrect usage of `ssr` environment in the documentation. Updated to use the correct node bundle for SSR rendering. In this PR used same environment in doc which used in `Create SSR configuration`.
https://rsbuild.dev/guide/advanced/ssr#custom-server
=> [doc] Fix SSR Node Bundle Usage in Docs

packages/core/src/cli/prepare.ts
Set `process.title` to make it easier to identify the process via activity monitor or other tools.
https://github.com/web-infra-dev/rspack/issues/8566
https://nodejs.org/api/process.html#processtitle
=> feat(CLI): set default `process.title`

e2e/cases/resolve/dedupe/index.test.ts, e2e/cases/resolve/dedupe/rsbuild.config.ts, e2e/cases/resolve/dedupe/src/index.js, packages/core/src/config.ts, packages/core/src/plugins/resolve.ts, packages/core/src/types/config.ts, packages/core/tests/__snapshots__/environments.test.ts.snap
Introduce a new `resolve.dedupe` config  for deduplication of specified packages.
This is essentially syntactic sugar based on `resolve.alias`, but since it might be frequently needed in real-world projects, we decided to add an option to support it.
Documentation will be added later.
=> feat: add `resolve.dedupe` config

packages/core/src/plugins/resolve.ts
`source.alias` has a default value `{}`, remove unused if condition.
=> fix: remove unused if condition

e2e/cases/alias/jsconfig-paths/index.test.ts, e2e/cases/alias/jsconfig-paths/src/common2/test.js, e2e/cases/alias/legacy-alias/index.test.ts, e2e/cases/alias/legacy-alias/rsbuild.config.ts, e2e/cases/alias/legacy-alias/src/common/test.js, e2e/cases/alias/legacy-alias/src/common2/test.js, e2e/cases/alias/legacy-alias/src/index.js, e2e/cases/alias/tsconfig-paths-references/index.test.ts, e2e/cases/alias/tsconfig-paths-references/src/common2/test.ts, e2e/cases/alias/tsconfig-paths-specify-config/rsbuild.config.ts, e2e/cases/alias/tsconfig-paths-specify-config/src/common2/test.ts, e2e/cases/alias/tsconfig-paths/index.test.ts, e2e/cases/alias/tsconfig-paths/src/common2/test.ts, e2e/cases/css/import-common-css/index.test.ts, e2e/cases/css/resolve-alias/rsbuild.config.ts, e2e/cases/source/source.test.ts, e2e/scripts/shared.ts, packages/core/src/config.ts, packages/core/src/plugins/resolve.ts, packages/core/src/types/config.ts, packages/core/tests/__snapshots__/environments.test.ts.snap
Rename `source.alias` to `resolve.alias`, the renamed API is consistent with Rspack/Vite and more intuitive.
```diff
- source: {
+ resolve: {
alias: {}
},
}
```
`source.alias` is deprecated, but it is still available and we plan to remove it in Rsbuild 2.0.
https://rspack.dev/config/resolve#resolvealias
=> feat: add `resolve.alias` and deprecate `source.alias`

packages/core/src/plugins/resolve.ts
Fix `resolve.dedupe` may set incorrect path.
For example, a `foo` package exports `node_modules/foo/foo/index.js` module.
=> fix: `resolve.dedupe` may set incorrect path

packages/plugin-preact/src/index.ts
Use `resolve.alias` in plugin-preact.
https://github.com/web-infra-dev/rsbuild/pull/4098
=> chore(plugin-preact): use `resolve.alias`

packages/core/src/config.ts, packages/core/src/plugins/resolve.ts, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/environments.test.ts, packages/core/tests/mergeConfig.test.ts, packages/core/tests/resolve.test.ts
Both of the following usages should work:
```js
source: {
alias(config) {
delete config['@swc/helpers'];
},
},
});
```
```js
resolve: {
alias(config) {
delete config['@swc/helpers'];
},
},
});
```
https://github.com/web-infra-dev/rsbuild/pull/4098
=> fix: improve compatibility of `source.alias`

packages/compat/plugin-webpack-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-vue/package.json, pnpm-lock.yaml, scripts/config/package.json, scripts/test-helper/package.json
Pin Rslib 0.1.0 to fix unstable CI.
https://github.com/web-infra-dev/rsbuild/actions/runs/12116056090/job/33775821740?pr=4109
=> chore: pin Rslib 0.1.0 to fix unstable CI

website/docs/en/api/javascript-api/environment-context.mdx, website/docs/en/config/dev/setup-middlewares.mdx, website/docs/en/guide/advanced/environments.mdx, website/docs/zh/api/javascript-api/environment-context.mdx, website/docs/zh/config/dev/setup-middlewares.mdx, website/docs/zh/guide/advanced/environments.mdx
=> docs: add environment API type

package.json, pnpm-lock.yaml, website/package.json
Bump Rspress 1.37.4 and remove temp overrides.
https://github.com/web-infra-dev/rspress/releases/tag/v1.37.4
=> chore: bump Rspress and remove overrides

packages/plugin-sass/src/index.ts, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, website/docs/en/plugins/list/plugin-sass.mdx, website/docs/zh/plugins/list/plugin-sass.mdx
`import` is widely used and will not be removed within two years, so I prefer to mute import deprecation warning.
> As previously announced, given the size of this change, we expect to wait at least a two years after this deprecation before we remove @import from the language. While we plan to release Dart Sass 2.0.0 soon with other, smaller breaking changes, that release will not include any changes to @import. Instead, we expect @import to be removed in Dart Sass 3.0.0.
https://sass-lang.com/blog/import-is-deprecated/
=> fix(plugin-sass): mute import deprecation warning

packages/core/src/types/config.ts, website/docs/en/config/dev/cli-shortcuts.mdx, website/docs/zh/config/dev/cli-shortcuts.mdx
Correct `cliShortcuts.custom` typing, `shortcuts` will not be undefined.
=> fix: correct `cliShortcuts.custom` typing

website/docs/en/guide/basic/cli.mdx, website/docs/zh/guide/advanced/env-vars.mdx, website/docs/zh/guide/basic/cli.mdx
The changes primarily focus on improving clarity and consistency in the documentation.
=> docs: fix mistakes in cli.mdx

e2e/cases/server/ssr/index.test.ts, e2e/cases/server/ssr/src/index.server.tsx, packages/core/src/server/devServer.ts, packages/core/src/server/environment.ts
make `loadBundle` and `getTransformedHtml` result cacheable.
https://github.com/web-infra-dev/rsbuild/discussions/4038
=> feat: make environment API result cacheable

packages/core/src/config.ts, packages/core/src/mergeConfig.ts, packages/core/src/plugins/resolve.ts, packages/core/src/types/config.ts, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/resolve.test.ts
Add new `resolve.extensions` config:
```js
resolve: {
extensions: ['.ts', '.js'],
},
};
```
https://rspack.dev/config/resolve#resolveextensions
=> feat: add `resolve.extensions` config

e2e/cases/assets/assets-retry/index.test.ts, packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts, packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
let async-retry url calculating aligned with initial-retry
only support
```ts
domain: ['https://a.com', 'https://b.com']
// or
domain: ['https://a.com/path-foo', 'https://b.com/path-foo']
```
if you uses below
```ts
domain: ['https://a.com/path-foo', 'https://b.com'],
max: 3
output: {
assetPrefix: 'https://a.com/path-foo'
}
```
the retry contexts: 
```
0. https://a.com/path-foo/static/js/main.js
1. https://a.com/path-foo/static/js/main.js
2. https://b.com/path-foo/static/js/main.js
3. https://a.com/path-foo/static/js/main.js
```
```ts
domains: ['https://a.com/path-foo', 'https://b.com'],
max: 3
output: {
assetPrefix: 'https://a.com/path-foo'
}
```
```
0. https://a.com/path-foo/static/js/main.js
1. https://a.com/path-foo/static/js/main.js
2. https://b.com/static/js/main.js
3. …
```
=> fix(plugin-assets-retry): support `output.assetPrefix` with absolute url

packages/core/src/plugins/fileSize.ts
Print file size should always ends with a new line.
=> fix: print file size should ends with a new line

packages/core/src/server/restart.ts
Correct the restart build message, `restart server` should be `restart build`.
=> fix: correct the restart build message

e2e/cases/module-federation-v2/index.test.ts, e2e/cases/module-federation/index.test.ts
Fix failed Module Federation test case. MF runtime contains dynamic import, which can not pass syntax checking, we need to configure `exclude` for it.
https://github.com/sk-pub/module-federation-core/blob/7199bd346980d08270f5620967b8bc7eb4729e73/packages/runtime/src/utils/load.ts#L28
=> test(e2e): fix failed Module Federation test case

e2e/cases/plugin-api/plugin-hooks/environments.test.ts
Fix unstable plugin hooks case:
=> test(e2e): fix unstable plugin hooks case

e2e/cases/plugin-api/plugin-hooks/index.test.ts, packages/compat/webpack/src/createCompiler.ts, packages/core/src/createRsbuild.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/types/context.ts
- Should not trigger dev hooks when building.
- Added `command` property to the internal context.
https://github.com/web-infra-dev/rsbuild/pull/4164
=> fix: should not trigger dev hooks when building

website/docs/en/plugins/list/plugin-svgr.mdx, website/docs/zh/plugins/list/plugin-svgr.mdx
This pull request includes updates to the documentation for the `plugin-svgr`. The changes clarify the behavior when importing SVG files without the `?react` suffix.
resolve https://github.com/web-infra-dev/rsbuild/issues/4167
=> docs(plugin-svgr): explain base64 URL

e2e/package.json, examples/module-federation-v2/host/package.json, examples/module-federation-v2/remote/package.json, pnpm-lock.yaml, website/package.json
Upgrade website to React 19 and fix peer dependency issues.
https://github.com/web-infra-dev/rspress/releases/tag/v1.38.0
=> docs: upgrade to React 19 and fix peer issues

.changeset/chilled-falcons-fetch.md, e2e/cases/html/html-tags/function-usage/index.test.ts, e2e/cases/html/inject/index.test.ts, e2e/cases/html/meta/index.test.ts, e2e/cases/html/script-loading/index.test.ts, e2e/cases/javascript-api/build/index.test.ts, e2e/cases/nonce/basic/index.test.ts, e2e/cases/plugin-api/plugin-modify-tags/index.test.ts, e2e/cases/sri/algotithm/index.test.ts, e2e/cases/sri/basic/index.test.ts, packages/compat/webpack/package.json, packages/compat/webpack/src/provider.ts, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/core/src/index.ts, packages/core/src/provider/helpers.ts, pnpm-lock.yaml
Use `html-webpack-plugin` in `@rsbuild/webpack` by default.
This allows us to:
- Remove `__internalHelper` from `@rsbuild/core`. We no longer need to export the helper for Modern.js
- `@rsbuild/core` can switch to the Rust [HtmlRspackPlugin](https://rspack.dev/plugins/rspack/html-rspack-plugin) in the future.
=> fix(webpack): use html-webpack-plugin by default

website/docs/en/config/server/port.mdx, website/docs/zh/config/server/port.mdx
Clarify the behavior of the server when the port is occupied and provide examples for setting the port using both configuration files and CLI parameters.
=> docs: improve `server.port`

packages/plugin-svelte/src/index.ts
fix require is not defined in computing sveltePath variable
no open issue, just a fix
=> fix(plugin-svelte): require is not defined in computing sveltePath variable

e2e/cases/server/cors/index.test.ts, e2e/cases/server/cors/src/index.js, packages/core/package.json, packages/core/prebundle.config.mjs, packages/core/src/config.ts, packages/core/src/server/getDevMiddlewares.ts, packages/core/src/server/prodServer.ts, packages/core/src/types/config.ts, packages/core/tests/__snapshots__/environments.test.ts.snap, pnpm-lock.yaml
This pull request introduces CORS support across the dev and preview servers, along with corresponding tests and configuration updates. The most important changes include adding CORS middleware (based on https://github.com/expressjs/cors), updating server configurations, and adding tests to ensure CORS functionality.
Documentation will be updated later.
=> feat: add `server.cors` config

e2e/package.json, packages/core/src/plugins/basic.ts
Add a temporary `process.env.EXPERIMENTAL_RSPACK_INCREMENTAL` env var for testing Rspack's new incremental implementation.
Now Rsbuild's e2e tests will run twice, one of which is enabled with incremental.
We will remove it after Rspack incremental is stable.
https://rspack.dev/config/experiments#experimentsincremental
=> test: run e2e cases with Rspack incremental

website/docs/en/config/tools/postcss.mdx, website/docs/zh/config/tools/postcss.mdx
It is recommended to use the `addPlugins` helper so that users do not have to deal with the TypeScript issue:
=> docs: improve PostCSS add plugins example

.github/renovate.json5
Update renovate config: group `sass` packages and remove `modern-js` group.
=> chore(renovate): group sass packages

e2e/cases/server/cors/index.test.ts
The CORS e2e cases are unstable in the Windows CI:
```bash
Error: apiRequestContext.get: connect ECONNREFUSED ::1:24257
Call log:
- → GET http://localhost:24257/
-   user-agent: Playwright/1.44.1 (x64; windows 10.0) node/22.12 CI/1
-   accept: */*
-   accept-encoding: gzip,deflate,br
at D:\a\rsbuild\rsbuild\e2e\apiRequestContext.get: connect ECONNREFUSED ::1:24257
at D:\a\rsbuild\rsbuild\e2e\cases\server\cors\index.test.ts:45:34
```
Possible solution: https://stackoverflow.com/questions/74567328/api-get-request-test-using-playwright
https://github.com/web-infra-dev/rsbuild/actions/runs/12328244091/job/34411201012?pr=4194#step:7:1838
=> test(e2e): fix unsable CORS cases

website/docs/en/guide/framework/react.mdx, website/docs/zh/guide/framework/react.mdx
Provide additional instructions for using the React Compiler with React versions prior to 19 by installing the `react-compiler-runtime` package and specifying the `target` in the configuration.
https://github.com/web-infra-dev/rsbuild/discussions/4197
=> docs: React Compiler for React 17 and 18

website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Change `stage-optimize` to `optimize`, as `stage-optimize` is not defined in [the list of supported stages](https://rsbuild.dev/plugins/dev/core#process-assets-stages). Therefore, the right term is `optimize`.
=> docs(website): revise the description

.github/ISSUE_TEMPLATE/bug-report.en-US.yml, .github/ISSUE_TEMPLATE/feature-request.en-US.yml
The GitHub issue types work well and we can remove the issue label to reduce duplicated information.
https://github.com/web-infra-dev/rsbuild/pull/4171
=> chore(workflow): remove duplicated issue label

packages/core/rslib.config.ts, packages/core/src/index.ts, packages/core/src/rspack/RsbuildHtmlPlugin.ts
This PR includes some planned changes in preparation for the v1.2.0 release.
Rspack & Rsbuild will be releasing the 1.2.0 pre-release this week.
=> chore: prepare for v1.2.0 release

e2e/cases/plugin-api/plugin-transform-import-module/index.test.ts, e2e/cases/plugin-api/plugin-transform-import-module/myPlugin.ts, e2e/cases/plugin-api/plugin-transform-import-module/rsbuild.config.ts, e2e/cases/plugin-api/plugin-transform-import-module/src/foo.ts, e2e/cases/plugin-api/plugin-transform-import-module/src/index.css, e2e/cases/plugin-api/plugin-transform-import-module/src/index.js, packages/core/src/loader/transformLoader.ts, packages/core/src/types/plugin.ts
This is the same as Rspack's `loaderContext.importModule`.
```ts
const myPlugin: RsbuildPlugin = {
setup(api) {
api.transform({ test: /\.css$/ }, async ({ code, importModule }) => {
const { foo } = await importModule(join(__dirname, './src/foo.ts'));
console.log('foo', foo);
return code.replace('red', foo);
});
},
};
```
Documentation will be added later as Rspack also lacks the documentation for this API.
https://github.com/web-infra-dev/rsbuild/pull/4186
=> feat: support for `importModule` in `api.transform`

e2e/cases/server/public-dir/publicDir.test.ts, packages/core/src/plugins/server.ts
should copy `publicDir` to the environment distDir when multiple environments.
https://github.com/web-infra-dev/rslib/issues/583
=> fix: should copy publicDir to the environment distDir when multiple environments

packages/core/package.json, pnpm-lock.yaml
Pin rspack version to avoid mistakenly installing unavailable version of rspack.
https://github.com/web-infra-dev/rspack/releases/tag/v1.1.8
=> fix: pin rspack version

website/docs/en/guide/advanced/alias.mdx, website/docs/en/guide/migration/cra.mdx, website/docs/zh/guide/advanced/alias.mdx, website/docs/zh/guide/migration/cra.mdx
This pull request includes updates to the documentation for configuring path aliases in Rsbuild. The most important changes involve adding examples and clarifying the use of `tsconfig.json` and `jsconfig.json` for setting up path aliases.
https://github.com/web-infra-dev/rsbuild/issues/4228
=> docs: configure alias via jsconfig.json

.github/workflows/release.yml
Update release workflow:
- use `pnpm -r publish` to publish
- rename some tokens
- require less tokens
- add `environment: production`
https://pnpm.io/cli/publish
=> chore(CI): update release workflow

packages/core/rslib.config.ts, packages/core/src/index.ts, packages/core/src/rspack/RsbuildHtmlPlugin.ts
This reverts commit ca531354d2348afcfe874ba75b559ff1d592dfee.
This allows us to release some `1.1.x` patch versions.
=> Revert "chore: prepare for v1.2.0 release (#4207)"

.github/workflows/release.yml
Specify pnpm publish branch in the release workflow, by default pnpm only allows `main` and `master` branches.
https://github.com/web-infra-dev/rsbuild/actions/runs/12445341903/job/34746555603#step:8:7
=> chore(CI): specify pnpm publish branch

e2e/cases/server/public-dir/publicDir.test.ts, packages/core/src/plugins/server.ts
This reverts commit 2b5570eb46b0e87aa09aebf4aee1300d3bb32fd0.
#4220 introduced a change that was not discussed and broke Rspress.
- fix https://github.com/web-infra-dev/rspress/issues/1684
- fix https://github.com/web-infra-dev/rspress/actions/runs/12454094694/job/34764966986?pr=1685#step:9:406
- https://github.com/web-infra-dev/rsbuild/pull/4220
=> Revert "fix: should copy publicDir to the environment distDir when multiple environments (#4220)"

packages/core/src/helpers/index.ts, packages/core/src/server/getDevMiddlewares.ts
Using the `URL` class instead of the deprecated `url.parse` method.
https://nodejs.org/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost
=> chore(server): replace deprecated `url.parse()`

.github/workflows/pr-label.yaml
Specify minimal permissions for the `issue-labeler` action.
https://github.com/github/issue-labeler?tab=readme-ov-file#create-workflow
=> chore(CI): specify minimal permissions for issue-labeler

e2e/cases/config/inspect-config/debug.test.ts, e2e/cases/config/inspect-config/index.test.ts, e2e/cases/performance/bundle-analyzer/index.test.ts, e2e/cases/server/ssr/rsbuild.config.ts
Proxy logs to avoid redundant e2e outputs, such as:
=> test(e2e): proxy logs to avoid redundant e2e outputs

.github/workflows/issue-labeled.yml, .github/workflows/pr-label.yaml
Since the `pr-labeler` workflow adds labels to pull requests, it needs the `pull-requests: write` permission.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#overview
=> chore(CI): correct permissions for issue labeler

README.md, packages/compat/webpack/src/initConfigs.ts, packages/core/src/provider/initConfigs.ts
This pull request includes changes to the `initConfigs` function to ensure async operations are properly awaited.
=> fix: should await inspect config in debug mode

packages/core/src/createRsbuild.ts
When calling the `rsbuild.createCompiler()` method, if `context.command` does not exist, we should assign a default value based on `process.env.NODE_ENV` to ensure dev and build hooks work as expected.
=> fix: set default command for `createCompiler()`

.github/workflows/issue-close-require.yml, .github/workflows/release.yml, website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Updating permissions in workflow files and adding the `importModule` methods to the `TransformContext` type.
https://github.com/web-infra-dev/rsbuild/pull/4217
=> docs: add `importModule` for `api.transform`

website/docs/en/guide/basic/configure-swc.mdx, website/docs/zh/guide/basic/configure-swc.mdx
Link to Rspack's SWC plugin unmatch FAQ to reduce the maintenance burden.
https://github.com/web-infra-dev/rspack/pull/8829
=> docs: link to SWC plugin unmatch FAQ

.github/workflows/issue-close-require.yml, .github/workflows/issue-labeled.yml, .github/workflows/pr-label.yaml, .github/workflows/release.yml
Provenance generation in GitHub Actions requires "write" access to the "id-token" and I should not delete it.
I have added comment to prompt the role of this permission.
=> chore(CI): fix missing permission for provenance

packages/core/package.json, packages/core/src/plugins/manifest.ts, pnpm-lock.yaml
Bump rspack-manifest-plugin to v5.0.3 and reuse the `FileDescriptor` type.
- https://github.com/rspack-contrib/rspack-manifest-plugin/pull/6
- https://github.com/rspack-contrib/rspack-manifest-plugin/releases/tag/v5.0.3
=> chore: bump rspack-manifest-plugin to reuse type

e2e/cases/server/overlay/index.test.ts, packages/core/src/client/overlay.ts, packages/core/src/server/ansiHTML.ts, packages/core/src/server/helper.ts, packages/core/src/server/socketServer.ts, scripts/dictionary.txt
Add support for displaying log colors on error overlay.
- before:
- after:
=> feat: display log colors on error overlay

e2e/cases/server/write-to-disk-environments/index.test.ts, packages/core/src/server/compilerDevMiddleware.ts
should writeToDisk correctly when the environment `writeToDisk` configuration is the same
=> fix: should writeToDisk correctly when environment writeToDisk configuration same

packages/core/src/client/hmr.ts, packages/core/src/server/socketServer.ts
Rsbuild should preserve ansi colors for browser error logs.
- before:
- after:
- https://github.com/web-infra-dev/rsbuild/pull/4266
=> fix: preserve ansi colors for browser error logs

e2e/cases/server/overlay-type-errors/index.test.ts, e2e/cases/server/overlay-type-errors/rsbuild.config.ts, e2e/cases/server/overlay-type-errors/src/index.ts, e2e/cases/server/overlay-type-errors/tsconfig.json, e2e/package.json, pnpm-lock.yaml
Add a new `overlay-type-errors` E2E case:
- https://github.com/web-infra-dev/rsbuild/pull/4266
=> test(e2e): add overlay-type-errors case

e2e/cases/server/setup-middlewares/index.test.ts, packages/core/src/server/compilerDevMiddleware.ts, packages/core/src/server/socketServer.ts, website/docs/en/config/dev/setup-middlewares.mdx, website/docs/zh/config/dev/setup-middlewares.mdx
Prefer to use `static-changed` instead of `content-changed` as the socket type.
This change aims to align with webpack-dev-server v5, see https://github.com/webpack/webpack-dev-server/pull/4679.
`content-changed` is deprecated, we may will remove it in Rsbuild 2.0.
=> chore: prefer to use `static-changed` socket type

packages/core/src/helpers/format.ts
Hint more unknown file types, added Vue / Svelte / MDX / TOML / YAML.
Example:
=> feat: hint more unknown file types

packages/core/src/client/hmr.ts, packages/core/src/client/overlay.ts, packages/core/src/server/socketServer.ts
Move the overlay template to server side to reduce client-side code.
This allows us to implement more powerful overlays in the future without worrying about adding too much client code.
=> perf: move overlay template to server side

packages/core/src/server/ansiHTML.ts, packages/core/tests/ansi.test.ts
- Enhance the `ansiHTML` function to handle more ANSI color codes.
- Add more test cases for it.
=> fix: ansi HTML edge cases

packages/core/src/createContext.ts, packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/core.mdx, website/docs/zh/api/javascript-api/core.mdx
Allow the `environment` option of `createRsbuild` to be an empty array.
=> fix: allow `environment` option of `createRsbuild` to be an empty array

scripts/dictionary.txt, website/docs/en/guide/basic/unocss.mdx, website/docs/zh/guide/basic/unocss.mdx
Update UnoCSS guide to use `@unocss/webpack`.
- https://github.com/web-infra-dev/rsbuild/issues/4285
- https://github.com/unocss/unocss/pull/4173
- https://github.com/rspack-contrib/rspack-examples/pull/197
- https://unocss.dev/integrations/webpack
=> docs: update UnoCSS guide to use `@unocss/webpack`

e2e/cases/output/manifest-generate/index.test.ts, e2e/cases/output/manifest-generate/src/index.ts, packages/core/src/plugins/manifest.ts, packages/core/src/types/config.ts
Allow to custom manifest JSON via `output.manifest.generate` function.
Documentation will be added in the next PR.
- https://github.com/web-infra-dev/rsbuild/pull/4186#discussion_r1884743445
- https://www.npmjs.com/package/webpack-manifest-plugin#generate
=> feat: allow to custom manifest JSON

website/docs/en/config/output/manifest.mdx, website/docs/zh/config/output/manifest.mdx
This pull request includes updates to the documentation for configuring the output manifest file. The changes simplify and clarify the instructions and add new configuration options.
- https://github.com/web-infra-dev/rsbuild/pull/4289
=> docs: add `output.manifest.generate` config

e2e/cases/server/public-dir/publicDir.test.ts, packages/core/src/config.ts, packages/core/src/plugins/server.ts, packages/core/src/types/config.ts, website/docs/en/config/server/public-dir.mdx, website/docs/zh/config/server/public-dir.mdx
Do not copy public dir for node target by default. Update `publicDir.copyOnBuild` default value from `true` to `target !== 'node'` as publicDir is not normally used for node target .
Note 🔴  : This modification may cause breaking changes for some users who use publicDir in node target.
=> fix: do not copy public dir for node target by default

packages/core/rslib.config.ts, packages/core/src/index.ts, packages/core/src/rspack/RsbuildHtmlPlugin.ts
This reverts commit 91a0edd994d4db73d11e3da8206f96741e119daa.
Add https://github.com/web-infra-dev/rsbuild/pull/4207 back.
=> chore: prepare for v1.2.0 pre-release

packages/core/src/config.ts, packages/core/src/plugins/server.ts, packages/core/src/types/config.ts, website/docs/en/config/server/public-dir.mdx, website/docs/zh/config/server/public-dir.mdx
In https://github.com/web-infra-dev/rsbuild/pull/4281, we have changed the default value of `publicDir.copyOnBuild`.
This PR adds the `auto` value to `publicDir.copyOnBuild` to make the default behavior clearer.
=> feat: allow `publicDir.copyOnBuild` to be 'auto'

.github/workflows/ecosystem-ci.yml
Fix pnpm not found in eco CI:
- https://github.com/web-infra-dev/rsbuild/pull/4298
- https://github.com/web-infra-dev/rsbuild/actions/runs/12545829437/job/34980655176#step:5:9
=> chore(CI): fix pnpm not found in eco CI

.github/workflows/ecosystem-ci.yml
Fix ecosystem CI failed to get commit sha:
- https://github.com/web-infra-dev/rsbuild/actions/runs/12547473767/job/34985012119#step:9:17
=> chore(CI): fix ecosystem CI failed to get commit sha

packages/compat/webpack/package.json, packages/core/package.json, packages/plugin-preact/package.json
* feat: hint more unknown file types by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4274
* feat: allow to custom manifest JSON by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4289
* feat(deps): bump Rspack 1.2.0-alpha.0 by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4296
* feat: allow `publicDir.copyOnBuild` to be 'auto' by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4299
* perf: move overlay template to server side by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4276
* perf: replace `commander` with `cac` by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4284
* fix: should copy public dir to environment's dist dir by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4268
* fix: ansi HTML …
=> release: 1.2.0-alpha.0

e2e/cases/output/manifest-async-chunks/index.test.ts, e2e/cases/output/manifest-generate/index.test.ts, e2e/cases/output/manifest/index.test.ts, e2e/cases/output/manifest/src/index.ts, packages/core/src/plugins/manifest.ts, packages/core/src/types/config.ts, website/docs/en/config/output/manifest.mdx, website/docs/zh/config/output/manifest.mdx
Added a new `manifest.filter` config to allow to filter files included in the manifest.
By default, `*.LICENSE.txt` files are excluded from the manifest, as these license files are only used to declare open source licenses and are not used at runtime.
=> feat: allow to filter files included in the manifest

packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/resolve.ts, packages/core/tests/__snapshots__/default.test.ts.snap, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap, website/docs/en/guide/basic/typescript.mdx, website/docs/zh/guide/basic/typescript.mdx
When importing `./foo.js` in a TypeScript file, if there are both `foo.ts` and `foo.js`, Node.js and TypeScript have different resolution orders:
- TypeScript will resolve `foo.ts` first.
- Node.js will resolve `foo.js` first.
Rsbuild should match the behavior of Node.js, because:
1. It maintains consistency with Node.js runtime behavior, avoiding potential surprises when the code runs in production
2. It follows the explicit intent when developers specifically write `.js` in their import statements
This PR fixes this issue from Discord:
=> fix: correct extension alias order to align with Node.js

packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
Avoid using function rest parameters, use `arguments` instead.
Reasons:
- Reduce the generated ES5 code, `asyncChunkRetry.min.js` from `4,582 bytes` -> `4,389 bytes`
- This allows us to use SWC instead of Babel to transform the code. If we use rest parameters, the SWC helpers will introduce `Array.from`, which is an ES6 API. See https://github.com/web-infra-dev/rsbuild/pull/4312.
- The code looks nicer.
- https://github.com/web-infra-dev/rsbuild/pull/4025
=> fix(asset-retry): avoid using function rest parameters

packages/plugin-assets-retry/package.json, packages/plugin-assets-retry/scripts/postCompile.mjs, packages/plugin-assets-retry/src/index.ts, packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts, packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts, packages/plugin-assets-retry/src/runtime/runtime.d.ts, pnpm-lock.yaml
Use SWC to transform and minify code, remove Babel and Terser from dev dependencies.
Let SWC mangle all function names to reduce bundle size:
- initialChunkRetry.min.js: `4,915 bytes` -> `4,275 bytes`
- asyncChunkRetry.min.j: `4,389 bytes` -> `3,351 bytes`
=> perf(asets-retry): use SWC to transform and minify code

packages/plugin-assets-retry/src/index.ts, packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
Normalize runtime options on the server side, this can reduce the client side code:
- initialChunkRetry.min.js: `4,275 bytes` -> `3,980 bytes`
=> perf(assets-retry): normalize options on the server side

packages/core/src/plugins/resolve.ts
Rsbuild allows the path alias to be read from `jsconfig.json`, see https://rsbuild.dev/guide/advanced/alias#jsconfigjson
In this case `extensionAlias` should not be used.
=> fix: no need to use extensionAlias when using jsconfig.json

website/docs/en/plugins/list/index.mdx, website/docs/zh/plugins/list/index.mdx
This pull request includes updates to the documentation to add the Angular plugin to the list of available plugins
https://github.com/Coly010/ng-rspack-build
=> docs: add `@ng-rsbuild/plugin-angular` to plugins list

e2e/cases/assets/assets-retry/index.test.ts, packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts, packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts, scripts/dictionary.txt, website/docs/en/plugins/list/plugin-assets-retry.mdx, website/docs/zh/plugins/list/plugin-assets-retry.mdx
fix
```ts
// At present, we don't consider the switching domain and addQuery of async CSS chunk
// 1. Async js chunk will be requested first. It is rare for async CSS chunk to fail alone.
// 2. the code of loading CSS in webpack runtime is complex and it may be modified by cssExtractPlugin, increase the complexity of this plugin.
```
When I implemented this plugin, rsbuild was just switched from `experiment.css` to `cssExtractPlugin` experimentally, I didn't know much about cssExtract.
after this change, it means that `plugin-assets-retry` can only be used together with `rspack.CssExtractPlugin` and MiniCssExtractPlugin in webpack
😂 by the way, it was also not implemented in "eden"
close #4306
=> fix(plugin/assets-retry): addQuery and switchDomain should work in async css chunk

e2e/cases/assets/assets-retry/index.test.ts, packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts, packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
The nullish coalescing operator is very useful in modern JS code, but it generates some extra code when it is transpiled to ES5.
This PR uses `||` to replace `??` because they are equivalent in the assets retry runtime code.
- `initialChunkRetry.min.js`: 3,980 bytes -> 3,946 bytes
- `asyncChunkRetry.min.js`: 3,778 bytes -> 3,575 byte
=> perf(assets-retry): reduce nullish coalescing operator

packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts, packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts, packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
Use shorter namespace prefix to reduce bundle size.
- `initialChunkRetry.min.js`: 3,946 bytes -> 3,865 bytes
=> perf(assets-retry): use shorter namespace prefix

packages/core/src/internal.ts
`internal.ts` is no longer used since https://github.com/web-infra-dev/rsbuild/pull/4297.
=> chore: remove unused internal.ts

packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/constants.ts, packages/core/tests/__snapshots__/asset.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/types.d.ts, website/docs/en/guide/basic/static-assets.mdx, website/docs/zh/guide/basic/static-assets.mdx
`.cur` is widely used to customize the cursor in CSS.
```css
.baz {
cursor: url("hyper.cur");
}
```
- https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
=> feat: treat `.cur` as image assets

e2e/cases/plugin-api/plugin-transform-import-module/myPlugin.ts
The type issue has been fixed by https://github.com/web-infra-dev/rspack/pull/8766
=> test: remove unused ts-expect-error

CONTRIBUTING.md
Update the release workflow: merge release PR before generating the release tag.
https://github.com/web-infra-dev/rslib/blob/main/CONTRIBUTING.md#releasing
=> chore(workflow): merge release PR first

packages/core/package.json, pnpm-lock.yaml
Bump Rspack to v1.2.0-beta.0.
https://github.com/web-infra-dev/rspack/releases/tag/v1.2.0-beta.0
=> feat(deps): bump Rspack 1.2.0-beta.0

website/docs/en/config/performance/bundle-analyze.mdx, website/docs/zh/config/performance/bundle-analyze.mdx
This pull request includes updates to the `bundle-analyze` documentation. The changes provide instructions on how to disable the `report-web.html` file if it is not needed.
https://github.com/web-infra-dev/rsbuild/discussions/4338
=> docs: only generate stats.json

package.json, patches/http-proxy@1.18.1.patch, pnpm-lock.yaml
The `util._extend` has been deprecated since Node 22. We need to patch `node-http-proxy` before https://github.com/http-party/node-http-proxy/pull/1666 is merged.
- resolve https://github.com/web-infra-dev/rsbuild/issues/4344
=> fix: deprecation warning when using proxy with Node 22

package.json, packages/core/prebundle.config.mjs, patches/css-loader@7.1.2.patch, patches/postcss-loader@8.1.1.patch, pnpm-lock.yaml
Use `pnpm patch` to patch `css-loader` and `postcss`, so we don't have to maintain additional scripts to replace the code.
- https://pnpm.io/cli/patch
=> chore: use pnpm patch instead of custom scripts

website/docs/en/config/source/decorators.mdx, website/docs/zh/config/source/decorators.mdx
Added a link to a resource explaining the differences between different versions of decorators.
=> docs: tip decorators version differences

CODE_OF_CONDUCT.md, README.md, website/docs/en/community/releases/v1-0.mdx, website/docs/en/guide/start/index.mdx, website/i18n.json
This pull request includes several documentation updates to ensure consistent capitalization and terminology usage across files. The changes primarily focus on standardizing the capitalization of "code of conduct" and "quick start."
=> docs: correct some cases

package.json, pnpm-lock.yaml
Bump pnpm to v10.
https://github.com/pnpm/pnpm/releases/tag/v10.0.0
=> chore: bump pnpm to v10

website/docs/en/guide/migration/webpack.mdx, website/docs/zh/guide/migration/webpack.mdx
This pull request includes updates to the migration guide documentation for Rsbuild, focusing on the transition from Babel to SWC. The changes provide detailed instructions on how to replace common Babel plugins with their Rsbuild equivalents.
=> docs: babel migration guide

website/docs/en/config/source/entry.mdx, website/docs/zh/config/source/entry.mdx
Add an example for asynchronous entry configuration.
=> docs: add asynchronous entry configuration example

website/docs/en/plugins/list/plugin-react.mdx, website/docs/zh/plugins/list/plugin-react.mdx
This pull request includes updates to the documentation for the `pluginReact` plugin, adding details about the `swcReactOptions.refresh` option.
=> docs: clarify `swcReactOptions.refresh` option

e2e/cases/output/clean-dist-path/index.test.ts, packages/core/src/helpers/fs.ts, packages/core/src/index.ts, packages/core/src/plugins/cleanOutput.ts, packages/core/src/types/config.ts
Add a new `cleanDistPath.keep` configuration to allow some files to be kept, similar to Rspack's [clean.keep](https://rspack.dev/config/output#outputclean).
This PR also improves the performance of the `emptyDir()` function.
=> feat: add `cleanDistPath.keep` config

.github/workflows/ecosystem-ci.yml, .github/workflows/release.yml
Declare `GitHUB_TOKEN` permissions for eco CI comments.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
=> chore(CI): declare permissions for eco CI comments

website/docs/en/guide/framework/svelte.mdx, website/docs/en/plugins/list/plugin-svelte.mdx, website/docs/zh/guide/framework/svelte.mdx, website/docs/zh/plugins/list/plugin-svelte.mdx
This pull request includes updates to the Svelte documentation to add a note about the current limitation of `svelte-loader` with Svelte v5.
https://github.com/web-infra-dev/rsbuild/issues/4367
=> docs: Svelte v5 HMR tip

website/docs/en/guide/advanced/environments.mdx
Sorry, just a small typo I noticed when reading this part of the docs.
Thanks for the great tooling 👌 
Docs page: https://rsbuild.dev/guide/advanced/environments
=> docs: correct typo in multi-env title

e2e/cases/output/clean-dist-path/index.test.ts, packages/core/src/helpers/fs.ts, packages/core/src/helpers/path.ts, packages/core/src/plugins/basic.ts, website/docs/en/config/output/clean-dist-path.mdx, website/docs/zh/config/output/clean-dist-path.mdx
This pull request updates the path handling for `cleanDistPath.keep` to use POSIX-style paths and removes outdated documentation hints.
=> feat: optimize `cleanDistPath.keep` RegExp

.github/workflows/lint.yml, package.json, pnpm-lock.yaml
Use pnpx to replace npx because it is faster.
- For remote packages: `pnpx` > `npx`
- For locally installed packages: `pnpm exec` > `npx` > `pnpx`
- https://pnpm.io/cli/exec
- https://pnpm.io/cli/dlx
=> chore: use pnpx to replace npx

e2e/cases/css/css-minify-inherit/index.test.ts, e2e/cases/css/css-minify-inherit/rsbuild.config.ts, e2e/cases/css/css-minify-inherit/src/index.css, e2e/cases/css/css-minify-inherit/src/index.js, packages/core/src/plugins/css.ts, packages/core/src/plugins/minimize.ts, website/docs/en/config/output/minify.mdx, website/docs/zh/config/output/minify.mdx
If user has configured `tools.lightningcssLoader` options, we should will use them as the default CSS minimizer options.
This helps to keep development and production consistent.
resolve https://github.com/web-infra-dev/rsbuild/issues/4374
=> fix: let lightningcss minimizer inherit loader options

packages/plugin-sass/src/index.ts, packages/plugin-sass/src/types.ts, website/docs/en/plugins/list/plugin-sass.mdx
Adds new `useOriginalUrlResolver` option to disable `resolve-url-loader`
Relative url usage like [this](https://github.com/junhea/rsbuild-sass-issue-sample/blob/2f5df5922c2161fdff50fb1bbec18b1a5a9360fb/src/assets/partials/_foo.scss#L2) should build
=> feat(plugin-sass): add `useOriginalUrlResolver` option to disable `resolve-url-loader`

packages/core/src/configChain.ts, packages/core/src/plugins/asset.ts
not regular
should be `${type}-asset-url`
```
font  font-asset-url
additional  additional-asset-url
```
for Rslib Asset
https://github.com/web-infra-dev/rslib/pull/684
=> fix(core): `output.assetsInclude` adds a rule but not exposes public api

packages/plugin-sass/src/index.ts, packages/plugin-sass/src/types.ts, website/docs/en/plugins/list/plugin-sass.mdx
Rename the unreleased `useOriginalUrlResolver` option to `rewriteUrls`, which can more clearly express the role of resolve-url-loader.
- https://github.com/web-infra-dev/rsbuild/pull/4389 
- https://github.com/bholloway/resolve-url-loader/blob/v5/packages/resolve-url-loader/README.md
- https://webpack.js.org/loaders/sass-loader/#problems-with-url
- https://github.com/sass/sass/issues/2535
=> chore(plugin-sass): rename unreleased option

e2e/cases/server/cors/index.test.ts, packages/core/src/config.ts, packages/core/src/types/config.ts, packages/core/tests/__snapshots__/environments.test.ts.snap, website/docs/en/config/server/cors.mdx, website/docs/zh/config/server/cors.mdx
This PR follows Vite's security patches to disallow fetching from untrusted origins.
Although this is a breaking change, considering that `server.cors` was newly added in version [v1.1.11](https://github.com/web-infra-dev/rsbuild/releases/tag/v1.1.11), it's unlikely that many users are relying on this behavior.
See:
- [GHSA-vg6x-rcgg-rjx6](https://github.com/vitejs/vite/security/advisories/GHSA-vg6x-rcgg-rjx6)
- https://github.com/vitejs/vite/commit/b09572acc939351f4e4c50ddf793017a92c678b1
=> fix!: disable `server.cors` by default for security reasons

website/docs/en/plugins/list/plugin-sass.mdx, website/docs/zh/plugins/list/plugin-sass.mdx
This pull request includes updates to the documentation for the `pluginSass` configuration option, specifically adding details about the `rewriteUrls` option.
- https://github.com/web-infra-dev/rsbuild/pull/4389
- https://github.com/web-infra-dev/rsbuild/pull/4398
=> docs(plugin-sass): improve `rewriteUrls` option

packages/core/package.json, pnpm-lock.yaml
Bump Rspack v1.2.0.
- https://github.com/web-infra-dev/rspack/releases/tag/v1.2.0
- https://github.com/web-infra-dev/rspack/pull/9065
- https://github.com/web-infra-dev/rspack/pull/9060
=> feat(deps): bump Rspack v1.2.0

website/docs/zh/api/javascript-api/core.mdx
=> docs(javascript-api): fix defineConfig parameters

website/docs/en/api/javascript-api/core.mdx
Fix defineConfig parameters in English documentation.
https://github.com/web-infra-dev/rsbuild/pull/4412
=> docs(javascript-api): fix defineConfig parameters in English documentation

packages/core/src/config.ts, packages/core/src/plugins/entry.ts, website/docs/en/config/source/entry.mdx, website/docs/zh/config/source/entry.mdx
Add support for additional entry file extensions (mts, cts) and updating the documentation to reflect these changes.
https://www.typescriptlang.org/docs/handbook/modules/reference.html#module-format-detection
=> feat: add support for additional entry file extensions (mts, cts)

packages/core/package.json, pnpm-lock.yaml
Bump Rspack v1.2.2.
See https://github.com/web-infra-dev/rspack/releases/tag/v1.2.2
=> fix(deps): bump Rspack v1.2.2

e2e/cases/cli/watch-files/index.test.ts
Fix occasional `directory not empty` error when wait and rm dist in e2e tests. Sometimes the dist directory exists, but the files in the dist directory have not been completely written.
=> test: fix occasional `directory not empty` error in e2e

packages/core/src/loader/transformLoader.ts, packages/core/src/types/plugin.ts, website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Support for `resolve` and `context` in `api.transform`, same as rspack loader api.
```js
api.transform(
{ test: /index\.js$/ },
async ({ code, resolve, context, resource }) => {
resolve(context!, '@foo', (err, res) => {
console.log('resolved', res);
});
},
);
```
https://rspack.dev/api/loader-api/context
=> feat: support for `resolve` and `context` in `api.transform`

packages/core/src/provider/rspackConfig.ts
Warn when using Rspack devServer config:
- https://rspack.dev/config/dev-server
=> feat: warn when using Rspack devServer config

packages/core/src/server/compilerDevMiddleware.ts
The primary change involves renaming a function to fix wrapper typo.
=> chore: fix wrapper typo

e2e/cases/stylus/basic/index.test.ts, e2e/cases/stylus/basic/rsbuild.config.ts, e2e/cases/stylus/environment/index.test.ts, e2e/cases/stylus/environment/rsbuild.config.ts, e2e/cases/stylus/environment/src/a.styl, e2e/cases/stylus/environment/src/b.module.styl, e2e/cases/stylus/environment/src/index.js, e2e/cases/stylus/rem/index.test.ts, e2e/cases/stylus/rem/rsbuild.config.ts, packages/core/src/createRsbuild.ts, packages/core/src/initPlugins.ts
Fix failed to register environment plugin.
Since https://github.com/web-infra-dev/rsbuild/pull/4283, `rsbuildOptions.environment` will be empty array by default, and we should use `context.specifiedEnvironments` to filter environments.
https://github.com/web-infra-dev/rsbuild/issues/4435
=> fix(core): failed to register environment plugin
