web-infra-dev/rsbuild

.changeset/sour-lamps-drive.md, packages/friendly-errors-webpack-plugin/CHANGELOG.md, packages/friendly-errors-webpack-plugin/package.json, packages/monorepo-utils/CHANGELOG.md, packages/monorepo-utils/package.json, packages/shared/CHANGELOG.md, packages/shared/package.json
- chore: extract shared dependencies
=> Release v0.0.3

.eslintrc.js, cspell.json, package.json, packages/friendly-errors-webpack-plugin/example/src/foo.js, pnpm-lock.yaml
https://github.com/web-infra-dev/oxc
=> chore: replace ESLint with Oxlint

.github/workflows/lint.yml
=> chore(CI): add Lint workflow

.changeset/four-plums-love.md, cspell.json, packages/babel-preset/package.json, packages/babel-preset/src/base.ts, packages/babel-preset/src/index.ts, packages/babel-preset/src/node.ts, packages/babel-preset/src/types.ts, packages/babel-preset/src/web.ts, pnpm-lock.yaml
Same as https://github.com/web-infra-dev/modern.js/tree/v2.35.1/packages/cli/babel-preset-base
=> feat(babel-preset): add babel plugins

.github/workflows/test-ubuntu.yml, .github/workflows/test-windows.yml, cspell.json, package.json, packages/babel-preset/tests/a.test.ts, packages/babel-preset/tests/tsconfig.json, packages/shared/tests/a.test.ts, packages/shared/tests/tsconfig.json, pnpm-lock.yaml, vitest.workspace.ts
https://vitest.dev/guide/workspace.html#workspace
=> test: setup vitest workspaces

.changeset/sixty-doors-tan.md, package.json, packages/vitest-helper/modern.config.ts, packages/vitest-helper/package.json, packages/vitest-helper/src/index.ts, packages/vitest-helper/src/path.ts, packages/vitest-helper/src/pathSerializer.ts, packages/vitest-helper/tsconfig.json, pnpm-lock.yaml, scripts/vitest.setup.ts, vitest.workspace.ts
ref: https://github.com/web-infra-dev/modern.js/tree/v2.35.1/scripts/vitest-config
=> feat: setup @rsbuild/vitest-helper

.changeset/four-plums-love.md, .changeset/neat-kids-develop.md, .changeset/silent-brooms-run.md, .changeset/sixty-doors-tan.md, packages/babel-preset/CHANGELOG.md, packages/babel-preset/package.json, packages/monorepo-utils/CHANGELOG.md, packages/monorepo-utils/package.json, packages/shared/CHANGELOG.md, packages/shared/package.json, packages/vitest-helper/CHANGELOG.md, packages/vitest-helper/package.json
- feat(babel-preset): add babel plugins
- feat(babel-preset): add support for preset-env and preset-typescript
- feat: setup @rsbuild/vitest-helper
- fix(babel-preset): should not register dynamic-import-node plugin for web
=> Release v0.0.4

.changeset/famous-yaks-serve.md, packages/babel-preset/src/base.ts, packages/babel-preset/src/node.ts, packages/babel-preset/src/pluginLockCorejsVersion.ts, packages/babel-preset/src/types.ts, packages/babel-preset/src/web.ts, packages/babel-preset/tests/__snapshots__/web.test.ts.snap, packages/babel-preset/tests/node.test.ts, packages/babel-preset/tests/web.test.ts
- add lockCorejsVersion plugin
=> feat(babel-preset): add lockCorejsVersion plugin

.changeset/famous-yaks-serve.md, packages/babel-preset/CHANGELOG.md, packages/babel-preset/package.json, packages/monorepo-utils/CHANGELOG.md, packages/monorepo-utils/package.json, packages/shared/CHANGELOG.md, packages/shared/package.json, packages/vitest-helper/CHANGELOG.md, packages/vitest-helper/package.json
- feat(babel-preset): add lockCorejsVersion plugin
=> Release v0.0.5

README.md
=> docs: update banner pic

packages/document/docs/en/config/experiments/sourceBuild.md, packages/document/docs/en/config/output/assetsRetry.md, packages/document/docs/en/config/output/cssModules.md, packages/document/docs/en/config/security/checkSyntax.md, packages/document/docs/en/config/source/alias.md, packages/document/docs/en/config/tools/babel.md, packages/document/docs/en/config/tools/bundlerChain.mdx, packages/document/docs/en/config/tools/cssLoader.md, packages/document/docs/en/config/tools/terser.md, packages/document/docs/en/config/tools/webpack.md, packages/document/docs/en/config/tools/webpackChain.md, packages/document/docs/en/guide/basic/css-modules.md, packages/document/docs/en/shared/alias.md, packages/document/docs/zh/config/experiments/sourceBuild.md, packages/document/docs/zh/config/html/tags.md, packages/document/docs/zh/config/output/assetsRetry.md, packages/document/docs/zh/config/output/cssModules.md, packages/document/docs/zh/config/security/checkSyntax.md, packages/document/docs/zh/config/source/alias.md, packages/document/docs/zh/config/tools/babel.md, packages/document/docs/zh/config/tools/bundlerChain.mdx, packages/document/docs/zh/config/tools/cssLoader.md, packages/document/docs/zh/config/tools/terser.md, packages/document/docs/zh/config/tools/webpack.md, packages/document/docs/zh/config/tools/webpackChain.md, packages/document/docs/zh/guide/basic/css-modules.md, packages/document/docs/zh/shared/alias.md, packages/document/rspress.config.ts
Close https://github.com/web-infra-dev/rsbuild/issues/16
=> docs: switch the default language to English

packages/document/docs/en/index.md, packages/document/docs/zh/index.md
=> docs: add logo to home page

packages/document/docs/en/index.md, packages/document/docs/zh/index.md, packages/document/rspress.config.ts
Update logo, favicon and navbar icon.
=> docs: update logo, favicon and navbar icon

packages/shared/package.json
=> fix(shared): remove unused exports overrides

packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-esbuild.mdx, packages/document/docs/en/plugins/list/plugin-image-compress.mdx, packages/document/docs/en/plugins/list/plugin-node-polyfill.mdx, packages/document/docs/en/plugins/list/plugin-stylus.mdx, packages/document/docs/en/plugins/list/plugin-swc.mdx, packages/document/docs/en/plugins/list/plugin-vue.mdx, packages/document/docs/en/plugins/list/plugin-vue2.mdx, packages/document/docs/zh/plugins/list/index.md, packages/document/docs/zh/plugins/list/plugin-esbuild.mdx, packages/document/docs/zh/plugins/list/plugin-image-compress.mdx, packages/document/docs/zh/plugins/list/plugin-node-polyfill.mdx, packages/document/docs/zh/plugins/list/plugin-stylus.mdx, packages/document/docs/zh/plugins/list/plugin-swc.mdx, packages/document/docs/zh/plugins/list/plugin-vue.mdx, packages/document/docs/zh/plugins/list/plugin-vue2.mdx
Sort plugin list and update register guide
=> docs(plugins): sort plugins list and update register guide

.changeset/warm-planets-remain.md, cspell.json, packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/en/plugins/dev/hooks.mdx, packages/document/docs/zh/api/javascript-api/instance.mdx, packages/document/docs/zh/plugins/dev/hooks.mdx, packages/shared/package.json, packages/shared/src/createContext.ts, packages/shared/src/logger.ts, pnpm-lock.yaml
https://github.com/rspack-contrib/rslog
=> chore: replace modern.js logger with rslog

.eslintignore, README.zh-CN.md, packages/plugin-swc/tests/browserslist.ts, packages/plugin-swc/tests/utils.ts, packages/shared/src/utils.ts
=> chore: fix Oxc lint issues

packages/document/docs/en/api/start/index.mdx, packages/document/docs/en/guide/start/quick-start.mdx, packages/document/docs/zh/api/start/index.mdx, packages/document/docs/zh/guide/start/quick-start.mdx
Update quick start document of JavaScript API.
=> docs: update quick start document of JavaScript API

.changeset/serious-berries-cheat.md, examples/basic/package.json, examples/basic/rsbuild.config.ts, examples/basic/src/index.ts, packages/core/bin/rsbuild.js, packages/core/package.json, packages/core/src/cli/commands.ts, packages/core/src/cli/config.ts, packages/core/src/cli/index.ts, packages/core/src/cli/provider.ts, packages/core/src/index.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Add basic implementation of CLI.
=> feat(core): add basic implementation of CLI

packages/core/src/cli/config.ts, packages/core/src/cli/provider.ts, packages/plugin-esbuild/package.json, packages/plugin-esbuild/src/index.ts, packages/plugin-esbuild/tests/index.test.ts, packages/plugin-image-compress/package.json, packages/plugin-image-compress/src/index.ts, packages/plugin-image-compress/src/minimizer.ts, packages/plugin-image-compress/tests/index.test.ts, packages/plugin-node-polyfill/package.json, packages/plugin-node-polyfill/src/index.ts, packages/plugin-node-polyfill/tests/index.test.ts, packages/plugin-stylus/package.json, packages/plugin-stylus/src/index.ts, packages/plugin-stylus/tests/index.test.ts, packages/plugin-swc/package.json, packages/plugin-swc/src/minimizer.ts, packages/plugin-swc/src/plugin.ts, packages/plugin-swc/src/utils.ts, packages/plugin-swc/tests/plugin.test.ts, packages/plugin-vue/package.json, packages/plugin-vue/src/index.ts, packages/plugin-vue/tests/index.test.ts, packages/plugin-vue2/package.json, packages/plugin-vue2/src/index.ts, packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap, packages/plugin-vue2/tests/index.test.ts, pnpm-lock.yaml
Replace builder-webpack-provider with `@rsbuild/webpack`.
=> chore(deps): replace builder-webpack-provider

.changeset/fresh-terms-invent.md, packages/core/src/plugins/target.ts, packages/shared/src/constants.ts, packages/shared/src/schema/source.ts, packages/shared/src/types/builder.ts, packages/shared/src/utils.ts, packages/shared/tests/getBrowserslist.test.ts, packages/webpack/src/core/webpackConfig.ts
close https://github.com/web-infra-dev/rsbuild/issues/64
=> chore: remove modern-web build target

.changeset/popular-humans-lie.md, packages/document/docs/en/guide/basic/output-files.md, packages/document/docs/zh/guide/basic/output-files.md
=> fix(@rsbuild/document): correct api content for disableHtmlFolder

package.json, packages/babel-preset/tests/tsconfig.json, packages/babel-preset/tsconfig.json, packages/core/tests/tsconfig.json, packages/core/tsconfig.json, packages/document/package.json, packages/document/tsconfig.json, packages/monorepo-utils/tsconfig.json, packages/plugin-esbuild/tests/tsconfig.json, packages/plugin-esbuild/tsconfig.json, packages/plugin-image-compress/tests/tsconfig.json, packages/plugin-image-compress/tsconfig.json, packages/plugin-node-polyfill/tests/tsconfig.json, packages/plugin-node-polyfill/tsconfig.json, packages/plugin-stylus/tests/tsconfig.json, packages/plugin-stylus/tsconfig.json, packages/plugin-swc/tsconfig.json, packages/plugin-vue/tests/tsconfig.json, packages/plugin-vue/tsconfig.json, packages/plugin-vue2/tests/tsconfig.json, packages/plugin-vue2/tsconfig.json, packages/shared/tests/tsconfig.json, packages/shared/tsconfig.json, packages/vitest-helper/tsconfig.json, packages/webpack/tests/tsconfig.json, packages/webpack/tsconfig.json, pnpm-lock.yaml, scripts/tsconfig.base.json
=> chore: use self hosted tsconfig

packages/core/package.json, packages/core/src/cli/provider.ts, packages/core/src/index.ts, packages/plugin-node-polyfill/package.json, packages/plugin-node-polyfill/src/index.ts, packages/plugin-stylus/package.json, packages/plugin-stylus/src/index.ts, packages/plugin-vue/package.json, packages/plugin-vue2/package.json, packages/shared/src/constants.ts, pnpm-lock.yaml
Decouple with builder-rspack-provider.
=> chore: decouple with builder-rspack-provider

.changeset/nasty-pianos-beg.md, packages/core/tests/rspack-provider/plugins/__snapshots__/html.test.ts.snap, packages/core/tests/rspack-provider/plugins/__snapshots__/pug.test.ts.snap, packages/document/docs/en/guide/basic/output-files.md, packages/document/docs/en/shared/config/html/disableHtmlFolder.md, packages/document/docs/en/shared/config/output/distPath.md, packages/document/docs/zh/guide/basic/output-files.md, packages/document/docs/zh/shared/config/html/disableHtmlFolder.md, packages/document/docs/zh/shared/config/output/distPath.md, packages/shared/src/config.ts, packages/shared/src/constants.ts, packages/webpack/tests/plugins/__snapshots__/html.test.ts.snap, packages/webpack/tests/plugins/__snapshots__/inlineChunk.test.ts.snap
https://github.com/web-infra-dev/rsbuild/issues/14
=> feat: flatten the output html files

packages/shared/src/config.ts
Rename the inspected config file.
=> chore: rename the inspected config file

.github/workflows/lint.yml, .github/workflows/test-ubuntu.yml, .github/workflows/test-windows.yml
=> chore(workflows): run test and lint on push

.pnpmfile.cjs, packages/babel-preset/tests/__snapshots__/web.test.ts.snap, packages/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/webpack/tests/plugins/__snapshots__/babel.test.ts.snap, packages/webpack/tests/plugins/__snapshots__/default.test.ts.snap, packages/webpack/tests/plugins/__snapshots__/react.test.ts.snap, packages/webpack/tests/plugins/__snapshots__/tsLoader.test.ts.snap, pnpm-lock.yaml
Alias the rsbuild scoped packages to workspace.
=> chore: alias the rsbuild scoped packages to workspace

packages/core/package.json, packages/core/tests/tsconfig.json, pnpm-lock.yaml
=> chore: fix cyclic deps between core and vitest-helper

packages/document/docs/en/api/javascript-api/core.mdx, packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/en/api/javascript-api/types.mdx, packages/document/docs/en/api/start/index.mdx, packages/document/docs/en/guide/advanced/rspack-start.mdx, packages/document/docs/en/guide/basic/builder-cli.mdx, packages/document/docs/en/guide/basic/config.mdx, packages/document/docs/en/guide/framework/vue2.mdx, packages/document/docs/en/guide/framework/vue3.mdx, packages/document/docs/en/guide/start/quick-start.mdx, packages/document/docs/en/plugins/dev/core.mdx, packages/document/docs/en/plugins/dev/index.md, packages/document/docs/zh/api/javascript-api/core.mdx, packages/document/docs/zh/api/javascript-api/instance.mdx, packages/document/docs/zh/api/javascript-api/types.mdx, packages/document/docs/zh/api/start/index.mdx, packages/document/docs/zh/guide/advanced/rspack-start.mdx, packages/document/docs/zh/guide/basic/builder-cli.mdx, packages/document/docs/zh/guide/basic/config.mdx, packages/document/docs/zh/guide/framework/vue2.mdx, packages/document/docs/zh/guide/framework/vue3.mdx, packages/document/docs/zh/plugins/dev/core.mdx, packages/document/docs/zh/plugins/dev/index.md, packages/shared/src/types/config/index.ts, packages/shared/src/types/context.ts, packages/shared/src/types/provider.ts, packages/webpack/src/types/config/index.ts
Update the provider guide for JavaScript API
=> docs: update the provider guide for JavaScript API

packages/document/docs/en/guide/basic/config.mdx, packages/document/docs/en/guide/debug/debug-mode.md, packages/document/docs/en/guide/faq/general.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/en/index.md, packages/document/docs/en/shared/bundler.md, packages/document/docs/en/shared/nodeVersion.md, packages/document/docs/zh/guide/basic/config.mdx, packages/document/docs/zh/guide/debug/debug-mode.md, packages/document/docs/zh/guide/faq/general.md, packages/document/docs/zh/guide/start/index.mdx, packages/document/docs/zh/index.md, packages/document/docs/zh/shared/bundler.md, packages/document/docs/zh/shared/nodeVersion.md
=> docs: improve start documents

packages/core/src/rspack-provider/core/rspackConfig.ts, packages/document/docs/en/plugins/dev/hooks.mdx, packages/document/docs/zh/plugins/dev/hooks.mdx, packages/plugin-node-polyfill/src/index.ts, packages/plugin-node-polyfill/tests/__snapshots__/index.test.ts.snap, packages/shared/src/types/hooks.ts, packages/webpack/src/core/webpackConfig.ts
=> chore: remove rspack builtins.provide

.github/workflows/lint.yml, package.json, packages/document/package.json, packages/plugin-swc/package.json, pnpm-lock.yaml
Add dependency version checker.
https://github.com/bmish/check-dependency-version-consistency
=> chore(workflow): add dependency version checker

packages/document/docs/en/plugins/list/_meta.json, packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-vue-jsx.mdx, packages/document/docs/en/plugins/list/plugin-vue.mdx, packages/document/docs/zh/plugins/list/_meta.json, packages/document/docs/zh/plugins/list/index.md, packages/document/docs/zh/plugins/list/plugin-vue-jsx.mdx, packages/document/docs/zh/plugins/list/plugin-vue.mdx
Add document for Vue JSX plugin.
=> docs: add document for Vue JSX plugin

e2e/cases/import-antd-v4/index.test.ts, e2e/cases/import-antd-v4/package.json, e2e/cases/import-antd-v5/index.test.ts, e2e/cases/import-antd-v5/package.json, e2e/cases/import-arco/index.test.ts, e2e/cases/import-arco/package.json, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap, packages/core/tests/rspack-provider/plugins/__snapshots__/swc.test.ts.snap, packages/plugin-swc/package.json, packages/webpack/package.json, packages/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/webpack/tests/plugins/__snapshots__/default.test.ts.snap, pnpm-lock.yaml
- antd is too heavy
- the `isPackageInstalled` util it not precise
=> test: remove ui libs, improve testing stability

packages/document/docs/en/plugins/list/_meta.json, packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-vue2-jsx.mdx, packages/document/docs/en/plugins/list/plugin-vue2.mdx, packages/document/docs/zh/plugins/list/_meta.json, packages/document/docs/zh/plugins/list/index.md, packages/document/docs/zh/plugins/list/plugin-vue2-jsx.mdx, packages/document/docs/zh/plugins/list/plugin-vue2.mdx
Add document for Vue2 JSX plugin
=> docs: add document for Vue2 JSX plugin

packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-stylus.mdx, packages/document/docs/zh/plugins/list/index.md, packages/document/docs/zh/plugins/list/plugin-stylus.mdx
Improve plugins list document.
=> docs: improve plugins list

packages/document/docs/en/api/javascript-api/core.mdx, packages/document/docs/en/guide/basic/config.mdx, packages/document/docs/zh/api/javascript-api/core.mdx, packages/document/docs/zh/guide/basic/config.mdx
Add guide for merging configurations.
https://github.com/web-infra-dev/rsbuild/issues/37
=> docs: add guide for merging configurations

packages/document/docs/en/guide/start/_meta.json, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/en/guide/start/npm-packages.mdx, packages/document/docs/en/plugins/list/index.md, packages/document/docs/zh/guide/start/_meta.json, packages/document/docs/zh/guide/start/index.mdx, packages/document/docs/zh/guide/start/npm-packages.mdx, packages/document/docs/zh/plugins/list/index.md
=> docs: add npm packages page

packages/webpack/src/plugins/babel.ts, packages/webpack/tests/plugins/__snapshots__/babel.test.ts.snap
https://github.com/web-infra-dev/modern.js/pull/4830
=> fix: babel addIncludes & addExcludes not take effect

packages/core/src/rspack-provider/core/createContext.ts, packages/plugin-type-checker/CHANGELOG.md, packages/plugin-type-checker/LICENSE, packages/plugin-type-checker/README.md, packages/plugin-type-checker/modern.config.ts, packages/plugin-type-checker/package.json, packages/plugin-type-checker/src/index.ts, packages/plugin-type-checker/tsconfig.json, packages/shared/package.json, packages/shared/src/re-exports/fork-ts-checker-webpack-plugin.ts, packages/shared/src/types/config/tools.ts, packages/shared/src/types/thirdParty.ts, pnpm-lock.yaml
Init @rsbuild/plugin-type-checker package.
=> feat: init @rsbuild/plugin-type-checker package

packages/core/tests/plugins/__snapshots__/asset.test.ts.snap, packages/core/tests/plugins/__snapshots__/bundleAnalyzer.test.ts.snap, packages/core/tests/plugins/__snapshots__/cache.test.ts.snap, packages/core/tests/plugins/__snapshots__/checkSyntax.test.ts.snap, packages/core/tests/plugins/__snapshots__/define.test.ts.snap, packages/core/tests/plugins/__snapshots__/networkPerformance.test.ts.snap, packages/core/tests/plugins/__snapshots__/nodeAddons.test.ts.snap, packages/core/tests/plugins/__snapshots__/splitChunks.test.ts.snap, packages/core/tests/plugins/__snapshots__/svg.test.ts.snap, packages/core/tests/plugins/__snapshots__/toml.test.ts.snap, packages/core/tests/plugins/__snapshots__/wasm.test.ts.snap, packages/core/tests/plugins/__snapshots__/yaml.test.ts.snap, packages/core/tests/plugins/asset.test.ts, packages/core/tests/plugins/bundleAnalyzer.test.ts, packages/core/tests/plugins/cache.test.ts, packages/core/tests/plugins/checkSyntax.test.ts, packages/core/tests/plugins/define.test.ts, packages/core/tests/plugins/entry.test.ts, packages/core/tests/plugins/external.test.ts, packages/core/tests/plugins/fileSize.test.ts, packages/core/tests/plugins/networkPerformance.test.ts, packages/core/tests/plugins/nodeAddons.test.ts, packages/core/tests/plugins/splitChunks.test.ts, packages/core/tests/plugins/startUrl.test.ts, packages/core/tests/plugins/svg.test.ts, packages/core/tests/plugins/target.test.ts, packages/core/tests/plugins/toml.test.ts, packages/core/tests/plugins/wasm.test.ts, packages/core/tests/plugins/yaml.test.ts
=> chore: migrate rsbuild/plugin test cases

packages/document/rspress.config.ts
=> docs: configure Google Analytics

packages/babel-preset/README.md, packages/core/README.md, packages/document/README.md, packages/monorepo-utils/README.md, packages/plugin-esbuild/README.md, packages/plugin-image-compress/README.md, packages/plugin-node-polyfill/README.md, packages/plugin-stylus/README.md, packages/plugin-swc/README.md, packages/plugin-type-check/README.md, packages/plugin-vue-jsx/README.md, packages/plugin-vue/README.md, packages/plugin-vue2-jsx/README.md, packages/plugin-vue2/README.md, packages/shared/README.md, packages/test-helper/README.md, packages/webpack/README.md
Simplify README and remove dead link.
=> docs: simplify README and remove dead link

packages/plugin-source-build/CHANGELOG.md, packages/plugin-source-build/LICENSE, packages/plugin-source-build/README.md, packages/plugin-source-build/modern.config.ts, packages/plugin-source-build/package.json, packages/plugin-source-build/src/index.ts, packages/plugin-source-build/tests/index.test.ts, packages/plugin-source-build/tests/tsconfig.json, packages/plugin-source-build/tsconfig.json, pnpm-lock.yaml
https://github.com/web-infra-dev/rsbuild/issues/23
=> feat: init @rsbuild/plugin-source-build

cspell.json, packages/core/src/rspack-provider/core/rspackConfig.ts, packages/core/src/rspack-provider/plugins/babel.ts, packages/core/src/rspack-provider/plugins/minimize.ts, packages/document/docs/en/shared/config/tools/bundlerChain.mdx, packages/document/docs/en/shared/config/tools/webpackChain.md, packages/document/docs/zh/shared/config/tools/bundlerChain.mdx, packages/document/docs/zh/shared/config/tools/webpackChain.md, packages/plugin-swc/src/utils.ts, packages/shared/src/apply/resolve.ts, packages/shared/src/chain.ts, packages/shared/src/types/hooks.ts, packages/webpack/src/core/webpackConfig.ts, packages/webpack/src/plugins/minimize.ts, packages/webpack/src/plugins/resolve.ts, packages/webpack/src/types/hooks.ts
- add CHAIN_ID constants
https://github.com/web-infra-dev/rsbuild/issues/22
=> chore(shared): add CHAIN_ID constants

.github/workflows/update-modern.yml, .github/workflows/update-rspress.yml, packages/document/package.json, pnpm-lock.yaml
=> feat: update rspress version

packages/plugin-react/tests/__snapshots__/webpack.test.ts.snap, packages/webpack/src/plugins/babel.ts, packages/webpack/tests/plugins/__snapshots__/default.test.ts.snap
=> chore: apply babel in modifyBundlerChain

e2e/cases/serve/index.test.ts, examples/basic-webpack/package.json, examples/basic/package.json, packages/core/src/cli/commands.ts, packages/core/src/createRsbuild.ts, packages/core/src/rspack-provider/provider.ts, packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/en/guide/basic/cli.mdx, packages/document/docs/zh/api/javascript-api/instance.mdx, packages/document/docs/zh/guide/basic/cli.mdx, packages/shared/src/types/provider.ts, packages/shared/src/types/rsbuild.ts, packages/webpack/src/provider.ts
Rename serve command to preview, same as `rspress`.
=> refactor: rename serve command to preview

cspell.json, packages/document/docs/en/guide/basic/typescript.md, packages/document/docs/en/guide/start/npm-packages.mdx, packages/document/docs/zh/guide/basic/typescript.md, scripts/skipCI.js
=> docs: update use TypeScript guide

.github/workflows/update-modern.yml, .github/workflows/update-rspress.yml, cspell.json, package.json, packages/core/package.json, packages/shared/package.json, packages/webpack/package.json, pnpm-lock.yaml, scripts/update-packages/package.json, scripts/update-packages/src/modern.ts
Update pull request title and fix root bump.
=> chore(workflow): update pull request title and fix root bump

package.json, packages/plugin-image-compress/tests/__snapshots__/index.test.ts.snap, packages/plugin-swc/tests/__snapshots__/plugin.test.ts.snap, packages/plugin-swc/tests/index.test.ts, packages/plugin-swc/tests/plugin.test.ts, pnpm-lock.yaml, vitest.workspace.ts
=> fix: update some plugin-swc test cases

package.json, scripts/update-packages/package.json, scripts/update-packages/src/rspack.ts
=> chore: support update-rspack

packages/create-rsbuild/CHANGELOG.md, packages/create-rsbuild/LICENSE, packages/create-rsbuild/README.md, packages/create-rsbuild/package.json, packages/create-rsbuild/src/index.ts, packages/document/docs/en/guide/start/npm-packages.mdx, packages/document/docs/zh/guide/start/npm-packages.mdx, pnpm-lock.yaml
=>  chore: init create-rsbuild package

README.md, README.zh-CN.md, packages/document/rspress.config.ts
=> docs: update the discord link

packages/create-rsbuild/package.json, packages/create-rsbuild/src/index.ts, pnpm-lock.yaml
=> feat: implement create-rsbuild

packages/create-rsbuild/template-vue2-js/README.md, packages/create-rsbuild/template-vue2-js/gitignore, packages/create-rsbuild/template-vue2-js/package.json, packages/create-rsbuild/template-vue2-js/rsbuild.config.ts, packages/create-rsbuild/template-vue2-js/src/App.vue, packages/create-rsbuild/template-vue2-js/src/index.html, packages/create-rsbuild/template-vue2-js/src/index.js, packages/create-rsbuild/template-vue2-js/src/style.css, packages/create-rsbuild/template-vue2-ts/README.md, packages/create-rsbuild/template-vue2-ts/gitignore, packages/create-rsbuild/template-vue2-ts/package.json, packages/create-rsbuild/template-vue2-ts/rsbuild.config.ts, packages/create-rsbuild/template-vue2-ts/src/App.vue, packages/create-rsbuild/template-vue2-ts/src/env.d.ts, packages/create-rsbuild/template-vue2-ts/src/index.html, packages/create-rsbuild/template-vue2-ts/src/index.ts, packages/create-rsbuild/template-vue2-ts/src/style.css, packages/create-rsbuild/template-vue2-ts/tsconfig.json, pnpm-lock.yaml
=> feat(create-rsbuild): add Vue 2 templates

cspell.json, packages/doctor-sdk/modern.config.esm.ts, packages/doctor-sdk/modern.config.ts, packages/doctor-sdk/package.json, packages/doctor-sdk/src/module-graph/tree-shaking/export.ts, packages/doctor-types/package.json, packages/doctor-utils/modern.config.esm.ts, packages/doctor-utils/package.json
Fix resolutions warning and correct package json.
=> chore: fix resolutions warning and correct package json

.changeset/yellow-masks-bake.md, packages/doctor-sdk/modern.config.esm.ts, packages/doctor-utils/modern.config.esm.ts, packages/doctor-utils/package.json, packages/doctor-utils/src/index.ts, packages/doctor-utils/src/rule-utils/document/document.ts, packages/doctor-utils/src/rule-utils/document/index.ts, packages/doctor-utils/src/rule-utils/document/server.ts, packages/doctor-utils/src/rule-utils/document/types.ts, packages/doctor-utils/src/rule-utils/index.ts, packages/doctor-utils/src/rule-utils/parser/asserts.ts, packages/doctor-utils/src/rule-utils/parser/index.ts, packages/doctor-utils/src/rule-utils/parser/parser.ts, packages/doctor-utils/src/rule-utils/parser/types.ts, packages/doctor-utils/src/rule-utils/parser/utils.ts, packages/doctor-utils/tests/parser/parser.test.ts, pnpm-lock.yaml
rsbuild doctor add rule-utils code to @rsbuild/doctor-utils.
rule-utils is some utils functions for building rules.
=> feat(@rsbuild/doctor): rsbuild doctor add rule-utils package

.changeset/rude-bottles-dream.md, packages/create-rsbuild/src/index.ts
Fix failed to resolve the templates.
=> fix(create-rsbuild): failed to resolve the templates

packages/create-rsbuild/package.json
Fix:  https://github.com/web-infra-dev/rsbuild/actions/runs/6663221852/job/18108771656
=> chore: try remove provenance for create-rsbuild releasing

package.json, packages/core/package.json, packages/shared/package.json, packages/webpack/package.json, pnpm-lock.yaml
=> chore(deps): bump Modern.js version

packages/create-rsbuild/src/index.ts
chore: modify the prompt for the startup command
=> fix: modify the prompt for the startup command

packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/en/api/start/index.mdx, packages/document/docs/zh/api/javascript-api/instance.mdx, packages/document/docs/zh/api/start/index.mdx, packages/shared/src/devServer.ts, packages/shared/src/prodServer.ts
=> feat: simplify dev server logs

packages/document/docs/en/guide/_meta.json, packages/document/docs/en/guide/framework/vue2.mdx, packages/document/docs/en/guide/framework/vue3.mdx, packages/document/docs/en/shared/deployApp.md, packages/document/docs/en/shared/vue2Project.md, packages/document/docs/en/shared/vue3Project.md, packages/document/docs/zh/guide/_meta.json, packages/document/docs/zh/guide/framework/vue2.mdx, packages/document/docs/zh/guide/framework/vue3.mdx, packages/document/docs/zh/shared/deployApp.md, packages/document/docs/zh/shared/vue2Project.md, packages/document/docs/zh/shared/vue3Project.md, packages/document/rspress.config.ts
=> docs: update Vue 2 / 3 guides

.changeset/rich-toes-cheat.md, packages/doctor-sdk/src/module-graph/utils.ts, packages/doctor-sdk/tests/utils.spec.ts, packages/doctor-utils/src/common/package.ts
rsbuild-doctor add based on instructions.
=> chore(doctor): add based on comments

packages/compat/webpack/package.json, packages/compat/webpack/src/plugins/react.ts, packages/compat/webpack/src/shared/plugin.ts, packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap, packages/compat/webpack/tests/plugins/__snapshots__/react.test.ts.snap, packages/compat/webpack/tests/plugins/react.test.ts, packages/plugin-react/package.json, packages/plugin-react/src/arco.ts, packages/plugin-react/src/index.ts, packages/plugin-react/src/react.ts, packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap, packages/plugin-styled-components/tests/index.test.ts, pnpm-lock.yaml
=> refactor(plugin-react): move webpack related logics

packages/shared/src/devServer.ts, packages/shared/src/port.ts, packages/shared/src/prodServer.ts
Improve logs when port is used.
=> chore: improve logs when port is used

.changeset/fluffy-mice-swim.md, packages/create-rsbuild/template-common/README.md
Fix incorrect preview command.
=> fix(create-rsbuild): incorrect preview command

.changeset/gorgeous-cheetahs-decide.md, packages/core/package.json, packages/core/src/plugins/fileSize.ts, pnpm-lock.yaml
=> perf(core): remove strip-ansi dependency

.changeset/friendly-llamas-pump.md, packages/compat/webpack/src/config/validate/tools.ts, packages/compat/webpack/src/types/config/tools.ts, packages/core/src/rspack-provider/config/validate/tools.ts, packages/shared/src/schema/tools.ts, packages/shared/src/types/config/tools.ts
Add missing tools schemas, move more common schemas to shared.
=> fix(schema): add missing tools schemas

README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx
=> docs: add Rust toolchain to README

.changeset/plenty-icons-play.md, packages/create-rsbuild/template-react-js/package.json, packages/create-rsbuild/template-react-ts/package.json, packages/create-rsbuild/template-svelte-js/package.json, packages/create-rsbuild/template-svelte-ts/package.json, packages/create-rsbuild/template-vue2-js/package.json, packages/create-rsbuild/template-vue2-ts/package.json, packages/create-rsbuild/template-vue3-js/package.json, packages/create-rsbuild/template-vue3-ts/package.json, packages/plugin-svelte/package.json, pnpm-lock.yaml
Fix failed to resolve svelte-preprocess.
=> fix(plugin-svelte): failed to resolve svelte-preprocess

packages/document/docs/en/shared/alias.md, packages/document/docs/en/shared/config/source/alias.md, packages/document/docs/en/shared/config/source/compileJsDataURI.md, packages/document/docs/en/shared/config/source/define.md, packages/document/docs/en/shared/config/source/include.md, packages/document/docs/en/shared/config/source/resolveExtensionPrefix.md, packages/document/docs/zh/shared/alias.md, packages/document/docs/zh/shared/config/source/alias.md, packages/document/docs/zh/shared/config/source/compileJsDataURI.md, packages/document/docs/zh/shared/config/source/define.md, packages/document/docs/zh/shared/config/source/include.md, packages/document/docs/zh/shared/config/source/resolveExtensionPrefix.md
=> docs: update source configs and Rspack doc links

.changeset/shaggy-crabs-pay.md, packages/create-rsbuild/src/index.ts, packages/create-rsbuild/template-react-js/package.json, packages/create-rsbuild/template-react-ts/package.json, packages/create-rsbuild/template-svelte-js/package.json, packages/create-rsbuild/template-svelte-ts/package.json, packages/create-rsbuild/template-vue2-js/package.json, packages/create-rsbuild/template-vue2-ts/package.json, packages/create-rsbuild/template-vue3-js/package.json, packages/create-rsbuild/template-vue3-ts/package.json, pnpm-lock.yaml
Always use the latest version when create new projects.
=> feat(create-rsbuild): always use the latest version

cspell.json, packages/compat/unibuilder/CHANGELOG.md, packages/compat/unibuilder/LICENSE, packages/compat/unibuilder/README.md, packages/compat/unibuilder/modern.config.ts, packages/compat/unibuilder/package.json, packages/compat/unibuilder/tests/tsconfig.json, packages/compat/unibuilder/tsconfig.json, packages/compat/webpack/package.json, pnpm-lock.yaml
Init @rsbuild/unibuilder package.
https://github.com/web-infra-dev/rsbuild/discussions/239
=> chore: init @rsbuild/unibuilder package

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress version

.changeset/shiny-countries-vanish.md, packages/compat/webpack/src/core/initConfigs.ts, packages/compat/webpack/src/core/webpackConfig.ts, packages/compat/webpack/src/plugins/tsLoader.ts, packages/core/src/plugins/entry.ts, packages/core/src/plugins/html.ts, packages/core/src/plugins/startUrl.ts, packages/core/src/rspack-provider/core/initConfigs.ts, packages/core/src/rspack-provider/core/rspackConfig.ts, packages/plugin-babel/src/helper.ts, packages/shared/src/apply/resolve.ts, packages/shared/src/chain.ts, packages/shared/src/getLoaderOptions.ts, packages/shared/src/mergeRsbuildConfig.ts, packages/shared/src/utils.ts
Unify the castArray implementation.
=> chore(utils): unify the castArray implementation

packages/compat/webpack/src/plugins/minimize.ts, packages/compat/webpack/src/types/config/tools.ts, packages/document/docs/en/plugins/list/_meta.json, packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-css-minimizer.mdx, packages/document/docs/zh/plugins/list/_meta.json, packages/document/docs/zh/plugins/list/index.md, packages/document/docs/zh/plugins/list/plugin-babel.mdx, packages/document/docs/zh/plugins/list/plugin-css-minimizer.mdx, packages/plugin-css-minimizer/src/index.ts
Add guide for css minimizer plugin.
close https://github.com/web-infra-dev/rsbuild/issues/302
=> docs: add guide for css minimizer plugin

.changeset/thirty-lamps-look.md, packages/plugin-source-build/src/index.ts
=> fix: modify the priority order of source field and default mainFeilds

packages/doctor-utils/tests/build/time.test.ts
https://github.com/web-infra-dev/rsbuild/actions/runs/6740539295/job/18323771553?pr=321
=> tests(doctor): skip timeout test case

.changeset/quiet-poets-hope.md, packages/compat/plugin-swc/src/minimizer.ts, packages/compat/webpack/src/webpackPlugins/ModuleScopePlugin.ts, packages/compat/webpack/src/webpackPlugins/ProgressPlugin/helpers/bar.ts, packages/compat/webpack/src/webpackPlugins/ProgressPlugin/helpers/type.ts, packages/core/src/plugins/fileSize.ts, packages/core/src/plugins/nodeAddons.ts, packages/core/src/rspack-provider/provider.ts, packages/plugin-check-syntax/src/helpers/generateError.ts, packages/plugin-check-syntax/src/helpers/printErrors.ts, packages/shared/package.json, packages/shared/src/color.ts, packages/shared/src/config.ts, packages/shared/src/format.ts, packages/shared/src/index.ts, packages/shared/src/logger.ts, packages/shared/src/port.ts, packages/shared/src/prettyTime.ts, packages/shared/src/prodServer.ts, packages/shared/src/progress.ts, packages/shared/src/re-exports/chalk.ts, packages/shared/src/re-exports/index.ts, pnpm-lock.yaml, vitest.workspace.ts
Replace chalk with picocolors.
https://github.com/web-infra-dev/rsbuild/issues/345
=> perf: replace chalk with picocolors

.changeset/selfish-otters-approve.md, packages/plugin-css-minimizer/src/index.ts
=> fix(css-minimizer): only apply in production

packages/document/docs/en/plugins/list/index.md, packages/document/docs/zh/plugins/list/index.md
=> docs: sort plugins list

.changeset/dry-pens-applaud.md, packages/compat/plugin-swc/package.json, pnpm-lock.yaml
Bump swc-plugins and swc-helpers
@swc/helpers changes:
- https://github.com/swc-project/swc/pull/8076
- https://github.com/swc-project/swc/pull/8097
=> chore: bump swc and helpers

package.json, pnpm-lock.yaml
=> chore(workflow): make nx build faster

.changeset/mean-oranges-grab.md, packages/document/src/utils.ts
=> fix: link error in NextStep component

.gitignore
=> chore: add .history to gitignore

README.md, README.zh-CN.md
=> docs: add npm downloads badge

.changeset/pretty-keys-develop.md, e2e/cases/html/html.test.ts, e2e/cases/html/title/index.test.ts, packages/compat/webpack/tests/plugins/__snapshots__/html.test.ts.snap, packages/compat/webpack/tests/plugins/__snapshots__/inlineChunk.test.ts.snap, packages/core/src/plugins/html.ts, packages/core/tests/rspack-provider/plugins/__snapshots__/html.test.ts.snap, packages/document/docs/en/shared/config/html/title.md, packages/document/docs/zh/shared/config/html/title.md, packages/shared/src/config.ts, packages/shared/src/mergeChainedOptions.ts, packages/shared/src/types/config/html.ts
Support html.title as a function.
https://github.com/web-infra-dev/rsbuild/issues/360
=>  feat: support html.title as a function

e2e/cases/type-checker/tsconfig.json, packages/document/docs/en/plugins/list/plugin-type-check.mdx, packages/document/docs/zh/plugins/list/plugin-type-check.mdx
Add guide for type check performance.
=> docs: add guide for type check performance

e2e/cases/svelte/index.test.ts, e2e/cases/svelte/less/src/App.svelte, e2e/cases/svelte/less/src/index.js, e2e/cases/svelte/package.json, e2e/cases/svelte/scss/src/App.svelte, e2e/cases/svelte/scss/src/index.js, e2e/cases/svelte/stylus/src/App.svelte, e2e/cases/svelte/stylus/src/index.js, e2e/cases/svelte/ts/src/App.svelte, e2e/cases/svelte/ts/src/index.ts, e2e/cases/svelte/ts/tsconfig.json, pnpm-lock.yaml
close https://github.com/web-infra-dev/rsbuild/issues/272
=> test: add more e2e test cases for plugin-svelte

packages/compat/webpack/src/plugins/css.ts, packages/compat/webpack/src/plugins/less.ts, packages/compat/webpack/src/plugins/sass.ts, packages/core/src/plugins/define.ts, packages/core/src/plugins/startUrl.ts, packages/core/src/rspack-provider/plugins/css.ts, packages/core/src/rspack-provider/plugins/less.ts, packages/core/src/rspack-provider/plugins/sass.ts, packages/plugin-node-polyfill/src/index.ts, packages/plugin-source-build/src/index.ts, packages/plugin-stylus/src/index.ts, packages/plugin-vue-jsx/src/index.ts, packages/plugin-vue/src/index.ts, packages/plugin-vue2-jsx/src/index.ts, packages/plugin-vue2/src/index.ts, packages/shared/src/apply/resolve.ts, packages/shared/src/css.ts, packages/shared/src/getLoaderOptions.ts, packages/shared/src/plugins/HtmlCrossOriginPlugin.ts, packages/shared/src/plugins/HtmlNetworkPerformancePlugin.ts, packages/shared/src/plugins/HtmlNoncePlugin.ts, packages/shared/tests/mergeChainedOptions.test.ts
Remove unnecessary async functions.
=> chore: remove unnecessary async functions

.changeset/green-deers-design.md, packages/core/package.json, packages/doctor-types/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml
Bump Rspack v0.3.11.
Ref: https://github.com/web-infra-dev/rspack/releases/tag/v0.3.11
=> feat(deps): bump Rspack v0.3.11

e2e/cases/lodash/index.swc.test.ts
Fix lodash cases occasionally failed:
=> test(e2e): fix lodash cases occasionally failed

e2e/cases/css/style-loader/index.test.ts, packages/document/docs/en/shared/config/output/disableCssExtract.md, packages/document/docs/zh/shared/config/output/disableCssExtract.md, packages/shared/src/css.ts
Add note for CSS minify with style-loader
=> docs: add note for CSS minify with style-loader

.changeset/real-terms-confess.md, packages/doctor-utils/src/common/time.ts, packages/doctor-utils/tests/build/time.test.ts
=>  fix: doctor utils time test error

.changeset/great-pandas-punch.md, cspell.json, packages/shared/src/devServer.ts, packages/shared/src/port.ts
Fix url logs break the progress bar.
=> fix: url logs break the progress bar

.changeset/olive-poets-repair.md, examples/react-webpack/package.json, examples/react-webpack/rsbuild.config.ts, examples/react-webpack/src/App.css, examples/react-webpack/src/App.jsx, examples/react-webpack/src/index.jsx, packages/compat/uni-builder/src/shared/parseCommonConfig.ts, packages/compat/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap, packages/compat/webpack/src/core/createCompiler.ts, packages/compat/webpack/src/plugins/progress.ts, packages/compat/webpack/src/webpackPlugins/ProgressPlugin/helpers/bar.ts, packages/core/src/cli/config.ts, packages/core/src/cli/index.ts, packages/core/src/rspack-provider/core/createCompiler.ts, packages/core/src/rspack-provider/plugins/progress.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap, packages/document/docs/en/shared/config/dev/progressBar.md, packages/document/docs/zh/shared/config/dev/progressBar.md, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/shared/src/config.ts, packages/shared/src/devServer.ts, packages/shared/src/types/config/dev.ts, pnpm-lock.yaml
Only enable progress bar in production.
=> feat: only enable progress bar in production

packages/compat/webpack/src/core/devMiddleware.ts, packages/compat/webpack/src/core/startDevServer.ts, packages/compat/webpack/src/provider.ts, packages/core/package.json, packages/core/src/rspack-provider/core/devMiddleware.ts, packages/core/src/rspack-provider/core/startDevServer.ts, packages/core/src/rspack-provider/provider.ts, packages/core/src/server/constants.ts, packages/core/src/server/dev-middleware/index.ts, packages/core/src/server/dev-middleware/socketServer.ts, packages/core/src/server/devServer.ts, packages/core/src/server/https.ts, packages/core/src/server/index.ts, packages/shared/package.json, packages/shared/src/devServer.ts, packages/shared/src/types/index.ts, packages/shared/src/types/provider.ts, packages/shared/src/types/server.ts, packages/shared/tests/devServer.test.ts, pnpm-lock.yaml
https://github.com/web-infra-dev/rsbuild/issues/3
=> chore: decouple type with modern.js server

.changeset/cuddly-pillows-kick.md, packages/doctor-sdk/tests/server/apis/index.test.ts
fix: doctor sdk router tests error
=> fix: doctor sdk router tests error

packages/core/package.json, packages/core/src/server/devServer.ts, packages/core/src/server/middlewares.ts, packages/core/src/server/prodServer.ts, packages/core/src/server/proxy.ts, packages/shared/package.json, packages/shared/src/types/config/tools.ts, pnpm-lock.yaml
=> feat: add proxy & favicon fallback middlewares

.changeset/cuddly-clouds-divide.md, packages/shared/src/types/stats.ts
https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/6819385524/job/18546640006
=> types: fix stats chunk type for rspack-ecosystem-ci

.changeset/purple-schools-press.md, packages/core/types.d.ts
Provide all static assets types, consistent with: https://rsbuild.dev/guide/basic/static-assets.html
=> types: provide all static assets types

.changeset/sharp-bears-taste.md, packages/core/types.d.ts
Add configuration files (YAML / TOML) and simplify queries.
=> types: add configuration files and simplify queries

.changeset/famous-tomatoes-breathe.md, packages/compat/webpack/package.json, packages/core/package.json, packages/plugin-assets-retry/package.json, packages/shared/package.json, pnpm-lock.yaml
Bump html-rspack-plugin v5.5.4.
=> chore(deps): bump html-rspack-plugin v5.5.4

examples/uni-builder/build.mjs, examples/uni-builder/dev.mjs, examples/uni-builder/package.json, examples/uni-builder/src/App.css, examples/uni-builder/src/App.jsx, examples/uni-builder/src/index.jsx, pnpm-lock.yaml
Add uni-builder example for debugging.
=> chore: add uni-builder example

.changeset/stale-beans-teach.md, packages/compat/webpack/tests/plugins/__snapshots__/react.test.ts.snap, packages/document/docs/en/guide/optimization/split-chunk.md, packages/document/docs/en/shared/config/performance/chunkSplit.md, packages/document/docs/zh/guide/optimization/split-chunk.md, packages/document/docs/zh/shared/config/performance/chunkSplit.md, packages/plugin-react/src/splitChunks.ts, packages/plugin-react/tests/__snapshots__/features.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Split react-refresh to lib-react.js.
=> feat(plugin-react): split react-refresh to lib-react.js

.changeset/silly-coins-roll.md, packages/compat/webpack/package.json, packages/core/package.json, packages/plugin-assets-retry/package.json, packages/shared/package.json, pnpm-lock.yaml
Bump html-rspack-plugin v5.5.5, ref: https://github.com/rspack-contrib/html-rspack-plugin/commit/bfc4a19744212334c3c342bcbe92162e9a63d5df
=> chore(deps): bump html-rspack-plugin v5.5.5

.changeset/nervous-maps-lick.md, examples/vanilla/package.json, examples/vanilla/rsbuild.config.ts, examples/vanilla/src/index.css, examples/vanilla/src/index.js, packages/create-rsbuild/src/index.ts, packages/create-rsbuild/template-vanilla-js/package.json, packages/create-rsbuild/template-vanilla-js/rsbuild.config.mjs, packages/create-rsbuild/template-vanilla-js/src/index.css, packages/create-rsbuild/template-vanilla-js/src/index.js, packages/create-rsbuild/template-vanilla-ts/package.json, packages/create-rsbuild/template-vanilla-ts/rsbuild.config.ts, packages/create-rsbuild/template-vanilla-ts/src/index.css, packages/create-rsbuild/template-vanilla-ts/src/index.ts, pnpm-lock.yaml
=> feat(create-rsbuild): add new vanilla template

packages/document/docs/en/guide/start/quick-start.mdx, packages/document/docs/zh/guide/start/quick-start.mdx
Add templates list to quickstart.
=> docs: add templates list to quickstart

.changeset/gentle-geese-glow.md, packages/core/package.json, packages/core/src/plugins/html.ts, packages/core/src/plugins/rem.ts, packages/core/src/rspack-provider/plugins/swc.ts, packages/core/src/rspack-provider/rspackLoader/css-modules-typescript-pre-loader/postcss-icss-extract-plugin.ts, packages/shared/src/re-exports/deepmerge.ts, packages/shared/src/utils.ts, packages/shared/tests/utils.test.ts, pnpm-lock.yaml
Remove lodash dependency from `@rsbuild/core`.
=> chore(core): remove lodash dependency

e2e/cases/output/assets-retry/index.test.ts, e2e/package.json, pnpm-lock.yaml
Fix assetsRetry e2e test case.
=> test: fix assetsRetry e2e test case

.changeset/eight-ligers-count.md, examples/lit/package.json, examples/lit/rsbuild.config.ts, examples/lit/src/index.css, examples/lit/src/index.html, examples/lit/src/index.js, examples/lit/src/my-element.js, packages/create-rsbuild/src/index.ts, packages/create-rsbuild/template-lit-js/package.json, packages/create-rsbuild/template-lit-js/rsbuild.config.mjs, packages/create-rsbuild/template-lit-js/src/index.css, packages/create-rsbuild/template-lit-js/src/index.html, packages/create-rsbuild/template-lit-js/src/index.js, packages/create-rsbuild/template-lit-js/src/my-element.js, packages/create-rsbuild/template-lit-ts/package.json, packages/create-rsbuild/template-lit-ts/rsbuild.config.ts, packages/create-rsbuild/template-lit-ts/src/env.d.ts, packages/create-rsbuild/template-lit-ts/src/index.css, packages/create-rsbuild/template-lit-ts/src/index.html, packages/create-rsbuild/template-lit-ts/src/index.ts, packages/create-rsbuild/template-lit-ts/src/my-element.ts, packages/create-rsbuild/template-lit-ts/tsconfig.json, packages/document/docs/en/guide/start/quick-start.mdx, packages/document/docs/zh/guide/start/quick-start.mdx, pnpm-lock.yaml
Add new lit template to `create-rsbuild`.
=> feat(create-rsbuild): add new lit template

packages/create-rsbuild/src/index.ts
=> chore: improve next steps message

packages/document/docs/en/guide/basic/typescript.md, packages/document/docs/zh/guide/basic/typescript.md
Add configuring tsconfig.json guide.
=> docs: add configuring tsconfig.json guide

packages/create-rsbuild/template-lit-js/package.json, pnpm-lock.yaml
=> fix: remove ts in lit js template

.changeset/stupid-kiwis-sin.md, packages/compat/uni-builder/tests/__snapshots__/globalVars.test.ts.snap, packages/core/package.json, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/plugins/__snapshots__/define.test.ts.snap, packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap, packages/core/tests/rspack-provider/plugins/__snapshots__/output.test.ts.snap, packages/core/tests/rspack-provider/plugins/minimize.test.ts, packages/doctor-core/package.json, packages/doctor-types/package.json, packages/plugin-node-polyfill/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/package.json, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-vue/tests/__snapshots__/index.test.ts.snap, packages/shared/package.json, pnpm-lock.yaml
Bump Rspack v0.3.12
https://github.com/web-infra-dev/rspack/releases/tag/v0.3.12
=> feat(deps): bump Rspack v0.3.12

packages/create-rsbuild/src/index.ts
=> fix: use correct field npm_config_user_agent

packages/document/docs/en/plugins/dev/index.md, packages/document/docs/zh/plugins/dev/index.md
Update plugin dev guide, some content are outdated.
=> docs: update plugin dev guide

packages/document/docs/en/shared/config/tools/rspack.md, packages/document/docs/zh/shared/config/tools/rspack.md
=> docs: add rspack util in tools.rspack

packages/document/docs/en/config/options/source.mdx, packages/document/docs/en/guide/start/quick-start.mdx, packages/document/docs/en/shared/config/source/entries.md, packages/document/docs/zh/config/options/source.mdx, packages/document/docs/zh/guide/start/quick-start.mdx, packages/document/docs/zh/shared/config/source/entries.md, packages/document/docs/zh/shared/nodeVersion.md
Add source.entries option to document.
=> docs: add source.entries option

packages/document/docs/en/guide/migration/_meta.json, packages/document/docs/en/guide/migration/cra.mdx, packages/document/docs/en/guide/migration/vue-cli.mdx, packages/document/docs/zh/guide/migration/_meta.json, packages/document/docs/zh/guide/migration/cra.mdx, packages/document/docs/zh/guide/migration/vue-cli.mdx
=> docs: add Vue CLI migration guide

packages/document/docs/en/guide/migration/cra.mdx, packages/document/docs/en/guide/migration/vue-cli.mdx, packages/document/docs/en/guide/start/quick-start.mdx, packages/document/docs/zh/guide/migration/cra.mdx, packages/document/docs/zh/guide/migration/vue-cli.mdx, packages/document/docs/zh/guide/start/quick-start.mdx
Add migration guide to quick start.
=> docs: add migration guide to quick start

.changeset/long-spoons-sing.md, packages/core/src/cli/commands.ts, packages/core/src/plugins/entry.ts, packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/zh/api/javascript-api/instance.mdx
Handle errors when CLI command failed.
=> feat: handle errors when CLI command failed

packages/document/docs/en/plugins/list/plugin-type-check.mdx, packages/document/docs/zh/plugins/list/plugin-type-check.mdx
=> docs: add 'Why are some errors reported as warnings?'

README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx
=> docs: update Rsbuild introduction

packages/document/docs/en/api/javascript-api/core.mdx, packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/en/api/javascript-api/types.mdx, packages/document/docs/en/config/options/_meta.json, packages/document/docs/en/config/options/dev.mdx, packages/document/docs/en/config/options/html.mdx, packages/document/docs/en/config/options/others.mdx, packages/document/docs/en/config/options/output.mdx, packages/document/docs/en/config/options/performance.mdx, packages/document/docs/en/config/options/plugins.mdx, packages/document/docs/en/config/options/source.mdx, packages/document/docs/en/config/options/tools.mdx, packages/document/docs/zh/api/javascript-api/core.mdx, packages/document/docs/zh/api/javascript-api/instance.mdx, packages/document/docs/zh/api/javascript-api/types.mdx, packages/document/docs/zh/config/options/_meta.json, packages/document/docs/zh/config/options/dev.mdx, packages/document/docs/zh/config/options/html.mdx, packages/document/docs/zh/config/options/others.mdx, packages/document/docs/zh/config/options/output.mdx, packages/document/docs/zh/config/options/performance.mdx, packages/document/docs/zh/config/options/plugins.mdx, packages/document/docs/zh/config/options/source.mdx, packages/document/docs/zh/config/options/tools.mdx
Improve config options structure.
=> docs: improve config options structure

packages/document/docs/en/guide/basic/_meta.json, packages/document/docs/en/guide/basic/tailwindcss.mdx, packages/document/docs/zh/guide/basic/_meta.json, packages/document/docs/zh/guide/basic/tailwindcss.mdx
Add using Tailwind CSS guide.
https://github.com/web-infra-dev/rsbuild/issues/77
=> docs: add using Tailwind CSS guide

.github/workflows/bench-pr.yaml
=> chore: add bench pr

packages/document/docs/en/guide/start/npm-packages.mdx, packages/document/docs/zh/guide/start/npm-packages.mdx, packages/shared/README.md, packages/shared/package.json
Mark `@rsbuild/shared` as an internal package.
=> docs: mark @rsbuild/shared as an internal package

.github/workflows/bench-pr.yaml
=> chore: use REPO_SCOPED_TOKEN

.changeset/tidy-steaks-wonder.md, packages/doctor-core/package.json
optimize the rsbuild/doctor-core's exports config
=> fix(rsbuild-doctor): optimize the rsbuild/doctor-core's exports config

packages/compat/webpack/tests/createCompiler.test.ts, packages/core/src/createRsbuild.ts, packages/core/src/index.ts, packages/test-helper/src/rsbuild.ts
Define the public methods of `@rsbuild/core` package.
=> chore(core): define the public methods

.changeset/old-rocks-doubt.md, packages/core/modern.config.ts, packages/core/src/cli/commands.ts, packages/core/src/env.d.ts
Using define to inject Rsbuild version.
=> perf(cli): using define to inject Rsbuild version

.changeset/late-shoes-drum.md, packages/core/bin/rsbuild.js, packages/core/modern.config.ts, packages/core/src/cli/commands.ts, packages/core/src/cli/config.ts, packages/core/src/cli/prepare.ts, packages/shared/package.json
Fix version display and improve perf.
=> fix(cli): fix version and improve perf

packages/document/docs/en/shared/config/source/entry.md, packages/document/docs/zh/shared/config/source/entry.md
Add explanation for source.entry.
=> docs: add explanation for source.entry

e2e/cases/svg/svg-external-react/static/index.html, e2e/cases/svg/svg.test.ts
Fix svg test occasionally failed.
=> test(e2e): fix svg test occasionally failed

packages/compat/uni-builder/src/webpack/webpackPlugins/ModuleScopePlugin.ts, packages/compat/webpack/src/plugins/css.ts, packages/compat/webpack/src/plugins/progress.ts, packages/core/src/rspack-provider/plugins/css.ts, packages/doctor-core/src/inner-plugins/utils/plugin.ts, packages/doctor-sdk/src/sdk/sdk/core.ts, packages/doctor-sdk/src/sdk/sdk/webpack.ts, packages/doctor-sdk/src/sdk/server/index.ts, packages/doctor-utils/src/common/data/index.ts, packages/doctor-webpack-plugin/src/multiple.ts, packages/doctor-webpack-plugin/src/plugins/resolver.ts, packages/plugin-babel/src/types.ts, packages/shared/src/apply/resolve.ts, packages/shared/src/config.ts, packages/shared/src/css.ts, packages/shared/src/types/config/source.ts, packages/shared/src/types/hooks.ts, packages/test-helper/src/index.ts, packages/test-helper/src/pathSerializer.ts, scripts/tsconfig/base.json
=> chore: enable TS no unused check

README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx
=> docs: improve README introduction

README.zh-CN.md, packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/en/guide/basic/configure-rspack.mdx, packages/document/docs/en/guide/basic/html-template.md, packages/document/docs/en/guide/basic/static-assets.md, packages/document/docs/en/guide/faq/exceptions.md, packages/document/docs/en/guide/optimization/split-chunk.md, packages/document/docs/en/plugins/list/plugin-babel.mdx, packages/document/docs/en/shared/config/performance/chunkSplit.md, packages/document/docs/en/shared/onAfterBuild.md, packages/document/docs/en/shared/onAfterCreateCompiler.md, packages/document/docs/en/shared/onBeforeBuild.md, packages/document/docs/en/shared/onBeforeCreateCompiler.md, packages/document/docs/zh/api/javascript-api/instance.mdx, packages/document/docs/zh/guide/basic/configure-rspack.mdx, packages/document/docs/zh/guide/basic/html-template.md, packages/document/docs/zh/guide/faq/exceptions.md, packages/document/docs/zh/guide/optimization/split-chunk.md, packages/document/docs/zh/guide/start/index.mdx, packages/document/docs/zh/plugins/list/plugin-babel.mdx, packages/document/docs/zh/shared/config/performance/chunkSplit.md, packages/document/docs/zh/shared/onAfterBuild.md, packages/document/docs/zh/shared/onAfterCreateCompiler.md, packages/document/docs/zh/shared/onBeforeBuild.md, packages/document/docs/zh/shared/onBeforeCreateCompiler.md
Update some outdated contents.
=> docs: update some outdated contents

packages/doctor-core/tests/common/module-graph/transform.spec.ts, packages/doctor-rspack-plugin/tests/plugin.test.ts, packages/doctor-webpack-plugin/tests/loaders/proxy.test.ts, packages/doctor-webpack-plugin/tests/loaders/query.test.ts, packages/doctor-webpack-plugin/tests/plugins/loader.test.ts, packages/doctor-webpack-plugin/tests/plugins/plugin.test.ts, packages/doctor-webpack-plugin/tests/plugins/rules.test.ts, packages/doctor-webpack-plugin/tests/summary.test.ts
fix: skip some slow test, then will migrate these
=> test(rsbuild-doctor): skip some slow test

packages/plugin-check-syntax/src/CheckSyntaxPlugin.ts, packages/plugin-css-minimizer/src/index.ts, packages/shared/src/apply/babel.ts, packages/shared/src/types/bundlerConfig.ts
Fix some type issue caused by BundlerChain.
=> types: fix some type issue caused by BundlerChain

README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx
Add performance graph.
The data is based on the benchmark built by the Farm team, more info in [performance-compare](https://github.com/rspack-contrib/performance-compare).
=> docs: add performance graph

packages/document/docs/en/shared/config/output/disableCssExtract.md, packages/document/docs/zh/shared/config/output/disableCssExtract.md
Only apply cssnano in production.
=> docs: only apply cssnano in production

packages/document/docs/en/plugins/dev/index.md, packages/document/docs/zh/plugins/dev/index.md
Update plugin naming convention.
=> docs: update plugin naming convention

packages/document/docs/zh/config/options/dev.mdx, packages/document/docs/zh/config/options/server.mdx
https://rsbuild.dev/zh/config/options/dev.html
Accessing this webpage now throws an error.
=> docs: fix dev config content

.changeset/moody-papayas-judge.md, packages/shared/src/logger.ts
Support uppercase debug flags.
=> feat: support uppercase debug flags

.changeset/fluffy-buses-report.md, packages/core/src/server/prodServer.ts, packages/document/docs/en/config/options/dev.mdx, packages/document/docs/en/config/options/server.mdx, packages/document/docs/en/shared/config/server/compress.md, packages/document/docs/zh/config/options/dev.mdx, packages/document/docs/zh/config/options/server.mdx, packages/document/docs/zh/shared/config/server/compress.md, packages/shared/src/config.ts, packages/shared/src/devServer.ts, packages/shared/src/types/config/dev.ts, packages/shared/src/types/config/server.ts, packages/shared/tests/devServer.test.ts
https://github.com/web-infra-dev/rsbuild/issues/609
=> refactor: rename `server.compress`  to support preview server

packages/document/docs/en/config/options/server.mdx, packages/document/docs/en/guide/basic/config.mdx, packages/document/docs/en/guide/start/features.mdx, packages/document/docs/en/shared/config/tools/rspack.md, packages/document/docs/en/shared/config/tools/webpackChain.md, packages/document/docs/zh/guide/basic/config.mdx, packages/document/docs/zh/guide/start/features.mdx, packages/document/docs/zh/shared/config/tools/rspack.md, packages/document/docs/zh/shared/config/tools/webpackChain.md, packages/shared/src/chain.ts
=> chore: update server and chainId related docs

.changeset/eleven-comics-taste.md, e2e/package.json, packages/core/package.json, packages/doctor-core/package.json, packages/doctor-rspack-plugin/package.json, packages/doctor-types/package.json, packages/plugin-react/package.json, packages/shared/package.json, packages/test-helper/package.json, pnpm-lock.yaml
Bump Rspack v0.4.0.
https://github.com/web-infra-dev/rspack/releases/tag/v0.4.0
=> feat(deps): bump Rspack v0.4.0

packages/document/docs/en/guide/faq/exceptions.md, packages/document/docs/en/guide/faq/features.md, packages/document/docs/en/plugins/dev/hooks.mdx, packages/document/docs/en/shared/bundlerChain.md, packages/document/docs/en/shared/config/tools/bundlerChain.mdx, packages/document/docs/zh/guide/faq/exceptions.md, packages/document/docs/zh/guide/faq/features.md, packages/document/docs/zh/shared/bundlerChain.md, packages/document/docs/zh/shared/config/tools/bundlerChain.mdx
=> docs: update webpack-related content

scripts/check-changeset/src/index.ts
Fix peer dependencies checker.
=> chore(workflow): fix peer dependencies checker

README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx, packages/document/rspress.config.ts
Update discord links, the previous link got invalid.
=> docs: update discord links

packages/document/docs/en/plugins/list/plugin-check-syntax.mdx, packages/document/docs/zh/plugins/list/plugin-check-syntax.mdx
=> chore: update tip of `plugin-check-syntax`

packages/compat/webpack/tests/config/normalize.test.ts, packages/compat/webpack/tests/core/initConfigs.test.ts, packages/core/tests/plugins/__snapshots__/html.test.ts.snap, packages/core/tests/plugins/__snapshots__/inlineChunk.test.ts.snap, packages/core/tests/plugins/html.test.ts, packages/core/tests/plugins/inlineChunk.test.ts
Add html and inlineChunk tests to core package, removed in:
- https://github.com/web-infra-dev/rsbuild/commit/523c0cb07194e6b674fa6e300ae68ebb5e1c5d84
- https://github.com/web-infra-dev/rsbuild/commit/8f889f9d8a04d77d4c8e8ba4ad6e7b4d6cdb8661
=> test(core): add html and inlineChunk tests

packages/document/docs/en/guide/basic/_meta.json, packages/document/docs/en/guide/basic/unocss.mdx, packages/document/docs/zh/guide/basic/_meta.json, packages/document/docs/zh/guide/basic/unocss.mdx
fx: https://github.com/web-infra-dev/rsbuild/issues/654
=> docs: add unocss usage

.changeset/gentle-llamas-shout.md, packages/compat/uni-builder/src/shared/parseCommonConfig.ts, packages/compat/uni-builder/src/types.ts, packages/compat/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap, packages/compat/uni-builder/tests/parseConfig.test.ts, packages/shared/src/types/config/server.ts
https://github.com/web-infra-dev/rsbuild/issues/444
=> fix: compat tools.devServer in uni-builder

.changeset/nervous-actors-rescue.md, package.json
- Prettier mdx files by default.
- Add changeset for https://github.com/web-infra-dev/rsbuild/pull/692
=> workflow: prettier mdx files by default

.github/workflows/issue-label.yml
=> chore(workflow): get issue from context.payload

.changeset/plenty-news-film.md, e2e/cases/cli/function-config/index.test.ts, e2e/cases/cli/function-config/rsbuild.config.ts, e2e/cases/cli/function-config/src/index.js, packages/core/src/cli/config.ts, packages/document/docs/en/guide/basic/config.mdx, packages/document/docs/zh/guide/basic/config.mdx
Support config file export function.
=> feat: support config file export function

packages/document/docs/en/guide/migration/vue-cli.mdx, packages/document/docs/zh/guide/migration/vue-cli.mdx
Add Vue CLI config migration guide.
=> docs: Vue CLI config migration guide

packages/document/rspress.config.ts
Enable cleanUrls option of Rspress
https://rspress.dev/api/config/config-basic.html#routecleanurls
=> docs: enable cleanUrls option of Rspress

packages/document/docs/en/guide/faq/general.md, packages/document/docs/zh/guide/faq/general.md
Explain the relationship between Rsbuild, Rspack and Modern.js.
=> docs: explain the relationship

.changeset/ten-drinks-float.md, packages/core/modern.config.ts, packages/plugin-assets-retry/src/AssetsRetryPlugin.ts, packages/plugin-assets-retry/src/env.d.ts, packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts, packages/plugin-rem/src/env.d.ts, packages/shared/src/plugins/index.ts, packages/shared/src/plugins/util.ts, scripts/modern.base.config.ts
Use define to inject version, remove the fs operation to build process.
=> perf(plugin-rem): use define to inject version

e2e/cases/preview/index.test.ts, e2e/scripts/shared.ts
Fix preview test occasionally failed.
Fix https://github.com/web-infra-dev/rsbuild/actions/runs/7001255972/job/19043086803
=> test(e2e): fix preview test occasionally failed

README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx
Update benchmark data, add webpack SWC.
https://github.com/rspack-contrib/performance-compare
=> docs: update benchmark data, add webpack SWC

.changeset/friendly-kangaroos-appear.md, packages/compat/uni-builder/package.json, packages/compat/uni-builder/src/shared/parseCommonConfig.ts, pnpm-lock.yaml
https://github.com/web-infra-dev/rsbuild/issues/6
=> feat: support react plugin in uni-builder

.changeset/quick-parrots-vanish.md, packages/compat/uni-builder/package.json, packages/compat/uni-builder/src/shared/parseCommonConfig.ts, packages/compat/uni-builder/src/types.ts, pnpm-lock.yaml
https://github.com/web-infra-dev/rsbuild/issues/207
=> feat: support svgr in uni-builder

.changeset/many-balloons-bow.md, packages/compat/uni-builder/package.json, packages/compat/uni-builder/src/shared/parseCommonConfig.ts, packages/compat/uni-builder/src/types.ts, pnpm-lock.yaml
support output.disableTsChecker and tools.tsChecker in uni-builder
=> feat(uni-builder): support ts-checker

.changeset/brave-parents-arrive.md, packages/compat/uni-builder/package.json, packages/compat/uni-builder/src/rspack/index.ts, packages/compat/uni-builder/src/types.ts, packages/plugin-css-minimizer/src/index.ts, pnpm-lock.yaml
apply css-minimizer-webpack-plugin in uni-builder
=> feat(uni-builder): apply css-minimizer-webpack-plugin

.changeset/two-doors-fail.md, packages/compat/uni-builder/package.json, packages/compat/uni-builder/src/shared/parseCommonConfig.ts, packages/compat/uni-builder/src/types.ts, pnpm-lock.yaml
support security.checkSyntax in uni-builder
=> feat(uni-builder): support checkSyntax

.changeset/rotten-geckos-smell.md, packages/compat/uni-builder/package.json, packages/compat/uni-builder/src/shared/parseCommonConfig.ts, packages/compat/uni-builder/src/types.ts, pnpm-lock.yaml
support tools.pug in uni-builder
=> feat(uni-builder): support tools.pug

.changeset/smooth-tools-decide.md, e2e/cases/css/css-modules/index.test.ts, e2e/cases/performance/performance.test.ts, e2e/cases/stylus-rem/index.test.ts, e2e/cases/stylus/index.test.ts, packages/core/package.json, packages/doctor-core/package.json, packages/doctor-rspack-plugin/package.json, packages/doctor-types/package.json, packages/plugin-react/package.json, packages/shared/package.json, packages/test-helper/package.json, pnpm-lock.yaml
https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/7014628924/job/19082632444
=> fix: rspack ecosystem-ci failed

.changeset/blue-boats-flash.md, e2e/cases/html/minify/index.test.ts, e2e/cases/inline-chunk/index.test.ts, packages/core/src/plugins/inlineChunk.ts, packages/document/docs/en/config/options/output.mdx, packages/document/docs/en/shared/config/output/inlineScripts.md, packages/document/docs/zh/config/options/output.mdx, packages/document/docs/zh/shared/config/output/inlineScripts.md
https://github.com/web-infra-dev/rspack/issues/4740
=> feat: support output.inlineScripts

.changeset/twelve-garlics-relate.md, packages/document/docs/en/plugins/list/plugin-react.mdx, packages/document/docs/zh/plugins/list/plugin-react.mdx, packages/plugin-react/src/index.ts, packages/plugin-react/src/splitChunks.ts, packages/plugin-react/tests/__snapshots__/features.test.ts.snap, packages/plugin-react/tests/features.test.ts
=> feat(plugin-react): allow to enable/disable chunk splitting

.github/workflows/test-ubuntu.yml, vitest.workspace.ts
Run ut in MacOS, as SWC cases will fail in Ubuntu CI
=> workflow: run SWC ut cases in CI

packages/plugin-react/src/index.ts, packages/plugin-react/src/splitChunks.ts
=> fix: use camel case for type

packages/document/docs/en/guide/advanced/_meta.json, packages/document/docs/en/guide/advanced/env-vars.md, packages/document/docs/zh/guide/advanced/_meta.json, packages/document/docs/zh/guide/advanced/env-vars.md
Add guide for .env files.
https://github.com/web-infra-dev/rsbuild/issues/47
=> docs: add guide for .env files

.changeset/fuzzy-shirts-smash.md, e2e/cases/cli/env/public/.env, e2e/cases/cli/env/public/index.test.ts, e2e/cases/cli/env/public/rsbuild.config.ts, e2e/cases/cli/env/public/src/index.js, packages/core/src/cli/commands.ts, packages/core/src/loadEnv.ts, packages/document/docs/en/guide/advanced/env-vars.md, packages/document/docs/zh/guide/advanced/env-vars.md
Auto inject public env vars to client.
close https://github.com/web-infra-dev/rsbuild/issues/47
=> feat: auto inject public env vars to client

.changeset/nervous-rats-provide.md, packages/compat/uni-builder/package.json, packages/compat/uni-builder/src/shared/parseCommonConfig.ts, packages/compat/uni-builder/src/types.ts, pnpm-lock.yaml
support experiments.sourceBuild in uni-builder
https://github.com/web-infra-dev/rsbuild/issues/23
=> feat(uni-builder): support experiments.sourceBuild

packages/document/docs/zh/guide/basic/config.mdx
=> docs: fix typo in config.mdx

packages/core/package.json, packages/core/src/rspack-provider/shared.ts, pnpm-lock.yaml
Remove semver from deps of `@rsbuild/core`.
=> perf(core): remove semver from deps

package.json, pnpm-lock.yaml, vitest.workspace.ts
Remove unused is-ci dependency from root package.json.
=> chore: remove unused is-ci dependency

packages/document/docs/en/guide/basic/_meta.json, packages/document/docs/en/guide/basic/page-route.md, packages/document/docs/en/shared/config/server/historyApiFallback.md, packages/document/docs/en/shared/config/server/htmlFallback.md, packages/document/docs/zh/guide/basic/_meta.json, packages/document/docs/zh/guide/basic/page-route.md, packages/document/docs/zh/shared/config/server/historyApiFallback.md, packages/document/docs/zh/shared/config/server/htmlFallback.md
=> docs: add page-route guide

packages/document/docs/en/guide/basic/cli.mdx, packages/document/docs/en/guide/basic/page-route.md, packages/document/docs/zh/guide/basic/cli.mdx
=> docs: add notice for preview server

e2e/cases/mjs-artifact/index.test.ts, e2e/cases/mjs-artifact/test.mjs, e2e/package.json, pnpm-lock.yaml
Check validity of mjs artifact.
https://github.com/web-infra-dev/rsbuild/pull/809
=> test(e2e): check validity of mjs artifact

packages/core/package.json
Add package.json to exports map of `@rsbuild/core`.
=> feat(core): add package.json to exports map

packages/document/docs/zh/guide/advanced/browserslist.md
https://github.com/web-infra-dev/rsbuild/blob/190b8c2c53694a24c3717ee88434fc5c5ae9f4cd/packages/shared/src/constants.ts#L16
=> docs: update web default browserslist

packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/zh/api/javascript-api/instance.mdx
Add missing logger imports to javascript-api part.
=> docs: add missing logger to javascript-api part

.changeset/soft-penguins-confess.md, packages/compat/uni-builder/src/rspack/index.ts, packages/compat/uni-builder/src/shared/parseCommonConfig.ts, packages/compat/uni-builder/src/types.ts, packages/compat/uni-builder/src/webpack/index.ts, packages/compat/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap, packages/compat/uni-builder/tests/parseConfig.test.ts
compat builder default browserslist and modern-web target
https://github.com/web-infra-dev/rsbuild/issues/794
=> feat(uni-builder): compat builder default browserslist

package.json, pnpm-lock.yaml
=> chore(deps): bump vitest to 1.0.1

.github/PULL_REQUEST_TEMPLATE.md
Simplify pull request template.
=> chore(workflow): simplify pull request template

packages/document/docs/en/config/server/proxy.mdx, packages/document/docs/zh/config/server/proxy.mdx
Add some example for `server.proxy`.
=> docs: add some example for server.proxy

packages/document/docs/en/plugins/list/plugin-assets-retry.mdx, packages/document/docs/zh/plugins/list/plugin-assets-retry.mdx
update document, delete usage limit description on dynamic import
#91
=> doc(assetsRetryPlugin): delete usage limit description on dynamic import

packages/document/docs/en/config/tools/html-plugin.mdx, packages/document/docs/zh/config/tools/html-plugin.mdx
Add example for custom HTML filename.
=> docs: add example for custom HTML filename

packages/core/src/cli/commands.ts, packages/core/src/cli/config.ts, packages/core/src/index.ts, packages/document/docs/en/api/javascript-api/core.mdx, packages/document/docs/zh/api/javascript-api/core.mdx
Expose the `loadConfig` method as a public JavaScript API.
=> feat(core): expose loadConfig method

examples/react/rsbuild.config.ts, packages/core/src/provider/core/createCompiler.ts
Avoid duplicated logs with multiple targets:
=> fix: avoid duplicated logs with multiple targets

packages/core/src/server/compiler-dev-middleware/index.ts, packages/core/src/server/compiler-dev-middleware/socketServer.ts, packages/core/src/server/devServer.ts, packages/shared/src/types/server.ts
=> chore(server): format dev-middleware options

packages/plugin-assets-retry/src/runtime/index.ts, packages/plugin-react/src/antd.ts, packages/plugin-react/src/arco.ts, packages/plugin-react/src/splitChunks.ts
Should get the new targets from context.
Fix the failed CI in: https://github.com/web-infra-dev/rsbuild/actions/runs/7138387223/job/19439867974?pr=888
=> fix(plugin-react): should get the new targets from context

packages/core/src/provider/core/initPlugins.ts, packages/document/docs/en/shared/getRsbuildConfig.md, packages/document/docs/zh/plugins/dev/index.md, packages/document/docs/zh/shared/getRsbuildConfig.md, packages/shared/src/types/plugin.ts
Support get original Rsbuild config via` getRsbuildConfig('original')`;
=> feat(core): support get original Rsbuild config

packages/document/docs/en/config/html/tags.mdx, packages/document/docs/en/config/source/alias.mdx, packages/document/docs/en/config/tools/bundler-chain.mdx, packages/document/docs/en/config/tools/css-loader.mdx, packages/document/docs/en/plugins/list/plugin-babel.mdx, packages/document/docs/en/shared/alias.md, packages/document/docs/zh/config/html/tags.mdx, packages/document/docs/zh/config/source/alias.mdx, packages/document/docs/zh/config/tools/bundler-chain.mdx, packages/document/docs/zh/config/tools/css-loader.mdx, packages/document/docs/zh/plugins/list/plugin-babel.mdx, packages/document/docs/zh/shared/alias.md
Prefer relative links and fix broken links in document.
=> docs: prefer relative links and fix broken links

e2e/cases/umd/rsbuild.config.ts, packages/document/docs/en/guide/start/npm-packages.mdx, packages/document/docs/en/plugins/list/_meta.json, packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-umd.mdx, packages/document/docs/zh/guide/start/npm-packages.mdx, packages/document/docs/zh/plugins/list/_meta.json, packages/document/docs/zh/plugins/list/index.md, packages/document/docs/zh/plugins/list/plugin-umd.mdx
Add guide for the UMD plugin.
close https://github.com/web-infra-dev/rsbuild/issues/70
=> docs: add guide for UMD plugin

packages/shared/compiled/line-diff/index.d.ts, packages/shared/compiled/line-diff/index.js, packages/shared/compiled/line-diff/license, packages/shared/compiled/line-diff/package.json, packages/shared/package.json, packages/shared/src/loaders/cssModulesTypescriptLoader.ts, pnpm-lock.yaml, scripts/prebundle/package.json, scripts/prebundle/src/constant.ts
Prebundle line-diff dependency.
=> perf(shared): prebundle line-diff dependency

packages/shared/src/types/stats.ts
=> types: export stats type from rspack

packages/shared/src/url.ts
Fix failed to resolve path/posix in some Node version.
=> fix: failed to resolve path/posix in some Node version

README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx
Update benchmark data to v0.2.0.
https://github.com/rspack-contrib/performance-compare
=> docs: update benchmark data to v0.2.0

e2e/cases/inspect-config/index.test.ts, e2e/scripts/shared.ts, packages/compat/webpack/tests/helper.ts, packages/core/src/createRsbuild.ts, packages/document/docs/en/api/javascript-api/core.mdx, packages/document/docs/zh/api/javascript-api/core.mdx, packages/shared/src/types/rsbuild.ts, packages/test-helper/src/rsbuild.ts
Simplify options of createRsbuild method.
=> types: simplify options of createRsbuild

packages/document/docs/en/config/performance/dns-prefetch.mdx, packages/document/docs/zh/config/performance/dns-prefetch.mdx
Add more guides and notes for DNF prefetch.
https://www.splunk.com/en_us/blog/learn/dns-prefetch.html
=> docs: add more guides for DNF prefetch

packages/document/docs/en/plugins/list/plugin-babel.mdx, packages/document/docs/zh/plugins/list/plugin-babel.mdx, packages/plugin-babel/src/types.ts
Add document of include and exclude options.
https://github.com/web-infra-dev/rsbuild/pull/833
=> docs(plugin-babel): add include and exclude options

e2e/cases/solid/index.test.ts, e2e/cases/vue/jsx-basic/rsbuild.config.ts, e2e/cases/vue/sfc-lang-jsx/rsbuild.config.ts, e2e/cases/vue/sfc-lang-tsx/rsbuild.config.ts, e2e/cases/vue2/jsx-basic/rsbuild.config.ts, e2e/cases/vue2/sfc-lang-jsx/rsbuild.config.ts, e2e/cases/vue2/sfc-lang-tsx/rsbuild.config.ts, packages/document/docs/en/plugins/list/plugin-solid.mdx, packages/document/docs/en/plugins/list/plugin-vue-jsx.mdx, packages/document/docs/en/plugins/list/plugin-vue2-jsx.mdx, packages/document/docs/zh/plugins/list/plugin-solid.mdx, packages/document/docs/zh/plugins/list/plugin-vue-jsx.mdx, packages/document/docs/zh/plugins/list/plugin-vue2-jsx.mdx
Match less files to improve babel perf, update the example code in `plugin-vue-jsx`, `plugin-vue2-jsx` and `plugin-solid`.
=> docs: match less files to improve babel perf

e2e/package.json, package.json, packages/test-helper/src/path.ts, packages/test-helper/src/rsbuild.ts, pnpm-lock.yaml
Reduce duplicated esbuild versions to make install faster.
=> chore(deps): reduce duplicated esbuild

packages/core/src/server/devMiddleware.ts, packages/core/src/server/devMiddlewares.ts, packages/core/src/server/httpServer.ts, packages/core/src/server/socketServer.ts
Improve some server code, perfer named exports instead of default exports.
=> chore: improve some server code

packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, packages/test-helper/package.json, pnpm-lock.yaml, scripts/update-packages/src/rspack.ts
https://github.com/web-infra-dev/rspack/compare/v0.4.2...v0.4.3
=> chore: bump rspack to 0.4.3

packages/babel-preset/package.json
=> chore(babel-preset): add typesVersions for compat moduleResolution node

packages/core/src/server/compilerDevMiddleware.ts, packages/core/src/server/devServer.ts, packages/core/src/server/getDevMiddlewares.ts, packages/shared/src/types/server.ts
=> chore(devServer): update filename and comment

e2e/cases/source-build/index.test.ts
=> test(e2e): fix type check error logs

packages/compat/plugin-esbuild/tests/index.test.ts, packages/compat/plugin-swc/tests/plugin.test.ts, packages/compat/uni-builder/tests/babel.test.ts, packages/compat/uni-builder/tests/fallback.test.ts, packages/compat/uni-builder/tests/lazyCompilation.test.ts, packages/compat/uni-builder/tests/manifest.test.ts, packages/compat/uni-builder/tests/moduleScopes.test.ts, packages/compat/uni-builder/tests/resolve.test.ts, packages/compat/uni-builder/tests/sri.test.ts, packages/compat/uni-builder/tests/tsLoader.test.ts, packages/compat/webpack/tests/core/initConfigs.test.ts, packages/compat/webpack/tests/helper.ts, packages/compat/webpack/tests/plugins/css.test.ts, packages/compat/webpack/tests/plugins/default.test.ts, packages/compat/webpack/tests/plugins/minimize.test.ts, packages/compat/webpack/tests/plugins/output.test.ts, packages/compat/webpack/tests/plugins/progress.test.ts, packages/compat/webpack/tests/plugins/resolve.test.ts, packages/compat/webpack/tests/webpackConfig.test.ts, packages/core/tests/plugins/target.test.ts, packages/core/tests/rspack-provider/plugins/resolve.test.ts, packages/plugin-assets-retry/tests/assetsRetry.test.ts, packages/plugin-rem/tests/index.test.ts, packages/test-helper/src/rsbuild.ts
Simplify test helpers, merge the similar methods in `compat/webpack/tests/helper.ts`.
=> test: simplify test helpers

packages/shared/src/types/thirdParty.ts
Extend PostcssOptions based on ProcessOptions of postcss.
=> types: extend ProcessOptions of postcss

README.md, README.zh-CN.md
- Update QoS dashboard link
- Add credits for Netlify
=> docs: update QoS dashboard link

e2e/cases/html-tags/index.test.ts, e2e/cases/html/inject/index.test.ts, e2e/cases/performance/file-size/printFileSize.test.ts, e2e/cases/wasm/index.test.ts, e2e/scripts/helper.ts, packages/test-helper/src/index.ts
Some cases are using posix path to match the output files, so we need to adjust some conditions.
=> test(e2e): fix some cases in Windows

e2e/cases/cli/inspect/index.test.ts
Validate the content of inspected files.
https://github.com/web-infra-dev/rsbuild/pull/967
=> test(e2e): validate the content of inspected files

packages/document/docs/en/config/output/clean-dist-path.mdx, packages/document/docs/zh/config/output/clean-dist-path.mdx
Add more example for cleanDistPath.
https://github.com/web-infra-dev/rsbuild/issues/978
=> docs: add more example for cleanDistPath

packages/create-rsbuild/src/index.ts
=> feat(create-rsbuild): set the name of package.json

packages/core/src/provider/core/createCompiler.ts
Only print Rspack version in debug mode.
=> chore: only print Rspack version in debug mode

packages/core/src/cli/prepare.ts, packages/shared/src/logger.ts
Should setup logger level if use the JavaScript API.
=> fix: setup logger level if use JavaScript API

packages/document/docs/en/config/tools/bundler-chain.mdx, packages/document/docs/en/config/tools/rspack.mdx, packages/document/docs/zh/config/tools/bundler-chain.mdx, packages/document/docs/zh/config/tools/rspack.mdx
Fix missing `service-worker` type.
=> docs: update target type

packages/document/docs/en/guide/basic/css-usage.md, packages/document/docs/zh/guide/basic/css-usage.md
Update PostCSS configure guide, add `postcss.config.*` intro.
=> docs: update PostCSS configure guide

packages/compat/plugin-esbuild/compiled/esbuild-loader/minify-plugin.d.ts, packages/compat/webpack/package.json, packages/compat/webpack/src/core/webpackConfig.ts, packages/core/src/plugins/cache.ts, packages/core/src/provider/core/rspackConfig.ts, packages/core/src/provider/plugins/css.ts, packages/plugin-check-syntax/src/CheckSyntaxPlugin.ts, packages/plugin-css-minimizer/src/index.ts, packages/shared/compiled/webpack-chain/types/index.d.ts, packages/shared/src/chain.ts, pnpm-lock.yaml
Using the webpack type in `﻿webpack-chain` is not an optimal choice for bundlers based on rspack.
=> fix: use rspack config chain

packages/document/docs/en/guide/faq/hmr.md, packages/document/docs/zh/guide/faq/hmr.md
=> docs(hmr): external react users can use devtools to achieve hmr

packages/document/docs/en/guide/faq/hmr.md, packages/document/docs/zh/guide/faq/hmr.md
add missing content and update link
=> docs(hmr): add missing content and update link

packages/core/src/provider/plugins/less.ts, packages/core/tests/rspack-provider/plugins/__snapshots__/css.test.ts.snap
=> fix(plugin-less): remove duplicate calls

packages/compat/plugin-swc/src/plugin.ts, packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
Should apply script condition correctly when using the SWC plugin.
=> fix(plugin-swc): should apply script condition

.changeset/odd-snakes-design.md, packages/compat/plugin-swc/package.json, pnpm-lock.yaml
=> chore(plugin-swc): bump @modern-js/swc-plugins v0.6.6

package.json, pnpm-lock.yaml
Bump nx v17.2.
Nx 17.2 Update:
https://blog.nrwl.io/nx-17-2-update-b8f23ec42cbb#4273
=> chore(deps): bump nx v17.2

packages/document/docs/en/config/dev/client.mdx, packages/document/docs/zh/config/dev/client.mdx
Improve dev.client document, make it clearer.
=> docs: improve dev.client document

packages/compat/webpack/package.json, packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap, packages/core/package.json, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/plugins/__snapshots__/html.test.ts.snap, packages/core/tests/plugins/__snapshots__/inlineChunk.test.ts.snap, packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap, packages/plugin-assets-retry/package.json, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-rem/package.json, packages/shared/package.json, pnpm-lock.yaml
Bump html-rspack-plugin v5.6.0.
https://github.com/rspack-contrib/html-rspack-plugin/pull/3
=> chore(deps): bump html-rspack-plugin v5.6.0

packages/document/docs/en/config/html/tags.mdx, packages/document/docs/en/config/source/exclude.mdx, packages/document/docs/en/config/source/include.mdx, packages/document/docs/zh/config/html/tags.mdx, packages/document/docs/zh/config/source/exclude.mdx, packages/document/docs/zh/config/source/include.mdx, packages/shared/src/types/config/source.ts
`source.include` and `source.exclude` supports RuleSetCondition.
https://github.com/web-infra-dev/rsbuild/discussions/915
=> types: source.include supports RuleSetCondition

examples/react/rsbuild.config.ts, packages/document/docs/en/config/source/include.mdx, packages/document/docs/zh/config/source/include.mdx
Update notes in source.include document.
https://github.com/web-infra-dev/rsbuild/discussions/915
=> docs: update notes in source.include document

packages/document/docs/en/config/source/include.mdx, packages/document/docs/en/guide/migration/cra.mdx, packages/document/docs/zh/config/source/include.mdx, packages/document/docs/zh/guide/migration/cra.mdx
Add compile node_modules note for CRA migration.
https://github.com/web-infra-dev/rsbuild/discussions/915
=> docs: add compile node_modules note for CRA

packages/document/docs/en/config/dev/client.mdx, packages/document/docs/zh/config/dev/client.mdx
Add description for hot-update files.
=> docs: add description for hot-update file

packages/document/docs/en/guide/migration/cra.mdx, packages/document/docs/zh/guide/migration/cra.mdx
Add CRA config migration table.
close https://github.com/web-infra-dev/rsbuild/issues/754
=> docs: add CRA config migration table

packages/shared/src/types/rsbuild.ts
=> fix: RsbuildInstance generics type error

packages/document/docs/en/config/output/source-map.mdx, packages/document/docs/zh/config/output/source-map.mdx
Fix sourceMap config example in the plugin-check-syntax document.
https://github.com/web-infra-dev/rsbuild/issues/1058
=> docs(check-syntax): fix sourceMap config example

.changeset/witty-cheetahs-study.md, packages/plugin-vue/src/index.ts, packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
Add feature flag for Vue v3.4.
https://github.com/vuejs/core/pull/9550
=> feat(plugin-vue): add feature flag for Vue v3.4

packages/document/docs/en/plugins/list/plugin-check-syntax.mdx, packages/document/docs/zh/plugins/list/plugin-check-syntax.mdx
=> docs(check-syntax): fix incorrect line feed

README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx, packages/document/rspress.config.ts
Fix discord invitation invalid.
=> docs: fix discord invitation invalid

packages/document/docs/en/config/dev/hmr.mdx, packages/document/docs/en/config/dev/live-reload.mdx, packages/document/docs/en/guide/advanced/hmr.md, packages/document/docs/zh/config/dev/hmr.mdx, packages/document/docs/zh/config/dev/live-reload.mdx, packages/document/docs/zh/guide/advanced/hmr.md
Add document for dev.liveReload config.
close https://github.com/web-infra-dev/rsbuild/issues/1031
=> docs: add document for dev.liveReload config

.changeset/purple-dragons-rule.md, packages/core/src/client/hmr/createSocketUrl.ts
https://github.com/web-infra-dev/modern.js/pull/5148
=> fix: make hmr-client isomorphic

packages/core/src/client/hmr/index.ts
Reverts web-infra-dev/rsbuild#1075
=> Revert "fix: reload when the updated modules is empty"

packages/document/docs/en/guide/framework/solid.mdx, packages/document/docs/en/guide/framework/svelte.mdx, packages/document/docs/en/plugins/list/plugin-solid.mdx, packages/document/docs/zh/guide/framework/solid.mdx, packages/document/docs/zh/guide/framework/svelte.mdx, packages/document/docs/zh/plugins/list/plugin-solid.mdx
Improve Svelte and Solid guide.
=> docs: improve Svelte and Solid guide

packages/plugin-stylus/src/index.ts, packages/plugin-stylus/tests/rspack.test.ts, packages/shared/src/constants.ts
Move STYLUS_REGEX constant to stylus plugin, and reduce any typing.
=> chore(plugin-stylus): move constant and reduce any

packages/compat/plugin-esbuild/package.json
=> fix(plugin-esbuild): compiled folder should be published

packages/document/docs/en/guide/basic/config.mdx, packages/document/docs/zh/guide/basic/config.mdx
Recommend using mjs config file, and add intro of jiti.
=> docs: recommend using mjs config file

e2e/cases/cli/inspect/index.test.ts, e2e/cases/inspect-config/index.test.ts, packages/document/docs/en/guide/basic/cli.mdx, packages/document/docs/en/guide/basic/config.mdx, packages/document/docs/en/guide/debug/debug-mode.md, packages/document/docs/en/guide/faq/features.md, packages/document/docs/en/plugins/list/plugin-babel.mdx, packages/document/docs/zh/guide/basic/cli.mdx, packages/document/docs/zh/guide/basic/config.mdx, packages/document/docs/zh/guide/debug/debug-mode.md, packages/document/docs/zh/guide/faq/features.md, packages/document/docs/zh/plugins/list/plugin-babel.mdx, packages/shared/src/config.ts
Output mjs files when inspecting configs.
=> feat: output mjs files when inspecting configs

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress to v1.9.0

packages/document/docs/en/guide/advanced/env-vars.md, packages/document/docs/zh/guide/advanced/env-vars.md
Add guide for custom env prefix.
=> docs: add guide for custom env prefix

packages/document/docs/en/plugins/list/plugin-source-build.mdx, packages/document/docs/zh/plugins/list/plugin-source-build.mdx, packages/plugin-source-build/src/index.ts
Document the sourceField option of `plugin-source-build`.
The other two options are not stable yet, maybe we will re-design them.
=> docs(plugin-source-build): document sourceField

packages/document/docs/en/guide/basic/static-assets.md, packages/document/docs/zh/guide/basic/static-assets.md
Add guide for custom asset rules.
=> docs: add guide for custom asset rules

packages/document/docs/en/config/performance/preconnect.mdx, packages/document/docs/zh/config/performance/preconnect.mdx
Fix example URL.
https://github.com/web-infra-dev/rspress/issues/499
=> docs: fix example URL

cspell.json, packages/document/docs/en/plugins/list/plugin-svgr.mdx, packages/document/docs/zh/plugins/list/plugin-svgr.mdx, packages/plugin-svgr/src/index.ts, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap, packages/plugin-svgr/tests/index.test.ts
Support configure SVGR options.
=> feat(plugin-svgr): support configure SVGR options

packages/document/docs/en/guide/migration/cra.mdx
Fix missing content in CRA migration guide.
=> docs: fix missing content in CRA migration guide

e2e/cases/check-syntax/index.test.ts, e2e/cases/exports-presence/index.test.ts, e2e/cases/server/print-urls/index.test.ts, e2e/cases/source/source-exclude/index.test.ts, e2e/cases/source/source-include/index.test.ts, e2e/cases/type-checker/index.test.ts, e2e/scripts/helper.ts, packages/plugin-check-syntax/src/helpers/printErrors.ts, packages/test-helper/src/index.ts
Verify error logs when running the e2e cases.
=> test(e2e): verify error logs

packages/document/docs/en/config/server/print-urls.mdx, packages/document/docs/zh/config/server/print-urls.mdx
Add document for server.printUrls.
https://github.com/web-infra-dev/rsbuild/pull/1125
=> docs: add document for server.printUrls

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress to v1.9.1

packages/core/src/server/middlewares.ts
Improve error message of invalid URLs.
before:
after:
=> feat: improve error message of invalid URLs

packages/document/docs/en/config/html/template-parameters.mdx, packages/document/docs/en/guide/basic/html-template.md, packages/document/docs/en/guide/migration/cra.mdx, packages/document/docs/en/guide/migration/vue-cli.mdx, packages/document/docs/zh/config/html/template-parameters.mdx, packages/document/docs/zh/guide/basic/html-template.md, packages/document/docs/zh/guide/migration/cra.mdx, packages/document/docs/zh/guide/migration/vue-cli.mdx
=> docs: add template migration guide

packages/document/docs/en/config/tools/rspack.mdx, packages/document/docs/zh/config/tools/rspack.mdx
=> docs: add tip for mergeConfig util

packages/document/docs/en/guide/migration/cra.mdx, packages/document/docs/zh/guide/migration/cra.mdx
Add polyfill guide for CRA projects.
=> docs: add polyfill guide for CRA projects

packages/document/package.json, pnpm-lock.yaml
Fix the sidebar disappear problem when `route.cleanUrls` is true
https://github.com/web-infra-dev/rspress/issues/343
=> fix: doc sidebar disappeared

packages/document/docs/en/guide/migration/cra.mdx, packages/document/docs/zh/guide/migration/cra.mdx
Add migration guide for CRACO configurations.
https://x.com/nimgrg/status/1742081299550978049?s=20
=> docs: add migration guide for CRACO configurations

e2e/cases/server/ipv6-host/index.test.ts, e2e/cases/server/ipv6-host/rsbuild.config.ts, e2e/cases/server/ipv6-host/src/index.js, packages/shared/src/url.ts
Support listening on ipv6 address.
=> feat(server): support listening on ipv6 address

packages/document/rspress.config.ts
=> docs: update footer time 2023 to 2024

packages/shared/src/pluginStore.ts
Registering Webpack or Rspack plugins in `RsbuildConfig.plugins` is a common issue. Rsbuild can provide better error prompts to guide users to use `tools.rspack` instead.
=> feat: validate plugin object, provide better hint

.changeset/large-scissors-rule.md, e2e/cases/cli/falsy-plugins/index.test.ts, e2e/cases/cli/falsy-plugins/rsbuild.config.ts, e2e/cases/cli/falsy-plugins/src/index.ts, e2e/cases/cli/falsy-plugins/tsconfig.json, packages/core/src/index.ts, packages/core/src/types.ts, packages/shared/src/mergeChainedOptions.ts, packages/shared/src/pluginStore.ts, packages/shared/src/types/config/index.ts, packages/shared/src/types/plugin.ts, packages/shared/src/types/utils.ts
- Enable to pass falsy values as plugins.
- Warning when got webpack-like plugin object.
=> feat: allow passing falsy plugins

packages/shared/src/pluginStore.ts
Revert plugin validation implementation.
- https://github.com/web-infra-dev/rsbuild/pull/1155
- https://github.com/web-infra-dev/rsbuild/pull/1156
- https://github.com/web-infra-dev/rsbuild/pull/1157
=> chore: revert plugin validation implementation

packages/document/docs/en/api/javascript-api/types.mdx, packages/document/docs/zh/api/javascript-api/types.mdx
Document more public types. There are still some undocumented types, as I'm not yet sure whether users should use them.
=> docs: document more public types

packages/core/src/cli/config.ts, packages/document/docs/en/guide/basic/config.mdx, packages/document/docs/zh/guide/basic/config.mdx
Validate config function return value, this check can remind users when they forget to return a value.
=> feat: validate config function return value

package.json, pnpm-lock.yaml
=> chore(deps): bump Modern.js v2.45.0

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress v1.9.3

packages/document/docs/en/guide/migration/webpack.mdx, packages/document/docs/zh/guide/migration/webpack.mdx
=> docs: fix webpack build typo

packages/document/docs/en/guide/migration/cra.mdx, packages/document/docs/en/guide/migration/vue-cli.mdx, packages/document/docs/en/guide/migration/webpack.mdx, packages/document/docs/zh/guide/migration/cra.mdx, packages/document/docs/zh/guide/migration/vue-cli.mdx, packages/document/docs/zh/guide/migration/webpack.mdx
Add tip for migrating CRACO and ejected projects.
=> docs: add tip for migrating CRACO and ejected projects

packages/core/src/index.ts, packages/core/tests/index.test.ts, packages/document/docs/en/api/javascript-api/core.mdx, packages/document/docs/zh/api/javascript-api/core.mdx
Export the version of `@rsbuild/core` currently in use, it can be used by upper-level solutions.
=> feat(core): export Rsbuild version

packages/plugin-babel/src/plugin.ts
`getDefaultBabelOptions` is used to compare babel configuration.
In the modern.js scenario, we need to check whether the default configuration has changed. If the configuration has not changed, babel-loader will not be used.
=> chore(babel-plugin): export getDefaultBabelOptions util

packages/compat/webpack/src/plugins/sass.ts, packages/core/src/provider/plugins/sass.ts, packages/document/docs/en/config/tools/bundler-chain.mdx, packages/document/docs/zh/config/tools/bundler-chain.mdx, packages/shared/src/chain.ts
Add more CHAIN_ID to the bundler-chain document.
=> docs: add more CHAIN_ID to bundler-chain document

packages/document/docs/en/guide/start/glossary.mdx, packages/document/docs/zh/guide/start/glossary.mdx
=> docs: fix Module Federation terminology explanation

packages/document/docs/en/guide/migration/cra.mdx, packages/document/docs/zh/guide/migration/cra.mdx
Add CRA output directory guide.
=> docs: add CRA output directory guide

packages/document/docs/en/guide/migration/cra.mdx, packages/document/docs/zh/guide/migration/cra.mdx
Add unknown assets guide for CRA.
=> docs: add unknown assets guide for CRA

packages/document/docs/en/plugins/list/plugin-svelte.mdx, packages/document/docs/zh/plugins/list/plugin-svelte.mdx
=> docs: add guides for the svelte process options

packages/core/src/loadEnv.ts, packages/document/docs/en/api/javascript-api/core.mdx, packages/document/docs/zh/api/javascript-api/core.mdx
Add cleanup to loadEnv document, see: https://github.com/web-infra-dev/rsbuild/pull/1173
=> docs: add cleanup to loadEnv document

e2e/cases/react/legacy-jsx/rsbuild.config.ts, packages/document/docs/en/plugins/list/plugin-react.mdx, packages/document/docs/zh/plugins/list/plugin-react.mdx, packages/plugin-react/src/index.ts, packages/plugin-react/src/react.ts, packages/plugin-react/tests/index.test.ts, packages/shared/src/types/rspack.ts
Allow to configure all SWC react options. This is more flexible for users
https://swc.rs/docs/configuration/compilation#jsctransformreact
=> feat(plugin-react): allow to configure all SWC react options

packages/document/docs/en/guide/migration/_meta.json, packages/document/docs/en/guide/migration/modern-builder.mdx, packages/document/docs/en/guide/start/quick-start.mdx, packages/document/docs/zh/guide/migration/_meta.json, packages/document/docs/zh/guide/migration/modern-builder.mdx, packages/document/docs/zh/guide/start/quick-start.mdx
Add migration guide for Modern.js Builder.
https://github.com/web-infra-dev/modern.js
=> docs: add migration guide for Modern.js Builder

packages/core/src/cli/commands.ts, packages/document/docs/en/guide/basic/cli.mdx, packages/document/docs/zh/guide/basic/cli.mdx
Add -o alias for --open option:
```bash
rsbuild dev -o
```
=> feat(CLI): add -o alias for --open option

packages/document/docs/en/guide/basic/config.mdx, packages/document/docs/zh/guide/basic/config.mdx
Add guide for specify config file.
=> docs: add guide for specify config file

.vscode/extensions.json, CONTRIBUTING.md
Add guide for Biome VS Code extension.
https://biomejs.dev/reference/vscode/
=> chore(workflow): add guide for Biome VS Code extension

packages/document/docs/en/guide/basic/json-files.md, packages/document/docs/en/guide/start/npm-packages.mdx, packages/document/docs/en/plugins/list/_meta.json, packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-toml.mdx, packages/document/docs/zh/guide/basic/json-files.md, packages/document/docs/zh/guide/start/npm-packages.mdx, packages/document/docs/zh/plugins/list/_meta.json, packages/document/docs/zh/plugins/list/index.md, packages/document/docs/zh/plugins/list/plugin-toml.mdx
=> docs: add TOML plugin document

packages/document/docs/en/guide/basic/json-files.md, packages/document/docs/en/guide/start/npm-packages.mdx, packages/document/docs/en/plugins/list/_meta.json, packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-yaml.mdx, packages/document/docs/zh/guide/basic/json-files.md, packages/document/docs/zh/guide/start/npm-packages.mdx, packages/document/docs/zh/plugins/list/_meta.json, packages/document/docs/zh/plugins/list/index.md, packages/document/docs/zh/plugins/list/plugin-yaml.mdx
=> docs: add YAML plugin document

e2e/cases/solid/hmr/rsbuild.config.ts, e2e/cases/solid/index.test.ts, e2e/cases/vue/jsx-basic/rsbuild.config.ts, e2e/cases/vue/sfc-lang-jsx/rsbuild.config.ts, e2e/cases/vue/sfc-lang-tsx/rsbuild.config.ts, e2e/cases/vue2/jsx-basic/rsbuild.config.ts, e2e/cases/vue2/sfc-lang-jsx/rsbuild.config.ts, e2e/cases/vue2/sfc-lang-tsx/rsbuild.config.ts, packages/document/docs/en/config/source/include.mdx, packages/document/docs/en/guide/framework/solid.mdx, packages/document/docs/en/plugins/dev/index.md, packages/document/docs/en/plugins/list/plugin-image-compress.mdx, packages/document/docs/en/plugins/list/plugin-solid.mdx, packages/document/docs/en/plugins/list/plugin-vue-jsx.mdx, packages/document/docs/en/plugins/list/plugin-vue2-jsx.mdx, packages/document/docs/zh/config/source/include.mdx, packages/document/docs/zh/guide/framework/solid.mdx, packages/document/docs/zh/plugins/dev/index.md, packages/document/docs/zh/plugins/list/plugin-image-compress.mdx, packages/document/docs/zh/plugins/list/plugin-solid.mdx, packages/document/docs/zh/plugins/list/plugin-vue-jsx.mdx, packages/document/docs/zh/plugins/list/plugin-vue2-jsx.mdx, packages/plugin-image-compress/src/shared/codecs.ts, packages/plugin-image-compress/tests/__snapshots__/index.test.ts.snap, packages/plugin-image-compress/tests/index.test.ts
Update RegExp in document and tests, to be consistent with:
- https://github.com/web-infra-dev/rsbuild/pull/1215
- https://github.com/web-infra-dev/rsbuild/pull/1091
=> chore: update RegExp in document and tests

packages/shared/src/types/config/server.ts
Improve rewriteTo type for historyApiFallback.
https://www.npmjs.com/package/@types/connect-history-api-fallback?activeTab=code
https://github.com/bripkens/connect-history-api-fallback?tab=readme-ov-file#rewrites
=> types: improve rewriteTo type for historyApiFallback

cspell.json, examples/preact/package.json, examples/preact/rsbuild.config.ts, examples/preact/src/App.css, examples/preact/src/App.jsx, examples/preact/src/index.jsx, packages/plugin-preact/CHANGELOG.md, packages/plugin-preact/LICENSE, packages/plugin-preact/README.md, packages/plugin-preact/modern.config.ts, packages/plugin-preact/package.json, packages/plugin-preact/src/index.ts, packages/plugin-preact/tsconfig.json, packages/shared/src/chain.ts, pnpm-lock.yaml
Add @rsbuild/plugin-react package.
Note that the fast refresh has not been implemented, as [Prefresh](https://github.com/preactjs/prefresh) now depend on babel.
https://github.com/preactjs/preact
=> feat: add @rsbuild/plugin-react package

e2e/cases/preact/basic/index.test.ts, e2e/cases/preact/basic/rsbuild.config.ts, e2e/cases/preact/basic/src/App.jsx, e2e/cases/preact/basic/src/index.js, e2e/cases/react/basic/index.test.ts, e2e/cases/react/basic/rsbuild.config.ts, e2e/cases/react/basic/src/App.jsx, e2e/cases/react/basic/src/index.js, e2e/cases/solid/basic/src/App.jsx, e2e/package.json, pnpm-lock.yaml
Add some basic cases for Preact / React.
=>  test(e2e): add basic cases for Preact / React

packages/document/docs/en/plugins/list/_meta.json, packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-preact.mdx, packages/document/docs/en/plugins/list/plugin-react.mdx, packages/document/docs/zh/plugins/list/_meta.json, packages/document/docs/zh/plugins/list/index.md, packages/document/docs/zh/plugins/list/plugin-preact.mdx, packages/document/docs/zh/plugins/list/plugin-react.mdx
Setup document for plugin-preact.
https://github.com/web-infra-dev/rsbuild/pull/1249
=> docs: setup document for plugin-preact

.github/workflows/release.yml
Related PR: https://github.com/web-infra-dev/modern.js/pull/5221
=> chore: auto trigger modern.js update rsbuild when rsbuild release

packages/monorepo-utils/src/common/pnpm.ts
The `makeFileFinder` function has called glob multiple times. It causes performance overload and make negative patterns not work. We just need to call glob once and pass all patterns.
before:
after:
=> perf(source-build): improve glob performance

.github/workflows/release.yml
=> chore(workflow): fix release workflow action

.github/workflows/release.yml
https://github.com/web-infra-dev/rsbuild/actions/runs/7537608600/job/20516782596
=> chore(workflow): fix trigger modern update failed when releasing

packages/document/docs/en/config/server/public-dir.mdx, packages/document/docs/en/config/source/tsconfig-path.mdx, packages/document/docs/en/guide/basic/typescript.md, packages/document/docs/zh/config/source/tsconfig-path.mdx, packages/document/docs/zh/guide/basic/typescript.md
Add document for source.tsconfigPath config.
https://github.com/web-infra-dev/rsbuild/pull/1293
=> docs: add document for source.tsconfigPath config

packages/document/docs/en/guide/faq/exceptions.md, packages/document/docs/zh/guide/faq/exceptions.md
=> docs: prettier exceptions faq

package.json, packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml, scripts/test-helper/package.json
https://github.com/web-infra-dev/rspack/releases/tag/v0.5.1
=> feat(deps): bump rspack v0.5.1

packages/document/docs/en/guide/advanced/browserslist.md, packages/document/docs/zh/guide/advanced/browserslist.md
Add guide for browserslist env section.
https://github.com/web-infra-dev/rsbuild/pull/1303
=> docs: add guide for browserslist env section

packages/document/docs/en/plugins/list/plugin-type-check.mdx
fix broken https://rsbuild.dev/plugins/list/plugin-type-check
feedback from discord.
=> docs(plugin-type-check): fix broken en page

packages/document/docs/en/plugins/list/plugin-css-minimizer.mdx, packages/document/docs/en/plugins/list/plugin-toml.mdx, packages/document/docs/en/plugins/list/plugin-type-check.mdx, packages/document/docs/en/plugins/list/plugin-yaml.mdx
Fix translator removed tabs.
https://github.com/web-infra-dev/rsbuild/pull/1310
=> docs: fix translator removed tabs

CONTRIBUTING.md
fix steps in the contribution doc
=> docs: amend e2e command description

.github/renovate.json5
Configure manually updated packages:
- core-js: needs to be consistent with the Rspack SWC version
- typescript: may introduce type issue
- esbuild: may introduce breaking change
close https://github.com/web-infra-dev/rsbuild/pull/1325
=> chore(workflow): configure manually updated packages

package.json, pnpm-lock.yaml
=> chore(deps): bump Modern.js to v2.46.0

packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/en/plugins/dev/hooks.mdx, packages/document/docs/en/shared/onAfterStartDevServer.md, packages/document/docs/en/shared/onAfterStartProdServer.md, packages/document/docs/zh/api/javascript-api/instance.mdx, packages/document/docs/zh/plugins/dev/hooks.mdx, packages/document/docs/zh/shared/onAfterStartDevServer.md, packages/document/docs/zh/shared/onAfterStartProdServer.md
Add routes param to server hooks document.
=> docs: add routes param to server hooks document

package.json, pnpm-lock.yaml
=> chore(deps): bump Modern.js version to 2.46.1

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress version to 1.10.1

.changeset/lemon-cups-accept.md, packages/shared/src/logger.ts
Support debug groups:
```bash
DEBUG=rsbuild,others npx rsbuild build
```
=> feat: support debug groups

packages/document/docs/en/plugins/list/plugin-pug.mdx, packages/document/docs/en/plugins/list/plugin-solid.mdx, packages/document/docs/en/plugins/list/plugin-type-check.mdx, packages/document/docs/zh/plugins/list/plugin-pug.mdx, packages/document/docs/zh/plugins/list/plugin-solid.mdx, packages/plugin-assets-retry/src/types.ts, packages/plugin-babel/src/types.ts, packages/plugin-css-minimizer/src/index.ts, packages/plugin-pug/src/index.ts, packages/plugin-rem/src/types.ts, packages/plugin-solid/src/index.ts, packages/plugin-svelte/src/index.ts, packages/plugin-svgr/src/index.ts, packages/plugin-type-check/src/index.ts, packages/plugin-umd/src/index.ts, packages/plugin-vue-jsx/src/index.ts, packages/plugin-vue/src/index.ts, packages/plugin-vue2-jsx/src/index.ts, packages/plugin-vue2/src/index.ts
Add JSDoc for all plugins options.
close https://github.com/web-infra-dev/rsbuild/issues/181
=> feat: add JSDoc for all plugins options

e2e/cases/performance/split-by-module/index.test.ts, packages/core/src/plugins/splitChunks.ts, packages/core/tests/plugins/splitChunks.test.ts
Improve regex pattern for package name matching, resolving incorrect matching with pnpm.
=> fix: improve regex for package name matching

examples/node/package.json, examples/node/rsbuild.config.ts, examples/node/src/index.ts, examples/node/tsconfig.json, pnpm-lock.yaml
Add example for node target.
https://github.com/web-infra-dev/rsbuild/discussions/1384
=> chore: add example for node target

packages/document/docs/en/guide/advanced/env-vars.md, packages/document/docs/zh/guide/advanced/env-vars.md
Add document for env vars replacement scope.
=> docs: add env vars replacement scope

packages/core/src/cli/config.ts
Validate config exports to improve error message:
=> feat: validate config exports to improve error message

cspell.json, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/asset.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/types.d.ts, packages/document/docs/en/guide/basic/static-assets.md, packages/document/docs/zh/guide/basic/static-assets.md, packages/plugin-image-compress/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/shared/src/constants.ts
Support more image and media formats.
=> feat: support more image and media formats

packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/asset.ts, packages/core/src/rspack/preload/helpers/determineAsValue.ts, packages/core/tests/__snapshots__/asset.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/document/docs/en/guide/basic/static-assets.md, packages/document/docs/zh/guide/basic/static-assets.md, packages/plugin-image-compress/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/shared/src/constants.ts
Align asset constants type in preload plugin.
=> chore: align asset constants type in preload plugin

.changeset/rude-kangaroos-appear.md, packages/core/src/provider/htmlPluginUtil.ts
Lazy load html-webpack-plugin, 10ms faster startup for some scenarios.
=> perf: lazy load html-webpack-plugin

packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml, scripts/test-helper/package.json
=> feat(deps): bump rspack 0.5.2

packages/core/src/server/middlewares.ts
=> perf: reduce color calls of debug

packages/compat/webpack/src/core/webpackConfig.ts, packages/core/src/plugins/inlineChunk.ts, packages/core/src/provider/core/rspackConfig.ts, packages/core/src/provider/index.ts, packages/document/docs/en/config/tools/bundler-chain.mdx, packages/document/docs/en/config/tools/rspack.mdx, packages/document/docs/en/plugins/dev/hooks.mdx, packages/document/docs/en/plugins/list/plugin-svelte.mdx, packages/document/docs/zh/config/tools/bundler-chain.mdx, packages/document/docs/zh/config/tools/rspack.mdx, packages/document/docs/zh/plugins/dev/hooks.mdx, packages/document/docs/zh/plugins/list/plugin-svelte.mdx, packages/plugin-check-syntax/src/index.ts, packages/plugin-image-compress/src/index.ts, packages/plugin-preact/src/index.ts, packages/plugin-react/src/react.ts, packages/plugin-react/tests/__snapshots__/features.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-solid/src/index.ts, packages/plugin-solid/tests/__snapshots__/index.test.ts.snap, packages/plugin-svelte/src/index.ts, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap, packages/shared/src/types/hooks.ts
- Add new isDev param, just for more convenience.
- Reuse `getChainUtils` function from core.
=> feat: add new isDev param

packages/document/docs/en/plugins/list/plugin-node-polyfill.mdx, packages/document/docs/zh/plugins/list/plugin-node-polyfill.mdx, packages/plugin-node-polyfill/src/index.ts, packages/plugin-node-polyfill/tests/__snapshots__/index.test.ts.snap, packages/plugin-node-polyfill/tests/index.test.ts
Add new globals option for `plugin-node-polyfill`.
```ts
pluginNodePolyfill({
globals: {
Buffer: false,
process: false,
},
});
```
=> feat(plugin-node-polyfill): add new globals option

README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx
Add Rsdoctor to ecosystem.
https://github.com/web-infra-dev/rsdoctor
=> docs: add Rsdoctor to ecosystem

package.json, packages/core/tests/__snapshots__/asset.test.ts.snap, packages/core/tests/__snapshots__/splitChunks.test.ts.snap, packages/core/tests/asset.test.ts, packages/core/tests/splitChunks.test.ts, pnpm-lock.yaml
- bump prettier v3.2, vitest v1.2
- fix some snapshots issue
=> chore(deps): bump prettier v3.2, vitest v1.2

packages/document/docs/en/guide/basic/tailwindcss.mdx, packages/document/docs/zh/guide/basic/tailwindcss.mdx
Add tailwindcss performance tip.
=> docs: add tailwindcss performance tip

README.zh-CN.md, packages/document/docs/zh/guide/start/index.mdx
Fix missing zh period in README file.
=> docs: missing zh period

packages/core/src/cli/commands.ts, packages/core/src/cli/config.ts, packages/document/docs/en/guide/basic/configure-rsbuild.mdx, packages/document/docs/zh/guide/basic/configure-rsbuild.mdx
support mode parameter in `defineConfig`
=> feat: support mode parameter in defineConfig

cspell.json, packages/document/package.json, packages/document/theme/index.tsx, packages/document/tsconfig.json, pnpm-lock.yaml
Integrate rsfamily-nav-icon to document.
https://github.com/rspack-contrib/rsfamily-nav-icon
=> docs: integrate rsfamily-nav-icon

packages/document/theme/index.tsx
docs: fix missing nav icon CSS
=> docs: fix missing nav icon CSS

packages/document/docs/en/guide/basic/configure-rsbuild.mdx, packages/document/docs/zh/guide/basic/configure-rsbuild.mdx
Improve document of config function params.
=> docs: improve config function params

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress to v1.11.1

examples/module-federation/host/module-federation.config.js, examples/module-federation/host/package.json, examples/module-federation/host/rsbuild.config.ts, examples/module-federation/host/src/App.js, examples/module-federation/host/src/bootstrap.js, examples/module-federation/host/src/index.js, examples/module-federation/remote/module-federation.config.js, examples/module-federation/remote/package.json, examples/module-federation/remote/rsbuild.config.ts, examples/module-federation/remote/src/App.js, examples/module-federation/remote/src/Button.js, examples/module-federation/remote/src/bootstrap.js, examples/module-federation/remote/src/index.js, pnpm-lock.yaml
Add basic module federation example, copied from https://github.com/module-federation/module-federation-examples/tree/master/cra
https://github.com/web-infra-dev/rsbuild/issues/1234
=> chore(example): add basic module federation example

e2e/README.md, examples/README.md, packages/document/docs/en/guide/start/glossary.mdx, packages/document/docs/zh/guide/start/glossary.mdx
- Add guide for examples and e2e.
- Update MF example link.
=> docs: add guide for examples and e2e

packages/document/docs/en/config/source/decorators.mdx, packages/document/docs/zh/config/source/decorators.mdx
Add document for `source.decorators` config.
- https://github.com/web-infra-dev/rsbuild/pull/1462
- close https://github.com/web-infra-dev/rsbuild/issues/87
=> docs: add document for decorators config

packages/core/src/provider/plugins/swc.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/plugin-preact/src/index.ts, packages/plugin-react/src/index.ts, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-svgr/src/index.ts
Add the SWC rule to the pre stage.
The SWC rule is basic and other plugins may depend on it. So we move the order of the SWC rule.
https://github.com/web-infra-dev/rsbuild/pull/1472
=> fix: attach SWC rule to the pre stage

packages/document/docs/en/config/source/include.mdx, packages/document/docs/zh/config/source/include.mdx
Improve include monorepo pkgs example
=> docs: improve include monorepo pkgs example

packages/document/docs/en/config/_meta.json, packages/document/docs/zh/config/_meta.json, packages/document/src/rsbuildPluginOverview.ts
Fix config options order, put security config in a proper place.
=> docs: fix config options order

packages/babel-preset/src/node.ts, packages/babel-preset/src/pluginLockCorejsVersion.ts, packages/babel-preset/src/web.ts, packages/compat/plugin-esbuild/src/index.ts, packages/compat/plugin-swc/src/constants.ts, packages/compat/plugin-swc/src/utils.ts
Reduce require.resolve for core-js.
=> perf: reduce require.resolve for core-js

packages/compat/plugin-swc/src/plugin.ts, packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap, packages/core/src/provider/plugins/swc.ts, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/shared/src/chain.ts
Set fullySpecified when defining the JS_DATA_URI rule.
=> chore: set fullySpecified when defining rule

packages/shared/src/chain.ts
=> fix: remove unused CHAIN_ID

packages/document/docs/en/config/output/filename-hash.mdx, packages/document/docs/zh/config/output/filename-hash.mdx
Add tips for filename hashing.
=> docs: add tips for filename hashing

e2e/cases/module-federation/host/rsbuild.config.ts, e2e/cases/module-federation/remote/rsbuild.config.ts, examples/module-federation/host/rsbuild.config.ts, examples/module-federation/remote/rsbuild.config.ts, packages/compat/webpack/src/shared.ts, packages/core/src/plugins/index.ts, packages/core/src/plugins/moduleFederation.ts, packages/core/src/provider/shared.ts, packages/core/tests/__snapshots__/inspect.test.ts.snap, packages/shared/src/chain.ts, packages/shared/src/config.ts, packages/shared/src/types/config/index.ts, packages/shared/src/types/plugin.ts
Add new moduleFederation config.
This PR adds some basic implementation, I will add splitChunk support and document later.
https://github.com/web-infra-dev/rsbuild/discussions/1461
https://github.com/web-infra-dev/rsbuild/issues/1234
=> feat: add new moduleFederation config

e2e/cases/module-federation/host/rsbuild.config.ts, e2e/cases/module-federation/remote/rsbuild.config.ts, examples/module-federation/host/rsbuild.config.ts, examples/module-federation/remote/rsbuild.config.ts, packages/core/src/plugins/moduleFederation.ts, packages/core/src/plugins/splitChunks.ts, packages/shared/src/types/config/performance.ts, packages/shared/src/utils.ts
Patch split chunks for module federation.
https://github.com/web-infra-dev/rsbuild/discussions/1461
=> feat: patch split chunks for module federation

packages/document/docs/en/config/_meta.json, packages/document/docs/en/config/module-federation/options.mdx, packages/document/docs/en/guide/basic/configure-rsbuild.mdx, packages/document/docs/zh/config/_meta.json, packages/document/docs/zh/config/module-federation/options.mdx, packages/document/docs/zh/guide/basic/configure-rsbuild.mdx, packages/document/src/rsbuildPluginOverview.ts
Add document for `moduleFederation.options`.
close https://github.com/web-infra-dev/rsbuild/issues/1234
=> docs: add document for moduleFederation.options

packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml, scripts/test-helper/package.json
https://github.com/web-infra-dev/rspack/releases/tag/v0.5.4
=> chore(deps): bump rspack 0.5.4

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress v1.11.2

packages/document/docs/en/config/source/transform-import.mdx, packages/document/docs/zh/config/source/transform-import.mdx
Improve transformImport config, add lodash example and fix some mistakes.
=> docs: improve transformImport config

packages/compat/plugin-swc/src/types.ts, packages/compat/plugin-swc/src/utils.ts, packages/compat/plugin-swc/tests/plugin.test.ts, packages/core/src/provider/config.ts, packages/shared/src/types/config/performance.ts
Remove unused transformLodash config type.
=> chore: remove unused transformLodash type

packages/shared/src/types/thirdParty.ts
Improve tools.cssLoader typing.
https://github.com/webpack-contrib/css-loader
=> types: improve tools.cssLoader typing

packages/document/docs/en/community/releases/v0-4.mdx, packages/document/docs/en/config/source/transform-import.mdx, packages/document/docs/zh/community/releases/v0-4.mdx, packages/document/docs/zh/config/source/transform-import.mdx
- Add import lodash tip.
- Improve transformImport example.
=> docs: add import lodash tip

.changeset/shaggy-sheep-lay.md, packages/compat/webpack/package.json, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/core/package.json, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/html.test.ts.snap, packages/core/tests/__snapshots__/inlineChunk.test.ts.snap, packages/plugin-assets-retry/package.json, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-rem/package.json, packages/shared/package.json, pnpm-lock.yaml
Bump html-rspack-plugin 5.6.0.
https://github.com/web-infra-dev/rspack/pull/5117
https://github.com/web-infra-dev/rsbuild/pull/1055
=> feat(deps): bump html-rspack-plugin 5.6.0

examples/mdx/package.json, examples/mdx/rsbuild.config.ts, examples/mdx/src/App.jsx, examples/mdx/src/hello.mdx, examples/mdx/src/index.jsx, packages/plugin-mdx/LICENSE, packages/plugin-mdx/README.md, packages/plugin-mdx/modern.config.ts, packages/plugin-mdx/package.json, packages/plugin-mdx/src/index.ts, packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap, packages/plugin-mdx/tests/index.test.ts, packages/plugin-mdx/tests/tsconfig.json, packages/plugin-mdx/tsconfig.json, pnpm-lock.yaml
Add @rsbuild/plugin-mdx package to support MDX.
https://www.npmjs.com/package/@mdx-js/loader
=> feat: add @rsbuild/plugin-mdx package

packages/plugin-mdx/src/index.ts, packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap, packages/plugin-mdx/tests/index.test.ts
Support configuring mdx loader options.
https://npmjs.com/package/@mdx-js/loader#api
=> feat(plugin-mdx): support configuring loader options

.github/renovate.json5
Group all patch for renovate, reduce patch PRs.
=> chore(workflow): group all patch for renovate

packages/document/docs/en/guide/start/npm-packages.mdx, packages/document/docs/en/plugins/list/_meta.json, packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-mdx.mdx, packages/document/docs/zh/guide/start/npm-packages.mdx, packages/document/docs/zh/plugins/list/_meta.json, packages/document/docs/zh/plugins/list/index.md, packages/document/docs/zh/plugins/list/plugin-mdx.mdx
Add document for MDX plugin.
https://github.com/web-infra-dev/rsbuild/pull/1550
=> docs: add document for MDX plugin

packages/plugin-mdx/src/index.ts, packages/plugin-react/src/react.ts, packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Support React refresh for MDX.
=> feat(plugin-mdx): support React refresh for MDX

.github/renovate.json5
Add @swc/helpers to ignoreDeps, it should be updated manually.
=> chore(workflow): add @swc/helpers to ignoreDeps

packages/document/docs/en/plugins/list/plugin-mdx.mdx, packages/document/docs/zh/plugins/list/plugin-mdx.mdx, packages/plugin-mdx/src/index.ts, packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
Add extensions option for MDX plugin.
=> feat(plugin-mdx): add extensions option

packages/document/docs/en/config/server/public-dir.mdx, packages/document/docs/en/guide/basic/static-assets.md, packages/document/docs/zh/config/server/public-dir.mdx, packages/document/docs/zh/guide/basic/static-assets.md
=> docs: add guide for public folder

packages/document/docs/zh/guide/migration/vue-cli.mdx
update `REACT_APP_` to `VUE_APP_`
=> docs: update vue-cli.mdx

packages/document/docs/en/guide/debug/_meta.json, packages/document/docs/en/guide/debug/rsdoctor.mdx, packages/document/docs/zh/guide/debug/_meta.json, packages/document/docs/zh/guide/debug/rsdoctor.mdx
=> docs: add using Rsdoctor guide

.github/renovate.json5
Allow renovate to create major updates.
=> chore(workflow): allow renovate to create major updates

packages/document/docs/en/plugins/list/plugin-mdx.mdx, packages/document/docs/zh/plugins/list/plugin-mdx.mdx
Add MDX type declarations guide.
=> docs: add MDX type declarations guide

.github/renovate.json5, pnpm-lock.yaml, scripts/update-packages/package.json, scripts/update-packages/src/modern.ts, scripts/update-packages/src/rspack.ts, scripts/update-packages/src/rspress.ts, scripts/update-packages/src/utils.ts
- remove execa dependency
- update renovate config
=> chore(scripts) remove execa dependency

packages/document/docs/en/config/dev/asset-prefix.mdx, packages/document/docs/en/config/output/asset-prefix.mdx, packages/document/docs/en/config/output/disable-minimize.mdx, packages/document/docs/en/config/output/inject-styles.mdx, packages/document/docs/en/guide/advanced/env-vars.md, packages/document/docs/en/guide/basic/cli.mdx, packages/document/docs/en/guide/faq/features.md, packages/document/docs/en/guide/optimization/optimize-bundle.md, packages/document/docs/en/plugins/list/plugin-type-check.mdx, packages/document/docs/en/plugins/list/plugin-typed-css-modules.mdx, packages/document/docs/zh/config/dev/asset-prefix.mdx, packages/document/docs/zh/config/output/asset-prefix.mdx, packages/document/docs/zh/plugins/list/plugin-typed-css-modules.mdx, packages/shared/src/types/config/output.ts
Improve assetPrefix document, add path relative example.
=> docs: improve assetPrefix document

packages/document/docs/en/plugins/dev/index.md, packages/document/docs/zh/plugins/dev/hooks.mdx, packages/document/docs/zh/plugins/dev/index.md
Add plugins comparison and some plugin examples.
=> docs: add plugins comparison

package.json, pnpm-lock.yaml
=> chore(deps): bump Modern.js v2.47.0

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress v1.12.0

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress v1.12.1

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress v.1.12.1

e2e/cases/source/multiple-entry/rsbuild.config.ts, packages/core/src/plugins/entry.ts, packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/en/config/source/entry.mdx, packages/document/docs/zh/api/javascript-api/instance.mdx, packages/document/docs/zh/config/source/entry.mdx, packages/shared/src/types/config/source.ts
- Add entry function guide.
- Update entry function params to make it simpler.
https://github.com/web-infra-dev/rsbuild/pull/1634
=> docs: add entry function guide

packages/document/docs/en/api/javascript-api/core.mdx, packages/document/docs/zh/api/javascript-api/core.mdx
- fix unused provider param of createRsbuild
- update createRsbuild example
https://github.com/web-infra-dev/rsbuild/issues/1638
=> docs: fix unused provider param of createRsbuild

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress v1.12.3

packages/document/docs/en/config/output/inline-scripts.mdx, packages/document/docs/zh/config/output/inline-scripts.mdx
Add script tag guide for inline script.
=> docs: add script tag guide for inline script

.changeset/happy-gorillas-rush.md, packages/document/docs/en/config/tools/bundler-chain.mdx, packages/document/docs/zh/config/tools/bundler-chain.mdx, packages/plugin-svgr/src/index.ts, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap, packages/shared/src/chain.ts, packages/shared/src/config.ts
Merge duplicated rules in plugin-svgr to reduce rule matching overhead.
=> perf(plugin-svgr): merge duplicated rules

packages/document/docs/en/plugins/dev/hooks.mdx, packages/document/docs/zh/plugins/dev/hooks.mdx
Update bundler type of modifyBundlerChain.
=> docs: update bundler type of modifyBundlerChain

packages/core/src/cli/commands.ts, packages/core/src/config.ts, packages/core/src/index.ts, packages/document/docs/en/config/plugins.mdx, packages/document/docs/en/guide/basic/cli.mdx, packages/document/docs/en/plugins/list/index.md, packages/document/docs/zh/config/plugins.mdx, packages/document/docs/zh/guide/basic/cli.mdx, packages/document/docs/zh/plugins/list/index.md
=> docs: add community plugins guide

packages/shared/src/url.ts
Avoid multiple prints of localhost when starting the dev server.
https://github.com/web-infra-dev/rsbuild/discussions/1543
=> fix(server): avoid multiple prints of localhost

packages/shared/src/constants.ts
=> chore: remove unused JSON_REGEX

package.json, pnpm-lock.yaml
=> chore(deps): bump Modern.js v2.47.1

packages/document/docs/en/guide/basic/configure-rsbuild.mdx, packages/document/docs/zh/guide/basic/configure-rsbuild.mdx, packages/shared/src/types/config/index.ts
Improve configuration structure document and JS Doc.
=> docs: improve configuration structure

.changeset/kind-wombats-hunt.md, packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml, scripts/test-helper/package.json
=> feat(deps): bump Rspack v0.5.5

packages/core/src/server/socketServer.ts
因为 node 版本会更新，这个类型可能也会改，用 ReturnType<typeof xxx>可以保证类型永远是最新的
=> types: Optimize timer using ReturnType

package.json, packages/plugin-eslint/LICENSE, packages/plugin-eslint/README.md, packages/plugin-eslint/modern.config.ts, packages/plugin-eslint/package.json, packages/plugin-eslint/src/index.ts, packages/plugin-eslint/tsconfig.json, packages/shared/src/chain.ts, pnpm-lock.yaml
Add new @rsbuild/plugin-eslint package.
https://www.npmjs.com/package/eslint-webpack-plugin
=> feat: add @rsbuild/plugin-eslint package

e2e/cases/eslint/.eslintrc.cjs, e2e/cases/eslint/.eslintrc.js, e2e/cases/eslint/index.test.ts, e2e/cases/eslint/package.json, e2e/cases/eslint/src/index.js, e2e/cases/mjs-artifact/test.mjs, e2e/package.json, packages/plugin-eslint/tests/__snapshots__/index.test.ts.snap, packages/plugin-eslint/tests/index.test.ts, packages/plugin-eslint/tests/tsconfig.json, pnpm-lock.yaml
Add some test cases for plugin-eslint.
https://github.com/web-infra-dev/rsbuild/pull/1679
=> test: add test cases for plugin-eslint

packages/plugin-eslint/src/index.ts, packages/plugin-eslint/tests/__snapshots__/index.test.ts.snap, packages/plugin-eslint/tests/index.test.ts, packages/plugin-type-check/tests/__snapshots__/index.test.ts.snap, packages/plugin-type-check/tests/index.test.ts
Avoid multiple registration in `@rsbuild/plugin-eslint`.
=> perf(plugin-eslint): avoid multiple registration

packages/document/docs/en/guide/faq/features.md, packages/document/docs/en/guide/start/npm-packages.mdx, packages/document/docs/en/plugins/list/_meta.json, packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-eslint.mdx, packages/document/docs/zh/guide/faq/features.md, packages/document/docs/zh/guide/start/npm-packages.mdx, packages/document/docs/zh/plugins/list/_meta.json, packages/document/docs/zh/plugins/list/index.md, packages/document/docs/zh/plugins/list/plugin-eslint.mdx
Add @rsbuild/plugin-eslint document.
=> docs: add @rsbuild/plugin-eslint document

package.json, packages/babel-preset/tests/__snapshots__/web.test.ts.snap, pnpm-lock.yaml
Regenerate lock file to fix renovate.
=> chore: regenerate lock file

packages/document/docs/en/guide/advanced/hmr.md
=> docs: fix proxy typo in hmr.md

packages/document/docs/en/plugins/list/plugin-eslint.mdx, packages/document/docs/zh/plugins/list/plugin-eslint.mdx
Add ESLint example projects to document.
=> docs: add ESLint examples

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress v1.13.0

package.json, pnpm-lock.yaml
=> chore(deps): bump Modern.js v2.48.0

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress v1.13.1

packages/document/docs/en/config/output/filename.mdx, packages/shared/src/types/config/output.ts
Improve JSDoc for filename configs.
=> chore: improve JSDoc for filename configs

.changeset/slimy-wasps-tell.md, packages/core/tests/output.test.ts, packages/document/docs/en/config/output/dist-path.mdx, packages/document/docs/zh/config/output/dist-path.mdx, packages/shared/src/chain.ts, packages/shared/src/fs.ts, packages/shared/src/types/config/output.ts
Add new `output.distPath.jsAsync` config.
https://github.com/web-infra-dev/rsbuild/issues/1699
=> feat: add output.distPath.jsAsync config

packages/document/docs/en/plugins/dev/hooks.mdx, packages/document/docs/zh/plugins/dev/hooks.mdx
add example for modifyRsbuildConfig
=> docs: add example for modifyRsbuildConfig

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress v1.13.2

packages/document/docs/en/api/javascript-api/core.mdx, packages/document/docs/zh/api/javascript-api/core.mdx
Intro merge rule of mergeRsbuildConfig.
=> docs: intro merge rule of mergeRsbuildConfig

packages/core/src/client/hmr/createSocketUrl.ts, packages/core/src/server/helper.ts, packages/core/tests/server.test.ts, packages/document/docs/en/config/dev/client.mdx, packages/document/docs/en/guide/advanced/hmr.md, packages/document/docs/zh/config/dev/client.mdx, packages/document/docs/zh/guide/advanced/hmr.md, packages/shared/src/types/config/dev.ts
Narrow dev.client.protocol type, make it more clear.
=> types: narrow dev.client.protocol type

README.md, README.zh-CN.md
=> docs(README): add graphs contributors

README.md, README.zh-CN.md
Improve contributor graph query params.
=> docs: improve contributor graph query params

README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx
Update benchmark data, use the latest Rspack / Rsbuild / Vite / Webpack to compare.
https://github.com/rspack-contrib/performance-compare
=> docs: update benchmark data

packages/document/docs/en/config/plugins.mdx, packages/document/docs/zh/config/plugins.mdx
Add using unplugin guide.
https://github.com/unjs/unplugin
=> docs: add using unplugin guide

packages/document/docs/en/config/html/tags.mdx, packages/document/docs/en/config/tools/html-plugin.mdx, packages/document/docs/en/guide/basic/html-template.md, packages/document/docs/en/plugins/list/plugin-assets-retry.mdx, packages/document/docs/zh/config/html/tags.mdx, packages/document/docs/zh/config/tools/html-plugin.mdx, packages/document/docs/zh/guide/basic/html-template.md, packages/document/docs/zh/plugins/list/plugin-assets-retry.mdx
Add more guide for https://github.com/rspack-contrib/html-rspack-plugin.
=> docs: add more guide for html plugin

packages/core/src/provider/plugins/swc.ts, packages/core/tests/__snapshots__/swc.test.ts.snap
Should merge tools.swc deeply with default config.
=> fix: merge tools.swc deeply with default config

packages/document/docs/en/config/output/minify.mdx, packages/document/docs/en/config/tools/style-loader.mdx, packages/document/docs/en/config/tools/swc.mdx, packages/document/docs/zh/config/output/minify.mdx, packages/document/docs/zh/config/tools/style-loader.mdx, packages/document/docs/zh/config/tools/swc.mdx
=> docs: add tools.swc document

packages/core/package.json, packages/shared/package.json, pnpm-lock.yaml, scripts/test-helper/package.json
=> chore: bump rspack to 0.5.6

packages/document/docs/en/config/tools/swc.mdx, packages/document/docs/zh/config/tools/swc.mdx
Add emotion and relay guide to `tools.swc` document.
=> docs: add emotion and relay guide

.changeset/yellow-jokes-beam.md, packages/plugin-styled-components/package.json, packages/plugin-styled-components/src/index.ts, packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap, packages/plugin-styled-components/tests/index.test.ts, pnpm-lock.yaml
The same as https://github.com/web-infra-dev/rsbuild/pull/1743.
=>  refactor(plugin-styled-components): modify rsbuild config directly

packages/plugin-preact/src/index.ts
Simplify the builtin tools.swc config of the preact plugin.
=> chore(plugin-preact): simplify tools.swc config

packages/document/docs/en/config/dev/asset-prefix.mdx, packages/document/docs/en/config/output/asset-prefix.mdx, packages/document/docs/zh/config/dev/asset-prefix.mdx, packages/document/docs/zh/config/output/asset-prefix.mdx
Add assetPrefix path types tip.
https://github.com/web-infra-dev/rsbuild/issues/1748
=> docs: add assetPrefix path types tip

packages/document/docs/en/config/server/host.mdx, packages/document/docs/zh/config/server/host.mdx, packages/shared/src/url.ts
=> docs: add ipv6 setup guide

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress v1.14.0

packages/document/docs/en/community/releases/v0-3.mdx, packages/document/docs/en/config/tools/swc.mdx, packages/document/docs/en/guide/faq/exceptions.md, packages/document/docs/en/shared/onAfterBuild.md, packages/document/docs/en/shared/onAfterCreateCompiler.md, packages/document/docs/en/shared/onBeforeBuild.md, packages/document/docs/en/shared/onBeforeCreateCompiler.md, packages/document/docs/zh/community/releases/v0-3.mdx, packages/document/docs/zh/config/tools/swc.mdx, packages/document/docs/zh/guide/faq/exceptions.md, packages/document/docs/zh/shared/onAfterBuild.md, packages/document/docs/zh/shared/onAfterCreateCompiler.md, packages/document/docs/zh/shared/onBeforeBuild.md, packages/document/docs/zh/shared/onBeforeCreateCompiler.md
Update hooks documents, add some links and fix some mistakes.
=> docs: update hooks documents

packages/compat/webpack/src/core/build.ts, packages/compat/webpack/src/core/devMiddleware.ts, packages/compat/webpack/src/shared.ts, packages/core/src/provider/build.ts, packages/core/src/provider/devMiddleware.ts, packages/core/src/server/devServer.ts, packages/shared/src/utils.ts
Add isMultiCompiler helper to replace the `try...catch`.
=> chore: add isMultiCompiler helper

packages/compat/webpack/src/core/createCompiler.ts, packages/core/src/provider/createCompiler.ts
Prefer using `hooks.tapPromise` to await for onDevCompileDone hook.
=> fix: should await for onDevCompileDone hook

.github/workflows/bench-pr.yml, .github/workflows/issue-close-require.yml, .github/workflows/issue-label.yml, .github/workflows/issue-labeled.yml, .github/workflows/pr-label.yaml, .github/workflows/release-pull-request.yml, .github/workflows/release.yml
This PR will examine workflows related to **issues** or **releases** and ensure they only run on the original repository.
=> chore(workflows): disable github workflows on forked repository

packages/document/docs/en/guide/start/npm-packages.mdx, packages/document/docs/zh/guide/start/npm-packages.mdx
=> docs: fix missing container type

.changeset/little-ways-hunt.md, packages/document/docs/en/plugins/list/plugin-svgr.mdx, packages/document/docs/zh/plugins/list/plugin-svgr.mdx
Add SVGR react query guide.
https://github.com/web-infra-dev/rsbuild/pull/1783
=> docs(plugin-svgr): add react query guide

packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml, scripts/test-helper/package.json
=> feat(deps): bump rspack to 0.5.7

.gitignore, e2e/cases/swc-plugin/index.test.ts, e2e/cases/swc-plugin/package.json, e2e/cases/swc-plugin/rsbuild.config.ts, e2e/cases/swc-plugin/src/index.js, packages/shared/src/types/rspack.ts, pnpm-lock.yaml
Support for SWC experimental plugins.
https://github.com/web-infra-dev/rspack/issues/5921
=> feat: support for SWC experimental plugins

packages/document/docs/en/guide/basic/tailwindcss.mdx, packages/document/docs/zh/guide/basic/tailwindcss.mdx
Add tailwindcss package installation tip.
=> docs: add tailwindcss package installation tip

README.md, README.zh-CN.md, packages/document/docs/en/community/releases/v0-1.mdx, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/community/releases/v0-1.mdx, packages/document/docs/zh/guide/start/index.mdx
Add Lightning CSS to intro.
https://github.com/web-infra-dev/rsbuild/pull/1741
=> docs: add Lightning CSS to intro

packages/plugin-svgr/src/index.ts
Remove the `svgDefaultExport` option of `@rsbuild/plugin-svgr`, use `svgrOptions.exportType` instead.
- Before:
```js
pluginSvgr({
svgDefaultExport: 'component',
});
```
- After:
```js
pluginSvgr({
svgrOptions: {
exportType: 'default',
},
});
```
=> breaking change(svgr): remove deprecated svgDefaultExport

.vscode/settings.json, packages/document/docs/en/config/tools/rspack.mdx, packages/document/docs/en/plugins/dev/index.md, packages/document/docs/en/plugins/list/plugin-babel.mdx, packages/document/docs/zh/config/tools/rspack.mdx, packages/document/docs/zh/plugins/dev/index.md, packages/document/docs/zh/plugins/list/plugin-babel.mdx
Make some demos more type friendly.
=> docs: make some demos more type friendly

packages/document/docs/en/config/source/include.mdx, packages/document/docs/zh/config/source/include.mdx
Aadd check syntax link to source.include document.
=> docs: add check syntax link to source.include

e2e/cases/svg/svgr-mdx/index.test.ts, e2e/cases/svg/svgr-mdx/rsbuild.config.ts, e2e/cases/svg/svgr-mdx/src/app.mdx, e2e/cases/svg/svgr-mdx/src/index.js, e2e/cases/svg/svgr-mdx/src/small.svg, packages/plugin-svgr/src/index.ts, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
`@rsbuild/plugin-svgr` add support for mdx.
=> feat(plugin-svgr): add support for mdx

package.json, pnpm-lock.yaml
resolve https://github.com/web-infra-dev/rsbuild/issues/1804
=> chore(deps): bump Modern.js v2.48.1

packages/core/src/cli/prepare.ts
Improve greet log when using bun.
- before:
- after:
=> fix: improve greet log when using bun

packages/document/docs/en/config/output/minify.mdx, packages/document/docs/zh/config/output/minify.mdx
Correct the output.minify code examples.
=> docs: correct output.minify examples

packages/document/package.json, pnpm-lock.yaml
=> chore(deps): bump Rspress v1.15.1

packages/document/docs/en/guide/optimization/build-performance.mdx, packages/document/docs/zh/guide/optimization/build-performance.mdx
reference https://www.rspack.dev/zh/guide/profile.html
=> docs: add Rspack Profiling guide

package.json, pnpm-lock.yaml
=> chore(deps): bump Modern.js v2.48.2

packages/document/docs/en/plugins/list/plugin-svgr.mdx, packages/document/docs/zh/plugins/list/plugin-svgr.mdx
Improve SVGR types guide for different cases.
=> docs: improve SVGR types guide

packages/document/docs/en/config/module-federation/options.mdx, packages/document/docs/en/guide/optimization/optimize-bundle.md, packages/document/docs/zh/config/module-federation/options.mdx, packages/document/docs/zh/guide/optimization/optimize-bundle.md
Recommend using Rsdoctor to detect duplicated packages.
https://rsdoctor.dev/blog/topic/duplicate-pkg-problem
=> docs: use Rsdoctor for duplicated packages

packages/document/docs/en/config/dev/start-url.mdx
https://github.com/web-infra-dev/rsbuild/issues/1856
=> docs: modify MacOS to macOS

packages/document/docs/en/config/tools/bundler-chain.mdx
=> docs: modify Toml to TOML

packages/document/docs/en/guide/migration/cra.mdx, packages/document/docs/zh/guide/migration/cra.mdx
Add react-jest example to CRA migration doc.
https://github.com/rspack-contrib/rspack-examples/pull/34
=> docs: add react-jest example to CRA migration doc

packages/document/docs/en/guide/basic/server.md, packages/document/docs/zh/guide/basic/server.md
=> docs: update custom server introduce

packages/document/package.json, pnpm-lock.yaml
Bump Rspress canary to fix SSG.
https://github.com/web-infra-dev/rspress/pull/810
=> chore: bump Rspress canary to fix SSG

e2e/cases/server/custom-server/index.test.ts, e2e/cases/server/custom-server/scripts/pure-server.mjs, e2e/cases/server/custom-server/scripts/server.mjs, packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/zh/api/javascript-api/instance.mdx
update express and polka example
=> docs: update custom server example

packages/document/docs/en/plugins/list/plugin-lightningcss.mdx, packages/document/docs/zh/plugins/list/plugin-lightningcss.mdx
=> docs(plugin-lightningcss): notes of lightningcss

packages/document/docs/en/community/releases/v0-5.mdx, packages/document/docs/zh/config/output/css-modules.mdx
Fix mistake of cssModules.auto RegExp.
=> docs: fix mistake of cssModules.auto RegExp

pnpm-lock.yaml, scripts/test-helper/package.json
=> chore(deps): remove unused rspack deps in test-helper

.gitignore, e2e/.gitignore
https://playwright.dev/docs/test-cli#reference
=> chore(test): ignore directory for artifacts produced by tests

e2e/cases/svg/svgr-query-custom/index.test.ts, e2e/cases/svg/svgr-query-custom/rsbuild.config.ts, e2e/cases/svg/svgr-query-custom/src/App.jsx, e2e/cases/svg/svgr-query-custom/src/index.js, e2e/cases/svg/svgr-query-custom/src/small.svg, packages/document/docs/en/plugins/list/plugin-svgr.mdx, packages/document/docs/zh/plugins/list/plugin-svgr.mdx, packages/plugin-svgr/src/index.ts
Add new query option for plugin-svgr to custom the query suffix to match SVGR transformation..
=> feat(plugin-svgr): add new query option

packages/document/package.json, pnpm-lock.yaml
reduce the total font size.
https://github.com/rspack-contrib/rsfamily-nav-icon/pull/1
=> docs: bump rsfamily-nav-icon v1.0.2

packages/document/docs/en/plugins/list/plugin-lightningcss.mdx, packages/document/docs/zh/plugins/list/plugin-lightningcss.mdx, packages/plugin-lightningcss/src/plugin.ts, packages/plugin-lightningcss/src/types.ts, packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap, packages/plugin-lightningcss/tests/index.test.ts
accept usages like below
```ts
pluginLightningcss({
transform: process.env.NODE_ENV === 'development'
});
```
=> feat(plugin-lightningcss): transform accepts boolean type

packages/document/package.json, packages/document/rspress.config.ts, pnpm-lock.yaml
Use rsbuild-plugin-open-graph to generate Open Graph meta tags.
https://github.com/rspack-contrib/rsbuild-plugin-open-graph
=> docs: use rsbuild-plugin-open-graph

.changeset/six-bees-kiss.md, README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx
=> docs: update roadmap

packages/document/docs/en/plugins/list/plugin-styled-components.mdx, packages/document/docs/zh/plugins/list/plugin-styled-components.mdx
=> docs(plugin-styled-components): rspack styled-components link fix

nx.json
=> fix(nx.json): modify defaultBase configuration

packages/document/docs/en/config/html/tags.mdx, packages/document/docs/zh/config/html/tags.mdx
update `html.tags` example and  the meaning of `append` .
=> docs: update html.tags `append` introduce

packages/document/docs/en/plugins/list/plugin-node-polyfill.mdx, packages/document/docs/zh/plugins/list/plugin-node-polyfill.mdx
Add document for node polyfill plugin options.
https://github.com/web-infra-dev/rsbuild/pull/1402
=> docs: add document for node polyfill plugin options

.github/PULL_REQUEST_TEMPLATE.md, README.md, README.zh-CN.md, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx
Add rsfamily-design-resources link.
https://github.com/rspack-contrib/rsfamily-design-resources
=> docs: add rsfamily-design-resources link

packages/core/src/client/hmr/overlay.ts
Make overlay responsive and improve the styles:
=> feat: make overlay responsive

packages/document/docs/en/guide/optimization/build-performance.mdx, packages/document/docs/en/plugins/list/plugin-lightningcss.mdx, packages/document/docs/zh/guide/optimization/build-performance.mdx
- Add lightningcss to build perf guide.
- Update outdated content.
=> docs: add lightningcss to build perf guide

packages/core/src/client/hmr/overlay.ts
Improve overlay close icon style:
=> feat: improve overlay close icon style

.changeset/six-houses-impress.md, packages/core/src/client/hmr/overlay.ts
Support for close overlay with esc.
=> feat: support for close overlay with esc

packages/core/src/client/hmr/overlay.ts
Add fade out transition for error overlay
=> feat: add fade out transition for error overlay

packages/document/docs/en/plugins/dev/core.mdx, packages/document/docs/zh/plugins/dev/core.mdx
Add guide for plugin communication.
see: https://github.com/web-infra-dev/rsbuild/pull/1972
=> docs: add guide for plugin communication

packages/document/rspress.config.ts
Keep the same as other ecological documents
=> chore: EditLink displays Chinese in zh locale

packages/document/docs/en/plugins/list/plugin-svgr.mdx, packages/document/docs/zh/plugins/list/plugin-svgr.mdx
=> docs(plugin-svgr): typo of export type

packages/core/src/rspack/transformLoader.ts, packages/shared/src/types/plugin.ts
Expose resource path and query for the transform API.
=> feat: expose resource path and query for transform API

packages/document/docs/en/guide/debug/_meta.json, packages/document/docs/en/guide/debug/build-profiling.mdx, packages/document/docs/en/guide/optimization/build-performance.mdx, packages/document/docs/zh/guide/debug/_meta.json, packages/document/docs/zh/guide/debug/build-profiling.mdx, packages/document/docs/zh/guide/optimization/build-performance.mdx
Create a separate page for the "Build Profiling" document.
=> docs: make build profiling a separate page

packages/document/docs/en/index.md, packages/document/docs/zh/index.md
Add the RSS link to homepage.
https://github.com/web-infra-dev/rspress/issues/828
=> docs: add RSS link to homepage

packages/core/src/server/compilerDevMiddleware.ts, packages/core/src/server/devServer.ts, packages/core/src/server/getDevMiddlewares.ts, packages/core/src/server/helper.ts, packages/core/src/server/socketServer.ts, packages/core/tests/server.test.ts, packages/shared/src/types/server.ts
fix `server.proxy` not work when has `dev.proxy`.
=> fix(server): unexpected dev config overwrite server config

packages/document/docs/en/guide/start/index.mdx, packages/document/docs/zh/guide/start/index.mdx
Add rspack-examples to intro page.
close https://github.com/web-infra-dev/rsbuild/issues/1867
=> docs: add rspack-examples to intro page

e2e/cases/mjs-artifact/test.mjs
add pluginLightningcss and pluginUmd to e2e/mjs-artifact
=> test(e2e/mjs-artifact): add pluginLightningcss and pluginUmd

packages/document/docs/zh/plugins/list/plugin-eslint.mdx
=> docs(plugin-eslint): fix incorrect description

packages/core/tests/pluginDagSort.test.ts
Add a new test case for plugin dag sort.
=> test(ut): add case for plugin dag sort

e2e/cases/server/overlay/index.test.ts, e2e/cases/server/overlay/rsbuild.config.ts, e2e/cases/server/overlay/src/App.tsx, e2e/cases/server/overlay/src/index.tsx
https://github.com/web-infra-dev/rsbuild/pull/1939
=> test(e2e): add case for client.overlay

packages/document/docs/en/api/javascript-api/instance.mdx, packages/document/docs/en/config/html/template-parameters.mdx, packages/document/docs/en/guide/basic/cli.mdx, packages/document/docs/en/guide/start/glossary.mdx, packages/document/docs/en/guide/start/index.mdx, packages/document/docs/en/plugins/dev/core.mdx, packages/document/docs/en/plugins/dev/index.md, packages/document/docs/en/plugins/list/index.md, packages/document/docs/en/plugins/list/plugin-rem.mdx, packages/document/docs/en/plugins/list/plugin-svgr.mdx, packages/document/docs/zh/plugins/dev/core.mdx, packages/shared/src/types/plugin.ts
Add the transform plugin API to document, and remove the experimental tag.
=> docs: add the transform plugin API

packages/document/docs/en/community/releases/v0-1.mdx, packages/document/docs/en/community/releases/v0-2.mdx, packages/document/docs/en/community/releases/v0-3.mdx, packages/document/docs/en/community/releases/v0-4.mdx, packages/document/docs/en/community/releases/v0-5.mdx, packages/document/docs/en/index.md, packages/document/docs/zh/community/releases/v0-1.mdx, packages/document/docs/zh/community/releases/v0-2.mdx, packages/document/docs/zh/community/releases/v0-3.mdx, packages/document/docs/zh/community/releases/v0-4.mdx, packages/document/docs/zh/community/releases/v0-5.mdx, packages/document/docs/zh/index.md, packages/document/rspress.config.ts, packages/document/theme/index.scss, packages/document/theme/index.tsx
Update the URL of some design resoureces.
https://github.com/rspack-contrib/rsfamily-design-resources
=> docs: update URL of some design resoureces

packages/document/docs/en/plugins/dev/core.mdx, packages/document/docs/zh/plugins/dev/core.mdx
=> docs: fix expose typo

packages/document/docs/en/config/output/inline-scripts.mdx, packages/document/docs/en/config/output/inline-styles.mdx, packages/document/docs/zh/config/output/inline-scripts.mdx, packages/document/docs/zh/config/output/inline-styles.mdx
=> docs: fix output.inlineStyle example

packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml
bump rspack to fix a known bug: https://github.com/web-infra-dev/rspack/issues/6164
=> fix(deps): bump rspack to 0.6.1

packages/document/docs/en/guide/start/quick-start.mdx, packages/document/docs/zh/guide/start/quick-start.mdx
Improve quickstart guide, add migration tips for other projects.
=> docs: improve quickstart guide

packages/document/docs/en/guide/start/features.mdx, packages/document/docs/zh/guide/start/features.mdx
Update the feature list as some of it is out of date.
=> docs: update features list

CONTRIBUTING.md
Add image assets guide to contributing.
=> docs: add image assets guide to contributing

packages/core/src/client/hmr/index.ts
It will helpful when some hmr update error.
=> feat(server): add HMR forced reload error log

e2e/cases/plugin-api/plugin-hooks/index.test.ts
Update plugin hooks test case and add `modifyHTMLTags` and `onDevCompileDone` hooks.
=> test(e2e): update plugin hooks test case

packages/document/docs/en/plugins/dev/hooks.mdx, packages/document/docs/zh/plugins/dev/hooks.mdx
Add `api.modifyHTMLTags` to document.
https://github.com/web-infra-dev/rsbuild/pull/2078
=> docs: add api.modifyHTMLTags to document

packages/core/src/config.ts
Fix failed to resolve mjs or cjs entry.
=> fix: failed to resolve mjs or cjs entry

packages/shared/src/utils.ts
close https://github.com/web-infra-dev/rsbuild/issues/2112
=> fix: remove the SIGINT listener

packages/core/src/provider/initPlugins.ts, packages/document/docs/en/community/releases/v0-6.mdx, packages/document/docs/zh/community/releases/v0-6.mdx, packages/shared/src/utils.ts
Update Rspack v0.6 link, link to the announcement page.
Also removed the onExitProcess util.
=> docs: update Rspack v0.6 link

packages/document/docs/en/config/source/entry.mdx, packages/document/docs/zh/config/source/entry.mdx
=> docs: fix entry function example

website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
Simplify the environment setup guide in quick start document.
=> docs: simplify environment setup guide

scripts/dictionary.txt, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
Add online example to quick start.
the same as https://github.com/web-infra-dev/rspack/pull/6294
=> docs: add online example to quick start

README.md, README.zh-CN.md
Add a node version badge to README.
=> docs: add node version badge to README

.changeset/clean-hornets-move.md, website/docs/en/plugins/list/plugin-react.mdx, website/docs/zh/plugins/list/plugin-react.mdx
translate enableProfiler to Chinese
https://github.com/web-infra-dev/rsbuild/pull/2143
=> docs(plugin-react): translate enableProfiler to Chinese

packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml
Bump Rspack v0.6.3.
https://github.com/web-infra-dev/rspack/releases/tag/v0.6.2
=> feat(deps): bump Rspack v0.6.3

pnpm-lock.yaml, website/docs/en/index.md, website/docs/zh/index.md, website/package.json, website/theme/index.scss
- update slogan and improve line break
- bump Rspress 1.18.4 to fix button styles
=>  docs: update slogan and improve line break

package.json
ref https://github.com/web-infra-dev/rsbuild/pull/2162#issuecomment-2076281753
https://biomejs.dev/reference/cli/
=> chore: biome should silence error when unmatched

packages/compat/webpack/package.json, packages/core/package.json, packages/plugin-assets-retry/package.json, packages/plugin-rem/package.json, packages/shared/package.json, pnpm-lock.yaml
bump html-rspack-plugin@5.7.0 to reduce dependencies and improve performance.
changes: https://github.com/rspack-contrib/html-rspack-plugin/pull/7
=> feat(deps): bump html-rspack-plugin@5.7.0

.gitattributes
Let GitHub languages ignores MDX files.
https://github.com/github-linguist/linguist/blob/master/docs/overrides.md
https://twitter.com/zhmushan/status/1784416473823465648
=> chore: let GitHub languages ignores MDX files

packages/core/package.json, packages/core/prebundle.config.mjs, packages/core/src/server/devMiddleware.ts, packages/core/src/server/proxy.ts, packages/create-rsbuild/package.json, packages/plugin-babel/package.json, packages/plugin-rem/package.json, packages/plugin-svgr/package.json, packages/plugin-yaml/package.json, packages/shared/package.json, packages/shared/prebundle.config.mjs, packages/shared/src/types/config/server.ts, packages/shared/src/types/thirdParty.ts, pnpm-lock.yaml
Fix all types broken by prebundle: https://github.com/web-infra-dev/rsbuild/pull/2239
=> types: fix types broken by prebundle

website/docs/en/config/module-federation/options.mdx, website/docs/en/guide/advanced/_meta.json, website/docs/en/guide/advanced/module-federation.mdx, website/docs/en/guide/start/features.mdx, website/docs/en/guide/start/glossary.mdx, website/docs/zh/config/module-federation/options.mdx, website/docs/zh/guide/advanced/_meta.json, website/docs/zh/guide/advanced/module-federation.mdx, website/docs/zh/guide/start/features.mdx, website/docs/zh/guide/start/glossary.mdx
Add module federation guide to help users choose the module federation version to use.
=> docs: add module federation guide

README.md, README.zh-CN.md, scripts/dictionary.txt, website/docs/en/guide/start/index.mdx, website/docs/zh/guide/start/index.mdx
Add comparisons section to introduction.
=> docs: add comparisons to introduction

website/docs/en/guide/basic/static-deploy.mdx, website/docs/zh/guide/basic/static-deploy.mdx
=> docs: add deploy guide for Netlify

website/docs/en/guide/basic/static-deploy.mdx, website/docs/zh/guide/basic/static-deploy.mdx
Add deploy guide for Vercel.
https://github.com/web-infra-dev/rsbuild/issues/780
=> docs: add deploy guide for Vercel

packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml
Bump Rspack v0.6.4: https://github.com/web-infra-dev/rspack/releases
=> feat(deps): bump Rspack v0.6.4

website/docs/en/guide/basic/static-deploy.mdx, website/docs/zh/guide/basic/static-deploy.mdx
Add deploy guide for Cloudflare Pages.
https://github.com/web-infra-dev/rsbuild/issues/780
=> docs: add deploy guide for Cloudflare Pages

README.md, e2e/cases/css/css-modules-composes/index.test.ts, e2e/cases/css/css-modules-global/index.test.ts, e2e/cases/css/css-modules-named-export/index.test.ts, e2e/cases/css/css-modules/index.test.ts, e2e/cases/css/import-loaders/index.test.ts, packages/shared/src/loaders/ignoreCssLoader.ts, packages/shared/src/types/config/output.ts, packages/shared/src/types/thirdParty.ts, website/docs/en/community/releases/v0-6.mdx, website/docs/en/config/output/css-modules.mdx, website/docs/en/guide/start/index.mdx
update `CSS modules` to `CSS Modules`
=> docs: unify CSS Modules

e2e/cases/css/css-modules-ident-name/index.test.ts, e2e/cases/css/css-modules-ident-name/src/a.module.css, e2e/cases/css/css-modules-ident-name/src/index.js, e2e/cases/css/css-modules-ident-name/src/sub/a.module.css
Add test case for https://github.com/web-infra-dev/rspack/issues/6470
=> test(e2e): add case for CSS Modules ident name

website/docs/en/config/server/public-dir.mdx, website/docs/zh/config/server/public-dir.mdx
Improve publicDir document, add tip for copy files in the dev build.
https://github.com/web-infra-dev/rsbuild/issues/2278
=> docs: improve publicDir document

website/docs/en/guide/framework/react.mdx, website/docs/zh/guide/framework/react.mdx
Add vanilla-extract guide and example link.
https://github.com/web-infra-dev/rsbuild/discussions/2298
=> docs(react): add vanilla-extract guide

website/docs/en/config/tools/swc.mdx, website/docs/en/guide/framework/react.mdx, website/docs/zh/config/tools/swc.mdx, website/docs/zh/guide/framework/react.mdx
Add guide and example link for Emotion.
=> docs: add guide for Emotion

website/docs/en/config/plugins.mdx, website/docs/zh/config/plugins.mdx
=> feat: add unplugin transform hook doc

scripts/dictionary.txt, website/docs/en/config/plugins.mdx, website/docs/en/guide/basic/css-usage.mdx, website/docs/en/guide/framework/react.mdx, website/docs/zh/config/plugins.mdx, website/docs/zh/guide/basic/css-usage.mdx, website/docs/zh/guide/framework/react.mdx
=> docs: add guide for StyleX

website/docs/en/guide/framework/react.mdx, website/docs/zh/guide/framework/react.mdx
=> docs: add guide for styled-jsx

website/docs/en/guide/basic/configure-rspack.mdx, website/docs/en/shared/bundlerChain.mdx, website/docs/zh/config/plugins.mdx, website/docs/zh/config/tools/rspack.mdx, website/docs/zh/guide/basic/configure-rspack.mdx, website/docs/zh/shared/bundlerChain.mdx
Add more example of configuring Rspack plugins, as some users may not know how to use Rspack / webpack plugins.
=> docs: add more example of configuring Rspack plugins

e2e/cases/mjs-artifact/test.mjs, packages/compat/webpack/src/provider.ts, packages/core/src/internal.ts, packages/core/src/pluginHelper.ts, packages/core/src/plugins/css.ts, packages/core/src/plugins/output.ts, packages/core/src/provider/rspackConfig.ts, packages/core/src/rspack/HtmlAppIconPlugin.ts, packages/core/src/rspack/HtmlBasicPlugin.ts, packages/core/src/rspack/InlineChunkHtmlPlugin.ts, packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts, packages/shared/modern.config.ts, packages/shared/package.json, packages/shared/src/chain.ts, packages/shared/src/config.ts, packages/shared/src/fs.ts, packages/shared/src/getBrowserslist.ts, packages/shared/src/logger.ts, packages/shared/src/minimize.ts, packages/shared/src/utils.ts
Provide mjs exports for `@rsbuild/shared`.
https://github.com/web-infra-dev/rsbuild/issues/99
=> feat(shared): provide mjs exports

website/docs/en/api/javascript-api/core.mdx, website/docs/zh/api/javascript-api/core.mdx
Update Rspack JS API link, see: https://github.com/web-infra-dev/rspack/pull/6529
=> docs: update Rspack JS API link

packages/core/src/plugins/css.ts, packages/core/src/plugins/resourceHints.ts, packages/plugin-lightningcss/src/plugin.ts, packages/shared/src/types/config/output.ts, website/docs/en/config/output/dist-path.mdx, website/docs/en/config/output/override-browserslist.mdx, website/docs/en/config/tools/css-loader.mdx, website/docs/en/guide/advanced/browserslist.mdx, website/docs/zh/config/output/dist-path.mdx, website/docs/zh/config/output/override-browserslist.mdx, website/docs/zh/config/tools/css-loader.mdx, website/docs/zh/guide/advanced/browserslist.mdx
Fix some inaccurate target judgments. The service-worker target is often forgotten, which may lead to some problems
Also updated some outdated documents for css-loader and browserslist.
=> fix: some inaccurate target judgments

.github/workflows/test-ubuntu.yml, .github/workflows/test-windows.yml, website/docs/en/guide/start/npm-packages.mdx, website/docs/en/plugins/list/plugin-typed-css-modules.mdx, website/docs/zh/guide/start/npm-packages.mdx
- Skip CI when meta.json and dictionary.txt changed.
- Add @rsbuild/plugin-typed-css-modules to packages list.
=> chore(workflow): skip CI when meta.json changed

scripts/modern.base.config.ts
Fix a typo in https://github.com/web-infra-dev/rsbuild/pull/2353.
=> chore: fix dist types package.json path

website/docs/en/guide/framework/react.mdx, website/docs/zh/guide/framework/react.mdx
- Doc: https://react.dev/learn/react-compiler
- Plugin: https://www.npmjs.com/package/babel-plugin-react-compiler
=> docs: add guide for React Compiler

README.md, README.zh-CN.md, website/docs/en/guide/start/index.mdx, website/docs/zh/guide/start/index.mdx
https://github.com/rspack-contrib/storybook-rsbuild
https://github.com/web-infra-dev/rsbuild/issues/1974
=> docs: add rsbuild-storybook link

packages/core/src/internal.ts, scripts/test-helper/src/rsbuild.ts
Simplify the createStubRsbuild method by using the new `rsbuild.getPlugins()` API.
https://github.com/web-infra-dev/rsbuild/pull/2369
=> test(helper): simplify createStubRsbuild

.vscode/settings.json, packages/core/src/plugins/moduleFederation.ts, packages/core/src/provider/build.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/server/compilerDevMiddleware.ts, packages/core/src/server/devMiddleware.ts, packages/core/src/server/devServer.ts, packages/core/src/server/getDevMiddlewares.ts, packages/core/src/server/middlewares.ts, packages/core/src/server/watchFiles.ts, packages/core/src/types.ts, packages/plugin-lightningcss/tests/index.test.ts, packages/shared/src/types/rspack.ts, packages/shared/src/types/server.ts
Clean up Rspack and server types of the `@rsbuild/shared` package.
=> chore(shared): clean up Rspack and server types

website/docs/en/api/start/index.mdx, website/docs/en/config/dev/before-start-url.mdx, website/docs/en/config/html/script-loading.mdx, website/docs/zh/api/start/index.mdx, website/docs/zh/config/dev/before-start-url.mdx, website/docs/zh/config/html/script-loading.mdx
Add example for exports format of JavaScript APIs.
=> docs: add example for exports format

website/docs/en/guide/faq/exceptions.mdx, website/docs/en/plugins/list/plugin-source-build.mdx, website/docs/zh/guide/faq/exceptions.mdx, website/docs/zh/plugins/list/plugin-source-build.mdx
=> docs: fix node.org dead link

packages/core/package.json, packages/plugin-react/package.json, packages/shared/package.json, pnpm-lock.yaml
bump Rspack 0.7.0-beta.1
https://github.com/web-infra-dev/rspack/releases/tag/v0.7.0-beta.1
=> chore(deps): bump Rspack 0.7.0-beta.1

e2e/cases/css/tailwindcss-hmr/index.test.ts, e2e/cases/css/tailwindcss-hmr/postcss.config.cjs, e2e/cases/css/tailwindcss-hmr/src/index.css, e2e/cases/css/tailwindcss-hmr/src/index.js, e2e/cases/css/tailwindcss-hmr/tailwind.config.cjs
Add E2E case for tailwindcss HMR.
https://github.com/web-infra-dev/rspack/issues/6422
=> test(e2e): add case for tailwindcss HMR

e2e/cases/css/less-exclude/index.test.ts, e2e/cases/css/less-exclude/rsbuild.config.ts, e2e/cases/css/sass-exclude/index.test.ts, e2e/cases/css/sass-exclude/rsbuild.config.ts, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-less/tests/index.test.ts, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/tests/index.test.ts
Update sass/less config usages in the test cases.
- https://github.com/web-infra-dev/rsbuild/pull/2407
- https://github.com/web-infra-dev/rsbuild/pull/2406
=> test: update sass/less config usages
