web-infra-dev/rsbuild

e2e/cases/assets/styles-as-assets/index.test.ts, e2e/cases/assets/styles-as-assets/src/test4.styl, e2e/cases/solid/stylus/src/App.styl, e2e/cases/stylus/basic/src/b.module.styl, e2e/cases/stylus/environment/src/b.module.styl, e2e/cases/stylus/rem/src/b.module.styl, packages/core/src/createRsbuild.ts
Adopt the recommendations in https://github.com/web-infra-dev/rsbuild/pull/4437.
Stylus supports omitting symbols such as `&` and `;`.
=> test(e2e): simplify stylus code

e2e/package.json
After bumping Rspack 1.2.0, Rsbuild's E2E testing takes longer and become unstable (We are still investigating the cause).
This PR reduced the number of cases that need to be run to make CI relatively stable.
=> test(e2e): run Rspack with incremental flag

website/docs/en/guide/basic/_meta.json, website/docs/en/guide/basic/tailwindcss-v3.mdx, website/docs/en/guide/basic/tailwindcss.mdx, website/docs/zh/guide/basic/_meta.json, website/docs/zh/guide/basic/tailwindcss-v3.mdx, website/docs/zh/guide/basic/tailwindcss.mdx
This pull request includes updates to the documentation files to add support for Tailwind CSS v3 and v4. The changes include new guides for integrating Tailwind CSS v3 and updates to the existing Tailwind CSS guide to reflect Tailwind CSS v4.
https://github.com/web-infra-dev/rsbuild/pull/4425
=> docs: provides guides for both Tailwind CSS v3 and v4

website/docs/en/guide/basic/server.mdx, website/docs/zh/guide/basic/server.mdx
This pull request includes updates to the Rsbuild configuration documentation. The changes add a new configuration mapping for `devServer.devMiddleware.writeToDisk`.
=> docs: add dev server writeToDisk config mapping

packages/core/package.json, pnpm-lock.yaml
Update `rspack-chain` to v1.2.0, the license has been changed to MIT.
see https://github.com/rspack-contrib/rspack-chain/releases/tag/v1.2.0
=> chore(deps): update rspack-chain to v1.2.0

e2e/cases/output/source-map/index.test.ts, packages/compat/webpack/src/webpackConfig.ts, packages/core/src/plugins/basic.ts, packages/core/src/provider/rspackConfig.ts, packages/core/src/types/hooks.ts, website/docs/en/plugins/dev/hooks.mdx, website/docs/zh/plugins/dev/hooks.mdx
When JS source map is disabled, but CSS source map is enabled, we should add the `SourceMapDevToolPlugin` to let Rspack generate CSS source map.
- resolve https://github.com/web-infra-dev/rsbuild/issues/4397
- https://rspack.dev/plugins/webpack/source-map-dev-tool-plugin#host-source-maps-externally
=> fix: allow to only generate source map for CSS files

packages/compat/webpack/src/webpackConfig.ts, packages/core/package.json, packages/core/src/configChain.ts, packages/core/src/provider/helpers.ts, packages/core/src/provider/rspackConfig.ts, pnpm-lock.yaml
Update rspack-chain to v1.2.1 and remove the entry related temporary code.
- https://github.com/rspack-contrib/rspack-chain/releases/tag/v1.2.1
- https://github.com/rspack-contrib/rspack-chain/pull/36
=> chore: remove rspack-chain temporary code

website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Fix return value of `rsbuild.rspackConfigs()`, should be `rspackConfigs`.
https://github.com/web-infra-dev/rsbuild/issues/4463
=> docs: fix return value of `rsbuild.rspackConfigs()`

.github/workflows/ecosystem-ci.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
Add `npm install -g corepack@latest --force` before `corepack enable` to fix corepack key id mismatch issue.
> `--force` to prevent windows install error
https://github.com/nodejs/corepack/issues/612
=> ci(corepack): fix corepack key id mismatch

website/rspress.config.ts
This pull request includes changes to the `website/rspress.config.ts` file to dynamically generate Open Graph images based on the route path. The most important changes include adding a function to determine the appropriate Open Graph image and removing the hardcoded image URL.
- https://rspress.dev/api/config/config-basic#head
=> docs: set Open Graph images based on page routes

packages/core/src/client/hmr.ts, packages/core/src/env.d.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/server/compilerDevMiddleware.ts, packages/core/src/server/devMiddleware.ts, packages/core/src/server/hmrFallback.ts
- Fallback to direct ws connection similar to Vite
Resolves https://github.com/web-infra-dev/rsbuild/issues/4466
=> feat: direct ws connection fallback

pnpm-lock.yaml, website/package.json, website/rspress.config.ts
- Bump Rspress to v1.41.0.
- Enable code blocks search feature.
- https://github.com/web-infra-dev/rspress/releases/tag/v1.41.0
=> docs: update rspress 1.41.0 and enable codeBlocks search

website/docs/en/guide/advanced/environments.mdx, website/docs/en/guide/basic/cli.mdx, website/docs/zh/guide/advanced/environments.mdx, website/docs/zh/guide/basic/cli.mdx
This pull request includes several updates to the documentation for Rsbuild CLI commands. The changes aim to improve clarity and provide more detailed information about the available commands and common options.
=> docs: improve CLI doc structure and add common flags section

e2e/cases/cli/config-loader/index.test.ts, e2e/cases/cli/config-loader/rsbuild.config.mts, e2e/cases/cli/config-loader/src/index.js, packages/core/src/cli/commands.ts, packages/core/src/cli/init.ts, packages/core/src/config.ts, website/docs/en/api/javascript-api/core.mdx, website/docs/en/guide/basic/cli.mdx, website/docs/en/guide/basic/configure-rsbuild.mdx, website/docs/zh/api/javascript-api/core.mdx, website/docs/zh/guide/basic/cli.mdx, website/docs/zh/guide/basic/configure-rsbuild.mdx
This PR adds an new CLI flag `--config-loader native` to support using the native Node.js loader to load configuration files in Rsbuild.
```bash
npx rsbuild build --config-loader native
NODE_OPTIONS="--experimental-strip-types" npx rsbuild build --config-loader native
```
The changes involve updating the CLI commands, configuration options, and documentation to accommodate this new functionality.
- https://nodejs.org/en/learn/typescript/run-natively#running-typescript-natively
- https://github.com/web-infra-dev/rsbuild/issues/3931
=> feat: native runtime support for loading config

packages/core/src/config.ts, packages/core/src/provider/initConfigs.ts
Adding a validation for the `server.base` configuration:
=> fix: validate `server.base` config

e2e/cases/output/clean-dist-path/index.test.ts, packages/core/src/plugins/cleanOutput.ts, website/docs/en/config/output/clean-dist-path.mdx, website/docs/zh/config/output/clean-dist-path.mdx
In development mode, if the value of `dev.writeToDisk` is `false`, Rsbuild will no longer clean up the output directory.
resolve https://github.com/web-infra-dev/rsbuild/issues/4481
=> fix: skip clean in dev mode when writeToDisk is false

.github/renovate.json5
Add `helpers:pinGitHubActionDigests` to let renovate automatically pin action digests. This change should fix all the `Unpinned tag for a non-immutable Action in workflow` alerts in https://github.com/web-infra-dev/rsbuild/security/code-scanning.
- https://docs.renovatebot.com/modules/manager/github-actions/#additional-information
=> chore(renovate): pin GitHub Action digests

README.md, website/docs/en/guide/start/index.mdx
Fixes grammar in the Rsbuild introduction section (which is also included in the project README).
Before:
> Rsbuild shares many similarities with Vite, as they **are** both aim to improve the frontend development experience.
After:
> Rsbuild shares many similarities with Vite, as they both aim to improve the frontend development experience.
* ["Getting Started" -> "Introduction" -> "Comparisons" -> "Vite"](https://rsbuild.dev/guide/start/index#vite)
=> docs: fix grammar in Rsbuild description

packages/core/src/plugins/cache.ts
The `buildDependencies.json` may be an invalid JSON in abnormal cases. This PR adds `try catch` to improve error handling for buildDependencies JSON parsing.
=> fix(cache): error handling for buildDependencies JSON parsing

packages/core/src/index.ts, packages/core/src/plugins/moduleFederation.ts, packages/core/src/plugins/splitChunks.ts, packages/core/src/types/config.ts, packages/plugin-react/src/splitChunks.ts, packages/plugin-vue/src/splitChunks.ts
This PR improves the handling and type definitions related to split chunks and cache groups. The most important changes include removing the `CacheGroup` and `CacheGroups` types, and updating related type references to use `Rspack.*`.
=> refactor(core): simplify CacheGroups types

e2e/cases/cache/index.test.ts, packages/core/src/plugins/cache.ts
The `validateCache` helper is useless when using Rspack, as Rspack can handle buildDependencies changes as expected.
This PR ensures that `validateCache` is only called when using the webpack provider.
=> fix(cache): only validate buildDependencies for webpack

website/docs/en/guide/optimization/inline-assets.mdx
Due to the missing `:::` in markdown, _Inline JS files section_ is included _Do you really need to exclude assets from inlining?_ info part of _Force no Inlining_ section.
https://rsbuild.dev/guide/optimization/inline-assets#inline-js-files
=> docs: fix missing admonition end indicator on inline-assets doc

website/docs/en/guide/optimization/build-performance.mdx, website/docs/zh/guide/optimization/build-performance.mdx
This pull request includes updates to the documentation for improving build performance guides. The changes mainly involve switching code snippets to TypeScript and adding new sections on enabling incremental builds.
=> docs: add guide for incremental build

e2e/cases/cli/config-loader/index.test.ts, packages/core/src/config.ts
Fix failed to use native config loader in Windows.
On Windows, absolute path must be valid `file://` URLs, we should use `pathToFileURL` to process the file path.
=> fix: failed to use native config loader on Windows

packages/core/src/plugins/cache.ts
Rspack's persistent cache is still experimental, this PR adds a log to make that clear.
=> feat(cache): add experimental cache logging

README.md, README.pt-BR.md, README.zh-CN.md, website/docs/en/guide/start/index.mdx, website/docs/zh/guide/start/index.mdx
Enhance performance section across README files. These changes ensure that the performance benefits of Rsbuild are clearly communicated.
=> docs: enhance performance section across README files

e2e/cases/rspack-profile/dev.mjs, e2e/cases/rspack-profile/index.test.ts, e2e/scripts/helper.ts, website/docs/en/guide/debug/build-profiling.mdx, website/docs/zh/guide/debug/build-profiling.mdx
Update rspack profile tips: in development mode, the cpu profile is generated only when exiting the process through `h + Enter` shortcut.
=> docs: update rspack profile tips

packages/core/src/server/socketServer.ts
This pull request includes changes to the `SocketServer` class to update the WebSocket import path and type references.
=> chore: fix ws server type mismatch

e2e/cases/assets/assets-url/index.test.ts, e2e/cases/assets/assets-url/rsbuild.config.ts, e2e/cases/assets/assets-url/src/App.jsx, e2e/cases/print-file-size/basic/index.test.ts, e2e/cases/print-file-size/basic/src/App.jsx, packages/core/src/plugins/fileSize.ts
Skip gzip size calculation for non-compressible assets, this reduces the cost of gzip calculations and avoids misleading.
- before:
- after:
=> perf: skip gzip size calculation for non-compressible assets

packages/core/package.json, pnpm-lock.yaml
=> feat(deps): update Rspack to v1.2.3

.github/workflows/test.yml
Most of the E2E tests in Rsbuild are run by both Rspack and webpack at the same time. This is to check that the functionality of Rspack is correctly aligned with webpack.
This PR splits the webpack E2E testing into an independent workflow to speed up the CI.
We may remove all the webpack related E2E cases in the future.
=> test: split webpack E2E test workflow

packages/core/src/plugins/fileSize.ts, website/docs/en/config/performance/print-file-size.mdx, website/docs/zh/config/performance/print-file-size.mdx
For non-compressible assets (such as images), the gzip size will not be shown in the detailed list, but their original size should be included in the total gzip size calculation.
- https://github.com/web-infra-dev/rsbuild/issues/4537
=> fix: gzipped total file size calculation

packages/core/src/plugins/fileSize.ts, website/docs/en/config/performance/print-file-size.mdx, website/docs/zh/config/performance/print-file-size.mdx
Exclude `.d.ts` type files from file size reporting as they do not affect the page load performance.
=> feat: exclude `.d.ts` files from file size reporting

e2e/cases/cache/index.test.ts, packages/core/src/plugins/cache.ts, packages/core/src/types/config.ts, website/docs/en/config/performance/build-cache.mdx, website/docs/zh/config/performance/build-cache.mdx
`buildDependencies` is an arrays of additional code dependencies for the build. Rspack will use a hash of each of these items and all dependencies to invalidate the filesystem cache.
https://rspack.dev/config/experiments#cachebuilddependencies
=> feat: support `buildCache.buildDependencies` configuration

.vscode/settings.json
Our E2E cases will create some dist-* folders and these should be excluded from the VS Code search.
=> chore(workflow): exclude dist folders from search result

e2e/cases/performance/resource-hints/index.test.ts, packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts, packages/core/src/rspack/preload/helpers/doesChunkBelongToHtml.ts, packages/core/src/types/config.ts, website/docs/en/config/performance/preload.mdx, website/docs/zh/config/performance/preload.mdx
By default, if a resource has been added to the current HTML via a script tag, it will not be preloaded additionally.
When set `preload.dedupe` to `false`, Rsbuild will generate preload tags for all eligible resources, even if these resources already exist in the HTML.
```js
performance: {
preload: {
dedupe: false,
},
},
};
```
=> feat: support generate preload link with duplicate

e2e/cases/plugin-api/plugin-before-start-dev-server-hook/index.test.ts, e2e/cases/plugin-api/plugin-before-start-dev-server-hook/src/index.js, e2e/cases/server/setup-middlewares/index.test.ts, packages/core/src/server/devServer.ts, packages/core/src/server/getDevMiddlewares.ts, packages/core/src/server/watchFiles.ts, packages/core/src/types/hooks.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/en/plugins/dev/hooks.mdx, website/docs/en/shared/onBeforeStartDevServer.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/plugins/dev/hooks.mdx, website/docs/zh/shared/onBeforeStartDevServer.mdx
Expose the dev server instance for the  `onBeforeStartDevServer` hook, this makes it easier for the Rsbuild plugins to add a custom middleware.
```js
const myPlugin = {
setup(api) {
api.onBeforeStartDevServer(({ server, environments }) => {
console.log('before starting dev server.');
console.log('the server is ', server);
console.log('the environments contexts are: ', environments);
});
},
};
```
```js
const myPlugin = {
name: 'test-plugin',
setup(api) {
api.onBeforeStartDevServer({ server }) => {
server.middlewares.use((_req, _res, next) => {
count++;
next();
});
});
},
};
```
=> feat: expose dev server instance for `onBeforeStartDevServer` hook

e2e/cases/server/ssr-type-module/index.test.ts, e2e/cases/server/ssr-type-module/package.json, e2e/cases/server/ssr-type-module/rsbuild.config.ts, e2e/cases/server/ssr-type-module/src/App.css, e2e/cases/server/ssr-type-module/src/App.tsx, e2e/cases/server/ssr-type-module/src/env.d.ts, e2e/cases/server/ssr-type-module/src/index.server.tsx, e2e/cases/server/ssr-type-module/src/index.tsx, e2e/cases/server/ssr-type-module/src/test.ts, e2e/cases/server/ssr-type-module/template.html, e2e/cases/server/ssr/index.test.ts, e2e/package.json, packages/core/src/server/environment.ts, packages/core/src/server/runner/basic.ts, packages/core/src/server/runner/cjs.ts, packages/core/src/server/runner/esm.ts, packages/core/src/server/runner/index.ts, packages/core/src/server/runner/type.ts, pnpm-lock.yaml
Only rspack outputs require proxy import, so only [experiments.outputModule](https://rspack.dev/config/experiments#experimentsoutputmodule) is required for loading rspack esm outputs in runner, no `.mjs` suffix is ​​required.
=> fix(server): remove `.mjs` suffix check when loading ESM module in runner

website/docs/en/plugins/dev/hooks.mdx, website/docs/zh/plugins/dev/hooks.mdx
Add example on how to access the `server` instance in other plugin hooks by storing it through `api.onBeforeStartDevServer`.
=> docs: add example for accessing dev server in plugin hooks

packages/compat/webpack/src/createCompiler.ts, packages/compat/webpack/src/webpackConfig.ts, packages/core/src/configChain.ts, packages/core/src/createRsbuild.ts, packages/core/src/hooks.ts, packages/core/src/initPlugins.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/provider/initConfigs.ts, packages/core/src/provider/rspackConfig.ts, packages/core/src/server/devServer.ts, packages/core/src/server/prodServer.ts, packages/core/src/types/plugin.ts, packages/core/tests/createAsyncHook.test.ts, packages/core/tests/hooks.test.ts
This PR distinguishes the `call` method of Rsbuild's internal hook into `callBatch` and `callChain` to prevent some hook return values from affecting other hooks.
- `callBatch`: Each callback receives the original parameters, and their results don't affect subsequent callbacks. For example, `onBeforeBuild` and `onAfterBuild` hooks.
- `callChain`: Passing the result of each callback as the first argument to the next callback in the chain. If a callback returns undefined, the original arguments will be passed to the next callback. For example, `modifyRspackConfig` and `modifyRsbuildConfig` hooks.
=> fix: prevent some hook return values from affecting other hooks

packages/core/src/server/devServer.ts, website/docs/en/api/javascript-api/dev-server-api.mdx, website/docs/zh/api/javascript-api/dev-server-api.mdx
Expose `httpServer` in RsbuildDevServer, this can be used to set up the Rspack lazy compilation backend server.
Example:
```js
const lazyCompilationServerPlugin = (): RsbuildPlugin => {
return {
name: 'lazy-compilation-server-plugin',
setup(api) {
let devServer: RsbuildDevServer;
api.onBeforeStartDevServer(({ server }) => {
devServer = server;
});
api.modifyRspackConfig((config) => {
const { httpServer } = devServer || {};
if (!httpServer) {
return;
}
config.experiments ||= {};
config.experiments.lazyCompilation = {
backend: {
server: () => httpServer,
},
};
});
},
};
};
```
TODO: Consider adding a new `server.middlewareMode` config to prevent the unnecessary `createHttpServer` call.
=> feat: expose httpServer in RsbuildDevServer

packages/core/src/types/plugin.ts
This pull request includes changes to improve type definitions for hooks.  This ensures that the return type of `callBatch` is automatically inferred.
=> fix: type infer for plugin hooks

e2e/cases/plugin-api/plugin-before-start-dev-server-hook/index.test.ts, packages/core/src/server/devServer.ts, packages/core/src/server/getDevMiddlewares.ts, packages/core/src/types/hooks.ts
Allow onBeforeStartDevServer hook to return a post callback, the post callback will be called when the default middlewares are registered:
```js
const plugin: RsbuildPlugin = {
name: 'test-plugin',
setup(api) {
api.onBeforeStartDevServer(async ({ server }) => {
server.middlewares.use((req, res, next) => {
if (req.url === '/test.html') {
res.end('Hello, world!');
} else {
next();
}
});
// the post callback will be called when the default middlewares are registered
return () => {
server.middlewares.use((req, res, next) => {
if (req.url === '/test2.html') {
res.end('Hello, world2!');
} else {
next();
}
});
};
});
},
};
```
Documentation will be updated later.
=> feat: allow onBeforeStartDevServer hook to return post callback

website/docs/en/api/javascript-api/instance.mdx, website/docs/en/plugins/dev/hooks.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/plugins/dev/hooks.mdx
Add guide for register middlewares in the `onBeforeStartDevServer` hook.
https://github.com/web-infra-dev/rsbuild/pull/4573
=> docs: register middlewares in onBeforeStartDevServer

e2e/cases/server/proxy/index.test.ts, packages/core/src/server/proxy.ts
use `http-proxy-middleware` default error handler.
fix: https://github.com/web-infra-dev/rsbuild/issues/4563
=> fix: should handle proxy error correctly

packages/core/src/plugins/output.ts, packages/core/tests/output.test.ts
When using Rsbuild without development server(e.g.: `rsbuild.initConfig()` or `rsbuild inspect`), the `publicPath` is not correct since we are using `context.devServer?.port || DEFAULT_PORT`
This patch fix this to use `server.port` when needed.
A fix of #3098.
=> fix(core): respect `server.port` when replacing `<port>`

packages/core/src/helpers/format.ts
Add the npm link to plugin hints to help users access the plugin:
=> feat: add npm link to plugin hints

e2e/cases/rsdoctor/index.test.ts
We can now enable Rsdoctor cases on Windows, as we have migrated all E2E cases to ESM.
https://github.com/web-infra-dev/rsbuild/pull/4579
=> test(e2e): enable Rsdoctor cases on Windows

packages/compat/plugin-webpack-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-assets-retry/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-vue/package.json
* feat: expose `httpServer` in RsbuildDevServer by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4570
* feat: allow `onBeforeStartDevServer` hook to return post callback by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4573
* feat: add npm link to plugin hints by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4583
* fix: prevent some hook return values from affecting other hooks by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4569
* fix: type infer for plugin hooks by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4571
* fix: should handle proxy error correctly by @9aoy in https://github.com/web-infra-dev/rsbuild/pull/4577
* fix(core): respect `server.port` when replacing `<port>` by @colinaaa in …
=> release: v1.2.9

e2e/cases/server/fallback/index.test.ts, e2e/cases/server/fallback/src/index.js, packages/core/src/server/devServer.ts, packages/core/src/server/getDevMiddlewares.ts, packages/core/src/server/middlewares.ts, packages/core/src/server/prodServer.ts
Updating the `optionsFallbackMiddleware` middleware registration order,  options fallback should only works in rsbuild server mode
=> fix(server): options fallback should only works in rsbuild server mode

website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Improve stats usage example in JavaScript API documentation, should add `all: false` to improve performance.
=> docs: improve stats usage example in JavaScript API documentation

packages/core/package.json, pnpm-lock.yaml
Update Rspack to v1.2.5.
- https://github.com/web-infra-dev/rspack/releases
=> feat(deps): update Rspack to v1.2.5

.github/workflows/test.yml
Configure Node.js memory limit in GitHub Actions to try to fix timeout.
- https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners#supported-runners-and-hardware-resources
=> chore(ci): configure Node.js memory limit in GitHub Actions

packages/core/src/plugins/css.ts
When running Rsbuild E2E tests, dozens of postcss configurations were stored in `postcsssrcCache`, which caused memory usage.
We can move `postcssrcCache` to the plugin scope to avoid memory leaks.
=> fix: postcssrc cache may cause memory leak

e2e/cases/plugin-api/plugin-hooks/environments.test.ts, e2e/cases/plugin-api/plugin-hooks/index.test.ts
Compile is async in dev, so the execution order of AfterStartDevServer and the compile hooks is uncertain.
=> test: fix flaky hooks order case

packages/core/package.json, pnpm-lock.yaml
This reverts commit 7a8c8daa1bfd6bd372c3833a94b5092216fd4bf9.
Rspack v1.2.4 and v1.2.5 break unplugin, for example `unplugin-vue-components` in https://github.com/vant-ui/vant-demo/tree/master/vant/rsbuild
Revert the version before Rspack releases a new patch.
=> Revert "feat(deps): update Rspack to v1.2.5 (#4591)"

e2e/cases/create-rsbuild/jsTemplates.test.ts, e2e/cases/create-rsbuild/tsTemplates.test.ts, packages/create-rsbuild/src/index.ts, packages/create-rsbuild/template-react18-js/package.json, packages/create-rsbuild/template-react18-js/rsbuild.config.mjs, packages/create-rsbuild/template-react18-js/src/App.css, packages/create-rsbuild/template-react18-js/src/App.jsx, packages/create-rsbuild/template-react18-js/src/index.jsx, packages/create-rsbuild/template-react18-ts/package.json, packages/create-rsbuild/template-react18-ts/rsbuild.config.ts, packages/create-rsbuild/template-react18-ts/src/App.css, packages/create-rsbuild/template-react18-ts/src/App.tsx, packages/create-rsbuild/template-react18-ts/src/env.d.ts, packages/create-rsbuild/template-react18-ts/src/index.tsx, packages/create-rsbuild/template-react18-ts/tsconfig.json, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
Add React 18 templates as some community libraries and users have not caught up with React 18 yet.
resolve https://github.com/web-infra-dev/rsbuild/issues/4595
=> feat(create-rsbuild): add React 18 templates

packages/core/src/server/compilerDevMiddleware.ts, packages/core/src/server/socketServer.ts
Improve socket server connection handling and cleanup to avoid potential memory leaks:
- Call `this.wsServer.close` when closing the ws server.
- Reset all properties when closing the ws server.
- Use `setTimeout` instead of `setInternal` for heartbeats checking.
=> feat: improve socket server connection handling and cleanup

website/docs/en/api/javascript-api/dev-server-api.mdx, website/docs/en/community/releases/v0-5.mdx, website/docs/en/config/server/middleware-mode.mdx, website/docs/en/guide/migration/vite.mdx, website/docs/zh/api/javascript-api/dev-server-api.mdx, website/docs/zh/community/releases/v0-5.mdx, website/docs/zh/config/server/middleware-mode.mdx, website/docs/zh/guide/migration/vite.mdx
This pull request includes updates to documentations to add support for the `server.middlewareMode` configuration. The changes include adding new examples and updating references
- https://github.com/web-infra-dev/rsbuild/pull/4614
=> docs: add `server.middlewareMode` config

e2e/cases/plugin-api/plugin-hooks-environment/index.test.ts, e2e/cases/plugin-api/plugin-hooks-environment/src/index.js, e2e/cases/plugin-api/plugin-hooks/index.test.ts
Fix the print file size warnings for plugin hook E2E cases:
=> test(e2e): fix warnings for plugin hook cases

packages/core/rslib.config.ts
Specify Rslib build id to make the build logs clearer:
Ref: https://lib.rsbuild.dev/config/lib/id
=> chore(build): specify Rslib build id

.github/renovate.json5
Update Renovate configuration with rules:
- Group Module Federation packages
- Ignore the React 18 and Vue 2 templates
- Allow to update pnpm non-patch version
=> chore(deps): update Renovate configuration with rules

website/docs/en/api/javascript-api/instance.mdx, website/docs/en/guide/framework/react.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/guide/framework/react.mdx
Add React Router to React guide, and link to [rsbuild-plugin-react-router](https://github.com/rspack-contrib/rsbuild-plugin-react-router).
=> docs: add React Router to React guide

website/docs/en/guide/framework/react.mdx, website/docs/en/guide/start/index.mdx, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/framework/react.mdx, website/docs/zh/guide/start/index.mdx, website/docs/zh/guide/start/quick-start.mdx, website/theme/components/Step.tsx
This pull request includes several updates to the quick start documentation. The most important changes include updates to the React documentation, improvements to the quick start guide, and modifications to the `Step` component to handle external links.
=> docs: update quick start guide content

website/docs/en/guide/basic/tailwindcss-v3.mdx, website/docs/zh/guide/basic/tailwindcss-v3.mdx
correct sample code to match actual postcss config interface
[current tailwind v3 guide](https://rsbuild.dev/guide/basic/tailwindcss-v3)
=> docs: correct wrong example in postcss v3 configuration

e2e/cases/cli/shortcuts/index.test.ts, e2e/cases/config/inspect-config/debug.test.ts, e2e/cases/config/inspect-config/index.test.ts, e2e/cases/rspack-profile/index.test.ts, packages/core/src/client/hmr.ts, packages/core/src/config.ts, packages/core/src/logger.ts, packages/core/src/plugins/rspackProfile.ts, packages/core/src/server/helper.ts, packages/core/src/server/restart.ts, packages/plugin-assets-retry/rslib.config.ts, website/docs/en/guide/advanced/environments.mdx, website/docs/en/guide/basic/cli.mdx, website/docs/en/guide/basic/configure-rsbuild.mdx, website/docs/en/guide/debug/debug-mode.mdx, website/docs/en/guide/faq/features.mdx, website/docs/zh/guide/advanced/environments.mdx, website/docs/zh/guide/basic/cli.mdx, website/docs/zh/guide/basic/configure-rsbuild.mdx, website/docs/zh/guide/debug/debug-mode.mdx, website/docs/zh/guide/faq/features.mdx
This pull request includes several changes to enforce a consistent logging message case convention across the codebase. 
```js
/**
* Logging message case convention:
*
* Info, ready, success and debug messages:
* - Start with lowercase
* - Example: "info  build started..."
*
* Errors and warnings:
* - Start with uppercase
* - Example: "error  Failed to build"
*
* This convention helps distinguish between normal operations
* and important alerts that require attention.
*/
```
=> chore(style): standardize logging messages

e2e/cases/javascript-api/load-env/index.test.ts, packages/core/src/loadEnv.ts, website/docs/en/api/javascript-api/core.mdx, website/docs/zh/api/javascript-api/core.mdx
Add a new `processEnv` option to `loadEnv` to specify a target object to store environment variables.
resolve https://github.com/web-infra-dev/rsbuild/issues/4638
=> feat: add `processEnv` option to loadEnv

website/docs/en/config/html/app-icon.mdx, website/docs/en/plugins/list/plugin-assets-retry.mdx, website/docs/zh/plugins/list/plugin-assets-retry.mdx
Improve formatting for plugin-assets-retry and app-icon.
https://github.com/web-infra-dev/rsbuild/pull/4643
=> docs: improve formatting for plugin-assets-retry and app-icon

e2e/cases/cli/config-loader/index.test.ts
Conditionally skip config loader test on older Node.js versions to fix Rspack ecosystem CI.
https://github.com/rspack-contrib/rspack-ecosystem-ci/actions/runs/13515028079/job/37762789136
=> test: conditionally skip config loader test on older Node.js versions

packages/core/src/types/config.ts, website/docs/en/config/resolve/alias.mdx, website/docs/zh/config/resolve/alias.mdx
Add detailed explanation for alias differences with Rspack.
resolve https://github.com/web-infra-dev/rsbuild/issues/4650
=> docs: alias differences with Rspack

packages/core/package.json, pnpm-lock.yaml
Update Rspack to v1.2.6.
https://github.com/web-infra-dev/rspack/releases/tag/v1.2.6
=> feat(deps): update Rspack to v1.2.6

packages/core/src/server/socketServer.ts
`sendStats` (stats.toJson) should not be called when no socket connection
https://github.com/web-infra-dev/rsbuild/issues/4589
=> perf(server): sendStats should not be called when no socket connection

packages/core/src/cli/init.ts, packages/core/src/helpers/fs.ts, packages/core/src/plugins/basic.ts, packages/core/src/plugins/html.ts, packages/core/src/rspack/RsbuildHtmlPlugin.ts
- remove unless `path.resolve` call from `devtoolModuleFilenameTemplate` callback.
- use `path.join` instead of `path.resolve` for path concatenation (it's faster).
- https://www.reddit.com/r/node/comments/1adklxy/any_reason_to_use_pathjoin_over_pathresolve/
=> perf: remove unless `path.resolve` call

e2e/cases/plugin-api/plugin-process-assets-by-environments/index.test.ts, packages/core/src/initPlugins.ts
Use `continue` instead of  `return` when filter processAssets hook handler.
=> fix: processAssets hook filter error

e2e/cases/html/favicon/index.test.ts, packages/core/src/rspack/RsbuildHtmlPlugin.ts
Fix a bug introduced by https://github.com/web-infra-dev/rsbuild/pull/4669
https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions/runs/13562976143/job/37909714106
=> fix: absolute path for favicon configuration

packages/core/src/helpers/index.ts, packages/core/src/rspack/RsbuildHtmlPlugin.ts
Improve favicon handling with better error logging, now favicon errors can be displayed on the error overlay.
=> fix: improve favicon handling with better error logging

packages/core/package.json, packages/core/prebundle.config.mjs, pnpm-lock.yaml
Bump `rsbuild-dev-middleware` to v0.2.0 to unify logger style.
- before:
- after:
- https://github.com/rspack-contrib/rsbuild-dev-middleware/pull/85
=> fix(deps): bump rsbuild-dev-middleware to unify logger style

website/docs/en/guide/framework/react.mdx, website/docs/en/plugins/list/plugin-react.mdx, website/docs/zh/guide/framework/react.mdx, website/docs/zh/plugins/list/plugin-react.mdx
This pull request enhances the documentation for customizing JSX guides. It provides detailed instructions on configuring the JSX runtime using `@rsbuild/plugin-react` and includes examples for both automatic and classic runtimes.
- https://github.com/web-infra-dev/rsbuild/issues/4654
=> docs: add guide for customizing JSX in React

e2e/cases/server/overlay-type-errors/tsconfig.json, examples/node/tsconfig.json, examples/react/tsconfig.json, examples/vue/tsconfig.json, packages/create-rsbuild/template-lit-ts/tsconfig.json, packages/create-rsbuild/template-preact-ts/tsconfig.json, packages/create-rsbuild/template-react-ts/tsconfig.json, packages/create-rsbuild/template-react18-ts/tsconfig.json, packages/create-rsbuild/template-solid-ts/tsconfig.json, packages/create-rsbuild/template-svelte-ts/tsconfig.json, packages/create-rsbuild/template-vanilla-ts/tsconfig.json, packages/create-rsbuild/template-vue2-ts/tsconfig.json, packages/create-rsbuild/template-vue3-ts/tsconfig.json, scripts/config/tsconfig-node16.json, scripts/config/tsconfig.json
SchemaStore have updated `moduleResolution` value casing. let we align it.
https://github.com/SchemaStore/schemastore/pull/4210
https://github.com/vitejs/vite/pull/18774
=> fix(create-rsbuild): update tsconfig `moduleResolution` to lowercase

packages/core/package.json, pnpm-lock.yaml
Revert @rspack/core to v1.2.5 to fix HMR.
https://github.com/web-infra-dev/rsbuild/issues/4682
=> fix(deps): revert @rspack/core to v1.2.5 to fix HMR

e2e/cases/cli/build-watch-restart/index.test.ts, e2e/cases/cli/build-watch/index.test.ts, e2e/cases/cli/reload-config/index.test.ts, e2e/cases/cli/reload-env/index.test.ts, e2e/cases/cli/shortcuts/index.test.ts, e2e/cases/cli/watch-files-array/index.test.ts, e2e/cases/cli/watch-files/index.test.ts, e2e/cases/rspack-profile/index.test.ts, e2e/cases/server/hmr-with-error/index.test.ts, e2e/cases/server/overlay-type-errors/index.test.ts, e2e/cases/server/overlay/index.test.ts, e2e/scripts/helper.ts
This pull request focuses on improving the reliability and readability of the E2E tests by replacing the `awaitFileExists` helper with the `expectFile` function and replacing `waitFor` with `expectPoll` in various test cases.
=> test(e2e): replace custom helper with `expect.poll`

README.md, README.pt-BR.md, README.zh-CN.md, examples/README.md, website/docs/en/api/javascript-api/dev-server-api.mdx, website/docs/en/community/index.mdx, website/docs/en/config/module-federation/options.mdx, website/docs/en/guide/advanced/environments.mdx, website/docs/en/guide/advanced/module-federation.mdx, website/docs/en/guide/advanced/ssr.mdx, website/docs/en/guide/framework/react.mdx, website/docs/en/guide/migration/cra.mdx, website/docs/en/guide/start/index.mdx, website/docs/zh/api/javascript-api/dev-server-api.mdx, website/docs/zh/community/index.mdx, website/docs/zh/config/module-federation/options.mdx, website/docs/zh/guide/advanced/environments.mdx, website/docs/zh/guide/advanced/module-federation.mdx, website/docs/zh/guide/advanced/ssr.mdx, website/docs/zh/guide/framework/react.mdx, website/docs/zh/guide/migration/cra.mdx, website/docs/zh/guide/start/index.mdx
Update rspack-examples references  to rstack-examples.
- https://github.com/rspack-contrib/rstack-examples
=> docs: update rspack-examples references to rstack-examples

packages/core/src/plugins/moduleFederation.ts
Add all `@module-federation/*` packages to `source.include` to avoid browser compatibility issues.
This change is to fix a syntax issue introduced in `@module-federation/webpack-bundler-runtime` in 0.9.1.
- https://github.com/module-federation/core/pull/3565
- https://github.com/web-infra-dev/rsbuild/actions/runs/13622050663/job/38073072909?pr=4690#step:7:920
=> fix(mf): add more MF packages to `source.include`

packages/core/src/server/devServer.ts, packages/core/src/server/gracefulShutdown.ts, packages/core/src/server/prodServer.ts
This PR introduces support for graceful shutdown:
- handling of SIGTERM signals (for container orchestration environments)
- handling of CTRL+D in non-CI environments
- support for reference counting for multiple servers
=> feat(server): add graceful shutdown support

e2e/cases/performance/single-vendor-splitting/index.test.ts, e2e/cases/performance/single-vendor-splitting/rsbuild.config.ts, e2e/cases/performance/single-vendor-splitting/src/App.jsx, e2e/cases/performance/single-vendor-splitting/src/index.js, packages/core/src/plugins/splitChunks.ts, packages/core/src/types/config.ts
Fix the `chunkSplit.forceSplitting` option not work when `chunkSplit.stategy` is `single-vendor`.
resolve https://github.com/web-infra-dev/rsbuild/issues/4697
=> fix: `forceSplitting` not work with `single-vendor`

e2e/cases/vue/with-react/index.test.ts, e2e/cases/vue/with-react/rsbuild.config.ts, e2e/cases/vue/with-react/src/A.vue, e2e/cases/vue/with-react/src/B.vue, e2e/cases/vue/with-react/src/index.js, packages/plugin-vue/src/index.ts, pnpm-lock.yaml
Ensure that the `VueLoaderPlugin` is applied before the `ReactFastRefreshPlugin`, otherwise the `VueLoaderPlugin` will throw an error for `builtin:react-refresh-loader`.
The root cause is that `VueLoaderPlugin` ignored the `include` option of rules. See https://github.com/vuejs/vue-loader/blob/main/src/pluginWebpack5.ts#L319-L321
https://github.com/web-infra-dev/rsbuild/discussions/4712
=> fix(plugin-vue): order problem with pluginReact

e2e/cases/css/export-type-string/index.test.ts, e2e/cases/css/export-type-string/rsbuild.config.ts, e2e/cases/css/export-type-string/src/a.scss, e2e/cases/css/export-type-string/src/b.module.scss, e2e/cases/css/export-type-string/src/index.js, e2e/cases/output/manifest-single-vendor/index.test.ts, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap, packages/core/src/plugins/css.ts, packages/core/src/plugins/output.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/output.test.ts.snap, pnpm-lock.yaml
When `cssLoader.exportType` is configured to `string`, the CSSExtractRspack should not be used, see https://github.com/webpack-contrib/css-loader?tab=readme-ov-file#string-3.
```ts
tools: {
cssLoader: {
exportType: 'string',
modules: {
namedExport: true,
},
},
},
});
```
resolve https://github.com/web-infra-dev/rsbuild/issues/4689
=> feat(css): support `cssLoader.exportType` as `string`

website/docs/en/config/output/filename.mdx, website/docs/zh/config/output/filename.mdx
This pull request includes updates to the filename.mdx files to enhance the documentation with additional tips and information.
=> docs: improve filename configuration

packages/core/src/types/hooks.ts, website/docs/en/api/javascript-api/environment-api.mdx, website/docs/zh/api/javascript-api/environment-api.mdx
Adding detailed comments to the `EnvironmentContext` properties and refining the descriptions in the documentation.
=> docs: add JSDoc for EnvironmentContext

packages/core/src/plugins/fileSize.ts
Should not display the `Gzip` header if all assets are not compressible.
=> fix: improve file size gzip header rendering

packages/core/src/config.ts
The `watcher.close` method returns a Promise and should be awaited.
=> fix: await watcher close before restart

e2e/cases/cli/watch-files/index.test.ts
The `watch-files/index.test.ts` contains three flaky cases. This PR makes the next two cases stable, but the first case is still unstable and needs further investigation.
=> test(e2e): fix flaky watch-files cases

e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts
Improve plugin watch hook test reliability, replace `setTimeout` with `expectFile`.
=> test(e2e): improve plugin watch hook test reliability

e2e/cases/server/overlay-type-errors/index.test.ts, packages/core/src/server/overlay.ts, packages/core/src/server/socketServer.ts
This PR adds support for opening relative paths on error overlay.
https://github.com/rspack-contrib/rsbuild-plugin-type-check/issues/19
=> feat: allow opening relative paths on error overlay

packages/core/tests/overlay.test.ts
Add some test cases for the `convertLinksInHtml` method.
https://github.com/web-infra-dev/rsbuild/pull/4739
=> test(ut): add test cases for overlay links

pnpm-lock.yaml, website/package.json, website/theme/index.tsx
Update Rspress to v2.0.0-alpha.0
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-alpha.0
=> chore(deps): update Rspress to v2.0.0-alpha.0

packages/core/src/helpers/path.ts, packages/core/src/server/overlay.ts, packages/core/tests/overlay.test.ts
Display relative paths on error overlay to improve readability.
- before:
- after:
=> feat: display relative paths on error overlay

packages/core/prebundle.config.mjs, packages/core/src/provider/rspackConfig.ts, packages/core/src/types/config.ts, packages/core/src/types/plugin.ts
Bundle `webpack-merge` to reduce `require` calls. This should improve startup performance slightly.
=> perf: bundle webpack-merge for faster startup

packages/core/src/provider/createCompiler.ts
Print environment name only when using multi compiler. This can keep the logs clean if there is only one environment.
=> fix: print environment name only when using multi compiler

e2e/package.json, pnpm-lock.yaml
Update Rsdoctor to 1.0.0-rc.0.
https://github.com/web-infra-dev/rsdoctor/releases/tag/v1.0.0-rc.0
=> chore(deps): update Rsdoctor to 1.0.0-rc.0

packages/core/package.json, pnpm-lock.yaml
Update Rspack to v1.2.8.
- https://github.com/web-infra-dev/rspack/releases
=> feat(deps): update Rspack to v1.2.8

website/docs/en/config/dev/asset-prefix.mdx, website/docs/en/config/output/asset-prefix.mdx, website/docs/zh/config/dev/asset-prefix.mdx, website/docs/zh/config/output/asset-prefix.mdx
Add dynamic asset prefix guide to documentation.
https://github.com/web-infra-dev/rspack/pull/9629
=> docs: add dynamic asset prefix guide

packages/core/src/server/runner/basic.ts, packages/core/src/server/runner/cjs.ts
remove useless `runInNewContext` option in server runner.
=> chore(server): remove useless runInNewContext option

website/docs/en/guide/basic/tailwindcss.mdx, website/docs/zh/guide/basic/tailwindcss.mdx
Add Tailwind CSS v4 compatibility tip for other CSS preprocessors.
https://tailwindcss.com/docs/compatibility#sass-less-and-stylus
=> docs: add Tailwind CSS v4 compatibility tip for preprocessors

packages/compat/webpack/src/build.ts, packages/core/src/cli/commands.ts, packages/core/src/provider/build.ts
Outputting two lines of build error logs seems a bit redundant. This PR adds a check to avoid this.
=> fix: simplify build error logs

packages/core/src/cli/commands.ts, website/docs/en/guide/basic/cli.mdx, website/docs/zh/guide/basic/cli.mdx
Allow to run `rsbuild` without sub-command to trigger dev, this will make it easier to start a development server locally.
```bash
npx rsbuild 
```
=> feat(CLI): allow to run without sub-command to trigger dev

packages/core/src/createContext.ts, packages/core/src/createRsbuild.ts, packages/core/src/types/rsbuild.ts, scripts/test-helper/src/index.ts, website/docs/en/api/javascript-api/core.mdx, website/docs/zh/api/javascript-api/core.mdx
This is one of the prerequisites for implementing the `server.restart` method.
To allow the `loadConfig` method to be called again when restarting the server, we need to allow `createRsbuild` to call `loadConfig`. Therefore, this PR supports `creatingRsbuild`'s `rsbuildOptions` to pass in an async function to dynamically load the configuration.
```ts
import { createRsbuild, loadConfig } from '@rsbuild/core';
const rsbuild = await createRsbuild({
rsbuildConfig: async () => {
const { content } = await loadConfig();
someFunctionToUpdateConfig(content);
return content;
},
});
```
=> feat: support async function for rsbuildConfig in createRsbuild options

packages/core/src/cli/init.ts
Extract config loader function and passing it to the `rsbuildConfig` option of `createRsbuild`.
See https://github.com/web-infra-dev/rsbuild/pull/4778 for background.
=> refactor(CLI): extract config loader function

e2e/cases/javascript-api/build-and-load-env/.env, e2e/cases/javascript-api/build-and-load-env/.env.prod, e2e/cases/javascript-api/build-and-load-env/index.test.ts, e2e/cases/javascript-api/build-and-load-env/src/index.js, packages/core/src/cli/init.ts, packages/core/src/createRsbuild.ts, packages/core/src/types/rsbuild.ts
Although Rsbuild's JavaScript API already provides the `loadEnv` method, combining `loadEnv` with `createRsbuild` is still somewhat cumbersome.
This PR introduces a new `loadEnv` option for `createRsbuild` to simplify the logic of env loading.
```js
const rsbuild = createRsbuild({ loadEnv: true });
```
This is equivalent to:
```js
const envs = loadEnv();
const config = {
// some options
};
config.source.define = {
...envs.publicVars,
...config.source.define,
};
// watch the env files
config.dev.watchFiles = [
...(config.dev.watchFiles ? castArray(config.dev.watchFiles) : []),
{
paths: envs.filePaths,
type: 'reload-server',
},
];
// add env files to build dependencies, so that the build cache
// can be invalidated when the env files are changed.
if (config.performance?.buildCache && …
```
=> feat: integrate env variable loading into createRsbuild options

packages/core/src/server/socketServer.ts
Handle null stats JSON in Socket server.
If the previous compilation is removed on the Rust side, `stats.toJson` gets a `null` instead of an object.
```bash
Failed to get stats due to error: Unable to access compilation with id = CompilationId(1) now. The compilation have been removed on the Rust side. The latest compilation id is CompilationId(4), are you trying to access the stats from the previous compilation?
file:///user/app/node_modules/.pnpm/@rsbuild+core@1.2.18/node_modules/@rsbuild/core/dist/index.js:5275
if (statsJson.entrypoints) for (let entrypoint of Object.values(statsJson.entrypoints)){
^
TypeError: Cannot read properties of null (reading 'entrypoints')
at SocketServer.sendStats 
```
https://discord.com/channels/977448667919286283/1167025132905173063/1349740225999405218
=> fix: handle null stats JSON in Socket server

packages/core/src/server/helper.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/en/plugins/dev/hooks.mdx, website/docs/en/shared/onCloseDevServer.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/plugins/dev/hooks.mdx, website/docs/zh/shared/onCloseDevServer.mdx
Update the `StartServerResult` type and related documentation to provide more detailed information for server close method.
=> docs: update examples for server close method

e2e/cases/output/copy/index.test.ts, packages/core/src/mergeConfig.ts
should merge copy config correctly when copy config type difference.
```ts
// config1 
output: {
copy: {
patterns: [
{
from: '../../../assets/icon.png',
},
],
},
},
// config2
output: {
copy: [
{
from: '../../../assets/image.png',
},
],
},
```
expect:
```ts
output: {
copy: {
patterns: [
{
from: '../../../assets/icon.png',
},
{
from: '../../../assets/image.png',
},
],
},
},
```
actual:
```ts
output: {
copy: [
{
patterns: [
{
from: '../../../assets/icon.png',
},
],
},
{
from: '../../../assets/image.png',
},
],
}
```
=> fix: should merge copy config correctly when copy config type is different

e2e/cases/cache/cache-directory/index.test.ts, e2e/cases/cache/cache-directory/src/index.js
Add E2E cases for `buildCache.cacheDirectory` config.
related: https://github.com/web-infra-dev/rsbuild/pull/4790
=> test(e2e): add cases for `buildCache.cacheDirectory`

packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/core.mdx, website/docs/zh/api/javascript-api/core.mdx
Add `loadEnv` option in `createRsbuild` method.
- https://github.com/web-infra-dev/rsbuild/pull/4783
=> docs: add `loadEnv` option in `createRsbuild` method

website/theme/index.scss
Apply new theme colors to the documentation site:
- New brand color
- Default code block color of Rspress
- Clean up unused variables
The same as Rspack: https://github.com/web-infra-dev/rspack/pull/9689
=> docs: apply new theme colors to the documentation site

e2e/cases/preact/prefresh-context/index.test.ts, e2e/cases/preact/prefresh-disabled/index.test.ts, e2e/cases/preact/prefresh/index.test.ts, e2e/cases/solid/hmr/index.test.ts, e2e/scripts/shared.ts, packages/compat/plugin-webpack-swc/tests/plugin.test.ts, packages/compat/webpack/tests/initConfigs.test.ts, packages/core/src/client/overlay.ts, packages/core/src/pluginManager.ts, packages/core/src/plugins/fileSize.ts, packages/core/src/plugins/manifest.ts, packages/core/tests/mergeConfig.test.ts, packages/create-rsbuild/template-vanilla-ts/src/index.ts, website/docs/en/config/html/tags.mdx, website/docs/en/config/index.mdx, website/docs/zh/config/html/tags.mdx
Improve code safety and consistency by replacing non-null assertion operators with optional chaining, and by ensuring proper initialization of object properties.
=> fix: update null checks to improve type safety

packages/core/src/client/overlay.ts
Clear error overlay immediately to avoid multiple error overlay instances.
The overlay animation is only needed when the user manually clicks the close icon
Fix the flaky E2E case:
=> fix(overlay): avoid multiple error overlay instances

website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Update documentation to add the `environment` option to `rsbuild.getPlugins` to specify an environment from which to retrieve plugins.
=> docs: `getPlugins` can accept `environment` option

e2e/cases/cache/build-dependencies/index.test.ts, e2e/cases/cache/cache-digest/index.test.ts, e2e/cases/cache/cache-directory/index.test.ts, e2e/cases/cli/build-watch-restart/index.test.ts, e2e/cases/cli/build-watch/index.test.ts, e2e/cases/cli/function-config/index.test.ts, e2e/cases/cli/load-import-meta-env/index.test.ts, e2e/cases/cli/load-process-env/index.test.ts, e2e/cases/cli/reload-config/index.test.ts, e2e/cases/cli/reload-env/index.test.ts, e2e/cases/cli/watch-files-array/index.test.ts, e2e/cases/cli/watch-files/index.test.ts, e2e/cases/config/inspect-config/index.test.ts, e2e/cases/node-addons/index.test.ts, e2e/cases/output/clean-dist-path/index.test.ts, e2e/cases/plugin-api/plugin-after-build-hook/index.test.ts, e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts, e2e/cases/plugin-api/plugin-on-exit-hook/index.test.ts, e2e/cases/resolve/extension-alias-js/index.test.ts
`fse.remove` is less verbose and can avoid exceptions caused by forgetting to add `force: true`.
Fix flaky cases like:
=> test(e2e): replace fs.rmSync with async remove from fs-extra

README.md, README.pt-BR.md, README.zh-CN.md, pnpm-lock.yaml, website/docs/en/guide/start/index.mdx, website/docs/zh/guide/start/index.mdx, website/package.json
Update ecosystem diagrams to show the latest Rstack ecosystem.
=> docs: update ecosystem diagrams

website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
This pull request includes updates to the quick start guides to provide additional information on obtaining more templates when creating a project with `create-rsbuild`.
=> docs: add information on obtaining additional templates

pnpm-lock.yaml, website/package.json
Update Rspress to 2.0.0-alpha.3.
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-alpha.3
=> chore(deps): update Rspress to 2.0.0-alpha.3

packages/core/package.json, pnpm-lock.yaml
Update Rspack to 1.3.0-beta.0.
https://github.com/web-infra-dev/rspack/releases/tag/v1.3.0-beta.0
=> feat(deps): update Rspack to 1.3.0-beta.0

e2e/cases/sri/enable-dev/index.test.ts, e2e/cases/sri/preload/index.test.ts, packages/core/src/configChain.ts, packages/core/src/helpers/stats.ts, packages/core/src/plugins/sri.ts, website/docs/en/config/tools/bundler-chain.mdx, website/docs/zh/config/tools/bundler-chain.mdx
Integrate Rspack's [SubresourceIntegrityPlugin](https://rspack.dev/plugins/rspack/subresource-integrity-plugin) to add integrity support for dynamic imports and improve performance.
resolve https://github.com/web-infra-dev/rsbuild/issues/3125
=> feat: add integrity support for dynamic imports

packages/core/src/server/gracefulShutdown.ts
Fix the MaxListenersExceeded warning after restarting server multiple times:
=> fix: MaxListenersExceeded warning after restarting server

packages/core/src/cli/commands.ts, packages/core/src/cli/init.ts, packages/core/src/config.ts, packages/core/src/restart.ts, packages/core/src/server/devServer.ts
Moving the `watchFilesForRestart` function and other related imports to a  `restart.ts`, file and updating the relevant imports across multiple files.
These changes help in better organizing the code by separating the restart-related functionalities into their own module.
=> refactor: move file watching and restart logic to separate module

packages/compat/webpack/src/createCompiler.ts, packages/core/src/cli/init.ts, packages/core/src/createContext.ts, packages/core/src/createRsbuild.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/types/context.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Expose a new `context.action` property.
`context.action` is set when running CLI commands or calling Rsbuild instance methods:
- `dev`: will be set when running [rsbuild dev](https://rsbuild.dev/guide/basic/cli#rsbuild-dev) or [rsbuild.startDevServer()](https://rsbuild.dev/api/javascript-api/instance#rsbuildstartdevserver)
- `build`: will be set when running [rsbuild build](https://rsbuild.dev/guide/basic/cli#rsbuild-build) or [rsbuild.build()](https://rsbuild.dev/api/javascript-api/instance#rsbuildbuild)
- `preview`: will be set when running [rsbuild preview](https://rsbuild.dev/guide/basic/cli#rsbuild-preview) or [rsbuild.preview()](https://rsbuild.dev/api/javascript-api/instance#rsbuildpreview)
For example:
```ts
if (rsbuild.context.action === 'dev') {
// do something
}
```
=> feat: expose `context.action` property

e2e/cases/source/define/index.test.ts, packages/core/src/plugins/define.ts
Warn users about potential security risks when defining `process.env` in the `source.define` configuration. It also includes updates to the test cases to ensure these warnings are properly handled.
=> feat(security): add warnings for defining `process.env`

website/docs/en/api/javascript-api/instance.mdx, website/docs/en/guide/advanced/environments.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/guide/advanced/environments.mdx
Improve clarity by adding additional links to the Rspack `MultiCompiler` documentation.
=> docs: add MultiCompiler references

e2e/cases/plugin-api/plugin-transform-error-handle/index.test.ts, e2e/cases/plugin-api/plugin-transform-error-handle/myPlugin.ts, e2e/cases/plugin-api/plugin-transform-error-handle/rsbuild.config.ts, e2e/cases/plugin-api/plugin-transform-error-handle/src/index.js, packages/core/src/loader/transformLoader.ts
Handle errors in transform loader with try-catch block. 
When I was fixing the unplugin transform issue, I found that Rsbuild's `api.transform` also had this issue, related https://github.com/web-infra-dev/rsbuild/issues/4789.
=> fix: handle errors in transform loader with try-catch block

e2e/cases/plugin-api/plugin-transform-error-handle/index.test.ts, e2e/cases/server/overlay-type-errors/index.test.ts, packages/core/src/helpers/format.ts, packages/core/src/helpers/stats.ts, website/docs/en/guide/faq/exceptions.mdx
Improve error handling and formatting by removing the verbose tip and highlighting the file path.
=> feat: improve build error messages

e2e/cases/css/css-raw/index.test.ts, e2e/cases/css/css-raw/src/a.css, e2e/cases/css/css-raw/src/b.module.css, e2e/cases/css/css-raw/src/index.js, examples/react/src/App.tsx, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/configChain.ts, packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/types.d.ts
Supports importing raw CSS files as strings in JavaScript by using the `?raw` query parameter:
```ts title="src/index.js"
import rawCss from './style.css?raw';
console.log(rawCss); // Output the raw content of the CSS file
```
- https://github.com/web-infra-dev/rsbuild/issues/4562
- https://github.com/web-infra-dev/rsbuild/issues/3778
While it is possible to support `?raw` query for all resources using the `NormalModuleReplacementPlugin`, this would result in a significant degradation in build performance, so this PR does not use it.
```js
tools: {
rspack: (config, { rspack }) => {
config.module?.rules?.push({
resourceQuery: /raw/,
type: 'asset/source',
});
config.plugins?.push(
new rspack.NormalModuleReplacementPlugin(/\?raw$/, (resource) => { …
```
=> feat(css): add support for raw CSS imports

website/docs/en/guide/basic/css-usage.mdx, website/docs/zh/guide/basic/css-usage.mdx
Adding a section explaining how to import raw CSS files in JavaScript using the `?raw` query parameter.
https://github.com/web-infra-dev/rsbuild/pull/4841
=> docs: add section on importing raw CSS files

e2e/cases/css/sass-raw/index.test.ts, e2e/cases/css/sass-raw/rsbuild.config.ts, e2e/cases/css/sass-raw/src/a.scss, e2e/cases/css/sass-raw/src/b.module.scss, e2e/cases/css/sass-raw/src/index.js, packages/core/src/configChain.ts, packages/core/src/plugins/css.ts, packages/plugin-sass/src/index.ts, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/tests/index.test.ts
Supports importing raw Sass files as strings in JavaScript by using the `?raw` query parameter:
```ts title="src/index.js"
import rawScss from './style.scss?raw';
console.log(rawScss); // Output the raw content of the Sass file
```
https://github.com/web-infra-dev/rsbuild/pull/4841
=> feat(plugin-sass): add support for raw query

e2e/cases/css/less-raw/index.test.ts, e2e/cases/css/less-raw/rsbuild.config.ts, e2e/cases/css/less-raw/src/a.less, e2e/cases/css/less-raw/src/b.module.less, e2e/cases/css/less-raw/src/index.js, packages/core/src/configChain.ts, packages/plugin-less/src/index.ts, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-less/tests/index.test.ts
Supports importing raw Less files as strings in JavaScript by using the `?raw` query parameter:
```ts title="src/index.js"
import rawLess from './style.less?raw';
console.log(rawLess); // Output the raw content of the Less file
```
https://github.com/web-infra-dev/rsbuild/pull/4841
=> feat(plugin-less): add support for raw query

e2e/cases/css/stylus-raw/index.test.ts, e2e/cases/css/stylus-raw/rsbuild.config.ts, e2e/cases/css/stylus-raw/src/a.styl, e2e/cases/css/stylus-raw/src/b.module.styl, e2e/cases/css/stylus-raw/src/index.js, packages/core/src/configChain.ts, packages/plugin-stylus/src/index.ts, packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
Supports importing raw Stylus files as strings in JavaScript by using the `?raw` query parameter:
```ts title="src/index.js"
import rawStylus from './style.styl?raw';
console.log(rawStylus); // Output the raw content of the Stylus file
```
https://github.com/web-infra-dev/rsbuild/pull/4841
=> feat(plugin-stylus): add support for raw query

packages/core/types.d.ts, website/docs/en/guide/basic/css-usage.mdx, website/docs/zh/guide/basic/css-usage.mdx
- Add types for raw imports of CSS preprocessors
- Updates the documentation to include information about the support for the `?raw` query parameter in Rsbuild's Sass, Less, and Stylus plugins.
- https://github.com/web-infra-dev/rsbuild/pull/4843
- https://github.com/web-infra-dev/rsbuild/pull/4844
- https://github.com/web-infra-dev/rsbuild/pull/4845
=> feat: add types for raw imports of CSS preprocessors

pnpm-lock.yaml, website/package.json, website/theme/components/Overview.module.scss
- Update Rspress to 2.0.0-alpha.5: https://github.com/web-infra-dev/rspress/releases
- Fix Overview link style
=> docs: update Rspress and fix Overview link style

e2e/cases/css/css-inline/index.test.ts, e2e/cases/css/css-inline/src/a.css, e2e/cases/css/css-inline/src/b.module.css, e2e/cases/css/css-inline/src/index.js, examples/react/src/App.tsx, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/configChain.ts, packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/types.d.ts
Supports importing transformed CSS files as strings in JavaScript by using the `?inline` query parameter:
```ts title="src/index.js"
import inlineCss from './style.css?inline';
console.log(inlineCss); // Output the inline content of the CSS file
```
- https://github.com/web-infra-dev/rsbuild/issues/4562
- https://github.com/web-infra-dev/rsbuild/issues/3778
=> feat(css): add support for inline CSS imports

e2e/cases/config/bundler-chain/index.test.ts, packages/core/package.json, packages/core/src/plugins/asset.ts, packages/core/src/plugins/basic.ts, packages/core/src/plugins/css.ts, packages/core/src/plugins/resolve.ts, packages/core/src/plugins/wasm.ts, packages/plugin-less/src/index.ts, packages/plugin-sass/src/index.ts, packages/plugin-solid/src/index.ts, packages/plugin-stylus/src/index.ts, packages/plugin-svelte/src/index.ts, pnpm-lock.yaml
- Replace `merge()` with `rspack-chain` methods for better readability and performance.
- Update `rspack-chain` to v1.2.3, https://github.com/rspack-contrib/rspack-chain/releases/tag/v1.2.3
=> chore: replace merge with rspack-chain methods

website/docs/en/plugins/list/plugin-svgr.mdx, website/docs/zh/plugins/list/plugin-svgr.mdx
update `pluginSvgr` usage example, `pluginReact` is also needed when using `pluginSvgr`.
```ts title="rsbuild.config.ts"
import { pluginReact } from '@rsbuild/plugin-react';
import { pluginSvgr } from '@rsbuild/plugin-svgr';
plugins: [pluginReact(), pluginSvgr()],
};
```
=> docs: `pluginReact` is also needed when using `pluginSvgr`

packages/plugin-stylus/src/index.ts, website/docs/en/plugins/list/plugin-stylus.mdx, website/docs/zh/plugins/list/plugin-stylus.mdx
Fix the documentation and type definitions for the `define` option in `StylusOptions`. 
resolve https://github.com/web-infra-dev/rsbuild/issues/4840
=> fix(plugin-stylus): `define` option type

packages/plugin-stylus/src/index.ts, website/docs/en/plugins/list/plugin-stylus.mdx, website/docs/zh/plugins/list/plugin-stylus.mdx
Added `includeCSS` option type to `@rsbuild/plugin-stylus`, also added JSDoc to improve DX.
Copied from https://github.com/webpack-contrib/stylus-loader#stylusoptions.
=> feat(plugin-stylus): add `includeCSS` option type and JSDoc

e2e/cases/assets/raw/index.test.ts, e2e/cases/assets/raw/src/index.js, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/asset.ts, packages/core/tests/__snapshots__/asset.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap
Allow to use the `?raw` query to get the raw content of static assets:
```js
import rawSvg from './icon.svg?raw';
console.log(rawSvg);
```
- https://github.com/web-infra-dev/rsbuild/issues/3778
=> feat(asset): add support for raw query

packages/core/types.d.ts
- Streamline query params as Rsbuild has supported `?raw` query for all static assets and CSS files.
- Improve JSDoc, adding notes and examples.
- https://github.com/web-infra-dev/rsbuild/pull/4869
=> refactor(types): streamline query params and improve JSDoc

website/docs/en/guide/basic/static-assets.mdx, website/docs/zh/guide/basic/static-assets.mdx
Add guide for importing static assets as string via the `?raw` query parameter.
https://github.com/web-infra-dev/rsbuild/pull/4869
=> docs: import static assets as string

README.md, README.pt-BR.md, README.zh-CN.md, website/docs/en/guide/debug/build-profiling.mdx, website/docs/zh/guide/debug/build-profiling.mdx
Polish credits in README files with LLM to make the expression more native。
=> docs: polish credits in README files

packages/core/package.json, pnpm-lock.yaml
The `cors` package does not contain any type declaration files, we should install `@types/cors` to ensure that the `server.cors` option is correctly typed.
- https://www.npmjs.com/package/@types/cors
=> fix(types): missing `server.cors` object type

e2e/cases/server/cors/index.test.ts, e2e/cases/server/fallback/index.test.ts, packages/core/src/helpers/index.ts, packages/core/src/plugins/moduleFederation.ts, packages/core/src/server/getDevMiddlewares.ts
The Rsbuild dev server unexpectedly set `Access-Control-Allow-Origin` to `*` by default, which caused the `server.cors` option not to work as expected and introduced security risks.
This PR removes the default `Access-Control-Allow-Origin: *` and strictly enables CORS according to the value of `server.cors`.
This may break users who are using Module Federation or proxy tools, so I added compatibility code for Module Federation.
To enable CORS, set [server.cors](https://rsbuild.dev/config/server/cors) to `true`:
```js
server: {
cors: true,
},
};
```
-  https://github.com/module-federation/core/pull/3635
- https://github.com/vitejs/vite/security/advisories/GHSA-vg6x-rcgg-rjx6
=> fix(server)!: should respect the value of the `server.cors` option

e2e/cases/lazy-compilation/basic/index.test.ts, e2e/cases/module/glob-import/index.test.ts, e2e/cases/preact/basic/index.test.ts, e2e/cases/react/basic/index.test.ts, e2e/cases/react/react-compiler-babel/index.test.ts, e2e/cases/solid/index.test.ts, e2e/cases/svelte/hmr/index.test.ts, e2e/cases/svelte/index.test.ts, e2e/cases/svelte/ts/index.test.ts
Improve the handling of async operations in E2E tests, ensuring that the `rsbuild.close()` and `button.click()` operations are awaited properly.
=> test(e2e): ensure proper async handling

website/docs/en/guide/framework/react.mdx, website/docs/zh/guide/framework/react.mdx
Fix the broken TanStack Router link in `react.mdx`.
https://tanstack.com/router/latest/docs/framework/react/routing/installation-with-rspack
=>  docs: fix broken TanStack Router link

.github/workflows/test.yml, e2e/cases/css/inject-styles/index.test.ts, e2e/cases/lazy-compilation/add-initial-chunk/index.test.ts, e2e/cases/lazy-compilation/basic/index.test.ts, e2e/cases/lazy-compilation/dynamic-import/index.test.ts, e2e/cases/lazy-compilation/dynamic-import/rsbuild.config.ts, e2e/cases/lazy-compilation/dynamic-import/src/foo.js, e2e/cases/lazy-compilation/dynamic-import/src/index.js, e2e/cases/live-reload/index.test.ts, e2e/cases/module-federation-v2/index.test.ts, e2e/cases/module-federation/index.test.ts, e2e/cases/preact/prefresh-context/index.test.ts, e2e/cases/preact/prefresh-disabled/index.test.ts, e2e/cases/preact/prefresh/index.test.ts, e2e/cases/react/disable-fast-refresh/index.test.ts, e2e/cases/server/environments-hmr/index.test.ts, e2e/cases/server/hmr/index.test.ts, e2e/cases/server/overlay/index.test.ts, e2e/cases/server/reload-html/index.test.ts, e2e/cases/server/setup-middlewares/index.test.ts, e2e/cases/solid/hmr/index.test.ts, e2e/cases/svelte/hmr/index.test.ts, e2e/cases/tailwindcss/hmr/index.test.ts, e2e/scripts/shared.ts, packages/core/src/plugins/output.ts, website/docs/en/config/dev/lazy-compilation.mdx, website/docs/en/config/source/include.mdx
Add more E2E case for lazy compilation.
https://github.com/web-infra-dev/rsbuild/pull/4881
=> test(e2e): add more case for lazy compilation

.github/workflows/ecosystem-ci.yml
use `dorny/paths-filter` instead of head commit message check.
=> chore(workflow): should not run eco-ci when only doc changed

.github/workflows/test.yml
Update test workflow: extract changes check as a single job. so we don't need to run it in each test job and check it in each step.
=> chore(workflow): extract changes check as a single job

packages/core/src/types/config.ts, website/docs/en/config/server/cors.mdx, website/docs/zh/config/server/cors.mdx
Update the CORS configuration documentation and type definitions to improve clarity and security recommendations.
=> docs: clarify CORS security recommendations

website/docs/en/config/server/headers.mdx, website/docs/zh/config/server/headers.mdx
- Correct `server.headers` type.
- Add examples and description for `server.headers`.
=> docs: correct `server.headers` type

.github/workflows/test.yml
This reverts commit c3243008ceb3fa510505090741aaa25b58cad894.
If no job is executed, the required CI will not be able to update the status, resulting in the PR being unable to be merged.
@9aoy cc
> https://github.com/web-infra-dev/rsbuild/pull/4895
- https://github.com/web-infra-dev/rsbuild/pull/4893
=> Revert "chore(workflow): extract changes check as a single job (#4893)"

e2e/cases/server/fallback/index.test.ts, packages/core/src/config.ts, packages/core/src/plugins/moduleFederation.ts, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/server.test.ts, website/docs/en/config/server/cors.mdx, website/docs/zh/config/server/base.mdx, website/docs/zh/config/server/cors.mdx, website/docs/zh/guide/basic/web-workers.mdx, website/docs/zh/guide/faq/hmr.mdx
The default CORS option has been changed in https://github.com/web-infra-dev/rsbuild/pull/4895.
This PR update CORS defaults to allow loopback addresses, this makes local development easier while ensuring security.
We still use `cors: true` as the default when using Module Federation, but this is still subject to discussion and further resolution.
=> feat(cors): update CORS defaults to allow loopback addresses

e2e/cases/server/cors/index.test.ts, e2e/cases/server/proxy/index.test.ts, packages/core/src/server/devMiddlewares.ts, packages/core/src/server/prodServer.ts, website/docs/en/config/server/headers.mdx, website/docs/zh/config/server/headers.mdx
Allow `server.headers` to override `server.cors`. This ensures that fields explicitly defined in `server.headers` always work as expected.
=> fix(server): allow `server.headers` to override `server.cors`

website/docs/en/guide/advanced/env-vars.mdx, website/docs/zh/guide/advanced/env-vars.mdx
Clarify env files merge behavior in env-vars.mdx. 
resolve https://github.com/web-infra-dev/rsbuild/issues/4885
=> docs: clarify env files merge behavior

packages/compat/webpack/rslib.config.ts, packages/core/rslib.config.ts
Since Rslib 0.6.0. No need to manually add CJS export annotation anymore.
=> build: remove CJS export annotation

packages/compat/plugin-webpack-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/plugin-less/package.json, packages/plugin-sass/package.json, packages/plugin-stylus/package.json
=> release: 1.3.0

packages/plugin-less/src/index.ts, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-less/tests/index.test.ts, packages/plugin-sass/src/index.ts, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/tests/index.test.ts, packages/plugin-stylus/src/index.ts, packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap, packages/plugin-stylus/tests/index.test.ts
Ensure compatibility of plugin-less, plugin-sass, and plugin-stylus with Rsbuild 1.2.x.
> I believe it might also crash when using Rsbuild v1.2.x with plugin-sass v1.3.0, though I haven’t tested it myself. 😉
See https://github.com/lynx-family/lynx-stack/pull/386.
=> fix: make CSS preprocessor plugins compat with Rsbuild 1.2

scripts/config/rslib.config.ts
Rslib now clean the .tsbuildinfo file by default, so we no longer need to add a `pluginCleanTscCache` plugin.
See https://github.com/web-infra-dev/rslib/blob/0d6d4fdb7460aa93328607c627235ecc0b323440/packages/plugin-dts/src/utils.ts#L481
=> chore(build): simplify rslib config by removing unused plugin

e2e/cases/lazy-compilation/dynamic-import/index.test.ts, e2e/cases/lazy-compilation/dynamic-import/rsbuild.config.ts
Fix a flaky lazy compilation E2E case:
=> test(e2e): fix flaky lazy compilation case

e2e/cases/cli/public-env-vars/index.test.ts, e2e/cases/cli/watch-files/index.test.ts, e2e/cases/cli/watch-files/rsbuild.config.ts
The `process.env.NODE_ENV` of the watch files case is affected by other test cases. We need to find a way to isolate the process.env.NODE_ENV of different test cases.
Fix:
=> test(e2e): fix flaky watch files cases

website/docs/en/guide/migration/vite.mdx, website/docs/zh/guide/migration/vite.mdx
Adding the `cacheDir` option to migration guide.
=> docs: add cacheDir option to migration guide

packages/core/src/config.ts
Add `@rspack/core` to jiti's `nativeModules` options. This allows jiti load `@rspack/core` with native `require()` and avoids `@rspack/core` being loaded twice.
This PR should fixes the "The 'compilation' argument must be an instance of Compilation error" error after upgrade to v1.3.0.
- https://github.com/unjs/jiti?tab=readme-ov-file#nativemodules
- https://github.com/web-infra-dev/rspack/issues/9841
=> fix: let jiti load `@rspack/core` with native require

e2e/cases/cli/no-env/.env, e2e/cases/cli/no-env/index.test.ts, e2e/cases/cli/no-env/rsbuild.config.ts, e2e/cases/cli/no-env/src/index.js, packages/core/src/cli/commands.ts, packages/core/src/cli/init.ts, scripts/dictionary.txt, website/docs/en/guide/advanced/env-vars.mdx, website/docs/en/guide/basic/cli.mdx, website/docs/zh/guide/advanced/env-vars.mdx, website/docs/zh/guide/basic/cli.mdx
Add a `--no-env` flag to the Rsbuild CLI to disable loading of .env files. This allows users to use other tools like
[dotenvx](https://github.com/dotenvx/dotenvx).
```bash
rsbuild build --no-env
```
=> feat(CLI): allow to disable loading .env files

packages/core/src/plugins/appIcon.ts
- Improve the appIcon plugin types and streamline icon path handling.
- Added a `clean` function to clear on closing the dev server and after the build.
=> refactor(appIcon): improve types and streamline icon path handling

e2e/cases/server/ssr/package.json, e2e/cases/server/ssr/src/assert.server.ts, packages/core/src/server/runner/asModule.ts, packages/core/src/server/runner/esm.ts
Fix ssr render error. support access globalThis attributes in esm vm, like `TextEncoder`.
We need to use `vm.SourceTextModule` to run ESM code in the **current context** like it was possible with CJS with `vm.runInThisContext`.
- Remove context specified, run esm code in current context (allow access globalThis attributes). 
- Use `vm.SyntheticModule` instead of legacy hard code which dependent `context`
https://nodejs.org/api/vm.html
=> fix(server): support access globalThis in esm vm

packages/core/src/server/open.ts
This is a prerequisite for supporting https://github.com/web-infra-dev/rsbuild/issues/4879.
1. When setting the `process.env.BROWSER` environment variable, Rsbuild now passes it to the [app](https://github.com/sindresorhus/open?tab=readme-ov-file#app) option of `open` to specify the browser name.
2. Refactor the AppleScript related code to make it clearer.
=> feat: support for specifying more browser names

website/docs/en/config/server/open.mdx, website/docs/zh/config/server/open.mdx
Update documentation to reflect the changes in https://github.com/web-infra-dev/rsbuild/pull/4955.
=> docs: improve guide for specifying browser name

packages/core/package.json, pnpm-lock.yaml
Update Rspack to v1.3.2.
https://github.com/web-infra-dev/rspack/releases/tag/v1.3.2
=> feat(deps): update Rspack to v1.3.2

packages/create-rsbuild/package.json, pnpm-lock.yaml
Update create-rstack to v1.4.0 to fix Vue TS ESLint template.
- https://github.com/rspack-contrib/create-rstack/releases/tag/v1.4.0
- https://github.com/web-infra-dev/rsbuild/issues/4962
=> fix(create-rsbuild): Vue TS ESLint template

packages/core/src/server/open.ts, website/docs/en/config/server/open.mdx, website/docs/zh/config/server/open.mdx
Using the `open` library's `apps` object to make it easier to set browser names across different operating systems.
- https://github.com/sindresorhus/open?tab=readme-ov-file#apps
=> feat: make it easier to set browser name

packages/core/package.json, pnpm-lock.yaml
> Versions of the package http-proxy-middleware before 2.0.7, from 3.0.0 and before 3.0.3 are vulnerable to Denial of Service (DoS) due to an UnhandledPromiseRejection error thrown by micromatch. An attacker could kill the Node.js process and crash the server by making requests to certain paths.
See https://nvd.nist.gov/vuln/detail/CVE-2024-21536 for more details.
=> fix(security): update http-proxy-middleware to 2.0.7

packages/core/prebundle.config.mjs
Fix invalid type in http-proxy-middleware:
This workaround can be removed after upgrading to http-proxy-middleware v3, which should be done before the release of Rsbuild 2.0.
Related: https://github.com/web-infra-dev/rsbuild/pull/3936
=> fix: invalid type in http-proxy-middleware

packages/core/package.json, packages/core/prebundle.config.mjs, packages/core/src/config.ts, packages/core/src/configChain.ts, packages/core/src/helpers/index.ts, packages/core/src/plugins/css.ts, packages/core/src/types/config.ts, packages/core/src/types/hooks.ts, packages/core/src/types/plugin.ts, packages/core/src/types/rspack.ts, packages/core/src/types/thirdParty.ts, packages/core/tests/external.test.ts, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-sass/package.json, packages/plugin-svgr/package.json, pnpm-lock.yaml
Fix failed to resolve `postcss` types.
The `postcss` package has been prebundled and we can use the `copyDts` option to copy declaration types to the compiled folder.
- https://github.com/rspack-contrib/prebundle/releases/tag/v1.3.0
=> fix(types): failed to resolve postcss types

website/docs/en/config/plugins.mdx, website/docs/en/guide/advanced/environments.mdx, website/docs/en/guide/advanced/ssr.mdx, website/docs/en/guide/basic/server.mdx, website/docs/zh/config/plugins.mdx, website/docs/zh/guide/advanced/environments.mdx, website/docs/zh/guide/advanced/ssr.mdx, website/docs/zh/guide/basic/server.mdx
- Updating the format of code block titles and removing unnecessary arguments in function calls.
- Correct `getTransformedHtml` link.
=> docs: correct `getTransformedHtml` link

packages/plugin-svgr/package.json, pnpm-lock.yaml
Unpin `@rsbuild/plugin-react` dependency version in `@rsbuild/plugin-svgr` to avoid repeated installation of `@rsbuild/plugin-react`.
=> fix(plugin-svgr): unpin @rsbuild/plugin-react dependency version

packages/core/src/server/overlay.ts, packages/core/tests/overlay.test.ts, scripts/dictionary.txt
Add support for clicking links in error logs when rendering the error overlay:
=> feat(overlay): support for clicking links in error logs

packages/core/src/mergeConfig.ts, packages/core/tests/mergeConfig.test.ts
When merging the `output.filename.*` configuration of the string type and function type, we should use the override strategy instead of  chaining strategy to output a valid configuration.
=> fix: output.filename config merging

website/docs/en/guide/debug/build-profiling.mdx, website/docs/zh/guide/debug/build-profiling.mdx
Update documentation to clarify when the build profiling files are generated and add a tip section for additional information.
=> docs: clarify Rsbuild profiling folder generation

e2e/cases/config/bundler-chain/index.test.ts, e2e/cases/config/bundler-chain/src/index.js, packages/core/src/provider/rspackConfig.ts, packages/core/src/types/config.ts, packages/core/src/types/hooks.ts, website/docs/en/config/tools/bundler-chain.mdx, website/docs/zh/config/tools/bundler-chain.mdx
Support use `rspack` in `tools.bundlerChain`.
```js
tools: {
bundlerChain: (chain, { rspack }) => {
chain.plugin('define').use(rspack.DefinePlugin, [
{
'process.env': {
NODE_ENV: JSON.stringify(process.env.NODE_ENV),
},
},
]);
},
},
};
```
=> feat: support use `rspack` in `tools.bundlerChain`

packages/core/src/helpers/exitHook.ts, packages/core/src/initPlugins.ts, website/docs/en/guide/debug/build-profiling.mdx, website/docs/zh/guide/debug/build-profiling.mdx
- Listen to the `SIGINT` process event to ensure the `onExit` hook can be called with CTRL+C.
- Update the build profiling guide as `CTRL+C` has been supported.
- https://stackoverflow.com/questions/21864127/nodejs-process-hangs-on-exit-ctrlc/21948167#21948167
- https://github.com/web-infra-dev/rsbuild/issues/2112
=> fix: `onExit` hook should be called with CTRL+C

e2e/cases/plugin-api/plugin-on-exit-hook/index.test.ts, e2e/cases/plugin-api/plugin-on-exit-hook/run.mjs, packages/core/src/helpers/exitHook.ts, packages/core/src/initPlugins.ts, packages/core/src/types/hooks.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/en/plugins/dev/hooks.mdx, website/docs/en/shared/onExit.mdx, website/docs/zh/api/javascript-api/instance.mdx, website/docs/zh/plugins/dev/hooks.mdx, website/docs/zh/shared/onExit.mdx
Add support for accessing the exit code in the `onExit` hook:
```js
const myPlugin = () => ({
setup(api) {
api.onExit(({ exitCode }) => {
console.log('exit: ', exitCode);
});
},
});
```
=> feat: support for accessing exit code in `onExit` hook

e2e/cases/mode/define/index.test.ts, website/docs/en/guide/advanced/env-vars.mdx, website/docs/zh/guide/advanced/env-vars.mdx
- Add example for disabling NODE_ENV injection to documentation.
- Add an E2E case for it.
- https://github.com/web-infra-dev/rsbuild/discussions/5007
=> docs: add example for disabling NODE_ENV injection

e2e/cases/svg/svgr-hash-digest/index.test.ts, e2e/cases/svg/svgr-hash-digest/rsbuild.config.ts, e2e/cases/svg/svgr-hash-digest/src/index.js, package.json, packages/plugin-svgr/package.json, packages/plugin-svgr/prebundle.config.mjs, patches/file-loader@6.2.0.patch, patches/url-loader@4.1.1.patch, pnpm-lock.yaml
- Update `loader-utils` to v3 to allow `@rsbuild/plugin-svg` to use the same hash function (`xxhash64`) as Rsbuild, see https://github.com/webpack/loader-utils/releases/tag/v3.0.0
- Since `file-loader` and `url-loader` are no longer maintained, patch `file-loader` and `url-loader` to be compatible with `loader-utils` v3.
fix https://github.com/web-infra-dev/rsbuild/issues/4610
=> fix(plugin-svgr): SVGs generated with different hash

pnpm-lock.yaml, website/package.json, website/rspress.config.ts
Update Rspress to 2.0.0-alpha.10 and the `ssg.strict` and `search.codeBlocks` configs are no longer required.
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-alpha.10
=> chore(deps): update Rspress to 2.0.0-alpha.10

packages/core/rslib.config.ts
Remove invalid plugin from build config, the `pluginCleanTscCache` has been removed in https://github.com/web-infra-dev/rsbuild/pull/4916
=> chore: remove invalid plugin from build config

packages/core/prebundle.config.mjs
There are some invalid types in the prebundled packages that prevent users from setting `skipLibCheck: false` in tsconfig.json.
These type issues are hard to address, so we are using the prebundle config to hack them. We may find a better solution in the long run.
=> fix(types): failed to resolve prebundled types

packages/core/src/types/plugin.ts, packages/core/src/types/thirdParty.ts
Fix failed to resolve webpack types when setting `skipLibCheck: false` in tsconfig.json. The `webpack` type only exists when `@rsbuild/webpack` is installed and it should be removed in Rsbuild 2.0.
=> fix(types): failed to resolve webpack types

packages/core/package.json, pnpm-lock.yaml
Update Rspack to v1.3.5.
- https://github.com/web-infra-dev/rspack/releases/tag/v1.3.5
=> feat(deps): update Rspack to v1.3.5

packages/core/package.json, packages/create-rsbuild/package.json
Update Node.js engine requirement to >=16.10 to correctly load Rspack bindings:
=> fix: update Node.js engine requirement to >=16.10

packages/core/src/server/devMiddlewares.ts
Although Rsbuild doesn't directly support setting [dev.lazyCompilation](https://rsbuild.dev/config/dev/lazy-compilation) with a custom `serverUrl`, we can leverage `api.modifyRsbuildConfig` to modify both `assetPrefix` and `dev.lazyCompilation.serverUrl`. However, there's an inconsistency: `assetPrefix` will find and replace `<port>` placeholders, while `dev.lazyCompilation.serverUrl` does not perform this replacement, leading to configuration mismatches.
```js
dev: {
assetPrefix: 'http://xxx:<port>/',
lazyCompilation: {
serverUrl: 'http://xxx:<port>/'
// ...
}
},
```
Therefore, in the `lazyCompilationMiddleware`, we need to check if <port> is present in the URL, and if so, we need to replace it.
=> feat: support dev.lazyCompilation.serverUrl use <port>

e2e/cases/lazy-compilation/port-placeholder/index.test.ts, e2e/cases/lazy-compilation/port-placeholder/rsbuild.config.ts, e2e/cases/lazy-compilation/port-placeholder/src/page1/App.jsx, e2e/cases/lazy-compilation/port-placeholder/src/page1/index.js, e2e/cases/lazy-compilation/port-placeholder/src/page2/App.jsx, e2e/cases/lazy-compilation/port-placeholder/src/page2/index.js
Add lazy compilation '<port>' placeholder case for https://github.com/web-infra-dev/rsbuild/pull/5035.
=> test(e2e): add lazy compilation '<port>' placeholder case

website/docs/en/config/dev/lazy-compilation.mdx, website/docs/zh/config/dev/lazy-compilation.mdx
- Add client and serverUrl options to lazy compilation
- Add tip for the `<port>` placeholder.
- https://rspack.dev/config/experiments#lazycompilationserverurl
- https://github.com/web-infra-dev/rsbuild/pull/5035
=> docs: add client and serverUrl options to lazy compilation

packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-babel/tests/index.test.ts, packages/plugin-svgr/tests/index.test.ts, packages/plugin-vue/tests/__snapshots__/index.test.ts.snap, packages/plugin-vue/tests/index.test.ts
Update plugin unit tests to use `createRsbuild` instead of `createStubRsbuild`.
`createRsbuild` as a real-world API can better reflect the changes in user scenarios.
=> test: update plugin tests to use createRsbuild

website/docs/en/guide/debug/build-profiling.mdx, website/docs/zh/guide/debug/build-profiling.mdx
docs: remove shortcut restrictions in cpuprofile.
https://github.com/web-infra-dev/rsbuild/pull/5003
=> docs: remove shortcut restrictions in cpuprofile

packages/core/src/plugins/css.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/css.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/minimize.test.ts, packages/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap, website/docs/en/config/tools/lightningcss-loader.mdx, website/docs/zh/config/tools/lightningcss-loader.mdx
Enable Lightning CSS `errorRecovery` option to fix an issue introduced in Rspack 1.3.5.
- resolve https://github.com/web-infra-dev/rspack/issues/10056
- resolve https://github.com/youzan/vant/issues/13441
- related https://github.com/web-infra-dev/rspack/pull/10076
=> fix: enable Lightning CSS `errorRecovery` option

packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
The `getHooks` methods has been deprecated by `html-rspack-plugin`, use `getCompilationHooks` instead.
See https://github.com/rspack-contrib/html-rspack-plugin/blob/524d20714b07bfe06e9cae53e80f45f69591ca72/typings.d.ts#L22
=> chore: replace deprecated method

packages/core/src/configChain.ts, packages/core/src/plugins/resourceHints.ts, packages/core/src/rspack/preload/HtmlResourceHintsPlugin.ts, packages/core/src/rspack/preload/helpers/doesChunkBelongToHtml.ts, packages/core/src/types/config.ts
This pull request refactors the naming and structure of the `HtmlPreloadOrPrefetchPlugin` to improve clarity and consistency.
The plugin has been renamed to `HtmlResourceHintsPlugin`, and associated types and identifiers have been updated accordingly.
=> chore: rename HtmlResourceHintsPlugin

packages/core/src/plugins/inlineChunk.ts
Make inline chunk matching faster:
- No need to call `asset.source().toString()` if the asset is not matched.
- Use `asset.size()` to get size, it's faster than `asset.source().toString().length`.
=> perf: make inline chunk matching faster

e2e/cases/performance/resource-hints-prefetch/index.test.ts, e2e/cases/performance/resource-hints-preload/index.test.ts, packages/core/src/plugins/inlineChunk.ts, packages/core/src/plugins/resourceHints.ts, packages/core/src/rspack/resource-hints/HtmlResourceHintsPlugin.ts
If the asset is inlined via `output.inlineScripts` or `output.inlineStyles`, it will be added to the HTML content directly, so we need to exclude it from the resource hints.
Example:
```js
output: {
inlineScripts: {
enable: 'auto',
test: /\.js$/,
},
inlineStyles: {
enable: 'auto',
test: /\.css$/,
},
},
performance: {
preload: true,
},
}
```
Note that the function usage of `inlineScripts` and `inlineStyles` is not yet supported, as it requires the `size` param.
=> fix: do not generate resource hints for inlined assets

website/docs/en/config/output/override-browserslist.mdx, website/docs/en/config/output/target.mdx, website/docs/en/guide/advanced/browserslist.mdx, website/docs/zh/config/output/override-browserslist.mdx, website/docs/zh/config/output/target.mdx, website/docs/zh/guide/advanced/browserslist.mdx
This pull request focuses on improving the clarity and consistency of the documentation for Rsbuild's Browserslist configurations. The changes include updates to terminology, formatting, and examples, as well as moving the default Browserslist values to top.
=> docs: improve Browserslist content order

packages/core/src/helpers/format.ts
Correct the highlighting of filename log.
- before:
- after:
=> fix: correct highlighting of filename log

packages/core/package.json, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/config.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/moduleFederation.test.ts.snap, pnpm-lock.yaml
Update Rspack to v1.3.6.
https://github.com/web-infra-dev/rspack/releases/tag/v1.3.6
=> feat(deps): update Rspack to v1.3.6

packages/core/src/rspack/resource-hints/HtmlResourceHintsPlugin.ts, website/docs/en/config/performance/prefetch.mdx, website/docs/en/config/performance/preload.mdx, website/docs/zh/config/performance/prefetch.mdx, website/docs/zh/config/performance/preload.mdx
When using `performance.prefetch` or `performance.preload`, the source map files should always be excluded, regardless of whether the user has configured a custom exclude option.
Fix Modern.js E2E cases: https://github.com/web-infra-dev/modern.js/actions/runs/14632877492/job/41058294609
=> fix: source map files should always be excluded from resource hints

pnpm-lock.yaml, website/docs/en/guide/advanced/rem.mdx, website/package.json, website/rspress.config.ts
Upgrade to Rspress@2.0.0-beta.2.
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-beta.2
=> chore(deps): upgrade to Rspress@2.0.0-beta.2

packages/core/src/provider/build.ts
Persistent cache of Rspack is implemented in Rust and we should always call `compiler.close` after building.
The same as https://github.com/web-infra-dev/rspack/pull/10154
=> fix: call `compiler.close` when having errors

packages/core/src/rspack/resource-hints/doesChunkBelongToHtml.ts
Updates the `recursiveChunkGroup` function to prevent circular references when traversing chunk groups. The change introduces a `visited` set to track visited `ChunkGroup` instances.
resolve https://github.com/web-infra-dev/rsbuild/issues/5106
=> fix: prevent circular references in recursiveChunkGroup

e2e/cases/print-file-size/basic/index.test.ts, e2e/cases/print-file-size/with-error/index.test.ts, packages/core/src/plugins/fileSize.ts, website/docs/en/config/performance/print-file-size.mdx, website/docs/zh/config/performance/print-file-size.mdx
Improve the alignment of total output size.
=> feat: improve alignment of total output size

website/docs/en/config/environments.mdx, website/docs/zh/config/environments.mdx
Add note on server and dev options limitations when using the `environments` configuration.
https://github.com/web-infra-dev/rsbuild/discussions/5111
=> docs(environments): add note on server and dev options limitations

e2e/cases/print-file-size/basic/index.test.ts, packages/core/src/plugins/fileSize.ts
Fix file size logging when `printFileSize.detail` is disabled.
- https://github.com/web-infra-dev/rsbuild/issues/5124
More test cases will be added in later PRs.
=> fix: file size logging when detail is disabled

packages/core/package.json, pnpm-lock.yaml
Update Rspack to v1.3.8.
- https://github.com/web-infra-dev/rspack/releases/tag/v1.3.8
=> feat(deps): update Rspack to v1.3.8

e2e/cases/print-file-size/basic/index.test.ts, packages/core/src/plugins/fileSize.ts
Make the file size logs more compact, this allows users of small-screen devices or projects with long file names to avoid line wrapping that reduces readability.
=> fix: make file size logs more compact

e2e/cases/rsdoctor/index.test.ts
Remove Windows-specific skip from Rsdoctor plugin test as we have updated playwright to latest version.
https://github.com/web-infra-dev/rsbuild/pull/4331
=> test(e2e): remove Windows-specific skip from Rsdoctor plugin test

e2e/cases/output/manifest-environment/index.test.ts, e2e/cases/output/manifest-environment/src/index.ts, e2e/cases/output/manifest/index.test.ts, e2e/cases/performance/resource-hints-prefetch/index.test.ts, e2e/cases/performance/resource-hints-preload/index.test.ts, packages/core/src/createContext.ts, packages/core/src/plugins/manifest.ts, packages/core/src/types/hooks.ts
Add a new `manifest` property to the environment context object to allow plugin hooks to access manifest data.
Only available when:
- The `output.manifest` config option is enabled
- The build process has completed, accessible in hooks like `onAfterBuild`, `onDevCompileDone` and `onAfterEnvironmentCompile`
```js
const plugin = {
name: 'test',
setup(api: RsbuildPluginAPI) {
api.onAfterBuild(({ environments }) => {
console.log(environments.web.manifest);
console.log(environments.node.manifest);
});
},
}
```
=> feat: allow to access manifest data in plugin hooks

e2e/cases/plugin-api/plugin-hooks-environment/index.test.ts, e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts, e2e/cases/plugin-api/plugin-hooks/index.test.ts, e2e/cases/plugin-api/plugin-modify-html/index.test.ts, e2e/cases/plugin-api/plugin-modify-html/src/index.css, e2e/cases/plugin-api/plugin-modify-html/src/index.js, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/createRsbuild.ts, packages/core/src/hooks.ts, packages/core/src/index.ts, packages/core/src/initPlugins.ts, packages/core/src/plugins/html.ts, packages/core/src/rspack/RsbuildHtmlPlugin.ts, packages/core/src/types/hooks.ts, packages/core/src/types/plugin.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/hooks.test.ts.snap, packages/core/tests/__snapshots__/html.test.ts.snap
Add a new `modifyHTML` hook to modify the final HTML content.
- The hook receives a context object that contains the HTML content, and you can return a new HTML string to replace the original one.
- This hook is triggered after the `modifyHTMLTags` hook.
Example:
```js
const myPlugin: RsbuildPlugin = {
setup(api) {
api.modifyHTMLTags((tags) => {
tags.bodyTags.push({
tag: 'div',
children: 'foo',
});
return tags;
});
api.modifyHTML((html) => {
return html.replace('foo', 'bar');
});
},
};
```
=> feat: add new `modifyHTML` hook

website/docs/en/guide/framework/preact.mdx, website/docs/en/guide/framework/react.mdx, website/docs/en/guide/framework/solid.mdx, website/docs/en/guide/framework/svelte.mdx, website/docs/en/guide/framework/vue.mdx, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/framework/preact.mdx, website/docs/zh/guide/framework/react.mdx, website/docs/zh/guide/framework/solid.mdx, website/docs/zh/guide/framework/svelte.mdx, website/docs/zh/guide/framework/vue.mdx, website/docs/zh/guide/start/quick-start.mdx
- Updated the quick-start guide to use an external link to the `create-rsbuild` package on npm
- Updated links in framework-specific guides for Preact, React, Solid, Svelte, and Vue to point to the relevant section in the quick-start guide
=> docs: update creation instructions to link to create-rsbuild

website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
It is recommended to use named export to export an Rsbuild plugin.
=> docs: update plugin example to use named export

packages/core/src/server/ansiHTML.ts, packages/core/src/server/overlay.ts
Changed the export of the `ansiHTML` module from a default export to a named export, this module accidentally has two duplicate exports.
=> chore: update ansiHTML to use named export

packages/core/src/server/devMiddlewares.ts, packages/core/src/server/prodServer.ts, website/docs/en/api/javascript-api/dev-server-api.mdx, website/docs/en/config/dev/setup-middlewares.mdx, website/docs/en/config/server/middleware-mode.mdx, website/docs/en/guide/advanced/environments.mdx, website/docs/en/guide/basic/server.mdx, website/docs/en/guide/start/features.mdx, website/docs/en/plugins/dev/hooks.mdx, website/docs/zh/config/dev/setup-middlewares.mdx, website/docs/zh/guide/advanced/environments.mdx, website/docs/zh/plugins/dev/hooks.mdx
- Add link to middleware guide.
- Standardizes the terminology across the codebase and documentation by replacing "middlewares" with "middleware", see https://english.stackexchange.com/questions/257120/middleware-vs-middlewares
=> docs: add link to middleware guide

e2e/cases/plugin-api/plugin-transform-mime-type/index.test.ts, e2e/cases/plugin-api/plugin-transform-mime-type/myPlugin.ts, e2e/cases/plugin-api/plugin-transform-mime-type/rsbuild.config.ts, e2e/cases/plugin-api/plugin-transform-mime-type/src/index.js, packages/core/src/initPlugins.ts, packages/core/src/types/plugin.ts, website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Added `mimetype` support in the `api.transform`, allowing plugins to match modules based on MIME type, particularly useful for data URI modules (e.g., `data:text/javascript,...`.
```ts
import type { RsbuildPlugin } from '@rsbuild/core';
export const myPlugin: RsbuildPlugin = {
setup(api) {
api.transform({ mimetype: 'text/javascript' }, ({ code }) => {
return code.replace('data-uri-foo', 'data-uri-bar');
});
},
};
```
=> feat: add `mimetype` option to `api.transform`

packages/core/src/rspack/RsbuildHtmlPlugin.ts, packages/core/src/types/config.ts, website/docs/en/config/html/tags.mdx, website/docs/en/plugins/dev/hooks.mdx, website/docs/zh/config/html/tags.mdx, website/docs/zh/plugins/dev/hooks.mdx
- Enhanced examples to demonstrate how to inject tags into `<head>` and `<body>` at different positions using `headTags` and `bodyTags`
- Updated properties to the `HtmlTag` type with detailed descriptions and default values.
- Added a note about using the `api.modifyHTMLTags` hook to modify tags in Rsbuild plugins.
=> docs: clarify tag injection position

website/docs/en/api/javascript-api/environment-api.mdx, website/docs/zh/api/javascript-api/environment-api.mdx
Removed the earlier explanation about accessing manifest data after the build and replaced it with a more detailed list of hooks where the data can be accessed, including `onAfterBuild`, `onAfterEnvironmentCompile`, `onCloseBuild`, `onCloseDevServer`, `onDevCompileDone`, and `onExit`.
=> docs: improve manifest data access instructions

website/docs/en/config/output/manifest.mdx, website/docs/zh/config/output/manifest.mdx
Added a new section explaining how to configure unique `manifest.filename` values for multiple environments to prevent overwriting.
- https://github.com/web-infra-dev/rsbuild/pull/5165
=> docs: configuring multiple environments manifest files

e2e/package.json, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/basic.ts, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap
- Enable Rspack incremental build by default because it is stable enough and can bring HMR performance improvements.
- Removed the `EXPERIMENTAL_RSPACK_INCREMENTAL` environment variable
If you run into any issues, you can switch to the safe and stable incremental, which is consistent with previous behavior, by adding the following configuration:
```js
tools: {
rspack: {
experiments: {
incremental: 'safe',
},
},
},
});
```
- https://rspack.dev/config/experiments#experimentsincremental
=> perf: enable Rspack incremental build by default

packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/basic.ts
The `incremental` config is Rspack-specific and should not be set when using `@rsbuild/webpack`.
- https://github.com/web-infra-dev/rsbuild/pull/5167
=> fix: should not apply incremental config to webpack

e2e/cases/plugin-api/plugin-transform-enforce/index.test.ts, e2e/cases/plugin-api/plugin-transform-enforce/myPlugin.ts, e2e/cases/plugin-api/plugin-transform-enforce/rsbuild.config.ts, e2e/cases/plugin-api/plugin-transform-enforce/src/index.js, packages/core/src/initPlugins.ts, packages/core/src/types/plugin.ts, website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Added support for the `enforce` property to `api.transform()` to specify execution order (`'pre'` or `'post'`). This ensures that transform functions can be executed before or after other transformations or loaders. 
```js
api.transform({ test: /\.js$/, enforce: 'pre' }, ({ code }) => {
return code.replace('__placeholder__', 'hello world');
});
```
- https://rspack.dev/config/module#ruleenforce
=> feat: add `enforce` option to `api.transform`

packages/core/package.json, pnpm-lock.yaml
Update html-rspack-plugin to 6.1.0 to ensure the child compiler cache can work as expected.
- https://github.com/rspack-contrib/html-rspack-plugin/releases/tag/v6.1.0
- https://github.com/rspack-contrib/html-rspack-plugin/pull/39
- https://github.com/web-infra-dev/rsbuild/issues/5176
=> perf: update html-rspack-plugin to 6.1.0

e2e/cases/html/template-cache/index.test.ts, e2e/cases/html/template-cache/src/bar.html, e2e/cases/html/template-cache/src/bar.js, e2e/cases/html/template-cache/src/index.html, e2e/cases/html/template-cache/src/index.js
Added a new E2E test to verify that templates are not recompiled unless modified.
- https://github.com/web-infra-dev/rsbuild/pull/5177
- https://github.com/web-infra-dev/rsbuild/issues/5176
=> test: add case for HTML template caching

packages/plugin-less/src/index.ts
Updated the `webpackImporter` property to support a new `only` option, allowing exclusive use of the built-in Rspack resolver. Added detailed documentation to clarify its behavior and default value.
- https://github.com/webpack-contrib/less-loader/pull/562
=> feat(plugin-less): update webpackImporter type to support 'only'

packages/plugin-less/src/index.ts
This pull request enhances the `LessLoaderOptions` type in the `plugin-less` package by adding new configuration options and improving documentation.
- https://github.com/webpack-contrib/less-loader?tab=readme-ov-file#options
=> feat(plugin-less): improve loader options type with JSDoc

e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts
Removing a `console.log` statement that was used for debugging purposes.
=> test: remove temporary log

packages/plugin-react/package.json, pnpm-lock.yaml
Update @rspack/plugin-react-refresh to 1.4.2.
- https://github.com/web-infra-dev/rsbuild/discussions/2665#discussioncomment-13058264
- https://github.com/rspack-contrib/rspack-plugin-react-refresh/releases/tag/v1.4.2
=> chore(deps): update @rspack/plugin-react-refresh to 1.4.2

website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
Added an example showing how to use the `--tools` flag to specify multiple tools (e.g., `eslint` and `prettier`) when running `npx create-rsbuild`.
=> docs: update quick-start to include multiple values example

e2e/cases/server/base-url-env-var/index.test.ts, packages/core/package.json, pnpm-lock.yaml
- Update Rspack to v1.3.9
- Skip failed tests, which should be fixed in later PR.
- https://github.com/web-infra-dev/rspack/releases/tag/v1.3.9
=> feat(deps): update Rspack to v1.3.9

packages/core/src/plugins/basic.ts
The `process.env.WATCHPACK_WATCHER_LIMIT` is no longer required since Rspack 1.3.9, see https://github.com/web-infra-dev/rspack/pull/10236
=> chore: remove watchpack-related environment variable

package.json
Fix the root e2e script name, should be `pnpm e2e`.
=> chore(workflow): fix e2e script name

e2e/cases/server/base-url-env-var/index.test.ts, packages/core/package.json, pnpm-lock.yaml
Since Rspack 1.3.9, the `with` statement cannot be used in SWC's strict mode. When the HTML template contains code like `import.meta.*`, the SWC parser will report an error.
This PR updates html-rspack-plugin to 6.1.1 to fix the template parsing error.
- https://github.com/rspack-contrib/html-rspack-plugin/releases
- https://github.com/rspack-contrib/html-rspack-plugin/pull/40
- https://github.com/web-infra-dev/rsbuild/pull/5188
=> fix: update html-rspack-plugin to 6.1.2 to fix template parsing

.github/renovate.json5, e2e/cases/react/react-compiler-babel/package.json, pnpm-lock.yaml
- Update `babel-plugin-react-compiler` to 19.1.0-rc.1
- Allow Renovate to update `babel-plugin-react-compiler`
=> chore(deps): update babel-plugin-react-compiler to 19.1.0-rc.1

e2e/cases/output/manifest-environment/index.test.ts
Fix manifest name conflict warning when running E2E test:
https://github.com/web-infra-dev/rsbuild/pull/5165
=> test(e2e): fix manifest name conflict warning

e2e/cases/module-federation-v2/host/rsbuild.config.ts, e2e/cases/module-federation-v2/remote/rsbuild.config.ts, packages/core/src/plugins/moduleFederation.ts
As https://github.com/module-federation/core/pull/3635 has been released, we can remove the temp code and allow users to set custom `server.cors` configuration.
=> fix(mf): allow to set `server.cors` with MF Rsbuild plugin

e2e/cases/module-federation/host/rsbuild.config.ts, e2e/cases/module-federation/index.test.ts, e2e/cases/module-federation/remote/rsbuild.config.ts, packages/core/src/plugins/moduleFederation.ts
When MF application sets both `server.cors` and `moduleFederation.options`, `server.cors` should read the value set by the user instead of forcing it to `true`.
https://github.com/web-infra-dev/rsbuild/pull/5200
=> fix(mf): allow to set `server.cors` with built-in MF plugin

e2e/cases/server/cors/index.test.ts, packages/core/src/config.ts, packages/core/src/index.ts, packages/core/tests/server.test.ts, website/docs/en/config/server/cors.mdx, website/docs/zh/config/server/cors.mdx
Exposes `defaultAllowedOrigins` from core to allow users to easily add additional origins while keeping the default localhost origins.
```ts title="rsbuild.config.ts"
import { defaultAllowedOrigins } from '@rsbuild/core';
server: {
cors: {
origin: [defaultAllowedOrigins, 'https://example.com'],
},
},
};
```
=> feat: expose `defaultAllowedOrigins` from core

e2e/cases/javascript-api/caller-name/index.test.ts, e2e/cases/javascript-api/caller-name/src/index.js, packages/core/src/createContext.ts, packages/core/src/createRsbuild.ts, packages/core/src/types/context.ts, packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/core.mdx, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/core.mdx, website/docs/zh/api/javascript-api/instance.mdx
This PR adds a new `callerName` option to `createRsbuild` to specify the name of the framework or tool that is currently invoking Rsbuild, which can be accessed by Rsbuild plugins through `context.callerName`, and execute different logic based on this identifier.
This naming is inspired by the [caller.name](https://babeljs.io/docs/options#caller) option provided by Babel.
```ts
import { myPlugin } from './myPlugin';
const rsbuild = await createRsbuild({
callerName: 'rslib',
rsbuildConfig: {
plugins: [myPlugin],
},
});
```
```ts
// myPlugin.ts
export const myPlugin = {
setup(api) {
const { callerName } = api.context;
if (callerName === 'rslib') {
// ...
} else if (callerName === 'rsbuild') {
// ...
}
},
};
```
=> feat: add `callerName` option to `createRsbuild`

packages/core/src/server/socketServer.ts, packages/core/src/types/config.ts, website/docs/en/config/dev/setup-middlewares.mdx, website/docs/zh/config/dev/setup-middlewares.mdx
- Added a new type, `SockWriteType`, which restricts the `sockWrite` function's `type` parameter to `'static-changed'` or other string values. Updated the `sockWrite` function to use this new type.
- Updated the `sockWrite` section to include the new type definition and clarified its usage.
=> feat: enhance sockWrite type to include 'static-changed'

e2e/cases/javascript-api/sock-write/index.test.ts, e2e/cases/javascript-api/sock-write/src/index.js, packages/core/src/server/devMiddlewares.ts, packages/core/src/server/devServer.ts, packages/core/src/server/socketServer.ts, packages/core/src/types/config.ts, website/docs/en/api/javascript-api/dev-server-api.mdx, website/docs/en/config/dev/setup-middlewares.mdx, website/docs/zh/api/javascript-api/dev-server-api.mdx, website/docs/zh/config/dev/setup-middlewares.mdx
Added a `sockWrite` method to the `RsbuildDevServer` API, enabling middleware to send messages (e.g., `'static-changed'`) to the HMR client to trigger actions like page reloads.
This is consistent with the `sockWrite` function in the `setupMiddlewares` config, and now developers can call it through the JS API.
```ts
const rsbuildServer = await rsbuild.createDevServer();
if (someCondition) {
rsbuildServer.sockWrite('static-changed');
}
```
=> feat(server): support for `server.sockWrite`

website/docs/en/api/javascript-api/dev-server-api.mdx, website/docs/en/config/dev/setup-middlewares.mdx, website/docs/zh/api/javascript-api/dev-server-api.mdx, website/docs/zh/config/dev/setup-middlewares.mdx
- Updated dev server API documentation to improve clarity and provide additional examples.
- Updated the `connectWebSocket` doc to include `node:http.Server` and `node:http2.Http2SecureServer` types
=> docs: update dev server API documentation

packages/core/src/client/hmr.ts, packages/core/src/server/socketServer.ts
Remove `'still-ok'` socket message type, as it has exactly the same effect as `'ok'` in Rsbuild.
- https://github.com/facebook/create-react-app/pull/1377
=> chore(hmr): remove 'still-ok' socket message type

website/docs/en/guide/basic/upgrade-rsbuild.mdx, website/docs/en/guide/optimization/build-performance.mdx, website/docs/zh/guide/basic/upgrade-rsbuild.mdx, website/docs/zh/guide/optimization/build-performance.mdx
The `experiments.incremental` config has been enabled by default and we can remove it from the build performance guide.
- https://github.com/web-infra-dev/rsbuild/pull/5167
=> docs: remove incremental from build perf guide

website/docs/en/config/performance/build-cache.mdx, website/docs/zh/config/performance/build-cache.mdx
The `.env` and `.env.*` files are included in `buildDependencies` within the `createRsbuild` function. This setup allows these files to be utilized by frameworks built on top of Rsbuild, such as Rspeedy and Rslib.
https://github.com/web-infra-dev/rsbuild/blob/045c4e45dfce3d0d0fc5dc27a8777c5fb1874f4a/packages/core/src/createRsbuild.ts#L140-L150
In contrast, the `rsbuild.config.*` files are added to `buildDependencies` within the `loadConfig` function.
https://github.com/web-infra-dev/rsbuild/blob/045c4e45dfce3d0d0fc5dc27a8777c5fb1874f4a/packages/core/src/config.ts#L449-L452
However, this does not apply to Rspeedy, as it does not utilize the `loadConfig` function from Rsbuild.
It does work in Rslib and Rspress (using `rslib.config.*` and `rspress.config.*`), so I'm uncertain if the current …
=> docs: correct default `buildDependencies`

website/docs/en/config/tools/bundler-chain.mdx, website/docs/en/guide/configuration/rspack.mdx, website/docs/zh/config/tools/bundler-chain.mdx, website/docs/zh/guide/configuration/rspack.mdx
Using `rspack-chain` to customize plugin options is unstable and can be broken by internal changes, such as https://github.com/web-infra-dev/rsbuild/pull/5197.
This PR updates the documentation to discourage the use of rspack-chain for custom plugin options.
=> docs: discourage the use of rspack-chain for custom plugin options

website/docs/en/config/performance/build-cache.mdx, website/docs/zh/config/performance/build-cache.mdx
Updates the documentation for the `buildDependencies` configuration, adds information about Rsbuild's `loadConfig` JS API, which also includes the configuration file path in the build dependencies.
=> docs: enhance buildDependencies section

e2e/cases/config/configure-rspack/index.test.ts, packages/core/src/provider/rspackConfig.ts, packages/core/src/types/config.ts, packages/core/src/types/plugin.ts, website/docs/en/config/source/exclude.mdx, website/docs/en/config/tools/rspack.mdx, website/docs/en/plugins/dev/index.mdx, website/docs/zh/config/source/exclude.mdx, website/docs/zh/config/tools/rspack.mdx, website/docs/zh/plugins/dev/index.mdx
This PR aims to improve DX by narrow the type of `Rspack.Configuration` to make it easier to use `tools.rspack` function. 
These properties are set by Rsbuild by default so they are non-nullable. A possible edge case is that a plugin removes these fields, but this is unlikely to happen.
- With `Rspack.Configuration`, the `plugins` property is nullable:
```js
tools: {
rspack(config) {
if (!config.plugins) {
config.plugins = [];
}
config.plugins.push(new SomePlugin());
}
}
```
- With `NarrowedRspackConfig`, the `plugins` property is non-nullable:
```js
tools: {
rspack(config) {
config.plugins.push(new SomePlugin());
}
}
```
=> feat: narrow Rspack configuration type for `tools.rspack`

packages/core/src/server/devServer.ts, website/docs/en/api/javascript-api/dev-server-api.mdx, website/docs/zh/api/javascript-api/dev-server-api.mdx
Updated the description of the `afterListen` method to clarify that it notifies Rsbuild when a custom server has successfully started, triggering the `onAfterStartDevServer` hook.
=> docs: add documentation for `afterListen` server method

website/docs/en/config/tools/lightningcss-loader.mdx, website/docs/zh/config/tools/lightningcss-loader.mdx
To disable vendor prefixes, you need set the value to `true`.
`null`
=> docs: fix typo in lightningcss-loader page

website/rspress.config.ts
Simplify Rspress config by removing the `dev.lazyCompilation: true`, it has been enabled by default: https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-beta.4
=> chore: simplify Rspress config

packages/core/src/plugins/cache.ts, packages/core/tests/__snapshots__/cache.test.ts.snap
- Replaced the MD5 hashing algorithm with SHA-256 in the `hash` function for generating digest hashes.
- Increases the hash length from 8 to 16 characters for better security.
- https://lemire.me/blog/2025/01/11/javascript-hashing-speed-comparison-md5-versus-sha-256/
=> perf(cache): switch hash algorithm to SHA-256 and adjust output length

packages/core/src/helpers/index.ts, packages/core/src/plugins/cache.ts
- Use `crypto.hash` in higher versions of Node:
> A utility for creating one-shot hash digests of data. It can be faster than the object-based crypto.createHash() when hashing a smaller amount of data (<= 5MB) that's readily available.
> https://nodejs.org/api/crypto.html#cryptohashalgorithm-data-outputencoding
- Extract the hash helper.
=> perf(hash): use `crypto.hash` in higher versions of Node

pnpm-lock.yaml, website/package.json, website/theme/components/HomeFooter.tsx, website/theme/components/ToolStack.tsx
- Update @rstack-dev/doc-ui to 1.10.0 to add Rstest to homepage.
- This update also includes some UI and text improvements.
Related: https://github.com/rspack-contrib/rstack-doc-ui/releases
=> docs: add Rstest to homepage

website/theme/components/Overview.module.scss
As Rspress 2.0 changed it's default layout, we need to decease the width of Overview component to prevent it being cut.
=> docs: fix overview page layout

pnpm-lock.yaml, website/docs/en/config/resolve/extensions.mdx, website/package.json
- Update Rspress to 2.0.0-beta.6
- No longer need to install the `@rspress/plugin-shiki` package
- https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-beta.6
=> chore(deps): update Rspress to 2.0.0-beta.6

packages/core/src/createContext.ts, packages/core/src/provider/initConfigs.ts
Normalize the `source.tsconfigPath` in environment configuration:
```js
api.modifyRspackConfig((config, { environment }) => {
console.log(environment.config.source.tsconfigPath); // -> Now is absolute path
return config;
});
```
=> feat: normalize tsconfigPath in environment configuration

packages/core/src/cli/init.ts, packages/core/src/createContext.ts, packages/core/src/helpers/path.ts, packages/core/src/provider/initConfigs.ts, packages/core/src/server/compilationManager.ts, packages/core/src/server/overlay.ts, packages/core/src/server/prodServer.ts
Remove duplicated path helper, `getAbsolutePath` and `ensureAbsolutePath` provide the same functionality and can be merged into one.
=> chore: remove duplicated path helper

website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Expanded the description of `rsbuild.context` to include two methods of accessing the property (via the `context` property of the Rsbuild instance and via the `api.context` in plugins) and added code examples.
=> docs: enhance rsbuild.context with access methods

packages/core/src/types/context.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Enhanced the `devServer` property in `RsbuildContext` to include detailed comments, an example usage, and descriptions for its fields (`hostname`, `port`, and `https`)
=> docs: update `context.devServer` with examples

packages/core/src/helpers/index.ts, packages/core/tests/rspackVersion.test.ts
Update the `rspackMinVersion` to 1.2.4 as Rspack's SubresourceIntegrityPlugin plugin was introduced in v1.2.4.
- https://rspack.dev/plugins/rspack/subresource-integrity-plugin
=> fix: update rspackMinVersion to 1.2.4 for SRI support

packages/plugin-svelte/src/index.ts, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Use `swc-loader` to transpile JavaScript code in `.svelte` files to ensure that the compiled JS code can be downgraded as expected.
More test cases will be added in later PRs.
https://discord.com/channels/977448667919286283/1167025132905173063/1373701903644622878
=> fix(plugin-svelte): should transpile JS code in .svelte files

packages/core/src/types/config.ts, packages/core/src/types/utils.ts
During the process of updating config types, I discovered that `DeepReadonly` type was causing more trouble than providing benefits, which led me to decide to replace it with a second-level Readonly to reduce type complexity. I guess this might also improve type inference performance.
=> chore(types): limit readonly config to two level

packages/core/src/cli/init.ts, packages/core/src/config.ts, packages/core/src/types/config.ts, packages/core/tests/__snapshots__/environments.test.ts.snap
This PR ensures that the `dev.watchFiles` option is always normalized into an array, making it easier to consume.
=> fix: narrow watchFiles type in normalized config

e2e/cases/alias/tsconfig-paths-reload/index.test.ts, e2e/cases/alias/tsconfig-paths-reload/rsbuild.config.ts, e2e/cases/alias/tsconfig-paths-reload/src/bar/test.ts, e2e/cases/alias/tsconfig-paths-reload/src/foo/test.ts, e2e/cases/alias/tsconfig-paths-reload/src/index.ts, e2e/cases/alias/tsconfig-paths-reload/tsconfig.json, e2e/cases/cli/build-watch-restart/index.test.ts, e2e/cases/cli/build-watch/index.test.ts, e2e/cases/cli/reload-config/index.test.ts, e2e/cases/plugin-api/plugin-on-exit-hook/index.test.ts, packages/core/src/provider/initConfigs.ts
The paths field in tsconfig.json affects the build result, so when the content of tsconfig.json changes, Rsbuild should reload the dev server to load the new tsconfig.json. This PR adds the paths of tsconfig.json files to `dev.watchFiles` to achieve this.
=> feat: reload server when tsconfig.json is changed

website/docs/en/plugins/list/plugin-react.mdx, website/docs/zh/plugins/list/plugin-react.mdx
Update SWC React options type to match the latest implementation.
Ref: https://github.com/swc-project/swc/blob/883b24c6248fecb223693974951080889bd8827a/packages/types/index.ts#L878-L949
Removed the deprecated `useBuiltins` option, see https://github.com/web-infra-dev/rspack/pull/10410
=> docs: update SWC React options type

packages/core/package.json, packages/core/tests/server.test.ts, pnpm-lock.yaml
Update Rspack to 1.3.11
- https://github.com/web-infra-dev/rspack/releases/tag/v1.3.11
=> feat(deps): update Rspack to 1.3.11

e2e/cases/cli/reload-env/index.test.ts
This pull request enables the `reload-env` E2E test and removes the previous `test.skip` directive.
=> test(e2e): enable reloading env files case

packages/core/src/provider/initConfigs.ts
Added a check to compare the plugin count before and after the `modifyRsbuildConfig` hook execution. If the plugin count changes, a warning is logged to inform users that modifying plugins at this stage is not allowed.
=> fix: add warning for modifying plugins in `modifyRsbuildConfig`

packages/core/src/createRsbuild.ts, packages/core/src/helpers/index.ts, packages/core/src/initPlugins.ts, packages/core/src/loadConfig.ts, packages/core/src/loadEnv.ts, packages/core/src/pluginManager.ts, packages/core/src/plugins/appIcon.ts, packages/core/src/plugins/css.ts, packages/core/src/plugins/define.ts, packages/core/src/plugins/entry.ts, packages/core/src/plugins/html.ts, packages/core/src/plugins/manifest.ts, packages/core/src/plugins/nodeAddons.ts, packages/core/src/plugins/resolve.ts, packages/core/src/plugins/swc.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/provider/initConfigs.ts, packages/core/src/provider/rspackConfig.ts, packages/core/src/rspack/RsbuildHtmlPlugin.ts, packages/core/src/server/cliShortcuts.ts, packages/core/src/server/devServer.ts, packages/core/src/server/environment.ts, packages/core/src/server/helper.ts, packages/core/src/server/open.ts, packages/core/src/server/runner/basic.ts, packages/core/src/server/runner/esm.ts, packages/core/src/server/runner/index.ts, packages/core/src/types/plugin.ts
Improves error and warning messages by standardizing the formatting and enhancing readability using the `color` utility. The changes ensure that messages are consistently styled with dimmed prefixes and highlighted key elements.
- before:
- after:
=> feat: enhance error messages with color for better visibility

website/docs/en/config/output/inline-scripts.mdx, website/docs/en/config/output/inline-styles.mdx, website/docs/zh/config/output/inline-scripts.mdx, website/docs/zh/config/output/inline-styles.mdx
`InlineStyles` and `inlineScripts` types have been deprecated, but the documentation hasn't been updated yet.
- https://rsbuild.dev/config/output/inline-scripts#outputinlinescripts
- https://rsbuild.dev/config/output/inline-styles#outputinlinestyles
- https://github.com/web-infra-dev/rsbuild/blob/main/packages/core/src/types/config.ts#L1198
=> docs: update inlineScripts and inlineStyles

packages/core/src/server/cliShortcuts.ts, packages/core/src/types/config.ts, website/docs/en/config/dev/cli-shortcuts.mdx, website/docs/zh/config/dev/cli-shortcuts.mdx
Allow the CLI shortcuts `help` option to accept custom string:
```ts title="rsbuild.config.ts"
dev: {
cliShortcuts: {
help: 'type "h + enter" to view available commands',
},
},
};
```
=> feat: allow CLI shortcuts help option to accept custom string

packages/core/src/server/open.ts
This pull request refactors the `openBrowser` function to improve performance by deferring the loading of certain modules until they are needed.
=> perf: use dynamic imports for exec and promisify

packages/core/src/server/helper.ts, packages/core/src/server/hmrFallback.ts
Dynamically importing the `node:dns` module for better performance..
=> perf: use dynamic import for node:dns

pnpm-lock.yaml, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx, website/package.json, website/theme/components/HomeFooter.tsx
Update Rslib website URL, Rslib now uses the shorter [rslib.rs](https://rslib.rs/) instead of lib.rsbuild.dev
=> docs: update Rslib website URL

packages/core/src/plugins/fileSize.ts
When using Rspress's LLMs plugin, many markdown files will be emitted, and Rsbuild should display the gzip size of these markdown files.
Fix:
https://v2.rspress.dev/plugin/official-plugins/llms
=> fix: display gzip size for markdown files

website/docs/en/guide/basic/wasm-assets.mdx, website/docs/zh/guide/basic/wasm-assets.mdx
fix inaccurate expression in import wasm module. use `named import` instead of `directly`.
=> docs: fix inaccurate expression in import wasm module

packages/core/src/inspectConfig.ts
avoid colon in output config file name.
=> fix: avoid colon in output config file name

website/docs/en/guide/advanced/ssr.mdx, website/docs/zh/guide/advanced/ssr.mdx
Adds documentation for SSR-specific plugin development. The changes provide examples and guidance on how to adapt Rsbuild and Rspack configurations, as well as how to transform code for SSR and client environments.
=> docs: SSR-specific plugins

website/docs/public/netlify.toml
Now that DNS propagation should be complete and we can enable domain redirection.
- https://www.whatsmydns.net/#NS/rsbuild.rs:
https://github.com/web-infra-dev/rsbuild/pull/5327
=> docs: enable domain redirection

website/docs/en/guide/advanced/browserslist.mdx
Fix an invalid browserslist query example, `Internet Explorer 11` should be `IE 11`.
=> docs: fix invalid browserslist query example

website/docs/en/api/javascript-api/environment-api.mdx, website/docs/zh/api/javascript-api/environment-api.mdx
Added two ways to access the environment context: via Rsbuild's plugin hooks and the Environment API, with corresponding links for better guidance.
=> docs: clarify methods to access environment context

packages/core/src/types/config.ts, website/docs/en/config/source/entry.mdx, website/docs/en/guide/basic/html-template.mdx, website/docs/zh/config/source/entry.mdx, website/docs/zh/config/tools/html-plugin.mdx, website/docs/zh/guide/basic/html-template.mdx
Added detailed explanations of how Rsbuild generates HTML files for each entry defined in `source.entry`, including the use of `html-rspack-plugin` and the ability to control HTML generation via the `html` property in the entry description object.
=> docs: enhance HTML generation for source.entry

packages/core/tests/css.test.ts, packages/core/tests/define.test.ts, packages/core/tests/helpers.test.ts, packages/core/tests/html.test.ts, packages/core/tests/resolve.test.ts, packages/core/tests/tsconfig.json
Updates type annotations and mock contexts to fix all type issues in unit test cases.
=> test(ut): fix all type issues

website/docs/en/config/source/include.mdx, website/docs/en/guide/advanced/browser-compatibility.mdx, website/docs/zh/config/source/include.mdx, website/docs/zh/guide/advanced/browser-compatibility.mdx
Reorganized sections to focus on "Compilation scope" instead of "Downgrade method," providing clearer explanations for Rsbuild's categorization and rationale.
=> docs: update terminology and clarify compilation scope

e2e/cases/source/source-include/index.test.ts, e2e/cases/source/test.js, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
This PR changes the default `source.include` behavior to make SWC compile modules outside the project, which ensures that JavaScript modules in the monorepo can be compiled correctly to avoid compatibility issues.
While this may slightly increase compile times in certain cases within a monorepo, it can help to improve the stability and browser compatibility of web apps.
=> feat: let SWC compile modules outside the project

website/docs/en/plugins/dev/core.mdx, website/docs/zh/plugins/dev/core.mdx
Clarify the relationship between the `api.transform` parameters and the corresponding Rspack loader APIs by adding explicit references to the relevant API documentation.
=> docs: enhance parameter descriptions of api.transform

packages/create-rsbuild/template-common/gitignore
Updates the `.gitignore` file in the `template-common` directory to add patterns to ignore `rspack` profile directories (`.rspack-profile-*`).
- https://rsbuild.rs/guide/debug/build-profiling#rspack-profiling
=> feat(create-rsbuild): update .gitignore to include rspack profile

e2e/cases/assets/raw-query/index.test.ts, e2e/cases/assets/raw-query/src/bar.ts, e2e/cases/assets/raw-query/src/baz.tsx, e2e/cases/assets/raw-query/src/foo.js, e2e/cases/assets/raw-query/src/index.js, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/configChain.ts, packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Add support for importing the raw content of JavaScript, TypeScript, and JSX files through the `?raw` query parameter. This makes the `?raw` query more general and intuitive.
```ts
import rawJs from './script1.js?raw';
import rawTs from './script2.ts?raw';
import rawJsx from './script3.jsx?raw';
import rawTsx from './script4.tsx?raw';
console.log(rawJs); // The raw content of the JS file
console.log(rawTs); // The raw content of the TS file
console.log(rawJsx); // The raw content of the JSX file
console.log(rawTsx); // The raw content of the TSX file
```
https://github.com/web-infra-dev/rsbuild/discussions/2665
=> feat: allow to get raw JS content with `?raw`

e2e/cases/assets/raw-query/index.test.ts, packages/plugin-react/src/index.ts, packages/plugin-react/src/react.ts, website/docs/en/plugins/list/plugin-react.mdx, website/docs/zh/plugins/list/plugin-react.mdx
Excluding raw JS modules from React Refresh processing to ensure that the `?raw` query can get the original file content.
- https://github.com/web-infra-dev/rsbuild/pull/5353
=> fix(plugin-react): skip React Refresh injection for raw JS content

website/docs/en/guide/basic/static-assets.mdx, website/docs/zh/guide/basic/static-assets.mdx
Update the documentation to reflect the support for importing the raw content of JS, TS, JSX, and TSX files using the `?raw` query parameter.
https://github.com/web-infra-dev/rsbuild/pull/5353
=> docs: update static assets guide to include raw JS content support

website/docs/en/config/tools/swc.mdx, website/docs/zh/config/tools/swc.mdx
This pull request updates the documentation for the `tools.swc` configuration, clarifying the type definition and default options.
=> docs: clarify swc-loader default options

packages/core/tests/cache.test.ts, packages/core/tests/html.test.ts
Remove unnecessary mocks from the test files to simplify the test setup and improve maintainability.
=> test(ut): remove useless mock

packages/core/src/plugins/css.ts, packages/core/src/types/config.ts, packages/core/src/types/thirdParty.ts
When user passes a PostCSS plugin to `tools.postcss` config, the plugin may depend on a different version of PostCSS, which can cause type errors. This PR loosens the PostCSS plugin type to resolve type issue. 
Fix ecosystem CI: https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions/runs/15458968100/job/43516378827
=> fix(type): make the PostCSS plugin type loose

packages/compat/plugin-webpack-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-vue/package.json, pnpm-lock.yaml, scripts/config/package.json, scripts/test-helper/package.json
Update @rslib/core to 0.9.2 to use the new ESM output.
- before:
```
File (esm_index)   Size       
dist/index.js      416.6 kB
```
- after:
```
File (esm_index)   Size       
dist/index.js      389.1 kB
```
- https://github.com/web-infra-dev/rslib/releases/tag/v0.9.2
=> chore(deps): update @rslib/core to 0.9.2

packages/create-rsbuild/template-preact-ts/src/env.d.ts, packages/create-rsbuild/template-vanilla-ts/src/env.d.ts
Fix missing `env.d.ts` in some templates.
https://github.com/web-infra-dev/rsbuild/issues/5380
=> fix(create-rsbuild): missing env.d.ts in some templates

packages/core/src/helpers/index.ts, packages/core/src/plugins/cache.ts
Switching from sync to async imports of the `crypto` module. Additionally, it updates the `hash` function to return a `Promise` and adjusts its usage accordingly.
=> perf: lazy import node crypto

scripts/config/tsconfig.json
To avoid side effect imports, enable the `noUncheckedSideEffectImports` setting in tsconfig.json for Rsbuild packages.
- https://www.typescriptlang.org/tsconfig/#noUncheckedSideEffectImports
=> chore: enable `noUncheckedSideEffectImports` in tsconfig.json

packages/core/types.d.ts
Add type declarations for normal CSS module, this is required when TypeScript's new `noUncheckedSideEffectImports` option is enabled.
- resolve https://github.com/web-infra-dev/rsbuild/issues/5380
- https://www.typescriptlang.org/tsconfig/#noUncheckedSideEffectImports
=> feat(types): add type declarations for normal CSS module

packages/create-rsbuild/src/index.ts
=> fix(create-rsbuild): correct ESLint template name in react18-ts preset

website/docs/en/guide/migration/vite.mdx, website/docs/zh/guide/migration/vite.mdx
Add more hooks to migration guide:
- Added `configEnvironment` hook with a link to `modifyEnvironmentConfig`
- Expanded the description of `transformIndexHtml` to include the `modifyHTMLTags` hook.
=> docs: add more hooks to migration guide

website/docs/en/guide/basic/typescript.mdx, website/docs/zh/guide/basic/typescript.mdx
Update TypeScript guide to include the `verbatimModuleSyntax` option. It is recommended and will supersede `isolatedModules`.
- https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax
- https://github.com/microsoft/TypeScript/issues/51479#issuecomment-1335765803
=> docs: update TypeScript guide to include verbatimModuleSyntax

scripts/config/tsconfig.json
Set types field in tsconfig, this should make `tsc` a bit faster.
https://github.com/microsoft/TypeScript/issues/58420#issuecomment-2919996436
=> chore: set types field in tsconfig

packages/plugin-sass/package.json, pnpm-lock.yaml
Unpin sass-embedded and update to the latest v1.89.2 to fix the `Package subpath './codegenv2' is not defined by "exports" in //node_modules/.pnpm/sass-embedded@1.89.1/node_modules/@bufbuild/protobuf/package.json` error.
https://github.com/web-infra-dev/rsbuild/pull/5360
=> fix(plugin-sass): unpin sass-embedded and update to v1.89.2

packages/core/package.json, packages/core/src/plugins/rspackProfile.ts, packages/core/src/server/devMiddlewares.ts, pnpm-lock.yaml, scripts/dictionary.txt
- Update @rspack/core to v1.4.0-beta.0
- Update tracing logic to match the latest Rspack implementation
https://github.com/web-infra-dev/rspack/releases/tag/v1.4.0-beta.0
=> feat(deps): update @rspack/core to v1.4.0-beta.0

packages/core/src/plugins/basic.ts, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap
Rspack 1.4.0-beta.0 enables `incremental` by default and we can remove the `incremental` config from Rsbuild.
- https://github.com/web-infra-dev/rspack/pull/10623
=> chore: remove useless incremental config

website/docs/en/guide/styling/css-modules.mdx, website/docs/zh/guide/styling/css-modules.mdx
Updates the documentation for CSS Modules to include information about using global styles with the `:global()` pseudo-class selector. The changes provide examples and explanations for combining local and global selectors, as well as nesting `:global()`.
- https://github.com/css-modules/css-modules/blob/c7bf6c02472fdce4dd8e569abc10d2aeb234e1c2/docs/composition.md#exceptions
- https://github.com/web-infra-dev/rsbuild/issues/5405
=> docs: add section on global styles in CSS Modules

packages/plugin-less/src/index.ts
Added the `lessLogAsWarnOrErr` option to `LessLoaderOptions`. When enabled, Less warnings and errors will be treated as Rspack warnings and errors.
- https://github.com/webpack-contrib/less-loader?tab=readme-ov-file#lesslogaswarnorerr
=> feat(plugin-less): add type for `lessLogAsWarnOrErr` option

e2e/cases/cli/log-level/index.test.ts, e2e/cases/cli/log-level/src/index.js, packages/core/src/cli/commands.ts, packages/core/src/cli/init.ts, packages/core/src/types/config.ts, website/docs/en/guide/basic/cli.mdx, website/docs/zh/guide/basic/cli.mdx
Add a new `--log-level` flag to the Rsbuild CLI, allowing users to specify the verbosity of logs (`info`, `warn`, `error`, or `silent`).
=> feat(CLI): add --logLevel flag

e2e/cases/cli/log-level/index.test.ts, packages/core/src/cli/index.ts
Added logic to parse `--log-level` flag in the `runCLI` function, ensuring the log level is set (`warn`, `error`, or `silent`) before any logs are printed.
https://github.com/web-infra-dev/rsbuild/issues/5194
=> fix: ensure log level can work for all logs

packages/core/package.json, packages/core/src/index.ts, pnpm-lock.yaml
- Export `LogLevel` type from core
- Update `rslog` to v1.2.7
- https://github.com/rspack-contrib/rslog/releases/tag/v1.2.7
=> feat(core): export `LogLevel` type

e2e/scripts/helper.ts, e2e/scripts/shared.ts
Deleted the `fix-react-refresh-in-rsbuild` plugin, which was a temporary solution to address HMR issues with the `css-loader`. This cleanup simplifies the codebase and removes a workaround specific to the repository. 
https://github.com/web-infra-dev/rspack/issues/5723
=> test(e2e): remove temporary plugin

packages/core/src/server/devMiddlewares.ts
`lazyCompilationMiddleware` now supports lazy compilation when using multiple compiler.
- https://github.com/web-infra-dev/rspack/pull/9828
=> feat: support lazy compilation in multi environments

packages/core/src/types/config.ts, packages/core/src/types/thirdParty.ts
Use a loose PostCSS plugin type that accepts plugins from different PostCSS versions. This helps avoid type conflicts when user projects use different PostCSS versions.
resolve https://github.com/web-infra-dev/rsbuild/issues/5439
=> fix(types): make PostCSSPlugin type loose

biome.json, website/theme/components/Overview.tsx, website/theme/components/Step.tsx
https://github.com/web-infra-dev/rsbuild/blob/main/website/theme/components/utils.ts#L12C1-L21C2
```
export function useI18nUrl() {
const lang = useLang();
const {
siteData: { lang: defaultLang },
} = usePageData();
return useCallback(
(url: string) => withBase(lang === defaultLang ? url : `/${lang}${url}`),
[lang, defaultLang],
);
}
```
The main benefits of this function are:
**Encapsulation of logic:** It encapsulates the logic for generating localized URLs based on the current language and default language, making your components cleaner and more maintainable.
**Hook compliance:**  By returning a memoized function via useCallback, it allows you to use the returned function anywhere in your component (including loops and callbacks) without violating React's hooks rules.
**Performance …
=> docs(website): use useI18nUrl to avoid useHookAtTopLevel error

website/theme/components/utils.ts
Remove unused `useUrl` helper from website.
https://github.com/web-infra-dev/rsbuild/pull/5453
=> chore(website): remove unused useUrl helper

packages/core/src/server/socketServer.ts
https://github.com/web-infra-dev/rsbuild/blob/main/packages/core/src/server/socketServer.ts#L79
```
if (this.heartbeatTimer !== null) {
this.heartbeatTimer = setTimeout(
this.checkSockets,
CHECK_SOCKETS_INTERVAL,
).unref();
}
```
I see that heartbeatTimer is created by setTimeout, so should clearTimeout be used when recycling and clearing? I guess this may be left by using setInterval before.
=> fix(socketServer): use clearTimeout instead of clearInterval

e2e/cases/output/manifest-environment/index.test.ts, e2e/cases/server/custom-server/scripts/pureServer.mjs, e2e/cases/server/environments/index.test.ts, e2e/cases/server/fallback/index.test.ts, e2e/cases/server/setup-middlewares/index.test.ts, e2e/cases/server/ssr-type-module/rsbuild.config.ts, e2e/cases/server/ssr/rsbuild.config.ts, packages/core/src/server/devMiddlewares.ts, packages/core/src/types/config.ts, website/docs/en/config/dev/setup-middlewares.mdx, website/docs/en/guide/basic/server.mdx, website/docs/zh/config/dev/setup-middlewares.mdx, website/docs/zh/guide/basic/server.mdx
The `dev.setupMiddlewares` requires the user to pass an array which is redundant.
This PR allows `dev.setupMiddlewares` to pass a function directly to streamline usage.
=> feat: streamline setupMiddlewares usage

e2e/cases/lazy-compilation/port-placeholder/index.test.ts, packages/core/src/plugins/lazyCompilation.ts, packages/core/src/server/devMiddlewares.ts
- Moved the lazy compilation port placeholder replacement logic from `devMiddlewares.ts` to `lazyCompilation.ts`, ensuring it is applied consistently. 
- Re-enabled the previously skipped E2E test for verifying the replacement of the port placeholder with the actual port.
=> fix: lazy compilation port replacement

website/docs/en/plugins/list/plugin-svelte.mdx, website/docs/zh/plugins/list/plugin-svelte.mdx
add less alias import solution to fix #5372
=> docs(svelte): add less alias import solution

e2e/cases/config/rspack-config-validate/index.test.ts, e2e/playwright.config.ts, packages/core/src/plugins/basic.ts
Disable Rspack's config schema validation to improve performance.
Rsbuild has ensured that the built-in Rspack configuration is correct through TypeScript, so it is usually redundant to perform schema validation at runtime. Disabling schema validation can improve performance by 20ms to 30ms.
This can be manually enabled via `RSPACK_CONFIG_VALIDATE=strict`:
```bash
RSPACK_CONFIG_VALIDATE=strict rsbuild build
```
See https://github.com/web-infra-dev/rspack/pull/10768 for performance comparison.
=> perf: disable Rspack config schema validation

packages/core/src/plugins/basic.ts, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap
This PR disables the default bundler info injection to reduce bundle size. This removes the Rspack version information from the bundle code and is not noticeable to users.
- before:
```txt
File (web)                           Size      Gzip   
dist/static/js/index.a18d906c.js     0.37 kB   0.28 kB
```
- after:
```txt
File (web)                           Size      Gzip   
dist/static/js/index.c2760cca.js     0.18 kB   0.17 kB
```
- https://rspack.rs/config/experiments#rspackfuturebundlerinfo
- https://github.com/web-infra-dev/rspack/issues/10783
=> perf: disable bundler info injection

packages/core/src/types/hooks.ts, website/docs/en/config/tools/bundler-chain.mdx, website/docs/en/config/tools/rspack.mdx, website/docs/zh/config/tools/bundler-chain.mdx, website/docs/zh/config/tools/rspack.mdx
This pull request introduces enhancements to the `ModifyChainUtils` type and updates related documentation. The changes add new JSDoc to the type and refine the documentation for clarity and consistency.
=> docs: improve env and target contexts

package.json, pnpm-workspace.yaml
I noticed that it seems the best approach seems to be to move all the settings to pnpm-workspace.yaml.
https://github.com/orgs/pnpm/discussions/9037
https://github.com/pnpm/pnpm/blob/main/pnpm-workspace.yaml#L334
https://github.com/vitejs/vite/pull/19895/files
=> chore: move all pnpm settings to pnpm-workspace.yaml

biome.json
Maybe it is also a good practice to `specify the relative path of the @biomejs/biome package`. I searched many repositories in github that use this method. The advantage of doing this is that there is no need to manually update the corresponding version.
https://biomejs.dev/reference/configuration/#schema
=> chore(biome): specify a relative path to the schema inside the package

e2e/cases/config/inspect-config/index.test.ts, packages/core/src/inspectConfig.ts, packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
support output extra configs when `inspectConfig`. For example, some upper-level framework configurations(rstest, etc.).
=> feat: support output extra configs when `inspectConfig`

packages/core/src/plugins/basic.ts
Since https://github.com/web-infra-dev/rspack/issues/10783 has been resolved in Rspack 1.4.1, we can now disable the bundler info in all cases.
=> fix: disable bundle info when SRI is enabled

.npmrc, pnpm-workspace.yaml
Move pnpm config from .npmrc to pnpm-workspace.yaml, fix the npm warning:
=> chore: move pnpm config from .npmrc to pnpm-workspace.yaml

.github/renovate.json5, packages/core/package.json, packages/core/prebundle.config.mjs, packages/core/src/server/open.ts, pnpm-lock.yaml
- Update `open` from v8 to v10
- Since open v10 is a pure ESM package, we use Rslib to bundle it instead of using `prebundle`.
- Removed the check for CodeSandbox, since Rslib no longer bundles the [xdg-open](https://github.com/sindresorhus/open/blob/main/xdg-open) script of the `open` package, we should no longer need to recognize CodeSandbox (this requires further testing)
- Add error handling for child process errors.
- This PR should fix the open error on StackBlitz:
- https://github.com/sindresorhus/open/releases
- https://github.com/sindresorhus/open/blob/39f7d2d4812f56ef77b2affec8e2110c89c27224/index.js#L204-L229
- https://github.com/vitejs/vite/pull/16726
- https://github.com/sindresorhus/open/issues/359
=> feat: update open to v10 and improve error handling

packages/core/package.json, packages/core/prebundle.config.mjs, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-sass/package.json, packages/plugin-svgr/package.json, pnpm-lock.yaml
This PR minifies the pre-bundled webpack-bundle-analyzer to reduce install size (474KB -> 231KB).
We do not enable minification for most pre-bundle packages, which is for debugging convenience. However, given that the size of webpack-bundle-analyzer is quite large and it is not part of the core feature, we can compress it to reduce its size.
=> perf: minify the prebundled webpack-bundle-analyzer

e2e/cases/rspack-profile/dev.mjs, e2e/cases/rspack-profile/index.test.ts
Fix the unstable rspack profile E2E cases, see:
=> test(e2e): fix unstable rspack profile cases

website/docs/en/config/tools/bundler-chain.mdx, website/docs/zh/config/tools/bundler-chain.mdx, website/docs/zh/guide/configuration/rspack.mdx
There seems to be a problem with the anchor jump in the rsbuild documentation. Steps to reproduce: 
1. Open https://rsbuild.rs/config/tools/bundler-chain
2. Click on "RspackChain examples" 
3. Does not accurately jump to "Use bundler chain"
https://rsbuild.rs/config/tools/bundler-chain
=> docs: fix use-bundler-chain anchor

packages/core/src/server/open.ts
I removed this condition in https://github.com/web-infra-dev/rsbuild/pull/5500, but after testing I think it would be better to add it back, since we should not open a new tab for `localhost:3000`.
=> fix(open): skip opening browser in CodeSandbox

packages/core/src/types/config.ts, website/docs/en/config/server/compress.mdx, website/docs/zh/config/server/compress.mdx
- Added a detailed explanation and example usage of the `server.compress.filter` function in the options section.
- Updated the `server.compress` type definition to include the new `filter` function.
- https://github.com/web-infra-dev/rsbuild/pull/5520
=> docs: add `compress.filter` option

packages/core/src/server/gzipMiddleware.ts, packages/core/src/server/prodServer.ts, packages/core/src/types/config.ts, website/docs/en/config/server/compress.mdx, website/docs/zh/config/server/compress.mdx
- Added a new `compress.level` option to set the level of zlib compression to apply to responses.
- Updated the documentation to provide a detailed explanation of the `level` option, including its type, default values, and usage examples.
- https://github.com/expressjs/compression?tab=readme-ov-file#level
=> feat(server): add `compress.level` option

website/docs/en/plugins/dev/hooks.mdx, website/docs/zh/plugins/dev/hooks.mdx
Added a tip explaining the execution order when using `modifyHTML`, `modifyHTMLTags`, and `html.tags` options together.
=> docs: clarify execution order with `modifyHTML` and `html.tags`

packages/core/src/client/hmr.ts, packages/core/src/server/compilationManager.ts
- Normalize config types in compilation manager to align type usage across files.
- Removed unused default value in `formatURL`.
=> refactor: normalize config types in compilation manager

e2e/cases/assets/raw-query/index.test.ts, e2e/cases/assets/raw-query/src/foo.js, e2e/cases/assets/raw-query/src/index.js, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Updated the regex for scripts resource queries to precisely match `?raw` by using `/^\?raw$/`. This ensures stricter validation for raw imports.
=> fix: ensure that raw query of scripts can be accurately matched

website/docs/en/guide/basic/typescript.mdx
Fixes a typo in the tsconfig.json example for `isolatedModules` (for older typescript versions)
Typo introduced in https://github.com/web-infra-dev/rsbuild/pull/5399
=> docs: Update typescript.mdx with fixed typo in `isolatedModules ` example

packages/core/types.d.ts, website/docs/en/guide/styling/css-usage.mdx, website/docs/zh/guide/styling/css-usage.mdx
Update the raw import JSDoc to include scripts.
https://rsbuild.rs/guide/basic/static-assets#import-as-string
=> docs: update raw import JSDoc to include scripts

e2e/cases/source/source-exclude/index.test.ts
Use a valid browserslist value instead of using the dead IE in our E2E case.
https://github.com/swc-project/swc/issues/1377#issuecomment-789633974
=> test(e2e): use valid browserslist value

e2e/cases/assets/raw-query/index.test.ts, e2e/cases/assets/raw-query/src/index.js, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/asset.ts, packages/core/tests/__snapshots__/asset.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/plugin-react/src/index.ts, packages/plugin-react/src/react.ts, packages/plugin-svgr/src/index.ts, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap, website/docs/en/plugins/dev/core.mdx, website/docs/en/plugins/list/plugin-react.mdx, website/docs/zh/plugins/dev/core.mdx, website/docs/zh/plugins/list/plugin-react.mdx
Improving query matching for raw and inline asset content, ensuring stricter regex patterns, and adding new test cases for edge scenarios.
- https://github.com/web-infra-dev/rsbuild/pull/5538
=> fix: ensure that raw query of assets can be accurately matched

pnpm-lock.yaml, website/docs/en/guide/advanced/ssr.mdx, website/docs/en/guide/basic/typescript.mdx, website/docs/zh/guide/basic/typescript.mdx, website/package.json
Update Rspress to 2.0.0-beta.19 and fix all dead links.
- https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-beta.19
=> chore(deps): update Rspress to 2.0.0-beta.19

packages/core/src/types/hooks.ts, website/docs/en/api/javascript-api/environment-api.mdx, website/docs/zh/api/javascript-api/environment-api.mdx
Added a new section explaining `webSocketToken`, including its type, usage, and an example of establishing a WebSocket connection with the Rsbuild dev server.
- https://github.com/web-infra-dev/rsbuild/discussions/5527
- https://github.com/web-infra-dev/rsbuild/pull/5531
=> docs: add webSocketToken to documentation

packages/core/src/helpers/index.ts, packages/core/tests/helpers.test.ts
Updates the `prettyTime` function to improve how time is formatted for better readability and accuracy.
- before: `20.57 m`
- after: `20 m 34 s`
=> fix: improve formatting of minutes in build time

rstest.config.ts, scripts/test-helper/src/index.ts
- Simplify Rstest config, remove unused fields.
- Remove unused test helpers.
=> chore: simplify Rstest config

rstest.config.ts
test: speed up UT by external `@rsbuild/core`.
`@rsbuild/core` has already been built, so there is no need to build it again in test.
=> test: speed up UT by external `@rsbuild/core`

packages/core/src/server/helper.ts
Use `hostname` to determine local or network
=> fix: Use `hostname` to determine local or network

packages/core/package.json
Update Node.js engine requirement to >=16.17.0 to allow using `import { constants } from 'node:fs/promises';`
- resolve https://github.com/web-infra-dev/rsbuild/issues/5566
- https://github.com/sindresorhus/open/blob/main/index.js#L7
- https://nodejs.org/api/fs.html#fspromisesconstants
=> fix: update Node.js engine requirement to >=16.17.0

packages/core/package.json, patches/open@10.1.2.patch, pnpm-lock.yaml, pnpm-workspace.yaml
- Revert "fix: update Node.js engine requirement to >=16.17.0 (https://github.com/web-infra-dev/rsbuild/pull/5567)
- patch open to maintaining Node < 16.17 compatibility
https://github.com/web-infra-dev/rsbuild/issues/5566#issuecomment-3051920591
=> fix: patch open to maintaining Node 16.10 compatibility

packages/core/src/plugins/cache.ts
Updated the log level to `debug` for the message indicating that Rspack persistent cache is enabled, since the Rspack persistent cache is now more stable.
=> chore(cache): change cache enabled message to debug log

e2e/cases/create-rsbuild/tools.test.ts, packages/create-rsbuild/package.json, pnpm-lock.yaml
Update `create-rstack` to v1.5.4 to update the default ESLint config in React templates.
https://github.com/rspack-contrib/create-rstack/releases/tag/v1.5.4
=> fix(create-rsbuild): update ESLint config in React templates

packages/core/src/index.ts
Export the `HtmlTag` type from '@rsbuild/core'.
=> feat: export `HtmlTag` type

packages/create-rsbuild/template-react-ts/src/env.d.ts, packages/create-rsbuild/template-react18-ts/src/env.d.ts
Before
After
type declaration should go in template project since `rsbuild/core` doesn't depend on React
=> fix(types): type error when importing SVG file with React query

website/docs/en/guide/migration/vite.mdx, website/docs/zh/guide/migration/vite.mdx
Provide information about Rsbuild's built-in support for TypeScript path aliases and the removal of the `vite-tsconfig-paths` dependency.
=> docs: add section on vite-tsconfig-paths support

e2e/cases/cli/shortcuts/index.test.ts, e2e/cases/server/print-urls/index.test.ts, packages/core/src/server/cliShortcuts.ts, packages/core/src/server/helper.ts, packages/core/tests/server.test.ts
When I run the project locally, the arrows and prompts are a bit tight, this should be a problem in windows environment, it behaves well in mac.
But I found that vite doesn't have this kind of problem, I checked the source code and found that they use two spaces, I don't know if it's adopted or not, I'll create a PR first, I hope to cause disturbance.
https://github.com/vitejs/vite/blob/6bc8bf634d4a2c9915da9813963dd80a4186daeb/packages/vite/src/node/logger.ts#L176
before：
| windows powershell  | windows wsl |
|--------------|--------------|
| <img width="109" height="227" alt="image" src="https://github.com/user-attachments/assets/b824f823-6a1d-4738-81fb-8374b0d90814" /> | <img width="155" height="224" alt="image" src="https://github.com/user-attachments/assets/5534198f-621e-4e4c-95de-694d …
=> fix(cli): increase arrow spacing

website/docs/en/guide/migration/vite-plugin.mdx, website/docs/zh/guide/migration/vite-plugin.mdx
This pull request updates the migration guides to provide an example to guide users in migrating the `transformIndexHtml` hook to Rsbuild plugin.
=> docs: add example for migrating HTML hook

website/docs/en/guide/migration/vite-plugin.mdx, website/docs/zh/guide/migration/vite-plugin.mdx
This pull request updates the migration guides to provide an example to guide users in migrating the `configureServer` hook to Rsbuild plugin.
=> docs: add example for migrating configureServer hook

packages/core/src/server/devServer.ts
fix rspack panic when call `stats.toJson()`  during rebuild,  rsbuild should wait the last compile done when `loadBundle`. Because, in the next compilation rspack will clean up the old compilation, but `stats.toJson` read from the old compilation, so the panic happens.
https://github.com/web-infra-dev/rspack/issues/11005
=> fix: wait until the last build is finished before calling `stats.toJson`

packages/core/src/hooks.ts, packages/core/src/initPlugins.ts, packages/core/src/pluginManager.ts, packages/core/src/types/plugin.ts, packages/core/src/types/rsbuild.ts
Improve code readability and simplify plugin environment handling by removing the `RSBUILD_ALL_ENVIRONMENT_SYMBOL` variable.
=> refactor: simplify plugin environment handling

e2e/cases/plugin-api/plugin-apply/index.test.ts, e2e/cases/plugin-api/plugin-apply/rsbuild.config.ts, e2e/cases/plugin-api/plugin-apply/src/index.css, e2e/cases/plugin-api/plugin-apply/src/index.js, packages/core/src/pluginManager.ts, packages/core/src/provider/initConfigs.ts, packages/core/src/types/plugin.ts, packages/core/tests/pluginStore.test.ts
Allow plugin to specify the `apply` property:
- `'serve'`: Apply the plugin when starting the dev server or preview server.
- `'build'`: Apply the plugin during build.
If not specified, the plugin will be applied during both serve and build.
```ts
const servePlugin: RsbuildPlugin = {
name: 'serve-plugin',
apply: 'serve',
setup(api) {
// ...
},
};
```
=> feat: allow plugin to specify `apply` property

e2e/cases/javascript-api/get-stats/index.test.ts, e2e/cases/javascript-api/get-stats/src/index.js, packages/core/src/server/devServer.ts
Fix failed to call `getStats` before the first build is finished, the `waitLastCompileDone` should be a pending Promise by default.
- https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions/runs/16360607946/job/46227603075
- https://github.com/web-infra-dev/rsbuild/pull/5615
=> fix: failed to call `getStats` before the first build is finished

website/docs/en/guide/advanced/env-vars.mdx, website/docs/zh/guide/advanced/env-vars.mdx
Updated instructions for extending `import.meta.env` types in TypeScript, including a reference to Rsbuild's default type definitions and an example of how to extend the `ImportMetaEnv` interface.
=> docs: enhance type declaration guidance for env variables

packages/core/types.d.ts, website/docs/en/guide/advanced/env-vars.mdx, website/docs/zh/guide/advanced/env-vars.mdx
Added a new `strictImportMetaEnv` type option to allow control of type safety for `import.meta.env`.
- resolve https://github.com/web-infra-dev/rsbuild/issues/5617
=> feat: allow control of type safety for import.meta.env

packages/core/src/plugins/lazyCompilation.ts
Adjust when the lazy compilation plugin can be applied. Lazy compilation is always available when the dev server is started, not when `mode` is `development`.
=> fix: adjust when lazy compilation can be applied

website/docs/en/guide/migration/vite-plugin.mdx, website/docs/zh/guide/migration/vite-plugin.mdx
This pull request updates the migration guides to provide an example to guide users in migrating the `configResolved` hook and `apply` property to Rsbuild plugin.
=> docs: enhance migration guide for resolved config

website/docs/en/guide/migration/vite-plugin.mdx, website/docs/zh/guide/migration/vite-plugin.mdx
This pull request updates the migration guides to provide an example to guide users in migrating the `configEnvironment` hook to Rsbuild plugin.
=> docs: add example for migrating configEnvironment hook

pnpm-lock.yaml, website/package.json
Update @rstack-dev/doc-ui to 1.10.8 to fix the duplicated navbar logo.
- https://github.com/rspack-contrib/rstack-doc-ui/releases/tag/v1.10.8
=> docs(deps): update @rstack-dev/doc-ui to 1.10.8

packages/core/src/pluginManager.ts, packages/core/src/types/plugin.ts, packages/core/tests/pluginDependencies.test.ts, packages/core/tests/pluginEnforce.test.ts
- Added an optional `enforce` property to the Rsbuild plugin to specify execution order.
- Introduced `sortPluginsByEnforce` to sort plugins based on their `enforce` property.
=> feat(plugin): support for the `enforce` property

patches/wsl-utils@0.1.0.patch, pnpm-lock.yaml, pnpm-workspace.yaml
The same as https://github.com/web-infra-dev/rsbuild/pull/5570.
- https://github.com/web-infra-dev/rsbuild/issues/5655
=> fix: patch is-wsl to maintaining Node 16.10 compatibility

website/docs/en/guide/migration/cra.mdx, website/docs/zh/guide/migration/cra.mdx
This pull request updates the documentation for migrating from CRA to Rsbuild by adding a new recommended testing framework, Rstest, alongside Jest and Vitest.
- https://rstest.rs/
=> docs: mention Rstest in CRA guide

rstest.config.ts
Updates the tsconfig.json path in the `rstest.config.ts` file to use the shared config file.
=> test: use the shared tsconfig

e2e/cases/typescript/type-re-exports/index.test.ts, e2e/cases/typescript/type-re-exports/src/bar.ts, e2e/cases/typescript/type-re-exports/src/foo.ts, e2e/cases/typescript/type-re-exports/src/index.ts, e2e/cases/typescript/type-re-exports/tsconfig.json, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/basic.ts, packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
Enable the new `parser.javascript.typeReexportsPresence` feature in Rspack to tolerate errors relating to type re-exports.
This is helpful for some older TypeScript projects that may not have "verbatimModuleSyntax" or "isolatedModules" enabled in their tsconfig.json, or re-export all types using the `type` modifier.
- https://rspack.rs/config/module#moduleparserjavascripttypereexportspresence
=> feat: enable error tolerance for type re-exports

packages/core/src/index.ts, packages/core/src/pluginHelper.ts, packages/core/src/plugins/minimize.ts, packages/core/src/plugins/moduleFederation.ts, packages/core/src/plugins/output.ts, packages/core/src/plugins/progress.ts, packages/core/src/plugins/rspackProfile.ts, packages/core/src/plugins/sri.ts, packages/core/src/provider/build.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/provider/rspackConfig.ts, packages/core/src/rspack.ts, packages/core/src/server/devMiddlewares.ts
Currently, Rspack only provides a CJS bundle, so we use require to load it for better startup performance. If we use `import { rspack } from '@rspack/core'`, Node.js will use `cjs-module-lexer` to parse it, which slows down startup by 25-30ms.
We can remove this module once `@rspack/core` provides an ESM bundle in the future.
- https://github.com/nodejs/cjs-module-lexer
=> perf: require rspack to improve startup performance

e2e/cases/cli/build-watch-options/index.test.ts, e2e/cases/cli/build-watch-options/rsbuild.config.mjs, e2e/cases/cli/build-watch-options/src/bar.js, e2e/cases/cli/build-watch-options/src/foo.js, e2e/cases/cli/build-watch-options/src/index.js, e2e/cases/cli/build-watch-options/tsconfig.json, e2e/cases/cli/build-watch/tsconfig.json, packages/core/src/provider/build.ts
This PR fixes support for custom watch options in the build watch mode and adds E2E tests to validate this functionality.
When calling the `compiler.watch()` method, we should pass `watchOptions` to ensure that Rspack can read it correctly.
- https://rspack.rs/api/javascript-api/compiler#watch-1
=> fix: watch options not work in build watch mode

packages/core/src/helpers/stats.ts, packages/core/src/plugins/fileSize.ts, packages/core/src/server/middlewares.ts
Passing fine-grained stats options to `stats.getJson()` to reduce the cost when previewing static assets.
- https://rspack.rs/api/javascript-api/stats#tojson
=> perf: reduce getStatus cost when previewing static assets

packages/core/package.json, pnpm-lock.yaml
Update rspack-chain to 1.3.0 to reduce the bundle size of `@rsbuild/core`.
- https://github.com/rspack-contrib/rspack-chain/releases/tag/v1.3.0
=> perf(deps): update rspack-chain to 1.3.0

.github/renovate.json5, e2e/cases/plugin-svelte/package.json, packages/plugin-less/package.json, pnpm-lock.yaml
Pin less version to 4.3.0 to fix the `@apply` syntax error.
- https://github.com/web-infra-dev/rsbuild/issues/5688
- https://github.com/web-infra-dev/rsbuild/discussions/5689
=> fix(plugin-less): pin less version to 4.3.0

packages/core/package.json, packages/core/prebundle.config.mjs, packages/core/src/server/devMiddlewares.ts, packages/core/src/server/historyApiFallback.ts, packages/core/src/server/prodServer.ts, packages/core/src/types/config.ts, pnpm-lock.yaml, scripts/dictionary.txt
The connect-history-api-fallback dependency is no longer actively maintained and contains only ~100 lines of code, so I decided to fork it to better maintain the code.
This PR also removes the `logger` and `verbose` options, because we can use `logger.debug()` instead, which will not have any impact on the functionality of this middleware.
- https://github.com/bripkens/connect-history-api-fallback
=> refactor: fork connect-history-api-fallback dependency

e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts
Fix the flaky plugin hooks watch test. Since the watch may fire multiple times, we need to limit the scope of the assertion.
=> test(e2e): fix flaky plugin hooks watch test

packages/core/src/helpers/index.ts, packages/core/src/server/historyApiFallback.ts, packages/core/src/types/config.ts
`url.parse` has been deprecated since Node 24, and we should use `new URL` instead.
- https://nodejs.org/en/blog/release/v24.0.0#deprecations-and-removals
- https://github.com/nodejs/node/pull/55017
- https://github.com/web-infra-dev/rsbuild/pull/5694
We still have three dependencies that use `url.parse`:
=> fix: remove the deprecated `url.parse` from historyApiFallback

package.json, pnpm-lock.yaml, rslint.json
Rslint is a linter currently under development for Rstack, and the repository is still private. We plan to make it public soon.
This PR introduces Rslint to enable type-aware linting rules. This improves the TypeScript code quality in Rsbuild and it also helps to validate Rslint’s capabilities.
- Fix issues found by Rslint
- Enable Rslint in CI
- Add more subdirectories to `project` options
=> chore(workflow): integrate Rslint for type-aware linting

.vscode/settings.json, packages/compat/plugin-webpack-swc/tsconfig.json, packages/core/tsconfig.json, packages/plugin-babel/tsconfig.json, packages/plugin-less/tsconfig.json, packages/plugin-preact/tsconfig.json, packages/plugin-react/tsconfig.json, packages/plugin-sass/tsconfig.json, packages/plugin-solid/tsconfig.json, packages/plugin-stylus/tsconfig.json, packages/plugin-svelte/tsconfig.json, packages/plugin-svgr/tsconfig.json, packages/plugin-vue/tsconfig.json
Write the tsBuildInfo files to node_modules/.cache to make the working directories cleaner.
- https://www.typescriptlang.org/tsconfig/#tsBuildInfoFile
=> chore: write tsBuildInfo files to node_modules cache folder

packages/core/src/pluginManager.ts, packages/core/src/plugins/asset.ts, packages/core/src/plugins/css.ts, packages/core/src/plugins/minimize.ts, packages/core/src/plugins/output.ts, packages/core/src/server/gzipMiddleware.ts, packages/core/src/server/helper.ts, rslint.json
Fix all lint issues found by the `@typescript-eslint/no-unnecessary-boolean-literal-compare`  rules in Rslint.
- https://github.com/web-infra-dev/rsbuild/pull/5699
=> chore: fix no-unnecessary-boolean-literal-compare lint issues

packages/core/src/client/hmr.ts, packages/core/src/helpers/index.ts, packages/core/src/hooks.ts, packages/core/src/plugins/fileSize.ts, rslint.json
Fix all lint issues found by the `@typescript-eslint/use-unknown-in-catch-callback-variable` and `@typescript-eslint/non-nullable-type-assertion-style` rules in Rslint.
- https://github.com/web-infra-dev/rsbuild/pull/5699
=> chore: fix non-nullable-type-assertion-style lint issues

packages/core/src/types/config.ts, website/docs/en/config/server/history-api-fallback.mdx, website/docs/zh/config/server/history-api-fallback.mdx
Update `server.historyApiFallback` documentation,  replacing references to `connect-history-api-fallback` , describe the current functionality and all configuration options.
=> docs: update historyApiFallback documentation

packages/core/package.json, packages/core/src/inspectConfig.ts, packages/core/src/server/gzipMiddleware.ts, pnpm-lock.yaml, rslint.json
Fix all lint issues found by the `unbound-method`  rules in Rslint.
- https://github.com/web-infra-dev/rsbuild/pull/5699
- https://github.com/rspack-contrib/rspack-chain/releases/tag/v1.3.1
=> refactor: fix unbound-method lint issues

e2e/cases/cli/specified-environment/index.test.ts, packages/core/src/cli/init.ts
fix(cli): support `--environment` shorten option
Build multiple environments can be shortened to: `rsbuild dev --environment web,node`
https://github.com/web-infra-dev/rsbuild/discussions/5714
=> fix(cli): support `--environment` shorten option

website/docs/en/guide/configuration/rsbuild.mdx, website/docs/zh/guide/configuration/rsbuild.mdx
This pull request updates the documentation to reflect changes in Node.js version support for TypeScript. The changes clarify the version ranges and requirements for using the Node.js native loader with or without the `--experimental-strip-types` flag.
- https://nodejs.org/en/blog/release/v22.18.0
=> docs: update Node version requirements for loading TS config

package.json, packages/core/src/server/helper.ts, packages/core/tests/server.test.ts, pnpm-lock.yaml
- Update @rstest/core to v0.1.0, see https://github.com/web-infra-dev/rstest/releases/tag/v0.1.0
- Spy on `console.log` to reduce verbose information
=> test: update Rstest to v0.1.0 and spy on console.log

e2e/cases/environments/disable-hmr/index.test.ts, e2e/cases/environments/disable-hmr/src/bar.js, e2e/cases/environments/disable-hmr/src/foo.js, packages/core/src/provider/initConfigs.ts, packages/core/src/server/compilationManager.ts, packages/core/src/server/compilationMiddleware.ts, packages/core/src/types/config.ts, website/docs/en/config/environments.mdx, website/docs/zh/config/environments.mdx
Add support for disabling live reload in a specified environment:
```js
foo: {
source: {
entry: {
foo: './src/foo.js',
},
},
},
bar: {
source: {
entry: {
bar: './src/bar.js',
},
},
dev: {
hmr: false,
liveReload: false,
},
},
},
});
```
- https://github.com/web-infra-dev/rsbuild/discussions/5728
=> feat: add support for disabling live reload in environments

packages/core/src/client/hmr.ts, packages/core/src/server/devServer.ts, packages/core/src/server/socketServer.ts
This pull request introduces type safety improvements of socket messages. The primary changes include replacing loosely typed structures with a strongly typed `SocketMessage` union, updating related functions to use these types, and simplifying the codebase for better maintainability.
=> refactor: socket message types

packages/core/src/helpers/index.ts, packages/core/src/server/runner/asModule.ts, packages/core/src/server/runner/esm.ts
Remove redundant `module.instantiate()` calls in the module runners. `module.instantiate` has been removed since Node.js >= 13.0.0.
- https://github.com/nodejs/node/pull/29776
=> fix(runner): remove redundant module.instantiate calls

.github/workflows/release.yml, packages/compat/plugin-webpack-swc/package.json, packages/compat/webpack/package.json, packages/core/package.json, packages/create-rsbuild/package.json, packages/plugin-babel/package.json, packages/plugin-less/package.json, packages/plugin-preact/package.json, packages/plugin-react/package.json, packages/plugin-sass/package.json, packages/plugin-solid/package.json, packages/plugin-stylus/package.json, packages/plugin-svelte/package.json, packages/plugin-svgr/package.json, packages/plugin-vue/package.json, scripts/test-helper/package.json
Enable OIDC publishing to make it easier and more secure to publish npm packages from CI.
- https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
- https://docs.npmjs.com/trusted-publishers
=> chore(workflow): enable npm trusted publishing

.github/workflows/release.yml
Since we already run ecosystem CI for each commit, running ecosystem CI in releases is no longer necessary, so this PR removes the ecosystem CI workflow trigger from release.
=> ci: remove ecosystem CI workflow trigger from release

packages/core/src/index.ts, packages/core/src/provider/provider.ts, packages/core/src/types/rsbuild.ts, packages/core/tests/pluginApply.test.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Add `action` option to `rsbuild.initConfigs` to make it easier for testing Rsbuild plugins.
```js
const rsbuild = await createRsbuild();
const [rspackConfig] = await rsbuild.initConfigs({
action: 'build'
});
```
We are migrating our plugin to use [`apply`](https://rsbuild.rs/plugins/dev/core#conditional-application) in https://github.com/lynx-family/lynx-stack/pull/1310#discussion_r2224826734. And it seems like it's hard to make unit tests since `rsbuild.initConfigs` would **always** apply a plugin due to there is no `context.action`.
=> feat(core): add `action` option to `rsbuild.initConfigs`

packages/core/src/provider/initConfigs.ts
Introduced a new helper function `createEnvironmentNotFoundError` to standardize error messages when a specified environment configuration is missing.
=> refactor: extracting environment error creation

e2e/cases/hmr/client-multiple-environment/index.test.ts, e2e/cases/hmr/client-multiple-environment/rsbuild.config.ts, e2e/cases/hmr/client-multiple-environment/src/bar.js, e2e/cases/hmr/client-multiple-environment/src/foo.js, packages/core/src/client/hmr.ts, packages/core/src/env.d.ts, packages/core/src/provider/initConfigs.ts, packages/core/src/server/cliShortcuts.ts, packages/core/src/server/compilationManager.ts, packages/core/src/server/compilationMiddleware.ts, packages/core/src/server/devMiddlewares.ts, packages/core/src/server/devServer.ts, packages/core/src/server/hmrFallback.ts, packages/core/src/server/prodServer.ts, packages/core/src/server/watchFiles.ts, packages/core/src/types/config.ts, website/docs/en/config/environments.mdx, website/docs/zh/config/environments.mdx
Add support for custom HMR client via `dev.client` in environments:
```js
foo: {
dev: {
client: {
// ...
},
},
},
bar: {
dev: {
client: {
// ...
},
},
},
},
});
```
=> feat: add support for custom HMR client in environments

rslint.json
Ignore the `compiled` and `dist-types` directory in Rslint config to avoid checking unnecessary files.
- https://github.com/web-infra-dev/rslint
=> chore: ignore output directories in Rslint config

README.md, README.pt-BR.md, README.zh-CN.md, scripts/dictionary.txt, website/docs/en/guide/start/index.mdx, website/docs/zh/guide/start/index.mdx
Add Rslint to the list of Rstack tools.
https://github.com/web-infra-dev/rslint
=> docs: add rslint to the list of Rstack tools

package.json, pnpm-lock.yaml
- Upgrading `@rstest/core` to v0.1.2
- Adjusting the test scripts
- https://github.com/web-infra-dev/rstest/releases/tag/v0.1.2
=> chore(deps): update @rstest/core to v0.1.2

packages/compat/webpack/src/webpackConfig.ts, packages/core/src/hooks.ts, packages/core/src/provider/rspackConfig.ts, packages/core/src/types/plugin.ts, packages/core/tests/configureRspack.test.ts
Fix the `appendRules` helper not work in some cases.
In https://github.com/web-infra-dev/rsbuild/pull/4767, we used a proxy to try to get the latest Rspack configuration object in config utils, but this did not work in some cases. This PR changes it to using `getCurrentConfig()` to allow config utils to always get the latest configuration object.
- resolve https://github.com/web-infra-dev/rsbuild/issues/5764
=> fix: appendRules helper not work in some cases

e2e/cases/alias/tsconfig-paths-reload/tsconfig.json, e2e/cases/cli/base/index.test.ts, e2e/cases/cli/basic/index.test.ts, e2e/cases/cli/config-loader/index.test.ts, e2e/cases/cli/custom-config/index.test.ts, e2e/cases/cli/custom-env-dir/index.test.ts, e2e/cases/cli/custom-env-prefix/index.test.ts, e2e/cases/cli/falsy-plugins/index.test.ts, e2e/cases/cli/function-config/index.test.ts, e2e/cases/cli/inspect/index.test.ts, e2e/cases/cli/load-import-meta-env/index.test.ts, e2e/cases/cli/load-node-env/index.test.ts, e2e/cases/cli/load-process-env/index.test.ts, e2e/cases/cli/log-level/index.test.ts, e2e/cases/cli/mode/index.test.ts, e2e/cases/cli/no-env/index.test.ts, e2e/cases/cli/node-env/index.test.ts, e2e/cases/cli/public-env-vars/index.test.ts, e2e/cases/cli/root/index.test.ts, e2e/cases/cli/specified-environment/index.test.ts, e2e/cases/cli/vue/index.test.ts, e2e/cases/server/ssr/package.json, e2e/scripts/shared.ts, package.json, pnpm-lock.yaml
Replace the `execSync` and `npx` with a faster `runCliSync` helper in e2e cases:
- Reduce the overhead of `npx`
- Fix the `npx` warning in Node 24
=> test(e2e): replace execSync and npx with a faster helper

e2e/cases/alias/tsconfig-paths-reload/index.test.ts, e2e/cases/cli/build-watch-options/index.test.ts, e2e/cases/cli/build-watch-restart/index.test.ts, e2e/cases/cli/build-watch/index.test.ts, e2e/cases/cli/reload-config/index.test.ts, e2e/cases/cli/reload-env/index.test.ts, e2e/cases/cli/watch-files-array/index.test.ts, e2e/cases/cli/watch-files/index.test.ts, e2e/cases/create-rsbuild/helper.ts, e2e/cases/rspack-profile/index.test.ts, e2e/cases/server/ssr-type-module/package.json, e2e/scripts/shared.ts, pnpm-lock.yaml
Replace the `exec` and `npx` with a faster `runCliSync` helper in e2e cases:
- Reduce the overhead of `npx`
- Fix the `npx` warning in Node 24
- https://github.com/web-infra-dev/rsbuild/pull/5783
=> test(e2e): replace direct exec calls with faster helper

package.json, packages/core/package.json, packages/create-rsbuild/package.json
Rspack and Rsbuild v1.5 will no longer support Node 16, as Node.js reached end-of-life on September 11th, 2023, and many npm packages in the ecosystem have also dropped support for Node 16.
This PR marks the first step toward this goal by updating the engines field in package.json to require Node.js >= 18.12.0.
- https://github.com/web-infra-dev/rspack/discussions/10867
=> feat!: update minimum Node.js version to 18.12.0

CONTRIBUTING.md, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
As Rsbuild ≥ 1.5.0 no longer supports Node 16, the quick start guide should be updated to reflect this.
This PR also adds links to the installation guides for other JavaScript runtimes, such as Bun and Deno.
**I removed the previous detailed Node.js installation guide because the Node.js website now provides better instructions: https://nodejs.org/en/download.**
- https://github.com/web-infra-dev/rsbuild/pull/5786
=> docs: update JavaScript runtime installation instructions

e2e/cases/server/overlay-type-errors/tsconfig.json, examples/node/tsconfig.json, examples/react/tsconfig.json, examples/vue/tsconfig.json, packages/core/rslib.config.ts, packages/create-rsbuild/rslib.config.ts, scripts/config/rslib.config.ts, scripts/config/tsconfig.json
Since Rsbuild v1.5 no longer supports Node 16, we can update build configs to target ES2022 to reduce the output code.
- https://github.com/web-infra-dev/rsbuild/pull/5786
=> perf: update build configs to target ES2022

packages/core/src/cli/index.ts
In Node.js >= 20, we can no longer use `npm_execpath.includes('npx-cli.js')` to identify npx.
This PR uses `process.env.npm_lifecycle_event === 'npx'` instead.
=> fix(cli): ensure consistent spacing for npx of node 20+

packages/core/src/cli/index.ts
Skip greeting when help is requested, as cac's help output already contains information that would be redundant with the greeting message.
https://github.com/cacjs/cac/blob/257b140085e8ef7527f3ce9628ae78ed29338ffb/src/Command.ts#L141-L145
=> fix(cli): skip greeting when help is requested

biome.json
It seems that Biome's `"useIgnoreFile": true` option does not work as expected. We can manually skip some directories to improve Biome's performance.
Try to fix: https://github.com/biomejs/biome/issues/7020
=> chore: exclude additional directories from biome

package.json, pnpm-lock.yaml, rslint.json
- Upgrades the `@rslint/core` dependency version 0.1.4 to 0.1.7 across the project
- Updates the linter configuration to disable the new `@typescript-eslint/no-empty-function` rule.
- https://github.com/web-infra-dev/rslint/releases
=> chore(deps): update @rslint/core to v0.1.7

.github/workflows/lint.yml, packages/core/src/server/runner/basic.ts, packages/core/src/server/runner/esm.ts, packages/plugin-react/src/splitChunks.ts, packages/plugin-vue/src/splitChunks.ts, rslint.json
- Removed unnecessary type assertions
- Removed the rule disabling `@typescript-eslint/no-unnecessary-type-assertion` in `rslint.json`
=> chore: remove unnecessary type assertions

packages/core/src/helpers/index.ts, packages/core/src/initPlugins.ts, packages/core/src/plugins/minimize.ts, rslint.json
- Eliminated switch exhaustiveness checks
- Added support for generating HTML output filenames in the `getFilename` helper
- Enabled the `@typescript-eslint/switch-exhaustiveness-check` rule
- https://typescript-eslint.io/rules/switch-exhaustiveness-check/#allowdefaultcaseforexhaustiveswitch-caveats
=> refactor: eliminate switch exhaustiveness checks

e2e/cases/plugin-less/parallel/index.test.ts, e2e/cases/plugin-less/parallel/rsbuild.config.ts, e2e/cases/plugin-less/parallel/src/a.less, e2e/cases/plugin-less/parallel/src/b.less, e2e/cases/plugin-less/parallel/src/c.less, e2e/cases/plugin-less/parallel/src/d.less, e2e/cases/plugin-less/parallel/src/e.less, e2e/cases/plugin-less/parallel/src/f.less, e2e/cases/plugin-less/parallel/src/index.js, packages/plugin-less/src/index.ts, website/docs/en/plugins/list/plugin-less.mdx, website/docs/zh/plugins/list/plugin-less.mdx
Add support for parallel loader execution to `@rsbuild/plugin-less`:
```ts
pluginLess({
parallel: true,
});
```
This option is experimental and may not work if your Less options contain functions.
See [Rspack - Rule.use.parallel](https://rspack.rs/config/module#ruleuseparallel) for more details.
=> feat(plugin-less): support for parallel loader execution

packages/core/prebundle.config.mjs, packages/core/rslib.config.ts, packages/core/src/plugins/css.ts
Since `postcss-load-config` is required to be executed by default, we don't need to pre-bundle it. Using Rslib to bundle it directly into the main bundle can reduce the overhead of Node.js import.
=> perf: remove pre-bundling of postcss-load-config

website/docs/en/shared/onBeforeDevCompile.mdx, website/docs/zh/shared/onBeforeDevCompile.mdx
Updates the documentation for the `OnBeforeDevCompile` hook to indicate the version in which it was introduced.
- https://github.com/web-infra-dev/rsbuild/pull/5788
=> docs: add version info to onBeforeDevCompile hook

.github/renovate.json5, pnpm-lock.yaml, scripts/config/package.json, scripts/config/rslib.config.ts, scripts/test-helper/package.json
Integrate with [`rsbuild-plugin-arethetypeswrong`](https://www.npmjs.com/package/rsbuild-plugin-arethetypeswrong?activeTab=readme). 
This could avoid future regression on issues like https://github.com/web-infra-dev/rsbuild/pull/3695 or https://github.com/web-infra-dev/rsbuild/pull/3089
=> chore: integrate with `rsbuild-plugin-arethetypeswrong`

website/docs/en/guide/optimization/code-splitting.mdx, website/docs/en/plugins/list/plugin-react.mdx, website/docs/en/plugins/list/plugin-vue.mdx, website/docs/zh/guide/optimization/code-splitting.mdx, website/docs/zh/plugins/list/plugin-react.mdx, website/docs/zh/plugins/list/plugin-vue.mdx
Clarified the description of the `split-by-experience` strategy code-splitting guides, specifying which npm packages are split into separate chunks and referencing plugin-provided chunks for React and Vue.
=> docs: improve code splitting documentation clarity

e2e/cases/server/ssr-type-module/rsbuild.config.ts, e2e/cases/server/ssr/rsbuild.config.ts, packages/core/src/createRsbuild.ts, packages/core/src/defaultConfig.ts, packages/core/src/plugins/esm.ts, packages/core/src/types/config.ts, packages/core/tests/__snapshots__/environments.test.ts.snap
Add `output.module` config to enable experimental ESM output format when target is node. This includes adding a new plugin to handle ESM-specific Rspack configurations and updating related type definitions and test cases.
The feature is marked as experimental and currently only supports node target. This provides a foundation for future ESM support in other targets.
```ts
output: {
module: true,
}
}
```
- https://github.com/web-infra-dev/rspack/pull/11344
- https://rspack.rs/config/output#outputmodule
=> feat: add experimental ESM output support for node target

packages/core/src/server/middlewares.ts
- Adjust indentation in debug log message
- Improve color for debug logs
=> fix(server): adjust indentation in debug log message

.github/workflows/ecosystem-ci.yml, e2e/cases/nonce/dynamic-chunk/index.test.ts, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/client/hmr.ts, packages/core/src/defaultConfig.ts, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap
- Enable lazyCompilation.imports by default.
We need specify lazyCompilation.entries as false , because rspack will enable lazyCompilation.entries if you pass a object as lazyCompilation. more detail see: [Rspack configuration.lazyCompilation](https://rspack.rs/config/lazy-compilation#lazycompilation-1)
- In lazyCompilation, we will do a hmr compile quickly, so we maybe complete the hmr compile before web socket connect done. It means we need do a hmr action when first web socket message send.
=> feat: enable lazyCompilation.imports by default

packages/core/src/client/hmr.ts
Remove redundant condition check in the `handleSuccess` method since `tryApplyUpdates()` already checks for updates.
=> fix(hmr): remove redundant condition check

packages/core/src/server/devMiddlewares.ts
See title
- https://github.com/web-infra-dev/rspack/pull/11337
=> fix: should apply lazyCompilationMiddleware when using top-level configuration 

packages/core/src/plugins/cache.ts, scripts/test-helper/rstest.setup.ts
Added a `try-catch` block to the `validateWebpackCache` function to handle failures when writing the `buildDependencies.json` file
=> fix(cache): handle fs operations errors

packages/core/src/plugins/basic.ts, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap
Enable Rspack's experimental barrel file optimization by default.
When building applications with barrel files, this optimization should make builds significantly faster.
- https://rspack.rs/config/experiments#experimentslazybarrel
=> perf: enable Rspack's barrel file optimization by default

e2e/cases/css/inject-styles/index.test.ts, e2e/cases/hmr/basic/index.test.ts, e2e/cases/hmr/multiple-connection/index.test.ts, e2e/cases/hmr/multiple-connection/rsbuild.config.ts, e2e/cases/hmr/multiple-connection/src/App.tsx, e2e/cases/hmr/multiple-connection/src/index.ts, e2e/cases/server/environments-hmr/index.test.ts, packages/core/src/server/socketServer.ts
- Fixed HMR failure when opening multiple browser tabs at the same time. We should use a Set to store all Web Socket connections instead of letting the new connection overwrite the previous one.
- Added a new e2e test that verifies multiple browser pages can establish independent HMR connections and receive updates simultaneously.
- https://github.com/web-infra-dev/rsbuild/pull/5531
=> fix: failed to create multiple HMR connections

website/docs/en/config/performance/chunk-split.mdx, website/docs/zh/config/performance/chunk-split.mdx
Add links to each chunk splitting strategy to improve navigation and provide direct access to detailed explanations.
=> docs(config): add links to chunk splitting strategies

packages/core/src/constants.ts, packages/core/src/env.d.ts, packages/core/src/plugins/server.ts
Fix the issue where it fails to copy the public directory when running in Deno by first removing the existing directory, if present.
Also improve the clarity of the error message.
resolve https://github.com/web-infra-dev/rsbuild/issues/5804
=> fix(server): handle Deno compatibility in public dir copy

e2e/cases/config/inspect-config/index.test.ts, packages/core/src/createRsbuild.ts, packages/core/src/types/rsbuild.ts
Ensure `inspectConfig` properly initializes `action` before execution. This allows `inspectConfig` to correctly filter based on the plugin's `apply` option and output a more accurate configuration.
=> fix: ensure inspectConfig properly initializes action before execution

e2e/cases/cli/build-watch/index.test.ts, e2e/scripts/shared.ts
- Fix the flaky build watch case
- Modified the `runCli` function to strip ANSI color codes from CLI output before storing logs
=> test(e2e): fix flaky build watch case

e2e/cases/lazy-compilation/basic/index.test.ts, e2e/cases/lazy-compilation/dynamic-import/index.test.ts, e2e/cases/lazy-compilation/port-placeholder/index.test.ts
Improves the reliability and clarity of several lazy compilation e2e tests by ensuring that build completion is explicitly awaited after navigation events, and by clearing build logs between test steps.
This should reduce the chance of panic in lazy compilation cases. I guess we need to wait for the last build to finish before closing the compiler, otherwise the worker process may exit incorrectly.
=> test(e2e): improve lazy compilation cases

e2e/cases/javascript-api/instance-api/index.test.ts, packages/core/src/createRsbuild.ts, packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/instance.mdx
Expose the `modifyEnvironmentConfig` plugin API in the Rsbuild instance.
This allows upper-level tools like Rslib or Rstest to more easily add some configuration merging logic.
=> feat(core): expose modifyEnvironmentConfig method in instance

e2e/cases/config/debug-mode/index.test.ts, packages/compat/webpack/src/createCompiler.ts, packages/core/src/configChain.ts, packages/core/src/createRsbuild.ts, packages/core/src/loadConfig.ts, packages/core/src/pluginManager.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/provider/initConfigs.ts, packages/core/src/provider/rspackConfig.ts, website/docs/en/guide/debug/debug-mode.mdx, website/docs/en/guide/faq/features.mdx, website/docs/zh/guide/debug/debug-mode.mdx, website/docs/zh/guide/faq/features.mdx
- update debug log messages across core modules to be more descriptive and consistent
- update documentation examples to reflect new debug log format
```bash
➜  DEBUG=rsbuild pnpm dev
rsbuild 10:49:23 configuration loaded from: /path/to/rsbuild.config.ts
rsbuild 10:49:23 registering default plugins
rsbuild 10:49:23 default plugins registered
rsbuild 10:49:23 initializing plugins
rsbuild 10:49:23 plugins initialized
rsbuild 10:49:23 applying modifyRsbuildConfig hook
rsbuild 10:49:23 applied modifyRsbuildConfig hook
rsbuild 10:49:23 applying modifyEnvironmentConfig hook (web)
rsbuild 10:49:23 applied modifyEnvironmentConfig hook (web)
rsbuild 10:49:23 create dev server
rsbuild 10:49:23 creating compiler
rsbuild 10:49:23 applying modifyBundlerChain hook
rsbuild 10:49:23 applied …
```
=> refactor: improve debug log messages for better clarity

website/docs/en/config/html/tags.mdx, website/docs/zh/config/html/tags.mdx
Add usage examples for the `append` and `head` options in the HTML tags configuration documentation to improve clarity.
=> docs: add code examples for html tags config options

website/docs/en/config/performance/print-file-size.mdx, website/docs/zh/config/performance/print-file-size.mdx
Adds the `exclude` option to the `PrintFileSizeOptions` type of `performance.printFileSize` configration.
=> docs: add exclude option to `printFileSize` type

packages/core/src/index.ts, packages/core/src/types/hooks.ts, website/docs/zh/api/javascript-api/types.mdx
Add the deprecated `OnDevCompileDoneFn` type alias to maintain backward compatibility.
Fix the ecosystem CI: https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions/runs/17115980695/job/48546866958#step:7:10790
- https://github.com/web-infra-dev/rsbuild/pull/5882
=> fix: add `OnDevCompileDoneFn` type for backward compatibility

website/docs/en/config/output/source-map.mdx, website/docs/zh/config/output/source-map.mdx
Add warning about the risks of deploying source maps to public servers in production builds. The warning explains that this could expose source code and create security vulnerabilities.
- https://rspack.rs/config/devtool#production
=> docs(config): add security warning about source maps in production

packages/core/src/plugins/rspackProfile.ts
Ensure proper execution order by awaiting the `onStart` callback during first compilation.
=> fix: floating promise in rspackProfile plugin

packages/core/src/plugins/fileSize.ts, packages/core/src/types/config.ts, website/docs/en/config/performance/print-file-size.mdx, website/docs/zh/config/performance/print-file-size.mdx
Add more params for `performance.printFileSize.total`
- `environmentName`: The unique name of the current environment, used to distinguish and locate the environment
- `distPath`: The output directory relative to the project root
=> feat: add more params for `performance.printFileSize.total`

packages/core/src/plugins/basic.ts, packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
Due to some edge case issues with inline enum, it has been temporarily disabled.
When Rspack releases a new hotfix, we will re-enable this optimization.
- https://github.com/web-infra-dev/rsbuild/issues/5959
- https://github.com/web-infra-dev/rspack/pull/11508
=> fix: temporarily disable inline enum optimization

e2e/cases/lazy-compilation/basic/index.test.ts, e2e/cases/lazy-compilation/dynamic-import/index.test.ts, e2e/cases/lazy-compilation/dynamic-import/src/foo.js, e2e/cases/lazy-compilation/dynamic-import/src/index.js, e2e/cases/lazy-compilation/port-placeholder/index.test.ts
Should use runtime to test lazyCompilation instead of terminal logs
=> test(e2e): do not rely on building URL to verify lazy  compilation

packages/plugin-react/src/react.ts, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/index.test.ts, website/docs/en/plugins/list/plugin-react.mdx, website/docs/zh/plugins/list/plugin-react.mdx
This PR updates the default options of `@rspack/plugin-react-refresh` to keep the plugin's transpilation scope consistent with the `builtin:swc-loader` of Rsbuild.
This is because the `builtin:swc-loader` injects the `$RefreshReg$` related code into the transpiled modules, which then needs to be further processed by the `builtin:react-refresh-loader`.
https://github.com/rspack-contrib/rspack-plugin-react-refresh/pull/45
=> feat(plugin-react): improve transpilation scope of ReactRefreshPlugin

packages/core/src/plugins/basic.ts, packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap, packages/core/tests/__snapshots__/swc.test.ts.snap, packages/plugin-babel/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap, packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
This reverts commit e3ce9421e268f0b04f30525eff2d1b53a50f9e08.
The known inline enum bug has been fixed in Rspack v1.5.1, so we can re-enable inline enum optimization.
- https://github.com/web-infra-dev/rsbuild/pull/5960
=> Revert "fix: temporarily disable inline enum optimization (#5960)"

packages/core/src/loader/ignoreCssLoader.ts, packages/core/src/loader/transformLoader.ts, packages/plugin-svgr/src/loader.ts
This pull request refactors several custom loader implementations to use the more generic `LoaderDefinition` type from `@rspack/core`, improving type safety and consistency across the codebase
- https://rspack.rs/api/loader-api/types#write-with-typescript
=> refactor(types): use `LoaderDefinition` to declare loader types

e2e/cases/typescript/const-enum/index.test.ts, e2e/cases/typescript/const-enum/src/foo.ts, e2e/cases/typescript/const-enum/src/index.ts
This PR adds new cases to verify enum with property access. This is to avoid the regression in https://github.com/web-infra-dev/rsbuild/issues/5959 from happening again.
=> test(e2e): add new cases to verify enum with property access

e2e/cases/plugin-api/plugin-hooks-environment/rebuild.test.ts, packages/core/src/hooks.ts
fix: should  rerun `onBeforeDevCompile` hook correctly with multiple environments.
The invalid hook is executed when a watching compilation has been invalidated (re-compilation). In multiple environments, the invalid hook is only triggered in the **affected environment**, not in **all environments**.
=> fix: rerun onBeforeDevCompile hook correctly with multiple environments

website/docs/en/config/output/css-modules.mdx, website/docs/zh/config/output/css-modules.mdx
Introduced additional examples for `cssModules.auto` configuration, showing how to match files containing `.module.` and `.modules.` using a regular expression for the `auto` option.
resolve https://github.com/web-infra-dev/rsbuild/issues/5982
=> docs: add example for `cssModules.auto` configuration

e2e/cases/plugin-api/plugin-hooks-environment/index.test.ts, e2e/cases/plugin-api/plugin-hooks-environment/rebuild.test.ts, e2e/cases/plugin-api/plugin-hooks/index.test.ts
- replace manual setup with `build/dev` helper methods
- remove redundant port handling and server management
=> refactor(e2e): simplify test setup by using helper methods

.github/workflows/ecosystem-ci.yml
Enables commenting on pull requests by adding the `pull-requests: write` permission to the `ecosystem-ci.yml` workflow.
- https://github.com/web-infra-dev/rsbuild/pull/5824#discussion_r2269443858
- https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
=> ci: add pull-requests write permission to ecosystem workflow

website/docs/en/config/output/externals.mdx, website/docs/zh/config/output/externals.mdx
Replace React examples with `axios` in externals documentation to demonstrate CDN usage, as React 19 no longer provides the Umd bundles.
- https://react.dev/blog/2024/04/25/react-19-upgrade-guide#umd-builds-removed
=> docs(config): update externals documentation with axios example

packages/core/src/plugins/server.ts
Add color highlighting to the path and suggest disabling public directory copying in config when the copy operation fails.
Preview:
- Related: https://github.com/web-infra-dev/rsbuild/issues/5986
=> fix: improve error message for public directory copy failure

e2e/cases/hmr/error-recovery/index.test.ts, e2e/cases/hmr/rebuild-logs/index.test.ts, e2e/cases/html/template-cache/index.test.ts, e2e/cases/lazy-compilation/add-initial-chunk/index.test.ts, e2e/cases/lazy-compilation/basic/index.test.ts, e2e/cases/lazy-compilation/dynamic-import/index.test.ts, e2e/cases/lazy-compilation/port-placeholder/index.test.ts, e2e/cases/module-federation-v2/index.test.ts, e2e/cases/print-file-size/basic/index.test.ts, e2e/cases/server/reload-html/index.test.ts
Removed redundant checks and calls to `test.skip()` for Windows from multiple test files, allowing tests to run on all platforms unless explicitly broken.
=> test(e2e): enable more cases on Windows

packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/basic.ts, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/builder.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/core/tests/__snapshots__/environments.test.ts.snap
This PR enables Rspack's [const inline optimization](https://rspack.rs/blog/announcing-1-5#const-inline-optimization) optimization by default to reduce bundle size:
```js
// constants.js
export const A = true;
// index.js
import { A } from './constants';
console.log(A ? 1 : 2);
// Bundled by Rspack: output.js
const __webpack_modules__ = {
'./index.js': __webpack_require__ => {
// 1. A will be inlined at the usage sites.
// 2. If all exports from constants.js are inlined, the constants.js module will be optimized away and won't appear in the final output.
console.log(true ? 1 : 2);
},
};
```
- https://rspack.rs/config/module#moduleparserjavascriptinlineconst
- https://rspack.rs/blog/announcing-1-5#const-inline-optimization
=> feat: enable inline const optimization by default

e2e/cases/optimization/inline-const/index.test.ts, e2e/cases/optimization/inline-const/src/constants.ts, e2e/cases/optimization/inline-const/src/index.ts, e2e/cases/optimization/inline-const/tsconfig.json
Add E2E test case to verify constant inlining behavior in both production and development modes. The test checks if constants are properly inlined in production and imported as expected in development.
- https://github.com/web-infra-dev/rsbuild/pull/6043
=> test(e2e): add test case for constant inlining optimization

e2e/cases/hmr/reconnect/index.test.ts, e2e/cases/hmr/reconnect/rsbuild.config.ts, e2e/cases/hmr/reconnect/src/App.tsx, e2e/cases/hmr/reconnect/src/index.ts
Add a E2E test case to verify the Web Socket server reconnection behavior.
=> test(e2e): add HMR reconnect test case

packages/core/src/client/hmr.ts
Introduces a minor improvement to the WebSocket connection logic, the reconnect count is now reset when the WebSocket successfully connects, ensuring accurate tracking of reconnection attempts.
=> fix(hmr): reset reconnect count when connection is established

packages/core/src/client/hmr.ts
Prevent duplicate console logs during reconnection, only show WebSocket connection messages on the first reconnection attempt to avoid log spam.
=> fix(client): prevent duplicate console logs during reconnection

website/docs/en/guide/styling/css-in-js.mdx, website/docs/zh/guide/styling/css-in-js.mdx
vanilla-extract-css webpack plugin has known issue which breaks HMR, there is a simple workaround that didn't break production output. Add the workaround in docs
https://github.com/web-infra-dev/rsbuild/issues/6049#issuecomment-3249933170
https://github.com/vanilla-extract-css/vanilla-extract/issues/905
=> docs: add HMR workaround for vanilla-extract-css plugin

e2e/cases/optimization/inline-const/index.test.ts, e2e/cases/optimization/inline-const/src/constants2.ts, e2e/cases/optimization/inline-const/src/index.ts
This pull request updates the inline constants optimization test case by introducing a new constant that is dynamically imported.
- https://github.com/web-infra-dev/rspack/issues/11589
=> test(e2e): improve inline const test case

.vscode/settings.json
Added JSON schema associations for files matching `_meta.json` and `_nav.json`, enabling VS Code to validate these files against the schemas provided by `@rspress/core`
- https://v2.rspress.rs/guide/basic/auto-nav-sidebar#json-schema-type-hint
=> chore: add JSON schemas for Rspress meta and nav files

website/docs/en/guide/optimization/build-performance.mdx, website/docs/zh/guide/optimization/build-performance.mdx
Add documentation for enabling Rspack's native watcher feature to improve HMR performance in development mode. 
- https://rspack.rs/config/experiments#experimentsnativewatcher
=> docs: add native watcher example to build perf guide

e2e/cases/server/print-urls/index.test.ts, e2e/cases/server/print-urls/src/index.js, e2e/helper/logs.ts, packages/core/src/server/helper.ts, packages/core/tests/helpers.test.ts
- Updated `getRoutes` helper to compute the common parent path across environments with HTML output, ensuring correct relative path calculation for server URLs in multi-environment setups.
- Enhanced the log E2E helper to support a `strict` option for exact line matching, improving the accuracy of log assertions in tests
- Added new tests in `index.test.ts` to verify server URL printing for multiple web environments
- resolve https://github.com/web-infra-dev/rsbuild/issues/5381
=> fix(server): prints correct urls when configuring web and node environments

e2e/cases/server/print-urls/index.test.ts
This pull request updates several E2E tests in `server/print-urls/index.test.ts` to improve reliability. The main changes include explicitly disabling HTML fallback in the server configuration, and verifying the test page loads correctly.
=> test(e2e): improve tests for server url printing

packages/core/src/types/config.ts
Update JSDoc comments for Rsbuild configuration options, picked from https://github.com/web-infra-dev/rsbuild/pull/6077
- close https://github.com/web-infra-dev/rsbuild/pull/6077
=> docs: update JSDoc comments for Rsbuild configuration options

website/docs/en/config/server/https.mdx, website/docs/zh/config/server/https.mdx
Improve documentation to clearly state that HTTP/2 is default with HTTPS but falls back to HTTP/1 when proxy is enabled due to http-proxy limitation
=> docs(config): clarify HTTP/2 behavior

packages/core/prebundle.config.mjs, packages/core/src/dev-middleware/index.ts, packages/core/src/dev-middleware/middleware.ts, packages/core/src/dev-middleware/utils/setupOutputFileSystem.ts, packages/core/src/server/compilationMiddleware.ts
Lazy loading the `memfs` dependency to reduce the main bundle size and make the dev server faster.
- https://github.com/web-infra-dev/rsbuild/pull/6092
=> perf: lazy loading memfs dependency

packages/core/src/dev-middleware/index.ts, packages/core/src/dev-middleware/middleware.ts, packages/core/src/dev-middleware/utils/escapeHtml.ts, packages/core/src/dev-middleware/utils/getFilenameFromUrl.ts, packages/core/src/dev-middleware/utils/memorize.ts, packages/core/src/dev-middleware/utils/setupHooks.ts, packages/core/src/dev-middleware/utils/setupOutputFileSystem.ts, packages/core/src/dev-middleware/utils/setupWriteToDisk.ts, rslint.json
- Simplify type definitions and remove unnecessary type assertions
- Remove redundant `eslint-disable` comments where no longer needed
https://github.com/web-infra-dev/rsbuild/pull/6092
=> refactor(dev-middleware): clean up code by removing redundant type casts

.vscode/extensions.json, .vscode/settings.json
Since the `TypeScriptTeam.native-preview` extension has not been published to the Open VSX registry, we removed the experimental typescript setting to avoid breaking the editors forked from VS Code.
- https://open-vsx.org/?search=typescript%20native&sortBy=relevance&sortOrder=desc
- https://github.com/web-infra-dev/rsbuild/pull/6087
=> chore(workflow): remove experimental typescript setting

e2e/cases/output/charset/index.test.ts, e2e/cases/output/charset/src/index.js
Added new test cases to explicitly verify `output.charset` behavior for both `'ascii'` and `'utf8'` settings in development mode.
=> test(e2e): add test case for utf-8 charset in dev mode

e2e/cases/cli/load-import-meta-env/rsbuild.config.ts, e2e/package.json, e2e/tsconfig.json
Enable type checking for test files, ensure that all E2E code is type-checked, simplify the TypeScript configuration, and add type references where needed.
=> test(e2e): enable type checking for test files

e2e/cases/cache/build-dependencies/index.test.ts, e2e/cases/cache/cache-digest/index.test.ts, e2e/cases/config/debug-mode/index.test.ts, e2e/cases/html/app-icon/index.test.ts, e2e/cases/lazy-compilation/basic/index.test.ts, e2e/cases/mode/basic/index.test.ts, e2e/cases/module-federation/v1-basic/index.test.ts, e2e/cases/module-federation/v2-basic/index.test.ts, e2e/cases/optimization/css-minify-options/index.test.ts, e2e/cases/output/charset-emoji-filename/index.test.ts, e2e/cases/output/charset/index.test.ts, e2e/cases/output/clean-dist-path/index.test.ts, e2e/cases/output/manifest-environment/index.test.ts, e2e/cases/output/manifest-generate/index.test.ts, e2e/cases/output/source-map/index.test.ts, e2e/cases/plugin-api/plugin-hooks-environment/index.test.ts, e2e/cases/plugin-api/plugin-hooks/index.test.ts, e2e/cases/plugin-svelte/hmr/index.test.ts, e2e/cases/plugin-svgr/svgo-minify-view-box/index.test.ts, e2e/cases/resolve/exports-presence/index.test.ts, e2e/cases/server/environments-hmr/index.test.ts, e2e/cases/server/environments/index.test.ts, e2e/cases/server/fallback/index.test.ts, e2e/cases/server/proxy-sse/index.test.ts, e2e/cases/server/proxy/index.test.ts, e2e/cases/server/watch-files/index.test.ts, e2e/cases/source/define/index.test.ts, e2e/cases/source/plugin-import/helper.ts, e2e/cases/source/pre-entry/index.test.ts, e2e/helper/index.ts
Standardizing the usage of test helpers by removing unnecessary imports and parameters, switching to destructured test context arguments (such as `dev`, `buildOnly`, `devOnly`), and eliminating redundant `cwd` and `page` properties in test invocations.
=> test(e2e): simplify test setup by removing imports

e2e/cases/css/inject-styles/index.test.ts, e2e/cases/hmr/basic/index.test.ts, e2e/cases/hmr/client-host/index.test.ts, e2e/cases/hmr/client-port-placeholder/index.test.ts, e2e/cases/hmr/error-recovery/index.test.ts, e2e/cases/hmr/live-reload/index.test.ts, e2e/cases/hmr/multiple-connection/index.test.ts, e2e/cases/hmr/rebuild-logs/index.test.ts, e2e/cases/hmr/reconnect/index.test.ts, e2e/cases/html/template-cache/index.test.ts, e2e/cases/plugin-preact/prefresh-context/index.test.ts, e2e/cases/plugin-preact/prefresh-disabled/index.test.ts, e2e/cases/plugin-preact/prefresh/index.test.ts, e2e/cases/plugin-react/disable-fast-refresh/index.test.ts, e2e/cases/plugin-solid/hmr/index.test.ts, e2e/cases/plugin-svelte/hmr/index.test.ts, e2e/cases/resolve/tsconfig-paths-reload/index.test.ts, e2e/cases/server/environments-hmr/index.test.ts, e2e/cases/server/overlay/index.test.ts, e2e/cases/server/reload-html/index.test.ts, e2e/helper/fixture.ts
Simplify test file modifications by introducing an `editFile` helper that handles file reading and writing. This improves test readability and reduces boilerplate code across multiple test cases.
=> test: add editFile helper for test file modifications

e2e/cases/resolve/condition-names/index.test.ts, e2e/cases/resolve/condition-names/package-foo/custom.js, e2e/cases/resolve/condition-names/package-foo/import.js, e2e/cases/resolve/condition-names/package-foo/package.json, e2e/cases/resolve/condition-names/package-foo/require.js, e2e/cases/resolve/condition-names/src/index.js, e2e/cases/resolve/extensions/index.test.ts, e2e/cases/resolve/extensions/tsconfig.json, packages/core/src/mergeConfig.ts, packages/core/src/plugins/resolve.ts, packages/core/src/types/config.ts
This pull request adds support for the `resolve.conditionNames` option in the configuration, allowing users to customize the order of condition names used when resolving package exports.
The newly added `resolve.conditionNames` is basically the same as `tools.rspack.resolve.conditionNames`. The differences are:
- `resolve.conditionNames` is shorter and more intuitive.
- `resolve.conditionNames` overrides the existing configuration instead of merging with it.
- https://github.com/web-infra-dev/rsbuild/issues/6097
- https://github.com/web-infra-dev/rsbuild/issues/3864
=> feat: add support for `resolve.conditionNames` configuration

e2e/cases/syntax-ts/const-enum/index.test.ts, packages/core/src/plugins/basic.ts, packages/core/src/plugins/swc.ts, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap, packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
This PR reverts https://github.com/web-infra-dev/rsbuild/pull/6114.
Since Rspack v1.5.4 has fixed all known enum inlining bugs, we can re-enable this optimization in production.
- https://github.com/web-infra-dev/rspack/pull/11629
=> feat: re-enable enum inlining optimization in production

packages/core/src/dev-middleware/index.ts, packages/core/src/dev-middleware/middleware.ts, packages/core/src/dev-middleware/utils/getFilenameFromUrl.ts, packages/core/src/dev-middleware/utils/getPaths.ts, packages/core/src/dev-middleware/utils/setupHooks.ts, packages/core/src/dev-middleware/utils/setupOutputFileSystem.ts, packages/core/src/dev-middleware/utils/setupWriteToDisk.ts
This pull request refactors the dev middleware to simplify the setup of hooks, output file systems, and compiler handling logic.
- Remove redundant type assertions and simplify compiler handling logic
- Move output file system setup to return the filesystem directly
- Update setupHooks to accept compiler parameter
=> refactor(dev-middleware): simplify compiler handling

packages/core/src/types/config.ts, website/docs/en/config/server/proxy.mdx, website/docs/zh/config/server/proxy.mdx
- Update `ProxyConfig` type to combine string and `ProxyOptions` records into a single union type
- Update documentation to reflect the type changes
resolve https://github.com/web-infra-dev/rsbuild/issues/6163
=> fix(types): correct ProxyConfig type definition

e2e/cases/optimization/inline-const/index.test.ts, packages/compat/webpack/tests/__snapshots__/default.test.ts.snap, packages/core/src/plugins/basic.ts, packages/core/tests/__snapshots__/basic.test.ts.snap, packages/core/tests/__snapshots__/default.test.ts.snap
The const inlining optimization was previously enabled in production builds, which could cause issues in some edge cases. (See https://github.com/web-infra-dev/rsbuild/issues/6171).
This PR disables these options to ensure the output code works as expected.
=> fix: temporarily disable const inlining optimization

packages/core/types.d.ts
Update `ImportMetaEnv` interface to use Record to fix the type error when `skipLibCheck` is `false`:
=> fix(types): update `ImportMetaEnv` interface to use Record

e2e/helper/fixture.ts, e2e/helper/logs.ts
Print the captured logs for failed E2E tests to make debugging easier:
=> test(e2e): print captured logs for failed tests

pnpm-workspace.yaml
Update workspace exclusion patterns to include 'dist' and 'dist-*' directories. 
Fix: https://github.com/web-infra-dev/rsbuild/pull/6192/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb
=> chore: update pnpm workspace exclusions

packages/core/package.json, packages/core/src/plugins/manifest.ts, pnpm-lock.yaml
- When generating the manifest file, get the initial chunks from `entries`, since they come from `compilation.entrypoints.get(entryName).getFiles()`, which ensures the correct chunk order (especially important for CSS chunks where order must be preserved).
- Update `rspack-manifest-plugin` to v5.1.0 to access `compilation` in the `generate` function.
- https://github.com/web-infra-dev/rsbuild/issues/6187
- https://github.com/rspack-contrib/html-rspack-plugin/blob/501c599b7ed8dd92c37f41a1c9586bcd0a9d0dbb/lib/index.js#L433
- https://github.com/rspack-contrib/rspack-manifest-plugin/blob/5e4bfb71d1ef10a466d4ae5079c9a87d0517dfa3/src/helpers.ts#L31-L35
- https://github.com/rspack-contrib/rspack-manifest-plugin/releases/tag/v5.1.0
=> fix: correct initial chunks order in generated manifest

e2e/cases/output/manifest-css-order/index.test.ts, e2e/cases/output/manifest-css-order/rsbuild.config.ts, e2e/cases/output/manifest-css-order/src/bar.css, e2e/cases/output/manifest-css-order/src/bar.js, e2e/cases/output/manifest-css-order/src/base.css, e2e/cases/output/manifest-css-order/src/env.d.ts, e2e/cases/output/manifest-css-order/src/foo.js, e2e/helper/fixture.ts, e2e/helper/logs.ts
Add test case to verify manifest generation with correct initial chunk order.
- https://github.com/web-infra-dev/rsbuild/issues/6187
- https://github.com/web-infra-dev/rsbuild/pull/6192
=> test(e2e): add manifest chunks order test case

website/docs/en/guide/advanced/environments.mdx, website/docs/zh/guide/advanced/environments.mdx
Explain how to use `output.distPath.root` to avoid dist files overwriting each other when building for multiple environments.
- https://github.com/web-infra-dev/rsbuild/issues/6150
=> docs: configuring output directories for multi-env builds

e2e/cases/cli/build-watch-options/index.test.ts, e2e/cases/cli/build-watch-restart/index.test.ts, e2e/cases/cli/build-watch/index.test.ts, e2e/cases/cli/reload-config/index.test.ts, e2e/cases/cli/reload-env/index.test.ts, e2e/cases/cli/watch-files-array/index.test.ts, e2e/cases/cli/watch-files/index.test.ts, e2e/cases/profiling/rspack-profile/index.test.ts, e2e/cases/resolve/tsconfig-paths-reload/index.test.ts, e2e/helper/cli.ts, e2e/helper/fixture.ts
Move the CLI execution logic to fixture and simplify test cases by using the new `execCli` helper.
=> test(e2e): move Rsbuild CLI execution logic to fixture

packages/core/src/cli/commands.ts, packages/core/src/cli/index.ts
Remove the built-in version log of cac and use Rsbuild CLI's greeting log instead.
https://github.com/cacjs/cac?tab=readme-ov-file#clihelpcallback
=> fix(cli): improve version log when displaying help

packages/core/src/cli/commands.ts, packages/core/src/cli/index.ts
Improve help output formatting:
- Add color for better visual distinction in help output
- Fix dev command name display in help section
- Simplify sub-command help instructions
=> feat(cli): improve help output formatting

e2e/helper/fixture.ts, e2e/helper/logs.ts, e2e/helper/package.json, pnpm-lock.yaml
The footer border was calculated with `header.length`, which broke in GitHub Actions because Unicode box-drawing chars are rendered double-width. Switched to using `string-width` so borders align correctly in all environments.
https://github.com/web-infra-dev/rsbuild/actions/runs/17903179910/job/50899610790?pr=6214#step:7:51
=> test(e2e): fix log formatting width calculation

e2e/cases/cli/log-level/index.test.ts, packages/core/src/cli/index.ts, packages/core/src/createRsbuild.ts, website/docs/en/config/log-level.mdx, website/docs/zh/config/log-level.mdx
Always output all logs in debug mode.
=> fix: always output all logs in debug mode

e2e/cases/cli/dev/index.test.ts, e2e/helper/fixture.ts, e2e/helper/package.json, pnpm-lock.yaml
The `string-width` package was removed as it's no longer needed for calculating box width. Simplified the box rendering logic by using fixed-width formatting instead of dynamic width calculation.
- https://www.npmjs.com/package/string-width#options
=> test(e2e): simplify box rendering

packages/core/src/dev-middleware/middleware.ts, packages/core/src/dev-middleware/utils/ready.ts, packages/core/src/dev-middleware/utils/setupWriteToDisk.ts
Remove unnecessary debug logging statements in dev middleware:
=> fix(dev-middleware): remove unnecessary debug logs

packages/core/package.json, packages/core/src/provider/createCompiler.ts, pnpm-lock.yaml
- Update dependency @rspack/core to v1.5.7
- Remove the temporary `ts-ignore`.
- https://github.com/web-infra-dev/rspack/releases/tag/v1.5.7
=> feat(deps): update dependency @rspack/core to v1.5.7

packages/plugin-react/src/react.ts, packages/plugin-react/tests/__snapshots__/index.test.ts.snap, packages/plugin-react/tests/index.test.ts
the second step after https://github.com/web-infra-dev/rspack/pull/11664.
the JavaScript parser must be set to support `jsx` or it will panic in paring JSX syntax.
=> feat(plugin-react): complete `preserve` React runtime

e2e/cases/assets/inline-query-auto/index.test.ts, e2e/cases/assets/inline-query-auto/rsbuild.config.ts, e2e/cases/assets/inline-query-false/index.test.ts, e2e/cases/assets/inline-query-false/rsbuild.config.ts, e2e/cases/assets/inline-query/index.test.ts, e2e/cases/assets/inline-query/rsbuild.config.ts, e2e/cases/css/css-modules-dom/index.test.ts, e2e/cases/css/css-modules-dom/rsbuild.config.ts, e2e/cases/html/inject/index.test.ts, e2e/cases/output/data-uri-limit/assets.test.ts, e2e/cases/output/externals/index.test.ts, e2e/cases/output/legal-comments/index.test.ts, e2e/cases/performance/resource-hints-prefetch/index.test.ts, e2e/cases/performance/resource-hints-preload/index.test.ts, e2e/cases/performance/split-chunk-by-module/index.test.ts, e2e/cases/plugin-api/async-plugin/index.test.ts, e2e/cases/plugin-api/plugin-process-assets-by-environments/index.test.ts, e2e/cases/plugin-babel/basic/index.test.ts, e2e/cases/plugin-babel/decorator/index.test.ts, e2e/cases/plugin-react/split-chunk/index.test.ts, e2e/cases/plugin-solid/index.test.ts, e2e/cases/plugin-svelte/hmr/index.test.ts, e2e/cases/plugin-vue/split-chunks/index.test.ts, e2e/cases/server/history-api-fallback/historyApiFallback.test.ts, e2e/cases/server/html-fallback/index.test.ts, e2e/cases/server/preview/index.test.ts, e2e/cases/syntax-es/decorator-2022-03/index.test.ts, e2e/cases/syntax-es/decorator-config/index.test.ts, e2e/helper/jsApi.ts
This change standardizes the test configuration by moving `plugins` from the root level into the `config` object. It improves consistency across all test cases.
=> test(e2e): move plugins config into config object in test cases

packages/core/src/client/hmr.ts, packages/core/src/server/socketServer.ts
When building web applications with coding agents, we need to provide the LLM with enough context. One current limitation is that the agent cannot observe runtime errors occurring in the browser.
This PR addresses that by forwarding browser runtime errors to the socket server via WebSocket and logging them in the terminal, enabling the agent to access richer context for analysis and decision-making.
- Capture `unhandledrejection` events
- Display error stacks
- Add an option to disable this behavior
- Add test cases
- Update documentation
- https://x.com/RobKnight__/status/1937724464395092137
=> feat: display browser runtime errors in the terminal

e2e/cases/server/browser-logs/index.test.ts, e2e/cases/server/browser-logs/src/index.js
Add a basic test case to verify that browser error logs are properly forwarded to the terminal.
- https://github.com/web-infra-dev/rsbuild/pull/6251
=> test: add browser logs test case for error forwarding

e2e/cases/server/browser-logs/index.test.ts, packages/core/src/client/hmr.ts, packages/core/src/defaultConfig.ts, packages/core/src/env.d.ts, packages/core/src/provider/initConfigs.ts, packages/core/src/server/compilationMiddleware.ts, packages/core/src/types/config.ts, packages/core/tests/__snapshots__/environments.test.ts.snap
Add `dev.browserLogs` configuration to control forwarding browser errors to terminal.
https://github.com/web-infra-dev/rsbuild/pull/6251
=> feat: add `dev.browserLogs` configuration

e2e/helper/logs.ts
When `expectLog` method failed, the colored logs were making it harder to read the actual error output in test failures. 
Using the original logs improves readability and debugging.
=> test(e2e): print original logs when expectLog failed

packages/core/src/server/assets-middleware/getFilenameFromUrl.ts, packages/core/src/server/assets-middleware/index.ts, packages/core/src/server/assets-middleware/middleware.ts, packages/core/src/server/assets-middleware/setupHooks.ts, packages/core/src/server/assets-middleware/setupOutputFileSystem.ts, packages/core/src/server/assets-middleware/setupWriteToDisk.ts, packages/core/src/server/buildManager.ts
This PR makes the `getFilenameFromUrl` helper independent of assets middleware context. This allows it to be used to parse source map files from browser log stacks. Also simplifies context handling by removing unused stats and using ready flag.
=> refactor(server): make filename helper independent of assets middleware context

e2e/cases/browser-logs/vue-error/index.test.ts, e2e/cases/browser-logs/vue-error/rsbuild.config.ts, e2e/cases/browser-logs/vue-error/src/EventError.vue, e2e/cases/browser-logs/vue-error/src/UndefinedError.vue, e2e/cases/browser-logs/vue-error/src/eventError.js, e2e/cases/browser-logs/vue-error/src/undefinedError.js
Add test cases for Vue runtime error logging to verify error forwarding to terminal.
- https://github.com/web-infra-dev/rsbuild/pull/6251
=> test(e2e): add Vue error logging test cases

e2e/cases/browser-logs/dedupe-log/index.test.ts, e2e/cases/browser-logs/dedupe-log/src/index.js, e2e/cases/plugin-api/plugin-before-start-dev-server-hook/index.test.ts, e2e/helper/utils.ts, packages/core/src/server/browserLogs.ts
Add tracking of last runtime error log to avoid outputting duplicate consecutive error messages. Also includes test case to verify the behavior.
=> fix(browser-logs): deduplicate consecutive runtime error logs

e2e/cases/browser-logs/basic-error/index.test.ts, e2e/cases/browser-logs/dedupe-log/index.test.ts, e2e/cases/browser-logs/unhandled-rejection/index.test.ts, packages/core/src/server/socketServer.ts
Although Rsbuild is still compatible with webpack, the newly added browser log feature does not need to support webpack as it will increase the workload.
This pull request ensures that runtime errors are only reported when the bundler is Rspack.
=> fix: skip browser error reporting for webpack

packages/core/src/client/hmr.ts, packages/core/src/server/browserLogs.ts, packages/core/src/server/devServer.ts, packages/core/src/server/socketServer.ts
Rename 'SocketMessage' to 'ServerMessage' and 'ClientMessageRuntimeError' to 'ClientMessageError' to better reflect their purpose and improve code readability.
Also update related type names and references across the codebase.
=> chore(socket): rename message types for better clarity

packages/core/src/client/hmr.ts
- Rename variables for better clarity
- Simplify error clearing and update checking logic
=> refactor: simplify variable naming in HMR client

.prettierignore, biome.json, e2e/cases/browser-logs/skip-build-error/index.test.ts, e2e/cases/browser-logs/skip-build-error/src/index.js, packages/core/src/server/socketServer.ts
Prevent reporting browser error logs when the build has failed to avoid confusion and redundant error messages.
- https://github.com/web-infra-dev/rsbuild/pull/6251
=> fix: skip browser error logs when build fails

packages/core/src/types/rsbuild.ts, website/docs/en/api/javascript-api/dev-server-api.mdx, website/docs/en/api/javascript-api/instance.mdx, website/docs/zh/api/javascript-api/dev-server-api.mdx, website/docs/zh/api/javascript-api/instance.mdx
- Mark compiler option as deprecated. The `compiler` option in the JavaScript API has been unreliable for a long time. Maintaining full compatibility for custom compilers is difficult, since many parts of Rsbuild’s internals are tightly coupled to its built-in compiler. Deprecating this option will help prevent new users from depending on it.
- Remove the deprecated `compiler` option from  documentation.
=> fix: mark custom compiler option as deprecated

packages/core/prebundle.config.mjs, packages/plugin-babel/prebundle.config.mjs
- Optimizes module resolution performance by using explicit `index.js` file paths instead of directory paths in prebundle configurations.
- Removes unused `schema-utils` prebundle config.
=> perf: optimize module resolution of compiled packages

website/docs/en/guide/basic/typescript.mdx, website/docs/zh/guide/basic/typescript.mdx
Add instructions for using tsc and vue-tsc for type checking in production builds.
=> docs: update type checking guide with tsc/vue-tsc

packages/core/src/helpers/format.ts
Checks for `stats.file` first before falling back to `stats.moduleName` for better error reporting. This ensures custom file paths take precedence over module names when available.
=> fix: prioritize custom file path in error logs

packages/core/src/types/config.ts, website/docs/en/config/dev/browser-logs.mdx, website/docs/zh/config/dev/browser-logs.mdx
Add detailed documentation for `dev.browserLogs` configuration, related: https://github.com/web-infra-dev/rsbuild/pull/6253
=> docs: add dev.browserLogs config

packages/core/src/helpers/format.ts, packages/core/src/helpers/stats.ts, packages/core/src/server/socketServer.ts
- Simplify stats error formatting logic
- Replace `formatStatsMessages` with `formatStatsError` for direct error formatting
=> refactor: simplify stats error formatting logic

packages/core/src/server/socketServer.ts
When using `stats.toJson` in Rspack, enabling the `assets: true` option introduces noticeable Rust-JS communication overhead — typically a few milliseconds for small applications, but potentially several hundred milliseconds for large ones.
This PR avoids that overhead by checking `stats.hash` instead of relying on `asset.emitted`.
- https://github.com/webpack/webpack-dev-server/pull/3906
=> perf(hmr): no need to get assets info

packages/compat/webpack/src/createCompiler.ts, packages/core/src/helpers/stats.ts, packages/core/src/index.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/provider/helpers.ts, packages/core/src/server/socketServer.ts, packages/core/src/types/rsbuild.ts
- introduce `RsbuildStats` type to better represent used stats fields
- remove redundant stats options (`errorsCount`, `warningsCount`) and simplify condition checks
=> refactor(stats): improve stats error and warning handling

e2e/cases/diagnostic/disable-stats-errors/index.test.ts, e2e/cases/diagnostic/disable-stats-errors/rsbuild.config.ts, e2e/cases/diagnostic/disable-stats-errors/src/index.js, e2e/helper/fixture.ts, packages/compat/webpack/src/createCompiler.ts, packages/core/src/helpers/stats.ts, packages/core/src/provider/createCompiler.ts, packages/core/src/provider/helpers.ts
This PR fixes a regression introduced in https://github.com/web-infra-dev/rsbuild/pull/6301.
Use `statsInstance.hasErrors()` so build still mark failures when `stats.errors` is `false`; emit a clear hint when no errors are reported because stats were suppressed and cover it with a new diagnostic e2e case.
=> fix: print hint when stats.errors is disabled

packages/compat/webpack/src/build.ts, packages/core/src/createRsbuild.ts, packages/core/src/plugins/fileSize.ts, packages/core/src/provider/build.ts
Use `context.buildState.hasErrors` instead of `stats.hasErrors()`, which will reduce the overhead slightly.
=> perf: reduce `stats.hasErrors()` calls

e2e/cases/hmr/basic/index.test.ts, e2e/cases/hmr/client-host/index.test.ts, e2e/cases/hmr/client-port-placeholder/index.test.ts, e2e/cases/hmr/error-recovery/index.test.ts, e2e/cases/hmr/multiple-connection/index.test.ts, e2e/cases/hmr/rebuild-logs/index.test.ts, e2e/cases/hmr/reconnect/index.test.ts, e2e/cases/output/clean-dist-path/index.test.ts, e2e/cases/performance/remove-console/index.test.ts, e2e/cases/plugin-react/disable-fast-refresh/index.test.ts, e2e/cases/print-file-size/basic/index.test.ts, e2e/cases/print-file-size/with-error/index.test.ts, e2e/cases/server/history-api-fallback/historyApiFallback.test.ts, e2e/cases/server/html-fallback/index.test.ts, e2e/cases/server/print-urls/index.test.ts, e2e/cases/server/public-dir-with-multi-template/index.test.ts, e2e/cases/server/public-dir-with-template/index.test.ts, e2e/cases/server/public-dir/publicDir.test.ts
- Remove hardcoded cwd declarations from test files and use the `cwd` provided by test context
- Simplify test configurations by removing redundant cwd options in build calls
- Update entry paths to use relative paths instead of `join`
=> test(e2e): remove redundant cwd declarations
