- .changeset/silent-brooms-run.md
- packages/babel-preset/src/base.ts
- packages/babel-preset/src/node.ts
- packages/babel-preset/tests/__snapshots__/node.test.ts.snap
- packages/babel-preset/tests/__snapshots__/web.test.ts.snap
- packages/babel-preset/tests/a.test.ts
- packages/babel-preset/tests/node.test.ts
- packages/babel-preset/tests/tsconfig.json
- packages/babel-preset/tests/web.test.ts
- packages/shared/package.json
- packages/shared/tests/a.test.ts
- packages/shared/tests/tsconfig.json
- packages/vitest-helper/CHANGELOG.md
- packages/vitest-helper/LICENSE
- packages/vitest-helper/README.md
- packages/vitest-helper/package.json
- Should not register dynamic-import-node plugin for web
- Add some test cases
> fix(babel-preset): not register dynamic-import-node plugin for web

- .changeset/clean-sloths-rush.md
- packages/babel-preset/src/base.ts
- packages/babel-preset/src/web.ts
- packages/babel-preset/tests/__snapshots__/node.test.ts.snap
- packages/babel-preset/tests/__snapshots__/web.test.ts.snap
Fix failed to resolve babel runtime for node bundles.
> fix(babel-preset): failed to resolve babel runtime for node bundles

- .changeset/tender-cougars-smash.md
- packages/babel-preset/src/base.ts
- packages/babel-preset/src/node.ts
- packages/babel-preset/src/types.ts
- packages/babel-preset/src/web.ts
- packages/babel-preset/tests/__snapshots__/node.test.ts.snap
- packages/babel-preset/tests/__snapshots__/web.test.ts.snap
Support Jest to use node preset.
https://github.com/web-infra-dev/rsbuild/issues/53
> feat(babel-preset): support Jest to use node preset

- packages/core/src/cli/config.ts
enable jiti esmResolve option, it will be enabled by default in jiti v2.
> chore(cli): enable jiti esmResolve option

- packages/document/docs/en/api/javascript-api/core.mdx
- packages/document/docs/en/api/javascript-api/instance.mdx
- packages/document/docs/en/guide/basic/html-template.md
- packages/document/docs/en/guide/basic/output-files.md
- packages/document/docs/zh/api/javascript-api/core.mdx
- packages/document/docs/zh/api/javascript-api/instance.mdx
- packages/shared/src/applyDefaultBuilderOptions.ts
- packages/shared/src/createContext.ts
- packages/shared/src/types/builder.ts
- packages/shared/src/types/context.ts
- packages/webpack/src/plugins/babel.ts
Remove unused `context.framework` property.
> chore: remove unused context.framework property

- package.json
- packages/core/package.json
- packages/document/package.json
- packages/plugin-esbuild/package.json
- packages/plugin-node-polyfill/package.json
- packages/plugin-stylus/package.json
- packages/plugin-swc/package.json
- packages/shared/package.json
- packages/webpack/package.json
- pnpm-lock.yaml
Bump modern.js v1.37.1 and rspress v1.1.1.
> chore: bump modern.js v1.37.1 and rspress v1.1.1

- packages/core/bin/rsbuild.js
Output a blank line to keep the greet log nice.
> fix(cli): output a blank line to keep the greet log nice

- packages/document/docs/en/plugins/list/plugin-vue.mdx
- packages/document/docs/en/plugins/list/plugin-vue2.mdx
- packages/document/docs/zh/plugins/list/plugin-vue.mdx
- packages/document/docs/zh/plugins/list/plugin-vue2.mdx
- packages/plugin-vue2/package.json
- packages/plugin-vue2/src/index.ts
- packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap
- pnpm-lock.yaml
Support extract CSS
https://github.com/vuejs/vue-loader/releases/tag/v15.11.0
> feat(plugin-vue2): support extract CSS

- e2e/cases/vue2/index.test.ts
- e2e/cases/vue2/sfc-lang-ts/rsbuild.config.ts
- e2e/package.json
- packages/plugin-vue2-jsx/CHANGELOG.md
- packages/plugin-vue2-jsx/LICENSE
- packages/plugin-vue2-jsx/README.md
- packages/plugin-vue2-jsx/modern.config.ts
- packages/plugin-vue2-jsx/package.json
- packages/plugin-vue2-jsx/src/index.ts
- packages/plugin-vue2-jsx/tests/__snapshots__/index.test.ts.snap
- packages/plugin-vue2-jsx/tests/index.test.ts
- packages/plugin-vue2-jsx/tests/tsconfig.json
- packages/plugin-vue2-jsx/tsconfig.json
- packages/plugin-vue2/src/index.ts
- packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap
- packages/plugin-vue2/tests/index.test.ts
- pnpm-lock.yaml
Split vue2-jsx as a standalone plugin.
> feat(plugin-vue2): split vue2-jsx as standalone plugin

- .github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
- .github/ISSUE_TEMPLATE/3-bug-report.zh-Hans.yml
Fix npm scope name for envinfo.
> chore(workflow): fix npm scope name for envinfo

- package.json
- packages/core/src/rspack-provider/plugins/transition.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
Enable new Oxc resolver.
https://github.com/web-infra-dev/rspack/releases/tag/v0.3.7
> perf: enable new Oxc resolver

- .github/workflows/update-modern.yml
- .github/workflows/update-rspress.yml
- create pull request to use REPO_SCOPED_TOKEN to trigger ci running in update-modern workflow and update-rspress workflow
> fix: update modern && rspress workflow token

- .changeset/config.json
- packages/create-rsbuild/package.json
Should bump create-rsbuild version.
> fix(workflow): should bump create-rsbuild version

- .changeset/silver-radios-count.md
- packages/create-rsbuild/package.json
- packages/create-rsbuild/src/index.ts
Skip copy local files for debugging.
> fix(create-rsbuild): skip copy local files for debugging

- .changeset/olive-wolves-mate.md
- packages/create-rsbuild/.npmignore
Fix failed to publish tsconfig of templates.
> fix(create-rsbuild): failed to publish tsconfig of templates

- e2e/cases/vue/index.test.ts
- e2e/cases/vue2/index.test.ts
- packages/plugin-vue/src/index.ts
- packages/plugin-vue2/src/index.ts
Remove compat logic for webpack and swc.
> fix(plugin-vue): remove compat logic for webpack and swc

- e2e/cases/performance/load-resource/src/page2/App.tsx
- package.json
- packages/doctor-utils/src/common/package.ts
- packages/shared/src/plugins/HtmlPreloadOrPrefetchPlugin/helpers/doesChunkBelongToHtml.ts
- pnpm-lock.yaml
Bump oxlint v0.0.14, fix flat map.
https://github.com/web-infra-dev/oxc/releases/tag/oxlint_v0.0.14
> chore(deps): bump oxlint v0.0.14, fix flat map

- .changeset/plenty-trains-laugh.md
- packages/compat/webpack/src/core/devMiddleware.ts
- packages/core/package.json
- packages/core/src/rspack-provider/core/devMiddleware.ts
- packages/plugin-react/src/index.ts
- packages/plugin-react/src/react.ts
- packages/shared/src/apply/html.ts
- packages/shared/src/devServer.ts
- pnpm-lock.yaml
Replace @rspack/dev-client with @rspack/plugin-react-refresh.
resolve https://github.com/web-infra-dev/rsbuild/issues/257
> refactor: replace @rspack/dev-client with @rspack/plugin-react-refresh

- .changeset/late-points-yell.md
- packages/create-rsbuild/template-react-js/package.json
- packages/create-rsbuild/template-react-ts/package.json
- packages/create-rsbuild/template-vue2-js/package.json
- packages/create-rsbuild/template-vue2-ts/package.json
- packages/create-rsbuild/template-vue3-js/package.json
- packages/create-rsbuild/template-vue3-ts/package.json
Templates depend on latest version of Rsbuild.
> feat(create-rsbuild): templates depend on latest version of Rsbuild

- .github/workflows/release-nightly.yml
Only run release-nightly in main repo.
> chore(workflow): only run release-nightly in main repo

- .changeset/strange-rice-dress.md
- packages/compat/webpack/src/types/config/source.ts
- packages/plugin-react/package.json
- pnpm-lock.yaml
Fix missing react-refresh dependency.
https://github.com/web-infra-dev/rsbuild/issues/255
> fix(plugin-react): missing react-refresh dependency

- packages/document/docs/en/guide/framework/_meta.json
- packages/document/docs/en/guide/framework/react.mdx
- packages/document/docs/en/guide/framework/vue2.mdx
- packages/document/docs/en/guide/framework/vue3.mdx
- packages/document/docs/en/plugins/list/plugin-react.mdx
- packages/document/docs/en/shared/config/source/transformImport.md
- packages/document/docs/zh/guide/framework/_meta.json
- packages/document/docs/zh/guide/framework/react.mdx
- packages/document/docs/zh/guide/framework/vue2.mdx
- packages/document/docs/zh/guide/framework/vue3.mdx
- packages/document/docs/zh/plugins/list/plugin-react.mdx
- packages/document/docs/zh/shared/config/source/transformImport.md
- add `react framework usage` doc
- add `react component library import on demand` introduce and update `source.transformImport` api introduce
- update `vue framework usage` doc
https://github.com/web-infra-dev/rsbuild/issues/6
> docs: update react

- .changeset/shy-taxis-ring.md
- e2e/cases/source/source.webpack.test.ts
- packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
- packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
- packages/compat/webpack/tests/core/initConfigs.test.ts
- packages/compat/webpack/tests/plugins/__snapshots__/babel.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/react.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/tsLoader.test.ts.snap
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/swc.test.ts.snap
- packages/document/docs/en/guide/advanced/browser-compatibility.md
- packages/document/docs/en/shared/config/output/polyfill.md
- packages/document/docs/zh/guide/advanced/browser-compatibility.md
- packages/document/docs/zh/shared/config/output/polyfill.md
- packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
- packages/plugin-react/tests/__snapshots__/features.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
- packages/plugin-vue-jsx/tests/__snapshots__/index.test.ts.snap
- packages/plugin-vue2-jsx/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/config.ts
Switch the default polyfill mode to usage, this change will greatly reduce the polyfill bundle size of most projects.
> perf: switch the default polyfill mode to usage

- packages/document/docs/en/guide/advanced/rem.md
- packages/document/docs/zh/guide/advanced/rem.md
update rem document about `How to ignore some CSS properties converted to REM?` and `How to specify the actual rootFontSize value of the page?`, and reorder them.
before:
after:
> docs: update rem usage

- .changeset/gorgeous-cheetahs-look.md
- e2e/cases/manifest/index.test.ts
- e2e/cases/tools/pug/tests/index.test.ts
- packages/compat/webpack/src/core/webpackConfig.ts
- packages/compat/webpack/src/exports/HtmlWebpackPlugin.ts
- packages/compat/webpack/src/types/hooks.ts
- packages/compat/webpack/tests/webpackConfig.test.ts
- packages/core/package.json
- packages/core/src/rspack-provider/core/rspackConfig.ts
- packages/core/src/rspack-provider/rspackPlugin/removeCssSourcemapPlugin.ts
- packages/core/tests/rspack-provider/plugins/__snapshots__/html.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/pug.test.ts.snap
- packages/document/docs/en/shared/config/tools/bundlerChain.mdx
- packages/document/docs/en/shared/config/tools/htmlPlugin.md
- packages/document/docs/en/shared/config/tools/webpack.md
- packages/document/docs/en/shared/config/tools/webpackChain.md
- packages/document/docs/zh/shared/config/tools/bundlerChain.mdx
- packages/document/docs/zh/shared/config/tools/htmlPlugin.md
- packages/document/docs/zh/shared/config/tools/webpack.md
- packages/document/docs/zh/shared/config/tools/webpackChain.md
- packages/shared/src/types/hooks.ts
- pnpm-lock.yaml
Replace @rspack/html-plugin with html-webpack-plugin.
https://github.com/web-infra-dev/rsbuild/pull/246
https://github.com/web-infra-dev/rspack/discussions/4393
>  refactor: replace @rspack/html-plugin with html-webpack-plugin

- .changeset/forty-ravens-hang.md
- packages/core/src/plugins/startUrl.ts
The error object is circular and can not be stringified.
> fix(startUrl): failed to stringify circular error object

- .changeset/hip-paws-fry.md
- packages/core/package.json
Fix failed to release static applescript.
> fix(core): failed to release static applescript

- packages/compat/uni-builder/src/rspack/index.ts
- packages/compat/uni-builder/src/shared.ts
- packages/compat/uni-builder/src/types.ts
- packages/compat/uni-builder/src/webpack/index.ts
- packages/compat/uni-builder/tests/parseConfig.test.ts
- packages/compat/webpack/tests/plugins/css.test.ts
- packages/core/src/rspack-provider/plugins/css.ts
- packages/core/tests/rspack-provider/plugins/css.test.ts
- packages/shared/src/css.ts
- packages/shared/src/types/config/output.ts
Move cssModuleLocalIdentName compat code to uni-builder.
> chore: move cssModuleLocalIdentName compat code to uni-builder

- .changeset/proud-deers-nail.md
- packages/compat/webpack/package.json
- packages/core/package.json
- packages/shared/package.json
- pnpm-lock.yaml
Using forked `@modern-js/server` from https://github.com/web-infra-dev/modern.js/tree/modern_server_light_1103.
This forked version removed many unused dependencies.
> perf: using a lighter modern.js server package

- nx.json
Exclude all md files from nx cache.
> chore(workflow): exclude all md files from nx cache

- .changeset/sharp-panthers-hide.md
- packages/core/package.json
- packages/core/src/plugins/moment.ts
- packages/core/src/rspack-provider/core/rspackConfig.ts
- packages/shared/src/types/hooks.ts
- pnpm-lock.yaml
@rsbuild/core no longer depend on webpack.
> refactor: @rsbuild/core no longer depend on webpack

- .changeset/modern-squids-relax.md
- packages/plugin-vue/package.json
- packages/plugin-vue2/package.json
- pnpm-lock.yaml
Fix failed to resolve webpack (the vue-loader depends on webpack internal modules)
> fix(plugin-vue): failed to resolve webpack

- .changeset/afraid-steaks-agree.md
- packages/document/docs/en/plugins/list/_meta.json
- packages/document/docs/en/plugins/list/index.md
- packages/document/docs/en/plugins/list/plugin-svelte.mdx
- packages/document/docs/zh/plugins/list/_meta.json
- packages/document/docs/zh/plugins/list/index.md
- packages/document/docs/zh/plugins/list/plugin-svelte.mdx
- packages/plugin-svelte/src/index.ts
- packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
- packages/plugin-svelte/tests/index.test.ts
Give a `svelteLoaderOptions` property to the options of plugin-svelte, which overrides the default options of svelte-loader.
close https://github.com/web-infra-dev/rsbuild/issues/271
> feat(plugin-svelte): allow to set options of svelte-loader

- packages/compat/webpack/src/core/webpackConfig.ts
- packages/compat/webpack/src/plugins/babel.ts
- packages/compat/webpack/src/plugins/css.ts
- packages/compat/webpack/src/plugins/output.ts
- packages/compat/webpack/src/plugins/tsLoader.ts
- packages/core/src/plugins/define.ts
- packages/core/src/plugins/html.ts
- packages/core/src/rspack-provider/core/rspackConfig.ts
- packages/core/src/rspack-provider/plugins/css.ts
- packages/plugin-babel/src/helper.ts
- packages/plugin-css-minimizer/src/index.ts
- packages/plugin-pug/src/index.ts
- packages/plugin-styled-components/src/index.ts
- packages/plugin-stylus/src/index.ts
- packages/plugin-type-check/src/index.ts
- packages/shared/src/apply/resolve.ts
- packages/shared/src/css.ts
- packages/shared/src/devServer.ts
- packages/shared/src/getLoaderOptions.ts
- packages/shared/src/mergeChainedOptions.ts
- packages/shared/src/minimize.ts
refactor the mergeChainedOptions method, accept object param.
> refactor(utils): mergeChainedOptions accept object param

- e2e/cases/html/meta/index.test.ts
- packages/compat/webpack/src/plugins/tsLoader.ts
- packages/compat/webpack/src/types/config/tools.ts
- packages/plugin-babel/src/types.ts
- packages/shared/src/mergeChainedOptions.ts
- packages/shared/src/types/config/source.ts
- packages/shared/src/types/config/tools.ts
- packages/shared/src/types/utils.ts
- packages/shared/tests/mergeChainedOptions.test.ts
Add useObjectParam option for mergeChainedOptions.
> feat(utils): add useObjectParam option for mergeChainedOptions

- e2e/cases/check-syntax/index.test.ts
- e2e/cases/tools.rspack.test.ts
Fix Rspack builtins deprecation warning, use `source.define` instead of `builtins.define`.
> test(e2e): fix Rspack builtins deprecation warning

- .changeset/thick-jokes-report.md
- packages/document/docs/en/shared/config/source/alias.md
- packages/document/docs/zh/shared/config/source/alias.md
- packages/shared/src/types/config/source.ts
Fix source.alias type, should be same as Rspack: https://www.rspack.dev/config/resolve.html#resolvealias
> types: fix source.alias type

- .changeset/strong-moose-behave.md
- cspell.json
- e2e/cases/css/style-loader/index.test.ts
- packages/shared/package.json
- packages/shared/src/css.ts
- pnpm-lock.yaml
Remove cssnano from shared package to reduce dependencies.
> chore: remove cssnano from shared package

- .changeset/gold-rocks-travel.md
- e2e/cases/web-worker/index.test.ts
- packages/core/src/plugins/splitChunks.ts
- packages/core/src/rspack-provider/plugins/swc.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/swc.test.ts.snap
- packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
- packages/plugin-react/tests/__snapshots__/features.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
since rspack release 0.3.11, we can support  preserveAllComments and dynamicImportMode.eager in rsbuild
https://github.com/web-infra-dev/rspack/releases/tag/v0.3.11
> feat: enable preserveAllComments & dynamicImportMode

- .changeset/light-hairs-bathe.md
- packages/compat/webpack/src/plugins/basic.ts
- packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/react.test.ts.snap
Disable webpack performance hints.
These logs are too complex, we can provide some hints in the Rsbuild fileSize plugin in the future.
> fix(webpack): disable webpack performance hints

- .changeset/blue-seals-end.md
- packages/core/package.json
- packages/core/types.d.ts
- packages/create-rsbuild/template-react-ts/src/env.d.ts
- packages/create-rsbuild/template-svelte-ts/src/env.d.ts
- packages/create-rsbuild/template-vue2-ts/src/env.d.ts
- packages/create-rsbuild/template-vue3-ts/src/env.d.ts
Add builtin assets and CSS modules types.
> feat: add builtin assets and CSS modules types

- .changeset/clever-steaks-march.md
- packages/doctor-core/package.json
- packages/doctor-core/src/build-utils/build/utils/loader.ts
- packages/doctor-core/tests/common/utils.ts
- pnpm-lock.yaml
rsbuild doctor will not compatible webpack4.
> fix: doctor delete webpack4

- .changeset/tidy-timers-lick.md
- e2e/cases/dev/dev.test.ts
- e2e/package.json
- e2e/scripts/shared.ts
- packages/core/src/server/devServer.ts
- packages/document/docs/en/api/javascript-api/instance.mdx
- packages/document/docs/en/shared/config/tools/devServer.md
- packages/document/docs/zh/api/javascript-api/instance.mdx
- packages/document/docs/zh/shared/config/tools/devServer.md
- packages/shared/src/devServer.ts
- packages/shared/src/types/provider.ts
- packages/shared/src/types/server.ts
- pnpm-lock.yaml
- remove useless serverOptions in rsbuild server, it's a legacy param for modern.js
- fix https urls not print when set https
fix: https://github.com/web-infra-dev/rsbuild/issues/431
> fix(server): https urls not print when set https

- packages/document/package.json
- pnpm-lock.yaml
This reverts commit 05ed6bce0ada37de979aab1653ceca0288616483.
The new Rsbuild dev server relies on https://github.com/web-infra-dev/rspress/pull/334
So we need to pin the Rspress version.
> Revert "chore(deps): bump Rspress version (#428)"

- .changeset/hot-owls-decide.md
- packages/compat/webpack/src/shared/plugin.ts
- packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/react.test.ts.snap
- packages/core/src/plugins/asset.ts
- packages/core/src/plugins/index.ts
- packages/core/src/rspack-provider/shared/plugin.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/plugins/__snapshots__/asset.test.ts.snap
- packages/core/tests/plugins/asset.test.ts
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/plugin-image-compress/tests/__snapshots__/index.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/types/plugin.ts
Merge asset plugins to a single plugin, reduce the code complexity.
> refactor(core): merge asset plugins to a single plugin

- .changeset/light-flowers-occur.md
- e2e/cases/dev/html-fallback.test.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/middlewares.ts
- packages/shared/src/types/server.ts
- packages/shared/src/url.ts
support access page without suffix and the following case：
TODO:
- print entries in terminal
- test prodServer
#448
> fix(dev-server): support access page without suffix

- .changeset/fast-garlics-fail.md
- packages/core/src/server/dev-middleware/hmr-client/createSocketUrl.ts
- packages/document/docs/en/guide/advanced/hmr.md
- packages/document/docs/en/guide/faq/hmr.md
- packages/document/docs/en/shared/config/dev/client.md
- packages/document/docs/zh/guide/advanced/hmr.md
- packages/document/docs/zh/guide/faq/hmr.md
- packages/document/docs/zh/shared/config/dev/client.md
- packages/shared/src/devServer.ts
- packages/shared/tests/devServer.test.ts
Rename hmr path to `/rsbuild-hmr`.
> chore: rename hmr path to /rsbuild-hmr

- .changeset/proud-meals-tell.md
- packages/core/src/plugins/startUrl.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/prodServer.ts
- packages/shared/src/devServer.ts
- packages/shared/src/url.ts
- packages/shared/tests/devServer.test.ts
- packages/shared/tests/url.test.ts
entry (single): index
entry (single): foo
entry(multiple): foo、bar
fix: #448
> feat(server): should print correct urls by html entry

- .changeset/polite-pillows-sip.md
- packages/core/package.json
- packages/core/src/server/dev-middleware/hmr-client/index.ts
- pnpm-lock.yaml
Remove strip-ansi dependency because Chrome support ansi code in console.
https://developer.chrome.com/docs/devtools/console/format-style/#style-ansi
> perf(core): remove strip-ansi dependency

- .changeset/stale-lizards-listen.md
- packages/core/package.json
- packages/core/src/plugins/fileSize.ts
- pnpm-lock.yaml
Remove filesize dependency, just display `kB` unit is enough.
> perf(core): remove filesize dependency

- .changeset/tall-chefs-pump.md
- packages/core/src/plugins/html.ts
- packages/shared/src/constants.ts
since rsbuild use rsbuild server, we don't need output route.json at all.
> chore(server): route.json is no longer needed

- .changeset/eighty-rocks-shop.md
- e2e/cases/source-build/common/package.json
- e2e/cases/source-build/components/package.json
- e2e/cases/source-build/utils/package.json
- packages/babel-preset/package.json
- packages/compat/plugin-swc/package.json
- packages/compat/webpack/package.json
- packages/core/package.json
- packages/core/src/rspack-provider/core/initHooks.ts
- packages/doctor-core/package.json
- packages/doctor-core/src/inner-plugins/loaders/proxy.ts
- packages/doctor-sdk/package.json
- packages/doctor-types/src/plugin/baseLoader.ts
- packages/doctor-utils/package.json
- packages/shared/package.json
- packages/shared/src/css.ts
- pnpm-lock.yaml
- scripts/tsconfig/base.json
Using exports.types to replace typesVersion.
Supported in TypeScript v4.7, ref: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html
> chore: using exports.types to replace typesVersion

- .changeset/shy-weeks-destroy.md
- examples/vanilla/src/index.js
- packages/create-rsbuild/template-vanilla-js/src/index.js
- packages/create-rsbuild/template-vanilla-ts/src/index.ts
Fix incorrect title in vanilla sample code.
> fix(create-rsbuild): incorrect title in vanilla sample code

- .changeset/forty-deers-push.md
- .changeset/mighty-ties-glow.md
- packages/create-rsbuild/template-vanilla-ts/tsconfig.json
Fix missing tsconfig.json in vanilla template.
> fix(create-rsbuild): missing tsconfig.json in vanilla template

- packages/babel-preset/package.json
- packages/compat/plugin-esbuild/package.json
- packages/compat/plugin-swc/package.json
- packages/compat/uni-builder/package.json
- packages/compat/webpack/package.json
- packages/core/package.json
- packages/create-rsbuild/package.json
- packages/monorepo-utils/package.json
- packages/plugin-assets-retry/package.json
- packages/plugin-babel/package.json
- packages/plugin-check-syntax/package.json
- packages/plugin-css-minimizer/package.json
- packages/plugin-image-compress/package.json
- packages/plugin-node-polyfill/package.json
- packages/plugin-pug/package.json
- packages/plugin-react/package.json
- packages/plugin-rem/package.json
- packages/plugin-source-build/package.json
- packages/plugin-styled-components/package.json
- packages/plugin-stylus/package.json
- packages/plugin-svelte/package.json
- packages/plugin-svgr/package.json
- packages/plugin-type-check/package.json
- packages/plugin-vue-jsx/package.json
- packages/plugin-vue/package.json
- packages/plugin-vue2-jsx/package.json
- packages/plugin-vue2/package.json
- packages/shared/package.json
No longer use publishConfig to override `types`, as `exports.types` have higher priority than `types`.
> chore: no longer use publishConfig to override types

- .changeset/tame-seas-roll.md
- packages/compat/plugin-esbuild/src/index.ts
- packages/compat/uni-builder/src/rspack/plugins/manifest.ts
- packages/compat/uni-builder/src/shared/parseCommonConfig.ts
- packages/compat/uni-builder/src/shared/plugins/fallback.ts
- packages/compat/uni-builder/tests/fallback.test.ts
- packages/core/src/index.ts
- packages/core/src/rspack-provider/index.ts
- packages/core/src/rspack-provider/types/plugin.ts
- packages/document/docs/en/api/javascript-api/types.mdx
- packages/document/docs/en/plugins/dev/core.mdx
- packages/document/docs/en/plugins/dev/index.md
- packages/document/docs/zh/api/javascript-api/types.mdx
- packages/document/docs/zh/plugins/dev/core.mdx
- packages/document/docs/zh/plugins/dev/index.md
- packages/plugin-assets-retry/src/index.ts
- packages/plugin-check-syntax/src/index.ts
- packages/plugin-node-polyfill/src/index.ts
- packages/plugin-pug/src/index.ts
- packages/plugin-source-build/src/index.ts
- packages/plugin-stylus/src/index.ts
- packages/plugin-svelte/src/index.ts
- packages/plugin-type-check/src/index.ts
- packages/plugin-vue-jsx/src/index.ts
- packages/plugin-vue/src/index.ts
- packages/plugin-vue2-jsx/src/index.ts
- packages/plugin-vue2/src/index.ts
Fix RsbuildPlugin do not provide API type by default.
> types: fix RsbuildPlugin do not provide API type by default

- .changeset/forty-phones-do.md
- e2e/cases/tools.rspack.test.ts
- packages/core/src/rspack-provider/core/rspackConfig.ts
support get rspack.xxx in tools.rspack
> fix: can't get rspack util in tools.rspack

- .changeset/selfish-ants-behave.md
- packages/document/docs/en/guide/faq/features.md
- packages/document/docs/en/shared/config/source/entry.md
- packages/document/docs/zh/guide/faq/features.md
- packages/document/docs/zh/shared/config/source/entry.md
- packages/shared/src/createContext.ts
Support use index.cjs or index.mjs as the default entry.
> feat: support use index.cjs or index.mjs as the default entry

- .changeset/selfish-boxes-battle.md
- packages/core/package.json
- packages/doctor-core/package.json
- packages/doctor-types/package.json
- packages/plugin-react/package.json
- packages/shared/package.json
- pnpm-lock.yaml
Bump Rspack 0.3.13 to fix new Class error.
https://github.com/web-infra-dev/rspack/issues/4643
> fix(deps): bump Rspack 0.3.13 to fix new Class error

- .changeset/heavy-poems-act.md
- e2e/cases/javascript-api/plugin/index.test.ts
- e2e/cases/javascript-api/plugin/rsbuild.config.js
- e2e/cases/javascript-api/plugin/src/A.vue
- e2e/cases/javascript-api/plugin/src/index.js
- packages/core/src/cli/config.ts
- packages/core/src/cli/run.ts
- packages/core/src/createRsbuild.ts
- packages/shared/src/types/config/index.ts
Should register config.plugins when using JavaScript API.
> fix: should register config.plugins when using JavaScript API

- .changeset/few-carpets-wink.md
- packages/core/src/plugins/entry.ts
- packages/core/src/plugins/startUrl.ts
- packages/shared/src/createContext.ts
Should not print entry error when entry is set by plugins.
> fix: should not print entry error when entry is set by plugins

- .changeset/brown-boats-tan.md
- packages/document/docs/en/api/javascript-api/instance.mdx
- packages/document/docs/zh/api/javascript-api/instance.mdx
- packages/shared/src/createContext.ts
- packages/shared/src/types/context.ts
Remove context.srcPath as this value can reflect the real src path, because the `entry` can be defined by user.
> refactor: remove context.srcPath

- .changeset/grumpy-donuts-eat.md
- packages/compat/webpack/src/core/initConfigs.ts
- packages/core/src/rspack-provider/core/initConfigs.ts
- packages/shared/src/createContext.ts
context should be updated after running modifyRsbuildConfig hook.
> fix: context should be updated after modifyRsbuildConfig hook

- packages/document/docs/en/guide/basic/configure-rspack.mdx
https://rsbuild.dev/guide/basic/configure-rspack.html#use-bundler-chain
The English documentation incorrectly references content from the Chinese documentation.
> docs: fix en "Use bundler Chain" block import from @zh scope.

- .changeset/ninety-seals-listen.md
- packages/doctor-sdk/src/sdk/multiple/controller.ts
- packages/doctor-sdk/src/sdk/sdk/core.ts
- packages/doctor-sdk/src/sdk/server/apis/bundle-diff.ts
- packages/doctor-sdk/tests/sdk/core/hooks.test.ts
- packages/doctor-types/src/manifest.ts
- packages/doctor-types/src/sdk/hooks.ts
- packages/doctor-types/src/sdk/instance.ts
- packages/doctor-types/src/sdk/server/apis/index.ts
- packages/doctor-utils/src/common/data/index.ts
rsbuild doctor don't need uploade cloud data, so delete the cloudurl property.
#558
> fix(rsbuild-doctor): should delete the useless cloudurl property

- .changeset/late-otters-fry.md
- packages/compat/uni-builder/src/rspack/index.ts
- packages/compat/uni-builder/src/shared/parseCommonConfig.ts
- packages/compat/uni-builder/src/shared/plugins/frameworkConfig.ts
- packages/compat/uni-builder/src/types.ts
- packages/compat/uni-builder/src/webpack/index.ts
- packages/core/src/createRsbuild.ts
- packages/core/src/plugins/cache.ts
- packages/core/tests/plugins/__snapshots__/cache.test.ts.snap
- packages/core/tests/plugins/cache.test.ts
- packages/doctor-webpack-plugin/tests/plugins/__snapshots__/plugin.test.ts.snap
- packages/document/docs/en/api/javascript-api/core.mdx
- packages/document/docs/en/api/javascript-api/instance.mdx
- packages/document/docs/zh/api/javascript-api/core.mdx
- packages/document/docs/zh/api/javascript-api/instance.mdx
- packages/shared/src/createContext.ts
- packages/shared/src/types/context.ts
- packages/shared/src/types/rsbuild.ts
Move the configPath option of `createRsbuild` to uni-builder. This option is designed for the framework config, and maybe misleading for Rsbuild users.
> refactor: move configPath option to uni-builder

- .changeset/lovely-baboons-heal.md
- packages/core/package.json
- packages/doctor-core/package.json
- packages/doctor-types/package.json
- packages/plugin-react/package.json
- packages/shared/package.json
- pnpm-lock.yaml
Bump Rspack v0.3.14.
https://github.com/web-infra-dev/rspack/releases/tag/v0.3.14
> chore(deps): bump Rspack v0.3.14

- packages/document/docs/en/shared/config/html/tags.md
- packages/document/docs/zh/shared/config/html/tags.md
Fix html.tags append default value.
> docs: fix html.tags append default value

- packages/compat/plugin-swc/package.json
- packages/compat/plugin-swc/src/utils.ts
- packages/compat/webpack/package.json
- packages/compat/webpack/src/plugins/react.ts
- packages/plugin-react/package.json
- packages/plugin-react/src/index.ts
- packages/plugin-react/src/utils.ts
- packages/shared/package.json
- packages/shared/src/utils.ts
- pnpm-lock.yaml
Move react utils to plugin react.
> chore: move react utils to plugin react

- .changeset/hip-cherries-fold.md
- e2e/cases/react/remove-prop-types/index.test.ts
- e2e/cases/react/split-chunk/index.test.ts
- e2e/cases/react/split-chunk/src/App.jsx
- e2e/cases/react/split-chunk/src/index.js
- packages/compat/webpack/tests/webpackConfig.test.ts
- packages/plugin-css-minimizer/src/index.ts
- packages/plugin-react/src/react.ts
- packages/plugin-react/src/splitChunks.ts
- packages/shared/src/types/bundlerConfig.ts
Fix failed to split react chunks if override chunkSplit.
https://github.com/web-infra-dev/rsbuild/issues/590
> fix(react): failed to split react chunks if override chunkSplit

- .changeset/khaki-camels-exercise.md
- packages/core/src/plugins/externals.ts
- packages/core/src/rspack-provider/core/initConfigs.ts
- packages/core/src/rspack-provider/core/rspackConfig.ts
- packages/plugin-css-minimizer/src/index.ts
- packages/shared/src/types/bundlerConfig.ts
- packages/shared/src/types/rspack.ts
- packages/test-helper/src/rsbuild.ts
Simplify BundlerChain and BundlerConfig, use `RspackConfig` as the default config type.
> types: simplify BundlerChain and BundlerConfig

- .changeset/three-dogs-draw.md
- e2e/cases/import-antd-v4/index.test.ts
- e2e/cases/import-antd-v5/index.test.ts
- e2e/cases/import-arco/index.test.ts
- packages/compat/uni-builder/src/shared/parseCommonConfig.ts
- packages/compat/uni-builder/src/shared/plugins/splitChunk.ts
- packages/core/src/plugins/splitChunks.ts
- packages/core/tests/plugins/splitChunks.test.ts
- packages/document/docs/en/guide/optimization/split-chunk.md
- packages/document/docs/en/shared/config/performance/chunkSplit.md
- packages/document/docs/zh/guide/optimization/split-chunk.md
- packages/document/docs/zh/shared/config/performance/chunkSplit.md
- packages/plugin-react/src/splitChunks.ts
- packages/plugin-react/tests/__snapshots__/features.test.ts.snap
- packages/shared/src/pluginStore.ts
- packages/shared/src/utils.ts
- packages/shared/tests/utils.test.ts
Move component chunks to uni-builder.
Split UI components to chunks is not a best practice for all cases.
> refactor(plugin-react): move component chunks to uni-builder

- .changeset/brave-falcons-perform.md
- packages/doctor-core/src/inner-plugins/plugins/loader.ts
- packages/doctor-core/src/inner-plugins/plugins/progress.ts
rsbuild doctor temporarily compatible with rspack canary version.
> fix: rsbuild doctor temporarily compatible with rspack canary version.

- .changeset/warm-donuts-compete.md
- packages/compat/webpack/package.json
- packages/core/package.json
- packages/plugin-assets-retry/package.json
- packages/plugin-rem/package.json
- packages/plugin-source-build/src/index.ts
- packages/shared/package.json
- pnpm-lock.yaml
Bump html-rspack-plugin v5.5.7 to reduce deps.
> perf: bump html-rspack-plugin v5.5.7 to reduce deps

- CONTRIBUTING.md
Add benchmark in CONTRIBUTING docs.
> docs: add benchmark in CONTRIBUTING docs

- .changeset/witty-taxis-beam.md
- packages/core/src/rspack-provider/core/createCompiler.ts
- packages/core/tests/rspack-provider/createCompiler.test.ts
create Compiler instead of MultiCompiler when target length is 1:
> perf: create Compiler instead of MultiCompiler when target length is 1

- e2e/cases/dev/dev.test.ts
skip https test case, it will fail in some CI machine.
> fix: skip https test case

- .changeset/nine-pumpkins-hear.md
- packages/doctor-core/src/inner-plugins/plugins/loader.ts
- packages/doctor-core/src/inner-plugins/plugins/progress.ts
- packages/doctor-types/src/plugin/baseCompiler.ts
rsbuild doctor compatible with rspack canary version.
because rspack's compiler.webpack type  changes from:
```ts
webpack: any;
````
to
```ts
webpack: typeof import("./rspack").rspack & typeof import("./exports");
```
#607
> fix(rsbuild-doctor): rsbuild doctor compatible with rspack canary version.

- .changeset/fifty-bobcats-love.md
- packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/react.test.ts.snap
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/apply/basic.ts
The default aggregateTimeout of WatchPack is 200ms, using smaller values can improve hmr performance.
https://github.com/webpack/watchpack
> perf: reduce aggregateTimeout to speed up HMR

- .changeset/rude-buttons-carry.md
- e2e/cases/dev/html-fallback.test.ts
- packages/core/src/server/devServer.ts
should not join pwd and distPath when distPath is absolute
> fix(server): should fallback success when distPath is absolute

- .changeset/polite-tips-melt.md
- .github/PULL_REQUEST_TEMPLATE.md
- packages/core/src/cli/config.ts
- packages/shared/src/utils.ts
Set 300ms debounce to avoid restart CLI frequently.
> feat(cli): set 300ms debounce to avoid restart frequently

- .changeset/swift-days-kiss.md
- packages/core/src/cli/commands.ts
- packages/core/src/cli/config.ts
- packages/core/src/server/restart.ts
Do not exit process when editing config file.
Maybe user is editing config file and write some invalid config, this should not break the process.
> fix(cli): should not exit process when editing config file

- .changeset/heavy-bulldogs-bow.md
- e2e/cases/dev/html-fallback.test.ts
- e2e/cases/prod-server/index.test.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/middlewares.ts
- packages/core/src/server/prodServer.ts
- packages/document/docs/en/config/options/server.mdx
- packages/document/docs/en/shared/config/server/htmlFallback.md
- packages/document/docs/zh/config/options/server.mdx
- packages/document/docs/zh/shared/config/server/htmlFallback.md
- packages/shared/src/config.ts
- packages/shared/src/types/config/server.ts
support fallback to `index.html` by default when the requested page is not found.
TODO: support htmlFallback to 'closest'
> feat(server): support htmlFallback

- .changeset/neat-buckets-watch.md
- examples/react/rsbuild.config.ts
- packages/core/src/server/prodServer.ts
- packages/core/src/server/proxy.ts
- packages/document/docs/en/config/options/dev.mdx
- packages/document/docs/en/config/options/server.mdx
- packages/document/docs/en/shared/config/server/proxy.md
- packages/document/docs/zh/config/options/dev.mdx
- packages/document/docs/zh/config/options/server.mdx
- packages/document/docs/zh/shared/config/server/proxy.md
- packages/shared/src/types/config/dev.ts
- packages/shared/src/types/config/server.ts
Rename `dev.proxy` to `server.proxy` to support preview server.
> refactor: rename `dev.proxy` to `server.proxy` to support preview server

- .changeset/warm-cups-cross.md
- packages/core/src/plugins/fileSize.ts
> fix(core): printFileSize throw err when set output.filename query

- .changeset/empty-dots-greet.md
- packages/core/src/rspack-provider/plugins/transition.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
No need to set newResolver config in Rspack v0.4.0, the newResolver is enabled by default.
https://github.com/web-infra-dev/rspack/releases/tag/v0.4.0
> chore: no need to set newResolver config

- .changeset/beige-lies-deny.md
- packages/shared/src/chain.ts
Remove unused CHAIN_ID, `html-loader` and `FaviconUrlPlugin` are no longer used in Rsbuild.
> chore(shared): remove unused CHAIN_ID

- .changeset/slow-gifts-wonder.md
- packages/compat/uni-builder/src/rspack/plugins/manifest.ts
- packages/compat/uni-builder/src/webpack/plugins/manifest.ts
- packages/compat/uni-builder/tests/__snapshots__/manifest.test.ts.snap
- packages/compat/uni-builder/tests/manifest.test.ts
Generate manifest correctly when targets contain node.
If the current project has multiple types of build artifacts, such as including SSR build artifacts, multiple manifest.json files will be generated.
- web artifact: `asset-manifest.json`
- node artifact: `asset-manifest-node.json`
> fix(uni-builder): generate manifest correctly when targets contain node

- packages/document/docs/en/guide/basic/html-template.md
- packages/document/docs/zh/guide/basic/html-template.md
Update template parameters, the `meta` and `title` properties are no longer injected.
> docs: update template parameters

- .changeset/breezy-days-cry.md
- packages/core/src/server/dev-middleware/index.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/middlewares.ts
- packages/shared/src/types/server.ts
when we set `dev.assetPrefix`, we will transform it as webpack `output.publicPath`, and webpack-dev-middleware only find file startsWith publicPath, but html file without publicPath.
> chore(server): compat html without publicPath by warp dev-middleware

- .changeset/lucky-experts-dance.md
- e2e/cases/doctor-webpack/loaders/loader.test.ts
- packages/doctor-core/src/build-utils/build/utils/loader.ts
Compatible loader's rule.use maybe empty array.
#663
> fix: compatible loader's rule.use maybe empty array

- .changeset/fresh-moles-promise.md
- e2e/cases/html/meta/index.test.ts
- e2e/cases/html/meta/src/index.html
- e2e/cases/html/meta/src/index.js
- packages/core/src/plugins/html.ts
- packages/document/docs/en/shared/config/html/meta.md
- packages/document/docs/zh/shared/config/html/meta.md
Should not inject duplicated charset meta tag.
close https://github.com/web-infra-dev/rsbuild/issues/657
> fix: should not inject duplicated charset meta tag

- e2e/cases/cli/build-watch/.gitignore
- e2e/cases/cli/build-watch/index.test.ts
- e2e/cases/cli/build-watch/rsbuild.config.mjs
- e2e/cases/cli/build-watch/tsconfig.json
- packages/core/src/cli/commands.ts
- packages/document/docs/en/guide/basic/cli.mdx
- packages/document/docs/zh/guide/basic/cli.mdx
Support `rsbuild build --watch` and `rsbuild build -w`
> feat(cli): support build --watch option

- .changeset/grumpy-toys-sin.md
- packages/core/src/rspack-provider/core/createCompiler.ts
Log the current used Rspack version:
>  feat(core): log the current used Rspack version

- .changeset/few-insects-mix.md
- packages/core/src/rspack-provider/core/createCompiler.ts
- packages/core/src/rspack-provider/provider.ts
- packages/core/src/rspack-provider/shared.ts
- packages/core/tests/rspack-provider/shared/rspackVersion.test.ts
Make rspack version check 3x faster.
before:
after:
> perf: make rspack version check 3x faster

- .changeset/early-kiwis-poke.md
- packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/react.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/resolve.test.ts.snap
- packages/compat/webpack/tests/plugins/resolve.test.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/core/tests/rspack-provider/plugins/resolve.test.ts
- packages/document/docs/en/guide/basic/typescript.md
- packages/document/docs/en/plugins/list/plugin-type-check.mdx
- packages/document/docs/zh/guide/basic/typescript.md
- packages/document/docs/zh/plugins/list/plugin-type-check.mdx
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/apply/resolve.ts
Sometimes user just forget to create a tsconfig file and the resolver will failed to resolve ts files.
This change allows user to resolve ts files without a tsconfig file.
> feat: resolve ts files by default

- .github/pr-labeler.yml
- .github/release.yml
- .github/workflows/pr-label.yaml
Add PR labeler to workflow, this allows to:
- add label for PR
- generate CHANGELOG via GitHub release.
> workflow: add PR labeler

- packages/document/docs/en/guide/basic/configure-rspack.mdx
- packages/document/docs/en/guide/basic/tailwindcss.mdx
- packages/document/docs/en/guide/basic/unocss.mdx
- packages/document/docs/en/shared/config/tools/rspack.md
- packages/document/docs/zh/guide/basic/tailwindcss.mdx
- packages/document/docs/zh/guide/basic/unocss.mdx
- packages/document/docs/zh/shared/config/tools/rspack.md
- packages/shared/src/types/hooks.ts
Mark getCompiledPath as private, we do not want user to use this util, because the compiled dependencies are unstable and may change during Rsbuild development.
> docs: mark getCompiledPath as private

- .changeset/red-walls-crash.md
- e2e/cases/preview/index.test.ts
- packages/compat/webpack/src/core/initConfigs.ts
- packages/compat/webpack/src/provider.ts
- packages/core/src/rspack-provider/core/initConfigs.ts
- packages/core/src/rspack-provider/index.ts
- packages/core/src/rspack-provider/provider.ts
Fix failed to modify server port in plugins.
> fix: failed to modify server port in plugins

- .changeset/perfect-queens-carry.md
- packages/compat/webpack/src/core/createCompiler.ts
- packages/compat/webpack/src/core/initHooks.ts
- packages/compat/webpack/src/provider.ts
- packages/compat/webpack/src/types/plugin.ts
- packages/core/src/rspack-provider/core/initHooks.ts
- packages/core/src/rspack-provider/provider.ts
- packages/core/src/types.ts
- packages/shared/src/types/hooks.ts
- packages/shared/src/types/plugin.ts
- packages/shared/src/types/provider.ts
Unify compiler type, use Rspack compiler by default.
> types: unify compiler type, use Rspack compiler by default

- .changeset/poor-buses-brush.md
- packages/plugin-svelte/src/index.ts
- packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Use wildcard in conditionNames.
https://www.rspack.dev/config/resolve.html#resolveconditionnames
> fix(plugin-svelte): use wildcard in conditionNames

- examples/service-worker/build.mjs
- examples/service-worker/index.html
- examples/service-worker/package.json
- examples/service-worker/src/sw.ts
- packages/shared/src/apply/output.ts
- pnpm-lock.yaml
https://github.com/web-infra-dev/rsbuild/blob/9c1919845979029fa44d880a13dfe797825e37dd/packages/shared/src/apply/output.ts#L57-L60
This behaviour seems weird because nor service worker / web worker / edge worker have exports.
@GiveMe-A-Name provide some information:
- The service worker target currently used for the edge worker service of corp.
- It even not a complete worker destination but a module and will be warpped.
So we need to remove the `libraryTarget` option here.
Maybe should refactor target plugin of @modern-js/app-tools later.
> feat: fix issue of service worker & add example

- .changeset/slow-badgers-love.md
- packages/core/src/cli/config.ts
Improve defineConfig typing to make the following types correct:
```ts
const config = defineConfig({});
console.log(config.html?.appIcon);
```
> types: improve defineConfig typing

- .changeset/popular-pants-refuse.md
- e2e/cases/source-build/app/rsbuild.config.ts
- e2e/cases/source-build/index.test.ts
- packages/plugin-source-build/src/index.ts
Fix plugin-source-build not work when use Rspack.
https://github.com/web-infra-dev/rsbuild/issues/203
> fix(plugin-source-build): not work when use Rspack

- .changeset/plenty-grapes-peel.md
- e2e/cases/html/combined/html.test.ts
- e2e/cases/html/cross-origin/index.test.ts
- e2e/cases/html/cross-origin/src/index.js
- e2e/cases/performance/load-resource/index.test.ts
- packages/shared/src/plugins/HtmlCrossOriginPlugin.ts
- packages/shared/src/plugins/HtmlPreloadOrPrefetchPlugin/index.ts
fix preload resource can't be used when crossOrigin attr does not match.
> fix: preload resource can't be used if crossOrigin attr not match

- .changeset/fuzzy-paws-attend.md
- packages/compat/plugin-swc/package.json
- packages/compat/plugin-swc/src/minimizer.ts
- packages/compat/plugin-swc/src/utils.ts
- packages/core/src/index.ts
- packages/document/docs/en/api/javascript-api/core.mdx
- packages/document/docs/zh/api/javascript-api/core.mdx
- packages/plugin-check-syntax/src/helpers/printErrors.ts
- packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
- packages/plugin-svelte/src/index.ts
- packages/plugin-type-check/src/index.ts
- pnpm-lock.yaml
- scripts/modern.base.config.ts
Export logger module as a helper, this allows Rsbuild plugins to use the same logger module and output with the same log format.
> feat(core): export logger module as a helper

- packages/document/docs/en/plugins/dev/core.mdx
- packages/document/docs/en/plugins/dev/hooks.mdx
- packages/document/docs/zh/plugins/dev/core.mdx
- packages/document/docs/zh/plugins/dev/hooks.mdx
Remove webpack related hooks, modifyWebpackChain and modifyWebpackConfig hooks are only used by Modern.js.
> docs: remove webpack related hooks

- .changeset/four-hats-pretend.md
- cspell.json
- e2e/package.json
- packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
- packages/core/package.json
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/doctor-core/package.json
- packages/doctor-rspack-plugin/package.json
- packages/doctor-types/package.json
- packages/plugin-react/package.json
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/shared/package.json
- packages/shared/src/apply/basic.ts
- packages/test-helper/package.json
- pnpm-lock.yaml
Bump Rspack to v0.4.1.
ref: https://github.com/web-infra-dev/rspack/releases/tag/untagged-b8f2eaffa446dddecc66
> feat(deps): bump Rspack to v0.4.1

- .changeset/warm-peas-run.md
- packages/compat/uni-builder/src/rspack/index.ts
- packages/compat/uni-builder/src/types.ts
- packages/plugin-babel/src/index.ts
support rspack tools.babel  in uni-builder
https://github.com/web-infra-dev/rsbuild/issues/7
> feat(uni-builder): support tools.babel in rspack mode

- packages/document/docs/en/api/javascript-api/core.mdx
- packages/document/docs/zh/api/javascript-api/core.mdx
Add loadEnv method to JavaScript API document.
> docs: add loadEnv method to JavaScript API document

- packages/document/docs/en/shared/config/server/https.md
- packages/document/docs/zh/shared/config/server/https.md
Add mkcert tip for https dev server.
https://web.dev/articles/how-to-use-local-https?hl=en
> docs: add mkcert tip for https dev server

- packages/document/docs/en/shared/config/tools/rspack.md
- packages/document/docs/zh/shared/config/tools/rspack.md
- packages/shared/src/types/config/tools.ts
Using loose plugin type for appendPlugins of `tools.rspack` config, as the webpack plugins type is not the same as rspack plugins.
> types: using loose plugin type for appendPlugins  @chenjiahan

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
No longer require changesets in pull request, we have switched to use GitHub release page to generate the CHANGELOG.
This means changeset is optional and only be used to bump the package version.
https://github.com/web-infra-dev/rsbuild/issues/473
> chore(workflow): no longer require changesets

- e2e/scripts/shared.ts
- examples/react-webpack/package.json
- examples/react-webpack/rsbuild.config.ts
- packages/compat/uni-builder/src/rspack/index.ts
- packages/compat/uni-builder/src/shared/parseCommonConfig.ts
- packages/compat/uni-builder/src/types.ts
- packages/compat/webpack/README.md
- packages/compat/webpack/package.json
- packages/compat/webpack/src/plugins/minimize.ts
- packages/compat/webpack/src/types/config/tools.ts
- packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/minimize.test.ts.snap
- packages/compat/webpack/tsconfig.json
- packages/plugin-css-minimizer/src/index.ts
- pnpm-lock.yaml
Remove builtin CSS minimizer from `@rsbuild/webpack`.
This allows us to align the `RsbuildConfig` typing of `@rsbuild/core` and `@rsbuild/webpack`.
> refactor(webpack): remove builtin CSS minimizer

- .changeset/stale-hairs-check.md
- packages/compat/uni-builder/src/shared/parseCommonConfig.ts
- packages/compat/uni-builder/src/types.ts
- packages/compat/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap
- packages/core/src/server/devServer.ts
- packages/core/src/server/prodServer.ts
- packages/shared/src/server.ts
- packages/shared/tests/server.test.ts
support html.disableHtmlFolder, and outputStructure default 'nested'
https://github.com/web-infra-dev/rsbuild/issues/14
> feat(uni-builder): support disableHtmlFolder

- packages/document/docs/en/shared/config/server/proxy.md
- packages/document/docs/zh/shared/config/server/proxy.md
- packages/shared/package.json
- packages/shared/src/types/config/server.ts
- pnpm-lock.yaml
- scripts/prebundle/package.json
`server.proxy.context` should allow function type.
close https://github.com/web-infra-dev/rsbuild/issues/797
> types: proxy.context should allow function type

- .github/workflows/test-ubuntu.yml
- pnpm-lock.yaml
- scripts/check-changeset/package.json
- scripts/update-packages/package.json
Bump tsx from v3 to v4.
ref: https://github.com/privatenumber/tsx/releases/tag/v4.0.0
> chore(deps): bump tsx from v3 to v4

- .changeset/young-guests-shop.md
- packages/plugin-babel/package.json
- packages/plugin-babel/src/plugin.ts
- pnpm-lock.yaml
Fix lodash breaks the mjs artifact.
> fix(plugin-babel): lodash breaks the mjs artifact

- .changeset/gentle-years-lick.md
- packages/core/src/plugins/fileSize.ts
Optimize the order of print file size, print largest file at the bottom.
This allows developers to quickly locate large files when there are many files.
> feat: optimize the order of print file size

- e2e/cases/css/tailwindcss/index.test.ts
- e2e/cases/css/tailwindcss/postcss.config.js
- e2e/cases/css/tailwindcss/src/index.css
- e2e/cases/css/tailwindcss/src/index.html
- e2e/cases/css/tailwindcss/src/index.ts
- e2e/cases/css/tailwindcss/tailwind.config.js
- e2e/package.json
- pnpm-lock.yaml
Add basic case for tailwindcss.
We still need to check if the tailwindcss + builtin autoprefixer can work correctly.
> test(e2e): add basic case for tailwindcss

- README.zh-CN.md
- packages/document/docs/en/shared/config/dev/writeToDisk.md
- packages/document/docs/zh/api/javascript-api/core.mdx
- packages/document/docs/zh/api/start/build-target.md
- packages/document/docs/zh/shared/config/dev/writeToDisk.md
Add more description for writeToDisk config.
https://github.com/webpack/webpack-dev-middleware#writetodisk
> docs: add more description for writeToDisk

- packages/document/docs/en/shared/config/dev/assetPrefix.md
- packages/document/docs/en/shared/config/output/assetPrefix.md
- packages/document/docs/zh/guide/advanced/env-vars.md
- packages/document/docs/zh/shared/config/dev/assetPrefix.md
- packages/document/docs/zh/shared/config/output/assetPrefix.md
Currently, `proecss.env.ASSET_PREFIX` can only be accessed in client code, so we should mention this in the documentation.
> docs: add tip for ASSET_PREFIX env var

- packages/plugin-react/package.json
- pnpm-lock.yaml
Reduce depdendencies of react plugin and fix peer dependency warning.
- https://github.com/web-infra-dev/rspack/pull/4807
- https://github.com/web-infra-dev/rsbuild/issues/255
> perf(plugin-react): reduce deps and fix peer dep warning

- packages/core/src/provider/plugins/minimize.ts
- packages/core/src/provider/plugins/rspackProfile.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/prodServer.ts
Load proxy module on demand, make dev server startup 5ms faster.
> perf(server): load proxy module on demand

- packages/core/src/provider/core/createCompiler.ts
No need to load dev middleware when building, make build 15ms faster.
> perf(build): no need to load dev middleware when building

- packages/plugin-react/src/splitChunks.ts
- packages/plugin-react/tests/__snapshots__/features.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Split react-refresh utils to lib-react chunk.
https://github.com/web-infra-dev/rspack/pull/4807
> fix(plugin-react): split react-refresh utils to lib-react chunk

- e2e/cases/vue/split-chunk/index.test.ts
- e2e/cases/vue/split-chunk/src/index.js
- e2e/package.json
- packages/compat/webpack/tests/core/initConfigs.test.ts
- packages/compat/webpack/tests/plugins/default.test.ts
- packages/document/docs/en/plugins/list/plugin-react.mdx
- packages/document/docs/en/plugins/list/plugin-vue.mdx
- packages/document/docs/zh/plugins/list/plugin-react.mdx
- packages/document/docs/zh/plugins/list/plugin-vue.mdx
- packages/plugin-vue/src/index.ts
- packages/plugin-vue/src/splitChunks.ts
- pnpm-lock.yaml
Apply default split chunk rules, same as the react plugin.
> feat(plugin-vue): apply default split chunk rules

- e2e/cases/vue2/split-chunk/index.test.ts
- e2e/cases/vue2/split-chunk/src/index.js
- packages/document/docs/en/plugins/list/plugin-vue2.mdx
- packages/document/docs/zh/plugins/list/plugin-vue2.mdx
- packages/plugin-vue2/src/index.ts
- packages/plugin-vue2/src/splitChunks.ts
Apply default split chunk rules, same as the react and vue3 plugin.
> feat(plugin-vue2): apply default split chunk rules

- .changeset/warm-bears-exercise.md
- packages/core/src/provider/core/createContext.ts
- packages/shared/src/types/config/source.ts
Remove the deprecated `source.entries` config.
`source.entries` has been renamed to `source.entry` since Rsbuild v0.1.0, and we will remove the legacy `source.entries` config in Rsbuild v0.2.0. 
- before:
```js
source: {
entries: {}
}
}
```
- after:
```js
source: {
entry: {}
}
}
```
https://github.com/web-infra-dev/rsbuild/discussions/813
> breaking change: remove deprecated source.entries config

- e2e/scripts/shared.ts
Port `10080` is not available in CI, so we start with `11000`
- https://github.com/web-infra-dev/rsbuild/actions/runs/7116541116/job/19392263962
- https://github.com/web-infra-dev/rsbuild/actions/runs/7116541116/job/19375201965
> test(e2e): fix ERR_UNSAFE_PORT error in CI

- .changeset/nine-numbers-sort.md
- packages/core/src/server/devServer.ts
- packages/core/src/server/httpServer.ts
- packages/core/src/server/prodServer.ts
createHttpServer is not used in middleware mode, so createHttpServer should independent with rsbuildServer.
> refactor(server): extract createHttpServer method from rsbuildServer

- packages/shared/src/constants.ts
Fix incorrect log name for service worker, should be `Service Worker` instead of `Server Worker`.
> fix: incorrect log name for service worker

- package.json
- pnpm-lock.yaml
This reverts commit f40c98f98660a5474ad9493c61f4b82152f5dca1.
The v2.42.1 version Modern.js Module will use `tsc --build` and can not generate type declaration correctly.
> Revert "chore(deps): bump Modern.js v2.42.1 (#888)"

- packages/core/src/server/compiler-dev-middleware/index.ts
- packages/core/src/server/compiler-dev-middleware/socketServer.ts
- packages/core/src/server/devMiddlewares.ts
- packages/core/src/server/devServer.ts
- packages/shared/src/types/server.ts
RsbuildDevServer is only used to init rsbuild devMiddlewares
> refactor: use getMiddlewares instead of RsbuildDevServer

- packages/compat/webpack/src/provider.ts
- packages/core/src/createRsbuild.ts
- packages/core/src/provider/provider.ts
- packages/core/src/server/devMiddlewares.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/index.ts
- packages/shared/src/types/provider.ts
- packages/shared/src/types/rsbuild.ts
- packages/shared/src/types/server.ts
rsbuild.createDevServer provides rsbuild server api and default middleware,  it is designed for high-level frameworks that require a custom server, such as modern.js.
> feat: support rsbuild.createDevServer

- e2e/cases/umd/index.test.ts
- packages/plugin-umd/src/index.ts
Add globalObject config to support Node.js env.
https://webpack.js.org/configuration/output/#outputglobalobject
> fix(plugin-umd): add globalObject to support Node.js env

- packages/shared/src/getLoaderOptions.ts
Use deepmerge instead of `lodash.merge`.
> chore(shared): use deepmerge instead of lodash.merge

- packages/compat/webpack/src/core/createCompiler.ts
- packages/core/src/provider/core/createCompiler.ts
- packages/core/src/server/compiler-dev-middleware/index.ts
- packages/document/docs/en/shared/onDevCompileDone.md
- packages/document/docs/zh/shared/onDevCompileDone.md
- packages/shared/src/types/hooks.ts
- feat: add stats params in onDevCompileDone hook
- chore: remove useless onChange event (it is equal with rsbuild.onDevCompileDone hook)
> feat: add stats params in onDevCompileDone hook

- packages/document/docs/en/config/output/inline-scripts.mdx
- packages/document/docs/en/config/output/inline-styles.mdx
- packages/document/docs/en/config/performance/chunk-split.mdx
- packages/document/docs/en/config/source/include.mdx
- packages/document/docs/en/guide/advanced/browser-compatibility.md
- packages/document/docs/en/guide/optimization/optimize-bundle.md
- packages/document/docs/en/guide/optimization/split-chunk.md
- packages/document/docs/zh/config/output/inline-scripts.mdx
- packages/document/docs/zh/config/output/inline-styles.mdx
- packages/document/docs/zh/config/performance/chunk-split.mdx
- packages/document/docs/zh/config/source/include.mdx
- packages/document/docs/zh/guide/advanced/browser-compatibility.md
- packages/document/docs/zh/guide/optimization/optimize-bundle.md
- packages/document/docs/zh/guide/optimization/split-chunk.md
- packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
- packages/plugin-babel/tests/index.test.ts
Update path separator examples to match Windows path.
Use `[\\/]` to match the path separator because different operating systems use different path separators. Using `[\\/]` ensures that the paths will match in both MacOS and Windows.
https://github.com/webpack/webpack/issues/2073
> docs: update path separator examples to match Windows path

- e2e/cases/server/custom-server/index.test.ts
- e2e/cases/server/custom-server/package.json
- e2e/cases/server/custom-server/scripts/index.mjs
- e2e/cases/server/custom-server/scripts/server.mjs
- e2e/cases/server/custom-server/src/index.js
- packages/compat/webpack/src/provider.ts
- packages/core/src/createRsbuild.ts
- packages/core/src/provider/provider.ts
- packages/core/src/server/compiler-dev-middleware/index.ts
- packages/core/src/server/compiler-dev-middleware/socketServer.ts
- packages/core/src/server/devMiddlewares.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/index.ts
- packages/core/src/server/prodServer.ts
- packages/core/src/server/proxy.ts
- packages/shared/src/types/provider.ts
- packages/shared/src/types/rsbuild.ts
- packages/shared/src/types/server.ts
- pnpm-lock.yaml
rsbuild supports start with other server frameworks, like [express](https://expressjs.com/) (This API is not stable)
example: /e2e/cases/server/custom-server/scripts/server.mjs
> feat(server): support use other server frameworks, like express

- packages/document/docs/en/api/javascript-api/instance.mdx
- packages/document/docs/zh/api/javascript-api/instance.mdx
Fix getPortSilently typo in document.
> docs: fix getPortSilently typo

- .changeset/early-panthers-reflect.md
- e2e/cases/cli/reload-env/index.test.ts
- packages/core/src/loadEnv.ts
Clear the assigned env vars for reloading, dotenv will not override process.env by default.
> fix: clear the assigned env vars for reloading

- .changeset/eleven-cats-study.md
- e2e/cases/source-build/app/rsbuild.config.ts
- e2e/cases/source-build/app/src/index.tsx
- e2e/cases/source-build/components/src/card/index.tsx
- e2e/cases/source-build/index.test.ts
- packages/document/docs/en/plugins/list/plugin-type-check.mdx
- packages/document/docs/zh/plugins/list/plugin-type-check.mdx
- packages/plugin-type-check/src/index.ts
- packages/plugin-type-check/tests/__snapshots__/index.test.ts.snap
- packages/shared/package.json
Add support for typescript project reference.
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin
> feat(type-check): support for typescript project reference

- e2e/scripts/shared.ts
- packages/compat/uni-builder/src/webpack/index.ts
- packages/compat/webpack/src/core/build.ts
- packages/compat/webpack/src/core/createCompiler.ts
- packages/compat/webpack/src/provider.ts
- packages/core/src/cli/commands.ts
- packages/core/src/cli/config.ts
- packages/core/src/createRsbuild.ts
- packages/core/src/provider/provider.ts
- packages/shared/src/types/config/index.ts
- packages/shared/src/types/provider.ts
- packages/test-helper/src/rsbuild.ts
Simplify provider params, no need to passing `rsbuildConfig` to the provider function any more.
>  refactor: simplify provider params

- packages/plugin-image-compress/tests/index.test.ts
- packages/plugin-node-polyfill/package.json
- packages/plugin-node-polyfill/tests/__snapshots__/index.test.ts.snap
- packages/plugin-node-polyfill/tests/index.test.ts
- packages/plugin-solid/package.json
- packages/plugin-solid/tests/index.test.ts
- packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
- packages/plugin-stylus/tests/index.test.ts
- packages/plugin-vue-jsx/package.json
- packages/plugin-vue-jsx/tests/index.test.ts
- packages/plugin-vue2-jsx/package.json
- packages/plugin-vue2-jsx/tests/index.test.ts
- pnpm-lock.yaml
Remove webpack provider in plugin tests because we do not need it.
> test(ut): remove webpack provider in plugin tests

- packages/document/docs/en/plugins/list/plugin-solid.mdx
- packages/document/docs/zh/plugins/list/plugin-solid.mdx
- packages/plugin-solid/src/types.ts
delegateEvents should be an optional property in the plugin-solid.
> fix(plugin-solid): delegateEvents should be optional

- e2e/cases/javascript-api/plugin-hooks/index.test.ts
- e2e/cases/server/custom-server/index.test.ts
- e2e/cases/server/custom-server/package.json
- e2e/cases/server/custom-server/scripts/index.mjs
- e2e/cases/server/custom-server/scripts/pure-server.mjs
- packages/core/src/server/compilerDevMiddleware.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/getDevMiddlewares.ts
- packages/core/src/server/socketServer.ts
- packages/shared/src/types/server.ts
before: 
```ts
// startCompile when calling serverAPIs.getMiddlewares(
const { middlewares, close, onUpgrade } = await serverAPIs.getMiddlewares();
```
after:
```ts
const compileMiddlewareAPI = await serverAPIs.startCompile();
const { middlewares, close, onUpgrade } = await serverAPIs.getMiddlewares({
compileMiddlewareAPI,
});
```
> refactor(server): decouple startCompiler from getMiddlewares

- .npmrc
Remove registry in npmrc as the npm registry is blocked in some regions of China.
(And pnpm do not write registry to lock file)
> chore(workflow): remove registry in npmrc

- e2e/cases/html/title/index.test.ts
- e2e/cases/html/title/src/plugin-options-title.html
- packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
- packages/core/src/plugins/html.ts
- packages/core/src/rspack/HtmlBasicPlugin.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/plugins/__snapshots__/html.test.ts.snap
- packages/core/tests/plugins/__snapshots__/inlineChunk.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Allow to read htmlWebpackPlugin.options.title in template.
Compatible with the html-webpack-plugin official usage:
https://github.com/jantimon/html-webpack-plugin
> feat: allow to read htmlWebpackPlugin.options.title in template

- e2e/cases/css/style-loader/index.test.ts
- e2e/scripts/helper.ts
- packages/test-helper/src/index.ts
Fix globContentJSON failed in Windows, use `convertPathToPattern` to format the glob pattern.
https://github.com/mrmlnc/fast-glob#convertpathtopatternpath
> test(e2e): fix globContentJSON failed in Windows

- packages/core/src/rspack/HtmlAppIconPlugin.ts
Should generate correct app icon URL in Windows, use `posix.join` instead of `join`.
https://github.com/web-infra-dev/rsbuild/issues/275
> fix: should generate correct app icon URL in Windows

- packages/plugin-vue/src/splitChunks.ts
- packages/plugin-vue2/src/splitChunks.ts
Fix SplitChunks typing error, should exclude the `false` type manually.
> types(plugin-vue): fix SplitChunks typing error

- packages/shared/src/config.ts
It may be need to refactor the implementation of `outputInspectConfigFiles`.
> fix: failed to inspect rsbuild config

- packages/document/docs/en/config/source/entry.mdx
- packages/document/docs/zh/config/source/entry.mdx
Make default entry config clearer. This current default value is kind of confusing.
> docs: make default entry config clearer

- packages/core/src/plugins/startUrl.ts
applescript may fail in some cases, such as:
1. unknown reason:
2. no permission:
Rsbuild will fallback to node.js `open` package if applescript failed.
> fix(startUrl): fallback to node.js open if applescript failed

- .changeset/thin-cobras-cheat.md
- packages/core/src/cli/prepare.ts
- packages/shared/src/logger.ts
Print debug logs when set DEBUG env:
> feat: print debug logs when set DEBUG env

- packages/plugin-rem/src/index.ts
postcss-pxtorem import error in some cases:
> fix(plugin-rem): complete postcss-pxtorem import path

- packages/plugin-react/package.json
- packages/plugin-react/src/utils.ts
- packages/shared/package.json
- pnpm-lock.yaml
Use prebundled semver, so `@rsbuild/plugin-react` do not need to depend on `semver`.
> perf(plugin-react): use prebundled semver

- e2e/scripts/shared.ts
Adjust port range to avoid permission denied error in Windows:
https://github.com/web-infra-dev/rsbuild/actions/runs/7249576923/job/19747831590
> test(e2e): adjust port range to avoid permission denied

- .changeset/strong-pianos-cheer.md
- e2e/cases/html/title/index.test.ts
- packages/core/src/plugins/html.ts
- packages/core/src/rspack/HtmlBasicPlugin.ts
Allow setting empty title to override the default title of html-webpack-plugin ('Webpack App').
> fix: allow setting empty title to override default title

- packages/shared/src/port.ts
- packages/shared/src/server.ts
The original way of passing parameters was not easily extensible. Now, they are merged into one object for passing.
#1000
> fix: get available port for a specified host

- e2e/cases/html/inject/index.test.ts
- packages/core/src/plugins/html.ts
- packages/core/tests/plugins/__snapshots__/html.test.ts.snap
- packages/core/tests/plugins/html.test.ts
- packages/shared/src/mergeChainedOptions.ts
- packages/shared/src/utils.ts
- packages/shared/tests/mergeChainedOptions.test.ts
when `html.inject` is `false`, rsbuild must not automatically inject <script> of chunks into html.
fixes #987
> fix(plugin-html): `inject: false` should behave as expected

- e2e/cases/javascript-api/plugin-hooks/index.test.ts
- packages/core/src/server/devServer.ts
- packages/shared/src/types/server.ts
onBeforeStartDevServer should called before listen and after compile, so inspect config  can works.
> fix: inspect config not works in dev

- packages/core/src/provider/plugins/minimize.ts
Rspack has deprecated some JS minimizer options, this PR updates them.
> chore: update deprecated minimizer options

- pnpm-lock.yaml
Fix browserify-sign security issue.
https://github.com/web-infra-dev/rsbuild/security/dependabot/4
> chore: fix browserify-sign security issue

- e2e/cases/legal-comments/index.test.ts
- packages/compat/plugin-swc/src/minimizer.ts
- packages/compat/plugin-swc/src/types.ts
- packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
- packages/compat/plugin-swc/tsconfig.json
- packages/compat/webpack/src/plugins/minimize.ts
- packages/core/src/provider/plugins/minimize.ts
- packages/shared/src/config.ts
- packages/shared/src/minimize.ts
Fix output.charset not work when using `@rsbuild/webpack` and `@rsbuild/plugin-swc`.
> fix(plugin-swc): output.charset not work

- packages/core/src/cli/config.ts
Improve defineConfig overload, provide precise error location.
before:
after:
> types: improve defineConfig overload

- .vscode/settings.json
- packages/document/docs/en/config/server/https.mdx
- packages/document/docs/zh/config/server/https.mdx
- packages/shared/src/types/config/server.ts
The server.https typing should supports all server options of `https.createServer`.
> types: server.https supports all server options

- packages/core/package.json
- packages/plugin-react/package.json
- packages/shared/package.json
- packages/test-helper/package.json
- pnpm-lock.yaml
bump rspack to 0.4.4
https://github.com/web-infra-dev/rspack/releases/tag/v0.4.4
> chore: bump rspack to 0.4.4

- packages/plugin-react/src/index.ts
- packages/plugin-rem/src/types.ts
- packages/plugin-vue/src/index.ts
- packages/plugin-vue2-jsx/src/index.ts
Added jsdoc comments for some plugins options: https://github.com/web-infra-dev/rsbuild/issues/181
covering `plugin-react`, `plugin-vue`, `plugin-rem`, `plugin-vue2-jsx`
> doc(plugins): added jsdoc comments for some plugins options

- packages/document/docs/en/guide/basic/cli.mdx
- packages/document/docs/en/guide/basic/page-route.md
- packages/document/docs/zh/guide/basic/cli.mdx
- packages/document/docs/zh/guide/basic/page-route.md
- Add rsbuild -h command.
- Fix title indent in the CLI document.
> docs(CLI): add rsbuild -h and fix title indent

- packages/create-rsbuild/template-vue2-ts/tsconfig.json
- packages/create-rsbuild/template-vue3-ts/tsconfig.json
Configure jsxImportSource: vue in the tsconfig.json by default:
See https://vuejs.org/guide/extras/render-function.html#jsx-type-inference for more informantion.
> feat(create-rsbuild): configure jsxImportSource vue by default

- packages/core/src/loadEnv.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/restart.ts
Only clear env vars when restart server, this change allows us to call `loadEnv` multiple times.
> fix: only clear env vars when restart server

- packages/core/src/cli/commands.ts
- packages/core/src/loadEnv.ts
- packages/document/docs/en/api/javascript-api/core.mdx
- packages/document/docs/zh/api/javascript-api/core.mdx
Make loadEnv a sync method. So users can call `loadEnv` in the `rsbuild.config.ts` file if needed.
> feat: make loadEnv a sync method

- packages/document/docs/en/guide/migration/cra.mdx
- packages/document/docs/en/guide/migration/vue-cli.mdx
- packages/document/docs/zh/guide/migration/cra.mdx
- packages/document/docs/zh/guide/migration/vue-cli.mdx
Add loadEnv to migration guides.
https://github.com/web-infra-dev/rsbuild/issues/1037
> docs: add loadEnv to migration guides

- packages/document/docs/en/guide/migration/_meta.json
- packages/document/docs/en/guide/migration/cra.mdx
- packages/document/docs/en/guide/migration/vue-cli.mdx
- packages/document/docs/en/guide/migration/webpack.mdx
- packages/document/docs/en/guide/start/quick-start.mdx
- packages/document/docs/zh/guide/migration/_meta.json
- packages/document/docs/zh/guide/migration/webpack.mdx
- packages/document/docs/zh/guide/start/quick-start.mdx
Add migration guide for webpack projects.
https://github.com/web-infra-dev/rsbuild/issues/779
> docs: add migration guide for webpack projects

- packages/compat/webpack/package.json
- packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
- packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
- packages/core/package.json
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/plugins/__snapshots__/html.test.ts.snap
- packages/core/tests/plugins/__snapshots__/inlineChunk.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/plugin-assets-retry/package.json
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/plugin-rem/package.json
- packages/shared/package.json
- pnpm-lock.yaml
This reverts commit 9030c719142d511bfe200d359576833576a61c73.
Fix the Windows path issue.
```text
start   Compiling...
error   Compile error: 
Failed to compile, check the errors for troubleshooting.
SyntaxError
× [html-rspack-plugin]: Invalid Unicode escape sequence
│ C:\userCode\23-2-2\vue-app6\node_modules\@rsbuild\core\static\template.html:74
│ var installedChunks = {"HtmlWebpackPlugin_0-C:\userCode\23-2-2\vue-app6\node_modules\html-webpack-plugin\lib\loader.js!C:\userCode\23-2-2\vue-
│ app6\node_modules\@rsbuild\core\static\template.html": 0,};
│                                               ^^^^^^
```
> Revert "chore(deps): bump html-rspack-plugin v5.6.0 (#1039)"

- packages/document/docs/en/config/server/history-api-fallback.mdx
- packages/document/docs/en/guide/basic/_meta.json
- packages/document/docs/en/guide/basic/server.md
- packages/document/docs/zh/config/server/history-api-fallback.mdx
- packages/document/docs/zh/guide/basic/_meta.json
- packages/document/docs/zh/guide/basic/server.md
Comparing Rspack dev server.
https://github.com/web-infra-dev/rsbuild/issues/1031
> docs: comparing Rspack dev server

- packages/document/docs/en/config/plugins.mdx
- packages/document/docs/zh/config/plugins.mdx
Add register Rspack plugins guide to the `plugins` page.
> docs: add register Rspack plugins guide

- packages/plugin-vue/package.json
- pnpm-lock.yaml
Bump vue-loader v17.4 to reuse AST.
https://github.com/vuejs/vue-loader/blob/main/CHANGELOG.md#1740-2023-12-25
> perf(plugin-vue): bump vue-loader v17.4 to reuse AST

- packages/plugin-svelte/src/index.ts
- packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Fix missing default mainFields when using `@rsbuild/plugin-svelte`.
https://github.com/sailscastshq/boring-stack/pull/74
> fix(plugin-svelte): missing default mainFields

- packages/compat/plugin-swc/src/plugin.ts
Use standard plugin name for plugin-swc.
https://rsbuild.dev/plugins/dev/index#naming-convention
> chore(plugin-swc): use standard plugin name

- e2e/cases/svg/svgo.test.ts
- packages/plugin-svgr/modern.config.ts
- packages/plugin-svgr/package.json
- packages/plugin-svgr/src/index.ts
- packages/plugin-svgr/src/loader.ts
- packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
- pnpm-lock.yaml
Implement `svgr-loader` to replace `@svgr/webpack`:
1. Better performance, `@svgr/webpack` depends on babel for transformation, and Rsbuild can reuse the builtin swc-loader to replace babel.
2. Less dependencies, no need to depend on `@babel/preset-env` and more.
> perf(plugin-svgr): reuse SWC loader to improve perf

- packages/core/package.json
- packages/core/src/provider/core/devMiddleware.ts
- packages/core/src/provider/plugins/transition.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/plugins/__snapshots__/define.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/plugin-react/package.json
- packages/plugin-react/src/react.ts
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
- packages/shared/package.json
- packages/test-helper/package.json
- pnpm-lock.yaml
Bump Rspack v0.4.5, update lazy entry.
- https://github.com/web-infra-dev/rspack/releases/tag/v0.4.5
- https://www.rspack.dev/config/experiments.html#experimentsrspackfuturedisableapplyentrylazily
> feat: bump Rspack v0.4.5, update lazy entry

- packages/core/src/client/hmr/index.ts
https://github.com/web-infra-dev/modern.js/pull/5152
> fix: reload when the updated modules is empty

- e2e/cases/server/dev.test.ts
Reduce HMR cases time, avoid using long `setTimeout`.
`pnpm run e2e:rspack server/dev`
before:
after:
> test(e2e): reduce HMR cases time

- packages/document/docs/en/plugins/list/plugin-vue-jsx.mdx
- packages/document/docs/zh/plugins/list/plugin-vue-jsx.mdx
Add Vue JSX type inference guide
https://vuejs.org/guide/extras/render-function.html#jsx-type-inference
> docs: add Vue JSX type inference guide

- e2e/cases/source/entry-description-object/index.test.ts
- e2e/cases/source/entry-description-object/rsbuild.config.ts
- e2e/cases/source/entry-description-object/src/bar.js
- e2e/cases/source/entry-description-object/src/baz.js
- e2e/cases/source/entry-description-object/src/foo.js
- packages/core/src/plugins/entry.ts
- packages/core/src/plugins/html.ts
- packages/document/docs/en/api/javascript-api/core.mdx
- packages/document/docs/en/api/javascript-api/instance.mdx
- packages/document/docs/en/config/source/entry.mdx
- packages/document/docs/zh/api/javascript-api/core.mdx
- packages/document/docs/zh/api/javascript-api/instance.mdx
- packages/document/docs/zh/config/source/entry.mdx
- packages/shared/src/types/rsbuild.ts
`source.entry` supports the use of entry description object.
https://www.rspack.dev/config/entry.html#entry-description-object
> feat: support use entry description object

- packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
Remove outdated comment from preload plugin, the feature has been supported by Rspack.
- https://github.com/web-infra-dev/rsbuild/pull/747
- https://github.com/web-infra-dev/rspack/issues/3896
> chore: remove outdated comment from preload plugin

- packages/core/src/client/hmr/index.ts
Remove unused `hadRuntimeError` variable from hmr client (the value is always `false`).
For React apps, react refresh can handle hot-reloading over errors, see [this comment](https://github.com/charrondev/create-react-app/blob/572d14c19cc9626656450de6ec545d90e460142e/packages/react-dev-utils/webpackHotDevClient.js#L248).
> chore(hmr-client): remove unused variable

- .changeset/new-vans-think.md
- packages/shared/src/css.ts
Handle css-loader mode option correctly, CSS Modules will be disabled if mode is `global`.
https://github.com/webpack-contrib/css-loader?tab=readme-ov-file#mode
> fix: handle css-loader mode option correctly

- packages/compat/webpack/src/core/createCompiler.ts
- packages/compat/webpack/src/core/initConfigs.ts
- packages/compat/webpack/src/core/webpackConfig.ts
- packages/compat/webpack/src/plugins/css.ts
- packages/core/src/index.ts
- packages/core/src/plugins/cache.ts
- packages/core/src/provider/core/createCompiler.ts
- packages/core/src/provider/core/createContext.ts
- packages/core/src/provider/core/initConfigs.ts
- packages/core/src/provider/core/initPlugins.ts
- packages/core/src/provider/core/rspackConfig.ts
- packages/core/src/provider/index.ts
- packages/core/src/provider/plugins/css.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/prodServer.ts
- packages/core/src/types.ts
- packages/shared/src/chain.ts
- packages/shared/src/types/context.ts
- packages/shared/src/types/plugin.ts
- packages/shared/src/types/provider.ts
- packages/shared/src/types/rsbuild.ts
There are two Context types in Rsbuild, the internal context for Rsbuild core, and the public context for Rsbuild plugins.
This PR renames them to distinguish between the two context types.
> chore: rename to differentiate between two context types

- packages/core/src/cli/commands.ts
- packages/document/docs/en/guide/basic/cli.mdx
- packages/document/docs/zh/guide/basic/cli.mdx
Support open specific URL:
```bash
rsbuild dev --open http://localhost:8080/foo
```
> feat(CLI): support open specific URL

- packages/plugin-source-build/src/index.ts
source build plugin depends on js/ts rule, so it should be after babel/ts-loader/swc plugin.
> fix(plugin-source-build): should after babel/ts-loader/swc

- e2e/cases/performance/bundle-analyzer/index.test.ts
- e2e/cases/performance/bundle-analyzer/rsbuild.config.ts
- e2e/cases/performance/bundle-analyzer/src/App.jsx
- e2e/cases/performance/bundle-analyzer/src/index.js
- e2e/cases/performance/performance.test.ts
- packages/core/src/plugins/bundleAnalyzer.ts
- packages/document/docs/en/config/performance/bundle-analyze.mdx
- packages/document/docs/zh/config/performance/bundle-analyze.mdx
Fix bundle analyzer failed to read assets during dev:
> fix: bundle analyzer failed to read assets during dev

- packages/core/src/rspack/HtmlAppIconPlugin.ts
- packages/core/src/rspack/InlineChunkHtmlPlugin.ts
- packages/core/src/rspack/RemoveCssSourcemapPlugin.ts
- packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
- packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
- packages/shared/src/utils.ts
Get compilation stage constant from compiler, we should not maintain `COMPILATION_PROCESS_STAGE` in the Rsbuild codebase.
> chore: get compilation stage constant from compiler

- cspell.json
- packages/document/docs/en/guide/basic/static-assets.md
- packages/document/docs/zh/guide/basic/static-assets.md
Update extend asset types example, use `tools.rspack` instead of `tools.bundlerChain`, as it is easier to use.
> docs: update extend asset types example

- packages/document/docs/en/config/tools/bundler-chain.mdx
- packages/document/docs/en/config/tools/rspack.mdx
- packages/document/docs/zh/config/tools/bundler-chain.mdx
- packages/document/docs/zh/config/tools/rspack.mdx
Improve bundler chain document, fix typography.
> docs: improve bundler chain document

- e2e/cases/server/print-urls/index.test.ts
- e2e/cases/server/print-urls/src/index.js
- e2e/scripts/helper.ts
- e2e/scripts/shared.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/prodServer.ts
- packages/shared/src/config.ts
- packages/shared/src/types/config/server.ts
Add new `server.printUrls` config.
- support function usage.
- deprecate `printURLs` option in Node API
- add document.
https://github.com/web-infra-dev/rsbuild/issues/1121
> feat: add new server.printUrls config

- packages/plugin-vue2/src/index.ts
- packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap
Alias Vue to support element-ui, resolve https://github.com/web-infra-dev/rsbuild/issues/1132
- https://github.com/ElemeFE/element/issues/21968
- https://github.com/vitejs/vite-plugin-vue2/blob/main/src/index.ts#L103-L109
> fix(plugin-vue2): alias Vue to support element-ui

- packages/document/docs/en/guide/framework/react.mdx
- packages/document/docs/en/guide/framework/vue2.mdx
- packages/document/docs/en/guide/framework/vue3.mdx
- packages/document/docs/zh/guide/framework/react.mdx
- packages/document/docs/zh/guide/framework/vue2.mdx
- packages/document/docs/zh/guide/framework/vue3.mdx
Add migration guide links to framework documents.
> docs: add migration guide links

- e2e/cases/server/print-urls/index.test.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/helper.ts
- packages/core/src/server/prodServer.ts
- packages/core/tests/server.test.ts
- packages/document/docs/en/config/server/print-urls.mdx
- packages/document/docs/zh/config/server/print-urls.mdx
- packages/shared/src/mergeRsbuildConfig.ts
- packages/shared/src/types/config/server.ts
Support custom print urls via `server.printUrls`.
https://github.com/web-infra-dev/rsbuild/issues/1121
> feat: support custom print urls

- packages/compat/webpack/src/core/webpackConfig.ts
- packages/core/src/plugins/entry.ts
- packages/core/src/provider/core/rspackConfig.ts
- packages/shared/src/chain.ts
Fix failed to prepend entry via chain API.
webpack-chain can not handle entry description object correctly, so we need to format the entry object and correct the entry description object.
> fix: failed to prepend entry via chain API

- packages/document/docs/en/api/javascript-api/instance.mdx
- packages/document/docs/zh/api/javascript-api/instance.mdx
- packages/shared/src/types/provider.ts
Deprecate legacy printURLs option.
https://github.com/web-infra-dev/rsbuild/issues/1121
> chore: deprecate legacy printURLs option

- .changeset/spicy-avocados-play.md
- packages/document/docs/en/api/javascript-api/instance.mdx
- packages/document/docs/zh/api/javascript-api/instance.mdx
- packages/shared/src/types/provider.ts
Deprecate logger option of startDevServer, use `logger.override()` instead. 
see: https://github.com/web-infra-dev/rsbuild/pull/1146
> chore: deprecate logger option of startDevServer

- e2e/cases/server/dev.test.ts
- e2e/package.json
- pnpm-lock.yaml
Remove unused devcert dependency and test case, as `server.https` now only supports object param.
> test(e2e): remove unused devcert

- packages/shared/src/url.ts
Print local label for more hosts.
before:
after:
> fix(server): print local label for more hosts

- packages/shared/src/chain.ts
inner html plugin chain_id  conflict with user's, when user's entryName is basic/tag/...
> fix: html plugin chain_id conflict

- packages/core/src/cli/commands.ts
Check output dir when running the preview command:
> feat: check output dir when running the preview command

- packages/plugin-image-compress/src/index.ts
- packages/plugin-image-compress/src/minimizer.ts
- packages/plugin-image-compress/tests/__snapshots__/index.test.ts.snap
- packages/plugin-image-compress/tests/index.test.ts
Rename some internal vars of `plugin-image-compress`, remove the Modern.js related prefixes, as Rsbuild now is not part of Modern.js.
> chore(plugin-image-compress): rename some internal vars

- .changeset/famous-penguins-tan.md
- packages/babel-preset/src/web.ts
in [@rsbuild/babel-preset base](https://github.com/web-infra-dev/rsbuild/blob/7a5eb25fff1bfdc449f2e27487882f1ae6f66b72/packages/babel-preset/src/base.ts#L17), it seems we can pass in null value.
```typescript
if (presetEnv) {
// some code
}
```
but actually not, if we use the web preset.
> fix(babel): presetEnv need allow null value

- packages/babel-preset/src/types.ts
- packages/babel-preset/src/web.ts
- packages/babel-preset/tests/__snapshots__/web.test.ts.snap
- packages/babel-preset/tests/web.test.ts
Allow disable presetEnv for web target.
> fix(babel-preset): allow disable presetEnv for web target

- packages/plugin-babel/src/index.ts
export getDefaultBabelOptions util from index for Modern.js.
> fix(plugin-babel): export getDefaultBabelOptions util from index

- .changeset/old-bags-visit.md
- packages/babel-preset/src/node.ts
- packages/babel-preset/tests/__snapshots__/node.test.ts.snap
- packages/babel-preset/tests/node.test.ts
Should merge targets array correctly.
`deepmerge` will merge `['node >= 14']` and `['node >= 16']` into `['node >= 14', 'node >= 16']`, which is not as expected. So we need to add some conditions.
> fix(babel-preset): should merge targets array correctly

- packages/document/docs/en/guide/framework/vue2.mdx
- packages/document/docs/en/plugins/list/plugin-vue2.mdx
- packages/document/docs/zh/guide/framework/vue2.mdx
- packages/document/docs/zh/plugins/list/plugin-vue2.mdx
Add Vue 2 version requirements.
Rspack + vue-loader@15.11.1 only works with Vue >= 2.7.0.
- https://github.com/vuejs/vue-loader/blob/v15.11.1/lib/plugin-webpack5.js#L203
- https://github.com/vuejs/vue-loader/blob/v15.11.1/lib/loaders/pitcher.js#L204
> docs: add Vue 2 version requirements

- packages/plugin-svelte/package.json
- packages/plugin-svelte/src/index.ts
- packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
- packages/plugin-svelte/tests/index.test.ts
- pnpm-lock.yaml
1. support pass preprocess options
2. add frequently used loader typings
> feat(plugin-svelte): support pass preprocess options

- .npmrc
- e2e/cases/react/legacy-jsx/index.test.ts
- e2e/cases/react/legacy-jsx/rsbuild.config.ts
- e2e/cases/react/legacy-jsx/src/App.jsx
- e2e/cases/react/legacy-jsx/src/index.js
- packages/document/docs/en/plugins/list/plugin-react.mdx
- packages/document/docs/zh/plugins/list/plugin-react.mdx
- packages/plugin-react/src/index.ts
- packages/plugin-react/src/react.ts
- pnpm-lock.yaml
Add new `jsxRuntime` option to support React 16.
- https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
- https://babeljs.io/docs/babel-preset-react#react-classic-runtime
> feat(plugin-react): add jsxRuntime option to support React 16

- packages/document/docs/en/plugins/list/plugin-react.mdx
- packages/document/docs/zh/plugins/list/plugin-react.mdx
- packages/plugin-react/src/index.ts
- packages/plugin-react/src/react.ts
- packages/plugin-react/tests/index.test.ts
Add new jsxImportSource option for Emotion.
- https://emotion.sh/docs/css-prop
- https://swc.rs/docs/configuration/compilation#jsctransformreactimportsource
> feat(plugin-react): add jsxImportSource option

- package.json
- pnpm-lock.yaml
Bump pnpm from v8.9.0 to v8.14.0.
https://github.com/pnpm/pnpm/releases
> chore(deps): bump pnpm from v8.9.0 to v8.14.0

- e2e/cases/node-addons/index.test.ts
- packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/document/docs/en/config/output/dist-path.mdx
- packages/document/docs/en/guide/basic/config.mdx
- packages/document/docs/en/guide/basic/output-files.md
- packages/document/docs/zh/config/output/dist-path.mdx
- packages/document/docs/zh/guide/basic/config.mdx
- packages/document/docs/zh/guide/basic/output-files.md
- packages/shared/src/constants.ts
- packages/shared/src/types/config/output.ts
The default value of `output.distPath.server` is changed to from 'bundles' to  'server'.
https://github.com/web-infra-dev/rsbuild/discussions/1101
> breaking change: default value of distPath.server is changed to 'server'

- packages/core/src/server/devServer.ts
- packages/core/src/server/prodServer.ts
- packages/shared/src/types/provider.ts
Remove deprecated printURLs option of `rsbuild.startDevServer`.
The `printURLs` option of `rsbuild.startDevServer` is deprecated, use [server.printUrls](https://rsbuild.dev/config/server/print-urls) instead.
https://github.com/web-infra-dev/rsbuild/discussions/1101
> breaking change: remove deprecated printURLs option

- packages/core/src/server/devServer.ts
- packages/core/src/server/helper.ts
- packages/core/tests/server.test.ts
- packages/shared/src/types/provider.ts
Remove deprecated logger option of `rsbuild.createServer`.
The `logger` option of `rsbuild.startDevServer` is deprecated, use [logger.override()](https://rsbuild.dev/api/javascript-api/core#logger) instead.
https://github.com/web-infra-dev/rsbuild/discussions/1101
> breaking change: remove deprecated logger option

- packages/core/src/provider/plugins/transition.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
This reverts commit f4fd4f8c4eb6f551f004d6dc6edcdc81b05a3f95.
https://github.com/web-infra-dev/rspack/issues/5270
> Revert "feat: enable Rspack new tree shaking by default (#1077)"

- packages/core/src/provider/plugins/transition.ts
- packages/core/src/provider/shared.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Remove some unused configs for Rspack 0.5:
- disableApplyEntryLazily is enabled by default, see https://github.com/web-infra-dev/rspack/pull/5179
- chunkIds defaults to `deterministic` in production, see https://github.com/web-infra-dev/rspack/pull/4822
> chore: remove unused config for Rspack 0.5

- .changeset/real-kings-protect.md
- packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
- packages/core/src/plugins/asset.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/plugins/__snapshots__/asset.test.ts.snap
- packages/core/tests/plugins/asset.test.ts
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/plugin-image-compress/tests/__snapshots__/index.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Use non-capturing groups for asset rules to improve performance.
The same as: https://github.com/web-infra-dev/rsbuild/pull/1091
> perf(RegExp): use non-capturing groups for asset rules

- packages/compat/webpack/src/provider.ts
- packages/core/src/provider/provider.ts
- packages/shared/src/types/provider.ts
Allow to narrow Compiler type for createCompiler.
```ts
import type { Compiler } from '@rspack/core';
const compiler = rsbuild.createCompiler<Compiler>();
```
> types: allow to narrow Compiler type for createCompiler

- e2e/scripts/shared.ts
remove unnecessary intermediate variable
> chore(e2e): remove unnecessary intermediate variable

- packages/document/docs/en/plugins/list/plugin-source-build.mdx
- packages/document/docs/zh/plugins/list/plugin-source-build.mdx
- packages/plugin-source-build/package.json
- packages/plugin-source-build/src/index.ts
- packages/plugin-source-build/tests/__snapshots__/index.test.ts.snap
- packages/plugin-source-build/tests/index.test.ts
- pnpm-lock.yaml
Add resolvePriority option, it is used to control the priority of reading the source code or the output code.
By default, Source Build plugin will reading the source code first, for example, in the following example, it will read the `source` field.
```json title="package.json"
{
"name": "lib",
"main": "./dist/index.js",
"source": "./src/index.ts"
}
```
When `resolvePriority` is set to `'output'`, Source Build plugin will read the output code first, i.e., the code from the `main` or `module` field.
```ts
pluginSourceBuild({
resolvePriority: 'output',
});
```
> feat(plugin-source-build): add resolvePriority option

- .changeset/big-bugs-think.md
- packages/create-rsbuild/template-vue3-js/.vscode/extensions.json
- packages/create-rsbuild/template-vue3-ts/.vscode/extensions.json
- packages/create-rsbuild/template-vue3-ts/src/env.d.ts
Add extensions config for Vue projects, be consistent with the official Vue template.
- https://vuejs.org/guide/typescript/overview.html#using-vue-with-typescript
- https://github.com/vuejs/create-vue/blob/333ec677088bfacd33bb10a85059ccba45dea37a/template/base/.vscode/extensions.json#L2
> feat(create-rsbuild): add extensions config for Vue projects

- packages/plugin-svgr/package.json
- pnpm-lock.yaml
Fix missing file-loader peer dependency, url-loader will use `file-loader` when svg size exceeds limit.
close https://github.com/web-infra-dev/rsbuild/issues/1238
> fix(plugin-svgr): missing file-loader peer dependency

- e2e/cases/server/print-urls/index.test.ts
- packages/core/src/server/helper.ts
- packages/document/docs/en/config/server/print-urls.mdx
- packages/document/docs/zh/config/server/print-urls.mdx
- packages/shared/src/types/config/server.ts
- packages/shared/src/url.ts
If the `printUrls` function returns a set of new URLs, Rsbuild will output these URLs in the default format to the terminal:
```ts title="rsbuild.config.ts"
server: {
printUrls({ urls }) {
return urls.map((url) => `${url}/base`);
},
},
};
```
Output:
```text
> Local:    http://localhost:8080/base/
> Network:  http://192.168.0.1:8080/base/
```
> feat: support return modified urls with printUrls

- packages/document/docs/en/guide/framework/vue3.mdx
- packages/document/docs/zh/guide/framework/vue3.mdx
Update outdated typescript support, the `declare module '*.vue'` is no longer needed. It is recommended to use the VS Code extension instead.
https://vuejs.org/guide/typescript/overview.html#ide-support
> docs(vue3): update outdated typescript support

- packages/document/docs/en/plugins/list/plugin-preact.mdx
- packages/document/docs/zh/plugins/list/plugin-preact.mdx
- packages/plugin-preact/src/index.ts
- packages/plugin-preact/tests/__snapshots__/features.test.ts.snap
- packages/plugin-preact/tests/index.test.ts
Add reactAliasesEnabled option, use the same API as the official preset.
> feat(plugin-preact): add reactAliasesEnabled option

- packages/create-rsbuild/template-lit-ts/tsconfig.json
- packages/create-rsbuild/template-preact-ts/tsconfig.json
- packages/create-rsbuild/template-react-ts/tsconfig.json
- packages/create-rsbuild/template-solid-ts/tsconfig.json
- packages/create-rsbuild/template-svelte-ts/tsconfig.json
- packages/create-rsbuild/template-vanilla-ts/tsconfig.json
- packages/create-rsbuild/template-vue2-ts/tsconfig.json
- packages/create-rsbuild/template-vue3-ts/tsconfig.json
- scripts/tsconfig/base.json
Enable useDefineForClassFields by default in the template's tsconfig.json.
Rsbuild uses SWC to transform the code, and SWC enables `useDefineForClassFields` by default, see https://github.com/swc-project/swc/pull/7055
So it is best for Rsbuild to set it in tsconfig.json by default to keep it consistent with the compilation behavior.
> feat(create-rsbuild): enable useDefineForClassFields by default

- packages/plugin-preact/src/index.ts
- packages/plugin-react/src/react.ts
- packages/plugin-styled-components/src/index.ts
- packages/shared/src/chain.ts
Use internal helper to modify swc loader options.
Maybe we should provide an API for plugins to modify the options of other plugins.
> chore: use helper to modify swc loader options

- package.json
- scripts/check-changeset/package.json
- scripts/update-packages/package.json
The `@scripts/test-helper` package should be built by default, otherwise the release CI will be broken.
https://github.com/web-infra-dev/rsbuild/actions/runs/7490120274/job/20388235225
> chore(workflow): should build script packages for testing

- scripts/check-changeset/package.json
- scripts/test-helper/package.json
- scripts/tsconfig/package.json
- scripts/update-packages/package.json
Fix pnpm publish failed to resolve `@scripts/test-helper`, the private package should also provides a version field.
see: https://github.com/pnpm/pnpm/issues/5094
> chore(workflow): fix pnpm publish failed to resolve

- packages/plugin-svgr/package.json
- packages/plugin-svgr/src/index.ts
- packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
- packages/plugin-svgr/tests/index.test.ts
- pnpm-lock.yaml
Fix plugin-svgr failed to reuse SWC react options, the `plugin-react` should run before `plugin-svgr`.
https://github.com/web-infra-dev/modern.js/pull/5217
> fix(plugin-svgr): failed to reuse SWC react options

- e2e/cases/server/htmlFallback.test.ts
- packages/core/src/server/middlewares.ts
This is a bug about accessing page get 404 error when the request url with query or hash.
For example:  visit `http://localhost:8082/index?aa=1` should be succeed as expected, but now got error in Rsbuild.
> fix(server): access page error when url with query or hash

- packages/shared/src/logger.ts
`DEBUG=*` is a common usage to print all debug logs
> feat: support log debug logger when debug=*

- packages/compat/plugin-esbuild/src/index.ts
- packages/compat/plugin-esbuild/tsconfig.json
- packages/compat/plugin-swc/src/plugin.ts
- packages/compat/plugin-swc/tsconfig.json
- packages/core/src/constants.ts
- packages/core/src/index.ts
- packages/core/src/provider/plugins/swc.ts
- packages/plugin-babel/src/plugin.ts
- packages/plugin-preact/src/index.ts
- packages/plugin-react/src/index.ts
- packages/plugin-rem/src/index.ts
- packages/plugin-solid/src/index.ts
- packages/plugin-source-build/src/index.ts
- packages/plugin-stylus/src/index.ts
- packages/plugin-svgr/package.json
- packages/plugin-svgr/src/index.ts
- packages/plugin-svgr/tsconfig.json
- packages/plugin-vue-jsx/src/index.ts
- packages/plugin-vue2-jsx/src/index.ts
- pnpm-lock.yaml
Extract some plugin names as constants, which allows other plugins to directly import the constant when defining plugin orders instead of using a string name.
> chore: extract some plugin names as constants

- packages/core/src/index.ts
- packages/document/docs/en/api/javascript-api/types.mdx
- packages/document/docs/zh/api/javascript-api/types.mdx
Export the types of config sub key from `@rsbuild/core`.
> types(core): export the type of config sub key

- .changeset/shiny-mayflies-float.md
- packages/core/package.json
Remove cli exports from `@rsbuild/core`, it was previously added to Modern.js Builder, and never used by Rsbuild or users.
> chore: remove cli exports from core

- packages/monorepo-utils/package.json
- packages/monorepo-utils/src/common/pnpm.ts
- packages/monorepo-utils/src/utils.ts
- pnpm-lock.yaml
Remove p-map dependency from plugin-source-build, as we do not need to limit concurrency in this case.
> perf(source-build): remove p-map dependency

- packages/monorepo-utils/package.json
- packages/monorepo-utils/src/common/pnpm.ts
- packages/monorepo-utils/src/utils.ts
- packages/shared/compiled/yaml/index.d.ts
- packages/shared/package.json
- pnpm-lock.yaml
- scripts/prebundle/src/constant.ts
Reuse shared dependencies from `@rsbuild/shared`, use `yaml` instead of `js-yaml`.
> perf(source-build): reuse shared dependencies

- e2e/cases/server/custom-server/package.json
- e2e/cases/server/custom-server/scripts/pure-server.mjs
- e2e/cases/server/custom-server/scripts/server.mjs
- pnpm-lock.yaml
Use polka instead of express for e2e testing. polka is more lightweight than express, so we can install less dependencies.
> test(e2e): use polka instead of express

- package.json
- pnpm-lock.yaml
use nolyfill to speed up installation, no `es-abstract` anymore.
https://github.com/SukkaW/nolyfill
> chore: use nolyfill to speed up installation

- e2e/cases/mjs-artifact/test.mjs
- packages/core/src/plugins/nodeAddons.ts
- packages/core/tests/plugins/nodeAddons.test.ts
Should ignore node addons when targeting service worker, the node addons is only supported when targeting node environment.
> fix: should ignore node addons when targeting service worker

- packages/document/docs/en/config/server/public-dir.mdx
- packages/document/docs/zh/config/server/public-dir.mdx
- packages/shared/src/types/config/server.ts
Add path types example for publicDir config.
The value of `name` can be set to a relative path or an absolute path. Relative path will be resolved relative to the project root directory.
- Example of a relative path:
```ts
server: {
publicDir: {
name: '../some-public',
},
},
};
```
- Example of an absolute path:
```ts
import path from 'node:path';
server: {
publicDir: {
name: path.join(__dirname, '../some-public'),
},
},
};
```
> docs: add path types example for publicDir config

- .github/workflows/issue-close-require.yml
- .github/workflows/issue-labeled.yml
Add workflows to manage and auto close inactive need reproduce issue, this can help us to manage issues and helps with long-term maintenance.
Referenced from https://github.com/youzan/vant/tree/main/.github/workflows
>  chore(workflow): auto close inactive need reproduce issue

- packages/compat/webpack/package.json
- packages/core/package.json
- packages/shared/package.json
- pnpm-lock.yaml
- scripts/prebundle/package.json
Bump postcss from 8.4.31 to ^8.4.33. `postcss` is a widely used package, so I prefer not to lock the version.
https://github.com/postcss/postcss/releases
> chore(deps): bump postcss from 8.4.31 to ^8.4.33

- packages/document/docs/en/guide/faq/hmr.md
- packages/document/docs/en/guide/framework/react.mdx
- packages/document/docs/zh/guide/faq/hmr.md
- packages/document/docs/zh/guide/framework/react.mdx
Move fast refresh guide to react document, easier to find it.
> docs: move fast refresh guide to react document

- e2e/cases/javascript-api/plugin-hooks/index.test.ts
- packages/core/src/provider/core/initConfigs.ts
- packages/core/src/server/devServer.ts
print server url should between listen and beforeCompile
- after listen: server can response url request when user visit page
- beforeCompile: the compile message can be printed at the bottom of terminal
> fix(server): print server url should between listen and beforeCompile

- packages/document/docs/en/guide/migration/modern-builder.mdx
- packages/document/docs/zh/guide/migration/modern-builder.mdx
Rsbuild is not coupled with any front-end UI framework. Therefore, if a React project wants to migrate from modern.js builder to rsbuild, add React Plugin is necessary.
> docs: add react plugin introduce in the builder migration guide

- packages/babel-preset/src/base.ts
- packages/compat/webpack/src/core/build.ts
- packages/compat/webpack/src/core/inspectConfig.ts
- packages/compat/webpack/src/core/webpackConfig.ts
- packages/core/src/cli/config.ts
- packages/core/src/loadEnv.ts
- packages/core/src/plugins/define.ts
- packages/core/src/provider/core/build.ts
- packages/core/src/provider/core/inspectConfig.ts
- packages/core/src/provider/core/rspackConfig.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/prodServer.ts
- packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
- packages/shared/src/utils.ts
Use helper to get and set NODE_ENV, we should then try to minimize code that can directly write NODE_ENV.
> chore: use helper to get and set NODE_ENV

- packages/core/src/provider/plugins/transition.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Enable Rspack new tree shaking by default, which can greatly reduce the bundle size for some cases, see: 
https://github.com/web-infra-dev/rspack/issues/5317.
Also we want to get more feedbacks for it.
https://github.com/web-infra-dev/rsbuild/pull/1212
> feat: enable Rspack new tree shaking by default

- scripts/modern.base.config.ts
- scripts/requireShims.js
Part of https://github.com/web-infra-dev/rsbuild/pull/1286.
remove the non-pure shims for ESM. Since the phantom dependencies are no longer available, the test case `e2e/cases/mjs-artifact/test.mjs` would fail because `global.require` will be set concurrently and fail due to the non-availability of the phantom dependency.
> build: remove require shims

- packages/core/package.json
- packages/core/src/provider/plugins/transition.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
- packages/document/docs/en/guide/basic/json-files.md
- packages/plugin-react/package.json
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/shared/package.json
- pnpm-lock.yaml
- scripts/test-helper/package.json
- Revert Rspack to 0.5.0 to fix warning.
- Revert new shaking as Rspress HMR is still broken.
- https://github.com/web-infra-dev/rspack/issues/5270
- https://github.com/web-infra-dev/modern.js/issues/5227
> chore: revert Rspack to 0.5.0

- .github/renovate.json5
Allow pnpmfile in renovate config.
https://github.com/renovatebot/renovate/discussions/16063
> chore(workflow): allow pnpmfile in renovate config

- packages/core/src/server/helper.ts
- packages/core/tests/server.test.ts
Fix double slash in formatted routes:
> fix: double slash in formatted routes

- packages/core/src/plugins/startUrl.ts
- packages/core/src/provider/core/createCompiler.ts
- packages/shared/src/logger.ts
Improve time info in debug logs, display current time is better than `performance.now` when dev server run a long time.
> feat: improve time info in debug logs

- examples/react/rsbuild.config.ts
- packages/core/src/plugins/startUrl.ts
- packages/core/src/server/helper.ts
- packages/core/tests/server.test.ts
- packages/document/docs/en/config/server/print-urls.mdx
- packages/document/docs/zh/config/server/print-urls.mdx
- packages/shared/src/types/config/server.ts
- packages/shared/src/types/hooks.ts
Add routes param to `server.printUrls`:
```ts title="rsbuild.config.ts"
server: {
printUrls({ routes }) {
/**
* [
*   { entryName: 'index', pathname: '/' },
*   { entryName: 'detail', pathname: '/detail' }
* ]
*/
console.log(routes);
},
},
};
```
> feat: add routes param to server.printUrls

- .github/renovate.json5
- packages/core/tests/server.test.ts
- fix type issues in server test, use rspack instead of webpack.
- update renovate config, use GitHub actions to update rspress and modern, manually update rspack.
> chore: fix type issues in server test, update renovate config

- packages/core/src/client/hmr/index.ts
Fix infinitely reload when disabling HMR, we should detect is there a newer version of this code before reloading the page.
close https://github.com/web-infra-dev/rsbuild/issues/1231
> fix: infinitely reload when disabling HMR

- packages/compat/plugin-esbuild/package.json
- packages/compat/plugin-swc/package.json
- packages/plugin-assets-retry/package.json
- packages/plugin-babel/package.json
- packages/plugin-check-syntax/package.json
- packages/plugin-css-minimizer/package.json
- packages/plugin-image-compress/package.json
- packages/plugin-node-polyfill/package.json
- packages/plugin-preact/package.json
- packages/plugin-pug/package.json
- packages/plugin-react/package.json
- packages/plugin-rem/package.json
- packages/plugin-solid/package.json
- packages/plugin-source-build/package.json
- packages/plugin-styled-components/package.json
- packages/plugin-stylus/package.json
- packages/plugin-svelte/package.json
- packages/plugin-svgr/package.json
- packages/plugin-toml/package.json
- packages/plugin-type-check/package.json
- packages/plugin-umd/package.json
- packages/plugin-vue-jsx/package.json
- packages/plugin-vue/package.json
- packages/plugin-vue2-jsx/package.json
- packages/plugin-vue2/package.json
- packages/plugin-yaml/package.json
- scripts/check-changeset/src/index.ts
Fix incorrect peer dependency range. pnpm may resolve `@rsbuild/core: 0.x` to v0.1.0 and breaks some plugin.
> fix: incorrect peer dependency range

- packages/shared/src/pluginStore.ts
- packages/shared/tests/pluginDagSort.test.ts
- optimize readability and robustness of pluginDagSort
- allow `pre` and `post` to contain `undefined` in some edge cases.
> refactor: optimize readability and robustness of pluginDagSort

- packages/core/src/plugins/server.ts
update publicDir copy error log, currently we can not get useful error stack when copy error
see: https://github.com/jprichardson/node-fs-extra/issues/769
https://github.com/web-infra-dev/rspress/pull/559
> feat: improve publicDir copy error log

- packages/create-rsbuild/.npmignore
- packages/create-rsbuild/modern.config.ts
- packages/create-rsbuild/package.json
- packages/create-rsbuild/src/index.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- scripts/modern.base.config.ts
- bundle dependencies for speed up
- this package is now ESM-only, as user only use it via `npm create`.
> perf(create-rsbuild): bundle dependencies for speed up

- .changeset/tender-planes-add.md
- packages/shared/src/types/thirdParty.ts
allow less.additionalData to be async function
close https://github.com/web-infra-dev/rsbuild/issues/1375
> types: allow less.additionalData to be async function

- packages/document/docs/en/plugins/list/plugin-stylus.mdx
- packages/document/docs/zh/plugins/list/plugin-stylus.mdx
- packages/plugin-stylus/src/index.ts
Fix sourceMap default value of `plugin-stylus` in document, should be the same as [output.sourceMap.css](/config/output/source-map).
> docs(plugin-stylus): fix sourceMap default value

- .github/renovate.json5
Renovate ignore webpack-bundler-analyzer, see https://github.com/web-infra-dev/rsbuild/pull/1105
close https://github.com/web-infra-dev/rsbuild/pull/1356
> chore(workflow): renovate ignore webpack-bundler-analyzer

- packages/shared/src/mergeRsbuildConfig.ts
- packages/shared/tests/mergeConfig.test.ts
Merge dev.startUrl with overrides strategy. If `[string]` and `[false]` are merged into `[string, false]`, the startUrl plugin can not handle it.
> fix: merge dev.startUrl with overrides strategy

- .changeset/curly-cats-itch.md
- packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
- packages/compat/webpack/tests/webpackConfig.test.ts
- packages/core/src/provider/config.ts
- packages/document/docs/en/plugins/dev/hooks.mdx
- packages/document/docs/zh/plugins/dev/hooks.mdx
- packages/shared/src/mergeRsbuildConfig.ts
- packages/shared/tests/mergeConfig.test.ts
mergeRsbuildConfig no longer needs generics, declare the input and return type as `RsbuildConfig`.
> types: mergeRsbuildConfig no longer needs generics

- packages/core/src/loadEnv.ts
Prevent using 'local' as the env mode.
> fix: prevent using 'local' as the env mode

- packages/plugin-source-build/src/index.ts
- packages/plugin-source-build/tests/__snapshots__/index.test.ts.snap
Skip TypeScript references config for JS project.
> fix(plugin-source-build): skip references for JS project

- packages/core/src/provider/plugins/css.ts
- packages/core/src/provider/plugins/resolve.ts
- packages/shared/src/config.ts
Remove setConfig helper:
- To remove `lodash` dependency.
- To keep type friendly.
> chore(shared): remove setConfig helper

- packages/core/src/plugins/html.ts
- packages/shared/src/mergeRsbuildConfig.ts
Rewrite `mergeRsbuildConfig` function:
- improved performance.
- no longer depend on `lodash`.
- stricter path matching
- before:
- after:
> perf: improve mergeRsbuildConfig performance

- packages/document/package.json
- pnpm-lock.yaml
Bump rsfamily-nav-icon v1.0.1, remove `antd` dependency.
> docs: bump rsfamily-nav-icon v1.0.1

- .changeset/unlucky-jars-drop.md
- cspell.json
- e2e/cases/output/clean-dist-path/index.test.ts
- e2e/cases/output/clean-dist-path/src/index.js
- e2e/cases/output/output.test.ts
- packages/core/src/plugins/cleanOutput.ts
- packages/document/docs/en/config/output/clean-dist-path.mdx
- packages/document/docs/zh/config/output/clean-dist-path.mdx
- packages/shared/src/config.ts
- packages/shared/src/types/config/output.ts
When `output.distPath.root` is an external directory, `cleanDistPath` is not enabled by default, to avoid accidentally deleting files from other directories.
> feat: do not clean dist path if it is outside root

- e2e/cases/javascript-api/plugin-hooks/index.test.ts
- packages/document/docs/en/plugins/dev/hooks.mdx
- packages/document/docs/zh/plugins/dev/hooks.mdx
Add guide for plugin hooks execution order.
> docs: add guide for plugin hooks execution order

- e2e/cases/inspect-config/debug.test.ts
- packages/compat/webpack/src/core/initConfigs.ts
add  test cases to ensure output inspect-config success when dev/build.
> test(e2e): add test cases for inspect-config when dev/build  

- cspell.json
- packages/core/src/provider/plugins/transition.ts
Set default WATCHPACK_WATCHER_LIMIT to 20 to improve kill process performance.
see https://github.com/web-infra-dev/rspack/pull/5486 for details.
> perf: set default WATCHPACK_WATCHER_LIMIT to 20

- packages/shared/src/utils.ts
- packages/shared/tests/url.test.ts
Treat publicPath auto as empty string, this will be more consistent with Rspack/webpack's behavior.
see https://github.com/jantimon/html-webpack-plugin/issues/1514
> fix: treat publicPath auto as empty string

- packages/core/package.json
- packages/shared/package.json
- pnpm-lock.yaml
- scripts/test-helper/package.json
Downgrade Rspack to v0.5.0 to fix module federation
https://github.com/web-infra-dev/rspack/issues/5494
https://github.com/web-infra-dev/rsbuild/issues/1234
> fix: downgrade Rspack v0.5.0 to fix module federation

- e2e/cases/asset-prefix/index.test.ts
- e2e/cases/asset-prefix/src/index.js
Add E2E case for assetPrefix: 'auto'.
https://github.com/web-infra-dev/rsbuild/pull/1447
> test(e2e): add case for assetPrefix auto

- e2e/cases/asset-prefix/index.test.ts
- e2e/cases/asset-prefix/src/template.html
- packages/core/src/plugins/define.ts
- packages/core/src/plugins/html.ts
- packages/document/docs/en/config/dev/asset-prefix.mdx
- packages/document/docs/en/config/output/asset-prefix.mdx
- packages/document/docs/zh/config/dev/asset-prefix.mdx
- packages/document/docs/zh/config/output/asset-prefix.mdx
- packages/shared/src/chain.ts
- packages/shared/src/utils.ts
Format assetPrefix for define and template. If `output.assetPrefix` is `auto`, `process.env.ASSET_PREFIX`  will be format to empty string.
> fix: format assetPrefix for define and template

- examples/module-federation/host/module-federation.config.ts
- examples/module-federation/host/rsbuild.config.ts
- examples/module-federation/remote/module-federation.config.ts
- examples/module-federation/remote/rsbuild.config.ts
- packages/core/src/plugins/splitChunks.ts
- packages/document/docs/en/config/performance/chunk-split.mdx
- packages/document/docs/zh/config/performance/chunk-split.mdx
- packages/shared/src/types/config/performance.ts
Allow `chunkSplit.strategy` to be optional, making it easier to override some chunkSplit rules.
> feat: allow chunkSplit.strategy to be optional

- e2e/cases/asset-prefix/index.test.ts
- e2e/cases/inspect-config/debug.test.ts
- e2e/cases/live-reload/index.test.ts
- e2e/cases/module-federation/index.test.ts
- e2e/cases/multi-compiler/index.test.ts
- e2e/cases/performance/bundle-analyzer/index.test.ts
- e2e/cases/polyfill/browserslist/index.test.ts
- e2e/cases/preact/basic/index.test.ts
- e2e/cases/react/basic/index.test.ts
- e2e/cases/server/dev.test.ts
- e2e/cases/server/history-api-fallback/historyApiFallback.test.ts
- e2e/cases/server/htmlFallback.test.ts
- e2e/cases/server/ipv6-host/index.test.ts
- e2e/cases/server/print-urls/index.test.ts
- e2e/cases/server/proxy/index.test.ts
- e2e/cases/server/public-dir-with-template/index.test.ts
- e2e/cases/server/public-dir/publicDir.test.ts
- e2e/cases/server/writeToDisk.test.ts
- e2e/cases/solid/hmr/index.test.ts
- e2e/cases/svelte/index.test.ts
- e2e/scripts/shared.ts
Align close server API in E2E code, use `rsbuild.close()` for both `dev` and `build`.
> test(e2e): align close server API

- .changeset/fluffy-kangaroos-hunt.md
- packages/core/package.json
- packages/plugin-react/package.json
- packages/shared/package.json
- pnpm-lock.yaml
- scripts/test-helper/package.json
Bump Rspack v0.5.3, improve performance and fix support for module federation.
- https://github.com/web-infra-dev/rspack/releases/tag/untagged-dbf004e70ca6cb6283d9
- https://github.com/web-infra-dev/rsbuild/issues/1234
> feat(deps): bump Rspack v0.5.3

- packages/document/docs/en/plugins/dev/hooks.mdx
- packages/document/docs/zh/plugins/dev/hooks.mdx
- packages/shared/src/createHook.ts
- packages/shared/src/types/plugin.ts
- packages/shared/tests/createAsyncHook.test.ts
Support declare plugin hooks order, add new `order` field.
When registering a hook, you can declare the order of hook through the `order` field.
```ts
type HookDescriptor<T extends (...args: any[]) => any> = {
handler: T;
order: 'pre' | 'post' | 'default';
};
```
In the following example, the console will sequentially output `'2'` and `'1'`, because `order` was set to `pre` when plugin2 called `modifyRsbuildConfig`.
```ts
const plugin1 = () => ({
setup: (api) => {
api.modifyRsbuildConfig(() => console.log('1'));
},
});
const plugin2 = () => ({
setup: (api) => {
api.modifyRsbuildConfig({
handler: () => console.log('2'),
order: 'pre',
});
},
});
rsbuild.addPlugins([plugin1, plugin2]);
```
> feat: support declare plugin hooks order

- e2e/cases/decorator/2022-03/index.test.ts
- e2e/cases/decorator/basic/index.test.ts
- packages/plugin-babel/package.json
- packages/plugin-babel/src/plugin.ts
- packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
- packages/plugin-solid/tests/__snapshots__/index.test.ts.snap
- packages/plugin-source-build/tests/__snapshots__/index.test.ts.snap
- packages/plugin-vue-jsx/tests/__snapshots__/index.test.ts.snap
- packages/plugin-vue2-jsx/tests/__snapshots__/index.test.ts.snap
- pnpm-lock.yaml
`source.decorators` config should also supported in babel plugin.
https://rsbuild.dev/config/source/decorators
> feat: support decorator syntax when use babel plugin

- packages/document/docs/en/config/_meta.json
- packages/document/docs/en/config/security/nonce.md
- packages/document/docs/en/guide/basic/configure-rsbuild.mdx
- packages/document/docs/zh/config/_meta.json
- packages/document/docs/zh/config/security/nonce.md
- packages/document/docs/zh/guide/basic/configure-rsbuild.mdx
`security.nonce` is supported in rsbuild, but missing in document.
> docs: add security.nonce config

- packages/babel-preset/package.json
- packages/babel-preset/src/base.ts
- packages/babel-preset/src/node.ts
- packages/babel-preset/src/web.ts
- packages/babel-preset/tests/__snapshots__/node.test.ts.snap
- packages/babel-preset/tests/node.test.ts
- pnpm-lock.yaml
Remove `@rsbuild/shared` dependency from `@rsbuild/babel-preset`, because babel-preset is used by many Modern.js packages, we do not want these packages to depend on `@rspack/core` (which is very large).
> chore(babel-preset): remove shared dependency

- packages/plugin-preact/src/index.ts
- packages/plugin-react/src/react.ts
Reduce deepmerge overhead, shallow merge is faster and do not need to create new object.
> perf(plugin-react): reduce deepmerge overhead

- packages/compat/plugin-esbuild/src/index.ts
- packages/compat/plugin-swc/src/plugin.ts
- packages/plugin-babel/src/plugin.ts
- packages/plugin-solid/src/index.ts
- packages/plugin-source-build/src/index.ts
- packages/plugin-svgr/src/index.ts
- packages/plugin-vue-jsx/src/index.ts
- packages/plugin-vue2-jsx/src/index.ts
Should not depend on uni builder plugin names in Rsbuild.
This is a breaking change for Modern.js and will be released in v0.4.0.
> fix: should not depend on uni builder plugin names

- .github/workflows/test-ubuntu.yml
- scripts/skipCI.js
Using new M1 macOS runner to make CI faster.
- old:
- new:
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
> test(workflow): using new M1 macOS runner

- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/chain.ts
in some cases (modern.js source-build integration case), get error when fullySpecified rule after js rule:
https://github.com/web-infra-dev/modern.js/actions/runs/7723370235/job/21053319458
> fix: resolve error when fullySpecified rule after js rule

- e2e/scripts/shared.ts
- packages/core/src/cli/commands.ts
- packages/core/src/cli/config.ts
- packages/document/docs/en/api/javascript-api/core.mdx
- packages/document/docs/zh/api/javascript-api/core.mdx
The `loadConfig` method now returns both the contents of the config and the path to the config file:
```js
import { loadConfig } from '@rsbuild/core';
// v0.3
const config = await loadConfig();
// v0.4
const { content, filePath } = await loadConfig();
```
https://github.com/web-infra-dev/rsbuild/discussions/1420
> breaking change: loadConfig method return value changed

- packages/core/src/constants.ts
- packages/core/src/index.ts
- packages/plugin-babel/src/plugin.ts
Move babel plugin name constant to `@rsbuild/plugin-babel`, this is a small breaking change. As far as I know, no external users are currently using this constant.
> chore: move babel plugin name constant

- packages/plugin-react/src/splitChunks.ts
- packages/plugin-vue/src/splitChunks.ts
- packages/plugin-vue2/src/splitChunks.ts
Fix cacheGroups type mismatch, Rspack and Webpack uses different cacheGroups type
> types: fix cacheGroups type mismatch

- packages/core/src/provider/shared.ts
Always show warnings in formatStats, remove the unused showWarnings param.
> chore: always show warnings in formatStats

- packages/document/docs/en/config/performance/profile.mdx
- packages/document/docs/en/guide/optimization/build-performance.mdx
- packages/document/docs/zh/config/performance/profile.mdx
- packages/document/docs/zh/guide/optimization/build-performance.mdx
Add Node.js profiling guide, use [speedscope](https://github.com/jlfwong/speedscope) to visualize this file.
> docs: add Node.js profiling guide

- packages/compat/webpack/tests/__snapshots__/css.test.ts.snap
- packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/__snapshots__/css.test.ts.snap
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/document/docs/en/config/tools/autoprefixer.mdx
- packages/document/docs/en/guide/basic/css-usage.md
- packages/document/docs/zh/config/tools/autoprefixer.mdx
- packages/document/docs/zh/guide/basic/css-usage.md
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
- packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
- packages/plugin-stylus/tests/__snapshots__/rspack.test.ts.snap
- packages/shared/src/css.ts
- packages/shared/tests/css.test.ts
Check if autoprefixer is already registered in the user project. If the autoprefixer plugin is already registered in your project, Rsbuild will not register the autoprefixer plugin again.
> perf: remove duplicate autoprefixer plugin

- packages/compat/webpack/src/plugins/less.ts
- packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
- packages/core/src/provider/plugins/less.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/__snapshots__/css.test.ts.snap
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/document/docs/en/config/tools/less.mdx
- packages/document/docs/zh/config/tools/less.mdx
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/getLoaderOptions.ts
Fix less default resolve directory.
Let less resolve from node_modules in the current root directory, to avoid resolving from wrong node_modules.
https://lesscss.org/usage/#less-options-include-paths
> fix: less default resolve directory

- packages/core/src/server/proxy.ts
- packages/document/docs/en/config/server/proxy.mdx
- packages/document/docs/zh/config/server/proxy.mdx
fix WebSocket connect error when user use proxy and forget exclude hmr path (proxy WebSocket to a wrong path )
This behavior is similar to the following code behavior, because`raw.proxyOptions.ws` default value is `undefined`:
https://github.com/web-infra-dev/rsbuild/pull/604/files#diff-0c9eec60641329e501f974ce5a16dedcb9c71b546219802c43a9a3687bdd3892L77
> fix(server): not proxy websocket by default

- .changeset/mean-pants-chew.md
- packages/core/src/provider/plugins/css.ts
- packages/shared/src/types/thirdParty.ts
Improve tools.styleLoader typing.
https://github.com/webpack-contrib/style-loader
> types: improve tools.styleLoader typing

- packages/plugin-solid/package.json
- pnpm-lock.yaml
Lock solid-refresh to fix runtime error.
resolve https://github.com/web-infra-dev/rsbuild/issues/1533
https://github.com/solidjs/solid-refresh/issues/58
> fix(plugin-solid): lock solid-refresh to fix runtime error

- .changeset/sweet-parents-act.md
- e2e/cases/source/alias-by-target/index.test.ts
- e2e/cases/source/alias-by-target/rsbuild.config.ts
- e2e/cases/source/alias-by-target/src/common/test.js
- e2e/cases/source/alias-by-target/src/common2/test.js
- e2e/cases/source/alias-by-target/src/index.js
- e2e/cases/source/alias-by-target/tsconfig.json
- packages/document/docs/en/config/source/alias.mdx
- packages/document/docs/en/config/tools/bundler-chain.mdx
- packages/document/docs/en/config/tools/rspack.mdx
- packages/document/docs/zh/config/source/alias.mdx
- packages/document/docs/zh/config/tools/bundler-chain.mdx
- packages/document/docs/zh/config/tools/rspack.mdx
- packages/shared/src/chain.ts
- packages/shared/src/types/config/source.ts
Support for set different alias by target:
```js
source: {
alias: (alias, { target }) => {
if (target === 'node') {
alias['@common'] = './src/node/common';
} else if (target === 'web') {
alias['@common'] = './src/web/common';
}
},
},
};
```
https://github.com/web-infra-dev/rsbuild/discussions/1565
> feat: support for set different alias by target

- packages/compat/plugin-swc/src/utils.ts
should remove transformLodash option when pass to swc-plugin
> fix(plugin-swc): build error when set transformLodash false

- .changeset/ten-balloons-jog.md
- packages/shared/src/utils.ts
- packages/shared/tests/prettyTime.test.ts
Display more accurate compile times, this is useful for observing compile time changes.
> fix: display more accurate compile times

- e2e/cases/css/style-loader/.gitignore
- e2e/cases/css/style-loader/index.test.ts
- e2e/cases/css/style-loader/rsbuild.config.ts
- e2e/cases/css/style-loader/src/index.ts
- packages/core/src/provider/plugins/css.ts
- packages/core/tests/__snapshots__/css.test.ts.snap
Setting styleLoader.esModule to false is to temporarily solve the hmr problem, which has now been fixed by Rspack
> chore: set styleLoader.esModule default true

- packages/core/modern.config.ts
- packages/core/package.json
- packages/core/src/client/hmr/index.ts
- packages/core/tsconfig.json
Use import.meta.webpackHot to replace module.hot, which is more ESM-friendly and type safe.
https://webpack.js.org/api/hot-module-replacement/
> refactor: use import.meta.webpackHot to replace module.hot

- packages/document/docs/en/guide/basic/server.md
- packages/document/docs/zh/guide/basic/server.md
Introduce how to use other server-side framework's middleware in Rsbuild.
> docs: add extend-middleware guide

- packages/plugin-type-check/package.json
- pnpm-lock.yaml
webpack is fork-ts-checker-webpack-plugin's peer dependency
> fix(plugin-type-check): missing webpack peer dependency

- .github/workflows/update-modern.yml
- .github/workflows/update-rspress.yml
- pnpm-lock.yaml
- scripts/update-packages/package.json
- scripts/update-packages/src/modern.ts
- scripts/update-packages/src/rspack.ts
- scripts/update-packages/src/utils.ts
Replace get-packages with monorepo-utils.
close https://github.com/web-infra-dev/rsbuild/pull/1593
> chore: replace get-packages with monorepo-utils

- packages/plugin-babel/src/types.ts
Fix missing babel loader types in `@rsbuild/plugin-babel`.
https://github.com/babel/babel-loader?tab=readme-ov-file#options
> fix(plugin-babel): missing babel loader types

- CONTRIBUTING.md
- packages/document/docs/en/guide/start/quick-start.mdx
- packages/document/docs/zh/guide/start/quick-start.mdx
Recommend using Node.js 20 in the quick start document.
Rsbuild still supports Node.js 16, but some 3rd party dependencies are going to drop Node.js 16 support. Therefore, we recommend users to use higher versions of Node.js in preparation for deprecating lower versions of Node.js in the future.
> docs: recommend using Node.js 20

- e2e/cases/source/multiple-entry/index.test.ts
- e2e/cases/source/multiple-entry/rsbuild.config.ts
- e2e/cases/source/multiple-entry/src/index.client.js
- e2e/cases/source/multiple-entry/src/index.server.js
- packages/core/src/plugins/entry.ts
- packages/core/src/provider/createContext.ts
- packages/shared/src/types/config/source.ts
Support configuring entry by target, this is useful for implementing SSR:
```js
import { defineConfig } from '@rsbuild/core';
source: {
entry(entry, { target }) {
if (target === 'web') {
entry.index = './src/index.client.js';
} else if (target === 'node') {
entry.index = './src/index.server.js';
}
return entry;
},
},
output: {
targets: ['web', 'node'],
},
});
```
> feat: support configuring entry by target

- e2e/cases/async-plugin/index.test.ts
- e2e/cases/async-plugin/src/index.js
- e2e/scripts/shared.ts
- packages/core/src/createRsbuild.ts
- packages/core/src/pluginManager.ts
- packages/document/docs/en/config/plugins.mdx
- packages/document/docs/zh/config/plugins.mdx
- packages/shared/src/types/plugin.ts
Support registering async plugin in config, this allows plugin to run some async code on initialization.
> feat: support registering async plugin in config

- packages/core/src/loadEnv.ts
Do not clean up NODE_ENV on server restart, otherwise the .env.${mode} file will not be loaded.
close https://github.com/web-infra-dev/rsbuild/issues/1643
> fix(server): do not cleanup NODE_ENV on restart

- packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
- packages/compat/webpack/tests/default.test.ts
- packages/core/src/cli/commands.ts
- packages/core/src/cli/init.ts
- packages/core/src/config.ts
- packages/core/src/plugins/cache.ts
- packages/core/src/server/restart.ts
- packages/shared/src/config.ts
- packages/shared/src/types/config/index.ts
- add rsbuild config to build dependencies.
- add `_privateMeta` field in the config object to store the config file path, this field is considered as a private filed and should not be used by users.
close https://github.com/web-infra-dev/rsbuild/issues/1574
> fix(webpack): add rsbuild config to build dependencies

- packages/shared/src/mergeRsbuildConfig.ts
Add `rsbuildConfig.provider` to override path list to avoid merge provider object.
> fix: avoid merge provider object

- packages/core/src/loadEnv.ts
- packages/core/src/provider/plugins/progress.ts
Fix progress plugin custom prefix not work.
[The docs](https://rsbuild.dev/zh/config/dev/progress-bar) says can modify the progress bar id by setting, but it's not working.
```
dev: {
progressBar: {
id: 'Some Text',
},
},
};
```
Use `progressBar.id` as prefix if it exist.
- docs: https://rsbuild.dev/zh/config/dev/progress-bar
> fix: progress plugin custom prefix not work

- e2e/cases/html/rem/index.test.ts
- e2e/cases/html/rem/src/index.js
- packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
At iOS webview, the meta of viewport should be placed before the rem runtime code.
> fix(plugin-rem): runtime code should inject at head end

- packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
Use alterAssetTags to insert script, make sure the rem runtime code is after the meta tag and before the user scripts.
https://github.com/web-infra-dev/rsbuild/pull/1664
> chore(plugin-rem): use alterAssetTags to insert script

- e2e/cases/html/cross-origin/index.test.ts
- packages/core/src/rspack/HtmlCrossOriginPlugin.ts
- packages/document/docs/en/config/html/crossorigin.mdx
- packages/document/docs/zh/config/html/crossorigin.mdx
no need to set crossorigin="anonymous" if asset domain is the same as the page domain, align with webpack's crossOriginLoading logic.
https://github.com/webpack/webpack/blob/611bded369b5a9ea695f2669b25a6f88b67d7826/lib/runtime/LoadScriptRuntimeModule.js#L100-L111
> fix: no need to set crossorigin if publicPath is auto

- examples/react/rsbuild.config.ts
- packages/compat/webpack/package.json
- packages/core/package.json
- packages/core/src/rspack/HtmlAppIconPlugin.ts
- packages/core/src/rspack/HtmlBasicPlugin.ts
- packages/core/src/rspack/HtmlCrossOriginPlugin.ts
- packages/core/src/rspack/HtmlNetworkPerformancePlugin.ts
- packages/core/src/rspack/HtmlNoncePlugin.ts
- packages/core/src/rspack/HtmlTagsPlugin.ts
- packages/core/src/rspack/InlineChunkHtmlPlugin.ts
- packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
- packages/plugin-assets-retry/package.json
- packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
- packages/plugin-rem/package.json
- packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
- packages/shared/package.json
- pnpm-lock.yaml
Bump html-rspack-plugin 5.6.1 to fix the compilation type issue.
> chore(deps): bump html-rspack-plugin 5.6.1

- packages/plugin-eslint/src/index.ts
- packages/plugin-eslint/tests/__snapshots__/index.test.ts.snap
- packages/plugin-type-check/tests/__snapshots__/index.test.ts.snap
- Let plugin-eslint ignore the dist folder by default.
- Remove an unused snapshot.
> fix(plugin-eslint): ignore dist folder by default

- e2e/cases/source-build/components/package.json
- packages/plugin-source-build/src/index.ts
user references configurations can also used in rsbuild source build.
https://www.rspack.dev/config/resolve.html#resolvetsconfigreferences
> feat(plugin-source-build): support merge user references config

- packages/document/docs/en/plugins/list/plugin-css-minimizer.mdx
- packages/document/docs/zh/plugins/list/plugin-css-minimizer.mdx
- packages/plugin-css-minimizer/src/index.ts
There are some constants to be exposed which is necessary for user custom-configuration in CssMinimizerWebpackPlugin.
```typescript
import { defineConfig } from '@rsbuild/core';
import {
pluginCssMinimizer,
CssMinimizerWebpackPlugin,
} from '@rsbuild/plugin-css-minimizer';
plugins: [
pluginCssMinimizer({
pluginOptions: {
minify: CssMinimizerWebpackPlugin.lightningCssMinify,
minimizerOptions: {
// ...
}
},
}),
],
});
```
no
If this usage is recommended, I can update the document later
> feat(plugin-css-minimizer): export webpack-plugin to let users customize configurations

- .changeset/wicked-rules-drive.md
- packages/core/src/provider/plugins/swc.ts
- packages/core/tests/__snapshots__/swc.test.ts.snap
- packages/core/tests/swc.test.ts
- packages/shared/src/types/config/tools.ts
Add tools.swc config to configure builtin swc-loader, this can be useful to enable some rspack experiments features, such as relay or emotion.
I will add the document later.
https://www.rspack.dev/guide/builtin-swc-loader.html#optionsrspackexperiments
> feat: add tools.swc config to configure builtin swc-loader

- packages/plugin-preact/package.json
- packages/plugin-preact/src/index.ts
- packages/plugin-preact/tests/index.test.ts
- pnpm-lock.yaml
Use `api.modifyRsbuildConfig` instead of `api.modifyBundlerChain` in the preact plugin. This way the plugin does not need to depend on the `modifySwcLoaderOptions` helper and becomes more independent.
> refactor(plugin-preact): modify rsbuild config directly

- .husky/pre-commit
- .ls-lint.yml
- package.json
- pnpm-lock.yaml
- remove a root folder for a neater look 😌
⚠️👇🏻
for developers has cloned the repository, run the following commands to clean husky's residue (https://github.com/toplenboren/simple-git-hooks?tab=readme-ov-file#add-simple-git-hooks-to-the-project)
```
git config core.hooksPath .git/hooks/
rm -rf .git/hooks
```
> chore: replace husky with simple-git-hooks

- packages/create-rsbuild/template-vue3-js/.vscode/extensions.json
- packages/create-rsbuild/template-vue3-ts/.vscode/extensions.json
TypeScript Vue Plugin (Volar)  has been  deprecated
https://github.com/vuejs/language-tools/releases/tag/v2.0.0
> fix(create-rsbuild): remove vue3 deprecated plugin (TypeScript Vue Plugin)

- packages/core/src/plugins/fileSize.ts
Coloring printed asset names.
- before:
- after:
> feat: coloring printed asset names

- packages/compat/plugin-swc/src/plugin.ts
- packages/compat/webpack/tests/minimize.test.ts
Fix duplicated JS minimizer when using `@rsbuild/webpack` and `@rsbuild/plugin-swc`.
https://github.com/web-infra-dev/rsbuild/issues/1738
> fix(webpack): duplicated JS minimizer

- .changeset/soft-dryers-brake.md
- e2e/cases/output/assets.test.ts
- packages/core/src/plugins/asset.ts
- packages/document/docs/en/config/output/data-uri-limit.mdx
- packages/document/docs/zh/config/output/data-uri-limit.mdx
- packages/plugin-svgr/src/index.ts
- packages/shared/src/types/config/output.ts
Allow output.dataUriLimit to be a number, which is more convenient.
> feat: allow output.dataUriLimit to be a number

- packages/shared/src/url.ts
should print `http://[::1]:8080/` instead of `http://::1:8080/`
> fix: print ipv6 url correctly

- packages/compat/webpack/package.json
- packages/core/package.json
- packages/plugin-assets-retry/package.json
- packages/plugin-rem/package.json
- packages/shared/package.json
- pnpm-lock.yaml
FIx the webpack peer dependencies of html-rspack-plugin will generate unexpected transitivePeerDependencies when using pnpm.
see: https://github.com/rspack-contrib/html-rspack-plugin/pull/6
> fix: html-rspack-plugin peer dependency issue

- e2e/cases/performance/print-file-size/index.test.ts
- packages/core/src/plugins/fileSize.ts
- packages/core/src/provider/build.ts
- packages/shared/src/types/stats.ts
Fix failed to print size of multiple targets.
https://github.com/web-infra-dev/rsbuild/pull/1763
> fix: failed to print size of multiple targets

- packages/compat/webpack/src/core/build.ts
- packages/core/src/provider/build.ts
- packages/document/docs/en/plugins/dev/hooks.mdx
- packages/document/docs/en/shared/onAfterBuild.md
- packages/document/docs/zh/plugins/dev/hooks.mdx
- packages/document/docs/zh/shared/onAfterBuild.md
- packages/shared/src/types/hooks.ts
> fix(core): call `onAfterBuild` on every build

- biome.json
- package.json
- packages/core/src/plugins/splitChunks.ts
- packages/core/src/server/helper.ts
- packages/core/tests/splitChunks.test.ts
- packages/document/docs/en/config/performance/chunk-split.mdx
- packages/document/docs/zh/config/performance/chunk-split.mdx
- packages/plugin-rem/tests/AutoSetRootFontSizePlugin.test.ts
- pnpm-lock.yaml
Bump biome v1.6.0 and fix errors, the vue and svelte rules are disabled until they are more stable.
close https://github.com/web-infra-dev/rsbuild/pull/1769
> chore: bump biome v1.6.0 and fix errors

- e2e/cases/svg/svgr-query-react/index.test.ts
- e2e/cases/svg/svgr-query-react/rsbuild.config.ts
- e2e/cases/svg/svgr-query-react/src/App.jsx
- e2e/cases/svg/svgr-query-react/src/index.js
- e2e/cases/svg/svgr-query-react/src/small.svg
- packages/core/src/plugins/asset.ts
- packages/plugin-svgr/src/index.ts
- packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/chain.ts
- packages/shared/src/config.ts
Add support for `?react` query to transform SVG into React component.
```js
import Component from './small.svg?react';
function App() {
return (
<Component />
);
}
```
This will become the recommended way to use SVGR, because:
- No longer depend on the deprecated `url-loader`.
- No longer rely on Rspack's issuer, which is inaccurate in some cases.
- Better for tree shaking, avoid duplicated code.
- Align with the `vite-plugin-svgr` usage.
- https://github.com/web-infra-dev/rsbuild/issues/1766
- https://github.com/gregberge/svgr/issues/551
- https://github.com/facebook/create-react-app/issues/11213
- https://www.npmjs.com/package/vite-plugin-svgr
> feat(plugin-svgr): support for react query

- e2e/cases/svg/svgr-query-react-dynamic-import/index.test.ts
- e2e/cases/svg/svgr-query-react-dynamic-import/rsbuild.config.ts
- e2e/cases/svg/svgr-query-react-dynamic-import/src/App.jsx
- e2e/cases/svg/svgr-query-react-dynamic-import/src/index.js
- e2e/cases/svg/svgr-query-react-dynamic-import/src/small.svg
Add E2E case for SVG dynamic import.
https://github.com/web-infra-dev/rsbuild/issues/1766
> test(e2e): add case for SVG dynamic import

- e2e/cases/svg/svg.test.ts
- e2e/cases/svg/svgo-minify-id-prefix/rsbuild.config.ts
- e2e/cases/svg/svgo-minify-view-box/rsbuild.config.ts
- e2e/cases/svg/svgr-default-export-url/rsbuild.config.ts
- e2e/cases/svg/svgr-query-url/rsbuild.config.ts
- packages/document/docs/en/plugins/list/plugin-svgr.mdx
- packages/document/docs/zh/plugins/list/plugin-svgr.mdx
- packages/plugin-svgr/src/index.ts
- packages/plugin-svgr/tests/index.test.ts
Prefer using svgrOptions.exportType option and deprecate the `svgDefaultExport` option.
This change is to avoid having two options with the same effect.
https://github.com/gregberge/svgr/blob/785cba48cca6c27810fca3eaeb4aae86822772cc/website/pages/docs/webpack.mdx#L165
> fix(plugin-svgr): prefer using svgrOptions.exportType option

- packages/babel-preset/package.json
- packages/babel-preset/tests/__snapshots__/web.test.ts.snap
- packages/compat/plugin-swc/package.json
- packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
- packages/core/package.json
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/core/tests/__snapshots__/swc.test.ts.snap
- packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
- packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
- packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
- pnpm-lock.yaml
Bump core-js from v3.32 to v3.36 to include the latest polyfills (note that this will increase the bundle size if use `polyfill: 'entry'`).
see: https://github.com/zloirock/core-js/releases
> feat(deps): bump core-js from v3.32 to v3.36

- e2e/cases/css/import-common-css/index.test.ts
- e2e/cases/css/nested-npm-import/index.test.ts
Proxy tilde deprecation warning to keep the e2e logs clean.
> test(e2e): proxy tilde deprecation warning

- packages/plugin-svgr/src/index.ts
- packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
- packages/plugin-svgr/tests/index.test.ts
Add `mixedImport` option for `@rsbuild/plugin-svgr`.
```js
// mixedImport: true
import url, { ReactComponent as Foo } from 'foo.svg';
// mixedImport: false
import url from 'foo.svg';
import Foo from 'foo.svg?react';
```
> feat(plugin-svgr): add mixedImport option

- packages/plugin-type-check/src/index.ts
- packages/plugin-type-check/tests/__snapshots__/index.test.ts.snap
- packages/plugin-type-check/tests/index.test.ts
The options type of plugin-type-check should be non nullable.
> fix(plugin-type-check): options type should be non nullable

- packages/shared/src/getBrowserslist.ts
- packages/shared/tests/getBrowserslist.test.ts
This PR implements a helper to convert browserslist to ECMAScript version, it can be used to:
- Set precise Rspack target to reduce Rspack runtime code size. https://www.rspack.dev/config/target.html
- Help the check syntax plugin to get correct ECMAScript version.
> chore: add browserslist to es version helper

- cspell.json
- packages/core/src/provider/plugins/transition.ts
- packages/core/tests/__snapshots__/default.test.ts.snap
Rsbuild v0.5.0 will enable the Rspack's [new tree shaking](https://www.rspack.dev/config/experiments.html#experimentsrspackfuturenewtreeshaking) in production build. This will significantly optimize the tree shaking algorithm, making the bundle size smaller in the production build.
If you encounter any issues with the new tree shaking in your project, you can report it to the Rspack repository through an issue. You can also manually switch to old tree shaking:
```js
import { defineConfig } from '@rsbuild/core';
tools: {
rspack: {
experiments: {
rspackFuture: {
newTreeshaking: false,
},
},
},
},
});
```
Note that Rsbuild only enable new tree shaking in production build, because Rspack still has some problems when using it in dev mode. Such …
> feat: enable new tree shaking in production

- packages/shared/src/getBrowserslist.ts
- packages/shared/tests/getBrowserslist.test.ts
handle more cases in ES version helper:
- support for es2018
- return number instead of string
- ignore unknown version
> fix: handle more cases in ES version helper

- packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
- packages/core/src/plugins/target.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/core/tests/target.test.ts
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/getBrowserslist.ts
Set correct rspack target based on browserslist, this change can fix some warning logs, such as:
> fix: set correct rspack target based on browserslist

- cspell.json
- e2e/cases/css/lightningcss/index.test.ts
- e2e/cases/css/lightningcss/src/_styl.js
- e2e/cases/css/lightningcss/src/c.module.styl
support webpack tests
At present, the execution order of rsbuild plugins is awkward in someway. I don't know if this meets expectations, and there are some usage burdens for users.
Lightningcss plugin has to be behind pluginStylus and pluginSwc if users use these plugins together
```ts
plugins: [pluginSwc(), pluginStylus(), pluginLightningCss(), pluginCssMinimizer()]
```
result
```js
// [bunder].config.js
minimizer: [
/* config.optimization.minimizer('swc') */
new SwcMinimizerPlugin({  // minify both css and js
jsMinify: undefined,
cssMinify: undefined,
}),
/* config.optimization.minimizer('css') */
new CssMinimizerPlugin(), // minify js
],
```
I'm not sure if this problem will be encountered when developing other plugins.
> test(plugin-lightningcss): add plugin-lightningcss using webpack and fix plugin-stylus test

- packages/plugin-type-check/src/index.ts
Improve the running log of plugin-type-check. The previous one is too long.
> chore(plugin-type-check): improve the running log

- e2e/cases/umd/basic/rsbuild.config.ts
- e2e/cases/umd/export-array/rsbuild.config.ts
- e2e/cases/umd/export/rsbuild.config.ts
- packages/core/src/plugins/html.ts
- packages/document/docs/en/config/tools/html-plugin.mdx
- packages/document/docs/zh/config/tools/html-plugin.mdx
- packages/shared/src/types/config/tools.ts
Allow tools.htmlPlugin to be true, this can be helpful to force generating HTML files when using the UMD plugin.
> feat: allow tools.htmlPlugin to be true

- packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
- packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
- packages/core/src/plugins/html.ts
- packages/core/src/rspack/HtmlBasicPlugin.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/core/tests/__snapshots__/html.test.ts.snap
- packages/core/tests/__snapshots__/inlineChunk.test.ts.snap
- packages/document/docs/en/config/html/tags.mdx
- packages/document/docs/zh/config/html/tags.mdx
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/types/config/html.ts
Simplify html.tags implementation, extract the functions and rename the types.
> refactor: simplify html.tags implementation

- .changeset/lazy-terms-perform.md
- packages/core/src/provider/plugins/transition.ts
- packages/core/tests/__snapshots__/default.test.ts.snap
Revert new tree shaking as it breaks the CSS modules in the doc website.
https://github.com/web-infra-dev/rspack/issues/5968
> fix: revert new tree shaking

- packages/core/src/config.ts
- packages/core/src/createRsbuild.ts
- packages/document/docs/en/api/javascript-api/core.mdx
- packages/document/docs/zh/api/javascript-api/core.mdx
Allow to call `loadConfig` and `createRsbuild` without options.
> fix: allow to call loadConfig without options

- packages/core/package.json
- packages/plugin-lightningcss/package.json
- packages/plugin-react/package.json
- packages/shared/package.json
- pnpm-lock.yaml
- scripts/test-helper/package.json
Bump Rspack v0.5.8.
https://github.com/web-infra-dev/rspack/releases/tag/v0.5.8
> feat: bump Rspack v0.5.8

- packages/document/docs/en/guide/faq/exceptions.md
- packages/document/docs/zh/guide/faq/exceptions.md
Remove outdated lodash FAQ as Rsbuild does not use the babel-plugin-lodash.
> docs: remove outdated lodash FAQ

- packages/core/src/plugins/html.ts
we should keep html-entry-plugin registration order stable based on entryNames.
`Promise.all` cannot make the html-entry-plugin registration order stable, and changes in the plugin registration order will cause runtime hash to change.
> fix: keep html-entry-plugin registration order stable

- packages/core/src/server/getDevMiddlewares.ts
Return 404 code in rsbuild dev server when `xxx.hot-update.json` file not found, so that some other frameworks which use custom server (such as modern.js) don't need to handle `.hot-update.json` file.
currently, in modern.js:
> feat(server): return 404 code when xxx.hot-update.json file not found

- .nvmrc
- package.json
It is allowed to use Node 18 or 20 when developing Rsbuild, so we can remove the `.nvmrc` file and just use `engines.node` to limit the version range.
> chore(workflow): remove .nvmrc

- packages/document/docs/en/plugins/list/plugin-lightningcss.mdx
- packages/document/docs/zh/plugins/list/plugin-lightningcss.mdx
unnecessary `transform` object key
No
> docs: fix pluginLightningcss unnecessary `transform` object key

- packages/document/package.json
- packages/document/rspress.config.ts
- pnpm-lock.yaml
Integrate rsbuild-plugin-google-analytics to the Rsbuild website.
https://github.com/rspack-contrib/rsbuild-plugin-google-analytics
> docs: integrate rsbuild-plugin-google-analytics

- .github/renovate.json5
Let renovate ignore engines.node, this should be manually upgraded.
https://github.com/web-infra-dev/rsbuild/pull/1929
> chore(workflow): let renovate ignore engines.node

- .changeset/thin-worms-build.md
- packages/plugin-react/src/splitChunks.ts
Resolves chunk issue where excessive bloat is downloaded if federation is applied 
before:
after:
While more chunks are emitted, they are smaller and do not cause module duplication
> fix(plugin-react): no chunk group of react if federation enabled

- packages/core/src/plugins/moduleFederation.ts
- packages/core/src/plugins/splitChunks.ts
- packages/document/docs/en/config/module-federation/options.mdx
- packages/document/docs/zh/config/module-federation/options.mdx
- packages/plugin-react/src/splitChunks.ts
Currently, splitChunks will take precedence over module federation shared modules. So we need to disable the default split chunks rules to make shared modules to work properly.
> See https://github.com/module-federation/module-federation-examples/issues/3161
The motivation for this PR is to completely resolve the issues addressed in #1942
> fix: disable default split chunks rules for MF

- packages/core/src/client/hmr/createSocketUrl.ts
- packages/core/src/client/hmr/index.ts
- packages/core/src/client/hmr/overlay.ts
- packages/core/src/server/compilerDevMiddleware.ts
- packages/document/docs/en/config/dev/client.mdx
- packages/document/docs/zh/config/dev/client.mdx
- packages/shared/src/types/config/dev.ts
support show overlay in the browser when compiler error:
Setting `dev.clientoverlay`  to true will enable the error overlay: 
```
dev: {
client: {
overlay: true,
}
}
});
```
> feat: support show overlay in the browser when compiler error

- e2e/cases/javascript-api/plugin-after-build-hook/index.test.ts
- e2e/cases/javascript-api/plugin-after-build-hook/src/index.js
- examples/webpack/rsbuild.config.ts
- packages/compat/webpack/src/core/build.ts
- packages/core/package.json
- packages/core/src/provider/build.ts
- packages/plugin-lightningcss/package.json
- packages/plugin-react/package.json
- packages/shared/package.json
- pnpm-lock.yaml
Fix onAfterBuild hook async not work.
The MultiCompiler of webpack does not supports `done.tapPromise`, so we need to use the `done` hook of `MultiCompiler.compilers` to implement it.
https://github.com/web-infra-dev/rspack/pull/6058
> fix: onAfterBuild hook async not work

- packages/compat/webpack/src/core/build.ts
- packages/compat/webpack/src/core/createCompiler.ts
- packages/core/src/provider/build.ts
- packages/core/src/provider/createCompiler.ts
- packages/shared/src/utils.ts
Fix onDevCompileDone hook async not work.
The MultiCompiler of Rspack / webpack does not supports `done.tapPromise`, so we need to use the `done` hook of `MultiCompiler.compilers` to implement it.
The same as https://github.com/web-infra-dev/rsbuild/pull/1955
> fix: onDevCompileDone hook async not work

- .changeset/itchy-lions-battle.md
- packages/core/src/client/hmr/index.ts
- packages/core/src/client/hmr/overlay.ts
- detect `document` object to detemine showing overlay
- `clearOverlay` respect overlay option
> fix(overlay): detect document, respect overlay option

- e2e/cases/solid/ref/index.test.ts
- e2e/cases/solid/ref/rsbuild.config.ts
- e2e/cases/solid/ref/src/App.jsx
- e2e/cases/solid/ref/src/index.jsx
- packages/plugin-solid/package.json
- pnpm-lock.yaml
Downgrade solid-refresh to v0.6.3.
resolve https://github.com/web-infra-dev/rsbuild/issues/1963
> fix(plugin-solid): downgrade solid-refresh to v0.6.3

- packages/core/src/client/hmr/overlay.ts
Add error overlay footer tips to guide users to dismiss the overlay.
> feat: add error overlay footer tips

- e2e/cases/javascript-api/plugin-expose/index.test.ts
- e2e/cases/javascript-api/plugin-expose/src/index.js
- packages/core/src/provider/initPlugins.ts
- packages/shared/src/types/plugin.ts
This PR introduced two new plugin API for plugin communication:
```js
const parentSymbol = Symbol('parent-api');
const pluginParent: RsbuildPlugin = {
name: 'plugin-parent',
setup(api) {
api.expose<ParentAPI>(parentSymbol, {
initial: 1,
double: (val: number) => val * 2,
});
},
};
const pluginChild: RsbuildPlugin = {
name: 'plugin-child',
setup(api) {
const parentAPI = api.useExposed<ParentAPI>(parentSymbol);
expect(parentAPI?.double(parentAPI.initial)).toEqual(2);
},
};
```
> feat: support for plugin communication

- packages/core/src/plugins/html.ts
Remove ts-expect-error comment for dependOn as it breaks the Rspack ecosystem CI.
- https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/8519320171/job/23333117046#step:7:150
- https://github.com/web-infra-dev/rspack/pull/6069
> chore: remove ts-expect-error comment for dependOn

- packages/core/src/provider/initPlugins.ts
- packages/core/src/rspack/transformLoader.ts
- packages/core/src/types.ts
- packages/document/docs/en/plugins/dev/hooks.mdx
- packages/document/docs/zh/plugins/dev/hooks.mdx
- packages/shared/src/types/hooks.ts
- packages/shared/src/types/plugin.ts
- packages/shared/src/types/rspack.ts
- packages/shared/src/types/utils.ts
Add new transform plugin API. 
This is similar to rollup's transform and can be used as an intuitive way to call Rspack loader.
For example, implement a Pug plugin to compile `.pug` files:
```js
import pug from 'pug';
import type { RsbuildPlugin } from '@rsbuild/core';
export const pluginPug = (): RsbuildPlugin => ({
name: 'rsbuild:pug',
setup(api) {
api.transform(
({ code }) => {
const templateCode = pug.compileClient(code, {});
return `${templateCode}; module.exports = template;`;
},
{ test: /\.pug$/ },
);
},
});
```
> feat: add new transform plugin API

- packages/core/package.json
- packages/plugin-lightningcss/package.json
- packages/plugin-react/package.json
- packages/shared/package.json
- pnpm-lock.yaml
Fix the missing Rspack bindings, see https://github.com/web-infra-dev/rspack/issues/6101
The current Rspack canary is released based on https://github.com/web-infra-dev/rspack/pull/6058.
> fix: missing Rspack bindings

- .changeset/dirty-pumas-walk.md
- packages/shared/src/types/plugin.ts
Mark transform API as experimental.
We still need some time to test and improve the transform API before v0.6.0.
> chore: mark transform API as experimental

- e2e/cases/plugin-api/plugin-transform/myPlugin.ts
- examples/webpack/rsbuild.config.ts
- packages/core/src/provider/initPlugins.ts
- packages/core/src/rspack/transformLoader.ts
- packages/core/src/types.ts
- packages/shared/src/types/plugin.ts
Adjust the params order of transform API to pass the descriptor as the first param. This helps users avoid forgetting to pass in `test` and transforming too many modules.
```js
api.transform({ test: /\.js$/ }, ({ code }) => {
return code;
});
```
> chore: adjust params order of transform API

- packages/core/src/rspack/transformLoader.ts
- packages/shared/src/types/plugin.ts
Allow to add dependency in transform API, `addDependency` is a commonly used API and we need to add it to refactor the Rsbuild Pug plugin.
> feat: allow to add dependency in transform API

- packages/shared/src/types/plugin.ts
Make RsbuildPluginAPI readonly to prevent unexpected modifications.
https://github.com/web-infra-dev/rsbuild/pull/1972#discussion_r1550046959
> types: make RsbuildPluginAPI readonly

- examples/react/rsbuild.config.ts
- packages/core/src/index.ts
- packages/document/docs/en/api/javascript-api/types.mdx
- packages/document/docs/zh/api/javascript-api/types.mdx
Export more hook fn types, such as `ModifyBundlerChainFn` and `ModifyRspackConfigFn`.
> types: export more hook fn types

- e2e/cases/plugin-api/plugin-transform/index.test.ts
- e2e/cases/plugin-api/plugin-transform/myPlugin.ts
- packages/core/src/rspack/transformLoader.ts
- packages/shared/src/types/plugin.ts
Add emitFile to transform API:
```js
api.transform({ test: /\.js$/ }, ({ code, emitFile }) => {
emitFile('static/hello.txt', 'hello world');
return {
code: code.replace('hello', 'world'),
};
});
```
> feat: add emitFile to transform API

- packages/document/docs/en/index.md
- packages/document/docs/zh/index.md
- packages/document/rspress.config.ts
Generate both rss and atom types to support more RSS readers, such as https://www.inoreader.com/
https://github.com/web-infra-dev/rspress/issues/828
> docs: generate both rss and atom types

- packages/document/package.json
- pnpm-lock.yaml
Bump Rspress v1.17.1 to fix RSS.
- https://github.com/web-infra-dev/rspress/releases/tag/v1.17.1
- https://github.com/web-infra-dev/rspress/issues/828
> chore: bump Rspress v1.17.1 to fix RSS

- packages/core/src/plugins/networkPerformance.ts
Skip `performance.prenonnect` and `performance.dnsPrefetch` when HTML is disabled.
> fix: skip prenonnect when HTML is disabled

- e2e/cases/html-tags/basic/index.test.ts
- e2e/cases/html-tags/basic/rsbuild.config.ts
- packages/shared/src/url.ts
- Input:
```js
html: {
tags: [
{
tag: 'link',
attrs: {
rel: 'preconnect',
href: 'https://example.com',
},
},
],
},
});
```
- Current output:
```html
<link ref="preconnect" href="https://example.com/">
```
- Expected output:
```html
<link ref="preconnect" href="https://example.com">
```
> fix: avoid adding unexpected trailing slash to href

- e2e/cases/resolve-pkg-imports/index.test.ts
- e2e/cases/resolve-pkg-imports/package.json
- e2e/cases/resolve-pkg-imports/src/common/test.js
- e2e/cases/resolve-pkg-imports/src/foo.js
- e2e/cases/resolve-pkg-imports/src/index.js
- pnpm-lock.yaml
Add E2E case for package.json#imports.
- https://github.com/web-infra-dev/rsbuild/issues/2000
- https://nodejs.org/docs/latest/api/packages.html#imports
> test(e2e): add case for package.json#imports

- e2e/cases/stats/stats-options/index.test.ts
- e2e/cases/stats/stats-options/src/App.scss
- e2e/cases/stats/stats-options/src/index.tsx
- packages/compat/webpack/src/core/createCompiler.ts
- packages/core/src/plugins/fileSize.ts
- packages/core/src/provider/createCompiler.ts
- packages/core/src/provider/index.ts
- packages/core/src/provider/shared.ts
- packages/shared/src/types/stats.ts
some [stats options](https://www.rspack.dev/config/stats.html) can be worked in Rsbuild, such as stats.preset / errors / warnings / children. 
default value:
```
{
preset: 'errors-warnings',
children: true,
}
```
before:
after:
> feat: support apply some stats options

- e2e/cases/decorator/2022-03/index.test.ts
Fix the confusing decorator error logs when running E2E cases.
https://github.com/web-infra-dev/rsbuild/pull/2018#issuecomment-2041970215
> test(e2e): fix confusing decorator error logs

- e2e/cases/source/jsconfig-paths/index.test.ts
- e2e/cases/source/jsconfig-paths/jsconfig.json
- e2e/cases/source/jsconfig-paths/src/common/test.js
- e2e/cases/source/jsconfig-paths/src/common2/test.js
- e2e/cases/source/jsconfig-paths/src/index.js
Add case for jsconfig#paths, see #2000
https://github.com/web-infra-dev/rsbuild/issues/2000
> test(e2e): add case for jsconfig#paths

- e2e/cases/babel/decorator/index.test.ts
- e2e/cases/babel/decorator/src/jsIndex.js
1. small fix: import the file 'jsDecorator.js'
2. test -> rspackOnlyTest
in webpack we use [uni-builder:babel](https://github.com/web-infra-dev/modern.js/blob/8a63297a72e93fc23335fbaae5aaed4a9cd693ae/packages/cli/uni-builder/src/webpack/plugins/babel.ts#L40) instead of @rsbuild/plugin-babel and already be tested [here](https://github.com/web-infra-dev/rsbuild/blob/a9a8eb085a286e135e4691d8b41ca080d74fcade/packages/babel-preset/tests/node.test.ts#L25)
no
> test(e2e/plugin-babel): babel/decorator test -> rspackOnlyTest

- packages/document/docs/en/guide/migration/cra.mdx
- packages/document/docs/zh/guide/migration/cra.mdx
Add reading jsconfig.json guide to CRA migration guide.
https://github.com/web-infra-dev/rsbuild/issues/2000
> docs: add reading jsconfig.json guide

- packages/core/src/client/hmr/createSocketUrl.ts
- packages/core/src/client/hmr/index.ts
- packages/core/src/client/hmr/types.d.ts
- packages/core/src/provider/devMiddleware.ts
- packages/core/src/server/compilerDevMiddleware.ts
- packages/shared/src/types/config/dev.ts
- packages/shared/src/types/server.ts
Allow to use error overlay when hmr is disabled:
```js
dev: {
client: {
overlay: true,
},
hmr: false,
},
});
```
> fix: allow to use error overlay when hmr is disabled

- packages/core/package.json
- packages/plugin-lightningcss/package.json
- packages/plugin-react/package.json
- packages/shared/package.json
- pnpm-lock.yaml
Bump Rspack v0.6.0.
https://github.com/web-infra-dev/rspack/releases/tag/v0.6.0
> feat: bump Rspack v0.6.0

- e2e/cases/server/overlay/rsbuild.config.ts
- packages/core/src/provider/config.ts
- packages/document/docs/en/config/dev/client.mdx
- packages/document/docs/zh/config/dev/client.mdx
Starting from v0.6, the default value of `dev.client.overlay` is `true`. This means that the error overlay is displayed by default when there are compilation errors.
You can disable it by setting `dev.client.overlay` to `false`:
```js
dev: {
client: {
overlay: false,
},
},
});
```
https://github.com/web-infra-dev/rsbuild/discussions/1970
> feat: enable error overlay by default

- e2e/cases/server/dev.test.ts
- e2e/cases/server/port/index.test.ts
- e2e/cases/server/port/src/index.js
Fix the unstable server.port case:
> test(e2e): fix unstable server.port case

- packages/core/src/provider/shared.ts
Change rspack min version to 0.6.0 because Rsbuild now uses the new CSS modules generator config.
> fix: change rspack min version to 0.6.0

- packages/plugin-lightningcss/package.json
- packages/plugin-lightningcss/src/loader.ts
- packages/plugin-lightningcss/src/minimizer.ts
- pnpm-lock.yaml
replace `@rspack/core` devDependencies with `type Rspack` from `@rsbuild/shared` in `@rsbuild/plugin-lightningcss`
none
> chore(plugin-lightningcss): remove @rspack/core devDependencies

- packages/core/src/provider/initPlugins.ts
- packages/document/docs/en/plugins/dev/core.mdx
- packages/document/docs/zh/plugins/dev/core.mdx
- packages/shared/src/types/plugin.ts
- `test`: matches module's path (without query), the same as Rspack's [Rule.test](https://rspack.dev/config/module#ruletest).
```js
api.transform({ test: /\.pug$/ }, ({ code }) => {
// ...
});
```
- `resourceQuery`: matches module's query, the same as Rspack's [Rule.resourceQuery](https://rspack.dev/config/module#ruleresourcequery).
```js
api.transform({ resourceQuery: /raw/ }, ({ code }) => {
// ...
});
```
> feat: support resourceQuery for transform API

- .changeset/many-cycles-end.md
- packages/plugin-solid/src/index.ts
- packages/plugin-solid/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/utils.ts
Only enable solid-refresh when target is web, use the `isUsingHMR` helper to detect whether is using HMR.
> fix(plugin-solid): only enable solid-refresh when target is web

- packages/compat/webpack/src/provider.ts
- packages/compat/webpack/src/shared.ts
- packages/core/src/createRsbuild.ts
- packages/core/src/plugins/index.ts
- packages/core/src/provider/provider.ts
- packages/core/src/provider/shared.ts
- packages/shared/src/types/plugin.ts
- packages/shared/src/types/provider.ts
- scripts/test-helper/src/rsbuild.ts
Simplify default plugins typing, we do not need to passing the default plugins list to provider and do not need to maintain the  default plugins typing.
> chore: simplify default plugins typing

- e2e/cases/plugin-api/plugin-modify-tags/myPlugin.ts
- packages/core/src/rspack/HtmlBasicPlugin.ts
- packages/shared/src/types/config/html.ts
- packages/shared/src/types/hooks.ts
Simplify tag interface for modifyHTMLTags, align typing with `html.tags` config.
> chore: simplify tag interface for modifyHTMLTags

- packages/compat/plugin-swc/src/utils.ts
- packages/core/src/provider/plugins/swc.ts
- packages/plugin-babel/src/helper.ts
- packages/shared/src/types/config/output.ts
fix https://github.com/web-infra-dev/rsbuild/issues/2091.
Related https://github.com/web-infra-dev/modern.js/pull/5642. Since modern.js used a fixed version Rsbuild, we could merge this directly.
> chore: remove "ua" type in "output.polyfill"

- packages/document/docs/en/community/releases/v0-1.mdx
- packages/document/docs/en/community/releases/v0-2.mdx
- packages/document/docs/en/community/releases/v0-3.mdx
- packages/document/docs/en/community/releases/v0-4.mdx
- packages/document/docs/en/community/releases/v0-5.mdx
- packages/document/docs/en/community/releases/v0-6.mdx
- packages/document/docs/en/index.md
- packages/document/docs/zh/community/releases/v0-1.mdx
- packages/document/docs/zh/community/releases/v0-2.mdx
- packages/document/docs/zh/community/releases/v0-3.mdx
- packages/document/docs/zh/community/releases/v0-4.mdx
- packages/document/docs/zh/community/releases/v0-5.mdx
- packages/document/docs/zh/community/releases/v0-6.mdx
- packages/document/docs/zh/index.md
- packages/document/rspress.config.ts
Use `https://assets.rspack.dev/` to host assets. The `rsfamily-design-resources.netlify.app` is no longer used because it might be blocked in some areas.
> docs: update assets domain

- packages/shared/src/logger.ts
https://github.com/web-infra-dev/rsbuild/blob/00a598f0095fd53cb309102757a58c89f416107b/packages/shared/src/logger.ts#L3-L8
logger.level is set too early to be affected by `process.env.DEBUG`
So it cannot be used like this
```ts
import { build } from '@rsbuild/core';
function main() {
process.env.DEBUG = 'rsbuild';
build();
process.env.DEBUG = ''
}
main()
```
and in some cases of devServer e2e, we need some logs of the server
https://github.com/web-infra-dev/rsbuild/pull/2115
> chore(@rsbuild/shared): set logger.level in isDebug() function

- packages/compat/webpack/src/core/webpackConfig.ts
- packages/core/src/plugins/moment.ts
- packages/core/src/provider/rspackConfig.ts
- packages/core/src/provider/shared.ts
- packages/document/docs/en/plugins/dev/hooks.mdx
- packages/document/docs/zh/plugins/dev/hooks.mdx
- packages/shared/src/types/hooks.ts
Use Rspack native IgnorePlugin instead of the current JS plugin.
https://github.com/web-infra-dev/rspack/pull/6166
> perf: use Rspack native IgnorePlugin

- packages/document/docs/en/guide/basic/unocss.mdx
- packages/document/docs/zh/guide/basic/unocss.mdx
https://github.com/unocss/unocss/pull/3740
> docs: update unocss config

- package.json
- pnpm-lock.yaml
Upgrade to pnpm v9 and use the new lock file version.
The lock file has been regenerated in this PR.
https://github.com/pnpm/pnpm/releases/tag/v9.0.0
> chore(workflow): upgrade to pnpm v9

- packages/core/src/client/overlay.ts
Fix failed access globalThis in legacy browsers, use window instead.
https://caniuse.com/?search=globalThis
> fix: failed access globalThis in legacy browsers

- e2e/cases/vue2/sfc-style/index.test.ts
- e2e/cases/vue2/sfc-style/src/App.vue
- packages/plugin-vue2/src/VueLoader15PitchFixPlugin.ts
- packages/plugin-vue2/src/index.ts
- packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/chain.ts
Case https://github.com/web-infra-dev/rsbuild/actions/runs/8741123011/job/23986414872?pr=2142
Since I have no idea about the current maintenance status of vue-loader@15, I create this quick fix plugin as an alternative of https://github.com/vuejs/vue-loader/pull/2071
fixes #2093
> fix(plugin-vue2): fix loaders duplicating problem caused by vue-loader@15

- e2e/cases/assets-retry/index.test.ts
fix the unstable e2e test
Possible reasons
1. race condition in runtime code (maybe not)
2. testRunner: devServer isolation of every runner
3. testRunner: logs isolation of every runner
4. Network environment
> test(e2e/plugin-assets-retry): fix the unstable request num

- packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
- packages/core/src/plugins/basic.ts
- packages/core/tests/__snapshots__/basic.test.ts.snap
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Ignore the CSS conflicting order warning by default.
- close https://github.com/web-infra-dev/rsbuild/issues/2088
- https://www.rspack.dev/blog/announcing-0.6.html#emit-warnings-when-css-order-is-inconsistent-in-multiple-chunks
> fix: ignore the CSS conflicting order warning by default

- e2e/cases/cli/function-config/index.test.ts
- e2e/cases/cli/inspect/index.test.ts
- e2e/cases/cli/node-env/index.test.ts
- e2e/cases/cli/reload-env/index.test.ts
`npx rsbuild build` is unstable because of shared `process.env` of parallel test runner
add `delete process.env.NODE_ENV`
> test(e2e): delete process.env.NODE_ENV to solve unstable e2e

- packages/core/src/plugins/startUrl.ts
Skip open in codesandbox.
After being bundled, the `open` package will try to call system xdg-open, which will cause an error on codesandbox.
https://github.com/sindresorhus/open/blob/2ea66da8e8b20880d235447cf4c94ba275da6a5a/index.js#L214-L227
https://github.com/codesandbox/codesandbox-client/issues/6642
> fix: skip open in codesandbox

- packages/core/src/client/hmr/index.ts
- packages/shared/src/types/config/dev.ts
- packages/shared/src/types/config/output.ts
- packages/shared/src/types/config/source.ts
- website/docs/en/config/dev/asset-prefix.mdx
- website/docs/en/config/output/asset-prefix.mdx
- website/docs/en/config/output/externals.mdx
- website/docs/en/config/output/filename.mdx
- website/docs/en/guide/debug/debug-mode.md
- website/docs/en/guide/faq/features.md
- website/docs/en/guide/optimization/build-performance.mdx
- website/docs/en/guide/optimization/split-chunk.md
- website/docs/en/guide/start/glossary.mdx
- website/docs/en/plugins/dev/index.md
- website/docs/en/plugins/list/plugin-styled-components.mdx
- website/docs/zh/config/output/externals.mdx
- website/docs/zh/config/output/filename.mdx
- website/docs/zh/guide/debug/debug-mode.md
- website/docs/zh/guide/faq/features.md
- website/docs/zh/guide/optimization/build-performance.mdx
- website/docs/zh/guide/optimization/split-chunk.md
- website/docs/zh/guide/start/glossary.mdx
- website/docs/zh/plugins/dev/index.md
- website/docs/zh/plugins/list/plugin-styled-components.mdx
Link more content to Rspack website instead of the webpack website.
> docs: link more content to Rspack website

- .npmrc
- e2e/cases/babel/decorator/index.test.ts
- packages/plugin-vue/package.json
- pnpm-lock.yaml
1. add `vue` to provide peer dep for vue-loader
2. tweak babel-loader cwd to help finding `@babel/preset-env`
> chore: remove pnpm hoist pattern

- e2e/cases/react/enable-profiler/index.test.ts
- e2e/cases/react/enable-profiler/rsbuild.config.ts
- e2e/cases/react/enable-profiler/src/App.jsx
- e2e/cases/react/enable-profiler/src/index.js
- packages/plugin-react/src/index.ts
- packages/plugin-react/src/react.ts
- website/docs/en/plugins/list/plugin-react.mdx
Adds support for profiling React components against a production build. This is a good use case for profiling an app when running preview in localhost.
- [CRA Profiling](https://create-react-app.dev/docs/production-build/#profiling)
> feat(plugin-react): enable support for profiling React in prod env

- packages/core/src/server/proxy.ts
- packages/shared/src/types/config/server.ts
- website/docs/en/config/server/proxy.mdx
- website/docs/zh/config/server/proxy.mdx
proxy bypass support return `true` to continue processing the request without proxy.
```
server: {
proxy: {
'/api': {
target: 'http://xxxx/',
bypass: (req) => {
// not proxy when request like /api/no-proxy/xxxx
if (req.url.includes('/no-proxy')) {
return true;
}
}
}
}
}
});
```
> feat: proxy bypass support return true

- packages/core/src/provider/shared.ts
should not log compile warning when warning length is 0 (use ignoreWarning)
fix: https://github.com/web-infra-dev/rsbuild/issues/2165
> fix: should not log compile warning when warning is ignored

- e2e/cases/performance/load-resource/index.test.ts
- e2e/cases/source/alias-by-target/index.test.ts
- e2e/cases/source/multiple-entry/index.test.ts
- e2e/scripts/helper.ts
`globContentJSON` could be written in concurrent async logic, and some test case need to be changed to prevent uncertain result in race-condition when running concurrently.
> test(e2e): use concurrent instead of serial for globContentJSON

- pnpm-lock.yaml
- website/docs/en/index.md
- website/docs/zh/index.md
- website/package.json
Bump Rspress 1.18.3 and add title suffix to homepage.
https://github.com/web-infra-dev/rspress/releases/tag/v1.18.3
> docs: bump Rspress 1.18.3 and add title suffix

- e2e/package.json
- examples/node/package.json
- packages/compat/babel-preset/package.json
- packages/compat/webpack/package.json
- packages/core/package.json
- packages/create-rsbuild/package.json
- packages/monorepo-utils/package.json
- packages/plugin-babel/package.json
- packages/plugin-css-minimizer/package.json
- packages/plugin-image-compress/package.json
- packages/plugin-lightningcss/package.json
- packages/plugin-preact/package.json
- packages/plugin-react/package.json
- packages/plugin-styled-components/package.json
- packages/plugin-svelte/package.json
- packages/plugin-svgr/package.json
- packages/shared/package.json
- pnpm-lock.yaml
- scripts/check-changeset/package.json
- scripts/prebundle/package.json
- scripts/test-helper/package.json
- website/package.json
bump @types/node to v18 to fix:
> chore: bump @types/node to v18

- e2e/cases/server/public-dir/publicDir.test.ts
- examples/vue2/rsbuild.config.ts
- packages/core/src/config.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/watchFiles.ts
- packages/shared/src/types/config/dev.ts
- packages/shared/src/types/config/server.ts
- website/docs/en/config/server/public-dir.mdx
- website/docs/zh/config/server/public-dir.mdx
support watch publicDir in dev
set `watch: true`, page will reload when watch file content changed.
```
server: {
publicDir: {
watch: true,
},
},
``` 
#1903
> feat(server): support watch publicDir in dev

- website/docs/en/api/javascript-api/instance.mdx
- website/docs/en/api/start/index.mdx
- website/docs/en/config/server/https.mdx
- website/docs/en/guide/start/npm-packages.mdx
- website/docs/en/plugins/list/_meta.json
- website/docs/en/plugins/list/index.md
- website/docs/en/plugins/list/plugin-basic-ssl.mdx
- website/docs/zh/api/javascript-api/instance.mdx
- website/docs/zh/api/start/index.mdx
- website/docs/zh/config/server/https.mdx
- website/docs/zh/guide/start/npm-packages.mdx
- website/docs/zh/plugins/list/_meta.json
- website/docs/zh/plugins/list/index.md
- website/docs/zh/plugins/list/plugin-basic-ssl.mdx
Add plugin-basic-ssl document.
https://github.com/web-infra-dev/rsbuild/pull/2176
> docs: add plugin-basic-ssl document

- packages/plugin-check-syntax/src/CheckSyntaxPlugin.ts
当 output.filename 为以下配置时，CheckSyntaxPlugin 匹配不到资源文件，进而导致失效了
```
filename: {
js: '[name].js?v=[contenthash:8]',
css: '[name].css?v=[contenthash:8]',
svg: '[name].svg?=[contenthash:8]',
font: '[name][ext]?v=[contenthash:8]',
image: '[name][ext]?v=[contenthash:8]',
media: '[name][ext]?v=[contenthash:8]'
},
```
> fix(plugin-check-syntax): allow to match assets with query

- packages/plugin-react/src/index.ts
- packages/plugin-react/src/react.ts
- website/docs/en/plugins/list/plugin-react.mdx
- website/docs/zh/plugins/list/plugin-react.mdx
Support for configuring react refresh plugin.
```js
pluginReact({
reactRefreshOptions: {
exclude: [/some-module-to-exclude/],
},
});
```
https://github.com/web-infra-dev/rsbuild/issues/2185
> feat(plugin-react): support for configuring react refresh plugin

- e2e/cases/assets-retry/index.test.ts
- e2e/cases/assets-retry/src/App.tsx
- packages/plugin-assets-retry/scripts/postCompile.js
- packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
- packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
- packages/plugin-assets-retry/src/index.ts
- packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
- packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
- packages/plugin-assets-retry/src/types.ts
- packages/plugin-assets-retry/tests/__snapshots__/assetsRetry.test.ts.snap
- packages/plugin-assets-retry/tests/assetsRetry.test.ts
- packages/shared/package.json
- packages/shared/src/chain.ts
- packages/shared/src/rspack.ts
1. implement asyncChunkRetry rspack plugin based on compilation.hooks.runtimeModule https://github.com/web-infra-dev/rspack/pull/5370
2. design based on https://github.com/mattlewis92/webpack-retry-chunk-load-plugin
We will rewrite `__webpack_require__.ensureChunk` and `__webpack_require.loadScript` to achieve this feature.
1. `__webpack_require__.ensureChunk` is a way how webpack loads async chunks and it returns a promise. We intercepted the error of this Promise.
2. `__webpack_require__.loadScript` is to calculate the request url and it defines the `src` of `<script>` and we intercepted the url calculation
close #91
> feat(plugin-asset-retry): support async chunk retry

- .changeset/few-lobsters-yell.md
- packages/core/src/index.ts
- packages/core/src/plugins/moduleFederation.ts
- packages/core/src/provider/build.ts
- packages/core/src/provider/createCompiler.ts
- packages/core/src/provider/plugins/minimize.ts
- packages/core/src/provider/plugins/output.ts
- packages/core/src/provider/plugins/progress.ts
- packages/core/src/provider/plugins/rspackProfile.ts
- packages/core/src/provider/rspackConfig.ts
- packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
- packages/shared/package.json
- packages/shared/src/rspack.ts
- packages/shared/src/types/config/tools.ts
- website/docs/en/api/javascript-api/core.mdx
- website/docs/en/api/javascript-api/instance.mdx
- website/docs/en/config/tools/rspack.mdx
- website/docs/en/plugins/dev/hooks.mdx
- website/docs/zh/api/javascript-api/core.mdx
- website/docs/zh/api/javascript-api/instance.mdx
- website/docs/zh/config/tools/rspack.mdx
- website/docs/zh/plugins/dev/hooks.mdx
Export the rspack object from core.
So users can directly refer to this object from `@rsbuild/core` without the need to install the `@rspack/core` dependency separately.
- **Type:** `Rspack`
- **Example:**
```ts
import { rspack } from '@rsbuild/core';
console.log(rspack.rspackVersion); // 1.0.0
console.log(rspack.util.createHash);
```
> feat(core): export the rspack object

- packages/core/package.json
- pnpm-lock.yaml
The prebundle should be devDependencies of `@rsbuild/core`.
> fix(core): prebundle should be devDependencies

- e2e/cases/plugin-api/plugin-transform-by-targets/index.test.ts
- e2e/cases/plugin-api/plugin-transform-by-targets/myPlugin.ts
- e2e/cases/plugin-api/plugin-transform-by-targets/rsbuild.config.ts
- e2e/cases/plugin-api/plugin-transform-by-targets/src/index.js
- packages/core/src/initPlugins.ts
- packages/shared/src/types/plugin.ts
- website/docs/en/plugins/dev/core.mdx
- website/docs/zh/plugins/dev/core.mdx
Supports use targets as a filter of the transform API.
```js
api.transform({ test: /\.pug$/, targets: ['web'] }, ({ code }) => {
// ...
});
```
> feat: supports use targets as a filter of the transform API

- packages/core/src/initPlugins.ts
- packages/core/src/rspack/transformRawLoader.ts
- packages/shared/src/types/plugin.ts
- website/docs/en/plugins/dev/core.mdx
- website/docs/zh/plugins/dev/core.mdx
if raw is `true`, the transform handler will receive the Buffer type code instead of the string type.
```js
api.transform({ test: /\.node$/, raw: true }, ({ code }) => {
// ...
});
```
> feat: support receive raw Buffer code with transform API

- e2e/cases/css/css-modules-named-export/index.test.ts
- e2e/cases/css/css-modules-named-export/src/a.module.css
- e2e/cases/css/css-modules-named-export/src/b.module.scss
- e2e/cases/css/css-modules-named-export/src/c.module.less
- e2e/cases/css/css-modules-named-export/src/index.js
- website/docs/en/guide/basic/css-modules.md
- website/docs/zh/guide/basic/css-modules.md
Add CSS modules named imports example and test case.
> docs: CSS modules named imports example

- website/docs/en/guide/basic/css-modules.mdx
- website/docs/zh/guide/basic/css-modules.mdx
Improve CSS modules type declaration.
When using named imports, it is hard to define a complete type declaration for CSS modules, so we can use a looser declaration.
> docs: improve CSS modules type declaration

- e2e/cases/assets-retry/index.test.ts
- packages/plugin-assets-retry/src/index.ts
- packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
- packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
some fixes
1. `onFail` or `onSuccess` would be triggered every time when retry succeed or failed, after merge this pull request, they will be trigged only once
2. pass the original error message, by https://github.com/web-infra-dev/rsbuild/pull/2200#issuecomment-2076897250
3. add more e2e cases
https://github.com/web-infra-dev/rsbuild/pull/2200
https://github.com/web-infra-dev/rsbuild/pull/2086#issuecomment-2076555980
> fix(plugin-assets-retry): execute onSuccess onFail once in async-chunk-retry

- packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
- packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
`string.endsWith` is es6 API and can be replaced with `nextDomain[nextDomain.length - 1] === '/'`.
Also renamed some variables to make the bundle smaller(asyncChunkRetry.min.js 2,995 bytes -> 2,849 bytes)
https://caniuse.com/?search=endsWith
> fix(assets-entry): string.endsWith compatibility issue

- e2e/cases/server/dev.test.ts
Should not use fixed port number in e2e test, it will fail if the port is used.
> test(e2e): should not use fixed port number

- packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
- packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
- packages/plugin-assets-retry/src/index.ts
- packages/plugin-assets-retry/tests/__snapshots__/assetsRetry.test.ts.snap
- website/docs/en/plugins/list/plugin-assets-retry.mdx
- website/docs/zh/plugins/list/plugin-assets-retry.mdx
Should use unminified assets retry code in dev builds.
https://github.com/web-infra-dev/rsbuild/pull/1978
> fix(asset-retry): should use unminified code in dev builds

- e2e/cases/assets-retry/index.test.ts
- e2e/package.json
- pnpm-lock.yaml
case 1. `18:09:23 404 GET /static/js/index.js.map 4.443 ms`
case 2. `18:09:23 404 GET /static/js/index.js 1.440 ms`
> test(e2e/plugin-assets-retry): fix windows unstable test caused by log parse

- packages/core/src/client/formatStats.ts
Fallback to `stats.moduleName` if `stats.moduleIdentifier` parse failed.
> fix(overlay): fallback to moduleName if moduleIdentifier parse failed

- packages/core/src/client/hmr/index.ts
- packages/core/src/client/overlay.ts
Fix failed to display overlay when use MF. Rsbuild should only close overlay when the compilation hash changed.
Reproduction: https://github.com/rspack-contrib/rspack-examples/pull/58
> fix: failed to display overlay when use MF

- .changeset/happy-fishes-cover.md
- packages/core/src/client/formatStats.ts
- packages/core/src/client/hmr/index.ts
- packages/core/src/client/hmr/url.ts
- packages/core/src/client/overlay.ts
Ship less client code by refactoring the client code and remove some outdated code.
For example, remove `typeof console` because we do not need to compatible with IE9:  https://github.com/facebook/create-react-app/pull/2301
> refactor: ship less client code

- packages/core/src/server/devServer.ts
- packages/core/src/server/getDevMiddlewares.ts
- packages/core/src/server/middlewares.ts
get outputFileSystem via compiler.outputFileSystem, no need depend on webpack-dev-middleware#res.locals.webpack
> chore(server): get outputFileSystem via compiler.outputFileSystem

- packages/compat/plugin-swc/src/plugin.ts
- packages/core/modern.config.ts
- packages/core/src/plugins/target.ts
- packages/core/src/provider/plugins/swc.ts
- packages/shared/src/chain.ts
- ship runtime code in es2017 by default
- use SWC to transform the runtime code if user target < es2017
> feat: ship runtime code in es2017 by default

- packages/core/tests/server.test.ts
- packages/shared/src/utils.ts
fix node compiler.name check error, the compiler.name is `Server` instead of `server`.
> fix(hmr): should not register node compiler event

- scripts/dictionary.txt
- website/docs/en/config/module-federation/options.mdx
- website/docs/en/config/source/define.mdx
- website/docs/en/guide/start/glossary.mdx
- website/docs/zh/config/module-federation/options.mdx
- website/docs/zh/config/source/define.mdx
- website/docs/zh/guide/start/glossary.mdx
Fix broken Rspack plugin links and update MF glossary.
> docs: fix broken plugin links and update MF glossary

- .changeset/swift-experts-taste.md
- packages/core/package.json
- packages/plugin-assets-retry/package.json
- packages/plugin-rem/package.json
- packages/shared/package.json
- pnpm-lock.yaml
`lodash.template` will generate `_.escape()` and can not work as expected:
Revert to lodash.
See: https://github.com/rspack-contrib/html-rspack-plugin/pull/8
> fix: lodash is not defined error

- e2e/cases/performance/print-file-size/index.test.ts
- examples/react/rsbuild.config.ts
- packages/core/src/plugins/fileSize.ts
Should print dist folder correctly if it's not a subdir of root.
- before:
- after:
> fix: print dist folder correctly if it's not a subdir of root

- website/docs/en/guide/basic/_meta.json
- website/docs/en/guide/basic/cli.mdx
- website/docs/en/guide/basic/static-deploy.mdx
- website/docs/zh/guide/basic/_meta.json
- website/docs/zh/guide/basic/cli.mdx
- website/docs/zh/guide/basic/static-deploy.mdx
Add basic deploy static site guide and GitHub Pages deployment example
https://github.com/web-infra-dev/rsbuild/issues/780
> docs: add basic deploy static site guide

- .changeset/stale-bags-double.md
- packages/shared/package.json
- packages/shared/prebundle.config.mjs
- pnpm-lock.yaml
Fix failed to resolve fsevents when using chokidar.
The `fsevents` is an optional dependency of `chokidar`, and `chokidar` is prebundled by `@rsbuild/shared`. So we should add it add an `optionalDependencies` of `@rsbuild/shared`.
> fix: failed to resolve fsevents when using chokidar

- .changeset/nine-tips-draw.md
- packages/plugin-svgr/prebundle.config.mjs
Fix failed to resolve file-loader, because we removed the minify step of prebundle and the file-loader path replacement can not work as expected.
https://github.com/web-infra-dev/rsbuild/issues/1238
> fix(plugin-svgr): failed to resolve file-loader

- e2e/cases/check-syntax/index.test.ts
Enable skipped check assets case as the bug has been fixed, see https://github.com/web-infra-dev/rspack/issues/6366
> test(e2e): enable skipped check assets case

- e2e/cases/output/manifest/index.test.ts
- e2e/cases/output/manifest/src/index.ts
- packages/compat/webpack/src/provider.ts
- packages/core/package.json
- packages/core/prebundle.config.mjs
- packages/core/src/config.ts
- packages/core/src/plugins/index.ts
- packages/core/src/plugins/manifest.ts
- packages/core/src/provider/provider.ts
- packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
- packages/core/src/rspack/preload/helpers/doesChunkBelongToHtml.ts
- packages/core/src/rspack/preload/helpers/extractChunks.ts
- packages/core/tests/__snapshots__/inspect.test.ts.snap
- packages/shared/src/types/config/output.ts
- pnpm-lock.yaml
- website/docs/en/config/output/manifest.mdx
- website/docs/zh/config/output/manifest.mdx
support generator manifest file
usage:
```js
output: {
manifest: true,
},
};
```
output:
```
{
"allFiles": [
"/static/css/index.a11cfb11.css",
"/static/js/index.c586cd5e.js",
"/index.html",
"/static/js/index.c586cd5e.js.LICENSE.txt"
],
"entries": {
"index": {
"initial": {
"js": ["/static/js/index.c586cd5e.js"],
"css": ["/static/css/index.a11cfb11.css"]
},
"async": {
"js": [],
"css": []
},
"assets": ["/static/js/index.c586cd5e.js.LICENSE.txt"],
"html": "/index.html"
}
}
}
```
fix: https://github.com/web-infra-dev/rsbuild/issues/989
> feat: support `output.manifest` config

- .changeset/polite-rules-kneel.md
- packages/core/package.json
- packages/plugin-react/package.json
- packages/shared/package.json
- pnpm-lock.yaml
Bump Rspack v0.6.5 to fix some critical bugs, see: https://github.com/web-infra-dev/rspack/releases/tag/v0.6.5
> fix(deps): bump Rspack v0.6.5

- e2e/cases/source/entry-depend-on/index.test.ts
- e2e/cases/source/entry-depend-on/rsbuild.config.ts
- e2e/cases/source/entry-depend-on/src/bar.js
- e2e/cases/source/entry-depend-on/src/baz.js
- e2e/cases/source/entry-depend-on/src/foo.js
- packages/core/src/plugins/html.ts
Should inject chunks to HTML when using  `entry.dependOn`.
```js
source: {
entry: {
foo: './src/foo.js',
bar: {
dependOn: 'foo',
import: './src/bar.js',
},
baz: {
dependOn: ['foo', 'bar'],
import: './src/baz.js',
},
},
},
};
```
Expected `baz.html`:
```html
<!doctype html>
<html>
<head>
<title>Rsbuild App</title>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<script defer="defer" src="/static/js/foo.js"></script>
<script defer="defer" src="/static/js/bar.js"></script>
<script defer="defer" src="/static/js/baz.js"></script>
</head>
<body>
<div id="root"></div>
</body>
</html>
```
https://github.com/web-infra-dev/rsbuild/discussions/2290
> fix(html): should inject chunks for entry.dependOn

- e2e/cases/assets-retry/index.test.ts
- e2e/cases/assets-retry/src/testQueryEntry.js
- packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
- packages/plugin-assets-retry/src/index.ts
- packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
- packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
- packages/plugin-assets-retry/src/types.ts
- packages/plugin-assets-retry/tests/__snapshots__/assetsRetry.test.ts.snap
- packages/plugin-assets-retry/tests/assetsRetry.test.ts
- website/docs/en/plugins/list/plugin-assets-retry.mdx
- website/docs/zh/plugins/list/plugin-assets-retry.mdx
support `addQuery` option in `@rsbuild/plugin-assets-retry`
Here are some examples: 
1. no query, `<script src="https://cdn.com/a.js"></script>`
after set `addQuery: true`, if the resource requests failed, we would retry with query like below
```
// if failed, retry the next line 
https://cdn.com/a.js?retry=1
https://cdn.com/a.js?retry=2
https://cdn.com/a.js?retry=3
```
2. with query, `<script src="https://cdn.com/a.js?version=1"></script>`
after set `addQuery: true`, if the resource request failed, we would retry with query like below
```
// if failed, retry the next line 
https://cdn.com/a.js?version=1&retry=1
https://cdn.com/a.js?version=1&retry=2
https://cdn.com/a.js?version=1&retry=3
```
3. with anchor, `<script src="https://cdn.com/a.js?version=1#title"></script>`
```
// if failed, …
```
> feat(plugin/assets-retry): support addQuery option

- e2e/cases/assets-retry/index.test.ts
- packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
- packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
- packages/plugin-assets-retry/src/types.ts
- packages/plugin-assets-retry/tests/assetsRetry.test.ts
- website/docs/en/plugins/list/plugin-assets-retry.mdx
- website/docs/zh/plugins/list/plugin-assets-retry.mdx
Passing addQuery params in object format, this makes it easier for us to add more parameters in the future.
```ts
// before
addQuery?: boolean | ((times: number, originalQuery: string) => string);
// after
addQuery?: boolean | ((context: { times: number; originalQuery: string }) => string);
```
https://github.com/web-infra-dev/rsbuild/pull/2277
> chore(assets-retry): passing addQuery params in object format

- .github/renovate.json5
- package.json
- pnpm-lock.yaml
- Ignore pnpm in renovate config, so we can upgrade pnpm manually.
- Remove unused dts-packer config.
> chore(deps): ignore pnpm in renovate config

- packages/shared/src/utils.ts
Fix server hook not trigger when target is others, only target node is excluded because ssr HMR is not supported yet.
> fix: server hooks not trigger when target is others

- website/docs/en/guide/framework/react.mdx
- website/docs/en/guide/framework/solid.mdx
- website/docs/en/guide/framework/svelte.mdx
- website/docs/en/guide/framework/vue2.mdx
- website/docs/en/shared/deployApp.mdx
- website/docs/zh/guide/framework/react.mdx
- website/docs/zh/guide/framework/solid.mdx
- website/docs/zh/guide/framework/svelte.mdx
- website/docs/zh/guide/framework/vue2.mdx
- website/docs/zh/shared/deployApp.mdx
Remove the outdated deploy guide, as we have provided a better guide in:  https://rsbuild.dev/guide/basic/static-deploy
> docs: remove outdated deploy guide

- packages/core/src/client/format.ts
`Array.prototype.at` not exist on legacy browsers, we should avoid using it.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility
> fix(client): Array.prototype.at not exist on legacy browsers

- .changeset/breezy-baboons-jump.md
- packages/shared/src/chain.ts
Fix core-js accidentally compiled in some cases.
- resolve https://github.com/web-infra-dev/rsbuild/issues/2323
- https://github.com/web-infra-dev/rsbuild/discussions/2318
> fix: core-js accidentally compiled in some cases

- packages/core/src/plugins/performance.ts
- website/docs/en/config/performance/profile.mdx
- website/docs/en/guide/debug/build-profiling.mdx
- website/docs/zh/config/performance/profile.mdx
- website/docs/zh/guide/debug/build-profiling.mdx
Make the document of `performance.profile` more clear, sometimes we are confused about the difference between it and RSPACK_PROFILE.
> docs: make performance.profile more clear

- e2e/cases/css/css-modules/index.test.ts
- packages/core/tests/css.test.ts
- website/docs/en/config/output/css-modules.mdx
- website/docs/zh/config/output/css-modules.mdx
since we use CssExtractRspackPlugin to extract CSS, localIdentName hashDigest has been supported in rspack mode.
https://github.com/web-infra-dev/rsbuild/pull/1577
> docs: localIdentName hashDigest has been supported in rspack mode

- packages/plugin-assets-retry/package.json
- packages/plugin-assets-retry/scripts/postCompile.mjs
- packages/plugin-image-compress/src/types/index.ts
- scripts/modern.base.config.ts
Rsbuild uses Modern.js Module to build packages, and it uses `rollup-plugin-dts` to generate dts files by default. But the `rollup-plugin-dts` can not perform a full type checking and does not have complete type generating supports (for example, cannot handle namespace).
This PR changed the build config and uses tsc for type checking and dts generation.
> chore(build): enable full type check and fix type issue

- e2e/cases/performance/print-file-size/rsbuild.config.ts
- packages/core/src/provider/plugins/swc.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/core/tests/__snapshots__/swc.test.ts.snap
- packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
- packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
- packages/plugin-preact/src/index.ts
- packages/plugin-react/src/react.ts
- packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
- website/docs/en/config/tools/swc.mdx
- website/docs/zh/config/tools/swc.mdx
The `jsc.parser.tsx` option should only be enabled in React / Preact projects, otherwise SWC will transform JSX with React syntax in non-React projects, and users might get confused.
https://github.com/web-infra-dev/rsbuild/discussions/2328
> fix: only enable React JSX compilation when using React plugin

- packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
- packages/core/tests/__snapshots__/asset.test.ts.snap
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/plugin-image-compress/tests/__snapshots__/index.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
- packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
- packages/shared/src/constants.ts
- website/docs/en/config/output/data-uri-limit.mdx
- website/docs/zh/config/output/data-uri-limit.mdx
The default value for `output.dataUriLimit` is changed from `10000 (10kB)` to `4096 (4KiB)`.
This is because more applications are currently using HTTP2.0, so splitting assets into separate files would perform better. Meanwhile, inlining assets over 4KiB can make the JS bundle to be too large and not cache-friendly.
https://github.com/web-infra-dev/rsbuild/discussions/2271
> feat: output.dataUriLimit defaults to 4096

- website/docs/en/plugins/list/_meta.json
- website/docs/en/plugins/list/index.mdx
- website/docs/en/plugins/list/plugin-typed-css-modules.mdx
- website/docs/zh/plugins/list/_meta.json
- website/docs/zh/plugins/list/index.mdx
- website/docs/zh/plugins/list/plugin-typed-css-modules.mdx
add document for `@rsbuild/plugin-typed-css-modules`.
https://github.com/web-infra-dev/rsbuild/pull/2340
> docs: introduce typed-css-modules plugin

- e2e/cases/rem/basic/index.test.ts
Fix regexp for matching rem script name:
https://github.com/web-infra-dev/rsbuild/actions/runs/9082225121/job/24958031046
> test(e2e): fix regexp for matching rem script name

- packages/core/bin/rsbuild.js
- packages/core/src/cli/prepare.ts
- packages/shared/package.json
- packages/shared/prebundle.config.mjs
- packages/shared/src/logger.ts
Remove rslog from the prebundle config to fix the ESM / CJS interop problem.
rslog is written in ESM and compiled to ESM + CJS, if we use `prebundle` to bundle it into CJS and then import the compiled rslog in an ESM file, it turns out to be a mess and we cannot get the correct exports.
So we just remove rslog from the prebundle config and it works fine.
> fix: remove rslog from prebundle config

- packages/core/prebundle.config.mjs
- packages/shared/package.json
- packages/shared/prebundle.config.mjs
- pnpm-lock.yaml
Reduce exports of the shared package. Some exports are only used by `@rsbuild/core` and can be removed.
> chore: reduce exports of the shared package

- packages/core/src/plugins/splitChunks.ts
- packages/core/tests/__snapshots__/splitChunks.test.ts.snap
fix: increase priority split-by-module so it can differ from defaultVendors
Webpack's defaultVendors priority is -10, so the priority of defaultVendors and vendors are the same, in some case, module will be in defaultVendors chunk, not vendor chunk
> fix: increase priority split-by-module so it can differ from defaultVendors

- packages/core/package.json
- packages/plugin-react/package.json
- packages/shared/package.json
- pnpm-lock.yaml
https://github.com/web-infra-dev/rspack/releases/tag/v0.7.0-beta.0
> chore(deps): bump rspack to 0.7.0-beta.0

- packages/compat/webpack/src/createCompiler.ts
- packages/core/src/provider/createCompiler.ts
- packages/core/src/server/devMiddleware.ts
After merging https://github.com/web-infra-dev/rsbuild/pull/2361, an unexpected rebuild will occur when Rspress starts:
Then I found that lazy import webpack-dev-middleware can solve this issue, this may be some side effects of webpack-dev-middleware on fs.
This PR lazy import webpack-dev-middleware to fix this issue.
> fix: lazy import webpack-dev-middleware

- packages/compat/webpack/src/inspectConfig.ts
- packages/core/src/createRsbuild.ts
- packages/core/src/pluginManager.ts
- packages/core/src/provider/inspectConfig.ts
- packages/core/tests/createPluginManager.test.ts
- packages/shared/src/types/plugin.ts
- packages/shared/src/types/rsbuild.ts
- scripts/test-helper/src/rsbuild.ts
- website/docs/en/api/javascript-api/instance.mdx
- website/docs/zh/api/javascript-api/instance.mdx
Add `rsbuild.getPlugins` JavaScript API, this API can be used for testing or some other scenarios.
For example, replace the current implementation of [createStubRsbuild](https://github.com/web-infra-dev/rsbuild/blob/1500f2e/scripts/test-helper/src/rsbuild.ts).
> feat: add rsbuild.getPlugins JavaScript API

- packages/core/src/helpers.ts
- packages/core/src/provider/rspackConfig.ts
- packages/shared/src/types/hooks.ts
- Reduce fs calls caused by getCompiledPath.
- Remove `getCompiledPath` from chain utils, as it is an internal API.
> perf: reduce fs calls caused by getCompiledPath

- packages/shared/src/types/config/output.ts
- packages/shared/src/types/thirdParty.ts
- website/docs/en/config/output/css-modules.mdx
- website/docs/zh/config/output/css-modules.mdx
Fix missing resourceQuery param of `cssLoader.module.auto`
https://github.com/webpack-contrib/css-loader?tab=readme-ov-file#auto
> fix: missing resourceQuery param of cssLoader.module.auto

- e2e/cases/vue/sfc-css-modules/index.test.ts
- e2e/cases/vue/sfc-css-modules/rsbuild.config.ts
- e2e/cases/vue/sfc-css-modules/src/A.vue
- e2e/cases/vue/sfc-css-modules/src/index.js
- e2e/cases/vue/sfc-css-modules/src/style.module.css
- packages/plugin-vue/src/index.ts
Support CSS Modules in SFC:
```html
<template>
<p id="test1" :class="{ [$style.red]: isRed }">Red</p>
</template>
<script>
setup() {
return {
isRed: true,
};
},
};
</script>
<style module>
.red {
color: red;
}
</style>
```
https://vuejs.org/api/sfc-css-features.html#css-modules
https://github.com/web-infra-dev/rsbuild/issues/1425
> feat(plugin-vue): support CSS Modules in SFC

- e2e/cases/css/postcss-config-ts/index.test.ts
- e2e/cases/css/postcss-config-ts/postcss.config.ts
- e2e/cases/css/postcss-config-ts/rsbuild.config.ts
- e2e/cases/css/postcss-config-ts/src/index.css
- e2e/cases/css/postcss-config-ts/src/index.html
- e2e/cases/css/postcss-config-ts/src/index.ts
- e2e/cases/css/postcss-config-ts/tailwind.config.cjs
- packages/core/prebundle.config.mjs
Fix failed to load postcss.config.ts.
Let the `postcss-load-config` to use the `jiti` exported by `@rsbuild/shared`, so it can transform `postcss.config.ts` as expected.
> fix: failed to load postcss.config.ts

- e2e/cases/css/configure-css-extract/index.test.ts
- e2e/cases/css/configure-css-extract/rsbuild.config.ts
- e2e/cases/css/configure-css-extract/src/index.css
- e2e/cases/css/configure-css-extract/src/index.js
- packages/core/src/config.ts
- packages/core/src/plugins/css.ts
- packages/core/src/plugins/output.ts
- packages/shared/package.json
- packages/shared/src/chain.ts
- packages/shared/src/types/config/tools.ts
- packages/shared/src/types/thirdParty.ts
- pnpm-lock.yaml
- website/docs/en/config/tools/css-extract.mdx
- website/docs/zh/config/tools/css-extract.mdx
Add a new `tools.cssExtract` config to configure the options of CssExtractRspackPlugin.
https://www.rspack.dev/plugins/rspack/css-extract-rspack-plugin
> feat: support tools.cssExtract config

- packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
- packages/core/src/plugins/basic.ts
- packages/core/tests/__snapshots__/basic.test.ts.snap
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Remove unused ignoreWarnings config, because Rsbuild have enabled the `ignoreOrder` option of  CssExtractRspackPlugin.
> chore: remove unused ignoreWarnings config

- packages/compat/webpack/src/provider.ts
- packages/core/src/provider/provider.ts
- packages/core/src/server/devServer.ts
- packages/core/src/server/helper.ts
- packages/core/src/server/prodServer.ts
- packages/core/tests/server.test.ts
Use the normalized Rsbuild config to create dev server or prod server, which is more type-friendly.
> chore: use normalized config to create server

- packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
- packages/plugin-sass/package.json
- packages/plugin-sass/src/index.ts
- packages/plugin-sass/src/types.ts
- packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
- pnpm-lock.yaml
sass-loader v14.2.0 added the `modern-compiler` value for API to reuse compiler process.
Using the `modern-compiler` value for the api option together with `sass-embedded` reduces compilation time by 5-10 times, especially for projects using large files with a lot of `@import/@use`, for small files the build time reduction will not be significant.
https://github.com/webpack-contrib/sass-loader/releases/tag/v14.2.0
> perf(plugin-sass): defaults to sass-embedded and modern API

- packages/core/package.json
- packages/plugin-react/package.json
- packages/shared/package.json
- pnpm-lock.yaml
bump Rspack 0.7.0-beta.2
https://github.com/web-infra-dev/rspack/releases/tag/v0.7.0-beta.2
> chore(deps): bump Rspack 0.7.0-beta.2

- e2e/cases/css/less-plugin-hints/index.test.ts
- e2e/cases/css/less-plugin-hints/src/a.less
- e2e/cases/css/less-plugin-hints/src/index.js
- e2e/cases/css/sass-plugin-hints/index.test.ts
- e2e/cases/css/sass-plugin-hints/src/a.scss
- e2e/cases/css/sass-plugin-hints/src/index.js
- e2e/cases/css/stylus-plugin-hints/index.test.ts
- e2e/cases/css/stylus-plugin-hints/src/a.styl
- e2e/cases/css/stylus-plugin-hints/src/index.js
- packages/core/src/client/format.ts
- packages/core/src/helpers.ts
Print hints for CSS preprocessors plugins, this could help users to migrate to Rsbuild v0.7.
> feat: print hints for CSS preprocessors plugins

- e2e/cases/vue/sfc-lang-pcss/index.test.ts
- e2e/cases/vue/sfc-lang-pcss/rsbuild.config.ts
- e2e/cases/vue/sfc-lang-pcss/src/App.vue
- e2e/cases/vue/sfc-lang-pcss/src/index.js
- e2e/cases/vue/sfc-lang-postcss/index.test.ts
- e2e/cases/vue/sfc-lang-postcss/rsbuild.config.ts
- e2e/cases/vue/sfc-lang-postcss/src/App.vue
- e2e/cases/vue/sfc-lang-postcss/src/index.js
- e2e/cases/vue2/sfc-lang-pcss/index.test.ts
- e2e/cases/vue2/sfc-lang-pcss/rsbuild.config.ts
- e2e/cases/vue2/sfc-lang-pcss/src/App.vue
- e2e/cases/vue2/sfc-lang-pcss/src/index.js
- e2e/cases/vue2/sfc-lang-postcss/index.test.ts
- e2e/cases/vue2/sfc-lang-postcss/rsbuild.config.ts
- e2e/cases/vue2/sfc-lang-postcss/src/App.vue
- e2e/cases/vue2/sfc-lang-postcss/src/index.js
- packages/plugin-vue/src/index.ts
- packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
- packages/plugin-vue2/src/index.ts
- packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap
- scripts/dictionary.txt
Support for lang="postcss" and lang="pcss" in Vue SFC.
https://vue-loader-v14.vuejs.org/en/features/postcss.html
> feat(plugin-vue): support for lang="postcss"

- e2e/cases/umd/split-chunks/index.test.ts
- e2e/cases/umd/split-chunks/rsbuild.config.ts
- e2e/cases/umd/split-chunks/src/index.html
- e2e/cases/umd/split-chunks/src/index.js
- packages/plugin-umd/src/index.ts
- website/docs/en/plugins/list/plugin-umd.mdx
- website/docs/zh/plugins/list/plugin-umd.mdx
Allow to configure chunk split strategy when using the UMD plugin. This can be used by Garfish (a micro frontend framework) users.
> feat(plugin-umd): allow to configure chunk split strategy

- website/docs/en/api/javascript-api/core.mdx
- website/docs/en/api/javascript-api/instance.mdx
- website/docs/en/api/javascript-api/types.mdx
- website/docs/zh/api/javascript-api/core.mdx
- website/docs/zh/api/javascript-api/instance.mdx
- website/docs/zh/api/javascript-api/types.mdx
- website/tsconfig.json
Add `rsbuild.initConfigs` to document and update some outdated descriptions in the API docs.
> docs: add rsbuild.initConfigs to document

- e2e/cases/css/lightningcss/index.test.ts
- packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
- packages/core/src/plugins/css.ts
- packages/core/tests/__snapshots__/builder.test.ts.snap
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/plugin-lightningcss/src/plugin.ts
- packages/plugin-react/tests/__snapshots__/index.test.ts.snap
This PR moves internal CSS rule and lightningcss-loader forward to the pre stage. So that the lightningcss-loader can be applied to sass/less/stylus rules and users do not need to care about the registration order of these plugins.
> fix(plugin-lightningcss): ensure works with CSS preprocessors

- packages/core/src/server/devServer.ts
- packages/core/src/server/httpServer.ts
- packages/core/src/server/prodServer.ts
- packages/shared/src/types/config/server.ts
- website/docs/en/config/server/https.mdx
- website/docs/zh/config/server/https.mdx
Support for HTTP/2 server, it will be enabled by default when configuring `server.https` or using the `@rsbuild/plugin-basic-ssl`.
> feat(server): support for HTTP/2

- e2e/cases/server/print-urls/index.test.ts
- packages/core/src/server/prodServer.ts
The `rsbuild preview` command should not print network URLs when `host: 'localhost'` is set.
> fix: preview command print invalid URL

- e2e/cases/eslint/flat-config/rsbuild.config.ts
- packages/plugin-eslint/package.json
- pnpm-lock.yaml
- website/docs/en/plugins/list/plugin-eslint.mdx
- website/docs/zh/plugins/list/plugin-eslint.mdx
Make ESLint as a peer dependency, this allows user to choose to use ESLint v8 or v9.
> fix(plugin-eslint): make ESLint as a peer dependency

- e2e/cases/browserslist/browserslist-config-mock/index.json
- e2e/cases/browserslist/browserslist-config-mock/package.json
- e2e/cases/browserslist/extends-browserslist/index.test.ts
- e2e/cases/browserslist/extends-browserslist/package.json
- e2e/cases/browserslist/extends-browserslist/rsbuild.config.ts
- e2e/cases/browserslist/extends-browserslist/src/index.js
- packages/shared/prebundle.config.mjs
- pnpm-lock.yaml
Fix browserslist resolve is broken by prebundle.
This PR is part of fixes to support `extends` in browserslist config, see https://github.com/web-infra-dev/rsbuild/issues/2443
We still need to support `extends` in the Rust (Rspack) side.
> fix: browserslist resolve is broken by prebundle

- packages/core/src/plugins/css.ts
- packages/shared/src/types/thirdParty.ts
Update css-loader modules typing to match the current implementation.
https://github.com/webpack-contrib/css-loader?tab=readme-ov-file#modules
> fix: update css-loader modules typing

- packages/plugin-sass/src/index.ts
export PluginSassOptions type, so other pkgs can used.
> types(plugin-sass): export PluginSassOptions type

- e2e/cases/lazy-compilation/basic/index.test.ts
- e2e/cases/lazy-compilation/basic/rsbuild.config.ts
- e2e/cases/lazy-compilation/basic/src/page1/App.jsx
- e2e/cases/lazy-compilation/basic/src/page1/index.js
- e2e/cases/lazy-compilation/basic/src/page2/App.jsx
- e2e/cases/lazy-compilation/basic/src/page2/index.js
- packages/core/src/createRsbuild.ts
- packages/core/src/plugins/lazyCompilation.ts
- packages/core/tests/__snapshots__/inspect.test.ts.snap
- packages/shared/src/types/config/dev.ts
Add `dev.lazyCompilation` config. It is a light wrapper to make Rspack's lazy compilation works in Rsbuild.
https://www.rspack.dev/config/experiments#experimentslazycompilation
> feat: add dev.lazyCompilation config

- package.json
- pnpm-lock.yaml
- website/package.json
- website/rspress.config.ts
Bump Rspress v1.22.0.
https://github.com/web-infra-dev/rspress/releases/tag/v1.22.0
> chore(deps): bump Rspress v1.22.0

- .changeset/tiny-donkeys-search.md
- packages/core/src/plugins/lazyCompilation.ts
Exclude all CSS lazy compilation as Rspack's lazy compilation does not support all CSS files with CSSExtractRspackPlugin yet.
> fix: exclude all CSS lazy compilation

- e2e/cases/css/css-modules-mode/index.test.ts
- e2e/cases/css/css-modules-mode/src/a.module.css
- e2e/cases/css/css-modules-mode/src/index.js
- packages/core/src/plugins/css.ts
- packages/shared/src/types/config/output.ts
- website/docs/en/config/output/css-modules.mdx
- website/docs/zh/config/output/css-modules.mdx
Add cssModules.mode option, which is the same as the `modules.mode` option of css-loader.
> feat: add cssModules.mode option

- packages/core/src/client/format.ts
Avoid printing undefined file path when using the `plugin-type-check`:
TODO: should get `stats.moduleName` when using Rspack + fork-ts-checker.
> fix: avoid printing undefined file path

- packages/core/src/provider/build.ts
The `compiler.close` method can accepts an error. Rsbuild should log it to notify users.
> feat: print compiler close errors

- e2e/cases/css/resolve-ts-paths/index.test.ts
- e2e/cases/css/resolve-ts-paths/rsbuild.config.ts
- e2e/cases/css/resolve-ts-paths/src/a.scss
- e2e/cases/css/resolve-ts-paths/src/common/b.scss
- e2e/cases/css/resolve-ts-paths/src/index.ts
- e2e/cases/css/resolve-ts-paths/tsconfig.json
- e2e/scripts/helper.ts
This is a failed case because the current js loader uses an enhanced resolver, which causes resolve.tsconfig to not work with the js loader.
see: https://github.com/web-infra-dev/rspack/issues/4672
> test: add css resolve-ts-paths test case

- website/docs/en/config/tools/swc.mdx
- website/docs/en/guide/framework/react.mdx
- website/docs/zh/config/tools/swc.mdx
- website/docs/zh/guide/framework/react.mdx
Recommend using `@swc/plugin-emotion`. `rspackExperiments.emotion` will be removed in Rspack v1.0.
https://github.com/web-infra-dev/rspack/discussions/6626#discussioncomment-9593912
> docs: recommend using @swc/plugin-emotion

- scripts/config/modern.config.ts
- scripts/config/tsconfig.json
Change node build target to ES2021.
The same as https://github.com/web-infra-dev/rspack/pull/6628
> chore: node build target to ES2021

- e2e/cases/css/css-modules-named-export/index.test.ts
- packages/core/src/config.ts
- packages/core/src/plugins/css.ts
- packages/shared/src/types/config/output.ts
- website/docs/en/config/output/css-modules.mdx
- website/docs/en/config/output/externals.mdx
- website/docs/en/config/tools/css-loader.mdx
- website/docs/zh/config/output/css-modules.mdx
- website/docs/zh/config/output/externals.mdx
- website/docs/zh/config/tools/css-loader.mdx
Allow to enable namedExport for CSS Modules.
https://github.com/webpack-contrib/css-loader?tab=readme-ov-file#namedexport
> feat: allow to enable namedExport for CSS Modules

- packages/plugin-babel/src/plugin.ts
Run babel loader before builtin SWC loader, and avoid transforming JS modules with SWC twice.
https://github.com/rspack-contrib/rspack-examples/issues/87
https://stackoverflow.com/questions/32234329/what-is-the-loader-order-for-webpack
> fix(plugin-babel): run babel loader before builtin SWC loader

- e2e/cases/react/react-compiler-babel/index.test.ts
- e2e/cases/react/react-compiler-babel/package.json
- e2e/cases/react/react-compiler-babel/rsbuild.config.ts
- e2e/cases/react/react-compiler-babel/src/App.jsx
- e2e/cases/react/react-compiler-babel/src/index.js
- pnpm-lock.yaml
Add E2E case for React compiler
https://github.com/rspack-contrib/rspack-examples/issues/87
> test(e2e): add case for React compiler

- website/docs/en/plugins/list/plugin-sass.mdx
- website/docs/zh/plugins/list/plugin-sass.mdx
Add tip for Sass legacy API.
https://github.com/webpack-contrib/sass-loader?tab=readme-ov-file#api
> docs(plugin-sass): add tip for legacy API

- scripts/dictionary.txt
- website/docs/en/guide/basic/_meta.json
- website/docs/en/guide/basic/upgrade-rsbuild.mdx
- website/docs/zh/guide/basic/_meta.json
- website/docs/zh/guide/basic/upgrade-rsbuild.mdx
Add guide for upgrading Rsbuild, using taze.
https://github.com/antfu-collective/taze?tab=readme-ov-file
> docs: add guide for upgrading Rsbuild

- packages/core/src/createRsbuild.ts
- packages/core/src/rspack/HtmlBasicPlugin.ts
- packages/shared/src/types/hooks.ts
- website/docs/en/plugins/dev/hooks.mdx
- website/docs/zh/plugins/dev/hooks.mdx
Allow to access compilation in modifyHTMLTags hook.
This can be used to get assets and calc SRI hash.
> feat: allow to access compilation in modifyHTMLTags hook

- packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
- packages/core/src/plugins/output.ts
- packages/core/tests/__snapshots__/default.test.ts.snap
- packages/core/tests/__snapshots__/output.test.ts.snap
Use [output.library.type](https://www.rspack.dev/config/output#outputlibrarytype)  instead of  [output.libraryTarget](https://www.rspack.dev/config/output#outputlibrarytarget) , both `output.library.type` and `output.libraryTarget` can configure how the library is exposed, but `output.libraryTarget` is not recommended, and `output.libraryTarget` configuration priority is higher than `output.library.type`. 
If rsbuild uses `output.libraryTarget`, it means that the `output.library.type` set by the user will not take effect.
> feat: support override library type config when target is node

- packages/core/src/createRsbuild.ts
- packages/core/src/plugins/html.ts
- packages/core/src/plugins/nonce.ts
- packages/core/tests/__snapshots__/inspect.test.ts.snap
Separate nonce plugin from html plugin to make the html plugin easier to maintain.
> chore: separate nonce plugin from html plugin

- packages/plugin-lightningcss/src/index.ts
- packages/plugin-lightningcss/src/loader.ts
- packages/plugin-lightningcss/src/minimizer.ts
- packages/plugin-lightningcss/src/plugin.ts
- packages/plugin-lightningcss/src/types.ts
- website/docs/en/config/security/nonce.mdx
- website/docs/en/config/security/sri.mdx
- website/docs/en/plugins/list/plugin-lightningcss.mdx
- website/docs/zh/plugins/list/plugin-lightningcss.mdx
- Only validate in setup stage for `plugin-lightningcss`.
- Reduce `any` in code.
- Export `PLUGIN_LIGHTNINGCSS_NAME` constant.
> perf(plugin-lightningcss): only validate in setup stage

- packages/compat/plugin-swc/src/minimizer.ts
- packages/compat/plugin-swc/src/plugin.ts
- packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
- packages/plugin-lightningcss/src/minimizer.ts
- apply lightningcss minify to the correct stage (`compilation.PROCESS_ASSETS_STAGE_OPTIMIZE_SIZE` is undefined)
- change the minimizer ID of SWC minimizers in webpack mode, so it can be override as expected.
> fix: apply lightningcss minify to the correct stage

- .changeset/empty-flies-own.md
- e2e/cases/configure-rspack/index.test.ts
- packages/core/src/provider/rspackConfig.ts
- packages/shared/src/reduceConfigs.ts
- packages/shared/src/types/config/tools.ts
- website/docs/en/config/tools/rspack.mdx
- website/docs/zh/config/tools/rspack.mdx
Allow `tools.rspack` to be async function.
https://github.com/web-infra-dev/rsbuild/issues/2503
> feat: allow tools.rspack to be async function

- e2e/cases/bundler-chain/index.test.ts
- packages/shared/src/chain.ts
- packages/shared/src/types/config/tools.ts
- website/docs/en/config/tools/bundler-chain.mdx
- website/docs/en/guide/basic/configure-rspack.mdx
- website/docs/zh/config/tools/bundler-chain.mdx
- website/docs/zh/guide/basic/configure-rspack.mdx
Allow `tools.bundlerChain` to be async function.
same as https://github.com/web-infra-dev/rsbuild/pull/2515
> feat: allow tools.bundlerChain to be async function

- e2e/cases/exports-presence/index.test.ts
- website/docs/en/guide/faq/exceptions.mdx
- website/docs/zh/guide/faq/exceptions.mdx
Enable the exports presence E2E case as Rspack 0.7.1 supports it.
https://github.com/web-infra-dev/rspack/pull/6660
> test(e2e): enable exports presence case

- e2e/cases/lazy-compilation/basic/index.test.ts
- packages/core/src/plugins/lazyCompilation.ts
- website/tsconfig.json
No longer need to exclude global entry when using the Rspack lazy compilation.
https://github.com/web-infra-dev/rspack/pull/6674
> chore(lazy-compilation): no need to exclude global entry

- packages/compat/webpack/src/index.ts
- packages/compat/webpack/src/types.ts
- packages/compat/webpack/src/webpackConfig.ts
- packages/core/src/plugins/asset.ts
- packages/core/src/plugins/css.ts
- packages/core/src/plugins/manifest.ts
- packages/core/src/plugins/splitChunks.ts
- packages/core/src/rspack/HtmlBasicPlugin.ts
- packages/plugin-css-minimizer/src/index.ts
- packages/shared/package.json
- packages/shared/prebundle.config.mjs
- packages/shared/src/chain.ts
- packages/shared/src/config.ts
- packages/shared/src/types/bundlerConfig.ts
- packages/shared/src/types/config/tools.ts
- packages/shared/src/types/hooks.ts
- packages/shared/src/types/plugin.ts
- packages/shared/src/types/utils.ts
- pnpm-lock.yaml
webpack-chain is no longer maintained and the types are outdated.
So we forked `webpack-chain` as `rspack-chain` and import types from `@rspack/core`.
Currently, the API of rspack-chain are exactly the same as webpack-chain. Some Rspack-specific APIs will be added in the future.
https://github.com/rspack-contrib/rspack-chain
https://github.com/neutrinojs/webpack-chain/issues/358
> chore: replace webpack-chain with rspack-chain

- e2e/cases/server/public-dir/publicDir.test.ts
Add two cases for public dir, the dev.assetPrefix and output.assetPrefix will not affect assets in the public dir.
https://github.com/web-infra-dev/rsbuild/discussions/2534
> test(e2e): add two cases for public dir

- packages/core/src/plugins/startUrl.ts
- packages/core/tests/startUrl.test.ts
- packages/shared/src/url.ts
- website/docs/en/config/dev/start-url.mdx
- website/docs/zh/config/dev/start-url.mdx
Support open with specified path.
- Open the specified path, equivalent to `http://localhost:<port>/home`:
```js
dev: {
startUrl: '/home',
},
};
```
> feat: support open with specified path

- e2e/cases/filename-function/index.test.ts
- e2e/cases/filename-function/rsbuild.config.ts
- e2e/cases/filename-function/src/async.css
- e2e/cases/filename-function/src/async.js
- e2e/cases/filename-function/src/index.css
- e2e/cases/filename-function/src/index.js
- packages/core/src/plugins/output.ts
- packages/shared/src/fs.ts
- packages/shared/src/types/config/output.ts
- website/docs/en/config/output/filename.mdx
- website/docs/zh/config/output/filename.mdx
Allow `output.filename.js` to be a function.
Except for `output.filename.js`, other types of files currently do not support using functions.
https://github.com/web-infra-dev/rsbuild/issues/2526
> feat: allow output.filename.js to be a function
